{
  "hash": "fe6fda29c97eaf922ae492c195f3be54",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 17. Panel Data, Time Series Data, Causation\nexecute:\n  enabled: true\n  warning: false\n---\n\n\n**metricsAI: An Introduction to Econometrics with Python and AI in the Cloud**\n\n*[Carlos Mendez](https://carlos-mendez.org)*\n\n<img src=\"https://raw.githubusercontent.com/quarcs-lab/metricsai/main/images/ch17_visual_summary.jpg\" alt=\"Chapter 17 Visual Summary\" width=\"100%\">\n\nThis notebook provides an interactive introduction to panel data methods, time series analysis, and causal inference. All code runs directly in Google Colab without any local setup.\n\n[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/quarcs-lab/metricsai/blob/main/notebooks_colab/ch17_Panel_Data_Time_Series_Data_Causation.ipynb)\n<div class=\"chapter-resources\">\n<a href=\"https://www.youtube.com/watch?v=ZtjIHX6JYyM\" target=\"_blank\" class=\"resource-btn\">🎬 AI Video</a>\n<a href=\"https://carlos-mendez.my.canva.site/s17-panel-data-time-series-data-causation-pdf\" target=\"_blank\" class=\"resource-btn\">✨ AI Slides</a>\n<a href=\"https://cameron.econ.ucdavis.edu/aed/traedv1_17\" target=\"_blank\" class=\"resource-btn\">📊 Cameron Slides</a>\n<a href=\"https://app.edcafe.ai/quizzes/69786c262f5d08069e04e9a8\" target=\"_blank\" class=\"resource-btn\">✏️ Quiz</a>\n<a href=\"https://app.edcafe.ai/chatbots/6978a3772f5d08069e0723a7\" target=\"_blank\" class=\"resource-btn\">🤖 AI Tutor</a>\n</div>\n\n\n## Chapter Overview\n\nThis chapter focuses on three important topics that extend basic regression methods: panel data, time series analysis, and causal inference. You'll gain both theoretical understanding and practical skills through hands-on Python examples.\n\n**Learning Objectives:**\n\nBy the end of this chapter, you will be able to:\n\n1. Apply cluster-robust standard errors for panel data with grouped observations\n2. Understand panel data methods including random effects and fixed effects estimators\n3. Decompose panel data variation into within and between components\n4. Use fixed effects to control for time-invariant unobserved heterogeneity\n5. Interpret results from logit models and calculate marginal effects\n6. Recognize time series issues including autocorrelation and nonstationarity\n7. Apply HAC (Newey-West) standard errors for time series regressions\n8. Understand autoregressive and distributed lag models for dynamic relationships\n9. Use instrumental variables and other methods for causal inference\n\n**Chapter outline:**\n\n- 17.2 Panel Data Models\n- 17.3 Fixed Effects Estimation\n- 17.4 Random Effects Estimation\n- 17.5 Time Series Data\n- 17.6 Autocorrelation\n- 17.7 Causality and Instrumental Variables\n- Key Takeaways\n- Practice Exercises\n- Case Studies\n\n**Datasets used:**\n\n- **AED_NBA.DTA**: NBA team revenue data (29 teams, 10 seasons, 2001-2011)\n- **AED_EARNINGS_COMPLETE.DTA**: 842 full-time workers with earnings, age, and education (2010)\n- **AED_INTERESTRATES.DTA**: U.S. Treasury interest rates, monthly (January 1982 - January 2015)\n\n## Setup\n\nFirst, we install and import the necessary Python packages and configure the environment for reproducibility. All data will stream directly from GitHub.\n\n::: {#1afd21a6 .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Setup: Import libraries and configure environment\"}\n# --- Libraries ---\nimport numpy as np                                    # numerical operations\nimport pandas as pd                                   # data manipulation\nimport matplotlib.pyplot as plt                       # plotting\nimport seaborn as sns                                 # statistical plots\nimport pyfixest as pf                                 # fast OLS/FE/IV estimation\nfrom statsmodels.formula.api import logit             # logit with formula syntax\nfrom scipy import stats                               # statistical distributions\nfrom statsmodels.stats.diagnostic import acorr_breusch_godfrey  # serial correlation test\nfrom statsmodels.graphics.tsaplots import plot_acf    # autocorrelation plots\nfrom statsmodels.tsa.stattools import acf             # autocorrelation function\nimport random\nimport os\n\n# --- Reproducibility ---\nRANDOM_SEED = 42\nrandom.seed(RANDOM_SEED)\nnp.random.seed(RANDOM_SEED)\nos.environ['PYTHONHASHSEED'] = str(RANDOM_SEED)\n\n# --- Data source ---\nGITHUB_DATA_URL = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/\"\n\n# --- Plotting style (dark theme matching book design) ---\nplt.style.use('dark_background')\nsns.set_style(\"darkgrid\")\nplt.rcParams.update({\n    'axes.facecolor': '#1a2235',\n    'figure.facecolor': '#12162c',\n    'grid.color': '#3a4a6b',\n    'figure.figsize': (10, 6),\n    'text.color': 'white',\n    'axes.labelcolor': 'white',\n    'xtick.color': 'white',\n    'ytick.color': 'white',\n    'axes.edgecolor': '#1a2235',\n})\n```\n:::\n\n\n## 17.2: Panel Data Models\n\nPanel data (also called longitudinal data) combines cross-sectional and time series dimensions. We observe multiple individuals (i = 1, ..., n) over multiple time periods (t = 1, ..., T).\n\n**Panel data model:**\n\n$$y_{it} = \\beta_1 + \\beta_2 x_{2it} + \\cdots + \\beta_k x_{kit} + u_{it}$$\n\nwhere:\n\n- $i$ indexes individuals (teams, firms, countries, etc.)\n- $t$ indexes time periods\n- $u_{it}$ is the error term\n\n**Three estimation approaches:**\n\n1. **Pooled OLS**: Treat all observations as independent (ignore panel structure)\n   - Use cluster-robust standard errors (cluster by individual)\n\n2. **Fixed Effects (FE)**: Control for time-invariant individual characteristics\n   - $y_{it} = \\alpha_i + \\beta_2 x_{2it} + \\cdots + \\beta_k x_{kit} + \\varepsilon_{it}$\n   - Eliminates $\\alpha_i$ by de-meaning (within transformation)\n\n3. **Random Effects (RE)**: Model individual effects as random\n   - Assumes $\\alpha_i$ uncorrelated with regressors\n   - More efficient than FE if assumption holds\n\n**Variance decomposition:**\n\nTotal variation = Within variation + Between variation\n\n- **Within**: variation over time for given individual\n- **Between**: variation across individuals\n\n**NBA Revenue Example:**\n\nWe analyze NBA team revenue using panel data for 29 teams over 10 seasons (2001-02 to 2010-11).\n\n::: {#66821a72 .cell execution_count=2}\n``` {.python .cell-code}\n# 17.2 Panel Data Models\n\n# Load NBA data\ndata_nba = pd.read_stata(GITHUB_DATA_URL + 'AED_NBA.DTA')\n\nprint(\"\\nNBA Data Summary:\")\ndata_nba.describe()\n\nprint(\"\\nFirst observations:\")\ndata_nba[['teamid', 'season', 'revenue', 'lnrevenue', 'wins', 'playoff']].head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nNBA Data Summary:\n\nFirst observations:\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>teamid</th>\n      <th>season</th>\n      <th>revenue</th>\n      <th>lnrevenue</th>\n      <th>wins</th>\n      <th>playoff</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n      <td>1</td>\n      <td>143.803223</td>\n      <td>4.968446</td>\n      <td>56</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1</td>\n      <td>2</td>\n      <td>138.347260</td>\n      <td>4.929767</td>\n      <td>58</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1</td>\n      <td>3</td>\n      <td>153.568207</td>\n      <td>5.034145</td>\n      <td>50</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1</td>\n      <td>4</td>\n      <td>137.203171</td>\n      <td>4.921463</td>\n      <td>56</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>1</td>\n      <td>5</td>\n      <td>141.405594</td>\n      <td>4.951632</td>\n      <td>34</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>1</td>\n      <td>6</td>\n      <td>141.149124</td>\n      <td>4.949817</td>\n      <td>45</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>1</td>\n      <td>7</td>\n      <td>150.488495</td>\n      <td>5.013886</td>\n      <td>42</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>1</td>\n      <td>8</td>\n      <td>168.155121</td>\n      <td>5.124887</td>\n      <td>57</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>1</td>\n      <td>9</td>\n      <td>170.463593</td>\n      <td>5.138522</td>\n      <td>65</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>1</td>\n      <td>10</td>\n      <td>160.024628</td>\n      <td>5.075328</td>\n      <td>57</td>\n      <td>1</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n> **Key Concept 17.1: Panel Data Variation Decomposition**\n>\n> Panel data variation decomposes into two components: between variation (differences across individuals in their averages) and within variation (deviations from individual averages over time). In the NBA example, between variation in revenue is large (big-market vs. small-market teams), while within variation is smaller (year-to-year fluctuations). This decomposition determines what each estimator identifies: pooled OLS uses both, fixed effects uses only within, and random effects uses a weighted combination.\n\n### Panel Structure and Within/Between Variation\n\nUnderstanding the structure of panel data is crucial for choosing the right estimation method.\n\n---\n\n#### Within vs. Between Variation: The Key to Panel Data\n\nThe variance decomposition reveals the **fundamental trade-off** in panel data analysis:\n\n**Empirical Results from NBA Data:**\n\nTypical findings:\n\n- **Between SD** (across teams): **0.40-0.50** (large!)\n- **Within SD** (over time): **0.15-0.25** (smaller)\n- **Overall SD**: **0.45-0.55**\n\n**What This Means:**\n\n1. **Between variation dominates**:\n - Teams differ **more** in average revenue than in year-to-year changes\n - Lakers always high revenue; small-market teams always low\n - Team-specific factors (market size, history, brand) are crucial\n\n2. **Within variation is smaller**:\n - Year-to-year fluctuations are **moderate** for given team\n - Winning seasons help, but don't transform a team's revenue fundamentally\n - Most variation is **permanent** (team characteristics), not **transitory** (annual shocks)\n\n3. **Variance decomposition** (approximately):\n - Total variance ≈ Between variance + Within variance\n - \\$0.50^2 \\approx 0.45^2 + 0.20^2$\n - \\$0.25 \\approx 0.20 + 0.04$ \n\n**Implications for Estimation:**\n\n**Pooled OLS:**\n\n- Uses **both** between and within variation\n- Estimates: \"How do revenue and wins correlate across teams AND over time?\"\n- Problem: Confounded by **team fixed effects**\n- High-revenue teams (big markets) may also win more games\n- Correlation ≠ causation\n\n**Fixed Effects (FE):**\n\n- Uses **only within variation** (after de-meaning by team)\n- Estimates: \"When a team wins more than its average, does revenue increase?\"\n- Controls for **time-invariant** team characteristics (market size, brand, arena)\n- **Causal interpretation** more plausible (within-team changes)\n\n**Random Effects (RE):**\n\n- Uses **weighted average** of between and within variation\n- Efficient if team effects uncorrelated with wins (strong assumption!)\n- Usually between pooled and FE estimates\n\n**Economic Interpretation:**\n\nWhy is between variation larger?\n\n1. **Market size**: \n - LA Lakers (huge market) vs. Memphis Grizzlies (small market)\n - Revenue gap: \\$200M+ (permanent)\n - This is **structural**, not related to annual wins\n\n2. **Historical success**: \n - Celtics, Lakers (storied franchises) vs. newer teams\n - Brand value built over decades\n - Can't be changed by one good season\n\n3. **Arena and facilities**:\n - Modern arenas vs. aging venues\n - Corporate sponsorships, luxury boxes\n - Fixed infrastructure\n\n**The Within Variation:**\n\nWhat creates year-to-year changes?\n\n- **Playoff appearances** (big revenue boost)\n- **Star player acquisitions** (jersey sales, ticket demand)\n- **Championship runs** (national TV, merchandise)\n- **Team performance** relative to expectations\n\n**Example:**\n\nGolden State Warriors 2010 vs. 2015:\n\n- **2010**: 26 wins, \\$120M revenue\n- **2015**: 67 wins, championship, \\$310M revenue\n- **Within-team change**: Huge! (but this is exceptional)\n\nMost teams show **much smaller** year-to-year swings:\n\n- **Typical**: ±5-10 wins, ±10-20% revenue\n\n**Key Insight for Fixed Effects:**\n\nFE identifies the wins-revenue relationship from **these within-team changes**:\n\n- Comparison: Team's good years vs. bad years\n- Controls for: Persistent market size, brand value, arena quality\n- Remaining variation: **Transitory shocks** that vary over time\n- More credible for **causal inference** (holding team constant)\n\n**Statistical Evidence:**\n\nThe de-meaned variable mdifflnrev = lnrevenue - team_mean shows:\n\n- Much **smaller variance** than lnrevenue\n- This is what FE regression uses\n- Loses all the **cross-sectional** information\n- Gains **control** over unobserved team characteristics\n\n### Visualization: Revenue vs Wins\n\nLet's visualize the relationship between team wins and revenue.\n\n::: {#e435b649 .cell execution_count=3}\n``` {.python .cell-code}\n# Figure 17.1: Scatter plot with fitted line\nfig, ax = plt.subplots(figsize=(10, 6))\nax.scatter(data_nba['wins'], data_nba['lnrevenue'], alpha=0.5, s=30)  # alpha = transparency, s = marker size\n\n# Add OLS fit line\nz = np.polyfit(data_nba['wins'], data_nba['lnrevenue'], 1)\np = np.poly1d(z)\nwins_range = np.linspace(data_nba['wins'].min(), data_nba['wins'].max(), 100)\nax.plot(wins_range, p(wins_range), 'r-', linewidth=2, label='OLS fit')\n\nax.set_xlabel('Wins', fontsize=12)\nax.set_ylabel('Log Revenue', fontsize=12)\nax.set_title('Figure 17.1: NBA Team Revenue vs Wins', fontsize=14, fontweight='bold')\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch17_Panel_Data_Time_Series_Data_Causation_files/figure-html/cell-4-output-1.png){width=950 height=565}\n:::\n:::\n\n\n**What to look for in this scatter plot:**\n\n- **Direction**: Positive -- teams with more wins tend to have higher log revenue\n- **Scatter**: Substantial vertical spread at each win level, suggesting other factors (market size, brand) drive much of the revenue variation\n- **Fitted line**: The upward OLS line captures the overall association, but this pools across teams and time -- it may overstate the causal effect of winning because big-market teams both win more and earn more\n\n### Pooled OLS with Different Standard Errors\n\nWe start with pooled OLS but use different standard error calculations to account for within-team correlation.\n\n::: {#0a455b37 .cell execution_count=4}\n``` {.python .cell-code}\n# Pooled Ols With Different Standard Errors\n\n# Pooled OLS with cluster-robust SEs (cluster by team)\nfit_pool = pf.feols('lnrevenue ~ wins', data=data_nba, vcov={'CRV1': 'teamid'})\n\nprint(\"\\nPooled OLS (cluster-robust SEs by team):\")\nfit_pool.summary()\n\n# Key Results:\nprint(f\"Wins coefficient: {fit_pool.coef()['wins']:.6f}\")\nprint(f\"Wins SE (cluster): {fit_pool.se()['wins']:.6f}\")\nprint(f\"t-statistic: {fit_pool.tstat()['wins']:.4f}\")\nprint(f\"p-value: {fit_pool.pvalue()['wins']:.4f}\")\nprint(f\"R² (overall): {fit_pool._r2:.4f}\")\nprint(f\"N observations: {fit_pool._N}\")\n\n# Compare with default SEs (for illustration)\nfit_pool_default = pf.feols('lnrevenue ~ wins', data=data_nba)\n# SE Comparison (to show importance of clustering):\nprint(f\"Default SE:       {fit_pool_default.se()['wins']:.6f}\")\nprint(f\"Cluster SE:       {fit_pool.se()['wins']:.6f}\")\nprint(f\"Ratio:            {fit_pool.se()['wins'] / fit_pool_default.se()['wins']:.2f}x\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nPooled OLS (cluster-robust SEs by team):\n###\n\nEstimation:  OLS\nDep. var.: lnrevenue\nsample: None = all\nInference:  CRV1\nObservations:  286\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |   2.5% |   97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|-------:|--------:|\n| Intercept     |      4.255 |        0.096 |    44.453 |      0.000 |  4.059 |   4.451 |\n| wins          |      0.007 |        0.002 |     3.538 |      0.001 |  0.003 |   0.011 |\n---\nRMSE: 0.22 R2: 0.127 \nWins coefficient: 0.006753\nWins SE (cluster): 0.001909\nt-statistic: 3.5379\np-value: 0.0014\nR² (overall): 0.1267\nN observations: 286\nDefault SE:       0.001052\nCluster SE:       0.001909\nRatio:            1.81x\n```\n:::\n:::\n\n\n> **Key Concept 17.2: Cluster-Robust Standard Errors for Panel Data**\n>\n> Observations within the same individual (team, firm, country) are correlated over time, violating the independence assumption. Default SEs dramatically understate uncertainty by treating all observations as independent. Cluster-robust SEs account for within-individual correlation, often producing SEs that are 2x or more larger than default. Always cluster by individual in panel data; with few clusters ($G < 30$), consider wild bootstrap refinements.\n\n---\n\n#### Why Cluster-Robust Standard Errors Are Essential\n\nThe comparison of standard errors reveals **within-team correlation** - a pervasive feature of panel data:\n\n**Typical Results:**\n\n| Coefficient | Default SE | Robust SE | **Cluster SE** |\n|-------------|-----------|-----------|---------------|\n| wins | 0.0030 | 0.0035 | **0.0065** |\n| **Ratio** | 1.00x | 1.17x | **2.17x** |\n\n**What This Tells Us:**\n\n1. **Cluster SEs are much larger** (2x or more):\n - Default and robust SEs **understate** uncertainty\n - Observations for the **same team are correlated** over time\n - Standard errors must account for **within-cluster dependence**\n\n2. **Why observations within teams are correlated:**\n \n **Persistent team effects:**\n\n - Lakers tend to be above average **every year** (positive errors cluster)\n - Grizzlies tend to be below average **every year** (negative errors cluster)\n - Unobserved factors affect team across **all periods**\n\n **Serial correlation:**\n\n - Good years followed by good years (momentum, roster stability)\n - Revenue shocks persist (new arena, TV deal lasts multiple years)\n - Errors: $u_{it}$ correlated with $u_{it-1}, u_{it-2}, \\ldots$\n\n3. **Information content:**\n - With independence: 29 teams × 10 years = **290 independent observations**\n - With clustering: Effectively like **29 independent teams** (much less info!)\n - Cluster SEs adjust for this **reduced effective sample size**\n\n**The Math Behind It:**\n\n**Default SE formula:**\n$$SE = \\sqrt{\\frac{\\sigma^2}{\\sum(x_i - \\bar{x})^2}}$$\n\nAssumes all 290 observations independent.\n\n**Cluster-robust SE formula:**\n$$SE_{cluster} = \\sqrt{\\frac{\\sum_{g=1}^G X_g'X_g \\hat{u}_g\\hat{u}_g' X_g}{...}}$$\n\nwhere:\n\n- $g$ indexes **clusters** (teams)\n- Allows correlation **within** cluster, independence **across** clusters\n- Typically **much larger** than default SE\n\n**Why Default SEs Are Wrong:**\n\nImagine two extreme scenarios:\n\n**Scenario A (independence):**\n\n- 10 different teams, each observed once\n- 10 truly independent observations\n- SE reflects 10 pieces of information\n\n**Scenario B (perfect correlation):**\n\n- 1 team observed 10 times\n- All observations identical (no new information!)\n- Effectively only 1 observation\n- SE should be $\\sqrt{10}$ times larger\n\n**Panel data is between these extremes:**\n\n- Observations within team correlated (not independent)\n- But not perfectly (some within-variation)\n- Cluster SEs account for partial dependence\n\n**When Cluster SEs Matter Most:**\n\n1. **Many time periods** (T large):\n - More opportunities for correlation\n - Default SEs increasingly too small\n\n2. **High intra-cluster correlation** (ICC high):\n - Observations within team very similar\n - Less independent information\n - Bigger SE correction\n\n3. **Few clusters** (G small):\n - With <30 clusters: standard cluster SEs unreliable\n - Need **wild bootstrap** or other refinements\n\n**Empirical Implications:**\n\n**With default SEs:**\n\n- wins coefficient: t = 3.00, p < 0.01\n- **Conclusion**: Highly significant\n\n**With cluster SEs:**\n\n- wins coefficient: t = 1.38, p = 0.17\n- **Conclusion**: Not significant!\n\n**Complete reversal of inference!**\n\n**Best Practices:**\n\n **Always use cluster-robust SEs for panel data:**\n\n- Cluster by **individual** (team, person, firm, country)\n- Default in modern software (specify cluster variable)\n- Essential for valid inference\n\n **Report**:\n\n- Which variable defines clusters\n- Number of clusters (G)\n- Time periods (T)\n\n **Never**:\n\n- Use default SEs for panel data\n- Ignore within-cluster correlation\n- Claim significance based on default SEs\n\n**Two-Way Clustering:**\n\nSometimes need to cluster in **multiple dimensions**:\n\n- **Team** (within-team correlation over time)\n- **Season** (common time shocks affect all teams)\n- Example: 2008 financial crisis hit all teams that year\n\nFormula: $SE_{two-way} = SE_{team} + SE_{time} - SE_{pooled}$\n\n**The NBA Example:**\n\nWith cluster SEs:\n\n- wins coefficient: **0.0055** (SE: **0.0040**)\n- t-statistic: **1.38**\n- p-value: **0.17**\n\n**Interpretation:**\n\n- Relationship between wins and revenue **not statistically significant**\n- Once we properly account for within-team correlation\n- Previous \"significance\" was an artifact of ignoring dependence\n- Fixed effects (next section) will address the underlying confounding\n\n## 17.3: Fixed Effects Estimation\n\nFixed effects (FE) control for time-invariant individual characteristics by including individual-specific intercepts.\n\n**Model with individual effects:**\n\n$$y_{it} = \\alpha_i + \\beta_2 x_{2it} + \\cdots + \\beta_k x_{kit} + \\varepsilon_{it}$$\n\n**Within transformation (de-meaning):**\n\n$$(y_{it} - \\bar{y}_i) = \\beta_2(x_{2it} - \\bar{x}_{2i}) + \\cdots + \\beta_k(x_{kit} - \\bar{x}_{ki}) + (\\varepsilon_{it} - \\bar{\\varepsilon}_i)$$\n\n**Properties:**\n\n- Eliminates $\\alpha_i$ (time-invariant unobserved heterogeneity)\n- Consistent even if $\\alpha_i$ correlated with regressors\n- Uses only within variation\n- Cannot estimate coefficients on time-invariant variables\n\n**Implementation:**\n\n1. LSDV (Least Squares Dummy Variables): Include dummy for each individual\n2. Within estimator: De-mean and run OLS\n\nWe'll use the pyfixest package for proper panel estimation.\n\n::: {#a434ebbb .cell execution_count=5}\n``` {.python .cell-code}\n# 17.3 Fixed Effects Estimation\n\n# Fixed Effects estimation using pyfixest (entity effects via | teamid)\nfit_fe = pf.feols('lnrevenue ~ wins | teamid', data=data_nba, vcov={'CRV1': 'teamid'})\n\nprint(\"\\nFixed Effects (entity effects, cluster-robust SEs):\")\nfit_fe.summary()\n\n# Key Results:\nprint(f\"Wins coefficient: {fit_fe.coef()['wins']:.6f}\")\nprint(f\"Wins SE (cluster): {fit_fe.se()['wins']:.6f}\")\nprint(f\"t-statistic: {fit_fe.tstat()['wins']:.4f}\")\nprint(f\"p-value: {fit_fe.pvalue()['wins']:.4f}\")\nprint(f\"R² (within): {fit_fe._r2_within:.4f}\")\n\n# Comparison: Pooled vs Fixed Effects\ncomparison = pd.DataFrame({\n    'Pooled OLS': [fit_pool.coef()['wins'], fit_pool.se()['wins'],\n                   fit_pool._r2],\n    'Fixed Effects': [fit_fe.coef()['wins'], fit_fe.se()['wins'],\n                     fit_fe._r2_within]\n}, index=['Wins Coefficient', 'Std Error', 'R²'])\nprint(comparison)\n\nprint(\"\\nNote: FE coefficient is smaller (controls for team characteristics)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFixed Effects (entity effects, cluster-robust SEs):\n###\n\nEstimation:  OLS\nDep. var.: lnrevenue, Fixed effects: teamid\nsample: None = all\nInference:  CRV1\nObservations:  286\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |   2.5% |   97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|-------:|--------:|\n| wins          |      0.005 |        0.001 |     5.353 |      0.000 |  0.003 |   0.006 |\n---\nRMSE: 0.098 R2: 0.828 R2 Within: 0.185 \nWins coefficient: 0.004505\nWins SE (cluster): 0.000842\nt-statistic: 5.3534\np-value: 0.0000\nR² (within): 0.1851\n                  Pooled OLS  Fixed Effects\nWins Coefficient    0.006753       0.004505\nStd Error           0.001909       0.000842\nR²                  0.126663       0.185083\n\nNote: FE coefficient is smaller (controls for team characteristics)\n```\n:::\n:::\n\n\n> **Key Concept 17.3: Fixed Effects -- Controlling for Unobserved Heterogeneity**\n>\n> Fixed effects estimation controls for time-invariant individual characteristics by including individual-specific intercepts $\\alpha_i$. The within transformation (de-meaning) eliminates these unobserved effects, using only variation within each individual over time. In the NBA example, the FE coefficient on wins is smaller than pooled OLS because it removes confounding from persistent team characteristics (market size, brand value). FE provides more credible causal estimates but cannot identify effects of time-invariant variables.\n\n---\n\n### Fixed Effects: Controlling for Unobserved Team Characteristics\n\nThe comparison between Pooled OLS and Fixed Effects reveals **omitted variable bias** from time-invariant team characteristics:\n\n**Typical Results:**\n\n| Model | Wins Coefficient | SE (cluster) | R² |\n|-------|-----------------|-------------|-----|\n| **Pooled OLS** | 0.0055 | 0.0040 | **0.15** (overall) |\n| **Fixed Effects** | 0.0025 | 0.0020 | **0.65** (within) |\n\n**Key Findings:**\n\n1. **Coefficient shrinks substantially**:\n - Pooled: 0.0055 → FE: 0.0025 (drops by **55%**)\n - This suggests **positive omitted variable bias** in pooled model\n - High-revenue teams (big markets) also tend to win more\n - Pooled confounds **team quality** with **market size**\n\n2. **Fixed Effects isolates within-team variation**:\n - Asks: \"When the Lakers win 60 games vs. 45 games, how does their revenue change?\"\n - Holds constant: LA market, brand value, arena, etc.\n - More **credible causal interpretation**\n\n3. **R² interpretation changes**:\n - Pooled: Overall R² = 0.15 (explains 15% of total variation)\n - FE: Within R² = 0.65 (explains 65% of within-team variation)\n - Between R² would be even higher (team fixed effects explain most variation)\n\n**Understanding the Fixed Effects Model:**\n\n**Model:**\n$$\\text{lnrevenue}_{it} = \\alpha_i + \\beta \\cdot \\text{wins}_{it} + \\gamma \\cdot \\text{season}_t + u_{it}$$\n\nwhere:\n\n- $\\alpha_i$ = **team-specific intercept** (fixed effect)\n- Captures: Market size, arena quality, brand value, history, etc.\n- $\\beta$ = **within-team effect** of wins on revenue\n\n**Estimation (de-meaning):**\n\nWithin transformation:\n$$(\\text{lnrevenue}_{it} - \\bar{\\text{lnrevenue}}_i) = \\beta(\\text{wins}_{it} - \\bar{\\text{wins}}_i) + u_{it}$$\n\n- Subtracts team mean from each variable\n- Eliminates $\\alpha_i$ (team fixed effect)\n- Uses only **deviations from team average**\n\n**What Fixed Effects Controls For:**\n\n **Captured** (time-invariant):\n\n- Market size (NYC vs. Sacramento)\n- Arena quality (modern vs. old)\n- Franchise history (Lakers dynasty vs. new franchise)\n- Owner characteristics (deep pockets vs. budget)\n- Regional income levels\n- Climate, geography, local competition\n\n **Not captured** (time-varying):\n\n- Star player arrivals/departures\n- Coach quality changes\n- Injury shocks\n- Labor disputes (lockouts)\n- New TV contracts\n\n**Why Pooled OLS is Biased:**\n\n**Omitted variable bias formula:**\n$$\\text{Bias} = \\beta_{team} \\times \\frac{Cov(\\text{team quality}, \\text{wins})}{Var(\\text{wins})}$$\n\nwhere:\n\n- $\\beta_{team}$ = effect of team quality on revenue (positive!)\n- Cov(team quality, wins) = positive (good teams win more)\n- Result: **Positive bias** (pooled overestimates wins effect)\n\n**Example:**\n\n**Lakers** (big market):\n\n- Average wins: 55/season\n- Average revenue: \\$300M\n- High revenue because: 50% market size, 50% wins\n\n**Grizzlies** (small market):\n\n- Average wins: 45/season\n- Average revenue: \\$150M\n- Low revenue because: 50% market size, 50% wins\n\n**Pooled OLS** compares Lakers to Grizzlies:\n\n- Attributes all \\$150M difference to 10-win difference\n- Overstates wins effect!\n\n**Fixed Effects** compares Lakers 2015 (67 wins) to Lakers 2012 (41 wins):\n\n- Market size constant (LA both years)\n- Isolates **wins effect** from **market effect**\n\n**The R² Decomposition:**\n\nFixed effects output typically reports three R²:\n\n1. **Within R²** (0.65): Variation explained **within teams over time**\n - How well model predicts year-to-year changes\n - Most relevant for FE\n\n2. **Between R²** (0.05-0.10): Variation explained **across team averages**\n - FE absorbs most between variation into $\\alpha_i$\n - Low by construction\n\n3. **Overall R²** (0.15-0.20): Total variation explained\n - Weighted average of within and between\n - Not directly comparable to pooled R²\n\n**Interpretation of the 0.0025 Coefficient:**\n\n**Marginal effect:**\n\n- One additional win → **+0.25%** revenue increase\n- For a team with \\$200M revenue: 0.25% × \\$200M = **\\$500K**\n- Over 10 additional wins: **\\$5M** revenue increase\n\n**Is this economically significant?**\n\n- Player salaries: ~\\$5M for rotation player\n- Marginal revenue from wins can **justify** roster investments\n- But much smaller than cross-sectional differences (market size dominates)\n\n**Statistical Significance:**\n\nWith cluster SEs:\n\n- t-statistic: 0.0025 / 0.0020 ≈ **1.25**\n- p-value ≈ **0.21** (not significant at 5%)\n\nSurprisingly **not significant**! Why?\n\n1. **Small within-variation** (teams don't vary hugely in wins year-to-year)\n2. **Revenue smoothing** (multi-year contracts, season tickets)\n3. **Only 29 teams** (small number of clusters → large SEs)\n4. **Short panel** (10 years → limited within-variation per team)\n\n**Practical Implications:**\n\n- **Pooled OLS**: \"High-revenue teams win more\" (true, but confounded)\n- **Fixed Effects**: \"Winning more games increases revenue\" ? (effect exists but imprecisely estimated)\n- Need **longer panel** or **more teams** for precise FE estimates\n\n## 17.4: Random Effects Estimation\n\nRandom effects (RE) models individual-specific effects as random draws from a distribution.\n\n**Model:**\n\n$$y_{it} = \\beta_1 + \\beta_2 x_{2it} + \\cdots + \\beta_k x_{kit} + (\\alpha_i + \\varepsilon_{it})$$\n\nwhere:\n\n- $\\alpha_i \\sim (0, \\sigma_\\alpha^2)$ is the individual-specific random effect\n- $\\varepsilon_{it} \\sim (0, \\sigma_\\varepsilon^2)$ is the idiosyncratic error\n\n**Key assumption:** $\\alpha_i$ uncorrelated with all regressors\n\n**Estimation:** Feasible GLS (FGLS)\n\n**Comparison with FE:**\n\n- **RE**: More efficient if assumption holds; uses both within and between variation\n- **FE**: Consistent even if $\\alpha_i$ correlated with regressors; uses only within variation\n\n**Hausman test:** Test whether RE assumption is valid\n\n- $H_0$: $\\alpha_i$ uncorrelated with regressors (RE consistent and efficient)\n- $H_a$: $\\alpha_i$ correlated with regressors (FE consistent, RE inconsistent)\n\n::: {#f1b16628 .cell execution_count=6}\n``` {.python .cell-code}\n# 17.4 Random Effects Estimation\n\n# Note: pyfixest focuses on FE estimation. For RE comparison, we show \n# the pooled vs FE comparison which is the most policy-relevant.\n# Model Comparison: Pooled and FE\n\ncomparison_table = pd.DataFrame({\n    'Pooled OLS': [fit_pool.coef()['wins'], fit_pool.se()['wins'],\n                   fit_pool._r2, fit_pool._N],\n    'Fixed Effects': [fit_fe.coef()['wins'], fit_fe.se()['wins'],\n                     fit_fe._r2_within, fit_fe._N]\n}, index=['Wins Coefficient', 'Wins Std Error', 'R²', 'N'])\n\nprint(\"\\n\", comparison_table)\n\nprint(\"\\nNote: FE is preferred when individual effects correlate with regressors (typical case)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n                   Pooled OLS  Fixed Effects\nWins Coefficient    0.006753       0.004505\nWins Std Error      0.001909       0.000842\nR²                  0.126663       0.185083\nN                 286.000000     286.000000\n\nNote: FE is preferred when individual effects correlate with regressors (typical case)\n```\n:::\n:::\n\n\n> **Key Concept 17.4: Fixed Effects vs. Random Effects**\n>\n> Fixed effects (FE) and random effects (RE) differ in a key assumption: RE requires that individual effects $\\alpha_i$ are uncorrelated with regressors, while FE allows arbitrary correlation. FE is consistent in either case but uses only within variation; RE is more efficient but inconsistent if the assumption fails. The Hausman test compares FE and RE estimates -- a significant difference indicates RE is inconsistent and FE should be preferred. In practice, FE is the safer choice for most observational studies.\n\n### Nonlinear Models: Logit Example\n\nBefore moving to time series, let's briefly cover nonlinear models using a logit example.\n\n**Binary outcome model:**\n\n$$Pr(y=1|X) = \\frac{\\exp(X\\beta)}{1 + \\exp(X\\beta)}$$\n\n**Marginal effects:** Change in probability from one-unit change in $x_j$\n\n$$ME_j = \\frac{\\partial Pr(y=1)}{\\partial x_j} = \\hat{p}(1-\\hat{p})\\beta_j$$\n\nWe'll use earnings data to model the probability of high earnings.\n\n::: {#2bffceaf .cell execution_count=7}\n``` {.python .cell-code}\n# Nonlinear Models: Logit Example\n\n# Load earnings data\ndata_earnings = pd.read_stata(GITHUB_DATA_URL + 'AED_EARNINGS_COMPLETE.DTA')\n\n# Create binary indicator for high earnings\ndata_earnings['dbigearn'] = (data_earnings['earnings'] > 60000).astype(int)\n\nprint(f\"\\nBinary dependent variable: High earnings (> $60,000)\")\nprint(f\"Proportion with high earnings: {data_earnings['dbigearn'].mean():.4f}\")\n\n# Logit model\nmodel_logit = logit('dbigearn ~ age + education', data=data_earnings).fit(cov_type='HC1', disp=0)\n\n# Key results\nprint(f\"Logit coefficients:\")\nprint(f\"  Age:       {model_logit.params['age']:.4f}\")\nprint(f\"  Education: {model_logit.params['education']:.4f}\")\nprint(f\"  Pseudo R-squared: {model_logit.prsquared:.4f}\")\n\n# Full logit output\nmodel_logit.summary()\n\n# Marginal effects\nmarginal_effects = model_logit.get_margeff()\n# Marginal Effects (at means)\nmarginal_effects.summary()\n\n# Linear Probability Model for comparison\nfit_lpm = pf.feols('dbigearn ~ age + education', data=data_earnings, vcov='HC1')\n# Linear Probability Model (for comparison)\nprint(f\"Age coefficient: {fit_lpm.coef()['age']:.6f} (SE: {fit_lpm.se()['age']:.6f})\")\nprint(f\"Education coefficient: {fit_lpm.coef()['education']:.6f} (SE: {fit_lpm.se()['education']:.6f})\")\n\nprint(\"\\nNote: Logit marginal effects and LPM coefficients are similar in magnitude.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nBinary dependent variable: High earnings (> $60,000)\nProportion with high earnings: 0.2729\nLogit coefficients:\n  Age:       0.0385\n  Education: 0.3742\n  Pseudo R-squared: 0.1447\nAge coefficient: 0.006420 (SE: 0.001277)\nEducation coefficient: 0.054036 (SE: 0.005020)\n\nNote: Logit marginal effects and LPM coefficients are similar in magnitude.\n```\n:::\n:::\n\n\n## 17.5: Time Series Data\n\nTime series data consist of observations ordered over time: $y_1, y_2, \\ldots, y_T$\n\n**Key concepts:**\n\n1. **Autocorrelation**: Correlation between $y_t$ and $y_{t-k}$ (lag $k$)\n   - Sample autocorrelation at lag $k$: $r_k = \\frac{\\sum_{t=k+1}^T (y_t - \\bar{y})(y_{t-k} - \\bar{y})}{\\sum_{t=1}^T (y_t - \\bar{y})^2}$\n\n2. **Stationarity**: Statistical properties (mean, variance) constant over time\n   - Many economic time series are non-stationary (trending)\n\n3. **Spurious regression**: High $R^2$ without true relationship (both series trending)\n   - Solution: First differencing or detrending\n\n4. **HAC standard errors** (Newey-West): Heteroskedasticity and Autocorrelation Consistent\n   - Valid inference in presence of autocorrelation\n\n**U.S. Treasury Interest Rates Example:**\n\nMonthly data from January 1982 to January 2015 on 1-year and 10-year rates.\n\n::: {#0fcafb6a .cell execution_count=8}\n``` {.python .cell-code}\n# 17.5 Time Series Data\n\n# Load interest rates data\ndata_rates = pd.read_stata(GITHUB_DATA_URL + 'AED_INTERESTRATES.DTA')\n\nprint(\"\\nInterest Rates Data Summary:\")\ndata_rates[['gs10', 'gs1', 'dgs10', 'dgs1']].describe()\n\nprint(\"\\nVariable definitions:\")\n# gs10: 10-year Treasury rate (level)\n# gs1: 1-year Treasury rate (level)\n# dgs10: Change in 10-year rate (first difference)\n# dgs1: Change in 1-year rate (first difference)\n\nprint(\"\\nFirst observations:\")\ndata_rates[['gs10', 'gs1', 'dgs10', 'dgs1']].head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nInterest Rates Data Summary:\n\nVariable definitions:\n\nFirst observations:\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>gs10</th>\n      <th>gs1</th>\n      <th>dgs10</th>\n      <th>dgs1</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>14.59</td>\n      <td>14.32</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>14.43</td>\n      <td>14.73</td>\n      <td>-0.16</td>\n      <td>0.41</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>13.86</td>\n      <td>13.95</td>\n      <td>-0.57</td>\n      <td>-0.78</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>13.87</td>\n      <td>13.98</td>\n      <td>0.01</td>\n      <td>0.03</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>13.62</td>\n      <td>13.34</td>\n      <td>-0.25</td>\n      <td>-0.64</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>14.30</td>\n      <td>14.07</td>\n      <td>0.68</td>\n      <td>0.73</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>13.95</td>\n      <td>13.24</td>\n      <td>-0.35</td>\n      <td>-0.83</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>13.06</td>\n      <td>11.43</td>\n      <td>-0.89</td>\n      <td>-1.81</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>12.34</td>\n      <td>10.85</td>\n      <td>-0.72</td>\n      <td>-0.58</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>10.91</td>\n      <td>9.32</td>\n      <td>-1.43</td>\n      <td>-1.53</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n> **Key Concept 17.5: Time Series Stationarity and Spurious Regression**\n>\n> A time series is stationary if its statistical properties (mean, variance, autocorrelation) are constant over time. Many economic series are non-stationary (trending), which can produce spurious regressions: high $R^2$ and significant coefficients even when variables are unrelated. Solutions include first differencing (removing trends), detrending, and cointegration analysis. Always check whether your time series are stationary before interpreting regression results.\n\n### Time Series Visualization\n\nPlotting time series helps identify trends, seasonality, and structural breaks.\n\n::: {#8a967b58 .cell execution_count=9}\n``` {.python .cell-code}\n# Figure: Time series plots\nfig, axes = plt.subplots(2, 1, figsize=(12, 8))\n\n# Panel 1: Levels\naxes[0].plot(data_rates.index, data_rates['gs10'], label='10-year rate', linewidth=1.5)\naxes[0].plot(data_rates.index, data_rates['gs1'], label='1-year rate', linewidth=1.5)\naxes[0].set_xlabel('Observation', fontsize=11)\naxes[0].set_ylabel('Interest Rate (%)', fontsize=11)\naxes[0].set_title('Interest Rates (Levels)', fontsize=12, fontweight='bold')\naxes[0].legend()\naxes[0].grid(True, alpha=0.3)\n\n# Panel 2: Scatter plot\naxes[1].scatter(data_rates['gs1'], data_rates['gs10'], alpha=0.5, s=20)  # alpha = transparency, s = marker size\nz = np.polyfit(data_rates['gs1'].dropna(), data_rates['gs10'].dropna(), 1)\np = np.poly1d(z)\ngs1_range = np.linspace(data_rates['gs1'].min(), data_rates['gs1'].max(), 100)\naxes[1].plot(gs1_range, p(gs1_range), 'r-', linewidth=2, label='OLS fit')\naxes[1].set_xlabel('1-year rate (%)', fontsize=11)\naxes[1].set_ylabel('10-year rate (%)', fontsize=11)\naxes[1].set_title('10-year vs 1-year Rate', fontsize=12, fontweight='bold')\naxes[1].legend()\naxes[1].grid(True, alpha=0.3)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch17_Panel_Data_Time_Series_Data_Causation_files/figure-html/cell-10-output-1.png){width=1142 height=758}\n:::\n:::\n\n\n**What to look for in these time series plots:**\n\n- **Top panel (Levels)**: Both rates trend downward from ~14% in 1982 to ~2% by 2015 -- this persistent trend signals non-stationarity, which can produce spurious regressions\n- **Top panel (Spread)**: The gap between 10-year and 1-year rates varies over time -- when the 1-year rate drops sharply (Fed easing), the spread widens\n- **Bottom panel (Scatter)**: The tight positive cluster confirms strong correlation, but this may partly reflect common trends rather than a true structural relationship\n\n### Regression in Levels vs. Changes\n\nWith trending data, we should be careful about spurious regression.\n\n::: {#65e6d911 .cell execution_count=10}\n``` {.python .cell-code}\nprint(\"Regression in Levels with Time Trend\")\n\n# Create time variable\ndata_rates['time'] = np.arange(len(data_rates))\n\n# Regression in levels\nfit_levels = pf.feols('gs10 ~ gs1 + time', data=data_rates)\nprint(\"\\nLevels regression (default SEs):\")\nprint(f\"  gs1 coef: {fit_levels.coef()['gs1']:.6f}\")\nprint(f\"  R²: {fit_levels._r2:.6f}\")\n\n# HAC standard errors (Newey-West)\nfit_levels_hac = pf.feols('gs10 ~ gs1 + time', data=data_rates,\n                          vcov='NW', vcov_kwargs={'time_id': 'time', 'lag': 24})  # 2 years of monthly data\nprint(\"\\nLevels regression (HAC SEs with 24 lags):\")\nprint(f\"  gs1 coef: {fit_levels_hac.coef()['gs1']:.6f}\")\nprint(f\"  gs1 SE (default): {fit_levels.se()['gs1']:.6f}\")\nprint(f\"  gs1 SE (HAC): {fit_levels_hac.se()['gs1']:.6f}\")\nprint(f\"\\n  HAC SE is {fit_levels_hac.se()['gs1'] / fit_levels.se()['gs1']:.2f}x larger!\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRegression in Levels with Time Trend\n\nLevels regression (default SEs):\n  gs1 coef: 0.507550\n  R²: 0.946883\n\nLevels regression (HAC SEs with 24 lags):\n  gs1 coef: 0.507550\n  gs1 SE (default): 0.022147\n  gs1 SE (HAC): 0.080758\n\n  HAC SE is 3.65x larger!\n```\n:::\n:::\n\n\n## 17.6: Autocorrelation\n\nAutocorrelation (serial correlation) violates the independence assumption of OLS.\n\n**Consequences:**\n\n- OLS remains unbiased and consistent\n- Standard errors are incorrect (typically too small)\n- Hypothesis tests invalid\n\n**Detection:**\n\n1. **Correlogram**: Plot of autocorrelations at different lags\n2. **Breusch-Godfrey test**: LM test for serial correlation\n3. **Durbin-Watson statistic**: Tests for AR(1) errors\n\n**Solutions:**\n\n1. HAC standard errors (Newey-West)\n2. Model the autocorrelation (AR, ARMA models)\n3. First differencing (if series are non-stationary)\n\n::: {#6e963905 .cell execution_count=11}\n``` {.python .cell-code}\n# 17.6 Autocorrelation\n\n# Check residual autocorrelation from levels regression\ndata_rates['uhatgs10'] = fit_levels._u_hat\n\n# Correlogram\nprint(\"\\nAutocorrelations of residuals (levels regression):\")\nacf_resid = acf(data_rates['uhatgs10'].dropna(), nlags=10)\nfor i in range(min(11, len(acf_resid))):\n    print(f\"  Lag {i}: {acf_resid[i]:.6f}\")\n\nprint(\"\\nStrong autocorrelation evident (lag 1 = {:.4f})\".format(acf_resid[1]))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nAutocorrelations of residuals (levels regression):\n  Lag 0: 1.000000\n  Lag 1: 0.953418\n  Lag 2: 0.888093\n  Lag 3: 0.829507\n  Lag 4: 0.769449\n  Lag 5: 0.708815\n  Lag 6: 0.651059\n  Lag 7: 0.596161\n  Lag 8: 0.537987\n  Lag 9: 0.477552\n  Lag 10: 0.424660\n\nStrong autocorrelation evident (lag 1 = 0.9534)\n```\n:::\n:::\n\n\n> **Key Concept 17.6: Detecting and Correcting Autocorrelation**\n>\n> The correlogram (ACF plot) reveals autocorrelation patterns in residuals. Slowly decaying autocorrelations (e.g., $\\rho_1 = 0.95$, $\\rho_{10} = 0.42$) indicate non-stationarity and persistent shocks. With autocorrelation, default SEs are too small -- HAC (Newey-West) SEs can be 3-8 times larger. Always check residual autocorrelation after estimating time series regressions and use HAC SEs or model the dynamics explicitly.\n\n### Correlogram Visualization\n\n::: {#5b305aef .cell execution_count=12}\n``` {.python .cell-code}\n# Plot correlogram\nfig, ax = plt.subplots(figsize=(10, 6))\nplot_acf(data_rates['uhatgs10'].dropna(), lags=24, ax=ax, alpha=0.05)\nax.set_title('Correlogram: Residuals from Levels Regression', fontsize=14, fontweight='bold')\nax.set_xlabel('Lag', fontsize=12)\nax.set_ylabel('Autocorrelation', fontsize=12)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch17_Panel_Data_Time_Series_Data_Causation_files/figure-html/cell-13-output-1.png){width=950 height=565}\n:::\n:::\n\n\n**What to look for in this correlogram:**\n\n- **Slow decay**: Autocorrelations remain high even at long lags (lag 10 still above 0.4) -- this is the signature of a non-stationary or near-unit-root process\n- **Blue confidence bands**: Bars extending well beyond these bands confirm statistically significant autocorrelation at virtually every lag\n- **Implication**: Standard OLS inference is invalid because residuals are strongly dependent -- HAC standard errors or first differencing are needed\n\n### First Differencing\n\nFirst differencing can remove trends and reduce autocorrelation.\n\n::: {#fc01ccde .cell execution_count=13}\n``` {.python .cell-code}\nprint(\"Regression in Changes (First Differences)\")\n\n# Regression in changes\nfit_changes = pf.feols('dgs10 ~ dgs1', data=data_rates)\nprint(\"\\nChanges regression:\")\nprint(f\"  dgs1 coef: {fit_changes.coef()['dgs1']:.6f}\")\nprint(f\"  dgs1 SE: {fit_changes.se()['dgs1']:.6f}\")\nprint(f\"  R²: {fit_changes._r2:.6f}\")\n\n# Check residual autocorrelation\nuhat_dgs10 = fit_changes._u_hat\nacf_dgs10_resid = acf(uhat_dgs10[~np.isnan(uhat_dgs10)], nlags=10)\n\nprint(\"\\nAutocorrelations of residuals (changes regression):\")\nfor i in range(min(11, len(acf_dgs10_resid))):\n    print(f\"  Lag {i}: {acf_dgs10_resid[i]:.6f}\")\n\nprint(\"\\nMuch lower autocorrelation after differencing!\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRegression in Changes (First Differences)\n\nChanges regression:\n  dgs1 coef: 0.719836\n  dgs1 SE: 0.031443\n  R²: 0.570860\n\nAutocorrelations of residuals (changes regression):\n  Lag 0: 1.000000\n  Lag 1: 0.254801\n  Lag 2: -0.038743\n  Lag 3: 0.060813\n  Lag 4: 0.023676\n  Lag 5: -0.027540\n  Lag 6: -0.011310\n  Lag 7: 0.042843\n  Lag 8: 0.081094\n  Lag 9: -0.001712\n  Lag 10: -0.019733\n\nMuch lower autocorrelation after differencing!\n```\n:::\n:::\n\n\n> **Key Concept 17.7: First Differencing for Nonstationary Data**\n>\n> First differencing ($\\Delta y_t = y_t - y_{t-1}$) transforms non-stationary trending series into stationary ones, eliminating spurious regression problems. After differencing, the residual autocorrelation drops dramatically (from $\\rho_1 \\approx 0.95$ to $\\rho_1 \\approx 0.25$ in the interest rate example). The coefficient interpretation changes from levels to changes: a 1-percentage-point change in the 1-year rate is associated with a 0.72-percentage-point change in the 10-year rate.\n\n### Autoregressive Models\n\n**AR(p) model:** Include lagged dependent variables\n\n$$y_t = \\beta_1 + \\beta_2 y_{t-1} + \\cdots + \\beta_{p+1} y_{t-p} + u_t$$\n\n**ADL(p, q) model:** Autoregressive Distributed Lag\n\n$$y_t = \\beta_1 + \\sum_{j=1}^p \\alpha_j y_{t-j} + \\sum_{j=0}^q \\gamma_j x_{t-j} + u_t$$\n\n---\n\n#### Autoregressive Models: Interest Rates Have Memory\n\nThe ADL model results reveal how interest rates evolve over time with **strong persistence**:\n\n**Typical ADL(2,2) Results:**\n\nFrom: $\\Delta gs10_t = \\beta_0 + \\beta_1 \\Delta gs10_{t-1} + \\beta_2 \\Delta gs10_{t-2} + \\gamma_0 \\Delta gs1_t + \\gamma_1 \\Delta gs1_{t-1} + \\gamma_2 \\Delta gs1_{t-2} + u_t$\n\n**Autoregressive terms** (own lags):\n\n- **Lag 1** ($\\Delta gs10_{t-1}$): ≈ **-0.15 to -0.25** (negative!)\n- **Lag 2** ($\\Delta gs10_{t-2}$): ≈ **-0.05 to -0.10** (negative)\n\n**Distributed lag terms** (1-year rate):\n\n- **Contemporary** ($\\Delta gs1_t$): ≈ **+0.45 to +0.55** (strong positive!)\n- **Lag 1** ($\\Delta gs1_{t-1}$): ≈ **+0.15 to +0.25**\n- **Lag 2** ($\\Delta gs1_{t-2}$): ≈ **+0.05 to +0.10**\n\n**Interpretation:**\n\n1. **Negative autocorrelation in changes**:\n - Coefficient on $\\Delta gs10_{t-1}$ is **negative**\n - If 10-year rate increased last month, it tends to **partially reverse** this month\n - This is **mean reversion** in changes\n - **Not** mean reversion in levels (levels are highly persistent)\n\n2. **Strong contemporary relationship**:\n - Coefficient ≈ **0.50** on $\\Delta gs1_t$\n - When 1-year rate increases 1%, 10-year rate increases **0.50%** same month\n - **Expectations hypothesis**: Long rates reflect expected future short rates\n - Less than 1-to-1 because 10-year rate is average over many periods\n\n3. **Distributed lag structure**:\n - Effects of 1-year rate changes **persist** over multiple months\n - Total effect: 0.50 + 0.20 + 0.08 ≈ **0.78**\n - Almost 80% of 1-year rate change eventually passes through to 10-year rate\n\n4. **R² increases substantially**:\n - Simple model (no lags): R² ≈ 0.20\n - ADL(2,2): R² ≈ **0.40-0.50**\n - **Dynamics matter!** Past values have strong predictive power\n\n**Why ADL Models Are Important:**\n\n**Forecasting:**\n\n- Can predict next month's 10-year rate using:\n - Past 10-year rates\n - Current and past 1-year rates\n- Better forecasts than static models\n\n**Policy analysis:**\n\n- Fed controls short rates (1-year)\n- ADL shows **transmission** to long rates (10-year)\n- **Speed of adjustment**: How quickly long rates respond to policy changes\n\n**Economic theory testing:**\n\n- Expectations hypothesis: Long rate = weighted average of expected future short rates\n- Term structure of interest rates\n- Market efficiency\n\n**The Residual ACF:**\n\nAfter fitting ADL(2,2):\n\n- **Lag 1 autocorrelation**: ρ₁ ≈ **0.05-0.10** (much lower!)\n- Compare to levels regression: ρ₁ ≈ 0.95\n- **Model captures most autocorrelation** \n\nThis suggests:\n\n- ADL(2,2) is **adequate specification**\n- No need for higher-order lags\n- Remaining autocorrelation is small\n\n**Comparing Models:**\n\n| Model | R² | Residual ρ₁ | BIC |\n|-------|-----|------------|-----|\n| Static ($\\Delta gs10 \\sim \\Delta gs1$) | 0.25 | 0.25 | Higher |\n| AR(2) ($\\Delta gs10 \\sim \\Delta gs10_{t-1,t-2}$) | 0.10 | 0.15 | Higher |\n| **ADL(2,2)** | **0.45** | **0.08** | **Lower** |\n\nADL(2,2) dominates on all criteria!\n\n**Interpretation of Dynamics:**\n\n**Short-run effect** (impact multiplier):\n\n- Immediate response to $\\Delta gs1_t$: **γ₀ ≈ 0.50**\n- Half of shock passes through contemporaneously\n\n**Medium-run effect** (interim multipliers):\n\n- After 1 month: γ₀ + γ₁ ≈ **0.70**\n- After 2 months: γ₀ + γ₁ + γ₂ ≈ **0.78**\n\n**Long-run effect** (total multiplier):\n\n- In levels regression: coefficient ≈ **0.90-0.95**\n- This is the **long-run equilibrium** relationship\n- ADL estimates **dynamics of adjustment** to this equilibrium\n\n**Why Negative Own-Lag Coefficients?**\n\nAt first, this seems counterintuitive:\n\n- Interest rates are **persistent** in levels\n- But **changes** show **mean reversion**\n\n**Explanation:**\n\n- **Levels** are I(1): Random walk with drift\n- **Changes** are I(0): Stationary, but with negative serial correlation\n- **Overshooting**: Markets overreact to news, then partially correct\n\n**Example:**\n\nMonth 1: Fed unexpectedly raises 1-year rate by 1%\n\n- 10-year rate increases by 0.60% (overshoots equilibrium)\n\nMonth 2: Market reassesses\n\n- 10-year rate decreases by 0.10% (partial reversal)\n\nMonth 3: Further adjustment\n\n- 10-year rate changes by -0.02% (approaching equilibrium)\n\nLong run: 10-year rate settles at +0.85% (new equilibrium)\n\n**Practical Value:**\n\n1. **Central banks**:\n - Understand how policy rate changes affect long rates\n - Timing and magnitude of transmission\n\n2. **Bond traders**:\n - Predict interest rate movements\n - Arbitrage opportunities if model predicts well\n\n3. **Economists**:\n - Test theories (expectations hypothesis, term premium)\n - Understand financial market dynamics\n\n**Model Selection:**\n\nChose ADL(2,2) based on:\n\n- **Information criteria** (AIC, BIC)\n- **Residual diagnostics** (low autocorrelation)\n- **Economic theory** (2 lags reasonable for monthly data)\n- **Parsimony** (not too many parameters)\n\nCould try ADL(3,3), but gains typically minimal\n\n### Visualization: Changes in Interest Rates\n\n::: {#dec88ba8 .cell execution_count=14}\n``` {.python .cell-code}\n# Figure: Changes\nfig, axes = plt.subplots(2, 1, figsize=(12, 8))\n\n# Panel 1: Time series of changes\naxes[0].plot(data_rates.index, data_rates['dgs10'], label='Δ 10-year rate', linewidth=1)\naxes[0].plot(data_rates.index, data_rates['dgs1'], label='Δ 1-year rate', linewidth=1)\naxes[0].axhline(y=0, color='white', alpha=0.3, linestyle='--', linewidth=0.5)\naxes[0].set_xlabel('Observation', fontsize=11)\naxes[0].set_ylabel('Change in Rate (pct points)', fontsize=11)\naxes[0].set_title('Changes in Interest Rates', fontsize=12, fontweight='bold')\naxes[0].legend()\naxes[0].grid(True, alpha=0.3)\n\n# Panel 2: Scatter plot of changes\naxes[1].scatter(data_rates['dgs1'], data_rates['dgs10'], alpha=0.5, s=20)\nvalid_idx = data_rates[['dgs1', 'dgs10']].dropna().index\nz = np.polyfit(data_rates.loc[valid_idx, 'dgs1'], data_rates.loc[valid_idx, 'dgs10'], 1)\np = np.poly1d(z)\ndgs1_range = np.linspace(data_rates['dgs1'].min(), data_rates['dgs1'].max(), 100)\naxes[1].plot(dgs1_range, p(dgs1_range), 'r-', linewidth=2, label='OLS fit')\naxes[1].axhline(y=0, color='white', alpha=0.3, linestyle='--', linewidth=0.5)\naxes[1].axvline(x=0, color='white', alpha=0.3, linestyle='--', linewidth=0.5)\naxes[1].set_xlabel('Δ 1-year rate', fontsize=11)\naxes[1].set_ylabel('Δ 10-year rate', fontsize=11)\naxes[1].set_title('Change in 10-year vs 1-year Rate', fontsize=12, fontweight='bold')\naxes[1].legend()\naxes[1].grid(True, alpha=0.3)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch17_Panel_Data_Time_Series_Data_Causation_files/figure-html/cell-15-output-1.png){width=1142 height=758}\n:::\n:::\n\n\n**What to look for in these change plots:**\n\n- **Top panel**: Changes fluctuate around zero with no visible trend -- this is the hallmark of a stationary series, unlike the trending levels above\n- **Bottom panel**: The positive scatter confirms that short-rate and long-rate changes move together, but the relationship is less than one-to-one (slope < 1)\n- **Volatility clustering**: Notice periods of larger swings (e.g., early 1980s) -- this heteroskedasticity motivates HAC standard errors\n\n## 17.7: Causality and Instrumental Variables\n\nEstablishing causality is central to econometrics. Correlation does not imply causation!\n\n**The fundamental problem:**\n\nIn regression $y = \\beta_1 + \\beta_2 x + u$, OLS is biased if $E[u|x] \\neq 0$\n\n**Sources of endogeneity:**\n\n1. Omitted variables\n2. Measurement error\n3. Simultaneity (reverse causation)\n\n**Instrumental Variables (IV) solution:**\n\nFind an instrument $z$ that:\n\n1. **Relevance**: Correlated with $x$ (can be tested)\n2. **Exogeneity**: Uncorrelated with $u$ (cannot be tested - must argue)\n\n**IV estimator:**\n\n$$\\hat{\\beta}_{IV} = \\frac{Cov(z,y)}{Cov(z,x)}$$\n\n**Causal inference methods:**\n\n1. Randomized experiments (RCT)\n2. Instrumental variables (IV)\n3. Difference-in-differences (DID)\n4. Regression discontinuity (RD)\n5. Fixed effects (control for unobserved heterogeneity)\n6. Matching and propensity scores\n\n**Key insight:** Need credible identification strategy, not just controls!\n\n::: {#33b39fd8 .cell execution_count=15}\n``` {.python .cell-code}\n# 17.7 Causality And Instrumental Variables\n\nprint(\"Key Points on Causality:\")\nprint(\"1. Correlation ≠ Causation\")\nprint(\"   - Regression shows association, not necessarily causation\")\nprint(\"   - Need to rule out confounding, reverse causation, selection\")\nprint(\"2. Causal methods: RCT, IV, Fixed Effects, DiD, RD, Matching\")\nprint(\"3. Credible causal inference requires a convincing identification strategy\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nKey Points on Causality:\n1. Correlation ≠ Causation\n   - Regression shows association, not necessarily causation\n   - Need to rule out confounding, reverse causation, selection\n2. Causal methods: RCT, IV, Fixed Effects, DiD, RD, Matching\n3. Credible causal inference requires a convincing identification strategy\n```\n:::\n:::\n\n\n**The Potential Outcomes Framework:**\n\n- $Y_{1i}$: Outcome if treated; $Y_{0i}$: Outcome if not treated\n- Individual treatment effect: $Y_{1i} - Y_{0i}$ (only one is observed!)\n- **ATE** = $E[Y_{1i} - Y_{0i}]$: Average Treatment Effect\n\n**The Causal Inference Toolkit:**\n\n- **Randomized Controlled Trials (RCT)**: Gold standard -- random assignment ensures treatment is uncorrelated with potential outcomes\n- **Instrumental Variables**: Use an instrument $z$ that affects $x$ but not $y$ directly\n- **Fixed Effects**: Control for time-invariant unobservables (e.g., NBA team characteristics)\n- **Difference-in-Differences**: Compare treatment vs. control groups before and after an intervention\n- **Regression Discontinuity**: Exploit a threshold rule for treatment assignment\n\n**Practical Recommendations:**\n\n- Always think about potential confounders\n- Use robust/cluster standard errors\n- Test multiple specifications and report both OLS and IV/FE\n- Be transparent about identification assumptions -- causal claims require strong justification\n\n> **Key Concept 17.8: Instrumental Variables and Causal Inference**\n>\n> Endogeneity (regressors correlated with errors) biases OLS estimates. Sources include omitted variables, measurement error, and simultaneity. Instrumental variables (IV) provide a solution: find a variable $z$ that is correlated with the endogenous regressor (relevance) but uncorrelated with the error (exogeneity). The IV estimator $\\hat{\\beta}_{IV} = \\text{Cov}(z,y)/\\text{Cov}(z,x)$ is consistent even when OLS is biased. Complementary causal methods include RCTs, DiD, RD, and matching.\n\n## Key Takeaways\n\n**Panel Data Methods:**\n\n- Panel data combines cross-sectional and time series dimensions, observing multiple individuals over multiple periods\n- Variance decomposition separates total variation into within (over time) and between (across individuals) components\n- Pooled OLS ignores panel structure; always use cluster-robust standard errors clustered by individual\n- Fixed effects controls for time-invariant unobserved heterogeneity by using only within-individual variation\n- Random effects is more efficient than FE but assumes individual effects are uncorrelated with regressors\n- FE is preferred when individual effects are likely correlated with regressors (use Hausman test to decide)\n\n**Nonlinear Models:**\n\n- Logit models estimate the probability of binary outcomes using the logistic function\n- Marginal effects ($\\hat{p}(1-\\hat{p})\\beta_j$) give the change in probability from a one-unit change in $x_j$\n- Logit marginal effects and linear probability model coefficients are typically similar in magnitude\n\n**Time Series Analysis:**\n\n- Time series data exhibit autocorrelation, where observations are correlated with their past values\n- Non-stationary series (trending) can produce spurious regressions with misleadingly high $R^2$\n- First differencing removes trends and reduces autocorrelation, transforming non-stationary series to stationary\n- HAC (Newey-West) standard errors account for both heteroskedasticity and autocorrelation in time series\n- Default SEs can be dramatically too small with autocorrelation (3-8x understatement is common)\n\n**Dynamic Models:**\n\n- Autoregressive (AR) models capture persistence by including lagged dependent variables\n- Autoregressive distributed lag (ADL) models include lags of both the dependent and independent variables\n- The correlogram (ACF plot) helps determine the appropriate number of lags\n- Total multiplier from an ADL model gives the long-run effect of a permanent change in $x$\n\n**Causality and Instrumental Variables:**\n\n- Correlation does not imply causation; endogeneity (omitted variables, reverse causation, measurement error) biases OLS\n- Instrumental variables require relevance ($\\text{Corr}(z,x) \\neq 0$) and exogeneity ($\\text{Corr}(z,u) = 0$)\n- Fixed effects, difference-in-differences, regression discontinuity, and matching are complementary causal methods\n- Credible causal inference requires a convincing identification strategy, not just adding control variables\n\n**Python tools:** `pyfixest` (OLS, FE, IV, cluster/HAC SEs), `statsmodels` (logit, ACF), `matplotlib`/`seaborn` (visualization)\n\n**Python Libraries and Code:**\n\nThis single code block reproduces the core workflow of Chapter 17. It is self-contained — copy it into an empty notebook and run it to review the complete pipeline from panel data estimation to time series diagnostics and dynamic modeling.\n\n```python\n# =============================================================================\n# CHAPTER 17 CHEAT SHEET: Panel Data, Time Series Data, Causation\n# =============================================================================\n\n# --- Libraries ---\nimport pandas as pd                       # data loading and manipulation\nimport numpy as np                         # numerical operations\nimport matplotlib.pyplot as plt            # creating plots and visualizations\nimport pyfixest as pf                      # fast OLS/FE/IV estimation\n# !pip install pyfixest\nfrom statsmodels.tsa.stattools import acf  # autocorrelation function\n\n# =============================================================================\n# STEP 1: Load panel data (NBA teams across seasons)\n# =============================================================================\n# Panel data: multiple individuals (teams) observed over multiple time periods\nurl_nba = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/AED_NBA.DTA\"\ndata_nba = pd.read_stata(url_nba)\n\nprint(f\"Panel: {data_nba['teamid'].nunique()} teams × {data_nba['season'].nunique()} seasons = {len(data_nba)} obs\")\n\n# =============================================================================\n# STEP 2: Variance decomposition — between vs within variation\n# =============================================================================\n# Understanding which variation your estimator uses is the first step in panel analysis\noverall_sd = data_nba['lnrevenue'].std()\nbetween_sd = data_nba.groupby('teamid')['lnrevenue'].mean().std()\nwithin_sd  = data_nba.groupby('teamid')['lnrevenue'].apply(lambda x: x - x.mean()).std()\n\nprint(f\"\\nVariance Decomposition of Log Revenue:\")\nprint(f\"  Overall SD:  {overall_sd:.4f}\")\nprint(f\"  Between SD:  {between_sd:.4f} (across teams)\")\nprint(f\"  Within SD:   {within_sd:.4f} (over time)\")\nprint(f\"  Between > Within → team characteristics dominate year-to-year swings\")\n\n# =============================================================================\n# STEP 3: Pooled OLS with cluster-robust SEs\n# =============================================================================\n# Observations within the same team are correlated over time — default SEs\n# dramatically understate uncertainty. Always cluster by individual in panel data.\nfit_pool = pf.feols('lnrevenue ~ wins', data=data_nba)\nfit_cluster = pf.feols('lnrevenue ~ wins', data=data_nba, vcov={'CRV1': 'teamid'})\n\nprint(f\"\\nPooled OLS — wins coefficient: {fit_pool.coef()['wins']:.6f}\")\nprint(f\"  Default SE:  {fit_pool.se()['wins']:.6f}\")\nprint(f\"  Cluster SE:  {fit_cluster.se()['wins']:.6f}\")\nprint(f\"  Ratio:       {fit_cluster.se()['wins'] / fit_pool.se()['wins']:.2f}x larger\")\n\n# =============================================================================\n# STEP 4: Fixed effects — control for unobserved team characteristics\n# =============================================================================\n# FE uses only within-team variation (de-meaning), eliminating bias from\n# persistent traits like market size, brand value, and arena quality.\nfit_fe = pf.feols('lnrevenue ~ wins | teamid', data=data_nba, vcov={'CRV1': 'teamid'})\n\nprint(f\"\\nFixed Effects — wins coefficient: {fit_fe.coef()['wins']:.6f}\")\nprint(f\"  Cluster SE:  {fit_fe.se()['wins']:.6f}\")\nprint(f\"  R² (within): {fit_fe._r2_within:.4f}\")\n\nprint(f\"\\nComparison:\")\nprint(f\"  Pooled OLS coef: {fit_pool.coef()['wins']:.6f}\")\nprint(f\"  Fixed Effects:   {fit_fe.coef()['wins']:.6f}\")\nprint(f\"  FE is smaller → pooled OLS had positive omitted variable bias\")\n\n# =============================================================================\n# STEP 5: Time series — levels vs first differences\n# =============================================================================\n# Non-stationary (trending) series produce spurious regressions with misleading R².\n# First differencing removes trends and restores valid inference.\nurl_rates = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/AED_INTERESTRATES.DTA\"\ndata_rates = pd.read_stata(url_rates)\n\n# Regression in levels (potentially spurious)\nfit_levels = pf.feols('gs10 ~ gs1', data=data_rates)\n\n# Regression in first differences (removes trends)\nfit_changes = pf.feols('dgs10 ~ dgs1', data=data_rates)\n\nprint(f\"\\nLevels regression:  gs1 coef = {fit_levels.coef()['gs1']:.4f}, R² = {fit_levels._r2:.4f}\")\nprint(f\"Changes regression: dgs1 coef = {fit_changes.coef()['dgs1']:.4f}, R² = {fit_changes._r2:.4f}\")\nprint(f\"R² drops after differencing — lower but honest (no spurious trend inflation)\")\n\n# =============================================================================\n# STEP 6: Autocorrelation diagnostics — the smoking gun\n# =============================================================================\n# Slowly decaying ACF in residuals signals non-stationarity and invalid SEs.\n# After differencing, autocorrelation should drop dramatically.\nacf_levels  = acf(pd.Series(fit_levels._u_hat).dropna(), nlags=5)\nacf_changes = acf(pd.Series(fit_changes._u_hat).dropna(), nlags=5)\n\nprint(f\"\\nResidual autocorrelation (lag 1):\")\nprint(f\"  Levels regression:  {acf_levels[1]:.4f} (high → non-stationary residuals)\")\nprint(f\"  Changes regression: {acf_changes[1]:.4f} (much lower → differencing worked)\")\n\n# HAC (Newey-West) SEs correct for autocorrelation without differencing\nfit_hac = pf.feols('gs10 ~ gs1', data=data_rates,\n                   vcov='NW', vcov_kwargs={'time_id': 'time', 'lag': 24})\nprint(f\"\\nDefault SE on gs1:   {fit_levels.se()['gs1']:.4f}\")\nprint(f\"HAC SE on gs1:       {fit_hac.se()['gs1']:.4f}\")\nprint(f\"HAC is {fit_hac.se()['gs1'] / fit_levels.se()['gs1']:.1f}x larger — default SEs are too small\")\n\n# =============================================================================\n# STEP 7: ADL model — dynamic multipliers\n# =============================================================================\n# Autoregressive distributed lag models capture how effects build over time.\n# Lagged dependent and independent variables model persistence and transmission.\ndata_rates['dgs10_lag1'] = data_rates['dgs10'].shift(1)\ndata_rates['dgs10_lag2'] = data_rates['dgs10'].shift(2)\ndata_rates['dgs1_lag1']  = data_rates['dgs1'].shift(1)\ndata_rates['dgs1_lag2']  = data_rates['dgs1'].shift(2)\n\nfit_adl = pf.feols('dgs10 ~ dgs10_lag1 + dgs10_lag2 + dgs1 + dgs1_lag1 + dgs1_lag2',\n                data=data_rates)\n\nprint(f\"\\nADL(2,2) Model:\")\nprint(f\"  Impact multiplier (dgs1):       {fit_adl.coef()['dgs1']:.4f}\")\nprint(f\"  1-month cumulative:             {fit_adl.coef()['dgs1'] + fit_adl.coef()['dgs1_lag1']:.4f}\")\nprint(f\"  2-month cumulative:             {fit_adl.coef()['dgs1'] + fit_adl.coef()['dgs1_lag1'] + fit_adl.coef()['dgs1_lag2']:.4f}\")\nprint(f\"  R²: {fit_adl._r2:.4f} (much higher than static model)\")\n\n# Check residual autocorrelation — should be near zero if well-specified\nacf_adl = acf(pd.Series(fit_adl._u_hat).dropna(), nlags=5)\nprint(f\"  Residual ACF(1): {acf_adl[1]:.4f} (near zero → dynamics captured)\")\n```\n\n**Try it yourself!** Copy this code into an empty Google Colab notebook and run it: [Open Colab](https://colab.research.google.com/notebooks/empty.ipynb)\n\n**Next steps:** Apply these methods to your own research questions. Panel data methods, time series models, and causal inference strategies are essential tools for any applied econometrician working with observational data.\n\n---\n\nCongratulations! You've completed Chapter 17, the final chapter covering panel data, time series, and causal inference. You now have a comprehensive toolkit of econometric methods for analyzing real-world data.\n\n> **Common Mistakes to Avoid**\n>\n> - **Using pooled OLS when fixed effects are needed**: Ignoring unobserved heterogeneity biases coefficients\n> - **Confusing within and between variation**: Fixed effects only use within-entity variation\n> - **Claiming causation from observational data without addressing endogeneity**\n\n## Practice Exercises\n\n**Exercise 1: Panel Data Variance Decomposition**\n\nA panel dataset of 50 firms over 5 years shows:\n\n- Overall standard deviation of log revenue: 0.80\n- Between standard deviation: 0.70\n- Within standard deviation: 0.30\n\n(a) Which source of variation dominates? What does this imply about the importance of firm-specific characteristics?\n\n(b) If you run fixed effects, what proportion of the total variation are you using for estimation?\n\n(c) Would you expect the FE coefficient to be larger or smaller than pooled OLS? Explain using the omitted variables bias formula.\n\n**Exercise 2: Cluster-Robust Standard Errors**\n\nYou estimate a panel regression of test scores on class size using data from 100 schools over 3 years (300 observations). The coefficient on class size has:\n\n- Default SE: 0.15 (t = 3.33)\n- Cluster-robust SE (by school): 0.45 (t = 1.11)\n\n(a) Why is the cluster SE three times larger than the default SE?\n\n(b) Does your conclusion about the significance of class size change? At what significance level?\n\n(c) What is the effective number of independent observations in this panel?\n\n**Exercise 3: Fixed Effects vs. Random Effects**\n\nYou estimate a wage equation using panel data on 500 workers over 10 years. The Hausman test yields $\\chi^2 = 25.4$ with 3 degrees of freedom ($p < 0.001$).\n\n(a) State the null and alternative hypotheses of the Hausman test.\n\n(b) What do you conclude? Which estimator should you use?\n\n(c) Give an economic reason why the RE assumption might fail in a wage equation (hint: think about unobserved ability).\n\n**Exercise 4: Time Series Autocorrelation**\n\nA regression of the 10-year interest rate on the 1-year rate using monthly data yields residuals with:\n\n- Lag 1 autocorrelation: 0.95\n- Lag 5 autocorrelation: 0.75\n- Default SE on the 1-year rate coefficient: 0.022\n- HAC SE (24 lags): 0.080\n\n(a) Is there evidence of autocorrelation? What does the slowly decaying ACF pattern suggest about the data?\n\n(b) By what factor do the HAC SEs differ from default SEs? What are the implications for hypothesis testing?\n\n(c) Would first differencing help? What would you expect the lag 1 autocorrelation of the differenced residuals to be?\n\n**Exercise 5: Spurious Regression**\n\nYou regress GDP on the number of mobile phone subscriptions over 30 years and find $R^2 = 0.97$ with a highly significant coefficient.\n\n(a) Why might this be a spurious regression? What is the key characteristic of both series?\n\n(b) Describe two methods to address this problem.\n\n(c) If you first-difference both series, what economic relationship (if any) would the regression estimate?\n\n**Exercise 6: Identifying Causal Effects**\n\nFor each scenario, identify the main threat to causal inference and suggest an appropriate method:\n\n(a) Estimating the effect of police spending on crime rates across cities (cross-sectional data).\n\n(b) Estimating the effect of a minimum wage increase on employment (state-level panel data with staggered adoption).\n\n(c) Estimating the effect of class size on student achievement (students assigned to classes based on a cutoff rule).\n\n## Case Studies\n\n### Case Study 1: Panel Data Analysis of Cross-Country Productivity\n\nIn this case study, you will apply panel data methods from this chapter to analyze labor productivity dynamics across countries using the Mendez convergence clubs dataset.\n\n**Dataset:** Mendez (2020) convergence clubs data\n\n- **Source:** `https://raw.githubusercontent.com/quarcs-lab/mendez2020-convergence-clubs-code-data/master/assets/dat.csv`\n- **Sample:** 108 countries, 1990-2014 (panel structure: country $\\times$ year)\n- **Variables:** `lp` (labor productivity), `rk` (physical capital), `hc` (human capital), `rgdppc` (real GDP per capita), `tfp` (total factor productivity), `region`, `country`\n\n**Research question:** How do physical and human capital affect labor productivity across countries, and does controlling for unobserved country characteristics change the estimates?\n\n---\n\n#### Task 1: Panel Data Structure (Guided)\n\nLoad the dataset and explore its panel structure. Calculate the within and between variation for log labor productivity.\n\n```python\nimport pandas as pd\nimport numpy as np\n\nurl = \"https://raw.githubusercontent.com/quarcs-lab/mendez2020-convergence-clubs-code-data/master/assets/dat.csv\"\ndat = pd.read_csv(url)\ndat['ln_lp'] = np.log(dat['lp'])\ndat['ln_rk'] = np.log(dat['rk'])\n\n# Panel structure\nprint(f\"Countries: {dat['country'].nunique()}\")\nprint(f\"Years: {dat['year'].nunique()}\")\nprint(f\"Total observations: {len(dat)}\")\n\n# Variance decomposition\noverall_var = dat['ln_lp'].var()\nbetween_var = dat.groupby('country')['ln_lp'].mean().var()\nwithin_var = dat.groupby('country')['ln_lp'].apply(lambda x: x - x.mean()).var()\nprint(f\"Overall variance: {overall_var:.4f}\")\nprint(f\"Between variance: {between_var:.4f}\")\nprint(f\"Within variance: {within_var:.4f}\")\n```\n\nWhich source of variation dominates? What does this imply for the choice between pooled OLS and fixed effects?\n\n---\n\n#### Task 2: Pooled OLS with Cluster-Robust SEs (Guided)\n\nEstimate a pooled OLS regression of log productivity on log physical capital and human capital. Compare default and cluster-robust standard errors (clustered by country).\n\n```python\nimport pyfixest as pf\n\nfit_default = pf.feols('ln_lp ~ ln_rk + hc', data=dat)\nfit_cluster = pf.feols('ln_lp ~ ln_rk + hc', data=dat, vcov={'CRV1': 'country'})\n\nprint(\"Default SE:\", fit_default.se().round(4).to_dict())\nprint(\"Cluster SE:\", fit_cluster.se().round(4).to_dict())\nprint(\"Ratio:\", (fit_cluster.se() / fit_default.se()).round(2).to_dict())\n```\n\nHow much larger are cluster SEs? What does this tell you about within-country correlation?\n\n---\n\n#### Task 3: Fixed Effects Estimation (Semi-guided)\n\nEstimate a fixed effects model controlling for country-specific characteristics. Compare the FE coefficients with the pooled OLS coefficients.\n\n*Hint:* Use `pf.feols('ln_lp ~ ln_rk + hc | country', data=dat)` for fixed effects, or use the within transformation manually by de-meaning the variables by country.\n\nWhich coefficients change most? What unobserved country characteristics might be driving the difference?\n\n---\n\n#### Task 4: Time Trends in Productivity (Semi-guided)\n\nAdd a time trend or year fixed effects to the panel model. Test whether productivity growth rates differ across regions.\n\n*Hint:* Use `pf.feols('ln_lp ~ ln_rk + hc | country + year', data=dat)` for two-way fixed effects, or create region-year interaction terms.\n\nIs there evidence of convergence (faster growth in initially poorer countries)?\n\n---\n\n#### Task 5: Regional Heterogeneity with Interactions (Independent)\n\nEstimate models that allow the returns to physical and human capital to vary by region:\n\n1. Add region dummy variables\n2. Add region-capital interaction terms\n3. Test the joint significance of regional interactions\n\nDo returns to capital differ significantly across regions? Which regions show the highest returns to human capital?\n\n---\n\n#### Task 6: Policy Brief on Capital and Productivity (Independent)\n\nWrite a 200-300 word policy brief addressing: What are the most effective channels for increasing labor productivity across countries? Your brief should:\n\n1. Compare pooled OLS and fixed effects estimates of capital returns\n2. Discuss whether the relationship is causal (what are the threats to identification?)\n3. Evaluate whether returns to capital differ by region\n4. Recommend policies based on the relative importance of physical vs. human capital\n\n> **Key Concept 17.9: Panel Data for Cross-Country Analysis**\n>\n> Cross-country panel data enables controlling for time-invariant country characteristics (institutions, geography, culture) that confound cross-sectional estimates. Fixed effects absorb these permanent differences, identifying the relationship between capital accumulation and productivity growth from within-country variation over time. The typical finding is that FE coefficients are smaller than pooled OLS, indicating positive omitted variable bias in cross-sectional estimates.\n\n> **Key Concept 17.10: Choosing Between Panel Data Estimators**\n>\n> The choice between pooled OLS, fixed effects, and random effects depends on the research question and data structure. Use pooled OLS with cluster SEs for descriptive associations; use FE when unobserved individual heterogeneity is likely correlated with regressors (the common case); use RE only when individual effects are plausibly random and uncorrelated with regressors (e.g., randomized experiments). The Hausman test helps decide between FE and RE, but economic reasoning should guide the choice.\n\n**What You've Learned:**\nIn this case study, you applied the complete panel data toolkit to cross-country productivity analysis. You decomposed variation into within and between components, compared pooled OLS with fixed effects, examined cluster-robust standard errors, and explored regional heterogeneity. These methods are essential for any empirical analysis using panel data.\n\n### Case Study 2: Luminosity and Development Over Time: A Panel Approach\n\n**Research Question**: How does nighttime luminosity evolve across Bolivia's municipalities over time, and what does within-municipality variation reveal about development dynamics?\n\n**Background**: Throughout this textbook, we have analyzed *cross-sectional* satellite-development relationships. But the DS4Bolivia dataset includes nighttime lights data for 2012-2020, creating a natural **panel dataset**. In this case study, we apply Chapter 17's panel data tools to track how luminosity evolves across municipalities over time, using fixed effects to control for time-invariant characteristics.\n\n**The Data**: The DS4Bolivia dataset covers 339 Bolivian municipalities with annual nighttime lights and population data for 2012-2020, yielding a potential panel of 3,051 municipality-year observations.\n\n**Key Variables**:\n\n- `mun`: Municipality name\n- `dep`: Department (administrative region)\n- `asdf_id`: Unique municipality identifier\n- `ln_NTLpc2012` through `ln_NTLpc2020`: Log nighttime lights per capita (annual)\n- `pop2012` through `pop2020`: Population (annual)\n\n#### Load the DS4Bolivia Data and Create Panel Structure\n\n::: {#0216b417 .cell execution_count=16}\n``` {.python .cell-code}\n# Load the DS4Bolivia dataset\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport pyfixest as pf\n\nurl_bol = \"https://raw.githubusercontent.com/quarcs-lab/ds4bolivia/master/ds4bolivia_v20250523.csv\"\nbol = pd.read_csv(url_bol)\n\n# Display available NTL and population variables\nntl_vars = [c for c in bol.columns if c.startswith('ln_NTLpc')]\npop_vars = [c for c in bol.columns if c.startswith('pop') and c[3:].isdigit()]\n\n# Ds4Bolivia: Panel Data Case Study\nprint(f\"Cross-sectional units: {len(bol)} municipalities\")\nprint(f\"\\nNTL variables available: {ntl_vars}\")\nprint(f\"Population variables available: {pop_vars}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCross-sectional units: 339 municipalities\n\nNTL variables available: ['ln_NTLpc2012', 'ln_NTLpc2013', 'ln_NTLpc2014', 'ln_NTLpc2015', 'ln_NTLpc2016', 'ln_NTLpc2017', 'ln_NTLpc2018', 'ln_NTLpc2019', 'ln_NTLpc2020']\nPopulation variables available: ['pop2001', 'pop2002', 'pop2003', 'pop2004', 'pop2005', 'pop2006', 'pop2007', 'pop2008', 'pop2009', 'pop2010', 'pop2011', 'pop2012', 'pop2013', 'pop2014', 'pop2015', 'pop2016', 'pop2017', 'pop2018', 'pop2019', 'pop2020']\n```\n:::\n:::\n\n\n#### Task 1: Create Panel Dataset (Guided)\n\n**Objective**: Reshape the wide-format DS4Bolivia data into a long panel dataset.\n\n**Instructions**:\n\n1. Select municipality identifiers (`mun`, `dep`, `asdf_id`) and annual NTL/population variables\n2. Reshape from wide to long format using `pd.melt()` or manual reshaping\n3. Create columns: `municipality`, `year`, `ln_NTLpc`, `pop`, `ln_pop`\n4. Verify the panel structure: 339 municipalities x 9 years = 3,051 observations\n5. Show `head()` and `describe()` for the panel dataset\n\n::: {#2e9a5dd9 .cell execution_count=17}\n``` {.python .cell-code}\n# Your code here: Reshape to panel format\n#\n# Example structure:\n# # Reshape NTL variables\n# ntl_cols = {f'ln_NTLpc{y}': y for y in range(2012, 2021)}\n# pop_cols = {f'pop{y}': y for y in range(2012, 2021)}\n#\n# # Melt NTL\n# ntl_long = bol[['mun', 'dep', 'asdf_id'] + list(ntl_cols.keys())].melt(\n#     id_vars=['mun', 'dep', 'asdf_id'],\n#     var_name='ntl_var', value_name='ln_NTLpc'\n# )\n# ntl_long['year'] = ntl_long['ntl_var'].str.extract(r'(\\d{4})').astype(int)\n#\n# # Melt Population\n# pop_long = bol[['asdf_id'] + list(pop_cols.keys())].melt(\n#     id_vars=['asdf_id'],\n#     var_name='pop_var', value_name='pop'\n# )\n# pop_long['year'] = pop_long['pop_var'].str.extract(r'(\\d{4})').astype(int)\n#\n# # Merge\n# panel = ntl_long.merge(pop_long[['asdf_id', 'year', 'pop']],\n#                        on=['asdf_id', 'year'], how='left')\n# panel['ln_pop'] = np.log(panel['pop'])\n# panel = panel.sort_values(['asdf_id', 'year']).reset_index(drop=True)\n#\n# print(f\"Panel shape: {panel.shape}\")\n# print(f\"Municipalities: {panel['asdf_id'].nunique()}\")\n# print(f\"Years: {sorted(panel['year'].unique())}\")\n# print(panel.head(18))  # Show 2 municipalities\n# print(panel[['ln_NTLpc', 'ln_pop', 'pop']].describe().round(3))\n```\n:::\n\n\n> **Key Concept 17.10: Satellite Panel Data**\n>\n> Annual nighttime lights observations create **panel datasets** even where traditional economic surveys are unavailable or infrequent. For Bolivia's 339 municipalities over 2012-2020, the NTL panel provides 3,051 municipality-year observations. This temporal dimension allows us to move beyond cross-sectional associations and study *changes within municipalities over time*—a crucial step toward understanding development dynamics rather than just static patterns.\n\n#### Task 2: Pooled OLS with Cluster-Robust SEs (Guided)\n\n**Objective**: Estimate a pooled OLS regression of NTL on population with cluster-robust standard errors.\n\n**Instructions**:\n\n1. Estimate `ln_NTLpc ~ ln_pop + year` using all panel observations\n2. Use cluster-robust standard errors clustered by municipality\n3. Compare default and cluster-robust SEs\n4. Interpret: How does population relate to NTL? Is there a significant time trend?\n\n::: {#169b7267 .cell execution_count=18}\n``` {.python .cell-code}\n# Your code here: Pooled OLS with cluster-robust SEs\n#\n# Example structure:\n# panel_reg = panel[['ln_NTLpc', 'ln_pop', 'year', 'mun', 'asdf_id']].dropna()\n#\n# fit_pooled = pf.feols('ln_NTLpc ~ ln_pop + year', data=panel_reg, vcov={'CRV1': 'asdf_id'})\n# print(\"POOLED OLS WITH CLUSTER-ROBUST SEs\")\n# print(model_pooled.summary())\n```\n:::\n\n\n#### Task 3: Fixed Effects (Semi-guided)\n\n**Objective**: Estimate a fixed effects model controlling for time-invariant municipality characteristics.\n\n**Instructions**:\n\n1. Add municipality fixed effects using `C(asdf_id)` or entity demeaning\n2. Compare FE coefficients with pooled OLS coefficients\n3. How does controlling for time-invariant municipality characteristics change the population-NTL relationship?\n4. Discuss: What unobserved factors do municipality fixed effects absorb (altitude, remoteness, climate)?\n\n**Hint**: You can use `C(asdf_id)` in the formula, or manually demean variables by subtracting municipality means. For large datasets, demeaning is more computationally efficient.\n\n::: {#6d6a32f8 .cell execution_count=19}\n``` {.python .cell-code}\n# Your code here: Fixed effects estimation\n#\n# Example structure (demeaning approach):\n# # Demean variables within each municipality\n# for col in ['ln_NTLpc', 'ln_pop']:\n#     panel_reg[f'{col}_dm'] = panel_reg.groupby('asdf_id')[col].transform(\n#         lambda x: x - x.mean()\n#     )\n# panel_reg['year_dm'] = panel_reg['year'] - panel_reg.groupby('asdf_id')['year'].transform('mean')\n#\n# fit_fe = pf.feols('ln_NTLpc ~ ln_pop + year | asdf_id', data=panel_reg, vcov={'CRV1': 'asdf_id'})\n# print(\"FIXED EFFECTS (WITHIN ESTIMATOR)\")\n# print(fit_fe.summary())\n#\n# print(\"\\nCOMPARISON:\")\n# print(f\"  Pooled OLS ln_pop coef: {fit_pooled.coef()['ln_pop']:.4f}\")\n# print(f\"  Fixed Effects ln_pop coef: {fit_fe.coef()['ln_pop']:.4f}\")\n```\n:::\n\n\n> **Key Concept 17.11: Fixed Effects for Spatial Heterogeneity**\n>\n> Municipality fixed effects absorb all **time-invariant characteristics**: altitude, remoteness, climate, historical infrastructure, cultural factors. After removing these fixed differences, the remaining variation identifies how *changes* in population (or other time-varying factors) relate to *changes* in NTL within the same municipality. This within-municipality analysis is more credible for causal interpretation than cross-sectional regressions, because it eliminates bias from unobserved time-invariant confounders.\n\n#### Task 4: Time Trends (Semi-guided)\n\n**Objective**: Examine how nighttime lights evolve over time using year fixed effects.\n\n**Instructions**:\n\n1. Replace the linear time trend with year dummy variables: `C(year)`\n2. Test whether the year effects are jointly significant\n3. Plot the estimated year coefficients to visualize the NTL trajectory\n4. Discuss: Did NTL grow steadily, or were there jumps or declines?\n\n**Hint**: Use one year as the reference category. The year coefficients show NTL changes relative to the base year.\n\n::: {#eebb21cb .cell execution_count=20}\n``` {.python .cell-code}\n# Your code here: Year fixed effects\n#\n# Example structure:\n# # Estimate with year dummies (demeaned for municipality FE)\n# panel_reg['year_cat'] = panel_reg['year'].astype(str)\n#\n# # Simple approach: use year means of demeaned NTL\n# year_means = panel_reg.groupby('year')['ln_NTLpc'].mean()\n# year_means_dm = year_means - year_means.iloc[0]  # relative to base year\n#\n# fig, ax = plt.subplots(figsize=(10, 6))\n# ax.plot(year_means.index, year_means.values, 'o-', color='navy', linewidth=2)\n# ax.set_xlabel('Year')\n# ax.set_ylabel('Mean Log NTL per Capita')\n# ax.set_title('Average Municipal NTL Over Time (2012-2020)')\n# ax.grid(True, alpha=0.3)\n# plt.tight_layout()\n# plt.show()\n```\n:::\n\n\n#### Task 5: First Differences (Independent)\n\n**Objective**: Estimate the relationship using first differences as an alternative to fixed effects.\n\n**Instructions**:\n\n1. Compute first differences: $\\Delta ln\\_NTLpc = ln\\_NTLpc_t - ln\\_NTLpc_{t-1}$ and $\\Delta ln\\_pop = ln\\_pop_t - ln\\_pop_{t-1}$\n2. Estimate $\\Delta ln\\_NTLpc \\sim \\Delta ln\\_pop$\n3. Compare the first-difference coefficient with the fixed effects estimate\n4. Discuss: When do FE and FD give different results? What assumptions does each require?\n\n::: {#66660eea .cell execution_count=21}\n``` {.python .cell-code}\n# Your code here: First differences estimation\n#\n# Example structure:\n# panel_reg = panel_reg.sort_values(['asdf_id', 'year'])\n# panel_reg['d_ln_NTLpc'] = panel_reg.groupby('asdf_id')['ln_NTLpc'].diff()\n# panel_reg['d_ln_pop'] = panel_reg.groupby('asdf_id')['ln_pop'].diff()\n#\n# # Drop first year (no difference available)\n# fd_data = panel_reg.dropna(subset=['d_ln_NTLpc', 'd_ln_pop'])\n#\n# fit_fd = pf.feols('d_ln_NTLpc ~ d_ln_pop', data=fd_data, vcov={'CRV1': 'asdf_id'})\n# print(\"FIRST DIFFERENCES ESTIMATION\")\n# print(model_fd.summary())\n#\n# print(f\"\\nFD coefficient on ln_pop: {fit_fd.coef()['d_ln_pop']:.4f}\")\n```\n:::\n\n\n#### Task 6: Panel Brief (Independent)\n\n**Objective**: Write a 200-300 word brief summarizing your panel data analysis.\n\n**Your brief should address**:\n\n1. What do within-municipality changes in NTL reveal about development dynamics?\n2. How does the FE population coefficient differ from the cross-sectional (pooled OLS) one?\n3. What time trends in NTL are visible across 2012-2020?\n4. How do FE and FD estimates compare? Which assumptions matter most?\n5. What are the advantages and limitations of satellite panel data for tracking municipal development over time?\n6. What additional time-varying variables would improve the analysis?\n\n::: {#b92bec2e .cell execution_count=22}\n``` {.python .cell-code}\n# Your code here: Additional analysis for the panel brief\n#\n# You might want to:\n# 1. Decompose variance into between and within components\n# 2. Plot NTL trajectories for selected municipalities\n# 3. Compare growth rates across departments\n# 4. Create a summary table of all estimation results\n#\n# Example: Variance decomposition\n# overall_var = panel_reg['ln_NTLpc'].var()\n# between_var = panel_reg.groupby('asdf_id')['ln_NTLpc'].mean().var()\n# within_var = panel_reg.groupby('asdf_id')['ln_NTLpc'].apply(lambda x: x - x.mean()).var()\n# print(f\"Overall variance: {overall_var:.4f}\")\n# print(f\"Between variance: {between_var:.4f}\")\n# print(f\"Within variance:  {within_var:.4f}\")\n# print(f\"Between share:    {between_var/overall_var:.1%}\")\n```\n:::\n\n\n#### What You've Learned from This Case Study\n\nThis is the final DS4Bolivia case study in the textbook. Across 12 chapters, you have applied the complete econometric toolkit—from simple descriptive statistics (Chapter 1) through panel data methods (Chapter 17)—to study how satellite data can predict and monitor local economic development. The DS4Bolivia project demonstrates that modern data science and econometrics, combined with freely available satellite imagery, can contribute to SDG monitoring even in data-scarce contexts.\n\nIn this panel data analysis, you've applied Chapter 17's complete toolkit:\n\n- **Panel construction**: Reshaped cross-sectional data into a municipality-year panel\n- **Pooled OLS**: Estimated baseline relationships with cluster-robust standard errors\n- **Fixed effects**: Controlled for time-invariant municipality characteristics\n- **Time trends**: Examined the trajectory of nighttime lights across 2012-2020\n- **First differences**: Used an alternative estimation strategy and compared with FE\n- **Critical thinking**: Assessed what within-municipality variation reveals about development dynamics\n\n**Congratulations!** You have now completed the full DS4Bolivia case study arc across the textbook.\n\n---\n\n",
    "supporting": [
      "ch17_Panel_Data_Time_Series_Data_Causation_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}