{
  "hash": "29e1a66290964b088c2740aa859019ca",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 5. Bivariate Data Summary\nexecute:\n  enabled: true\n  warning: false\n---\n\n\n**metricsAI: An Introduction to Econometrics with Python and AI in the Cloud**\n\n*[Carlos Mendez](https://carlos-mendez.org)*\n\n<img src=\"https://raw.githubusercontent.com/quarcs-lab/metricsai/main/images/ch05_visual_summary.jpg\" alt=\"Chapter 05 Visual Summary\" width=\"100%\">\n\nThis notebook provides an interactive introduction to bivariate data analysis and simple linear regression using Python. You'll learn how to summarize relationships between two variables using correlation, scatter plots, and regression analysis. All code runs directly in Google Colab without any local setup.\n\n[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/quarcs-lab/metricsai/blob/main/notebooks_colab/ch05_Bivariate_Data_Summary.ipynb)\n<div class=\"chapter-resources\">\n<a href=\"https://www.youtube.com/watch?v=sVT1KfjoZQg\" target=\"_blank\" class=\"resource-btn\">🎬 AI Video</a>\n<a href=\"https://carlos-mendez.my.canva.site/s05-bivariate-data-summary-pdf\" target=\"_blank\" class=\"resource-btn\">✨ AI Slides</a>\n<a href=\"https://cameron.econ.ucdavis.edu/aed/traedv1_05\" target=\"_blank\" class=\"resource-btn\">📊 Cameron Slides</a>\n<a href=\"https://app.edcafe.ai/quizzes/697865de2f5d08069e0482cc\" target=\"_blank\" class=\"resource-btn\">✏️ Quiz</a>\n<a href=\"https://app.edcafe.ai/chatbots/69789e4c2f5d08069e0704c6\" target=\"_blank\" class=\"resource-btn\">🤖 AI Tutor</a>\n</div>\n\n\n## Chapter Overview\n\n**Bivariate data** involves observations on two variables—for example, house prices and house sizes, or income and education. This chapter teaches you how to summarize and analyze relationships between two variables using correlation and regression.\n\n**What you'll learn:**\n\n- Summarize bivariate relationships using two-way tabulations and scatterplots\n- Calculate and interpret correlation coefficients and understand their relationship to covariance\n- Estimate and interpret regression lines using ordinary least squares (OLS)\n- Evaluate model fit using R-squared, standard error, and variation decomposition\n- Make predictions and identify outliers in regression analysis\n- Understand the critical distinction between association and causation\n- Apply nonparametric regression methods to check linearity assumptions\n\n**Datasets used:**\n\n- **AED_HOUSE.DTA**: House prices and characteristics for 29 houses sold in Central Davis, California in 1999 (price, size, bedrooms, bathrooms, lot size, age)\n\n**Chapter outline:**\n\n- 5.1 Example - House Price and Size\n- 5.2 Two-Way Tabulation\n- 5.3 Two-Way Scatter Plot\n- 5.4 Sample Correlation\n- 5.5 Regression Line\n- 5.6 Measures of Model Fit\n- 5.7 Computer Output Following Regression\n- 5.8 Prediction and Outlying Observations\n- 5.9 Regression and Correlation\n- 5.10 Causation\n- 5.11 Nonparametric Regression\n\n## Setup\n\nFirst, we import the necessary Python packages and configure the environment for reproducibility. All data will stream directly from GitHub.\n\n::: {#504328bf .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Setup: Import libraries and configure environment\"}\n# --- Libraries ---\nimport numpy as np                                          # numerical operations\nimport pandas as pd                                         # data manipulation\nimport matplotlib.pyplot as plt                             # plotting\nimport seaborn as sns                                       # statistical visualization\nimport statsmodels.api as sm                                # statistical models\nfrom statsmodels.formula.api import ols                     # OLS with formula syntax\nfrom statsmodels.nonparametric.smoothers_lowess import lowess  # LOWESS smoothing\nfrom scipy import stats                                     # statistical distributions\nfrom scipy.ndimage import gaussian_filter1d                 # kernel smoothing\nimport random\nimport os\n\n# --- Reproducibility ---\nRANDOM_SEED = 42\nrandom.seed(RANDOM_SEED)\nnp.random.seed(RANDOM_SEED)\nos.environ['PYTHONHASHSEED'] = str(RANDOM_SEED)\n\n# --- Data source ---\nGITHUB_DATA_URL = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/\"\n\n# --- Plotting style ---\nplt.style.use('dark_background')\nsns.set_style(\"darkgrid\")\nplt.rcParams.update({\n    'axes.facecolor': '#1a2235',\n    'figure.facecolor': '#12162c',\n    'grid.color': '#3a4a6b',\n    'figure.figsize': (10, 6),\n    'text.color': 'white',\n    'axes.labelcolor': 'white',\n    'xtick.color': 'white',\n    'ytick.color': 'white',\n    'axes.edgecolor': '#1a2235',\n})\n\nprint(\"Setup complete! Ready to explore bivariate data analysis.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSetup complete! Ready to explore bivariate data analysis.\n```\n:::\n:::\n\n\n## 5.1 Example - House Price and Size\n\nWe begin by loading and examining data on house prices and sizes from 29 houses sold in Central Davis, California in 1999. This dataset will serve as our main example throughout the chapter.\n\n**Why this dataset?**\n\n- Small enough to see individual observations\n- Large enough to demonstrate statistical relationships\n- Economically meaningful: housing is a major component of wealth\n- Clear relationship: larger houses tend to cost more\n\n::: {#e0abc573 .cell execution_count=2}\n``` {.python .cell-code}\n# Load the house data\ndata_house = pd.read_stata(GITHUB_DATA_URL + 'AED_HOUSE.DTA')\n\nprint(\"Data loaded successfully!\")\nprint(f\"Number of observations: {len(data_house)}\")\nprint(f\"Number of variables: {data_house.shape[1]}\")\nprint(f\"\\nVariables: {', '.join(data_house.columns.tolist())}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData loaded successfully!\nNumber of observations: 29\nNumber of variables: 8\n\nVariables: price, size, bedrooms, bathrooms, lotsize, age, monthsold, list\n```\n:::\n:::\n\n\n::: {#ed18817b .cell execution_count=3}\n``` {.python .cell-code}\n# Table 5.1: Complete dataset\ndata_house\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>price</th>\n      <th>size</th>\n      <th>bedrooms</th>\n      <th>bathrooms</th>\n      <th>lotsize</th>\n      <th>age</th>\n      <th>monthsold</th>\n      <th>list</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>204000</td>\n      <td>1400</td>\n      <td>3</td>\n      <td>2.0</td>\n      <td>1</td>\n      <td>31.0</td>\n      <td>7</td>\n      <td>199900</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>212000</td>\n      <td>1600</td>\n      <td>3</td>\n      <td>3.0</td>\n      <td>2</td>\n      <td>33.0</td>\n      <td>5</td>\n      <td>212000</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>213000</td>\n      <td>1800</td>\n      <td>3</td>\n      <td>2.0</td>\n      <td>2</td>\n      <td>51.0</td>\n      <td>4</td>\n      <td>219900</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>220000</td>\n      <td>1600</td>\n      <td>3</td>\n      <td>2.0</td>\n      <td>1</td>\n      <td>49.0</td>\n      <td>4</td>\n      <td>229000</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>224500</td>\n      <td>2100</td>\n      <td>4</td>\n      <td>2.5</td>\n      <td>2</td>\n      <td>47.0</td>\n      <td>6</td>\n      <td>224500</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>229000</td>\n      <td>1700</td>\n      <td>4</td>\n      <td>2.5</td>\n      <td>2</td>\n      <td>35.0</td>\n      <td>3</td>\n      <td>229500</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>230000</td>\n      <td>2100</td>\n      <td>4</td>\n      <td>2.0</td>\n      <td>2</td>\n      <td>34.0</td>\n      <td>8</td>\n      <td>239000</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>233000</td>\n      <td>1700</td>\n      <td>3</td>\n      <td>2.0</td>\n      <td>1</td>\n      <td>40.0</td>\n      <td>6</td>\n      <td>244500</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>235000</td>\n      <td>1700</td>\n      <td>4</td>\n      <td>2.0</td>\n      <td>2</td>\n      <td>29.0</td>\n      <td>7</td>\n      <td>245000</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>235000</td>\n      <td>1600</td>\n      <td>3</td>\n      <td>2.0</td>\n      <td>3</td>\n      <td>35.0</td>\n      <td>5</td>\n      <td>242000</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>236500</td>\n      <td>1600</td>\n      <td>3</td>\n      <td>2.0</td>\n      <td>3</td>\n      <td>23.0</td>\n      <td>8</td>\n      <td>239500</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>238000</td>\n      <td>1900</td>\n      <td>4</td>\n      <td>2.0</td>\n      <td>2</td>\n      <td>29.0</td>\n      <td>7</td>\n      <td>249000</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>239500</td>\n      <td>1600</td>\n      <td>3</td>\n      <td>2.0</td>\n      <td>3</td>\n      <td>34.0</td>\n      <td>6</td>\n      <td>239500</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>241000</td>\n      <td>1600</td>\n      <td>4</td>\n      <td>2.0</td>\n      <td>2</td>\n      <td>34.0</td>\n      <td>8</td>\n      <td>242500</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>244000</td>\n      <td>2000</td>\n      <td>4</td>\n      <td>2.0</td>\n      <td>1</td>\n      <td>29.0</td>\n      <td>7</td>\n      <td>249000</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>245000</td>\n      <td>1400</td>\n      <td>4</td>\n      <td>2.0</td>\n      <td>2</td>\n      <td>30.0</td>\n      <td>8</td>\n      <td>252000</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>249000</td>\n      <td>1900</td>\n      <td>4</td>\n      <td>3.0</td>\n      <td>3</td>\n      <td>37.0</td>\n      <td>6</td>\n      <td>235000</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>253000</td>\n      <td>2100</td>\n      <td>4</td>\n      <td>2.0</td>\n      <td>3</td>\n      <td>47.0</td>\n      <td>6</td>\n      <td>269000</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>255000</td>\n      <td>1500</td>\n      <td>4</td>\n      <td>2.0</td>\n      <td>3</td>\n      <td>47.0</td>\n      <td>7</td>\n      <td>240000</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>258500</td>\n      <td>1600</td>\n      <td>3</td>\n      <td>2.0</td>\n      <td>1</td>\n      <td>39.0</td>\n      <td>8</td>\n      <td>259900</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>270000</td>\n      <td>1800</td>\n      <td>4</td>\n      <td>2.0</td>\n      <td>3</td>\n      <td>31.0</td>\n      <td>3</td>\n      <td>263900</td>\n    </tr>\n    <tr>\n      <th>21</th>\n      <td>270000</td>\n      <td>2000</td>\n      <td>4</td>\n      <td>2.5</td>\n      <td>3</td>\n      <td>39.0</td>\n      <td>5</td>\n      <td>269000</td>\n    </tr>\n    <tr>\n      <th>22</th>\n      <td>272000</td>\n      <td>1800</td>\n      <td>4</td>\n      <td>2.5</td>\n      <td>2</td>\n      <td>46.0</td>\n      <td>3</td>\n      <td>279500</td>\n    </tr>\n    <tr>\n      <th>23</th>\n      <td>273000</td>\n      <td>1900</td>\n      <td>5</td>\n      <td>2.0</td>\n      <td>2</td>\n      <td>37.0</td>\n      <td>7</td>\n      <td>273000</td>\n    </tr>\n    <tr>\n      <th>24</th>\n      <td>278500</td>\n      <td>2600</td>\n      <td>6</td>\n      <td>2.0</td>\n      <td>3</td>\n      <td>38.0</td>\n      <td>8</td>\n      <td>280000</td>\n    </tr>\n    <tr>\n      <th>25</th>\n      <td>279900</td>\n      <td>2000</td>\n      <td>4</td>\n      <td>2.0</td>\n      <td>2</td>\n      <td>31.0</td>\n      <td>7</td>\n      <td>279900</td>\n    </tr>\n    <tr>\n      <th>26</th>\n      <td>310000</td>\n      <td>2300</td>\n      <td>4</td>\n      <td>2.5</td>\n      <td>2</td>\n      <td>28.0</td>\n      <td>5</td>\n      <td>315000</td>\n    </tr>\n    <tr>\n      <th>27</th>\n      <td>340000</td>\n      <td>2400</td>\n      <td>4</td>\n      <td>3.0</td>\n      <td>2</td>\n      <td>34.0</td>\n      <td>6</td>\n      <td>369900</td>\n    </tr>\n    <tr>\n      <th>28</th>\n      <td>375000</td>\n      <td>3300</td>\n      <td>4</td>\n      <td>2.5</td>\n      <td>2</td>\n      <td>39.0</td>\n      <td>3</td>\n      <td>386000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#726f1989 .cell execution_count=4}\n``` {.python .cell-code}\n# Table 5.2: Summary statistics\ndisplay(data_house[['price', 'size']].describe())\n\n# Extract key variables\nprice = data_house['price']\nsize = data_house['size']\n\nprint(\"\\nPrice Statistics:\")\nprint(f\"  Mean:      ${price.mean():,.2f}\")\nprint(f\"  Median:    ${price.median():,.2f}\")\nprint(f\"  Min:       ${price.min():,.2f}\")\nprint(f\"  Max:       ${price.max():,.2f}\")\nprint(f\"  Std Dev:   ${price.std():,.2f}\")\n\nprint(\"\\nSize Statistics:\")\nprint(f\"  Mean:      {size.mean():,.0f} sq ft\")\nprint(f\"  Median:    {size.median():,.0f} sq ft\")\nprint(f\"  Min:       {size.min():,.0f} sq ft\")\nprint(f\"  Max:       {size.max():,.0f} sq ft\")\nprint(f\"  Std Dev:   {size.std():,.0f} sq ft\")\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>price</th>\n      <th>size</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>29.000000</td>\n      <td>29.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>253910.344828</td>\n      <td>1882.758621</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>37390.710695</td>\n      <td>398.272130</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>204000.000000</td>\n      <td>1400.000000</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>233000.000000</td>\n      <td>1600.000000</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>244000.000000</td>\n      <td>1800.000000</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>270000.000000</td>\n      <td>2000.000000</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>375000.000000</td>\n      <td>3300.000000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nPrice Statistics:\n  Mean:      $253,910.34\n  Median:    $244,000.00\n  Min:       $204,000.00\n  Max:       $375,000.00\n  Std Dev:   $37,390.71\n\nSize Statistics:\n  Mean:      1,883 sq ft\n  Median:    1,800 sq ft\n  Min:       1,400 sq ft\n  Max:       3,300 sq ft\n  Std Dev:   398 sq ft\n```\n:::\n:::\n\n\n> **Key Concept 5.1: Summary Statistics for Bivariate Data**\n>\n> Summary statistics describe the center, spread, and range of each variable before examining their relationship. For bivariate analysis, compute the mean, median, standard deviation, minimum, and maximum of both variables. Comparing means and medians reveals skewness; standard deviations indicate variability. These univariate summaries provide essential context for interpreting correlation and regression results.\n\n**What do these numbers tell us about the Davis housing market (1999)?**\n\n**Price Statistics:**\n\n- **Mean = \\$253,910**: Average house price in the sample\n- **Median = \\$244,000**: Middle value (half above, half below)\n- **Range**: \\$204,000 to \\$375,000 (spread of \\$171,000)\n- **Std Dev = \\$37,391**: Typical deviation from the mean\n\n**Size Statistics:**\n\n- **Mean = 1,883 sq ft**: Average house size\n- **Median = 1,800 sq ft**: Middle value\n- **Range**: 1,400 to 3,300 sq ft (spread of 1,900 sq ft)\n- **Std Dev = 398 sq ft**: Typical deviation from the mean\n\n**Key insights:**\n\n- Both distributions are fairly symmetric (means close to medians)\n- Substantial variation in both price and size (good for regression!)\n- The price coefficient of variation (CV = 0.15) and size CV (0.21) show moderate variability\n- **Moving from univariate to bivariate**: In Chapter 2, we looked at single variables. Now we ask: *how do these two variables move together?*\n\n**Economic context:** These are moderate-sized homes in a California college town (UC Davis), with typical prices for the late 1990s.\n\n**Key observations:**\n\n- House prices range from \\$204,000 to \\$375,000 (mean: \\$253,910)\n- House sizes range from 1,400 to 3,300 square feet (mean: 1,883 sq ft)\n- Both variables show substantial variation, which is good for regression analysis\n- The data appear to be reasonably symmetric (means close to medians)\n\n## 5.2 Two-Way Tabulation\n\nA **two-way tabulation** (or crosstabulation) shows how observations are distributed across combinations of two categorical variables. For continuous variables like price and size, we first create categorical ranges.\n\n**Why use tabulation?**\n\n- Provides a quick summary of the relationship\n- Useful for discrete or categorical data\n- Can reveal patterns before formal analysis\n\n::: {#7916f13e .cell execution_count=5}\n``` {.python .cell-code}\n# Create categorical variables\nprice_range = pd.cut(price, bins=[0, 249999, np.inf],\n                     labels=['< $250,000', '≥ $250,000'])\n\nsize_range = pd.cut(size, bins=[0, 1799, 2399, np.inf],\n                    labels=['< 1,800', '1,800-2,399', '≥ 2,400'])\n\n# Two-way tabulation of price and size\ncrosstab = pd.crosstab(price_range, size_range, margins=True)\ncrosstab\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>size</th>\n      <th>&lt; 1,800</th>\n      <th>1,800-2,399</th>\n      <th>≥ 2,400</th>\n      <th>All</th>\n    </tr>\n    <tr>\n      <th>price</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>&lt; $250,000</th>\n      <td>11</td>\n      <td>6</td>\n      <td>0</td>\n      <td>17</td>\n    </tr>\n    <tr>\n      <th>≥ $250,000</th>\n      <td>2</td>\n      <td>7</td>\n      <td>3</td>\n      <td>12</td>\n    </tr>\n    <tr>\n      <th>All</th>\n      <td>13</td>\n      <td>13</td>\n      <td>3</td>\n      <td>29</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n**What to look for:** 11 houses are both low-priced and small; 0 houses are both low-priced and large (>= 2,400 sq ft); 3 houses are both high-priced and large. The pattern suggests positive association: larger houses tend to be more expensive.\n\n> **Key Concept 5.2: Two-Way Tabulations**\n>\n> Two-way tabulations show the joint distribution of two categorical variables. Expected frequencies (calculated assuming independence) provide the basis for Pearson's chi-squared test of statistical independence. The crosstabulation reveals patterns: no low-priced large houses suggests a positive association between size and price.\n\n**What does this crosstab tell us?**\n\nLooking at the table:\n\n- **11 houses** are both small (< 1,800 sq ft) AND low-priced (< \\$250,000)\n- **0 houses** are both large (≥ 2,400 sq ft) AND low-priced\n- **3 houses** are both large (≥ 2,400 sq ft) AND high-priced (≥ \\$250,000)\n- **6 houses** are medium-sized (1,800-2,399 sq ft) AND low-priced\n\n**The pattern reveals:**\n\n- **Positive association**: Most observations cluster in the \"small and cheap\" or \"large and expensive\" cells\n- **No counterexamples**: We never see \"large and cheap\" houses (the bottom-right cell is empty)\n- **Imperfect relationship**: Some medium-sized houses are low-priced (6 houses), some are high-priced (7 houses)\n\n**Limitation of tabulation:**\n\n- We lose information by categorizing continuous variables\n- We can't quantify the strength of the relationship\n- We can't make precise predictions\n\n**Next step:** Use the correlation coefficient and regression to measure the relationship more precisely using the full continuous data.\n\n**From Categorical to Continuous:**\n\nCrosstabulation is useful but has limitations:\n\n- **Information loss**: We convert continuous data (exact prices/sizes) into categories\n- **Arbitrary bins**: Results can change depending on where we draw category boundaries\n- **No precise measurement**: Can't quantify exact strength of relationship\n\n**Solution**: Use the full continuous data with **correlation** and **regression** to:\n\n- Preserve all information in the original measurements\n- Get precise, interpretable measures (r, slope)\n- Make specific predictions for any value of x\n\n## 5.3 Two-Way Scatter Plot\n\nA **scatter plot** is the primary visual tool for examining the relationship between two continuous variables. Each point represents one observation, with x-coordinate showing size and y-coordinate showing price.\n\n**What to look for:**\n\n- **Direction:** Does y increase or decrease as x increases?\n- **Strength:** How closely do points follow a pattern?\n- **Form:** Is the relationship linear or curved?\n- **Outliers:** Are there unusual observations far from the pattern?\n\n::: {#26a57400 .cell execution_count=6}\n``` {.python .cell-code}\n# Scatter plot of price vs size\nfig, ax = plt.subplots(figsize=(10, 6))\nax.scatter(size, price, s=80, alpha=0.7, color='#22d3ee', edgecolor='#3a4a6b')  # s = marker size, alpha = transparency\nax.set_xlabel('House size (in square feet)', fontsize=12)\nax.set_ylabel('House sale price (in dollars)', fontsize=12)\nax.set_title('House Price vs Size', fontsize=14, fontweight='bold')\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch05_Bivariate_Data_Summary_files/figure-html/cell-7-output-1.png){width=950 height=565}\n:::\n:::\n\n\n**What to look for in this scatter plot:**\n\n- **Direction**: Positive -- larger houses tend to have higher prices\n- **Form**: Roughly linear -- points follow an upward-sloping pattern\n- **Scatter**: Moderate -- not all points lie exactly on a line\n- **Outliers**: None obvious -- all points fit the general pattern\n\n> **Key Concept 5.3: Scatterplots and Relationships**\n>\n> Scatterplots provide visual evidence of relationships between two continuous variables. They reveal the direction (positive/negative), strength (tight/loose clustering), form (linear/curved), and outliers of the relationship. The house price-size scatterplot shows a strong, positive, roughly linear relationship with no obvious outliers.\n\n**Visual vs. Quantitative Analysis:**\n\nThe scatter plot provides **qualitative** insight (direction, form, outliers), but we need **quantitative** measures to:\n\n- **Communicate precisely**: \"Strong positive relationship\" is vague; \"r = 0.79\" is specific\n- **Compare across studies**: Can't compare scatter plots directly across datasets\n- **Test hypotheses**: Need numerical values for statistical inference (Chapter 7)\n- **Make predictions**: Visual estimates from graphs are imprecise\n\n**Next**: We'll quantify this relationship using the correlation coefficient.\n\n**What patterns do we observe?**\n\n**1. Direction: Positive relationship**\n\n- As house size increases (moving right), house price increases (moving up)\n- This makes economic sense: bigger houses should cost more\n\n**2. Form: Roughly linear**\n\n- Points follow an upward-sloping pattern\n- No obvious curvature (e.g., not exponential or U-shaped)\n- A straight line appears to be a reasonable summary\n\n**3. Strength: Moderate to strong**\n\n- Points cluster fairly closely around an imaginary line\n- Not perfect (some scatter), but clear pattern visible\n- We'll quantify this with the correlation coefficient\n\n**4. Outliers: None obvious**\n\n- No houses wildly far from the general pattern\n- All observations seem consistent with the relationship\n\n**Comparison to univariate analysis (Chapter 2):**\n\n- **Univariate**: Histogram shows distribution of one variable\n- **Bivariate**: Scatter plot shows *relationship* between two variables\n- **New question**: How does Y change when X changes?\n\n**What we can't tell from the graph alone:**\n\n- Exact strength of relationship (need correlation)\n- Precise prediction equation (need regression)\n- Statistical significance (need inference, Chapter 7)\n\n## 5.4 Sample Correlation\n\nThe **correlation coefficient** $r$ is a unit-free measure of linear association between two variables. It ranges from -1 to 1:\n\n- $r = 1$: Perfect positive linear relationship\n- \\$0 < r < 1$: Positive linear relationship\n- $r = 0$: No linear relationship\n- $-1 < r < 0$: Negative linear relationship\n- $r = -1$: Perfect negative linear relationship\n\n**Formula:**\n$$r_{xy} = \\frac{\\sum_{i=1}^{n}(x_i - \\bar{x})(y_i - \\bar{y})}{\\sqrt{\\sum_{i=1}^{n}(x_i - \\bar{x})^2 \\times \\sum_{i=1}^{n}(y_i - \\bar{y})^2}} = \\frac{s_{xy}}{s_x s_y}$$\n\nwhere $s_{xy}$ is the sample covariance, and $s_x$, $s_y$ are sample standard deviations.\n\n**Key Properties of Correlation:**\n\nUnderstanding these properties helps avoid common misinterpretations:\n\n1. **Unit-free**: r = 0.79 whether we measure price in dollars, thousands, or millions\n2. **Bounded**: Always between -1 and +1 (unlike covariance, which is unbounded)\n3. **Symmetric**: r(price, size) = r(size, price) — order doesn't matter\n4. **Only measures linear relationships**: Can miss curved, U-shaped, or other nonlinear patterns\n5. **Sensitive to outliers**: One extreme point can dramatically change r\n\n**Limitation**: Correlation is a summary measure but doesn't provide predictions. For that, we need **regression**.\n\n::: {#8e1a1527 .cell execution_count=7}\n``` {.python .cell-code}\n# Compute correlation and covariance\ncov_matrix = data_house[['price', 'size']].cov()\ncorr_matrix = data_house[['price', 'size']].corr()\n\n# Covariance and correlation\n\n# Covariance matrix\ndisplay(cov_matrix)\n\n# Correlation matrix\ndisplay(corr_matrix)\n\nr = corr_matrix.loc['price', 'size']\nprint(f\"\\nCorrelation coefficient: r = {r:.4f}\")\nprint(f\"\\nInterpretation:\")\nprint(f\"  The correlation of {r:.4f} indicates a strong positive linear\")\nprint(f\"  relationship between house price and size.\")\nprint(f\"  About {r**2:.1%} of the variation in price is linearly associated\")\nprint(f\"  with variation in size.\")\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>price</th>\n      <th>size</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>price</th>\n      <td>1.398065e+09</td>\n      <td>1.170161e+07</td>\n    </tr>\n    <tr>\n      <th>size</th>\n      <td>1.170161e+07</td>\n      <td>1.586207e+05</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>price</th>\n      <th>size</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>price</th>\n      <td>1.000000</td>\n      <td>0.785782</td>\n    </tr>\n    <tr>\n      <th>size</th>\n      <td>0.785782</td>\n      <td>1.000000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCorrelation coefficient: r = 0.7858\n\nInterpretation:\n  The correlation of 0.7858 indicates a strong positive linear\n  relationship between house price and size.\n  About 61.7% of the variation in price is linearly associated\n  with variation in size.\n```\n:::\n:::\n\n\n> **Key Concept 5.4: The Correlation Coefficient**\n>\n> The correlation coefficient (r) is a scale-free measure of linear association ranging from -1 (perfect negative) to +1 (perfect positive). A correlation of 0 indicates no linear relationship. For house price and size, r = 0.786 indicates strong positive correlation. The correlation is unit-free, symmetric, and measures only linear relationships.\n\n**What does r = 0.7858 mean?**\n\n**1. Strength of linear association:**\n\n- **r = 0.7858** indicates a **strong positive** linear relationship\n- Scale reference:\n  - |r| < 0.3: weak\n  - 0.3 ≤ |r| < 0.7: moderate\n  - |r| ≥ 0.7: strong\n- Our value (0.79) is well into the \"strong\" range\n\n**2. Direction:**\n\n- **Positive**: Larger houses are associated with higher prices\n- If r were negative, larger houses would be associated with lower prices (unlikely for housing!)\n\n**3. Variance explained (preview):**\n\n- r² = (0.7858)² = 0.617 = **61.7%**\n- About 62% of price variation is linearly associated with size variation\n- The remaining 38% is due to other factors (location, age, condition, etc.)\n\n**4. Properties of correlation:**\n\n- **Unit-free**: Same value whether we measure price in dollars or thousands of dollars\n- **Symmetric**: r(price, size) = r(size, price) = 0.7858\n- **Bounded**: Always between -1 and +1\n- **Linear measure**: Detects linear relationships, not curves\n\n**Comparison to Chapter 2 (univariate):**\n\n- Chapter 2: Standard deviation measures spread of ONE variable\n- Chapter 5: Correlation measures how TWO variables move together\n- Both are standardized measures (unit-free)\n\n**Economic interpretation:** The strong correlation confirms what we saw in the scatter plot: house size is a major determinant of house price, but it's not the only factor.\n\n### Illustration: Different Correlation Patterns\n\nTo build intuition, let's visualize simulated data with different correlation coefficients.\n\n::: {#291ab372 .cell execution_count=8}\n``` {.python .cell-code}\n# Different correlation patterns\nnp.random.seed(12345)\nn = 30\nx = np.random.normal(3, 1, n)\nu1 = np.random.normal(0, 0.8, n)\ny1 = 3 + x + u1  # Strong positive correlation\nu2 = np.random.normal(0, 2, n)\ny2 = 3 + x + u2  # Moderate positive correlation\ny3 = 5 + u2      # Zero correlation\ny4 = 10 - x - u2 # Moderate negative correlation\n\ncorrelations = [\n    np.corrcoef(x, y1)[0, 1],\n    np.corrcoef(x, y2)[0, 1],\n    np.corrcoef(x, y3)[0, 1],\n    np.corrcoef(x, y4)[0, 1]\n]\n\nfig, axes = plt.subplots(2, 2, figsize=(14, 12))\naxes = axes.flatten()\n\ndatasets = [(x, y1, 'Panel A: Strong Positive'),\n            (x, y2, 'Panel B: Moderate Positive'),\n            (x, y3, 'Panel C: Zero Correlation'),\n            (x, y4, 'Panel D: Moderate Negative')]\n\nfor idx, (ax, (x_data, y_data, title), corr) in enumerate(zip(axes, datasets, correlations)):\n    ax.scatter(x_data, y_data, s=60, alpha=0.7, color='#22d3ee', edgecolor='#3a4a6b')\n    ax.set_xlabel('x', fontsize=11)\n    ax.set_ylabel('y', fontsize=11)\n    ax.set_title(f'{title}\\nr = {corr:.2f}', fontsize=12, fontweight='bold')\n    ax.grid(True, alpha=0.3)\n\nplt.suptitle('Different Correlation Patterns',\n             fontsize=14, fontweight='bold', y=0.995)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch05_Bivariate_Data_Summary_files/figure-html/cell-9-output-1.png){width=1334 height=1151}\n:::\n:::\n\n\n**What to look for in each panel:**\n\n- **Panel A** (r ~ 0.78): Points cluster tightly around an upward slope\n- **Panel B** (r ~ 0.44): More scatter, but still positive relationship\n- **Panel C** (r ~ 0.00): No systematic pattern\n- **Panel D** (r ~ -0.53): Points follow a downward slope\n\n## 5.5 Regression Line\n\nThe **regression line** provides the \"best-fitting\" linear summary of the relationship between y (dependent variable) and x (independent variable):\n\n$$\\hat{y} = b_1 + b_2 x$$\n\nwhere:\n\n- $\\hat{y}$ = predicted (fitted) value of y\n- $b_1$ = intercept (predicted y when x = 0)\n- $b_2$ = slope (change in y for one-unit increase in x)\n\n**Ordinary Least Squares (OLS)** chooses $b_1$ and $b_2$ to minimize the sum of squared residuals:\n\n$$\\min_{b_1, b_2} \\sum_{i=1}^n (y_i - b_1 - b_2 x_i)^2$$\n\n**Formulas:**\n$$b_2 = \\frac{\\sum_{i=1}^n (x_i - \\bar{x})(y_i - \\bar{y})}{\\sum_{i=1}^n (x_i - \\bar{x})^2} = \\frac{s_{xy}}{s_x^2}$$\n\n$$b_1 = \\bar{y} - b_2 \\bar{x}$$\n\nCorrelation measures the strength of association, but doesn't provide a prediction equation. Now we turn to regression analysis, which fits a line to predict y from x and quantifies how much y changes per unit change in x.\n\n::: {#760d5ede .cell execution_count=9}\n``` {.python .cell-code}\n# Fit OLS regression\nmodel = ols('price ~ size', data=data_house).fit()\n\n# Key results\nintercept = model.params['Intercept']\nslope = model.params['size']\nr_squared = model.rsquared\nprint(f\"Estimated equation: price = {intercept:,.2f} + {slope:.4f} x size\")\nprint(f\"R-squared: {r_squared:.4f} ({r_squared*100:.1f}% of variation explained)\")\n\n# Full regression output\nmodel.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEstimated equation: price = 115,017.28 + 73.7710 x size\nR-squared: 0.6175 (61.7% of variation explained)\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=9}\n```{=html}\n<table class=\"simpletable\">\n<caption>OLS Regression Results</caption>\n<tr>\n  <th>Dep. Variable:</th>          <td>price</td>      <th>  R-squared:         </th> <td>   0.617</td>\n</tr>\n<tr>\n  <th>Model:</th>                   <td>OLS</td>       <th>  Adj. R-squared:    </th> <td>   0.603</td>\n</tr>\n<tr>\n  <th>Method:</th>             <td>Least Squares</td>  <th>  F-statistic:       </th> <td>   43.58</td>\n</tr>\n<tr>\n  <th>Date:</th>             <td>Tue, 07 Apr 2026</td> <th>  Prob (F-statistic):</th> <td>4.41e-07</td>\n</tr>\n<tr>\n  <th>Time:</th>                 <td>08:28:45</td>     <th>  Log-Likelihood:    </th> <td> -332.05</td>\n</tr>\n<tr>\n  <th>No. Observations:</th>      <td>    29</td>      <th>  AIC:               </th> <td>   668.1</td>\n</tr>\n<tr>\n  <th>Df Residuals:</th>          <td>    27</td>      <th>  BIC:               </th> <td>   670.8</td>\n</tr>\n<tr>\n  <th>Df Model:</th>              <td>     1</td>      <th>                     </th>     <td> </td>   \n</tr>\n<tr>\n  <th>Covariance Type:</th>      <td>nonrobust</td>    <th>                     </th>     <td> </td>   \n</tr>\n</table>\n<table class=\"simpletable\">\n<tr>\n      <td></td>         <th>coef</th>     <th>std err</th>      <th>t</th>      <th>P>|t|</th>  <th>[0.025</th>    <th>0.975]</th>  \n</tr>\n<tr>\n  <th>Intercept</th> <td>  1.15e+05</td> <td> 2.15e+04</td> <td>    5.352</td> <td> 0.000</td> <td> 7.09e+04</td> <td> 1.59e+05</td>\n</tr>\n<tr>\n  <th>size</th>      <td>   73.7710</td> <td>   11.175</td> <td>    6.601</td> <td> 0.000</td> <td>   50.842</td> <td>   96.700</td>\n</tr>\n</table>\n<table class=\"simpletable\">\n<tr>\n  <th>Omnibus:</th>       <td> 0.576</td> <th>  Durbin-Watson:     </th> <td>   1.219</td>\n</tr>\n<tr>\n  <th>Prob(Omnibus):</th> <td> 0.750</td> <th>  Jarque-Bera (JB):  </th> <td>   0.638</td>\n</tr>\n<tr>\n  <th>Skew:</th>          <td>-0.078</td> <th>  Prob(JB):          </th> <td>   0.727</td>\n</tr>\n<tr>\n  <th>Kurtosis:</th>      <td> 2.290</td> <th>  Cond. No.          </th> <td>9.45e+03</td>\n</tr>\n</table><br/><br/>Notes:<br/>[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.<br/>[2] The condition number is large, 9.45e+03. This might indicate that there are<br/>strong multicollinearity or other numerical problems.\n```\n:::\n:::\n\n\n> **Key Concept 5.5: Ordinary Least Squares**\n>\n> The method of ordinary least squares (OLS) chooses the regression line to minimize the sum of squared residuals. This yields formulas for the slope (b₂ = Σ(xᵢ - x̄)(yᵢ - ȳ) / Σ(xᵢ - x̄)²) and intercept (b₁ = ȳ - b₂x̄) that can be computed from the data. The slope equals the covariance divided by the variance of x.\n\n::: {#d3d51490 .cell execution_count=10}\n``` {.python .cell-code}\n# Extract and interpret coefficients\nintercept = model.params['Intercept']\nslope = model.params['size']\nr_squared = model.rsquared\n\n# Key regression coefficients\nprint(f\"Fitted regression line:\")\nprint(f\"  ŷ = {intercept:,.2f} + {slope:.2f} × size\")\nprint(f\"\\nIntercept (b₁): ${intercept:,.2f}\")\nprint(f\"  Interpretation: Predicted price when size = 0\")\nprint(f\"  (Not economically meaningful in this case)\")\n\nprint(f\"\\nSlope (b₂): ${slope:.2f} per square foot\")\nprint(f\"  Interpretation: Each additional square foot is associated with\")\nprint(f\"  a ${slope:.2f} increase in house price, on average.\")\n\nprint(f\"\\nExamples:\")\nprint(f\"  • 100 sq ft larger → ${slope * 100:,.2f} higher price\")\nprint(f\"  • 500 sq ft larger → ${slope * 500:,.2f} higher price\")\n\nprint(f\"\\nR-squared: {r_squared:.4f} ({r_squared*100:.2f}%)\")\nprint(f\"  {r_squared*100:.2f}% of price variation is explained by size\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFitted regression line:\n  ŷ = 115,017.28 + 73.77 × size\n\nIntercept (b₁): $115,017.28\n  Interpretation: Predicted price when size = 0\n  (Not economically meaningful in this case)\n\nSlope (b₂): $73.77 per square foot\n  Interpretation: Each additional square foot is associated with\n  a $73.77 increase in house price, on average.\n\nExamples:\n  • 100 sq ft larger → $7,377.10 higher price\n  • 500 sq ft larger → $36,885.52 higher price\n\nR-squared: 0.6175 (61.75%)\n  61.75% of price variation is explained by size\n```\n:::\n:::\n\n\n**Key findings from the house price regression:**\n\n**The fitted equation:**\n```\nŷ = 115,017 + 73.77 × size\n```\n\n**1. Slope coefficient: \\$73.77 per square foot (p < 0.001)**\n\n- **Interpretation**: Each additional square foot is associated with a \\$73.77 increase in house price, on average\n- **Statistical significance**: p-value ≈ 0 (highly significant)\n- **Confidence interval**: [50.84, 96.70] — we're 95% confident the true effect is between \\$51 and \\$97 per sq ft\n\n**2. Practical examples:**\n\n- 100 sq ft larger → \\$73.77 × 100 = **\\$7,377** higher price\n- 500 sq ft larger → \\$73.77 × 500 = **\\$36,885** higher price\n- 1,000 sq ft larger → \\$73.77 × 1,000 = **\\$73,770** higher price\n\n**3. Intercept: \\$115,017**\n\n- **Mathematical interpretation**: Predicted price when size = 0\n- **Reality check**: A house can't have zero square feet!\n- **Better interpretation**: This is just where the regression line crosses the y-axis\n- Don't take it literally — it's outside the data range (1,400-3,300 sq ft)\n\n**4. R-squared: 0.617 (61.7%)**\n\n- Size explains **62% of the variation** in house prices\n- The remaining **38%** is due to other factors:\n - Location (neighborhood quality, schools)\n - Physical characteristics (bathrooms, garage, condition)\n - Market conditions (time of sale)\n - Unique features (view, lot size, upgrades)\n\n**Comparison to correlation:**\n\n- We computed r = 0.7858\n- R² = (0.7858)² = 0.617 (they match!)\n- For simple regression, R² always equals r²\n\n**Economic interpretation:** The strong relationship (R² = 0.62) between size and price makes economic sense. Buyers pay a substantial premium for additional space. However, the imperfect fit reminds us that many factors beyond size affect house values.\n\n### Visualizing the Fitted Regression Line\n\n::: {#819350bd .cell execution_count=11}\n``` {.python .cell-code}\n# Scatter plot with regression line\nfig, ax = plt.subplots(figsize=(10, 6))\nax.scatter(size, price, s=80, alpha=0.7, color='#22d3ee',\n           edgecolor='#3a4a6b', label='Actual prices')\nax.plot(size, model.fittedvalues, color='#c084fc', linewidth=2, label='Fitted regression line')\n\n# Add equation to plot\nequation_text = f'ŷ = {intercept:,.0f} + {slope:.2f} × size\\nR² = {r_squared:.4f}'\nax.text(0.05, 0.95, equation_text,\n        transform=ax.transAxes, fontsize=11,\n        verticalalignment='top',\n        bbox=dict(boxstyle='round', facecolor='#1e2a45', alpha=0.9))\n\nax.set_xlabel('House size (in square feet)', fontsize=12)\nax.set_ylabel('House sale price (in dollars)', fontsize=12)\nax.set_title('Scatter plot with regression line',\n             fontsize=14, fontweight='bold')\nax.legend(loc='lower right')\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch05_Bivariate_Data_Summary_files/figure-html/cell-12-output-1.png){width=950 height=565}\n:::\n:::\n\n\nThe purple line is the \"line of best fit.\" It minimizes the sum of squared vertical distances from each point to the line.\n\n### Special Case: Intercept-Only Regression\n\nWhen we regress y on only an intercept (no x variable), the OLS estimate equals the sample mean of y. This shows that regression is a natural extension of univariate statistics.\n\n::: {#91cf2382 .cell execution_count=12}\n``` {.python .cell-code}\n# Intercept-only regression\nmodel_intercept = ols('price ~ 1', data=data_house).fit()\n\n# Intercept-only regression\nprint(f\"Intercept from regression: ${model_intercept.params[0]:,.2f}\")\nprint(f\"Sample mean of price:      ${price.mean():,.2f}\")\n# These are equal, confirming that OLS generalizes the sample mean.\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nIntercept from regression: $253,910.34\nSample mean of price:      $253,910.34\n```\n:::\n:::\n\n\n## 5.6 Measures of Model Fit\n\nTwo key measures assess how well the regression line fits the data:\n\n### R-squared (R²)\nProportion of variation in y explained by x (ranges from 0 to 1):\n\n$$R^2 = \\frac{\\text{Explained SS}}{\\text{Total SS}} = \\frac{\\sum (\\hat{y}_i - \\bar{y})^2}{\\sum (y_i - \\bar{y})^2} = 1 - \\frac{\\sum (y_i - \\hat{y}_i)^2}{\\sum (y_i - \\bar{y})^2}$$\n\n**Interpretation:**\n\n- $R^2 = 0$: x explains none of the variation in y\n- $R^2 = 1$: x explains all of the variation in y\n- $R^2 = r^2$ (for simple regression, R² equals the squared correlation)\n\n### Standard Error of the Regression (s_e)\nStandard deviation of the residuals (typical size of prediction errors):\n\n$$s_e = \\sqrt{\\frac{1}{n-2} \\sum_{i=1}^n (y_i - \\hat{y}_i)^2}$$\n\n**Interpretation:**\n\n- Lower $s_e$ means fitted values are closer to actual values\n- Units: same as y (dollars in our example)\n- Dividing by (n-2) accounts for estimation of two parameters\n\n::: {#cf79c347 .cell execution_count=13}\n``` {.python .cell-code}\n# Measures of model fit\nr_squared = model.rsquared\nadj_r_squared = model.rsquared_adj\nse = np.sqrt(model.mse_resid)\nn = len(data_house)\n\nprint(f\"\\nR-squared:               {r_squared:.4f}\")\nprint(f\"  {r_squared*100:.2f}% of price variation explained by size\")\n\nprint(f\"\\nAdjusted R-squared:      {adj_r_squared:.4f}\")\nprint(f\"  Penalizes for number of regressors\")\n\nprint(f\"\\nStandard error (s_e):    ${se:,.2f}\")\nprint(f\"  Typical prediction error is about ${se:,.0f}\")\n\n# Verify R² = r²\nr = corr_matrix.loc['price', 'size']\nprint(f\"\\nVerification: R² = r²\")\nprint(f\"  R² = {r_squared:.4f}\")\nprint(f\"  r² = {r**2:.4f}\")\nprint(f\"  Match: {np.isclose(r_squared, r**2)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nR-squared:               0.6175\n  61.75% of price variation explained by size\n\nAdjusted R-squared:      0.6033\n  Penalizes for number of regressors\n\nStandard error (s_e):    $23,550.66\n  Typical prediction error is about $23,551\n\nVerification: R² = r²\n  R² = 0.6175\n  r² = 0.6175\n  Match: True\n```\n:::\n:::\n\n\n> **Key Concept 5.6: R-Squared Goodness of Fit**\n>\n> R-squared measures the fraction of variation in y explained by the regression on x. It ranges from 0 (no explanatory power) to 1 (perfect fit). For bivariate regression, R² equals the squared correlation coefficient (R² = r²ₓᵧ). R² = 0.62 means 62% of house price variation is explained by size variation, while 38% is due to other factors.\n\nWe've estimated the regression line. Now we assess how well this line fits the data using R-squared (proportion of variation explained) and the standard error of regression (typical prediction error).\n\n**Understanding R² = 0.617 and Standard Error = \\$23,162**\n\n**1. R-squared (coefficient of determination):**\n\n- **Value**: 0.617 or 61.7%\n- **Meaning**: Size explains 61.7% of the variation in house prices\n- **The other 38.3%**: Due to factors not in our model (location, quality, age, etc.)\n\n**How to think about R²:**\n\n- **R² = 0**: x has no predictive power (horizontal line)\n- **R² = 0.617**: x has substantial predictive power (our case)\n- **R² = 1**: x predicts y perfectly (all points on the line)\n\n**Is R² = 0.617 \"good\"?**\n\n- **For cross-sectional data**: Yes, this is quite good!\n- **Context matters**: \n - Lab experiments: Often R² > 0.9\n - Cross-sectional economics: R² = 0.2-0.6 is typical\n - Time series: R² = 0.7-0.95 is common\n\n- **Single predictor**: Size alone explains most variation — impressive!\n\n**2. Standard error: \\$23,162**\n\n- **Meaning**: Typical prediction error (residual size)\n- **Context**: \n - Average house price: \\$253,910\n - Typical error: \\$23,162 (about 9% of average)\n - This is reasonably accurate for house price prediction\n\n**3. Verification: R² = r²**\n\n- Correlation: r = 0.7858\n- R-squared: R² = 0.617\n- Check: (0.7858)² = 0.617 \n- For simple regression, these are always equal\n\n**4. Sum of Squares decomposition:**\n```\nTotal SS = Explained SS + Residual SS\n100% = 61.7% + 38.3%\n```\n\n**Practical implications:**\n\n- **For predictions**: Expect errors around ±\\$23,000\n- **For policy**: Size is important, but other factors matter too\n- **For research**: May want to add more variables (multiple regression, Chapters 10-12)\n\n### Illustration: Total SS, Explained SS, and Residual SS\n\nLet's create a simple example to visualize how R² is computed.\n\n::: {#37cb4425 .cell execution_count=14}\n``` {.python .cell-code}\n# Simulated data for demonstration\nnp.random.seed(123456)\nx_sim = np.arange(1, 6)\nepsilon = np.random.normal(0, 2, 5)\ny_sim = 1 + 2*x_sim + epsilon\n\ndf_sim = pd.DataFrame({'x': x_sim, 'y': y_sim})\nmodel_sim = ols('y ~ x', data=df_sim).fit()\n\n# Simulated data for model fit illustration\nprint(f\"{'x':<5} {'y':<10} {'y-hat':<10} {'Residual (e)':<15} {'(y - y-bar)':<10} {'(y-hat - y-bar)':<10}\")\nfor i in range(len(x_sim)):\n    print(f\"{x_sim[i]:<5} {y_sim[i]:<10.4f} {model_sim.fittedvalues[i]:<10.4f} \"\n          f\"{model_sim.resid[i]:<15.4f} {y_sim[i] - y_sim.mean():<10.4f} \"\n          f\"{model_sim.fittedvalues[i] - y_sim.mean():<10.4f}\")\n\nprint(f\"\\nSums of Squares:\")\ntotal_ss = np.sum((y_sim - y_sim.mean())**2)\nexplained_ss = np.sum((model_sim.fittedvalues - y_sim.mean())**2)\nresidual_ss = np.sum(model_sim.resid**2)\n\nprint(f\"  Total SS     = {total_ss:.4f}\")\nprint(f\"  Explained SS = {explained_ss:.4f}\")\nprint(f\"  Residual SS  = {residual_ss:.4f}\")\nprint(f\"\\nCheck: Explained SS + Residual SS = {explained_ss + residual_ss:.4f}\")\nprint(f\"       Total SS                     = {total_ss:.4f}\")\n\nprint(f\"\\nR² = Explained SS / Total SS = {explained_ss / total_ss:.4f}\")\nprint(f\"R² from model = {model_sim.rsquared:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nx     y          y-hat      Residual (e)    (y - y-bar) (y-hat - y-bar)\n1     3.9382     2.2482     1.6900          -2.5632    -4.2533   \n2     4.4343     4.3748     0.0595          -2.0672    -2.1266   \n3     3.9819     6.5015     -2.5196         -2.5196    0.0000    \n4     6.7287     8.6281     -1.8994         0.2273     2.1266    \n5     13.4242    10.7548    2.6695          6.9228     4.2533    \n\nSums of Squares:\n  Total SS     = 65.1680\n  Explained SS = 45.2262\n  Residual SS  = 19.9418\n\nCheck: Explained SS + Residual SS = 65.1680\n       Total SS                     = 65.1680\n\nR² = Explained SS / Total SS = 0.6940\nR² from model = 0.6940\n```\n:::\n:::\n\n\n::: {#191638ae .cell execution_count=15}\n``` {.python .cell-code}\n# Visualization of model fit\nfig, axes = plt.subplots(1, 2, figsize=(14, 5))\n\n# Panel A: Total SS (deviations from mean)\naxes[0].scatter(x_sim, y_sim, s=100, color='#22d3ee', marker='^', label='Actual y', zorder=3)\naxes[0].axhline(y=y_sim.mean(), color='red', linewidth=2, linestyle='--',\n                label=f'Mean of y = {y_sim.mean():.2f}', zorder=2)\n# Draw vertical lines from points to mean\nfor i in range(len(x_sim)):\n    axes[0].plot([x_sim[i], x_sim[i]], [y_sim[i], y_sim.mean()],\n                 '-', color='#c084fc', linewidth=1.5, alpha=0.5, zorder=1)\naxes[0].set_xlabel('x', fontsize=12)\naxes[0].set_ylabel('y', fontsize=12)\naxes[0].set_title('Panel A: Total SS\\n(Deviations from Mean)', fontsize=12, fontweight='bold')\naxes[0].legend()\naxes[0].grid(True, alpha=0.3)\n\n# Panel B: Explained SS (deviations of fitted values from mean)\naxes[1].scatter(x_sim, model_sim.fittedvalues, s=100, color='#22d3ee',\n                marker='o', label='Fitted ŷ', zorder=3)\naxes[1].axhline(y=y_sim.mean(), color='red', linewidth=2, linestyle='--',\n                label=f'Mean of y = {y_sim.mean():.2f}', zorder=2)\n# Draw vertical lines from fitted values to mean\nfor i in range(len(x_sim)):\n    axes[1].plot([x_sim[i], x_sim[i]], [model_sim.fittedvalues[i], y_sim.mean()],\n                 'g-', linewidth=1.5, alpha=0.5, zorder=1)\naxes[1].set_xlabel('x', fontsize=12)\naxes[1].set_ylabel('ŷ', fontsize=12)\naxes[1].set_title('Panel B: Explained SS\\n(Fitted Values from Mean)', fontsize=12, fontweight='bold')\naxes[1].legend()\naxes[1].grid(True, alpha=0.3)\n\nplt.suptitle('Model Fit Illustration',\n             fontsize=14, fontweight='bold', y=1.00)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch05_Bivariate_Data_Summary_files/figure-html/cell-16-output-1.png){width=1334 height=484}\n:::\n:::\n\n\n**What to look for:** Panel A shows Total SS (how far actual y values are from their mean). Panel B shows Explained SS (how far fitted values are from the mean). R-squared = (Explained SS) / (Total SS) measures the proportion explained.\n\n**Practical Implications of R² in Economics:**\n\nIn applied econometrics, R² values around 0.60 are considered quite strong for cross-sectional data. Our R² = 0.617 tells us:\n\n- **Size is a major determinant**: House size explains most of the price variation\n- **Other factors matter**: The remaining 38% is due to location, quality, age, amenities, etc.\n- **Single-variable limits**: One predictor can only explain so much in complex real-world data\n\n**Why R² varies by context:**\n\n- **Lab experiments**: Often R² > 0.90 (controlled conditions, few confounding factors)\n- **Cross-sectional economics**: Typically R² = 0.20-0.60 (many unobserved heterogeneities)\n- **Time series data**: Often R² = 0.70-0.95 (trends and persistence dominate)\n\n**Next step:** This motivates **multiple regression** (Chapters 10-12), where we include many explanatory variables simultaneously to capture more of the variation in y.\n\n## 5.7 Computer Output Following Regression\n\nModern statistical software provides comprehensive regression output. Let's examine each component of the output for our house price regression.\n\n**Understanding Prediction Uncertainty:**\n\nOur prediction ŷ = $262,559 for a 2,000 sq ft house is a **point estimate** — our best single guess. But predictions have uncertainty:\n\n**Sources of uncertainty:**\n\n- **Estimation error**: We don't know the true β₁ and β₂, only estimates b₁ and b₂\n- **Fundamental randomness**: Even houses of identical size sell for different prices\n- **Model limitations**: Our simple model omits many price determinants\n\n**Preview of Chapter 7**: We'll learn to construct **prediction intervals** like:\n\n- \"We're 95% confident the price will be between $215,000 and $310,000\"\n- This acknowledges uncertainty while still providing useful guidance\n\nFor now, remember: the standard error ($23,551) gives a rough sense of typical prediction errors.\n\n::: {#a499077e .cell execution_count=16}\n``` {.python .cell-code}\n# Complete regression output\nmodel.summary()\n```\n\n::: {.cell-output .cell-output-display execution_count=16}\n```{=html}\n<table class=\"simpletable\">\n<caption>OLS Regression Results</caption>\n<tr>\n  <th>Dep. Variable:</th>          <td>price</td>      <th>  R-squared:         </th> <td>   0.617</td>\n</tr>\n<tr>\n  <th>Model:</th>                   <td>OLS</td>       <th>  Adj. R-squared:    </th> <td>   0.603</td>\n</tr>\n<tr>\n  <th>Method:</th>             <td>Least Squares</td>  <th>  F-statistic:       </th> <td>   43.58</td>\n</tr>\n<tr>\n  <th>Date:</th>             <td>Tue, 07 Apr 2026</td> <th>  Prob (F-statistic):</th> <td>4.41e-07</td>\n</tr>\n<tr>\n  <th>Time:</th>                 <td>08:28:45</td>     <th>  Log-Likelihood:    </th> <td> -332.05</td>\n</tr>\n<tr>\n  <th>No. Observations:</th>      <td>    29</td>      <th>  AIC:               </th> <td>   668.1</td>\n</tr>\n<tr>\n  <th>Df Residuals:</th>          <td>    27</td>      <th>  BIC:               </th> <td>   670.8</td>\n</tr>\n<tr>\n  <th>Df Model:</th>              <td>     1</td>      <th>                     </th>     <td> </td>   \n</tr>\n<tr>\n  <th>Covariance Type:</th>      <td>nonrobust</td>    <th>                     </th>     <td> </td>   \n</tr>\n</table>\n<table class=\"simpletable\">\n<tr>\n      <td></td>         <th>coef</th>     <th>std err</th>      <th>t</th>      <th>P>|t|</th>  <th>[0.025</th>    <th>0.975]</th>  \n</tr>\n<tr>\n  <th>Intercept</th> <td>  1.15e+05</td> <td> 2.15e+04</td> <td>    5.352</td> <td> 0.000</td> <td> 7.09e+04</td> <td> 1.59e+05</td>\n</tr>\n<tr>\n  <th>size</th>      <td>   73.7710</td> <td>   11.175</td> <td>    6.601</td> <td> 0.000</td> <td>   50.842</td> <td>   96.700</td>\n</tr>\n</table>\n<table class=\"simpletable\">\n<tr>\n  <th>Omnibus:</th>       <td> 0.576</td> <th>  Durbin-Watson:     </th> <td>   1.219</td>\n</tr>\n<tr>\n  <th>Prob(Omnibus):</th> <td> 0.750</td> <th>  Jarque-Bera (JB):  </th> <td>   0.638</td>\n</tr>\n<tr>\n  <th>Skew:</th>          <td>-0.078</td> <th>  Prob(JB):          </th> <td>   0.727</td>\n</tr>\n<tr>\n  <th>Kurtosis:</th>      <td> 2.290</td> <th>  Cond. No.          </th> <td>9.45e+03</td>\n</tr>\n</table><br/><br/>Notes:<br/>[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.<br/>[2] The condition number is large, 9.45e+03. This might indicate that there are<br/>strong multicollinearity or other numerical problems.\n```\n:::\n:::\n\n\n**Guide to reading regression output:**\n\n- **Top section** -- Model Summary: Dep. Variable, No. Observations, R-squared, F-statistic\n- **Middle section** -- Coefficients Table: coef, std err, t, P>|t|, 95% CI\n- **Bottom section** -- Diagnostic Tests: Omnibus, Durbin-Watson, Jarque-Bera, Cond. No.\n\n## 5.8 Prediction and Outliers\n\nOnce we have a fitted regression line, we can use it to predict y for any given value of x:\n\n$$\\hat{y} = b_1 + b_2 x^*$$\n\n**Two types of predictions:**\n\n1. **In-sample:** x is within the range of observed data (reliable)\n2. **Out-of-sample:** x is outside the observed range (extrapolation - use with caution)\n\n**Outliers** are observations that are unusually far from the regression line. They may indicate:\n\n- Data entry errors\n- Unusual circumstances\n- Model misspecification\n- Natural variation\n\n::: {#6eec52ea .cell execution_count=17}\n``` {.python .cell-code}\n# Prediction examples\n\n# Predict for a 2000 sq ft house\nnew_size = pd.DataFrame({'size': [2000]})\npredicted_price = model.predict(new_size)\n\nprint(f\"\\nExample 1: Predict price for a 2,000 sq ft house\")\nprint(f\"  Using the model: ŷ = {intercept:.2f} + {slope:.2f} × 2000\")\nprint(f\"  Predicted price: ${predicted_price.values[0]:,.2f}\")\n\n# Manual calculation\nmanual_prediction = intercept + slope * 2000\nprint(f\"  Manual check: ${manual_prediction:,.2f}\")\n\n# Multiple predictions\nprint(f\"\\nExample 2: Predictions for various house sizes\")\nsizes_to_predict = [1500, 1800, 2000, 2500, 3000]\npredictions = pd.DataFrame({'size': sizes_to_predict})\npredictions['predicted_price'] = model.predict(predictions)\n\npredictions\n\nprint(f\"\\nObserved size range: {size.min():.0f} to {size.max():.0f} sq ft\")\nprint(f\"  1500, 1800, 2000 are in-sample (reliable)\")\nprint(f\"  3000 is at the edge; 3500+ would be extrapolation (less reliable)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nExample 1: Predict price for a 2,000 sq ft house\n  Using the model: ŷ = 115017.28 + 73.77 × 2000\n  Predicted price: $262,559.36\n  Manual check: $262,559.36\n\nExample 2: Predictions for various house sizes\n\nObserved size range: 1400 to 3300 sq ft\n  1500, 1800, 2000 are in-sample (reliable)\n  3000 is at the edge; 3500+ would be extrapolation (less reliable)\n```\n:::\n:::\n\n\n**Example prediction: 2,000 sq ft house**\n\n**Predicted price: \\$262,559**\n\nUsing our regression equation:\n```\nŷ = \\$115,017 + \\$73.77 × 2,000 = \\$262,559\n```\n\n**How reliable is this prediction?**\n\n**1. In-sample vs. out-of-sample:**\n\n- Our data range: 1,400 to 3,300 sq ft\n- Prediction at 2,000 sq ft: **in-sample** (safe)\n- Prediction at 5,000 sq ft: **out-of-sample** (risky extrapolation)\n\n**2. Prediction accuracy:**\n\n- Standard error: \\$23,162\n- Typical error: about ±\\$23,000 around the prediction\n- **Informal prediction interval**: roughly \\$239,000 to \\$286,000\n- (Chapter 7 will cover formal prediction intervals)\n\n**3. Why predictions aren't perfect:**\n\n- Our model only includes size\n- Missing factors affect individual houses:\n  - Neighborhood quality\n  - Number of bathrooms\n  - Lot size\n  - Age and condition\n  - Unique features\n\n**Understanding residuals:**\n\nA **residual** is the prediction error for one observation:\n```\nresidual = actual price - predicted price\n         = y - ŷ\n```\n\n**Positive residual**: House sold for MORE than predicted (underestimate)\n**Negative residual**: House sold for LESS than predicted (overestimate)\n\n**Why do some houses have large residuals?**\n\n- Particularly desirable/undesirable location\n- Exceptional quality or poor condition\n- Unique features not captured by size alone\n- May indicate measurement error or unusual circumstances\n\n**Key insight:** The regression line gives the **average** relationship. Individual houses deviate from this average based on their unique characteristics.\n\n::: {#06ca33e1 .cell execution_count=18}\n``` {.python .cell-code}\n# Outlier detection\n\n# Add residuals and standardized residuals to dataset\ndata_house['fitted'] = model.fittedvalues\ndata_house['residual'] = model.resid\ndata_house['std_resid'] = model.resid / model.resid.std()\n\n# Observations with large residuals (>2 std deviations)\noutliers = data_house[np.abs(data_house['std_resid']) > 2]\n\nprint(f\"\\nObservations with large residuals (|standardized residual| > 2):\")\nif len(outliers) > 0:\n    print(outliers[['price', 'size', 'fitted', 'residual', 'std_resid']])\nelse:\n    print(\"  None found (all residuals within 2 standard deviations)\")\n\n# Top 5 largest residuals (in absolute value)\ndata_house.nlargest(5, 'residual', keep='all')[['price', 'size', 'fitted', 'residual']]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nObservations with large residuals (|standardized residual| > 2):\n     price  size         fitted      residual  std_resid\n27  340000  2400  292067.779503  47932.220497   2.072629\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=18}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>price</th>\n      <th>size</th>\n      <th>fitted</th>\n      <th>residual</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>27</th>\n      <td>340000</td>\n      <td>2400</td>\n      <td>292067.779503</td>\n      <td>47932.220497</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>255000</td>\n      <td>1500</td>\n      <td>225673.843168</td>\n      <td>29326.156832</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>245000</td>\n      <td>1400</td>\n      <td>218296.739130</td>\n      <td>26703.260870</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>258500</td>\n      <td>1600</td>\n      <td>233050.947205</td>\n      <td>25449.052795</td>\n    </tr>\n    <tr>\n      <th>26</th>\n      <td>310000</td>\n      <td>2300</td>\n      <td>284690.675466</td>\n      <td>25309.324534</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## 5.9 Regression and Correlation\n\nThere's a close relationship between the regression slope and the correlation coefficient:\n\n$$b_2 = r_{xy} \\times \\frac{s_y}{s_x}$$\n\n**Key insights:**\n\n- $r_{xy} > 0 \\Rightarrow b_2 > 0$ (positive correlation means positive slope)\n- $r_{xy} < 0 \\Rightarrow b_2 < 0$ (negative correlation means negative slope)\n- $r_{xy} = 0 \\Rightarrow b_2 = 0$ (zero correlation means zero slope)\n\n**But regression and correlation differ:**\n\n- Correlation treats x and y symmetrically: $r_{xy} = r_{yx}$\n- Regression does not: slope from regressing y on x $\\neq$ inverse of slope from regressing x on y\n\n**Why This Relationship Matters:**\n\nThe formula **b₂ = r × (sᵧ/sₓ)** reveals an important insight about the connection between correlation and regression:\n\n**Correlation (r):**\n\n- Scale-free measure (unitless)\n- Same value regardless of measurement units\n- Symmetric: r(price, size) = r(size, price)\n\n**Regression slope (b₂):**\n\n- Scale-dependent (has units: $/sq ft in our example)\n- Changes when we rescale variables\n- Asymmetric: slope from price~size ≠ inverse of slope from size~price\n\n**The ratio (sᵧ/sₓ):**\n\n- Converts between correlation and slope\n- Accounts for the relative variability of y and x\n- Explains why slopes have interpretable units while r does not\n\n**Practical implication:** This is why we use **regression** (not just correlation) in economics—we need interpretable coefficients with units ($/sq ft, % change, etc.) to make policy recommendations and predictions.\n\n::: {#26c98d2b .cell execution_count=19}\n``` {.python .cell-code}\n# Relationship: slope = correlation x (SD_Y / SD_X)\nr = corr_matrix.loc['price', 'size']\ns_y = price.std()\ns_x = size.std()\nb2_from_r = r * (s_y / s_x)\n\nprint(f\"\\nFrom regression:\")\nprint(f\"  Slope (b₂) = {slope:.4f}\")\n\nprint(f\"\\nFrom correlation:\")\nprint(f\"  r = {r:.4f}\")\nprint(f\"  s_y = {s_y:.4f}\")\nprint(f\"  s_x = {s_x:.4f}\")\nprint(f\"  b₂ = r × (s_y / s_x) = {r:.4f} × ({s_y:.4f} / {s_x:.4f}) = {b2_from_r:.4f}\")\n\nprint(f\"\\nMatch: {np.isclose(slope, b2_from_r)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFrom regression:\n  Slope (b₂) = 73.7710\n\nFrom correlation:\n  r = 0.7858\n  s_y = 37390.7107\n  s_x = 398.2721\n  b₂ = r × (s_y / s_x) = 0.7858 × (37390.7107 / 398.2721) = 73.7710\n\nMatch: True\n```\n:::\n:::\n\n\n## 5.10 Causation\n\n**Critical distinction:** Regression measures **association**, not **causation**.\n\nOur regression shows that larger houses are associated with higher prices. But we cannot conclude that:\n\n- Adding square footage to a house will increase its price by \\$73.77 per sq ft\n\n**Why not?**\n\n- **Omitted variables:** Many factors affect price (location, quality, age, condition)\n- **Reverse causality:** Could price influence size? (e.g., builders construct larger houses in expensive areas)\n- **Confounding:** A third variable (e.g., neighborhood quality) may influence both size and price\n\n**Demonstrating non-symmetry: Reverse regression**\n\nIf we regress x on y (instead of y on x), we get a different slope:\n\n- Original: $\\hat{y} = b_1 + b_2 x$\n- Reverse: $\\hat{x} = c_1 + c_2 y$\n\nThese two regressions answer different questions and have different slopes!\n\n> **Key Concept 5.7: Association vs. Causation**\n>\n> Regression measures association, not causation. A regression coefficient shows how much y changes when x changes, but does not prove that x causes y. Causation requires additional assumptions, experimental design, or advanced econometric techniques (Chapter 17). Regression is directional and asymmetric: regressing y on x gives a different slope than regressing x on y.\n\nWe've learned how to measure and quantify relationships. Now we address a critical question: does association imply causation? This distinction is fundamental to interpreting regression results correctly.\n\n::: {#546a56e2 .cell execution_count=20}\n``` {.python .cell-code}\n# Reverse regression: demonstrating non-symmetry\nreverse_model = ols('size ~ price', data=data_house).fit()\n\nprint(\"\\nOriginal Regression (price ~ size):\")\nprint(f\"  ŷ = {model.params['Intercept']:,.2f} + {model.params['size']:.4f} × size\")\nprint(f\"  Slope: {model.params['size']:.4f}\")\nprint(f\"  R-squared: {model.rsquared:.4f}\")\n\nprint(\"\\nReverse Regression (size ~ price):\")\nprint(f\"  x̂ = {reverse_model.params['Intercept']:.2f} + {reverse_model.params['price']:.6f} × price\")\nprint(f\"  Slope: {reverse_model.params['price']:.6f}\")\nprint(f\"  R-squared: {reverse_model.rsquared:.4f}\")\n\nprint(\"\\nComparison:\")\nprint(f\"  1 / b₂ = 1 / {model.params['size']:.4f} = {1/model.params['size']:.6f}\")\nprint(f\"  c₂ = {reverse_model.params['price']:.6f}\")\nprint(f\"  Are they equal? {np.isclose(1/model.params['size'], reverse_model.params['price'])}\")\n\nprint(\"\\nKey insight:\")\nprint(\"  • Original slope: $1 increase in size → ${:.2f} increase in price\".format(model.params['size']))\nprint(\"  • Reverse slope: $1 increase in price → {:.6f} sq ft increase in size\".format(reverse_model.params['price']))\nprint(\"  • These answer different questions!\")\n\nprint(\"\\nNote: Both regressions have the same R² because in simple regression,\")\nprint(\"      R² = r² regardless of which variable is on the left-hand side.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nOriginal Regression (price ~ size):\n  ŷ = 115,017.28 + 73.7710 × size\n  Slope: 73.7710\n  R-squared: 0.6175\n\nReverse Regression (size ~ price):\n  x̂ = -242.44 + 0.008370 × price\n  Slope: 0.008370\n  R-squared: 0.6175\n\nComparison:\n  1 / b₂ = 1 / 73.7710 = 0.013555\n  c₂ = 0.008370\n  Are they equal? False\n\nKey insight:\n  • Original slope: $1 increase in size → $73.77 increase in price\n  • Reverse slope: $1 increase in price → 0.008370 sq ft increase in size\n  • These answer different questions!\n\nNote: Both regressions have the same R² because in simple regression,\n      R² = r² regardless of which variable is on the left-hand side.\n```\n:::\n:::\n\n\n**CRITICAL DISTINCTION: Association ≠ Causation**\n\n**What our regression shows:**\n```\nprice = 115,017 + 73.77 × size\n```\n\n**What we CAN say:**\n\n- Larger houses are **associated with** higher prices\n- Size and price move together in a predictable way\n- We can **predict** price from size with reasonable accuracy\n\n**What we CANNOT say:**\n\n- Adding square footage to your house will increase its value by exactly \\$73.77 per sq ft\n- Size **causes** the price to be higher\n- Buying a bigger house will make it worth more\n\n**Why not? Three reasons:**\n\n**1. Omitted variables (confounding)**\n\n- Many factors affect BOTH size and price:\n  - **Neighborhood quality**: Rich neighborhoods have larger, more expensive houses\n  - **Lot size**: Bigger lots allow bigger houses AND command higher prices\n  - **Build quality**: High-quality construction → larger AND more expensive\n- The \\$73.77 coefficient captures both direct effects of size AND correlated factors\n\n**2. Reverse causality**\n\n- Our model: size → price\n- Alternative: price → size? \n  - In expensive areas, builders construct larger houses because buyers can afford them\n  - The causal arrow may run both ways\n\n**3. Measurement of different concepts**\n\n- **Cross-sectional comparison**: 2,000 sq ft house vs. 1,500 sq ft house (different houses)\n- **Causal question**: What happens if we ADD 500 sq ft to ONE house?\n- These are different questions with potentially different answers!\n\n**The reverse regression demonstration:**\n\n**Original**: price ~ size\n\n- Slope: \\$73.77 per sq ft\n\n**Reverse**: size ~ price  \n\n- Slope: 0.00837 sq ft per dollar\n\n**Key observation:**\n\n- If regression = causation, these should be reciprocals\n- 1 / 73.77 = 0.01355 ≠ 0.00837\n- They're NOT reciprocals! This reveals regression measures association, not causation\n\n**When can we claim causation?**\n\n- **Randomized experiments**: Randomly assign house sizes\n- **Natural experiments**: Find exogenous variation in size\n- **Careful econometric methods**: Instrumental variables, difference-in-differences, etc. (advanced topics)\n\n**Economic intuition:** In reality, building an addition probably DOES increase house value, but perhaps not by exactly \\$73.77/sq ft. The true causal effect depends on quality, location, and market conditions — factors our simple regression doesn't isolate.\n\n## 5.11 Nonparametric Regression\n\n**Parametric regression** (like OLS) assumes a specific functional form (e.g., linear).\n\n**Nonparametric regression** allows the relationship to be more flexible, letting the data determine the shape without imposing a specific functional form.\n\n**Common methods:**\n\n1. **LOWESS** (Locally Weighted Scatterplot Smoothing): Fits weighted regressions in local neighborhoods\n2. **Kernel smoothing:** Weighted averages using kernel functions\n3. **Splines:** Piecewise polynomials\n\n**Uses:**\n\n- Exploratory data analysis\n- Checking linearity assumption\n- Flexible modeling when functional form is unknown\n\n**When to Use Nonparametric vs. Parametric Regression:**\n\n**Use parametric (OLS linear regression) when:**\n\n- Theory suggests a linear relationship\n- You need interpretable coefficients ($73.77 per sq ft)\n- Sample size is small to moderate (n < 100)\n- You want statistical inference (t-tests, confidence intervals)\n\n**Use nonparametric (LOWESS, kernel) when:**\n\n- Exploring data without strong prior assumptions\n- Checking whether linear model is appropriate (diagnostic)\n- Relationship appears curved or complex\n- Large sample size (n > 100) provides enough data for flexible fitting\n\n**Best practice**: Start with scatter plot + nonparametric curve to check for nonlinearity, then use parametric model if linear assumption is reasonable.\n\n::: {#20f6029c .cell execution_count=21}\n``` {.python .cell-code}\n# Nonparametric regression\n\n# LOWESS smoothing\nlowess_result = lowess(price, size, frac=0.6)\n\n# Kernel smoothing (Gaussian filter approximation)\nsort_idx = np.argsort(size)\nsize_sorted = size.iloc[sort_idx]\nprice_sorted = price.iloc[sort_idx]\nsigma = 2  # bandwidth parameter\nprice_smooth = gaussian_filter1d(price_sorted, sigma)\n\n# Plot comparison\nfig, ax = plt.subplots(figsize=(12, 7))\n\n# Scatter plot\nax.scatter(size, price, s=80, alpha=0.6, color='#22d3ee',\n           edgecolor='#3a4a6b', label='Actual data', zorder=1)\n\n# OLS line\nax.plot(size, model.fittedvalues, color='#c084fc', linewidth=2.5,\n        label='OLS (parametric)', zorder=2)\n\n# LOWESS\nax.plot(lowess_result[:, 0], lowess_result[:, 1], color='red',\n        linewidth=2.5, linestyle='--', label='LOWESS', zorder=3)\n\n# Kernel smoothing\nax.plot(size_sorted, price_smooth, color='green', linewidth=2.5,\n        linestyle=':', label='Kernel smoothing', zorder=4)\n\nax.set_xlabel('House size (in square feet)', fontsize=12)\nax.set_ylabel('House sale price (in dollars)', fontsize=12)\nax.set_title('Figure 5.6: Parametric vs Nonparametric Regression',\n             fontsize=14, fontweight='bold')\nax.legend(fontsize=11, loc='lower right')\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch05_Bivariate_Data_Summary_files/figure-html/cell-22-output-1.png){width=1142 height=661}\n:::\n:::\n\n\n**What to look for in this comparison:**\n\n- **OLS** (purple solid): Assumes a linear relationship\n- **LOWESS** (red dashed): Flexible, data-driven curve\n- **Kernel smoothing** (green dotted): Another flexible method\n- For this data, all three methods are similar, suggesting that the linear model is a reasonable approximation.\n\n**Comparing three approaches to fitting the data:**\n\n**1. OLS (Ordinary Least Squares) — BLUE LINE**\n\n- **Parametric**: Assumes linear relationship\n- **Equation**: ŷ = \\$115,017 + \\$73.77 × size\n- **Advantage**: Simple, interpretable, efficient\n- **Limitation**: Restricted to straight lines\n\n**2. LOWESS (Locally Weighted Scatterplot Smoothing) — RED DASHED**\n\n- **Nonparametric**: Lets data determine the shape\n- **Method**: Fits weighted regressions in local neighborhoods\n- **Advantage**: Flexible, can capture curves\n- **Limitation**: Harder to interpret, more complex\n\n**3. Kernel Smoothing — GREEN DOTTED**\n\n- **Nonparametric**: Weighted moving averages\n- **Method**: Uses Gaussian kernel to smooth nearby points\n- **Advantage**: Very smooth curves\n- **Limitation**: Choice of bandwidth affects results\n\n**What does this comparison tell us?**\n\n**Key observation: All three lines are very similar!**\n\n- LOWESS and kernel smoothing follow OLS closely\n- No obvious systematic curvature\n- The relationship appears genuinely linear\n\n**This validates our linear model:**\n\n- If nonparametric methods showed strong curvature, we'd question the linear assumption\n- Since they align with OLS, the linear model is appropriate\n- We can confidently use the simpler parametric approach\n\n**When would nonparametric methods differ?**\n\n**Example scenarios:**\n\n- **Diminishing returns**: Price increases with size, but at a decreasing rate\n- **Threshold effects**: Small houses have steep price-size relationship, large houses flatten\n- **Nonlinear relationships**: Exponential, logarithmic, or polynomial patterns\n\n**For our housing data:**\n\n- Linear model works well\n- Adding complexity (nonparametric) doesn't improve fit much\n- **Occam's Razor**: Choose the simpler model when performance is similar\n\n**Practical use of nonparametric methods:**\n\n- **Exploratory analysis**: Check for nonlinearity before modeling\n- **Model diagnostics**: Verify linear assumption\n- **Flexible prediction**: When functional form is unknown\n- **Complex relationships**: When theory doesn't suggest specific form\n\n**Bottom line:** Nonparametric methods confirm that our linear regression is appropriate for this dataset. The relationship between house price and size is genuinely linear, not curved.\n\n## Key Takeaways\n\n### Visualization and Correlation\n\n- **Two-way tabulations**, scatterplots, and correlation are essential first steps in bivariate analysis\n- **Scatterplots** provide visual evidence of relationships and help identify direction, strength, form, and outliers\n- Two-way tabulations with **expected frequencies** enable chi-squared tests of independence for categorical data\n- The **correlation coefficient (r)** is a scale-free measure of linear association ranging from -1 to +1\n- **Covariance** measures the direction of association but depends on the units of measurement\n- For house price and size, **r = 0.786** indicates strong positive linear association\n- **Autocorrelation** extends correlation to time series, measuring how a variable relates to its own past values\n\n### Regression Analysis and Interpretation\n\n- The **regression line** ŷ = b₁ + b₂x is estimated by **ordinary least squares (OLS)**, which minimizes the sum of squared residuals\n- The **slope b₂** measures the change in y for a one-unit change in x and is the most important interpretable quantity\n- For house prices, **b₂ = $73.77** means each additional square foot is associated with a $73.77 price increase\n- The **intercept b₁** represents the predicted y when x = 0 (often not meaningful if x = 0 is outside the data range)\n- **Residuals** (e = y - ŷ) measure prediction errors; OLS makes the sum of squared residuals as small as possible\n- Regression of y on only an intercept yields the **sample mean** as the fitted value, showing OLS generalizes univariate statistics\n- The formulas **b₂ = Σ(xᵢ - x̄)(yᵢ - ȳ) / Σ(xᵢ - x̄)²** and **b₁ = ȳ - b₂x̄** enable manual computation\n- The regression slope equals **b₂ = rₓᵧ × (sᵧ/sₓ)**, connecting regression and correlation\n\n### Model Fit and Evaluation\n\n- **R-squared** measures the fraction of variation in y explained by x, ranging from 0 (no fit) to 1 (perfect fit)\n- **R² = (Explained SS) / (Total SS) = 1 - (Residual SS) / (Total SS)**\n- For bivariate regression, **R² = r²ₓᵧ** (squared correlation coefficient)\n- For house prices, **R² = 0.618** means 62% of price variation is explained by size variation\n- **Standard error of regression (sₑ)** measures the typical size of residuals in the units of y\n- **Low R² doesn't mean regression is uninformative**—the coefficient can still be statistically significant and economically important\n- R² depends on data aggregation and choice of dependent variable; use it to compare models with the **same dependent variable**\n- Computer regression output provides coefficients, standard errors, t-statistics, p-values, F-statistics, and ANOVA decomposition\n\n### Prediction, Causation, and Extensions\n\n- **Predictions** use ŷ = b₁ + b₂x* to forecast y for a given x*\n- **In-sample predictions** use observed x values (fitted values); **out-of-sample predictions** use new x values\n- **Extrapolation** beyond the sample range of x can be unreliable\n- **Outliers** can strongly influence regression estimates, especially if far from both x̄ and ȳ\n- **Association does not imply causation**—regression measures correlation, not causal effects\n- **Confounding variables**, reverse causality, or selection bias can create associations without causation\n- Establishing **causation** requires experimental design, natural experiments, or advanced econometric techniques (Chapter 17)\n- **Regression is directional and asymmetric**: regressing y on x gives a different slope than regressing x on y\n- The two slopes are **NOT reciprocals**, reflecting that regression treats y and x differently\n- **Nonparametric regression** (local linear, lowess) provides flexible alternatives without assuming linearity\n- Nonparametric methods are useful for **exploratory analysis** and checking the appropriateness of linear models\n\n### Connection to Economic Analysis\n\n- The strong relationship (R² = 0.62) between size and price makes economic sense: buyers pay a premium for space\n- The imperfect fit reminds us that **many factors beyond size affect house values** (location, quality, age, condition)\n- Regression provides the **foundation for econometric analysis**, allowing us to quantify economic relationships\n- This chapter's bivariate methods extend naturally to **multiple regression** (Chapters 10-12) with many explanatory variables\n- Understanding association vs. causation is **critical for policy analysis** and program evaluation\n\n**Congratulations!** You've mastered the basics of bivariate data analysis and simple linear regression. You now understand how to measure and visualize relationships between two variables, fit and interpret a regression line, assess model fit, and recognize the crucial distinction between association and causation. These tools form the foundation for all econometric analysis!\n\n> **Common Mistakes to Avoid**\n>\n> - **Confusing covariance and correlation**: Covariance depends on units, correlation is standardized\n> - **Assuming correlation implies a linear relationship**: Correlation only measures linear association\n> - **Ignoring outliers in correlation**: A single extreme point can dramatically change the correlation coefficient\n\n## Practice Exercises\n\nTest your understanding of bivariate data analysis and regression with these exercises.\n\n**Exercise 1: Correlation Interpretation**\n\nSuppose the correlation between years of education and annual income is r = 0.35.\n\n(a) What does this correlation tell us about the relationship between education and income?\n\n(b) If we measured income in thousands of dollars instead of dollars, would the correlation change?\n\n(c) Can we conclude that education causes higher income? Why or why not?\n\n---\n\n**Exercise 2: Computing Correlation**\n\nGiven the following data for variables x and y with n = 5 observations:\n\n- Σ(xᵢ - x̄)(yᵢ - ȳ) = 20\n- Σ(xᵢ - x̄)² = 50\n- Σ(yᵢ - ȳ)² = 10\n\n(a) Calculate the sample correlation coefficient r.\n\n(b) Is this a strong, moderate, or weak correlation?\n\n(c) Is the relationship positive or negative?\n\n---\n\n**Exercise 3: Regression Slope Calculation**\n\nFor the data in Exercise 2:\n\n(a) Calculate the regression slope coefficient b₂ from regression of y on x.\n\n(b) Verify the relationship: b₂ = r × (sᵧ / sₓ)\n\n(c) If x̄ = 10 and ȳ = 25, calculate the intercept b₁.\n\n---\n\n**Exercise 4: R-squared Interpretation**\n\nA regression of test scores on hours studied yields R² = 0.40.\n\n(a) What percentage of test score variation is explained by hours studied?\n\n(b) What percentage is due to other factors?\n\n(c) Does this mean studying is not important? Explain.\n\n(d) If the correlation is r = 0.632, verify that R² = r².\n\n---\n\n**Exercise 5: Prediction**\n\nFrom the house price regression: ŷ = 115,017 + 73.77 × size\n\n(a) Predict the price of a house with 2,200 square feet.\n\n(b) Predict the price of a house with 5,000 square feet.\n\n(c) Which prediction is more reliable? Why?\n\n(d) If the standard error is $23,551, what does this tell us about prediction accuracy?\n\n---\n\n**Exercise 6: Residuals**\n\nA house of 1,800 sq ft sold for $270,000. The regression predicts ŷ = $247,805.\n\n(a) Calculate the residual for this observation.\n\n(b) Is the actual price higher or lower than predicted?\n\n(c) What might explain this large positive residual?\n\n(d) Would you consider this an outlier? Why or why not?\n\n---\n\n**Exercise 7: Causation vs. Association**\n\nStudies show that ice cream sales and crime rates are positively correlated.\n\n(a) Does this mean ice cream causes crime? Explain.\n\n(b) What might be a confounding variable?\n\n(c) How would you design a study to test for causation?\n\n(d) Give another example where correlation does not imply causation.\n\n---\n\n**Exercise 8: Python Practice**\n\nUsing the house price data or your own dataset:\n\n(a) Create a scatterplot with a fitted regression line.\n\n(b) Calculate the correlation coefficient using `pandas` `.corr()` method.\n\n(c) Fit an OLS regression using `statsmodels` and interpret the output.\n\n(d) Create residual plots to check for outliers.\n\n(e) Compare OLS with LOWESS nonparametric regression.\n\n---\n\n**Solutions to selected exercises:**\n\n- **Exercise 2a**: r = 20 / √(50 × 10) = 20 / √500 = 0.894\n- **Exercise 3a**: b₂ = 20 / 50 = 0.4\n- **Exercise 4a**: 40% explained, 60% due to other factors\n- **Exercise 5a**: ŷ = 115,017 + 73.77 × 2,200 = $277,311\n\nFor complete solutions and additional practice problems, see the course website.\n\n## Case Studies\n\nNow that you've learned the fundamentals of bivariate analysis, correlation, and regression, let's apply these techniques to real economic research questions using the **Economic Convergence Clubs** dataset from Mendez (2020).\n\n**Why case studies matter:**\n\n- Bridge theory and application: Move from learning formulas to answering substantive economic questions\n- Build analytical workflow: Practice the complete cycle from visualization to interpretation\n- Develop critical thinking: Distinguish association from causation in real data\n- Connect to research: See how econometric tools support published economic studies\n\n### Case Study 1: Capital and Productivity Across Countries\n\n**Research Question:** What is the relationship between capital per worker and labor productivity across countries? Does this relationship vary by income group?\n\n**Background:** Traditional growth theory suggests that countries with more capital per worker should have higher labor productivity. This is the **capital-output relationship**—a fundamental concept in development economics. However, differences in technology, institutions, and human capital mean that capital alone doesn't fully explain productivity differences.\n\nThis research ([Mendez, 2020](https://github.com/quarcs-lab/mendez2020-convergence-clubs-code-data)) uses panel data from 108 countries to study convergence clubs in labor productivity. Rather than assuming all countries converge to a single equilibrium, the analysis identifies distinct groups (clubs) that converge toward different productivity levels.\n\n**The Data:** We'll use the same dataset from Chapter 1, but now apply Chapter 5's bivariate tools:\n\n- **Panel dataset:** 108 countries observed from 1990-2014 (2,700 country-year observations)\n- **Key variables:**\n - `lp`: Labor productivity (output per worker, in 2011 USD PPP)\n - `kl`: Capital per worker (physical capital stock per worker)\n - `h`: Human capital index (based on years of schooling)\n - `TFP`: Total factor productivity (aggregate efficiency)\n - `hi1990`: High-income country indicator (as of 1990)\n - `region`: Regional classification\n\n**Your Task:** Use Chapter 5's visualization, correlation, and regression tools to explore the capital-productivity relationship and test whether it differs across country groups.\n\n> **Key Concept 5.8: Capital-Productivity Relationship**\n>\n> The regression of labor productivity on capital per worker quantifies the **capital-output elasticity**—how much productivity increases when capital per worker rises by 1%. In cross-country data, this relationship reflects both:\n>\n> 1. **Diminishing returns to capital** (holding technology constant)\n> 2. **Technology differences** across countries (correlated with capital accumulation)\n>\n> Distinguishing these two effects requires controlling for other factors (human capital, TFP), which we'll learn in later chapters on multiple regression.\n\n### How to Use These Tasks\n\n**Progressive difficulty:**\n\n- **Tasks 1-2:** Guided (detailed instructions, code provided)\n- **Tasks 3-4:** Semi-guided (moderate guidance, you write most code)\n- **Tasks 5-6:** Independent (minimal guidance, design your own analysis)\n\n**Work incrementally:** Complete tasks in order. Each builds on previous skills.\n\n**Learn by doing:** Modify code, experiment with variables, interpret results economically.\n\n#### Task 1: Load and Explore the Data (Guided)\n\n**Objective:** Load the convergence clubs dataset and generate descriptive statistics for key variables.\n\n**Instructions:** Run the code below to load data and examine the structure.\n\n```python\n# Import required libraries\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom statsmodels.formula.api import ols\n\n# Load convergence clubs dataset\ndf = pd.read_csv(\n \"https://raw.githubusercontent.com/quarcs-lab/mendez2020-convergence-clubs-code-data/master/assets/dat.csv\",\n index_col=[\"country\", \"year\"]\n).sort_index()\n\n# Display dataset info\nprint(f\"Dataset shape: {df.shape[0]} observations, {df.shape[1]} variables\")\nprint(f\"Countries: {len(df.index.get_level_values('country').unique())}\")\nprint(f\"Years: {df.index.get_level_values('year').min()} to {df.index.get_level_values('year').max()}\")\n\n# First 5 observations\ndisplay(df[['lp', 'kl', 'h', 'TFP', 'hi1990', 'region']].head())\n\n# Descriptive statistics (key variables)\ndf[['lp', 'kl', 'h', 'TFP']].describe().round(2)\n```\n\n**What to observe:**\n\n- How many observations? How many countries?\n- What is the range of labor productivity (`lp`)? Capital per worker (`kl`)?\n- Are there missing values in key variables?\n\n#### Task 2: Visualize the Capital-Productivity Relationship (Semi-guided)\n\n**Objective:** Create a scatterplot to visualize the relationship between capital per worker and labor productivity.\n\n**Instructions:**\n\n1. Prepare a subset of data with non-missing values for `lp` and `kl`\n2. Create a scatterplot with capital per worker on the x-axis and labor productivity on the y-axis\n3. Add appropriate labels and title\n4. Interpret the pattern: positive/negative? Linear? Outliers?\n\n**Starter code:**\n\n```python\n# Prepare data (remove missing values)\nplot_data = df[['lp', 'kl']].dropna()\n\n# Create scatterplot\nfig, ax = plt.subplots(figsize=(10, 6))\nax.scatter(plot_data['kl'], plot_data['lp'], alpha=0.5, s=20)\n\n# Add labels and formatting\nax.set_xlabel('Capital per Worker (thousands, 2011 USD PPP)', fontsize=12)\nax.set_ylabel('Labor Productivity (thousands, 2011 USD PPP)', fontsize=12)\nax.set_title('Capital per Worker vs. Labor Productivity (108 countries, 1990-2014)', fontsize=14)\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n\n# What pattern do you see?\nprint(\"\\n Interpretation:\")\nprint(\"- Relationship: [Positive/Negative/No clear pattern]\")\nprint(\"- Strength: [Strong/Moderate/Weak]\")\nprint(\"- Outliers: [Yes/No] - [Describe if present]\")\n```\n\n**Questions:**\n\n- Is the relationship positive (as theory predicts)?\n- Is it approximately linear, or curved?\n- Are there countries with very high capital but moderate productivity (or vice versa)?\n\n#### Task 3: Calculate the Correlation Coefficient (Semi-guided)\n\n**Objective:** Quantify the strength of the linear relationship between capital and productivity using the correlation coefficient.\n\n**Instructions:**\n\n1. Calculate the Pearson correlation coefficient between `lp` and `kl`\n2. Interpret the magnitude: Is it close to 0 (weak), 0.5 (moderate), or 1.0 (strong)?\n3. Test statistical significance: Is the relationship likely due to chance?\n\n**Hint:** Use `.corr()` method or `np.corrcoef()` function.\n\n**Example structure:**\n\n```python\n# Calculate correlation\ncorr = plot_data[['lp', 'kl']].corr()\nprint(\"Correlation matrix:\")\nprint(corr)\n\n# Extract the correlation coefficient\nr = corr.loc['lp', 'kl']\nprint(f\"\\nCorrelation between capital and productivity: r = {r:.4f}\")\n\n# Interpretation\nprint(f\"\\nInterpretation:\")\nprint(f\"- Magnitude: {'Strong' if abs(r) > 0.7 else 'Moderate' if abs(r) > 0.4 else 'Weak'}\")\nprint(f\"- Direction: {'Positive' if r > 0 else 'Negative'}\")\nprint(f\"- R² (shared variation): {r**2:.4f} ({r**2*100:.2f}%)\")\n```\n\n**Questions:**\n\n- How much of the variation in productivity is explained by capital?\n- Does this match what you observed in the scatterplot?\n\n#### Task 4: Estimate the Regression Line (More Independent)\n\n**Objective:** Estimate an OLS regression of labor productivity on capital per worker and interpret the slope coefficient.\n\n**Instructions:**\n\n1. Prepare regression data (remove missing values, reset index if needed)\n2. Estimate: `lp ~ kl` using `ols()` from statsmodels\n3. Display the regression summary\n4. Extract and interpret the slope coefficient economically\n5. Report the R-squared value\n\n**Key questions to answer:**\n\n- What is the slope coefficient? Interpret it in economic terms.\n- Is the coefficient statistically significant (p < 0.05)?\n- What percentage of productivity variation is explained by capital?\n- Does the relationship appear causal, or could there be omitted variables?\n\n**Hint:** Remember to reset the index before regression if you're using formula syntax.\n\n> **Key Concept 5.9: Interpreting Slope in Economic Context**\n>\n> The regression slope β₁ in `productivity = β₀ + β₁ × capital` measures the **average change in productivity (in thousands of USD) for each additional thousand USD of capital per worker**.\n>\n> In cross-country data, this captures both:\n> - **True capital effect** (more machines → higher output)\n> - **Confounding factors** (richer countries have both more capital AND better technology/institutions)\n>\n> To isolate the true capital effect, we need **multiple regression** (Chapters 6-9) to control for human capital, TFP, and other factors.\n\n#### Task 5: Compare Relationships Across Income Groups (Independent)\n\n**Objective:** Investigate whether the capital-productivity relationship differs between high-income and developing countries.\n\n**Research Question:** Do high-income countries have a stronger/weaker capital-productivity association than developing countries?\n\n**Instructions:**\n\n1. Group the data by `hi1990` (high-income indicator)\n2. Calculate the correlation coefficient for each group separately\n3. Create comparative scatterplots (one color per group)\n4. (Advanced) Run separate regressions for each group and compare slope coefficients\n5. Interpret differences: Why might the relationship vary by income level?\n\n**Hints:**\n\n- Use `df.groupby('hi1990')` to split data\n- Use different colors in scatter plot for each group\n- Compare both correlations and regression slopes\n\n**Expected findings:**\n\n- High-income countries may show **weaker** capital-productivity correlation (approaching diminishing returns)\n- Developing countries may show **stronger** correlation (still accumulating capital)\n- Consider alternative explanations!\n\n#### Task 6: Explore Alternative Relationships (Independent)\n\n**Objective:** Investigate other bivariate relationships relevant to growth and convergence.\n\n**Choose ONE of the following research questions:**\n\n**Option A:** Human capital vs. productivity\n\n- Research question: Does education (human capital) explain productivity differences?\n- Variables: `lp` (productivity) and `h` (human capital index)\n- Expected: Positive relationship, but possibly weaker than capital\n\n**Option B:** TFP vs. productivity\n\n- Research question: How much of productivity is driven by aggregate efficiency (TFP)?\n- Variables: `lp` (productivity) and `TFP` (total factor productivity)\n- Expected: Strong positive relationship (TFP is a key driver)\n\n**Option C:** Time trend in productivity\n\n- Research question: Has average global productivity increased over time?\n- Variables: Year vs. average `lp` across all countries\n- Expected: Positive trend, but with variation across countries\n\n**Your analysis should include:**\n\n1. Scatterplot with clear labels\n2. Correlation coefficient\n3. Regression results (slope, R², significance)\n4. Economic interpretation: What does this relationship tell us about growth and development?\n\n> **Key Concept 5.10: Correlation vs. Causation in Growth Economics**\n>\n> Our regressions show **associations**—capital and productivity move together. But association ≠ causation:\n>\n> 1. **Reverse causality:** Does capital cause productivity, or does high productivity enable more capital accumulation?\n> 2. **Omitted variables:** Technology, institutions, geography, culture—all affect both capital and productivity\n> 3. **Selection effects:** High-income countries differ systematically from developing countries in ways beyond capital\n>\n> Establishing causation requires:\n> - **Controlled experiments** (rarely feasible for countries)\n> - **Natural experiments** (e.g., policy changes, resource discoveries)\n> - **Instrumental variables** (advanced econometric methods, Chapter 14-15)\n>\n> For now, interpret regression slopes as **descriptive associations**, not causal effects.\n\n### What You've Learned from This Case Study\n\nThrough this hands-on exploration of capital and productivity across countries, you've applied all Chapter 5 tools:\n\n **Visualization:** Scatterplots reveal patterns before quantifying relationships\n\n **Correlation:** Pearson coefficient quantifies linear association strength\n\n **Regression:** OLS slope measures average change in Y per unit change in X\n\n **Interpretation:** Translated coefficients into economic meaning (dollars, percentages)\n\n **Model fit:** R-squared shows explanatory power (proportion of variation explained)\n\n **Comparative analysis:** Group comparisons reveal heterogeneity (relationships vary by income level)\n\n **Critical thinking:** Distinguished association from causation; recognized omitted variable bias\n\n**Connection to the Research:** The patterns you've discovered—the capital-productivity relationship, differences across income groups, the role of TFP—are the empirical foundations for Mendez (2020)'s convergence clubs analysis. The full research uses advanced methods (nonparametric regression, clustering algorithms) to formally identify clubs, which you'll learn in later chapters.\n\n**Looking ahead:**\n\n- **Chapter 6-7:** Multiple regression to control for human capital, TFP, and other factors\n- **Chapter 10-11:** Panel data methods to exploit time variation within countries\n- **Chapter 15-17:** Advanced methods for causal inference and club detection\n\n**Congratulations!** You've completed Chapter 5 and applied bivariate analysis to real cross-country growth data. Continue to Chapter 6 to learn how to extend regression analysis to multiple explanatory variables.\n\n### Case Study 2: Nighttime Lights and Development: A Bivariate Exploration\n\nIn Chapter 1, we introduced the DS4Bolivia project and estimated a simple regression of development on nighttime lights. In this case study, we apply Chapter 5's bivariate tools—scatter plots, correlations, OLS regression, and model fit measures—to explore multiple satellite-development relationships in greater depth.\n\n**Data**: Cross-sectional dataset covering 339 Bolivian municipalities from the [DS4Bolivia Project](https://github.com/quarcs-lab/ds4bolivia).\n\n**Key variables**:\n\n- `mun`: Municipality name\n- `dep`: Department (administrative region)\n- `imds`: Municipal Sustainable Development Index (0–100 composite)\n- `ln_NTLpc2017`: Log nighttime lights per capita (2017)\n- `index_sdg1`: SDG 1 Index — No Poverty (0–100)\n- `index_sdg4`: SDG 4 Index — Quality Education (0–100)\n- `index_sdg8`: SDG 8 Index — Decent Work and Economic Growth (0–100)\n- `sdg7_1_ec`: SDG 7.1 — Electricity coverage (%)\n- `sdg1_1_ubn`: Unsatisfied Basic Needs (% of population)\n\n#### Task 1: Load and Explore (Guided)\n\n**Objective**: Load the DS4Bolivia dataset, select key variables, and create a two-way frequency table.\n\n**Instructions**:\n\n1. Load the data from the URL below and select the key variables listed above\n2. Use `pd.cut()` to bin the `imds` variable into three equal-frequency groups labeled **Low**, **Medium**, and **High** (terciles)\n3. Create a two-way frequency table (cross-tabulation) of `imds` terciles against department using `pd.crosstab()`\n4. Examine the table: Which departments have the most municipalities in the *Low* development category?\n\n::: {#ad800e4f .cell execution_count=22}\n``` {.python .cell-code}\n# Load the DS4Bolivia dataset\nurl_bol = \"https://raw.githubusercontent.com/quarcs-lab/ds4bolivia/master/ds4bolivia_v20250523.csv\"\nbol = pd.read_csv(url_bol)\n\n# Select key variables for this case study\nkey_vars = ['mun', 'dep', 'imds', 'ln_NTLpc2017',\n            'index_sdg1', 'index_sdg4', 'index_sdg8',\n            'sdg7_1_ec', 'sdg1_1_ubn']\nbol_cs = bol[key_vars].copy()\n\nprint(f\"Dataset: {bol_cs.shape[0]} municipalities, {bol_cs.shape[1]} variables\")\nprint(f\"Departments: {sorted(bol_cs['dep'].unique())}\")\nprint()\n\n# Bin imds into terciles\nbol_cs['imds_group'] = pd.cut(bol_cs['imds'],\n                               bins=3,\n                               labels=['Low', 'Medium', 'High'])\n\n# Two-way frequency table: imds tercile x department\ncross_tab = pd.crosstab(bol_cs['imds_group'], bol_cs['dep'],\n                        margins=True, margins_name='Total')\n# Two-way frequency table: IMDS tercile by department\ncross_tab\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDataset: 339 municipalities, 9 variables\nDepartments: ['Beni', 'Chuquisaca', 'Cochabamba', 'La Paz', 'Oruro', 'Pando', 'Potosí', 'Santa Cruz', 'Tarija']\n\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=22}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>dep</th>\n      <th>Beni</th>\n      <th>Chuquisaca</th>\n      <th>Cochabamba</th>\n      <th>La Paz</th>\n      <th>Oruro</th>\n      <th>Pando</th>\n      <th>Potosí</th>\n      <th>Santa Cruz</th>\n      <th>Tarija</th>\n      <th>Total</th>\n    </tr>\n    <tr>\n      <th>imds_group</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Low</th>\n      <td>9</td>\n      <td>21</td>\n      <td>20</td>\n      <td>45</td>\n      <td>21</td>\n      <td>13</td>\n      <td>28</td>\n      <td>13</td>\n      <td>0</td>\n      <td>170</td>\n    </tr>\n    <tr>\n      <th>Medium</th>\n      <td>10</td>\n      <td>7</td>\n      <td>22</td>\n      <td>40</td>\n      <td>13</td>\n      <td>2</td>\n      <td>11</td>\n      <td>43</td>\n      <td>9</td>\n      <td>157</td>\n    </tr>\n    <tr>\n      <th>High</th>\n      <td>0</td>\n      <td>1</td>\n      <td>5</td>\n      <td>2</td>\n      <td>1</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>2</td>\n      <td>12</td>\n    </tr>\n    <tr>\n      <th>Total</th>\n      <td>19</td>\n      <td>29</td>\n      <td>47</td>\n      <td>87</td>\n      <td>35</td>\n      <td>15</td>\n      <td>40</td>\n      <td>56</td>\n      <td>11</td>\n      <td>339</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n#### Task 2: Scatter Plots (Guided)\n\n**Objective**: Create a 2×2 grid of scatter plots to compare different satellite-development relationships.\n\n**Instructions**:\n\n1. Create a figure with four subplots arranged in a 2×2 grid\n2. Plot the following relationships:\n   - (a) `ln_NTLpc2017` vs `imds`\n   - (b) `ln_NTLpc2017` vs `index_sdg1`\n   - (c) `ln_NTLpc2017` vs `sdg7_1_ec`\n   - (d) `sdg1_1_ubn` vs `imds`\n\n3. Add axis labels and subplot titles\n4. Discuss: Which relationship appears strongest? Which appears weakest?\n\n::: {#b03d5e6a .cell execution_count=23}\n``` {.python .cell-code}\n# 2x2 scatter plot grid\nfig, axes = plt.subplots(2, 2, figsize=(12, 10))\n\nplot_data = bol_cs.dropna(subset=['ln_NTLpc2017', 'imds', 'index_sdg1',\n                                   'sdg7_1_ec', 'sdg1_1_ubn'])\n\n# (a) NTL vs IMDS\naxes[0, 0].scatter(plot_data['ln_NTLpc2017'], plot_data['imds'],\n                   alpha=0.5, color='#008CB7', s=20)\naxes[0, 0].set_xlabel('Log NTL per Capita (2017)')\naxes[0, 0].set_ylabel('IMDS')\naxes[0, 0].set_title('(a) Nighttime Lights vs Development Index')\n\n# (b) NTL vs SDG1 (No Poverty)\naxes[0, 1].scatter(plot_data['ln_NTLpc2017'], plot_data['index_sdg1'],\n                   alpha=0.5, color='#7A209F', s=20)\naxes[0, 1].set_xlabel('Log NTL per Capita (2017)')\naxes[0, 1].set_ylabel('SDG 1 Index (No Poverty)')\naxes[0, 1].set_title('(b) Nighttime Lights vs No Poverty')\n\n# (c) NTL vs SDG7.1 (Electricity Coverage)\naxes[1, 0].scatter(plot_data['ln_NTLpc2017'], plot_data['sdg7_1_ec'],\n                   alpha=0.5, color='#C21E72', s=20)\naxes[1, 0].set_xlabel('Log NTL per Capita (2017)')\naxes[1, 0].set_ylabel('Electricity Coverage (%)')\naxes[1, 0].set_title('(c) Nighttime Lights vs Electricity Coverage')\n\n# (d) UBN vs IMDS\naxes[1, 1].scatter(plot_data['sdg1_1_ubn'], plot_data['imds'],\n                   alpha=0.5, color='#2E86AB', s=20)\naxes[1, 1].set_xlabel('Unsatisfied Basic Needs (%)')\naxes[1, 1].set_ylabel('IMDS')\naxes[1, 1].set_title('(d) Unsatisfied Basic Needs vs Development Index')\n\nplt.suptitle('Bivariate Relationships: Satellite Data and Development in Bolivia',\n             fontsize=14, fontweight='bold', y=1.02)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch05_Bivariate_Data_Summary_files/figure-html/cell-24-output-1.png){width=1140 height=984}\n:::\n:::\n\n\n> **Key Concept 5.11: Nighttime Lights as Development Proxy**\n>\n> Nighttime light (NTL) intensity measured by satellites correlates with GDP, electrification, and urbanization across the world. The **log per-capita** transformation serves two purposes: the logarithm compresses the highly skewed raw luminosity values, and dividing by population accounts for the mechanical relationship between more people and more light. After these transformations, NTL becomes a meaningful proxy for *economic intensity* rather than simply population density.\n\n#### Task 3: Correlation Analysis (Semi-guided)\n\n**Objective**: Calculate and visualize the correlation matrix for key development and satellite variables.\n\n**Instructions**:\n\n1. Select the variables: `imds`, `ln_NTLpc2017`, `index_sdg1`, `index_sdg4`, `index_sdg8`, `sdg7_1_ec`, `sdg1_1_ubn`\n2. Calculate the Pearson correlation matrix using `.corr()`\n3. Display the results as a heatmap or formatted table\n4. Identify: Which variable has the **strongest** correlation with `imds`? Which has the **weakest**?\n\n**Hint**: Use `plt.imshow()` or `sns.heatmap()` (if seaborn is available) to visualize the correlation matrix.\n\n::: {#bbbd6ce0 .cell execution_count=24}\n``` {.python .cell-code}\n# Your code here: Correlation analysis\n#\n# Steps:\n# 1. Select numeric variables of interest\n# 2. Compute correlation matrix\n# 3. Display as heatmap or formatted table\n# 4. Identify strongest/weakest correlations with imds\n\n# Example structure:\n# corr_vars = ['imds', 'ln_NTLpc2017', 'index_sdg1', 'index_sdg4',\n#              'index_sdg8', 'sdg7_1_ec', 'sdg1_1_ubn']\n# corr_matrix = bol_cs[corr_vars].corr()\n# print(corr_matrix.round(3))\n#\n# # Heatmap\n# fig, ax = plt.subplots(figsize=(9, 7))\n# im = ax.imshow(corr_matrix, cmap='RdBu_r', vmin=-1, vmax=1)\n# ax.set_xticks(range(len(corr_vars)))\n# ax.set_yticks(range(len(corr_vars)))\n# ax.set_xticklabels(corr_vars, rotation=45, ha='right')\n# ax.set_yticklabels(corr_vars)\n# for i in range(len(corr_vars)):\n#     for j in range(len(corr_vars)):\n#         ax.text(j, i, f\"{corr_matrix.iloc[i, j]:.2f}\",\n#                 ha='center', va='center', fontsize=8)\n# plt.colorbar(im, ax=ax, label='Pearson Correlation')\n# ax.set_title('Correlation Matrix: Development and Satellite Variables')\n# plt.tight_layout()\n# plt.show()\n#\n# # Identify strongest/weakest correlations with imds\n# imds_corrs = corr_matrix['imds'].drop('imds').abs().sort_values(ascending=False)\n# print(f\"\\nStrongest correlation with IMDS: {imds_corrs.index[0]} (r = {corr_matrix.loc['imds', imds_corrs.index[0]]:.3f})\")\n# print(f\"Weakest correlation with IMDS: {imds_corrs.index[-1]} (r = {corr_matrix.loc['imds', imds_corrs.index[-1]]:.3f})\")\n```\n:::\n\n\n#### Task 4: OLS Regression Line (Semi-guided)\n\n**Objective**: Estimate and compare OLS regressions predicting IMDS from different variables.\n\n**Instructions**:\n\n1. Estimate OLS: `imds ~ ln_NTLpc2017`. Report the slope, intercept, and R²\n2. Overlay the fitted regression line on a scatter plot of `ln_NTLpc2017` vs `imds`\n3. Estimate a second OLS: `imds ~ sdg1_1_ubn`. Report slope, intercept, and R²\n4. Compare: Which predictor explains more variation in development?\n\n**Hint**: Use `ols()` from statsmodels as practiced in this chapter.\n\n::: {#9266dea0 .cell execution_count=25}\n``` {.python .cell-code}\n# Your code here: OLS regression with fitted lines\n#\n# Steps:\n# 1. Estimate imds ~ ln_NTLpc2017\n# 2. Overlay fitted line on scatter plot\n# 3. Estimate imds ~ sdg1_1_ubn\n# 4. Compare R-squared values\n\n# Example structure:\n# reg_data = bol_cs[['imds', 'ln_NTLpc2017', 'sdg1_1_ubn']].dropna()\n#\n# # Model 1: NTL\n# model_ntl = ols('imds ~ ln_NTLpc2017', data=reg_data).fit()\n# print(\"Model 1: IMDS ~ Log NTL per Capita\")\n# print(f\"  Slope:     {model_ntl.params['ln_NTLpc2017']:.4f}\")\n# print(f\"  Intercept: {model_ntl.params['Intercept']:.4f}\")\n# print(f\"  R-squared: {model_ntl.rsquared:.4f}\")\n#\n# # Model 2: UBN\n# model_ubn = ols('imds ~ sdg1_1_ubn', data=reg_data).fit()\n# print(\"\\nModel 2: IMDS ~ Unsatisfied Basic Needs\")\n# print(f\"  Slope:     {model_ubn.params['sdg1_1_ubn']:.4f}\")\n# print(f\"  Intercept: {model_ubn.params['Intercept']:.4f}\")\n# print(f\"  R-squared: {model_ubn.rsquared:.4f}\")\n#\n# # Scatter + fitted line for Model 1\n# fig, ax = plt.subplots(figsize=(8, 6))\n# ax.scatter(reg_data['ln_NTLpc2017'], reg_data['imds'], alpha=0.4, color='#008CB7', s=20)\n# x_range = np.linspace(reg_data['ln_NTLpc2017'].min(), reg_data['ln_NTLpc2017'].max(), 100)\n# ax.plot(x_range, model_ntl.params['Intercept'] + model_ntl.params['ln_NTLpc2017'] * x_range,\n#         color='#C21E72', linewidth=2, label=f'OLS: R² = {model_ntl.rsquared:.3f}')\n# ax.set_xlabel('Log NTL per Capita (2017)')\n# ax.set_ylabel('IMDS')\n# ax.set_title('OLS Regression: Nighttime Lights Predicting Development')\n# ax.legend()\n# plt.tight_layout()\n# plt.show()\n```\n:::\n\n\n> **Key Concept 5.12: Prediction vs. Causation with Satellite Data**\n>\n> A high R² between nighttime lights and development indices does **not** mean that lights *cause* development. Both NTL and IMDS reflect underlying economic activity, infrastructure, and urbanization. NTL is best understood as a **proxy variable**—an observable measure that correlates with the unobserved concept we care about (true economic development). The correlation is useful for prediction but should not be interpreted as a causal relationship.\n\n#### Task 5: Departmental Comparisons (Independent)\n\n**Objective**: Assess whether the NTL-development relationship differs across Bolivia's departments.\n\n**Instructions**:\n\n1. Create a scatter plot of `ln_NTLpc2017` vs `imds` with points colored by department\n2. Visually assess: Does the relationship appear to differ across departments?\n3. Run separate OLS regressions for 2–3 departments and compare slopes and R² values\n4. Discuss: What might explain differences in the satellite-development relationship across regions?\n\n::: {#4f780890 .cell execution_count=26}\n``` {.python .cell-code}\n# Your code here: Departmental comparisons\n#\n# Steps:\n# 1. Create scatter plot colored by department\n# 2. Run separate regressions for 2-3 departments\n# 3. Compare slopes and R-squared\n\n# Example structure:\n# plot_data = bol_cs[['ln_NTLpc2017', 'imds', 'dep']].dropna()\n# departments = plot_data['dep'].unique()\n# colors = plt.cm.tab10(np.linspace(0, 1, len(departments)))\n#\n# fig, ax = plt.subplots(figsize=(10, 7))\n# for dep, color in zip(sorted(departments), colors):\n#     subset = plot_data[plot_data['dep'] == dep]\n#     ax.scatter(subset['ln_NTLpc2017'], subset['imds'],\n#                alpha=0.6, color=color, label=dep, s=25)\n# ax.set_xlabel('Log NTL per Capita (2017)')\n# ax.set_ylabel('IMDS')\n# ax.set_title('NTL vs Development by Department')\n# ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=8)\n# plt.tight_layout()\n# plt.show()\n#\n# # Separate regressions for selected departments\n# for dep_name in ['La Paz', 'Santa Cruz', 'Potosí']:\n#     dep_data = plot_data[plot_data['dep'] == dep_name]\n#     if len(dep_data) > 5:\n#         model_dep = ols('imds ~ ln_NTLpc2017', data=dep_data).fit()\n#         print(f\"{dep_name}: slope = {model_dep.params['ln_NTLpc2017']:.3f}, \"\n#               f\"R² = {model_dep.rsquared:.3f}, n = {len(dep_data)}\")\n```\n:::\n\n\n#### Task 6: Alternative Predictors (Independent)\n\n**Objective**: Compare nighttime lights with unsatisfied basic needs (UBN) as predictors of development.\n\n**Instructions**:\n\n1. Compare the R² values from `imds ~ ln_NTLpc2017` and `imds ~ sdg1_1_ubn`\n2. Create side-by-side scatter plots with fitted regression lines for both models\n3. Discuss: Which predictor has the higher R²? Why might a socioeconomic variable (UBN) predict development better than satellite data (NTL)?\n4. Reflect: What are the advantages of satellite data even if its R² is lower?\n\n::: {#c5f79515 .cell execution_count=27}\n``` {.python .cell-code}\n# Your code here: Compare NTL vs UBN as predictors of IMDS\n#\n# Steps:\n# 1. Estimate both models (if not already done in Task 4)\n# 2. Create side-by-side fitted line plots\n# 3. Compare R-squared values\n# 4. Discuss advantages and limitations\n\n# Example structure:\n# reg_data = bol_cs[['imds', 'ln_NTLpc2017', 'sdg1_1_ubn']].dropna()\n# model_ntl = ols('imds ~ ln_NTLpc2017', data=reg_data).fit()\n# model_ubn = ols('imds ~ sdg1_1_ubn', data=reg_data).fit()\n#\n# fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n#\n# # Left: NTL model\n# axes[0].scatter(reg_data['ln_NTLpc2017'], reg_data['imds'], alpha=0.4, color='#008CB7', s=20)\n# x1 = np.linspace(reg_data['ln_NTLpc2017'].min(), reg_data['ln_NTLpc2017'].max(), 100)\n# axes[0].plot(x1, model_ntl.predict(pd.DataFrame({'ln_NTLpc2017': x1})),\n#              color='#C21E72', linewidth=2)\n# axes[0].set_xlabel('Log NTL per Capita (2017)')\n# axes[0].set_ylabel('IMDS')\n# axes[0].set_title(f'Model 1: NTL (R² = {model_ntl.rsquared:.3f})')\n#\n# # Right: UBN model\n# axes[1].scatter(reg_data['sdg1_1_ubn'], reg_data['imds'], alpha=0.4, color='#7A209F', s=20)\n# x2 = np.linspace(reg_data['sdg1_1_ubn'].min(), reg_data['sdg1_1_ubn'].max(), 100)\n# axes[1].plot(x2, model_ubn.predict(pd.DataFrame({'sdg1_1_ubn': x2})),\n#              color='#C21E72', linewidth=2)\n# axes[1].set_xlabel('Unsatisfied Basic Needs (%)')\n# axes[1].set_ylabel('IMDS')\n# axes[1].set_title(f'Model 2: UBN (R² = {model_ubn.rsquared:.3f})')\n#\n# plt.suptitle('Comparing Predictors of Municipal Development',\n#              fontsize=13, fontweight='bold')\n# plt.tight_layout()\n# plt.show()\n#\n# print(f\"\\nR² comparison:\")\n# print(f\"  NTL model: {model_ntl.rsquared:.4f}\")\n# print(f\"  UBN model: {model_ubn.rsquared:.4f}\")\n# print(f\"  Difference: {abs(model_ubn.rsquared - model_ntl.rsquared):.4f}\")\n```\n:::\n\n\n### What You've Learned from This Case Study\n\nThrough this bivariate exploration of satellite data and municipal development in Bolivia, you've applied the full Chapter 5 toolkit:\n\n- **Two-way tabulations** for categorical exploration of development levels across departments\n- **Multiple scatter plots** comparing satellite-development relationships across different indicators\n- **Correlation analysis** across multiple SDG indicators to identify strongest and weakest associations\n- **OLS regression with fitted lines and R²** to quantify the NTL-development relationship\n- **Regional heterogeneity** in bivariate relationships across Bolivia's departments\n- **Comparing alternative predictors** of development (satellite data vs. socioeconomic measures)\n\n**Connection to the research**: The DS4Bolivia project extends this bivariate analysis to multivariate machine learning models, using 64-dimensional satellite embeddings alongside nighttime lights to achieve higher predictive accuracy for SDG indicators.\n\n**Looking ahead**: In Chapter 7, we'll apply *statistical inference* to these regressions—testing whether the NTL coefficient is significantly different from zero and constructing confidence intervals for the effect of satellite data on development.\n\n**Well done!** You've now explored two real-world datasets—cross-country convergence and Bolivian municipal development—using the complete bivariate analysis toolkit from Chapter 5.\n\n",
    "supporting": [
      "ch05_Bivariate_Data_Summary_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}