{
  "hash": "d445b65e9b3f7d3ff4ad75362f18519b",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 11. Statistical Inference for Multiple Regression\nexecute:\n  enabled: true\n  warning: false\n---\n\n\n**metricsAI: An Introduction to Econometrics with Python and AI in the Cloud**\n\n*[Carlos Mendez](https://carlos-mendez.org)*\n\n<img src=\"https://raw.githubusercontent.com/quarcs-lab/metricsai/main/images/ch11_visual_summary.jpg\" alt=\"Chapter 11 Visual Summary\" width=\"100%\">\n\nThis notebook provides an interactive introduction to extending inference to models with multiple regressors. All code runs directly in Google Colab without any local setup.\n\n[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/quarcs-lab/metricsai/blob/main/notebooks_colab/ch11_Statistical_Inference_for_Multiple_Regression.ipynb)\n<div class=\"chapter-resources\">\n<a href=\"https://www.youtube.com/watch?v=yvcSMmluY5Y\" target=\"_blank\" class=\"resource-btn\">🎬 AI Video</a>\n<a href=\"https://carlos-mendez.my.canva.site/s11-statistical-inference-for-multiple-regression-pdf\" target=\"_blank\" class=\"resource-btn\">✨ AI Slides</a>\n<a href=\"https://cameron.econ.ucdavis.edu/aed/traedv1_11\" target=\"_blank\" class=\"resource-btn\">📊 Cameron Slides</a>\n<a href=\"https://app.edcafe.ai/quizzes/697868ad2f5d08069e04b748\" target=\"_blank\" class=\"resource-btn\">✏️ Quiz</a>\n<a href=\"https://app.edcafe.ai/chatbots/6978a1572f5d08069e071814\" target=\"_blank\" class=\"resource-btn\">🤖 AI Tutor</a>\n</div>\n\n\n## Chapter Overview\n\nThis chapter extends statistical inference to models with multiple regressors. You'll learn to construct confidence intervals, conduct hypothesis tests on individual and groups of parameters, and present regression results professionally.\n\n**Learning Objectives:**\n\nBy the end of this chapter, you will be able to:\n\n1. Extend statistical inference from bivariate regression to multiple regression with $k$ regressors\n2. Understand the $t$-statistic for individual coefficients following a $T(n-k)$ distribution\n3. Calculate and interpret standard errors for OLS slope coefficients: $se(b_j) = s_e / \\sqrt{\\sum \\widetilde{x}_{ji}^2}$\n4. Construct confidence intervals using $b_j \\pm t_{n-k, \\alpha/2} \\times se(b_j)$\n5. Conduct hypothesis tests on individual parameters to determine statistical significance\n6. Understand and apply F-tests for joint hypotheses involving multiple parameter restrictions\n7. Interpret the F distribution with two degrees of freedom ($v_1$ = restrictions, $v_2 = n-k$)\n8. Perform the test of overall statistical significance using $H_0: \\beta_2 = \\cdots = \\beta_k = 0$\n9. Test whether subsets of regressors are jointly significant using nested model comparisons\n10. Present regression results in standard formats (standard errors, t-statistics, p-values, confidence intervals, asterisks)\n\n**Dataset used:**\n\n- **AED_HOUSE.DTA**: 29 houses sold in Davis, California (1999)\n\n**Key economic questions:**\n\n- Is house size a statistically significant predictor of price?\n- Are additional variables (bedrooms, bathrooms, age) jointly significant?\n- What is a reasonable range for the effect of size on price?\n\n**Chapter outline:**\n\n- 11.1 Properties of the Least Squares Estimator\n- 11.2 Estimators of Model Parameters\n- 11.3 Confidence Intervals\n- 11.4 Hypothesis Tests on a Single Parameter\n- 11.5 Joint Hypothesis Tests\n- 11.6 F Statistic Under Assumptions 1-4\n- 11.7 Presentation of Regression Results\n- Key Takeaways\n- Practice Exercises\n- Case Studies\n\n\n## Setup\n\nFirst, we import the necessary Python packages and configure the environment for reproducibility. All data will stream directly from GitHub.\n\n::: {#4244af55 .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Setup: Import libraries and configure environment\"}\n# --- Libraries ---\nimport numpy as np                              # numerical operations\nimport pandas as pd                             # data manipulation\nimport matplotlib.pyplot as plt                 # plotting\nimport seaborn as sns                           # statistical visualization\nimport pyfixest as pf                           # fast estimation with robust SEs\nfrom scipy import stats                         # statistical distributions\n# anova_lm replaced by manual F-test with pyfixest\nimport random\nimport os\n\n# --- Reproducibility ---\nRANDOM_SEED = 42\nrandom.seed(RANDOM_SEED)\nnp.random.seed(RANDOM_SEED)\nos.environ['PYTHONHASHSEED'] = str(RANDOM_SEED)\n\n# --- Data source ---\nGITHUB_DATA_URL = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/\"\n\n# --- Plotting style (dark theme matching book design) ---\nplt.style.use('dark_background')\nsns.set_style(\"darkgrid\")\nplt.rcParams.update({\n    'axes.facecolor': '#1a2235',\n    'figure.facecolor': '#12162c',\n    'grid.color': '#3a4a6b',\n    'figure.figsize': (10, 6),\n    'text.color': 'white',\n    'axes.labelcolor': 'white',\n    'xtick.color': 'white',\n    'ytick.color': 'white',\n    'axes.edgecolor': '#1a2235',\n})\n\nprint(\"Setup complete! Ready to explore statistical inference for multiple regression.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSetup complete! Ready to explore statistical inference for multiple regression.\n```\n:::\n:::\n\n\n### Data Preparation\n\nWe'll work with the same house price dataset from Chapter 10, which contains information on 29 houses sold in Davis, California in 1999.\n\n::: {#fe36677d .cell execution_count=2}\n``` {.python .cell-code}\n# Read in the house data\ndata_house = pd.read_stata(GITHUB_DATA_URL + 'AED_HOUSE.DTA')\n\nprint(\"Data summary:\")\ndata_summary = data_house.describe()\nprint(data_summary)\n\nprint(\"\\nFirst few observations:\")\ndata_house[['price', 'size', 'bedrooms', 'bathrooms', 'lotsize', 'age', 'monthsold']].head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData summary:\n               price         size   bedrooms  bathrooms    lotsize        age  \\\ncount      29.000000    29.000000  29.000000  29.000000  29.000000  29.000000   \nmean   253910.344828  1882.758621   3.793103   2.206897   2.137931  36.413792   \nstd     37390.710695   398.272130   0.675030   0.341144   0.693034   7.118975   \nmin    204000.000000  1400.000000   3.000000   2.000000   1.000000  23.000000   \n25%    233000.000000  1600.000000   3.000000   2.000000   2.000000  31.000000   \n50%    244000.000000  1800.000000   4.000000   2.000000   2.000000  35.000000   \n75%    270000.000000  2000.000000   4.000000   2.500000   3.000000  39.000000   \nmax    375000.000000  3300.000000   6.000000   3.000000   3.000000  51.000000   \n\n       monthsold           list  \ncount  29.000000      29.000000  \nmean    5.965517  257824.137931  \nstd     1.679344   40860.264099  \nmin     3.000000  199900.000000  \n25%     5.000000  239000.000000  \n50%     6.000000  245000.000000  \n75%     7.000000  269000.000000  \nmax     8.000000  386000.000000  \n\nFirst few observations:\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>price</th>\n      <th>size</th>\n      <th>bedrooms</th>\n      <th>bathrooms</th>\n      <th>lotsize</th>\n      <th>age</th>\n      <th>monthsold</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>204000</td>\n      <td>1400</td>\n      <td>3</td>\n      <td>2.0</td>\n      <td>1</td>\n      <td>31.0</td>\n      <td>7</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>212000</td>\n      <td>1600</td>\n      <td>3</td>\n      <td>3.0</td>\n      <td>2</td>\n      <td>33.0</td>\n      <td>5</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>213000</td>\n      <td>1800</td>\n      <td>3</td>\n      <td>2.0</td>\n      <td>2</td>\n      <td>51.0</td>\n      <td>4</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>220000</td>\n      <td>1600</td>\n      <td>3</td>\n      <td>2.0</td>\n      <td>1</td>\n      <td>49.0</td>\n      <td>4</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>224500</td>\n      <td>2100</td>\n      <td>4</td>\n      <td>2.5</td>\n      <td>2</td>\n      <td>47.0</td>\n      <td>6</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## 11.1: Properties of the Least Squares Estimator\n\nBefore conducting inference, we need to understand the statistical properties of the OLS estimator. Under the classical linear regression assumptions, OLS has desirable properties.\n\n**Classical Assumptions (1-4):**\n\n1. **Linearity**: The population model is linear in parameters:\n   $$y = \\beta_1 + \\beta_2 x_2 + \\beta_3 x_3 + \\cdots + \\beta_k x_k + u$$\n\n2. **Random sampling**: Data are randomly sampled from the population\n\n3. **No perfect collinearity**: No exact linear relationships among regressors\n\n4. **Zero conditional mean**: $E[u | x_2, \\ldots, x_k] = 0$\n\n**Properties of OLS under these assumptions:**\n\n- **Unbiased**: $E[\\hat{\\beta}_j] = \\beta_j$ (centered on true value)\n- **Consistent**: $\\hat{\\beta}_j \\rightarrow \\beta_j$ as $n \\rightarrow \\infty$\n- **Efficient (BLUE)**: Best Linear Unbiased Estimator (Gauss-Markov Theorem)\n  - Has minimum variance among all linear unbiased estimators\n\n**Standard error of coefficient $\\hat{\\beta}_j$:**\n\n$$se(\\hat{\\beta}_j) = \\frac{s_e}{\\sqrt{\\sum_{i=1}^n \\tilde{x}_{ji}^2}}$$\n\nwhere:\n\n- $s_e$ is the standard error of the regression\n- $\\tilde{x}_{ji}$ is the residual from regressing $x_j$ on all other regressors\n\n**Smaller standard errors occur when:**\n\n- Model fits well (small $s_e$)\n- Large sample size (large $\\sum \\tilde{x}_{ji}^2$)\n- Variable $x_j$ has high variation after controlling for other regressors\n\n::: {#597c25c6 .cell execution_count=3}\n``` {.python .cell-code}\n# 11.1 PROPERTIES OF THE LEAST SQUARES ESTIMATOR\n\n# Under assumptions 1-4, OLS is unbiased, consistent, and BLUE\n```\n:::\n\n\n> **Key Concept 11.1: Classical Assumptions for Statistical Inference**\n>\n> Four assumptions underpin valid inference in multiple regression: (1) linearity in parameters, (2) random sampling, (3) no perfect collinearity among regressors, and (4) zero conditional mean of errors $E[u|X] = 0$. Under these assumptions, OLS is unbiased ($E[b_j] = \\beta_j$), consistent, and the Best Linear Unbiased Estimator (BLUE) by the Gauss-Markov theorem.\n\n## 11.2: Estimators of Model Parameters\n\nNow we estimate the full multiple regression model and examine the parameter estimates, standard errors, and related statistics.\n\n**The full model:**\n\n$$\\text{price} = \\beta_1 + \\beta_2 \\times \\text{size} + \\beta_3 \\times \\text{bedrooms} + \\beta_4 \\times \\text{bathrooms} + \\beta_5 \\times \\text{lotsize} + \\beta_6 \\times \\text{age} + \\beta_7 \\times \\text{monthsold} + u$$\n\n**Key statistics:**\n\n- **Coefficients** ($\\hat{\\beta}_j$): Point estimates of partial effects\n- **Standard errors** ($se(\\hat{\\beta}_j)$): Measure of estimation uncertainty\n- **t-statistics**: Coefficient divided by standard error\n- **p-values**: Probability of observing such extreme values under $H_0: \\beta_j = 0$\n- **Root MSE** ($s_e$): Standard deviation of residuals, measures typical prediction error\n\n::: {#e86301f0 .cell execution_count=4}\n``` {.python .cell-code}\n# Full multiple regression model\nmodel_full = pf.feols('price ~ size + bedrooms + bathrooms + lotsize + age + monthsold', data=data_house)\n\n# Key results\nsize_coef = model_full.coef()['size']\nsize_pval = model_full.pvalue()['size']\nr_squared = model_full._r2\nroot_mse = np.sqrt(np.sum(model_full._u_hat**2) / (int(model_full._N) - len(model_full.coef())))\n\nprint(f\"Size effect: ${size_coef:,.2f} per sq ft (p = {size_pval:.4f})\")\nprint(f\"R-squared: {r_squared:.4f} ({r_squared*100:.1f}% of variation explained)\")\nprint(f\"Root MSE: ${root_mse:,.2f} (typical prediction error)\")\n\n# Full regression output\nprint(\"\\nFull Multiple Regression Results:\")\nmodel_full.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSize effect: $68.37 per sq ft (p = 0.0002)\nR-squared: 0.6506 (65.1% of variation explained)\nRoot MSE: $24,935.73 (typical prediction error)\n\nFull Multiple Regression Results:\n###\n\nEstimation:  OLS\nDep. var.: price\nsample: None = all\nInference:  iid\nObservations:  29\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |       2.5% |      97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|-----------:|-----------:|\n| Intercept     | 137791.066 |    61464.952 |     2.242 |      0.035 |  10320.557 | 265261.574 |\n| size          |     68.369 |       15.389 |     4.443 |      0.000 |     36.454 |    100.285 |\n| bedrooms      |   2685.315 |     9192.526 |     0.292 |      0.773 | -16378.816 |  21749.447 |\n| bathrooms     |   6832.880 |    15721.192 |     0.435 |      0.668 | -25770.876 |  39436.636 |\n| lotsize       |   2303.221 |     7226.535 |     0.319 |      0.753 | -12683.695 |  17290.138 |\n| age           |   -833.039 |      719.335 |    -1.158 |      0.259 |  -2324.847 |    658.770 |\n| monthsold     |  -2088.504 |     3520.898 |    -0.593 |      0.559 |  -9390.399 |   5213.392 |\n---\nRMSE: 21718.733 R2: 0.651 \n```\n:::\n:::\n\n\n### Interpreting the Regression Results\n\n**What these results tell us:**\n\nThe regression output reveals several important findings about the house price data:\n\n1. **Size coefficient = \\$68.37 (p < 0.001)**: Each additional square foot increases house price by \\$68.37 on average, holding all other variables constant. This effect is highly statistically significant (p = 0.0002), meaning we can be very confident this relationship is not due to chance.\n\n2. **Other variables are not statistically significant**:\n   - **Bedrooms coefficient = \\$2,685 (p = 0.773)**: Surprisingly, the number of bedrooms doesn't significantly affect price once we control for size. The p-value of 0.773 means we cannot reject the hypothesis that this coefficient is zero.\n   - **Bathrooms coefficient = \\$6,833 (p = 0.668)**: Similarly, bathrooms show no significant effect.\n   - **Age coefficient = -\\$833 (p = 0.259)**: Older homes tend to sell for less, but this effect is not statistically significant.\n\n3. **Model fit: R² = 0.651**: The model explains 65.1% of the variation in house prices, which is quite good for cross-sectional real estate data.\n\n4. **Overall F-statistic = 6.83 (p = 0.0003)**: The model as a whole is highly significant, meaning at least one of our predictors has a real effect on price.\n\n**Economic Interpretation**: \n\nSize dominates all other house characteristics in determining price in this market. Features like number of bedrooms and bathrooms don't add explanatory power beyond what size already captures. This likely reflects multicollinearity—larger houses naturally tend to have more bedrooms and bathrooms, so once we control for size, these other features provide little additional information.\n\nThe large standard errors on most coefficients (relative to the coefficient values) suggest imprecise estimation, common in small samples (n=29) with correlated predictors.\n\n### Model Diagnostics\n\nLet's extract and display key model diagnostics to understand the estimation.\n\n::: {#a823ced5 .cell execution_count=5}\n``` {.python .cell-code}\n# Extract key statistics\nn = len(data_house)\nk = len(model_full.coef())\ndf = n - k\n\nprint(\"Model diagnostics:\")\nprint(f\"  Sample size (n): {n}\")\nprint(f\"  Number of parameters (k): {k}\")\nprint(f\"  Degrees of freedom (n-k): {df}\")\nprint(f\"  Root MSE (σ̂): ${np.sqrt(np.sum(model_full._u_hat**2) / (int(model_full._N) - len(model_full.coef()))):,.2f}\")\nprint(f\"  R-squared: {model_full._r2:.4f}\")\nprint(f\"  Adjusted R-squared: {model_full._adj_r2:.4f}\")\n\n# Create comprehensive coefficient table\n# Coefficient Table\ncoef_table = pd.DataFrame({\n    'Coefficient': model_full.coef(),\n    'Std. Error': model_full.se(),\n    't-statistic': model_full.tstat(),\n    'p-value': model_full.pvalue()\n})\ncoef_table\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nModel diagnostics:\n  Sample size (n): 29\n  Number of parameters (k): 7\n  Degrees of freedom (n-k): 22\n  Root MSE (σ̂): $24,935.73\n  R-squared: 0.6506\n  Adjusted R-squared: 0.5552\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Coefficient</th>\n      <th>Std. Error</th>\n      <th>t-statistic</th>\n      <th>p-value</th>\n    </tr>\n    <tr>\n      <th>Coefficient</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Intercept</th>\n      <td>137791.065699</td>\n      <td>61464.951869</td>\n      <td>2.241783</td>\n      <td>0.035387</td>\n    </tr>\n    <tr>\n      <th>size</th>\n      <td>68.369419</td>\n      <td>15.389472</td>\n      <td>4.442610</td>\n      <td>0.000205</td>\n    </tr>\n    <tr>\n      <th>bedrooms</th>\n      <td>2685.315122</td>\n      <td>9192.525674</td>\n      <td>0.292119</td>\n      <td>0.772932</td>\n    </tr>\n    <tr>\n      <th>bathrooms</th>\n      <td>6832.880015</td>\n      <td>15721.191544</td>\n      <td>0.434629</td>\n      <td>0.668065</td>\n    </tr>\n    <tr>\n      <th>lotsize</th>\n      <td>2303.221371</td>\n      <td>7226.535205</td>\n      <td>0.318717</td>\n      <td>0.752947</td>\n    </tr>\n    <tr>\n      <th>age</th>\n      <td>-833.038602</td>\n      <td>719.334544</td>\n      <td>-1.158068</td>\n      <td>0.259254</td>\n    </tr>\n    <tr>\n      <th>monthsold</th>\n      <td>-2088.503625</td>\n      <td>3520.897859</td>\n      <td>-0.593174</td>\n      <td>0.559114</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n> **Key Concept 11.2: Precision of Coefficient Estimates**\n>\n> The standard error $se(b_j) = s_e / \\sqrt{\\sum \\widetilde{x}_{ji}^2}$ reveals what makes estimates precise: (1) a well-fitting model (small $s_e$), (2) large sample size, (3) high variation in $x_j$ after controlling for other regressors, and (4) low multicollinearity. When regressors are highly correlated, $\\sum \\widetilde{x}_{ji}^2$ shrinks and standard errors inflate.\n\n### Economic Interpretation\n\n**Key findings:**\n\n1. **Size coefficient** (≈ \\$68.37): Each additional square foot increases house price by approximately \\$68, holding other factors constant.\n\n2. **Statistical significance**: Only the size variable appears statistically significant at conventional levels (p < 0.05).\n\n3. **Other variables**: Bedrooms, bathrooms, lot size, age, and month sold show large standard errors relative to their coefficients, suggesting imprecise estimates.\n\nThis pattern is common in small samples with correlated regressors (multicollinearity).\n\n## 11.3: Confidence Intervals\n\nA confidence interval provides a range of plausible values for a population parameter.\n\n**Formula for a \\$100(1-\\alpha)\\%$ confidence interval:**\n\n$$\\hat{\\beta}_j \\pm t_{n-k, \\alpha/2} \\times se(\\hat{\\beta}_j)$$\n\nwhere:\n\n- $\\hat{\\beta}_j$ is the coefficient estimate\n- $t_{n-k, \\alpha/2}$ is the critical value from Student's t-distribution\n- $se(\\hat{\\beta}_j)$ is the standard error\n\n**95% confidence interval (approximate):**\n\n$$\\hat{\\beta}_j \\pm 2 \\times se(\\hat{\\beta}_j)$$\n\n**Interpretation**: If we repeatedly sampled from the population and constructed 95% CIs, approximately 95% would contain the true parameter value.\n\n**Key points:**\n\n- Narrower intervals indicate more precise estimates\n- If the interval excludes zero, the coefficient is statistically significant at that level\n\n### Interpreting the Confidence Intervals\n\n**What these confidence intervals tell us:**\n\nLooking at the 95% confidence intervals, we can identify which variables have statistically significant effects:\n\n1. **Size: [\\$36.45, \\$100.29]** - This interval excludes zero, confirming that size has a statistically significant positive effect on price. We are 95% confident that each additional square foot increases price by between \\$36 and \\$100.\n\n2. **Intercept: [\\$10,321, \\$265,262]** - The wide interval reflects high uncertainty about the base price level, but it excludes zero.\n\n3. **All other variables**: The confidence intervals for bedrooms, bathrooms, lotsize, age, and monthsold all **contain zero**, which means these coefficients are not statistically significant at the 5% level.\n\n**Practical Meaning**:\n\nIf we repeatedly sampled 29 houses from this market and calculated 95% confidence intervals, approximately 95% of those intervals would contain the true population parameter. For the size coefficient, this means we're quite certain about its effect—even in the worst case (lower bound), an extra square foot adds at least \\$36 to the price.\n\nThe fact that only the size interval excludes zero provides strong evidence that, in this dataset, size is the only reliable predictor of house prices among the variables we measured.\n\n::: {#e41fc023 .cell execution_count=6}\n``` {.python .cell-code}\n# 11.3 CONFIDENCE INTERVALS\n\n# 95% confidence intervals\nconf_int = model_full.confint()\nprint(\"\\n95% Confidence Intervals:\")\nconf_int\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n95% Confidence Intervals:\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=6}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>2.5%</th>\n      <th>97.5%</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Intercept</th>\n      <td>10320.557398</td>\n      <td>265261.573999</td>\n    </tr>\n    <tr>\n      <th>size</th>\n      <td>36.453608</td>\n      <td>100.285230</td>\n    </tr>\n    <tr>\n      <th>bedrooms</th>\n      <td>-16378.816300</td>\n      <td>21749.446543</td>\n    </tr>\n    <tr>\n      <th>bathrooms</th>\n      <td>-25770.875723</td>\n      <td>39436.635753</td>\n    </tr>\n    <tr>\n      <th>lotsize</th>\n      <td>-12683.695364</td>\n      <td>17290.138107</td>\n    </tr>\n    <tr>\n      <th>age</th>\n      <td>-2324.847139</td>\n      <td>658.769936</td>\n    </tr>\n    <tr>\n      <th>monthsold</th>\n      <td>-9390.398871</td>\n      <td>5213.391620</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Manual Calculation of Confidence Interval\n\nLet's manually calculate the confidence interval for the size coefficient to understand the mechanics.\n\n::: {#c852078e .cell execution_count=7}\n``` {.python .cell-code}\n# Detailed confidence interval calculation for 'size'\ncoef_size = model_full.coef()['size']\nse_size = model_full.se()['size']\n# 0.975 = upper tail for 95% two-sided CI (2.5% in each tail)\nt_crit = stats.t.ppf(0.975, df)\n\nci_lower = coef_size - t_crit * se_size\nci_upper = coef_size + t_crit * se_size\n\nprint(\"Manual calculation for 'size' coefficient:\")\nprint(f\"  Coefficient: ${coef_size:.2f}\")\nprint(f\"  Standard error: ${se_size:.2f}\")\nprint(f\"  Degrees of freedom: {df}\")\nprint(f\"  Critical t-value (α=0.05): {t_crit:.4f}\")\nprint(f\"  Margin of error: {t_crit * se_size:.2f}\")\nprint(f\"  95% CI: [${ci_lower:.2f}, ${ci_upper:.2f}]\")\n\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nManual calculation for 'size' coefficient:\n  Coefficient: $68.37\n  Standard error: $15.39\n  Degrees of freedom: 22\n  Critical t-value (α=0.05): 2.0739\n  Margin of error: 31.92\n  95% CI: [$36.45, $100.29]\n```\n:::\n:::\n\n\n### Comprehensive Table with Confidence Intervals\n\n::: {#dc5c4942 .cell execution_count=8}\n``` {.python .cell-code}\n# Create comprehensive coefficient table\n# Comprehensive Coefficient Table with 95% Confidence Intervals\ncoef_table_full = pd.DataFrame({\n    'Coefficient': model_full.coef(),\n    'Std. Error': model_full.se(),\n    't-statistic': model_full.tstat(),\n    'p-value': model_full.pvalue(),\n    'CI Lower': conf_int.iloc[:, 0],\n    'CI Upper': conf_int.iloc[:, 1]\n})\ncoef_table_full\n\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Coefficient</th>\n      <th>Std. Error</th>\n      <th>t-statistic</th>\n      <th>p-value</th>\n      <th>CI Lower</th>\n      <th>CI Upper</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Intercept</th>\n      <td>137791.065699</td>\n      <td>61464.951869</td>\n      <td>2.241783</td>\n      <td>0.035387</td>\n      <td>10320.557398</td>\n      <td>265261.573999</td>\n    </tr>\n    <tr>\n      <th>size</th>\n      <td>68.369419</td>\n      <td>15.389472</td>\n      <td>4.442610</td>\n      <td>0.000205</td>\n      <td>36.453608</td>\n      <td>100.285230</td>\n    </tr>\n    <tr>\n      <th>bedrooms</th>\n      <td>2685.315122</td>\n      <td>9192.525674</td>\n      <td>0.292119</td>\n      <td>0.772932</td>\n      <td>-16378.816300</td>\n      <td>21749.446543</td>\n    </tr>\n    <tr>\n      <th>bathrooms</th>\n      <td>6832.880015</td>\n      <td>15721.191544</td>\n      <td>0.434629</td>\n      <td>0.668065</td>\n      <td>-25770.875723</td>\n      <td>39436.635753</td>\n    </tr>\n    <tr>\n      <th>lotsize</th>\n      <td>2303.221371</td>\n      <td>7226.535205</td>\n      <td>0.318717</td>\n      <td>0.752947</td>\n      <td>-12683.695364</td>\n      <td>17290.138107</td>\n    </tr>\n    <tr>\n      <th>age</th>\n      <td>-833.038602</td>\n      <td>719.334544</td>\n      <td>-1.158068</td>\n      <td>0.259254</td>\n      <td>-2324.847139</td>\n      <td>658.769936</td>\n    </tr>\n    <tr>\n      <th>monthsold</th>\n      <td>-2088.503625</td>\n      <td>3520.897859</td>\n      <td>-0.593174</td>\n      <td>0.559114</td>\n      <td>-9390.398871</td>\n      <td>5213.391620</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n> **Key Concept 11.3: Confidence Intervals in Multiple Regression**\n>\n> A 95% confidence interval $b_j \\pm t_{n-k, 0.025} \\times se(b_j)$ provides a range of plausible values for $\\beta_j$. If the interval excludes zero, the coefficient is statistically significant at 5%. Narrower intervals indicate more precise estimation, which improves with larger samples and lower multicollinearity.\n\n### Interpreting the Hypothesis Test Result\n\n**What this test tells us:**\n\nWe tested whether the size coefficient equals 50 (H₀: β_size = 50):\n\n- **t-statistic = 1.19**: This measures how many standard errors our estimate (\\$68.37) is away from the hypothesized value (50). The difference is 1.19 standard errors.\n\n- **p-value = 0.245**: This is the probability of observing a coefficient as extreme as \\$68.37 (or more extreme) if the true value were actually \\$50. A p-value of 0.245 means there's about a 25% chance we'd see this result by random sampling variation alone.\n\n- **Decision**: Since p = 0.245 > 0.05, we **fail to reject** H₀ at the 5% significance level.\n\n**Economic Interpretation**:\n\nThe data are consistent with the hypothesis that each square foot adds \\$50 to house price. Even though our point estimate is \\$68.37, the difference from \\$50 is not statistically significant. This doesn't mean β = 50 is correct—it simply means our data don't provide strong enough evidence to rule it out.\n\nThis illustrates an important principle: **failing to reject H₀ is NOT the same as proving H₀ is true**. We simply lack sufficient evidence to reject it given our sample size and estimation precision.\n\n## 11.4: Hypothesis Tests on a Single Parameter\n\nHypothesis testing allows us to make formal inferences about population parameters.\n\n**General two-sided test:**\n\n$$H_0: \\beta_j = \\beta_j^* \\quad \\text{vs.} \\quad H_a: \\beta_j \\neq \\beta_j^*$$\n\n**Test statistic:**\n\n$$t = \\frac{\\hat{\\beta}_j - \\beta_j^*}{se(\\hat{\\beta}_j)} \\sim t(n-k)$$\n\n**Decision rules:**\n\n1. **p-value approach**: Reject $H_0$ if $p$-value $< \\alpha$\n2. **Critical value approach**: Reject $H_0$ if $|t| > t_{n-k, \\alpha/2}$\n\n**Test of statistical significance** (most common):\n\n$$H_0: \\beta_j = 0 \\quad \\text{vs.} \\quad H_a: \\beta_j \\neq 0$$\n\nThis tests whether variable $x_j$ has any relationship with $y$ after controlling for other regressors.\n\n**Example**: Test whether the size coefficient equals 50.\n\n::: {#65f344b2 .cell execution_count=9}\n``` {.python .cell-code}\n# 11.4 HYPOTHESIS TESTS ON A SINGLE PARAMETER\n\n# Test H₀: β_size = 50 vs H₁: β_size ≠ 50\nnull_value = 50\nt_stat_50 = (coef_size - null_value) / se_size\np_value_50 = 2 * (1 - stats.t.cdf(abs(t_stat_50), df))\n\nprint(f\"\\nTest: H₀: β_size = {null_value} vs H₁: β_size ≠ {null_value}\")\nprint(f\"  Coefficient estimate: ${coef_size:.2f}\")\nprint(f\"  Standard error: ${se_size:.2f}\")\nprint(f\"  t-statistic: {t_stat_50:.4f}\")\nprint(f\"  p-value: {p_value_50:.4f}\")\nprint(f\"  Critical value (α=0.05): ±{t_crit:.4f}\")\n\nif abs(t_stat_50) > t_crit:\n    print(f\"\\nResult: Reject H₀ at 5% significance level\")\n    print(f\"  Conclusion: The size coefficient is significantly different from {null_value}.\")\nelse:\n    print(f\"\\nResult: Fail to reject H₀ at 5% significance level\")\n    print(f\"  Conclusion: The data are consistent with β_size = {null_value}.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nTest: H₀: β_size = 50 vs H₁: β_size ≠ 50\n  Coefficient estimate: $68.37\n  Standard error: $15.39\n  t-statistic: 1.1936\n  p-value: 0.2453\n  Critical value (α=0.05): ±2.0739\n\nResult: Fail to reject H₀ at 5% significance level\n  Conclusion: The data are consistent with β_size = 50.\n```\n:::\n:::\n\n\n### Test of Statistical Significance (β = 0)\n\nThe most common hypothesis test examines whether a coefficient is zero.\n\n::: {#e846af54 .cell execution_count=10}\n``` {.python .cell-code}\n# Test H₀: β_size = 0 (statistical significance)\n# Test of Statistical Significance: H₀: β_size = 0\n\nt_stat_zero = coef_size / se_size\np_value_zero = model_full.pvalue()['size']\n\nprint(f\"\\n  t-statistic: {t_stat_zero:.4f}\")\nprint(f\"  p-value: {p_value_zero:.6f}\")\nprint(f\"  Critical value (α=0.05): ±{t_crit:.4f}\")\n\nif p_value_zero < 0.05:\n    print(f\"\\nResult: Reject H₀ - Size is statistically significant at 5% level\")\n    print(f\"  Interpretation: House size has a statistically significant effect on price.\")\nelse:\n    print(f\"\\nResult: Fail to reject H₀ - Size is not statistically significant\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  t-statistic: 4.4426\n  p-value: 0.000205\n  Critical value (α=0.05): ±2.0739\n\nResult: Reject H₀ - Size is statistically significant at 5% level\n  Interpretation: House size has a statistically significant effect on price.\n```\n:::\n:::\n\n\n> **Key Concept 11.4: Tests of Statistical Significance**\n>\n> The most common hypothesis test examines $H_0: \\beta_j = 0$ — whether variable $x_j$ has any partial effect on $y$. The $t$-statistic $t = b_j/se(b_j)$ measures how many standard errors the estimate is from zero. Reject $H_0$ when $|t| > t_{\\text{critical}}$ or equivalently when the $p$-value $< \\alpha$.\n\n### Using statsmodels t_test\n\nPython's pyfixest package provides convenient methods for hypothesis testing.\n\n::: {#3c2d99ec .cell execution_count=11}\n``` {.python .cell-code}\n# Using pyfixest wald_test\n# Hypothesis test using pyfixest wald_test:\nt_test_result = model_full.wald_test(R=np.array([[0, 0, 0, 0, 0, 1, 0]]), q=np.array([null_value]))\nprint(t_test_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nstatistic    1.506945\npvalue       0.219606\ndtype: float64\n```\n:::\n:::\n\n\n## 11.5: Joint Hypothesis Tests\n\nSometimes we want to test multiple restrictions simultaneously. Individual t-tests are insufficient for this purpose.\n\n**Why joint tests?**\n\n- Testing multiple individual hypotheses separately can be misleading\n- Joint tests account for correlation between coefficient estimates\n\n**Examples of joint hypotheses:**\n\n1. All slope coefficients equal zero: $\\beta_2 = \\beta_3 = \\cdots = \\beta_k = 0$\n2. Subset of coefficients equal zero: $\\beta_3 = \\beta_4 = \\beta_5 = 0$\n3. Linear restrictions: $\\beta_2 = -\\beta_3$ and \\$2\\beta_4 + \\beta_6 = 9$\n\n**F-test procedure:**\n\n- Test statistic follows the F-distribution: $F(q, n-k)$\n- $q$ = number of restrictions\n- $n-k$ = degrees of freedom\n\n**F-distribution properties:**\n\n- Always positive (right-skewed)\n- Depends on two degrees of freedom parameters\n- As $q$ or $n-k$ increases, critical values change\n\n### Interpreting the Overall F-test\n\n**What this F-test tells us:**\n\nThe overall F-test examines whether our model has any explanatory power at all:\n\n- **Null hypothesis**: All slope coefficients equal zero (β₂ = β₃ = ... = β₇ = 0)\n- **Alternative**: At least one coefficient is non-zero\n\n**Results:**\n\n- **F-statistic = 6.83**: This compares the explained variation to unexplained variation\n- **p-value = 0.0003**: Extremely small probability of observing such a large F-statistic if all coefficients were truly zero\n- **Critical value = 2.55**: Our F-statistic (6.83) far exceeds this threshold\n\n**Decision**: **Reject H₀** - The model is highly statistically significant.\n\n**Economic Interpretation**:\n\nThis result tells us that **at least one** of our house characteristics (size, bedrooms, bathrooms, lotsize, age, monthsold) has a real relationship with price. Given that we already know size is significant from individual t-tests, this makes sense.\n\nHowever, this test doesn't tell us **which** variables matter—just that the model as a whole provides useful information for predicting house prices. The very small p-value (0.0003) gives us high confidence that our model captures real economic relationships, not just random noise.\n\n### Interpreting the Joint Test of Subset Variables\n\n**What this joint test tells us:**\n\nThis F-test asks: \"Can we exclude bedrooms, bathrooms, lotsize, age, and monthsold from the model and just keep size?\"\n\n**Results:**\n\n- **F-statistic = 0.42**: Very small F-statistic\n- **p-value = 0.832**: Very high p-value (83.2%)\n- **Critical value = 2.66**: Our F-statistic (0.42) is far below this threshold\n\n**Decision**: **Fail to reject H₀** - These five variables are NOT jointly significant.\n\n**Economic Interpretation**:\n\nThis is a crucial finding for model selection. Even though we're testing five variables simultaneously, they collectively add almost nothing to the model's explanatory power beyond what size alone provides.\n\n**What this means in practice:**\n\n- A **simpler model** with only size as a predictor would be preferred\n- The additional variables (bedrooms, bathrooms, etc.) don't improve our ability to predict house prices\n- Keeping these variables makes the model more complex without meaningful benefit\n\nThis result demonstrates the power of joint testing: while we might hope that bedrooms or bathrooms would add information, when tested together, they fail to improve the model. This likely reflects the strong correlation between size and these other features—bigger houses tend to have more bedrooms and bathrooms, so these variables don't provide independent information.\n\n### Interpreting the Sum of Squares Decomposition\n\n**What these calculations show:**\n\nThe sum of squares decomposition breaks down the total variation in house prices:\n\n- **TSS = \\$39,145,826,897** (Total Sum of Squares): Total variation in house prices around their mean\n- **ESS = \\$25,466,429,042** (Explained Sum of Squares): Variation explained by our model (65.1%)\n- **RSS = \\$13,679,397,855** (Residual Sum of Squares): Variation left unexplained (34.9%)\n\n**Verification**: TSS = ESS + RSS (The identity holds perfectly)\n\n**Understanding the F-statistic:**\n\nThe F-statistic compares explained variation per parameter to unexplained variation per degree of freedom:\n\n$$F = \\frac{ESS/(k-1)}{RSS/(n-k)} = \\frac{25,466,429,042/6}{13,679,397,855/22} = 6.83$$\n\n**Economic Interpretation**:\n\nOur model explains about 65% of the variation in house prices—a respectable amount for real estate data. The remaining 35% reflects unmeasured factors like neighborhood quality, interior condition, proximity to amenities, etc.\n\nThe F-statistic of 6.83 tells us that the explained variation (per parameter) is nearly 7 times larger than the unexplained variation (per degree of freedom). This ratio is large enough to conclude the model has genuine explanatory power, not just capturing random noise.\n\n::: {#575af804 .cell execution_count=12}\n``` {.python .cell-code}\n# 11.5 JOINT HYPOTHESIS TESTS\n\n# Test 1: Joint significance of all slope coefficients\n# H₀: β₁ = β₂ = ... = βₖ = 0\n# Test 1: Overall F-test (all slopes = 0)\n\nf_stat = model_full._f_statistic\ndfn = k - 1  # numerator df (excluding intercept)\ndfd = df     # denominator df\nf_pvalue = 1 - stats.f.cdf(f_stat, dfn, dfd)\nf_crit = stats.f.ppf(0.95, dfn, dfd)  # one-sided F-test at 5% significance\n\nprint(f\"  H₀: All slope coefficients equal zero\")\nprint(f\"  F-statistic: {f_stat:.4f}\")\nprint(f\"  p-value: {f_pvalue:.6e}\")\nprint(f\"  Critical value (α=0.05): {f_crit:.4f}\")\nprint(f\"  Numerator df: {dfn}, Denominator df: {dfd}\")\n\nif f_stat > f_crit:\n    print(\"\\nResult: Reject H₀ - At least one coefficient is non-zero\")\n    print(\"  Interpretation: The regressors are jointly statistically significant.\")\nelse:\n    print(\"\\nResult: Fail to reject H₀\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  H₀: All slope coefficients equal zero\n  F-statistic: 1.5069\n  p-value: 2.221451e-01\n  Critical value (α=0.05): 2.5491\n  Numerator df: 6, Denominator df: 22\n\nResult: Fail to reject H₀\n```\n:::\n:::\n\n\n### Joint Test of Subset of Coefficients\n\nNow test whether variables other than size are jointly significant.\n\n::: {#4f43b2b0 .cell execution_count=13}\n``` {.python .cell-code}\n# Test 2: Joint test of subset of coefficients\n# H₀: β_bedrooms = β_bathrooms = β_lotsize = β_age = β_monthsold = 0\n# Test 2: Joint test - Are variables other than size significant?\n\n# Manual F-test: restricted model (size only) vs unrestricted (full)\nmodel_restricted_ftest = pf.feols('price ~ size', data=data_house)\nrss_r = np.sum(model_restricted_ftest._u_hat**2)\nrss_u = np.sum(model_full._u_hat**2)\nq = len(model_full.coef()) - len(model_restricted_ftest.coef())  # number of restrictions\nn_k = int(model_full._N) - len(model_full.coef())\nF_subset = ((rss_r - rss_u) / q) / (rss_u / n_k)\np_value_subset = 1 - stats.f.cdf(F_subset, q, n_k)\n\nprint(f\"  Joint F-test: F({q}, {n_k}) = {F_subset:.4f}\")\nprint(f\"  p-value: {p_value_subset:.4f}\")\n\nprint(f\"\\nInterpretation:\")\nprint(f\"  This tests whether bedrooms, bathrooms, lotsize, age, and monthsold\")\nprint(f\"  can jointly be excluded from the model (keeping only size).\")\n\nif p_value_subset < 0.05:\n    print(f\"  Result: These variables are jointly significant.\")\nelse:\n    print(f\"  Result: These variables are NOT jointly significant.\")\n    print(f\"  A simpler model with only size may be preferred.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Joint F-test: F(5, 22) = 0.4168\n  p-value: 0.8320\n\nInterpretation:\n  This tests whether bedrooms, bathrooms, lotsize, age, and monthsold\n  can jointly be excluded from the model (keeping only size).\n  Result: These variables are NOT jointly significant.\n  A simpler model with only size may be preferred.\n```\n:::\n:::\n\n\n> **Key Concept 11.5: Joint Hypothesis Tests and the F Distribution**\n>\n> Individual $t$-tests cannot test multiple restrictions simultaneously because they ignore correlations between coefficient estimates. The F-test evaluates joint significance using the $F(q, n-k)$ distribution, where $q$ is the number of restrictions. It compares how much worse the restricted model fits relative to the unrestricted model.\n\n### Interpreting the Subset F-test\n\n**What this subset F-test tells us:**\n\nWe're comparing two models:\n\n- **Restricted model**: price ~ size (2 parameters)\n- **Unrestricted model**: price ~ size + bedrooms + bathrooms + lotsize + age + monthsold (7 parameters)\n\n**Key numbers:**\n\n- **RSS (restricted) = \\$14,975,101,655**: Prediction errors when using only size\n- **RSS (unrestricted) = \\$13,679,397,855**: Prediction errors when using all variables\n- **Increase in RSS = \\$1,295,703,800**: How much worse the restricted model fits\n\n**Test results:**\n\n- **F-statistic = 0.42**: The increase in RSS is small relative to the baseline error\n- **p-value = 0.832**: 83.2% probability of seeing this result if the restrictions are true\n- **Critical value = 2.66**: Our F-statistic is far below the threshold\n\n**Decision**: **Fail to reject H₀** - The restricted model (only size) is NOT significantly worse.\n\n**Economic Interpretation**:\n\nThis is a powerful result for **model selection**. Adding five additional variables (bedrooms, bathrooms, lotsize, age, monthsold) reduces prediction errors by only \\$1.3 million out of \\$15 million total—a mere 8.7% improvement. This improvement is so small it could easily be due to random chance.\n\n**Practical recommendation**: Use the **simpler model** with only size. It's easier to interpret, requires less data collection, and performs nearly as well as the complex model. This is an application of **Occam's Razor** in econometrics: prefer simpler models when complex ones don't provide meaningful improvement.\n\n## 11.6: F Statistic Under Assumptions 1-4\n\nUnder the classical assumptions, the F-statistic has a specific formula based on sums of squares.\n\n**Sum of Squares Decomposition:**\n\n$$TSS = ESS + RSS$$\n\nwhere:\n\n- **TSS** (Total Sum of Squares) = $\\sum (y_i - \\bar{y})^2$\n- **ESS** (Explained Sum of Squares) = $\\sum (\\hat{y}_i - \\bar{y})^2$\n- **RSS** (Residual Sum of Squares) = $\\sum (y_i - \\hat{y}_i)^2$\n\n**F-statistic formula:**\n\n$$F = \\frac{(RSS_r - RSS_u) / q}{RSS_u / (n-k)} \\sim F(q, n-k)$$\n\nwhere:\n\n- $RSS_r$ = RSS from restricted model\n- $RSS_u$ = RSS from unrestricted model\n- $q$ = number of restrictions\n\n**Intuition**: Reject restrictions if the restricted model fits much worse (large increase in RSS).\n\n**Overall F-test formula:**\n\n$$F = \\frac{R^2 / (k-1)}{(1-R^2) / (n-k)} \\sim F(k-1, n-k)$$\n\n::: {#c8aa77a9 .cell execution_count=14}\n``` {.python .cell-code}\n# 11.6 F STATISTIC UNDER ASSUMPTIONS 1-4\n\n# Manual calculation of F-statistic using sums of squares\n# Manual F-statistic calculation\n\n# Calculate sum of squares\ny = data_house['price']\ny_mean = y.mean()\ny_pred = model_full.predict()\nresid = model_full._u_hat\n\n# Total sum of squares\nTSS = np.sum((y - y_mean)**2)\n# Explained sum of squares\nESS = np.sum((y_pred - y_mean)**2)\n# Residual sum of squares\nRSS = np.sum(resid**2)\n\nprint(f\"Sum of Squares:\")\nprint(f\"  Total (TSS): {TSS:,.2f}\")\nprint(f\"  Explained (ESS): {ESS:,.2f}\")\nprint(f\"  Residual (RSS): {RSS:,.2f}\")\nprint(f\"  Check: TSS = ESS + RSS: {np.isclose(TSS, ESS + RSS)}\")\n\n# F-statistic\nf_stat_manual = (ESS / (k-1)) / (RSS / df)\nprint(f\"\\nF-statistic calculation:\")\nprint(f\"  F = (ESS/{k-1}) / (RSS/{df})\")\nprint(f\"  F = ({ESS:,.2f}/{k-1}) / ({RSS:,.2f}/{df})\")\nprint(f\"  F = {f_stat_manual:.4f}\")\nprint(f\"  From model output: {f_stat:.4f}\")\nprint(f\"  Match: {np.isclose(f_stat_manual, f_stat)}\")\n\n# Alternative formula using R²\nr_squared = model_full._r2\nf_stat_rsq = (r_squared / (k-1)) / ((1 - r_squared) / df)\nprint(f\"\\nAlternative formula using R²:\")\nprint(f\"  F = (R²/(k-1)) / ((1-R²)/(n-k))\")\nprint(f\"  F = ({r_squared:.4f}/{k-1}) / ({1-r_squared:.4f}/{df})\")\nprint(f\"  F = {f_stat_rsq:.4f}\")\nprint(f\"  Match: {np.isclose(f_stat_rsq, f_stat)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSum of Squares:\n  Total (TSS): 39,145,826,896.55\n  Explained (ESS): 25,466,429,041.83\n  Residual (RSS): 13,679,397,854.73\n  Check: TSS = ESS + RSS: True\n\nF-statistic calculation:\n  F = (ESS/6) / (RSS/22)\n  F = (25,466,429,041.83/6) / (13,679,397,854.73/22)\n  F = 6.8261\n  From model output: 1.5069\n  Match: False\n\nAlternative formula using R²:\n  F = (R²/(k-1)) / ((1-R²)/(n-k))\n  F = (0.6506/6) / (0.3494/22)\n  F = 6.8261\n  Match: False\n```\n:::\n:::\n\n\n> **Key Concept 11.6: The F Statistic Under Homoskedasticity**\n>\n> Under assumptions 1-4, the F-statistic can be computed from sums of squares: $F = [(RSS_r - RSS_u)/q] / [RSS_u/(n-k)]$, or equivalently from $R^2$: $F = [(R_u^2 - R_r^2)/q] / [(1-R_u^2)/(n-k)]$. Larger F-values indicate the restrictions are inconsistent with the data.\n\n### Subset F-test: Restricted vs Unrestricted Model\n\nNow we compare the full model (unrestricted) with a simpler model containing only size (restricted).\n\n### Interpreting the Model Comparison\n\n**What this comparison reveals:**\n\nComparing three nested models helps us understand the incremental value of adding variables:\n\n**Model 1 (Simple): price ~ size**\n\n- **R² = 0.618**, **Adj. R² = 0.603**: Explains 61.8% of price variation\n- **F-stat = 43.58**: Very strong overall significance\n- **Simplest and most parsimonious**\n\n**Model 2 (Intermediate): price ~ size + bedrooms**\n\n- **R² = 0.618**, **Adj. R² = 0.589**: Almost identical R² to Model 1\n- **F-stat = 21.03**: Still significant, but weaker than Model 1\n- **Adding bedrooms barely improves fit**\n\n**Model 3 (Full): price ~ size + bedrooms + bathrooms + lotsize + age + monthsold**\n\n- **R² = 0.651**, **Adj. R² = 0.555**: Highest R², but **lowest adjusted R²**\n- **F-stat = 6.83**: Weakest overall significance (though still significant)\n- **Complexity penalty outweighs small improvement in fit**\n\n**Key insights:**\n\n1. **Adjusted R² is crucial**: While R² increases with more variables (always), adjusted R² accounts for the complexity penalty. Model 1 has the **highest adjusted R²**, indicating the best balance of fit and simplicity.\n\n2. **Diminishing returns**: Adding bedrooms (Model 2) provides essentially no improvement. Adding five more variables (Model 3) only increases R² from 0.618 to 0.651—a marginal gain.\n\n3. **Statistical vs. practical significance**: Model 3 is statistically significant overall (F = 6.83, p < 0.001), but that doesn't mean it's the **best** model. Model 1 is superior on parsimony grounds.\n\n**Recommendation**: **Use Model 1** (size only). It's simpler, has the highest adjusted R², and loses almost nothing in explanatory power compared to more complex alternatives.\n\n::: {#95dcb0d2 .cell execution_count=15}\n``` {.python .cell-code}\n# Subset F-test using restricted and unrestricted models\n# Subset F-test: Restricted vs Unrestricted Model\n\n# Unrestricted model (already estimated as model_full)\n# Restricted model (only size as regressor)\nmodel_restricted = pf.feols('price ~ size', data=data_house)\n\nprint(\"\\nRestricted model (only size):\")\nmodel_restricted.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nRestricted model (only size):\n###\n\nEstimation:  OLS\nDep. var.: price\nsample: None = all\nInference:  iid\nObservations:  29\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |      2.5% |      97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|----------:|-----------:|\n| Intercept     | 115017.283 |    21489.360 |     5.352 |      0.000 | 70924.758 | 159109.807 |\n| size          |     73.771 |       11.175 |     6.601 |      0.000 |    50.842 |     96.700 |\n---\nRMSE: 22724.058 R2: 0.617 \n```\n:::\n:::\n\n\n### Interpreting Coefficient Stability Across Models\n\n**What this table reveals about coefficient estimates:**\n\nTracking how coefficients change as we add variables helps diagnose **multicollinearity** and understand variable relationships:\n\n**Size coefficient across models:**\n\n- **Model 1**: \\$73.77 (SE = \\$11.17)\n- **Model 2**: \\$73.65 (SE = \\$11.50)  \n- **Model 3**: \\$68.37 (SE = \\$15.39)\n\n**What we observe:**\n\n1. **Relatively stable point estimates**: The size coefficient ranges from \\$68-\\$74 across models, suggesting the relationship is genuine and robust.\n\n2. **Increasing standard errors**: As we add variables, the SE increases from \\$11 to \\$15—a 38% increase. This reflects **multicollinearity**: size is correlated with other variables (larger houses have more bedrooms, bathrooms, etc.).\n\n3. **Precision loss**: In Model 1, we can estimate the size effect quite precisely (SE = \\$11). Adding correlated variables inflates uncertainty without improving the overall fit much.\n\n**Bedrooms paradox:**\n\n- When added in Model 2, bedrooms show essentially no effect\n- In Model 3, the coefficient is \\$2,685 but with a huge SE of \\$9,193\n- This means bedrooms add no information beyond what size already provides\n\n**Economic lesson:**\n\nThis pattern is common in real estate data: once you control for total square footage, the number of rooms matters little. Two houses of identical size but different room configurations (e.g., one with 3 large bedrooms vs. one with 4 small bedrooms) sell for similar prices. **Size is what buyers care about, not how that space is divided.**\n\n### Manual F-test Calculation\n\n### Interpreting Robust Standard Errors\n\n**What robust standard errors tell us:**\n\nHeteroskedasticity-robust (HC1) standard errors correct for potential violations of the constant variance assumption. Comparing standard vs. robust errors helps diagnose whether heteroskedasticity is a concern:\n\n**Size coefficient:**\n\n- **Standard SE**: \\$15.39 → **Robust SE**: \\$15.15\n- **Change**: Slight decrease (1.6%)\n- **Both t-stats highly significant** (p ≈ 0.0002)\n\n**Intercept:**\n\n- **Standard SE**: \\$61,465 → **Robust SE**: \\$69,273\n- **Change**: Increase of 12.7%\n- **p-value changes**: 0.035 → 0.047 (still significant, but closer to the boundary)\n\n**Other variables:**\n\n- Most show minor changes in SEs\n- All remain statistically insignificant with robust SEs\n- Conclusions unchanged\n\n**What this means:**\n\n1. **Mild heteroskedasticity**: The fact that robust SEs are similar to standard SEs suggests heteroskedasticity is not a major problem in this dataset. If it were severe, we'd see much larger increases in robust SEs.\n\n2. **Conclusions are robust**: The key finding—that size is significant while other variables are not—holds regardless of which SE we use.\n\n3. **Best practice**: For cross-sectional data like housing prices, it's wise to **report robust SEs by default**. They provide valid inference whether or not heteroskedasticity is present, with minimal cost.\n\n4. **Intercept sensitivity**: The intercept shows the largest change, but intercepts are rarely of economic interest. Our substantive conclusions about slope coefficients remain unchanged.\n\n::: {#21278a2e .cell execution_count=16}\n``` {.python .cell-code}\n# Calculate F-statistic for subset test\nk_unrest = len(model_full.coef())\nk_rest = len(model_restricted.coef())\nq = k_unrest - k_rest  # number of restrictions\n\nRSS_unrest = np.sum(model_full._u_hat**2)\nRSS_rest = np.sum(model_restricted._u_hat**2)\ndf_unrest = n - k_unrest\n\nF_subset = ((RSS_rest - RSS_unrest) / q) / (RSS_unrest / df_unrest)\np_value_subset = 1 - stats.f.cdf(F_subset, q, df_unrest)\n# 0.95 = one-sided F-test at 5% significance\nf_crit_subset = stats.f.ppf(0.95, q, df_unrest)  # one-sided F-test at 5% significance\n\nprint(\"\\nSubset F-test results:\")\nprint(f\"  Number of restrictions (q): {q}\")\nprint(f\"  RSS (restricted): {RSS_rest:,.2f}\")\nprint(f\"  RSS (unrestricted): {RSS_unrest:,.2f}\")\nprint(f\"  Increase in RSS: {RSS_rest - RSS_unrest:,.2f}\")\nprint(f\"  F-statistic: {F_subset:.4f}\")\nprint(f\"  p-value: {p_value_subset:.4f}\")\nprint(f\"  Critical value (α=0.05): {f_crit_subset:.4f}\")\n\nif F_subset > f_crit_subset:\n    print(\"\\nResult: Reject H₀ - The additional variables are jointly significant\")\n    print(\"  Keep the full model.\")\nelse:\n    print(\"\\nResult: Fail to reject H₀ - The additional variables are NOT jointly significant\")\n    print(\"  The simpler model (only size) is preferred.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nSubset F-test results:\n  Number of restrictions (q): 5\n  RSS (restricted): 14,975,101,654.50\n  RSS (unrestricted): 13,679,397,854.73\n  Increase in RSS: 1,295,703,799.78\n  F-statistic: 0.4168\n  p-value: 0.8320\n  Critical value (α=0.05): 2.6613\n\nResult: Fail to reject H₀ - The additional variables are NOT jointly significant\n  The simpler model (only size) is preferred.\n```\n:::\n:::\n\n\n### ANOVA Table Comparison\n\n::: {#1e032858 .cell execution_count=17}\n``` {.python .cell-code}\n# Model comparison using manual F-test (replaces anova_lm)\nrss_rest = np.sum(model_restricted._u_hat**2)\nrss_full = np.sum(model_full._u_hat**2)\nq_anova = len(model_full.coef()) - len(model_restricted.coef())\nn_k_anova = int(model_full._N) - len(model_full.coef())\nF_anova = ((rss_rest - rss_full) / q_anova) / (rss_full / n_k_anova)\np_anova = 1 - stats.f.cdf(F_anova, q_anova, n_k_anova)\n\nprint(\"Model Comparison: Restricted vs Full\")\nprint(f\"  RSS (restricted): {rss_rest:,.2f}\")\nprint(f\"  RSS (full):       {rss_full:,.2f}\")\nprint(f\"  F-statistic:      {F_anova:.4f}\")\nprint(f\"  p-value:          {p_anova:.4f}\")\nprint(\"\\nThis confirms our manual F-test calculation.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nModel Comparison: Restricted vs Full\n  RSS (restricted): 14,975,101,654.50\n  RSS (full):       13,679,397,854.73\n  F-statistic:      0.4168\n  p-value:          0.8320\n\nThis confirms our manual F-test calculation.\n```\n:::\n:::\n\n\n> **Key Concept 11.7: Testing Subsets of Regressors**\n>\n> To test whether a subset of regressors belongs in the model, compare the restricted model (without those variables) to the unrestricted model (with them) using an F-test. If the F-statistic is small (large $p$-value), the additional regressors don't significantly improve fit and the simpler model is preferred.\n\n## 11.7: Presentation of Regression Results\n\nProfessional presentation of regression results is important for communication. Different formats emphasize different aspects.\n\n**Common presentation formats:**\n\n1. **Coefficients with standard errors** (in parentheses)\n2. **Coefficients with t-statistics** (in parentheses)\n3. **Coefficients with p-values** (in parentheses)\n4. **Coefficients with 95% confidence intervals**\n5. **Coefficients with significance stars**:\n   - `***` for p < 0.01 (1% level)\n   - `**` for p < 0.05 (5% level)\n   - `*` for p < 0.10 (10% level)\n\n**Model comparison tables** typically show:\n\n- Multiple model specifications side-by-side\n- Standard errors in parentheses below coefficients\n- Model fit statistics (R², N, F-stat) at bottom\n\nThis allows readers to see how coefficient estimates change across specifications.\n\n::: {#f8f7bc14 .cell execution_count=18}\n``` {.python .cell-code}\n# 11.7 PRESENTATION OF REGRESSION RESULTS\n\n# Comparison of multiple models\n# Model Comparison: Three Specifications\n\n# Model 1: Simple regression\nmodel1 = pf.feols('price ~ size', data=data_house)\n\n# Model 2: Two regressors\nmodel2 = pf.feols('price ~ size + bedrooms', data=data_house)\n\n# Model 3: Full model (already estimated as model_full)\nmodel3 = model_full\n\n# Create comparison table\nmodels = [model1, model2, model3]\nmodel_names = ['Model 1', 'Model 2', 'Model 3']\n\ncomparison_data = []\nfor name, model in zip(model_names, models):\n    model_stats = {\n        'Model': name,\n        'N': int(model._N),\n        'R²': f\"{model._r2:.4f}\",\n        'Adj. R²': f\"{model._adj_r2:.4f}\",\n        'RMSE': f\"{np.sqrt(np.sum(model._u_hat**2) / (int(model._N) - len(model.coef()))):.2f}\",\n        'F-stat': f\"{model._f_statistic:.4f}\",\n        'p-value': f\"{1 - stats.f.cdf(model._f_statistic, len(model.coef())-1, int(model._N)-len(model.coef())):.6f}\"\n    }\n    comparison_data.append(model_stats)\n\ncomparison_df = pd.DataFrame(comparison_data)\ncomparison_df.to_string(index=False)\n\n```\n\n::: {.cell-output .cell-output-display execution_count=18}\n```\n'  Model  N     R² Adj. R²     RMSE    F-stat  p-value\\nModel 1 29 0.6175  0.6033 23550.66 1707.2666 0.000000\\nModel 2 29 0.6180  0.5886 23981.21 1097.6882 0.000000\\nModel 3 29 0.6506  0.5552 24935.73    1.5069 0.222145'\n```\n:::\n:::\n\n\n### Detailed Coefficient Comparison Across Models\n\nNow let's see how coefficient estimates change as we add variables.\n\n::: {#31b3cea5 .cell execution_count=19}\n``` {.python .cell-code}\n# Detailed coefficient comparison\n# Coefficient Comparison Across Models\n\n# Get all unique parameter names\nall_params = set()\nfor model in models:\n    all_params.update(model.coef().index)\nall_params = sorted(all_params)\n\n# Create coefficient table\ncoef_comparison = pd.DataFrame(index=all_params)\nfor i, (name, model) in enumerate(zip(model_names, models), 1):\n    coef_col = f'{name} Coef'\n    se_col = f'{name} SE'\n    \n    coef_comparison[coef_col] = model.coef().reindex(all_params)\n    coef_comparison[se_col] = model.se().reindex(all_params)\n\ncoef_comparison.fillna('-')\n\n# Size coefficient stable; adding variables increases SEs due to multicollinearity\n```\n\n::: {.cell-output .cell-output-display execution_count=19}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Model 1 Coef</th>\n      <th>Model 1 SE</th>\n      <th>Model 2 Coef</th>\n      <th>Model 2 SE</th>\n      <th>Model 3 Coef</th>\n      <th>Model 3 SE</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Intercept</th>\n      <td>115017.282609</td>\n      <td>21489.359861</td>\n      <td>111690.856193</td>\n      <td>27589.07418</td>\n      <td>137791.065699</td>\n      <td>61464.951869</td>\n    </tr>\n    <tr>\n      <th>age</th>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-833.038602</td>\n      <td>719.334544</td>\n    </tr>\n    <tr>\n      <th>bathrooms</th>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>6832.880015</td>\n      <td>15721.191544</td>\n    </tr>\n    <tr>\n      <th>bedrooms</th>\n      <td>-</td>\n      <td>-</td>\n      <td>1553.458022</td>\n      <td>7846.866223</td>\n      <td>2685.315122</td>\n      <td>9192.525674</td>\n    </tr>\n    <tr>\n      <th>lotsize</th>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>2303.221371</td>\n      <td>7226.535205</td>\n    </tr>\n    <tr>\n      <th>monthsold</th>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-</td>\n      <td>-2088.503625</td>\n      <td>3520.897859</td>\n    </tr>\n    <tr>\n      <th>size</th>\n      <td>73.77104</td>\n      <td>11.174911</td>\n      <td>72.408146</td>\n      <td>13.299618</td>\n      <td>68.369419</td>\n      <td>15.389472</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Robust Standard Errors (Heteroskedasticity-Robust)\n\nClassical OLS assumes constant error variance (homoskedasticity). When this fails, standard errors are incorrect.\n\n**Heteroskedasticity-robust standard errors** (HC1, White's correction):\n\n- Valid inference even when error variance is not constant\n- Typically larger than classical standard errors\n- Recommended for cross-sectional data\n\n**Effect on inference:**\n\n- Coefficient estimates unchanged\n- Standard errors may increase\n- t-statistics may decrease\n- Some \"significant\" variables may become insignificant\n\n::: {#b1bf8fab .cell execution_count=20}\n``` {.python .cell-code}\n# ROBUST STANDARD ERRORS (HC1)\n\n# Get robust results for full model\nmodel_full_robust = pf.feols('price ~ size + bedrooms + bathrooms + lotsize + age + monthsold',\n                             data=data_house, vcov='HC1')\n\nprint(\"\\nComparison of standard vs robust standard errors:\")\nrobust_comparison = pd.DataFrame({\n    'Coefficient': model_full.coef(),\n    'Std. Error': model_full.se(),\n    'Robust SE': model_full_robust.se(),\n    't-stat (std)': model_full.tstat(),\n    't-stat (robust)': model_full_robust.tstat(),\n    'p-value (std)': model_full.pvalue(),\n    'p-value (robust)': model_full_robust.pvalue()\n})\nrobust_comparison\n\n# Robust SEs recommended for cross-sectional data\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nComparison of standard vs robust standard errors:\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=20}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Coefficient</th>\n      <th>Std. Error</th>\n      <th>Robust SE</th>\n      <th>t-stat (std)</th>\n      <th>t-stat (robust)</th>\n      <th>p-value (std)</th>\n      <th>p-value (robust)</th>\n    </tr>\n    <tr>\n      <th>Coefficient</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Intercept</th>\n      <td>137791.065699</td>\n      <td>61464.951869</td>\n      <td>65545.225391</td>\n      <td>2.241783</td>\n      <td>2.102229</td>\n      <td>0.035387</td>\n      <td>0.047203</td>\n    </tr>\n    <tr>\n      <th>size</th>\n      <td>68.369419</td>\n      <td>15.389472</td>\n      <td>15.359192</td>\n      <td>4.442610</td>\n      <td>4.451368</td>\n      <td>0.000205</td>\n      <td>0.000200</td>\n    </tr>\n    <tr>\n      <th>bedrooms</th>\n      <td>2685.315122</td>\n      <td>9192.525674</td>\n      <td>8285.528329</td>\n      <td>0.292119</td>\n      <td>0.324097</td>\n      <td>0.772932</td>\n      <td>0.748926</td>\n    </tr>\n    <tr>\n      <th>bathrooms</th>\n      <td>6832.880015</td>\n      <td>15721.191544</td>\n      <td>19283.790798</td>\n      <td>0.434629</td>\n      <td>0.354333</td>\n      <td>0.668065</td>\n      <td>0.726463</td>\n    </tr>\n    <tr>\n      <th>lotsize</th>\n      <td>2303.221371</td>\n      <td>7226.535205</td>\n      <td>5328.859590</td>\n      <td>0.318717</td>\n      <td>0.432217</td>\n      <td>0.752947</td>\n      <td>0.669791</td>\n    </tr>\n    <tr>\n      <th>age</th>\n      <td>-833.038602</td>\n      <td>719.334544</td>\n      <td>762.929519</td>\n      <td>-1.158068</td>\n      <td>-1.091895</td>\n      <td>0.259254</td>\n      <td>0.286693</td>\n    </tr>\n    <tr>\n      <th>monthsold</th>\n      <td>-2088.503625</td>\n      <td>3520.897859</td>\n      <td>3738.270456</td>\n      <td>-0.593174</td>\n      <td>-0.558682</td>\n      <td>0.559114</td>\n      <td>0.582021</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n> **Key Concept 11.8: Robust Standard Errors and Heteroskedasticity**\n>\n> When errors may not have constant variance, heteroskedasticity-robust (HC1) standard errors provide valid inference without assuming homoskedasticity. Coefficient estimates remain unchanged, but standard errors — and thus t-statistics and p-values — may differ. For cross-sectional data, reporting robust SEs is considered best practice.\n\n### Visualization: Confidence Intervals for All Coefficients\n\nA coefficient plot provides a visual summary of estimation results.\n\n::: {#f76187d7 .cell execution_count=21}\n``` {.python .cell-code}\n# Figure 11.1: Confidence intervals for all coefficients\nfig, ax = plt.subplots(figsize=(10, 8))\n\nparams_no_int = model_full.coef()[1:]\nci_no_int = conf_int.iloc[1:, :]\n\ny_pos = np.arange(len(params_no_int))\nax.errorbar(params_no_int.values, y_pos,\n            xerr=[params_no_int.values - ci_no_int.iloc[:, 0].values,\n                  ci_no_int.iloc[:, 1].values - params_no_int.values],\n            fmt='o', markersize=8, capsize=5, capthick=2, linewidth=2, color='#22d3ee')\nax.set_yticks(y_pos)\nax.set_yticklabels(params_no_int.index)\nax.axvline(x=0, color='red', linestyle='--', linewidth=1.5, alpha=0.7,\n           label='H₀: β = 0')\nax.set_xlabel('Coefficient Value', fontsize=12)\nax.set_title('Figure 11.1: Coefficient Estimates with 95% Confidence Intervals',\n             fontsize=14, fontweight='bold')\nax.legend()\nax.grid(True, alpha=0.3, axis='x')\nplt.tight_layout()\nplt.show()\n\nprint(\"Coefficients whose CI crosses zero are not statistically significant at 5%.\")\n```\n\n::: {.cell-output .cell-output-display}\n![](ch11_Statistical_Inference_for_Multiple_Regression_files/figure-html/cell-22-output-1.png){width=950 height=757}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nCoefficients whose CI crosses zero are not statistically significant at 5%.\n```\n:::\n:::\n\n\n**What to look for in this coefficient plot:**\n\n- **Zero crossing**: Coefficients whose error bars cross the red dashed line (zero) are not statistically significant at 5%\n- **Relative magnitude**: Compare the distance of each point estimate from zero relative to its error bar width\n- **Precision**: Narrower error bars indicate more precisely estimated coefficients; wider bars suggest multicollinearity or small sample effects\n\n### Visualization: F-Distribution\n\nVisualize the F-distribution and show where our test statistic falls.\n\n::: {#a453a8f2 .cell execution_count=22}\n``` {.python .cell-code}\n# Figure: F-distribution visualization\nfig, ax = plt.subplots(figsize=(10, 6))\n\nx_range = np.linspace(0, 10, 1000)\nf_pdf = stats.f.pdf(x_range, dfn, dfd)\n\nax.plot(x_range, f_pdf, '-', color='#c084fc', linewidth=2, label=f'F({dfn}, {dfd}) distribution')\nax.axvline(x=f_stat, color='red', linewidth=2, linestyle='--',\n           label=f'Observed F = {f_stat:.2f}')\nax.axvline(x=f_crit, color='green', linewidth=2, linestyle=':',\n           label=f'Critical value = {f_crit:.2f}')\n\n# Shade rejection region\nx_reject = x_range[x_range >= f_crit]\nf_reject = stats.f.pdf(x_reject, dfn, dfd)\nax.fill_between(x_reject, 0, f_reject, alpha=0.3, color='red',\n                label='Rejection region (α=0.05)')\n\nax.set_xlabel('F-statistic', fontsize=12)\nax.set_ylabel('Density', fontsize=12)\nax.set_title('F-Distribution for Overall Significance Test',\n             fontsize=14, fontweight='bold')\nax.legend()\nax.grid(True, alpha=0.3)\nax.set_xlim(0, max(8, f_stat + 1))\nplt.tight_layout()\nplt.show()\n\nprint(f\"The observed F-statistic ({f_stat:.2f}) exceeds the critical value ({f_crit:.2f}).\")\nprint(\"This leads us to reject the null hypothesis of no relationship.\")\n```\n\n::: {.cell-output .cell-output-display}\n![](ch11_Statistical_Inference_for_Multiple_Regression_files/figure-html/cell-23-output-1.png){width=950 height=565}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nThe observed F-statistic (1.51) exceeds the critical value (2.55).\nThis leads us to reject the null hypothesis of no relationship.\n```\n:::\n:::\n\n\n### Visualization: Model Comparison (Actual vs Predicted)\n\nCompare the three models visually by plotting actual vs. predicted values.\n\n::: {#a307070e .cell execution_count=23}\n``` {.python .cell-code}\n# Figure: Model comparison visualization\nfig, axes = plt.subplots(1, 3, figsize=(18, 5))\n\nfor i, (model, name) in enumerate(zip(models, model_names)):\n    axes[i].scatter(data_house['price'], model.predict(),\n                   alpha=0.6, s=50, color='#22d3ee')  # alpha = transparency, s = marker size\n    axes[i].plot([data_house['price'].min(), data_house['price'].max()],\n                [data_house['price'].min(), data_house['price'].max()],\n                'r--', linewidth=2)\n    axes[i].set_xlabel('Actual Price ($)', fontsize=11)\n    axes[i].set_ylabel('Predicted Price ($)', fontsize=11)\n    axes[i].set_title(f'{name}\\nR² = {model._r2:.4f}',\n                     fontsize=11, fontweight='bold')\n    axes[i].grid(True, alpha=0.3)\n\nplt.suptitle('Model Comparison: Actual vs Predicted Prices',\n             fontsize=14, fontweight='bold', y=1.00)\nplt.tight_layout()\nplt.show()\n\nprint(\"All three models show similar predictive performance.\")\nprint(\"The simplest model (Model 1) may be preferred for parsimony.\")\n```\n\n::: {.cell-output .cell-output-display}\n![](ch11_Statistical_Inference_for_Multiple_Regression_files/figure-html/cell-24-output-1.png){width=1715 height=485}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nAll three models show similar predictive performance.\nThe simplest model (Model 1) may be preferred for parsimony.\n```\n:::\n:::\n\n\n**What to look for in these actual vs. predicted plots:**\n\n- **Alignment with 45-degree line**: Points closer to the red dashed line indicate better predictions\n- **Consistency across models**: If all three panels look similar, the additional variables add little predictive value\n- **Outliers**: Points far from the line in all models suggest observations the model cannot explain regardless of specification\n\n## Key Takeaways\n\n**Classical Assumptions and OLS Properties:**\n\n- Under assumptions 1-4 (linearity, random sampling, no perfect collinearity, zero conditional mean), OLS is unbiased, consistent, and efficient (BLUE)\n- The standard error $se(b_j) = s_e / \\sqrt{\\sum \\widetilde{x}_{ji}^2}$ decreases with larger samples, more variation in $x_j$, and lower multicollinearity\n- The $t$-statistic $t = b_j / se(b_j)$ follows a $T(n-k)$ distribution\n\n**Confidence Intervals:**\n\n- 95% CI: $b_j \\pm t_{n-k, 0.025} \\times se(b_j)$\n- If the CI excludes zero, the coefficient is statistically significant at 5%\n- Narrower CIs indicate more precise estimation\n\n**Individual Hypothesis Tests:**\n\n- Test $H_0: \\beta_j = \\beta_j^*$ using $t = (b_j - \\beta_j^*) / se(b_j)$\n- Most common: test of significance $H_0: \\beta_j = 0$ — does variable $x_j$ matter after controlling for others?\n- Reject $H_0$ if $|t| > t_{\\text{critical}}$ or equivalently if $p$-value $< \\alpha$\n\n**Joint F-Tests:**\n\n- F-test evaluates multiple restrictions simultaneously: $F = \\frac{(RSS_r - RSS_u)/q}{RSS_u/(n-k)} \\sim F(q, n-k)$\n- Overall significance test: $H_0: \\beta_2 = \\cdots = \\beta_k = 0$ (all slopes zero)\n- Subset tests: compare restricted vs. unrestricted models to decide if additional regressors are needed\n- Equivalently: $F = \\frac{(R_u^2 - R_r^2)/q}{(1 - R_u^2)/(n-k)}$\n\n**Model Comparison and Selection:**\n\n- Use F-tests to formally compare nested models\n- Consider adjusted $R^2$, AIC, BIC alongside F-tests\n- Prefer parsimony: if additional variables don't significantly improve fit, use the simpler model\n- In our house price example, size alone was sufficient — five additional variables failed the joint F-test ($p = 0.83$)\n\n**Presenting Results and Robust Inference:**\n\n- Five standard formats: coefficients with (SEs), (t-stats), (p-values), (CIs), or (asterisks)\n- Heteroskedasticity-robust (HC1) standard errors provide valid inference without assuming constant variance\n- Report robust SEs by default for cross-sectional data\n\n**Python Libraries and Code:**\n\nThis single code block reproduces the core workflow of Chapter 11. It is self-contained — copy it into an empty notebook and run it to review the complete pipeline from multiple regression estimation to confidence intervals, hypothesis tests, F-tests, and robust inference.\n\n```python\n# =============================================================================\n# CHAPTER 11 CHEAT SHEET: Statistical Inference for Multiple Regression\n# =============================================================================\n\n# --- Libraries ---\nimport numpy as np                              # numerical operations\nimport pandas as pd                             # data loading and manipulation\nimport matplotlib.pyplot as plt                 # creating plots and visualizations\nimport pyfixest as pf                           # fast estimation with robust SEs\nfrom scipy import stats                         # t and F distributions for inference\n# anova_lm replaced by manual F-test with pyfixest\n\n# =============================================================================\n# STEP 1: Load data directly from a URL\n# =============================================================================\n# pd.read_stata() reads Stata .dta files; the dataset has 29 houses from Davis, CA\nurl = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/AED_HOUSE.DTA\"\ndata_house = pd.read_stata(url)\n\nprint(f\"Dataset: {data_house.shape[0]} observations, {data_house.shape[1]} variables\")\nprint(data_house[['price', 'size', 'bedrooms', 'bathrooms', 'lotsize', 'age']].describe().round(2))\n\n# =============================================================================\n# STEP 2: Estimate the full multiple regression model\n# =============================================================================\n# Formula syntax: 'y ~ x1 + x2 + ...' includes an intercept automatically\n# IMPORTANT: .fit() estimates the model — without it, nothing is computed!\nmodel_full = pf.feols('price ~ size + bedrooms + bathrooms + lotsize + age + monthsold', data=data_house)\n\nn = int(model_full._N)\nk = len(model_full.coef())\ndf = n - k  # degrees of freedom for t and F tests\n\nprint(f\"\\nSize effect: ${model_full.coef()['size']:,.2f} per sq ft (p = {model_full.pvalue()['size']:.4f})\")\nprint(f\"R-squared: {model_full._r2:.4f} ({model_full._r2*100:.1f}% of variation explained)\")\nprint(f\"Degrees of freedom: n-k = {n}-{k} = {df}\")\n\n# Full regression table (coefficients, std errors, t-stats, p-values, R²)\nmodel_full.summary()\n\n# =============================================================================\n# STEP 3: Confidence intervals — does the CI exclude zero?\n# =============================================================================\n# 95% CI: b_j ± t_critical × se(b_j)\n# If the interval excludes zero, the coefficient is statistically significant at 5%\nconf_int = model_full.confint()\nprint(\"\\n95% Confidence Intervals:\")\nprint(conf_int.round(2))\n\n# Manual calculation for the size coefficient\ncoef_size = model_full.coef()['size']\nse_size   = model_full.se()['size']\nt_crit    = stats.t.ppf(0.975, df)  # 0.975 = upper tail for two-sided 95% CI\n\nci_lower = coef_size - t_crit * se_size\nci_upper = coef_size + t_crit * se_size\nprint(f\"\\nSize 95% CI: [${ci_lower:.2f}, ${ci_upper:.2f}]  (excludes zero → significant)\")\n\n# =============================================================================\n# STEP 4: Hypothesis test on a single coefficient\n# =============================================================================\n# Test H₀: β_size = 50 vs H₁: β_size ≠ 50\n# t = (b_j - hypothesized value) / se(b_j)\nnull_value = 50\nt_stat = (coef_size - null_value) / se_size\np_value = 2 * (1 - stats.t.cdf(abs(t_stat), df))\n\nprint(f\"\\nTest H₀: β_size = {null_value}\")\nprint(f\"  t-statistic: {t_stat:.4f}\")\nprint(f\"  p-value: {p_value:.4f}\")\nprint(f\"  Decision: {'Reject' if p_value < 0.05 else 'Fail to reject'} H₀ at 5% level\")\n\n# Test of statistical significance: H₀: β_size = 0\nt_stat_zero = coef_size / se_size\nprint(f\"\\nTest H₀: β_size = 0\")\nprint(f\"  t-statistic: {t_stat_zero:.4f}, p-value: {model_full.pvalue()['size']:.6f}\")\nprint(f\"  Size IS statistically significant at 5% level\")\n\n# =============================================================================\n# STEP 5: Joint F-test — are groups of coefficients jointly significant?\n# =============================================================================\n# Overall F-test: H₀: all slope coefficients = 0\nf_p = 1 - stats.f.cdf(model_full._f_statistic, len(model_full.coef())-1, int(model_full._N)-len(model_full.coef()))\nprint(f\"\\nOverall F-test: F = {model_full._f_statistic:.4f}, p = {f_p:.6e}\")\nprint(f\"  At least one variable matters → model is jointly significant\")\n\n# Subset F-test: are variables other than size jointly significant?\n# H₀: β_bedrooms = β_bathrooms = β_lotsize = β_age = β_monthsold = 0\nmodel_restricted = pf.feols('price ~ size', data=data_house)\nrss_r = np.sum(model_restricted._u_hat**2)\nrss_u = np.sum(model_full._u_hat**2)\nq = len(model_full.coef()) - len(model_restricted.coef())\nn_k = int(model_full._N) - len(model_full.coef())\nF_sub = ((rss_r - rss_u) / q) / (rss_u / n_k)\np_sub = 1 - stats.f.cdf(F_sub, q, n_k)\nprint(f\"\\nSubset F-test (drop 5 vars, keep size):\")\nprint(f\"  F = {F_sub:.4f}, p = {p_sub:.4f}\")\nprint(f\"  Extra variables are NOT jointly significant → simpler model preferred\")\n\n# =============================================================================\n# STEP 6: Model comparison — restricted vs unrestricted\n# =============================================================================\n# Compare fit statistics\nprint(f\"\\n{'Model':<25} {'R²':>8} {'Adj. R²':>9}\")\nprint(\"-\" * 44)\nfor name, m in [('Size only', model_restricted), ('Full model', model_full)]:\n    print(f\"{name:<25} {m._r2:>8.4f} {m._adj_r2:>9.4f}\")\n\n# =============================================================================\n# STEP 7: Robust standard errors — valid under heteroskedasticity\n# =============================================================================\n# HC1 (White's correction) provides valid inference without constant variance\nmodel_robust = pf.feols('price ~ size + bedrooms + bathrooms + lotsize + age + monthsold',\n                        data=data_house, vcov='HC1')\n\nprint(\"\\nStandard vs Robust SEs:\")\nprint(f\"{'Variable':<14} {'Coef':>10} {'Std SE':>10} {'Robust SE':>10} {'p (robust)':>10}\")\nprint(\"-\" * 56)\nfor var in model_full.coef().index:\n    print(f\"{var:<14} {model_full.coef()[var]:>10.2f} \"\n          f\"{model_full.se()[var]:>10.2f} {model_robust.se()[var]:>10.2f} \"\n          f\"{model_robust.pvalue()[var]:>10.4f}\")\n\n# =============================================================================\n# STEP 8: Coefficient plot — visual summary of significance\n# =============================================================================\n# Error bars crossing zero = not significant at 5%\nparams_plot = model_full.coef()[1:]  # exclude intercept\nci_plot = conf_int.iloc[1:, :]\n\nfig, ax = plt.subplots(figsize=(10, 6))\ny_pos = np.arange(len(params_plot))\nax.errorbar(params_plot.values, y_pos,\n            xerr=[params_plot.values - ci_plot.iloc[:, 0].values,\n                  ci_plot.iloc[:, 1].values - params_plot.values],\n            fmt='o', markersize=8, capsize=5, capthick=2, linewidth=2)\nax.axvline(x=0, color='red', linestyle='--', linewidth=1.5, alpha=0.7, label='H₀: β = 0')\nax.set_yticks(y_pos)\nax.set_yticklabels(params_plot.index)\nax.set_xlabel('Coefficient Value')\nax.set_title('Coefficient Estimates with 95% Confidence Intervals')\nax.legend()\nax.grid(True, alpha=0.3, axis='x')\nplt.tight_layout()\nplt.show()\n```\n\n**Try it yourself!** Copy this code into an empty Google Colab notebook and run it: [Open Colab](https://colab.research.google.com/notebooks/empty.ipynb)\n\n**Next steps:** Chapter 12 covers **further inference and model specification** — additional diagnostic tests and extensions to the multiple regression framework.\n\nCongratulations on completing Chapter 11! You can now conduct rigorous statistical inference for multiple regression models.\n\n> **Common Mistakes to Avoid**\n>\n> - **Testing individual coefficients when joint significance matters**: Use F-tests for groups of variables\n> - **Comparing R-squared across models with different numbers of variables**: Use adjusted R-squared instead\n> - **Ignoring the difference between economic and statistical significance**\n\n## Practice Exercises\n\nTest your understanding of statistical inference for multiple regression.\n\n---\n\n**Exercise 1: Confidence Interval Calculation**\n\nA multiple regression with $n = 200$ observations and $k = 4$ parameters yields:\n\n- $b_2 = 5.0$, $se(b_2) = 2.0$\n- $b_3 = 7.0$, $se(b_3) = 2.0$\n\na) Compute an approximate 95% confidence interval for $\\beta_2$.\n\nb) Compute an approximate 95% confidence interval for $\\beta_3$.\n\nc) Which coefficient is estimated more precisely? Explain.\n\n---\n\n**Exercise 2: Test of Statistical Significance**\n\nUsing the regression from Exercise 1:\n\na) Is $x_2$ statistically significant at the 5% level? Compute the $t$-statistic and state your conclusion.\n\nb) Is $x_3$ statistically significant at the 5% level?\n\nc) What is the approximate $p$-value for each coefficient?\n\n---\n\n**Exercise 3: Testing a Specific Value**\n\nUsing the same regression, test the claim that $\\beta_3 = 10.0$ at significance level 0.05.\n\na) State the null and alternative hypotheses.\n\nb) Compute the $t$-statistic.\n\nc) What is your decision? Can you reject $H_0$?\n\n---\n\n**Exercise 4: Joint F-Test Setup**\n\nConsider the model $y = \\beta_1 + \\beta_2 x_2 + \\beta_3 x_3 + \\beta_4 x_4 + \\beta_5 x_5 + \\beta_6 x_6 + u$.\n\nWe wish to test whether only $x_2$ and $x_3$ should be included in the model.\n\na) State $H_0$ and $H_a$ for this test.\n\nb) How many restrictions are being tested ($q$)?\n\nc) What are the degrees of freedom for the F-test if $n = 100$?\n\n---\n\n**Exercise 5: F-Statistic Computation**\n\nYou estimate two models on $n = 53$ observations:\n\n- Restricted model ($k_r = 3$): $RSS_r = 40$\n- Unrestricted model ($k_u = 6$): $RSS_u = 30$\n\na) Compute the F-statistic.\n\nb) What are the degrees of freedom?\n\nc) At $\\alpha = 0.05$, would you reject the restrictions?\n\n---\n\n**Exercise 6: Regression Presentation**\n\nGiven these regression results:\n\n| Variable | Coefficient | Std. Error | p-value |\n|----------|------------|------------|--------|\n| Intercept | 3.0 | 1.5 | 0.047 |\n| $x_2$ | 5.0 | 2.0 | 0.013 |\n| $x_3$ | 7.0 | 2.0 | 0.001 |\n\na) Present these results using the asterisk notation (`***` for $p < 0.01$, `**` for $p < 0.05$, `*` for $p < 0.10$).\n\nb) Present using the coefficient (standard error) format.\n\nc) Which variables are significant at the 1% level? At the 5% level?\n\n## Case Studies\n\n### Case Study 1: Statistical Inference for Cross-Country Productivity\n\nIn this case study, you will apply confidence intervals, hypothesis tests, and F-tests to investigate whether physical capital and human capital are statistically significant determinants of cross-country labor productivity differences.\n\n**Dataset:** Mendez Convergence Clubs Data\n\n- **Source:** Mendez (2020), 108 countries, 1990-2014\n- **Key variables:**\n  - `lp` — Labor productivity (GDP per worker)\n  - `rk` — Physical capital per worker\n  - `hc` — Human capital index\n  - `region` — Geographic region\n\n**Research question:** Are physical capital and human capital jointly significant in explaining cross-country labor productivity?\n\n```python\n# Load the Mendez convergence clubs dataset\nurl = \"https://raw.githubusercontent.com/quarcs-lab/mendez2020-convergence-clubs-code-data/master/assets/dat.csv\"\ndat = pd.read_csv(url)\ndat_2014 = dat[dat['year'] == 2014].dropna(subset=['lp', 'rk', 'hc']).copy()\ndat_2014['ln_lp'] = np.log(dat_2014['lp'])\ndat_2014['ln_rk'] = np.log(dat_2014['rk'])\nprint(f\"Cross-section sample: {len(dat_2014)} countries (year 2014)\")\ndat_2014.head()\n```\n\n#### Task 1: Estimate Productivity Model (Guided)\n\nEstimate the multiple regression model for labor productivity.\n\n```python\n# Estimate: ln(lp) = beta_0 + beta_1 * ln(rk) + beta_2 * hc + u\nmodel_prod = pf.feols('ln_lp ~ ln_rk + hc', data=dat_2014)\nmodel_prod.summary()\n```\n\n**Questions:**\n\n- How many observations and parameters does the model have?\n- What is the $R^2$? How much of productivity variation do capital and human capital explain?\n\n#### Task 2: Confidence Intervals (Guided)\n\nCompute and interpret 95% confidence intervals for the coefficients.\n\n```python\n# 95% confidence intervals\nprint(\"95% Confidence Intervals:\")\nprint(model_prod.confint())\n\n# Manual calculation for ln_rk coefficient\nb_rk = model_prod.coef()['ln_rk']\nse_rk = model_prod.se()['ln_rk']\ndf = (int(model_prod._N) - len(model_prod.coef()))\nt_crit = stats.t.ppf(0.975, df)\nprint(f\"\\nManual CI for ln(rk): [{b_rk - t_crit*se_rk:.4f}, {b_rk + t_crit*se_rk:.4f}]\")\n```\n\n**Questions:**\n\n- Does the CI for $\\ln(\\text{rk})$ exclude zero? What does this tell you?\n- Does the CI for hc exclude zero? Interpret in economic terms.\n\n> **Key Concept 11.9: Statistical Significance in Cross-Country Regressions**\n>\n> With over 100 countries, cross-country regressions have sufficient power to detect moderate effects. However, statistical significance does not imply causation — unobserved factors (institutions, geography, culture) may confound the relationship between capital inputs and productivity. Confidence intervals quantify estimation uncertainty but not omitted variable bias.\n\n#### Task 3: Individual Hypothesis Tests (Semi-guided)\n\nTest the statistical significance of each coefficient.\n\n```python\n# Test significance of each coefficient\nprint(\"t-statistics and p-values:\")\nfor var in ['ln_rk', 'hc']:\n    t = model_prod.tstat()[var]\n    p = model_prod.pvalue()[var]\n    sig = '***' if p < 0.01 else '**' if p < 0.05 else '*' if p < 0.10 else ''\n    print(f\"  {var}: t = {t:.3f}, p = {p:.4f} {sig}\")\n```\n\n**Questions:**\n\n- Which coefficients are significant at the 1% level? At the 5% level?\n- Interpret the economic meaning: what does significance of $\\ln(\\text{rk})$ tell us about physical capital?\n\n#### Task 4: Joint F-Test (Semi-guided)\n\nTest whether physical capital and human capital are jointly significant.\n\n```python\n# Overall F-test: H0: beta_1 = beta_2 = 0\nprint(f\"Overall F-statistic: {model_prod._f_statistic:.4f}\")\nf_p_prod = 1 - stats.f.cdf(model_prod._f_statistic, len(model_prod.coef())-1, int(model_prod._N)-len(model_prod.coef()))\nprint(f\"p-value: {f_p_prod:.6e}\")\n\n# Compare to restricted model (intercept only) using manual F-test\nmodel_restricted = pf.feols('ln_lp ~ 1', data=dat_2014)\nrss_r = np.sum(model_restricted._u_hat**2)\nrss_u = np.sum(model_prod._u_hat**2)\nq = len(model_prod.coef()) - len(model_restricted.coef())\nn_k = int(model_prod._N) - len(model_prod.coef())\nF_val = ((rss_r - rss_u) / q) / (rss_u / n_k)\np_val = 1 - stats.f.cdf(F_val, q, n_k)\nprint(f\"\\nF-test: F({q}, {n_k}) = {F_val:.4f}, p = {p_val:.6e}\")\n```\n\n**Questions:**\n\n- Can you reject $H_0: \\beta_1 = \\beta_2 = 0$? What does this mean economically?\n- How does the F-test relate to the individual $t$-tests?\n\n#### Task 5: Model Comparison (Independent)\n\nCompare nested models to determine the best specification.\n\n**Your tasks:**\n\n1. Estimate three models: (a) $\\ln(\\text{lp}) \\sim \\ln(\\text{rk})$ only, (b) $\\ln(\\text{lp}) \\sim \\text{hc}$ only, (c) both regressors\n2. Create a model comparison table with $R^2$, adjusted $R^2$, AIC, BIC\n3. Conduct subset F-tests: does adding hc to the $\\ln(\\text{rk})$-only model significantly improve fit?\n4. Report robust standard errors for the preferred model\n\n*Hint: Use the manual F-test formula (RSS comparison) for nested model tests and `pf.feols(..., vcov='HC1')` for robust SEs.*\n\n#### Task 6: Inference Policy Brief (Independent)\n\nWrite a 200-300 word policy brief summarizing your inference results.\n\n**Your brief should address:**\n\n1. Which factors are statistically significant predictors of cross-country productivity?\n2. What are the 95% confidence intervals for the effects of capital and human capital?\n3. Are both factors jointly significant? What does the F-test tell us?\n4. What policy implications follow from these findings?\n5. What caveats should policymakers consider (association vs. causation, omitted variables)?\n\n> **Key Concept 11.10: From Statistical Significance to Policy Relevance**\n>\n> Finding that both physical and human capital are statistically significant predictors of productivity suggests that investments in both areas may boost economic output. However, the magnitudes matter for policy: confidence intervals tell us the plausible range of effects, while F-tests confirm that both factors jointly matter beyond what each contributes alone. Policy decisions should weigh statistical evidence alongside practical considerations like cost-effectiveness and implementation feasibility.\n\n### What You've Learned\n\nIn this case study, you applied the full statistical inference toolkit to cross-country productivity data:\n\n- Estimated multiple regression models and examined coefficient properties\n- Constructed and interpreted confidence intervals for partial effects\n- Conducted individual $t$-tests to assess each predictor's significance\n- Performed joint F-tests to evaluate whether both capital types matter\n- Compared nested models and reported results with robust standard errors\n\nThese inferential tools are essential for drawing reliable conclusions from empirical economic analysis.\n\n### Case Study 2: Which Satellite Features Matter? Joint Tests for Predictive Power\n\nIn Chapter 10, we estimated a multiple regression of municipal development on nighttime lights and satellite embeddings. Now we apply Chapter 11's inference tools—t-tests for individual coefficients and F-tests for joint significance—to determine which satellite features add statistically significant predictive power.\n\n**Dataset:** DS4Bolivia — Satellite Data for Sustainable Development\n\n- **Source:** [DS4Bolivia Project](https://github.com/quarcs-lab/ds4bolivia), 339 municipalities\n- **Key variables:**\n  - `imds` — Municipal Sustainable Development Index (0-100 composite)\n  - `ln_NTLpc2017` — Log nighttime lights per capita (2017)\n  - `A00`, `A10`, `A20`, `A30`, `A40` — Selected satellite image embedding dimensions\n\n**Research question:** Do satellite image embeddings add statistically significant predictive power for municipal development beyond nighttime lights alone?\n\n```python\n# Load the DS4Bolivia dataset\nurl_bol = \"https://raw.githubusercontent.com/quarcs-lab/ds4bolivia/master/ds4bolivia_v20250523.csv\"\nbol = pd.read_csv(url_bol)\n\n# Select variables and prepare analysis sample\nembed_vars = ['A00', 'A10', 'A20', 'A30', 'A40']\nanalysis_vars = ['imds', 'ln_NTLpc2017'] + embed_vars\nbol_cs = bol[['mun', 'dep'] + analysis_vars].dropna(subset=analysis_vars).copy()\nprint(f\"Analysis sample: {len(bol_cs)} municipalities with complete data\")\nbol_cs[analysis_vars].describe().round(3)\n```\n\n#### Task 1: Estimate Full Model (Guided)\n\nEstimate the full multiple regression model with nighttime lights and all five satellite embedding dimensions as predictors of municipal development.\n\n```python\n# Estimate: imds = beta_0 + beta_1*ln_NTLpc2017 + beta_2*A00 + ... + beta_6*A40 + u\nmodel_full = pf.feols('imds ~ ln_NTLpc2017 + A00 + A10 + A20 + A30 + A40', data=bol_cs)\nmodel_full.summary()\n```\n\n**Questions:**\n\n- How many coefficients are estimated (including the intercept)?\n- Which coefficients have p-values below 0.05? Below 0.10?\n- What is the overall $R^2$? How much variation in development does this model explain?\n- Compare this $R^2$ to a model with NTL alone—how much do the embeddings add?\n\n::: {#090c17dd .cell execution_count=24}\n``` {.python .cell-code}\n# Your code here: Estimate the full model\n#\n# Steps:\n# 1. Estimate the full model with NTL and all 5 embeddings\n# 2. Print the full summary\n# 3. Identify significant coefficients (p < 0.05 and p < 0.10)\n\n# Example structure:\n# model_full = pf.feols('imds ~ ln_NTLpc2017 + A00 + A10 + A20 + A30 + A40', data=bol_cs)\n# model_full.summary()\n#\n# # Identify significant predictors\n# print(\"\\nSignificance at 5% level:\")\n# for var in model_full.coef().index:\n#     p = model_full.pvalue()[var]\n#     sig = \"***\" if p < 0.01 else \"**\" if p < 0.05 else \"*\" if p < 0.10 else \"\"\n#     print(f\"  {var:18s}  p = {p:.4f}  {sig}\")\n```\n:::\n\n\n#### Task 2: Confidence Intervals (Guided)\n\nCompute 95% confidence intervals for all coefficients and create a coefficient plot (forest plot) to visualize the estimates and their uncertainty.\n\n```python\n# 95% confidence intervals\nci = model_full.confint()\nci.columns = ['Lower 2.5%', 'Upper 97.5%']\nci['Estimate'] = model_full.coef()\nprint(ci[['Estimate', 'Lower 2.5%', 'Upper 97.5%']].round(4))\n```\n\n**Questions:**\n\n- Which confidence intervals include zero? What does this imply about significance?\n- Which coefficient has the widest confidence interval? The narrowest (excluding intercept)?\n- Create a forest plot showing point estimates and 95% CIs for the embedding coefficients\n- How do the confidence intervals for embeddings compare in width to the NTL coefficient?\n\n::: {#848e57e7 .cell execution_count=25}\n``` {.python .cell-code}\n# Your code here: Confidence intervals and coefficient plot\n#\n# Steps:\n# 1. Compute confidence intervals with model_full.confint()\n# 2. Print the table of estimates and CIs\n# 3. Create a coefficient plot (forest plot) for embedding variables\n# 4. Identify which CIs include zero\n\n# Example structure:\n# ci = model_full.confint()\n# ci.columns = ['Lower', 'Upper']\n# ci['Estimate'] = model_full.coef()\n# print(ci[['Estimate', 'Lower', 'Upper']].round(4))\n#\n# # Forest plot for embedding coefficients\n# embed_vars = ['A00', 'A10', 'A20', 'A30', 'A40']\n# fig, ax = plt.subplots(figsize=(8, 5))\n# y_pos = range(len(embed_vars))\n# estimates = [model_full.coef()[v] for v in embed_vars]\n# errors = [(model_full.coef()[v] - ci.loc[v, 'Lower'],\n#            ci.loc[v, 'Upper'] - model_full.coef()[v]) for v in embed_vars]\n# errors_T = list(zip(*errors))\n# ax.errorbar(estimates, y_pos, xerr=errors_T, fmt='o', color='navy',\n#             capsize=5, markersize=8)\n# ax.axvline(x=0, color='red', linestyle='--', alpha=0.7, label='Zero (no effect)')\n# ax.set_yticks(y_pos)\n# ax.set_yticklabels(embed_vars)\n# ax.set_xlabel('Coefficient Estimate with 95% CI')\n# ax.set_title('Coefficient Plot: Satellite Embedding Effects on IMDS')\n# ax.legend()\n# plt.tight_layout()\n# plt.show()\n```\n:::\n\n\n#### Task 3: Individual t-Tests (Semi-guided)\n\nExamine the t-statistics and p-values for each satellite embedding coefficient individually.\n\n**Your tasks:**\n\n1. Extract and display the t-statistic and p-value for each embedding variable (`A00`-`A40`)\n2. Classify each as significant at 5%, significant at 10%, or not significant\n3. Count how many of the 5 embeddings are individually significant at each level\n4. Discuss: If some embeddings are individually insignificant, can we conclude they are \"useless\"? Why or why not?\n\n**Hint:** Individual insignificance may reflect multicollinearity among embeddings rather than lack of predictive power. The joint F-test in Task 4 will help resolve this.\n\n::: {#76bc39b7 .cell execution_count=26}\n``` {.python .cell-code}\n# Your code here: Individual t-tests for embedding coefficients\n#\n# Steps:\n# 1. Extract t-statistics and p-values for each embedding\n# 2. Classify significance levels\n# 3. Discuss the implications\n\n# Example structure:\n# print(\"Individual t-Tests for Satellite Embeddings\")\n#\n# embed_vars = ['A00', 'A10', 'A20', 'A30', 'A40']\n# sig_5 = 0\n# sig_10 = 0\n# for var in embed_vars:\n#     t = model_full.tstat()[var]\n#     p = model_full.pvalue()[var]\n#     if p < 0.05:\n#         level = \"Significant at 5%  ***\"\n#         sig_5 += 1\n#         sig_10 += 1\n#     elif p < 0.10:\n#         level = \"Significant at 10% *\"\n#         sig_10 += 1\n#     else:\n#         level = \"Not significant\"\n#     print(f\"  {var}: t = {t:7.3f}, p = {p:.4f}  --> {level}\")\n# print(f\"\\nSignificant at 5%:  {sig_5}/5 embeddings\")\n# print(f\"Significant at 10%: {sig_10}/5 embeddings\")\n```\n:::\n\n\n#### Task 4: Joint F-Test (Semi-guided)\n\nTest whether all five satellite embedding coefficients are jointly equal to zero.\n\n$$H_0: \\beta_{A00} = \\beta_{A10} = \\beta_{A20} = \\beta_{A30} = \\beta_{A40} = 0$$\n\n**Your tasks:**\n\n1. Construct a restriction matrix $R$ where each row sets one embedding coefficient to zero\n2. Compute the manual F-test using RSS comparison between restricted and unrestricted models\n3. Report the F-statistic, degrees of freedom, and p-value\n4. Compare the joint test result with the individual t-test results from Task 3\n5. Are embeddings *jointly* significant even if some are individually insignificant?\n\n**Hint:** The restriction matrix has 5 rows (one per restriction) and 7 columns (one per coefficient including intercept). Each row has a 1 in the position of the embedding coefficient being tested and 0s elsewhere.\n\n::: {#091abf91 .cell execution_count=27}\n``` {.python .cell-code}\n# Your code here: Joint F-test for all embedding coefficients\n#\n# Steps:\n# 1. Construct the restriction matrix R\n# 2. Compute manual F-test using RSS comparison\n# 3. Report F-statistic and p-value\n# 4. Compare with individual t-test results\n\n# Example structure:\n# import numpy as np\n#\n# # Restriction matrix: 5 restrictions (A00=A10=A20=A30=A40=0)\n# # Coefficients order: Intercept, ln_NTLpc2017, A00, A10, A20, A30, A40\n# R = np.zeros((5, 7))\n# R[0, 2] = 1  # A00 = 0\n# R[1, 3] = 1  # A10 = 0\n# R[2, 4] = 1  # A20 = 0\n# R[3, 5] = 1  # A30 = 0\n# R[4, 6] = 1  # A40 = 0\n#\n# F = ((rss_r - rss_u) / q) / (rss_u / n_k)\n# print(\"Joint F-Test: All Embedding Coefficients = 0\")\n#\n# print(f\"F-statistic: {f_test._f_statistic[0][0]:.4f}\")\n# print(f\"p-value:     {f_test.pvalue:.6f}\")\n# print(f\"df:          ({int(f_test.df_num)}, {int(f_test.df_denom)})\")\n# print(f\"\\nConclusion: {'Reject H0' if f_test.pvalue < 0.05 else 'Fail to reject H0'} at 5% level\")\n```\n:::\n\n\n> **Key Concept 11.12: Joint Significance of Satellite Features**\n>\n> Individual satellite embedding coefficients may appear **statistically insignificant** (p > 0.05) in a multiple regression, yet the group of embeddings may be **jointly significant** (F-test p < 0.05). This paradox arises when embeddings are correlated with each other: the individual t-tests cannot distinguish each embedding's unique contribution, but the F-test captures their collective explanatory power. Joint F-tests are essential when evaluating groups of related predictors.\n\n#### Task 5: Restricted vs Unrestricted Model Comparison (Independent)\n\nCompare the restricted model (NTL only) with the unrestricted model (NTL + embeddings) to quantify the contribution of satellite embeddings.\n\n**Your tasks:**\n\n1. Estimate Model 1 (restricted): `imds ~ ln_NTLpc2017` (NTL only)\n2. Estimate Model 2 (unrestricted): `imds ~ ln_NTLpc2017 + A00 + A10 + A20 + A30 + A40`\n3. Compute the F-statistic manually using the formula:\n\n$$F = \\frac{(R^2_u - R^2_r) / q}{(1 - R^2_u) / (n - k - 1)}$$\n\nwhere $q = 5$ (number of restrictions), $n$ = sample size, $k$ = number of regressors in unrestricted model\n\n4. Compare your manual calculation with `model_full.compare_f_test(model_restricted)`\n5. Interpret: How much do the embeddings improve the model's explanatory power?\n\n::: {#39283f5d .cell execution_count=28}\n``` {.python .cell-code}\n# Your code here: Restricted vs unrestricted model comparison\n#\n# Steps:\n# 1. Estimate restricted model (NTL only)\n# 2. Compare R-squared values\n# 3. Compute F-statistic manually\n# 4. Verify with compare_f_test()\n\n# Example structure:\n# # Restricted model: NTL only\n# model_restricted = pf.feols('imds ~ ln_NTLpc2017', data=bol_cs)\n#\n# # Compare R-squared\n# R2_r = model_restricted._r2\n# R2_u = model_full._r2\n# n = model_full._N\n# k = len(model_full.coef()) - 1  # number of regressors (excluding intercept)\n# q = 5  # number of restrictions (embedding coefficients)\n#\n# print(\"Model Comparison\")\n#\n# print(f\"Restricted (NTL only):      R² = {R2_r:.4f}\")\n# print(f\"Unrestricted (NTL + embed): R² = {R2_u:.4f}\")\n# print(f\"Improvement in R²:          ΔR² = {R2_u - R2_r:.4f}\")\n#\n# # Manual F-statistic\n# F_manual = ((R2_u - R2_r) / q) / ((1 - R2_u) / (n - k - 1))\n# print(f\"\\nManual F-statistic: {F_manual:.4f}\")\n#\n# # Verify with statsmodels\n# f_compare = model_full.compare_f_test(model_restricted)\n# print(f\"compare_f_test:     F = {f_compare[0]:.4f}, p = {f_compare[1]:.6f}\")\n```\n:::\n\n\n#### Task 6: Inference Brief (Independent)\n\nWrite a 200-300 word inference brief summarizing your statistical findings.\n\n**Your brief should address:**\n\n1. Which satellite features add significant predictive power for municipal development?\n2. Does the joint F-test tell a different story than the individual t-tests? Why?\n3. How much do satellite embeddings improve explanatory power beyond nighttime lights alone?\n4. What are the implications for feature selection in satellite-based prediction models?\n5. How should researchers decide which satellite features to include in SDG prediction models?\n\n**Connection to methods:** This analysis demonstrates a core tension in applied econometrics: individual insignificance vs. joint significance. When predictors are correlated (as satellite embeddings often are), individual t-tests may lack power while joint F-tests reveal collective importance.\n\n::: {#605a258a .cell execution_count=29}\n``` {.python .cell-code}\n# Your code here: Additional analysis for the inference brief\n#\n# You might want to:\n# 1. Create a summary table comparing individual and joint test results\n# 2. Visualize the R-squared improvement from adding embeddings\n# 3. Calculate specific statistics to cite in your brief\n\n# Example: Summary of key inference results\n# print(\"KEY INFERENCE RESULTS\")\n#\n# print(f\"Sample size: {int(model_full._N)} municipalities\")\n# print(f\"R² (NTL only):          {model_restricted._r2:.4f}\")\n# print(f\"R² (NTL + embeddings):  {model_full._r2:.4f}\")\n# print(f\"R² improvement:         {model_full._r2 - model_restricted._r2:.4f}\")\n# print(f\"\\nJoint F-test p-value:   {f_test.pvalue:.6f}\")\n# print(f\"Individually significant at 5%: {sig_5}/5 embeddings\")\n# print(f\"Individually significant at 10%: {sig_10}/5 embeddings\")\n```\n:::\n\n\n> **Key Concept 11.13: Feature Selection in Prediction Models**\n>\n> When many potential predictors are available (e.g., 64 satellite embedding dimensions), selecting which to include requires balancing **explanatory power** against **model parsimony**. Joint F-tests help determine whether *subsets* of features add genuine predictive value beyond what simpler models provide. In the DS4Bolivia context, testing whether 5 selected embeddings improve upon NTL alone informs practical decisions about data collection and model complexity for SDG monitoring.\n\n#### What You've Learned from This Case Study\n\nThrough this analysis of satellite features and municipal development in Bolivia, you applied Chapter 11's full inference toolkit to a remote sensing application:\n\n- **Full model estimation**: Estimated a multiple regression with nighttime lights and satellite embeddings as predictors of development\n- **Confidence intervals**: Constructed and visualized 95% CIs for all coefficients using a forest plot\n- **Individual t-tests**: Assessed the statistical significance of each satellite embedding individually\n- **Joint F-tests**: Tested whether all embeddings are jointly significant using restriction matrices\n- **Restricted vs unrestricted comparison**: Computed F-statistics manually and verified with `compare_f_test()`\n- **Inference interpretation**: Distinguished between individual insignificance and joint significance\n\n**Connection to the next chapter**: In Chapter 12, we address robust standard errors and prediction intervals—crucial for making reliable predictions about individual municipalities.\n\n---\n\n**Well done!** You've now applied the full statistical inference toolkit to two datasets—cross-country productivity and Bolivian satellite data—discovering that joint tests can reveal predictive power hidden from individual tests.\n\n",
    "supporting": [
      "ch11_Statistical_Inference_for_Multiple_Regression_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}