/* Canonical chapter titles — registered into window.I18N by i18n-runtime.js.
 * Sourced from each web-apps/chNN/template.html `header.title` value (unicode escapes decoded).
 * Will be referenced by: web-apps/chNN/dashboard.html (after Phase 4 migration), and by
 * index.html's "Web Apps" dropdown (which currently uses webapps.chNN keys; Phase 3 may
 * collapse those references onto these canonical keys).
 * 17 keys total.
 */
window.I18N_REGISTER({
  "chapter.ch01.title": { en: "Analysis of Economics Data",
                          es: "Análisis de datos económicos",
                          ja: "経済データの分析" },
  "chapter.ch02.title": { en: "Univariate Data Summary",
                          es: "Resumen de datos univariados",
                          ja: "一変量データの要約" },
  "chapter.ch03.title": { en: "The Sample Mean",
                          es: "La media muestral",
                          ja: "標本平均" },
  "chapter.ch04.title": { en: "Statistical Inference for the Mean",
                          es: "Inferencia estadística para la media",
                          ja: "平均に関する統計的推測" },
  "chapter.ch05.title": { en: "Bivariate Data Summary",
                          es: "Resumen de datos bivariados",
                          ja: "二変量データの要約" },
  "chapter.ch06.title": { en: "The Least Squares Estimator",
                          es: "El estimador de mínimos cuadrados",
                          ja: "最小二乗推定量" },
  "chapter.ch07.title": { en: "Statistical Inference for Bivariate Regression",
                          es: "Inferencia estadística para regresión bivariada",
                          ja: "二変量回帰の統計的推測" },
  "chapter.ch08.title": { en: "Case Studies for Bivariate Regression",
                          es: "Estudios de caso para regresión bivariada",
                          ja: "二変量回帰のケーススタディ" },
  "chapter.ch09.title": { en: "Models with Natural Logarithms",
                          es: "Modelos con logaritmos naturales",
                          ja: "自然対数を用いたモデル" },
  "chapter.ch10.title": { en: "Data Summary for Multiple Regression",
                          es: "Resumen de datos para regresión múltiple",
                          ja: "重回帰のためのデータ要約" },
  "chapter.ch11.title": { en: "Statistical Inference for Multiple Regression",
                          es: "Inferencia estadística para regresión múltiple",
                          ja: "重回帰の統計的推測" },
  "chapter.ch12.title": { en: "Additional Topics in Multiple Regression",
                          es: "Temas adicionales en regresión múltiple",
                          ja: "重回帰の追加トピック" },
  "chapter.ch13.title": { en: "Case Studies for Multiple Regression",
                          es: "Estudios de caso para regresión múltiple",
                          ja: "重回帰のケーススタディ" },
  "chapter.ch14.title": { en: "Regression with Indicator Variables",
                          es: "Regresión con variables indicadoras",
                          ja: "ダミー変数を用いた回帰" },
  "chapter.ch15.title": { en: "Regression with Transformed Variables",
                          es: "Regresión con variables transformadas",
                          ja: "変数変換を用いた回帰" },
  "chapter.ch16.title": { en: "Model and Data Verification",
                          es: "Verificación del modelo y los datos",
                          ja: "モデルとデータの検証" },
  "chapter.ch17.title": { en: "Panel Data, Time Series, and Causality",
                          es: "Datos de panel, series de tiempo y causalidad",
                          ja: "パネルデータ、時系列、因果性" }
});
