/* Page-specific strings for index.html — registered into window.I18N by i18n-runtime.js.
 * Shared keys (nav.*, common.*, code.*, chapter.*) live in their own _shared/strings/*.js files.
 * The 17 webapps.chNN keys were collapsed into chapter.chNN.title (values match verbatim).
 */
window.I18N_REGISTER({
  "about.f1.body": { en: "Review statistical principles and econometric examples from <a href=\"https://cameron.econ.ucdavis.edu/aed/index.html\" target=\"_blank\" class=\"text-[#008CB7] hover:underline\">Cameron's (2022) textbook</a>.", es: "Repasa los principios estadísticos y los ejemplos de econometría del <a href=\"https://cameron.econ.ucdavis.edu/aed/index.html\" target=\"_blank\" class=\"text-[#008CB7] hover:underline\">libro de texto de Cameron (2022)</a>." },
  "about.f1.title": { en: "Foundational Concepts", es: "Conceptos fundamentales" },
  "about.f2.body": { en: "Run Python code directly in the cloud using Google Colab and its powerful AI features. Regressions use the new <a href=\"https://pyfixest.org/\" target=\"_blank\" class=\"text-[#008CB7] hover:underline\">pyfixest package</a> for estimation, inference, and reporting.", es: "Ejecuta código Python directamente en la nube con Google Colab y sus potentes funciones de IA. Las regresiones usan el nuevo paquete <a href=\"https://pyfixest.org/\" target=\"_blank\" class=\"text-[#008CB7] hover:underline\">pyfixest</a> para estimación, inferencia y reporte." },
  "about.f2.title": { en: "Computational Notebooks", es: "Cuadernos computacionales" },
  "about.f3.body": { en: "Explore key concepts with interactive web apps — sliders, toggles, and real-time charts for every chapter. No coding required.", es: "Explora los conceptos clave con aplicaciones web interactivas — controles deslizantes, selectores y gráficos en tiempo real para cada capítulo. No requiere programar." },
  "about.f3.title": { en: "Learning Apps", es: "Aplicaciones de aprendizaje" },
  "about.f4.body": { en: "Leverage Google's NotebookLM and other AI tools for interactive study, code explanations, and deep dives into complex concepts.", es: "Aprovecha Google NotebookLM y otras herramientas de IA para estudio interactivo, explicaciones de código y profundizar en conceptos complejos." },
  "about.f4.title": { en: "AI-Powered Learning", es: "Aprendizaje con IA" },
  "about.heading": { en: "Why metricsAI?", es: "¿Por qué metricsAI?" },
  "about.lede": { en: "Learning econometrics should be a more accessible and interactive experience.", es: "Aprender econometría debería ser una experiencia más accesible e interactiva." },
  "about.podcast.body": { en: "Let's review econometrics concepts through friendly podcast conversations.", es: "Repasemos los conceptos de econometría a través de conversaciones cercanas en formato podcast." },
  "about.podcast.title": { en: "Listen to the <a href=\"https://open.spotify.com/show/2lN5pA3l10UdHe61ZCoHcF?si=IFFMpG3pROepG61o8qbnvg\" target=\"_blank\" class=\"text-brand-600 hover:text-brand-700 dark:text-brand-400 dark:hover:text-brand-300 underline\">metricsAI podcast</a> to learn more.", es: "Escucha el <a href=\"https://open.spotify.com/show/2lN5pA3l10UdHe61ZCoHcF?si=IFFMpG3pROepG61o8qbnvg\" target=\"_blank\" class=\"text-brand-600 hover:text-brand-700 dark:text-brand-400 dark:hover:text-brand-300 underline\">podcast de metricsAI</a> para conocer más." },
  "authors.heading": { en: "Authors & Credits", es: "Autores y créditos" },
  "books.b1.subtitle": { en: "An Introduction Using Cloud-based Python Notebooks", es: "Una introducción con cuadernos Python en la nube" },
  "books.b2.subtitle": { en: "An Introduction to Econometrics", es: "Una introducción a la econometría" },
  "books.byline": { en: "by", es: "por" },
  "books.heading": { en: "Books", es: "Libros" },
  "books.learnMore": { en: "Learn More", es: "Saber más" },
  "books.lede": { en: "The learning materials of metricsAI are based on the contents of these books.", es: "Los materiales de aprendizaje de metricsAI se basan en el contenido de estos libros." },
  "curriculum.heading": { en: "Interactive AI-Powered Notebooks", es: "Cuadernos interactivos potenciados por IA" },
  "curriculum.lede": { en: "<a href=\"https://colab.research.google.com/notebooks/empty.ipynb\" target=\"_blank\" class=\"text-brand-600 hover:text-brand-700 dark:text-brand-400 dark:hover:text-brand-300 transition-colors\">Google Colab notebooks</a> provide an interactive programming environment where AI tools generate code, explain errors, and provide conversational guidance to accelerate learning.", es: "Los <a href=\"https://colab.research.google.com/notebooks/empty.ipynb\" target=\"_blank\" class=\"text-brand-600 hover:text-brand-700 dark:text-brand-400 dark:hover:text-brand-300 transition-colors\">cuadernos de Google Colab</a> ofrecen un entorno de programación interactivo donde las herramientas de IA generan código, explican errores y aportan guía conversacional para acelerar el aprendizaje." },
  "curriculum.part1": { en: "Part I: Statistical Foundations", es: "Parte I: Fundamentos estadísticos" },
  "curriculum.part2": { en: "Part II: Bivariate Regression", es: "Parte II: Regresión bivariada" },
  "curriculum.part3": { en: "Part III: Multiple Regression", es: "Parte III: Regresión múltiple" },
  "curriculum.part4": { en: "Part IV: Advanced Topics", es: "Parte IV: Temas avanzados" },
  "index.document.title": { en: "metricsAI: Econometrics with Python & AI", es: "metricsAI: Econometría con Python e IA" },
  "footer.ack.body": { en: "AI tools were used to make high-quality educational materials more accessible and to reduce barriers for students worldwide.\n                        All AI-generated content was reviewed, edited, and approved by Carlos Mendez. This author takes full responsibility for the accuracy and quality of all content in this project, including materials produced with the assistance of AI tools.", es: "Se utilizaron herramientas de IA para hacer más accesibles los materiales educativos de alta calidad y reducir las barreras para estudiantes en todo el mundo. Todo el contenido generado con IA fue revisado, editado y aprobado por Carlos Mendez. El autor asume la responsabilidad total de la exactitud y la calidad del contenido del proyecto, incluidos los materiales producidos con asistencia de IA." },
  "footer.ack.heading": { en: "Acknowledgments", es: "Agradecimientos" },
  "footer.aiTools.heading": { en: "AI tools", es: "Herramientas de IA" },
  "footer.copyright": { en: "&copy; 2026 metricsAI Project.", es: "© 2026 Proyecto metricsAI." },
  "footer.datasets.body": { en: "Originally created (and shared with permission) by\n                                <a href=\"https://cameron.econ.ucdavis.edu/aed/index.html\" target=\"_blank\" class=\"text-brand-400 hover:text-brand-300 underline\">A. Colin Cameron</a>.", es: "Creados originalmente (y compartidos con permiso) por <a href=\"https://cameron.econ.ucdavis.edu/aed/index.html\" target=\"_blank\" class=\"text-brand-400 hover:text-brand-300 underline\">A. Colin Cameron</a>." },
  "footer.datasets.heading": { en: "Datasets, Examples, and PDF Slides", es: "Conjuntos de datos, ejemplos y diapositivas en PDF" },
  "footer.disclaimer": { en: "<i class=\"fa-solid fa-circle-info mr-1\"></i>\n                        This project uses AI-generated content to enhance learning. Despite efforts to ensure accuracy,\n                        AI-generated materials should always be scrutinized and cross-referenced with authoritative sources.\n                        Found an issue? <a href=\"https://github.com/quarcs-lab/metricsai/issues\" target=\"_blank\" class=\"text-brand-400 hover:text-brand-300 underline\">Submit feedback on GitHub</a>.", es: "<i class=\"fa-solid fa-circle-info mr-1\"></i> Este proyecto usa contenido generado con IA para mejorar el aprendizaje. A pesar de los esfuerzos por garantizar su precisión, los materiales generados con IA deben siempre revisarse y contrastarse con fuentes autorizadas. ¿Encontraste un problema? <a href=\"https://github.com/quarcs-lab/metricsai/issues\" target=\"_blank\" class=\"text-brand-400 hover:text-brand-300 underline\">Envía tu comentario en GitHub</a>." },
  "footer.help.body": { en: "Found an error in the notebooks, book, or AI materials? Your feedback helps make metricsAI better for everyone!\n                        Please submit an issue on GitHub describing what you found, and we'll work to fix it.", es: "¿Encontraste un error en los cuadernos, el libro o los materiales de IA? ¡Tus comentarios ayudan a que metricsAI mejore para todos! Envía una incidencia en GitHub describiendo lo que encontraste y trabajaremos para corregirlo." },
  "footer.help.cta": { en: "Submit an Issue on GitHub", es: "Enviar una incidencia en GitHub" },
  "footer.help.heading": { en: "Help Improve This Project", es: "Ayuda a mejorar este proyecto" },
  "footer.license.body": { en: "This work is licensed under a\n                                <a href=\"https://creativecommons.org/licenses/by-nc-sa/4.0/\" target=\"_blank\" class=\"text-brand-400 hover:text-brand-300 underline\">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.", es: "Este trabajo está licenciado bajo una <a href=\"https://creativecommons.org/licenses/by-nc-sa/4.0/\" target=\"_blank\" class=\"text-brand-400 hover:text-brand-300 underline\">Licencia Internacional Creative Commons Atribución-NoComercial-CompartirIgual 4.0</a>." },
  "footer.license.heading": { en: "License", es: "Licencia" },
  "hero.badge": { en: "Python & AI for Economics", es: "Python e IA para Economía" },
  "hero.chapters": { en: "17 Chapters", es: "17 Capítulos" },
  "hero.check.ai": { en: "AI Support", es: "Asistencia con IA" },
  "hero.check.apps": { en: "Learning Apps", es: "Aplicaciones interactivas" },
  "hero.check.install": { en: "Zero Installation", es: "Sin instalación" },
  "hero.cta.primary": { en: "Learn by coding", es: "Aprender programando" },
  "hero.cta.secondary": { en: "Chat with AI Tutors", es: "Chatear con tutores IA" },
  "hero.subtitle": { en: "A modern introduction that combines cloud-based computational notebooks, learning apps, and AI tools.", es: "Una introducción moderna que combina cuadernos computacionales en la nube, aplicaciones de aprendizaje y herramientas de IA." },
  "hero.title": { en: "Econometrics", es: "Econometría" },
  "resources.empty": { en: "No resources found in this category yet.", es: "Aún no hay recursos en esta categoría." },
  "resources.heading": { en: "More Resources", es: "Más recursos" },
  "resources.lede": { en: "Additional materials to boost your learning journey", es: "Materiales adicionales para impulsar tu aprendizaje" },
  "resources.showMore.post": { en: "More Resources", es: "recursos más" },
  "resources.showMore.pre": { en: "Show", es: "Mostrar" }
});
