/* Page-specific strings for tutors.html — registered into window.I18N by i18n-runtime.js.
 * Shared keys (nav.*) live in _shared/strings/nav.js.
 */
window.I18N_REGISTER({
  "tutors.document.description": { en: "9 AI tutors with distinct learning styles for introductory econometrics. Choose the tutor that matches how you learn best.", es: "9 tutores de IA con estilos de aprendizaje distintos para una introducción a la econometría. Elige el tutor que se ajuste a cómo aprendes mejor." },
  "tutors.document.title": { en: "AI Tutors | metricsAI", es: "Tutores IA | metricsAI" },
  "tutors.bestFor": { en: "Best for:", es: "Ideal para:" },
  "tutors.card.analogy.bestFor": { en: "abstract concepts feel hard", es: "cuando los conceptos abstractos cuestan" },
  "tutors.card.analogy.desc": { en: "Ask about any concept and it gives you a vivid real-world analogy before any formula. OLS becomes drawing lines through stars, hypothesis testing becomes a courtroom trial. Stories first, math second &mdash; then connects back to the formal definition.", es: "Pregunta sobre cualquier concepto y te da una analogía vívida del mundo real antes que cualquier fórmula. MCO se convierte en trazar líneas entre estrellas; la prueba de hipótesis se convierte en un juicio en un tribunal. Primero las historias, después las matemáticas — y luego conecta con la definición formal." },
  "tutors.card.analogy.tag.1": { en: "Storytelling", es: "Narrativa" },
  "tutors.card.analogy.tag.2": { en: "Analogies", es: "Analogías" },
  "tutors.card.analogy.tag.3": { en: "Intuition First", es: "Intuición primero" },
  "tutors.card.analogy.tag.4": { en: "Beginner Friendly", es: "Apto para principiantes" },
  "tutors.card.analogy.try": { en: "\"Explain the Central Limit Theorem with an analogy\"", es: "\"Explícame el Teorema Central del Límite con una analogía\"" },
  "tutors.card.case.bestFor": { en: "applied / real-world framing", es: "enfoque aplicado / mundo real" },
  "tutors.card.case.desc": { en: "Tell it a chapter topic and it transforms the example into a structured case study. It walks you through 6 stages: Motivation, Research Question, Data Description, Methods, Results, and Answer. At the end, you write a 3-sentence Policy Brief for a non-technical audience.", es: "Dile un tema de capítulo y transforma el ejemplo en un estudio de caso estructurado. Te lleva por 6 etapas: Motivación, Pregunta de Investigación, Descripción de los Datos, Métodos, Resultados y Respuesta. Al final, escribes un Resumen de Política de 3 frases para una audiencia no técnica." },
  "tutors.card.case.tag.1": { en: "Case Studies", es: "Estudios de caso" },
  "tutors.card.case.tag.2": { en: "Policy Briefs", es: "Resúmenes de política" },
  "tutors.card.case.tag.3": { en: "6-Part Structure", es: "Estructura de 6 partes" },
  "tutors.card.case.tag.4": { en: "Real-World Data", es: "Datos del mundo real" },
  "tutors.card.case.try": { en: "\"Build a case study around Okun's Law from Chapter 8\"", es: "\"Construye un estudio de caso sobre la Ley de Okun del Capítulo 8\"" },
  "tutors.card.code.bestFor": { en: "learn-by-doing coders", es: "quienes aprenden programando" },
  "tutors.card.code.desc": { en: "Every concept starts with a Python code block you can copy into Google Colab. Run it, change something, observe what happens. It uses Monte Carlo simulations and the course datasets to build your intuition through hands-on experimentation.", es: "Cada concepto comienza con un bloque de código Python que puedes copiar en Google Colab. Ejecútalo, cambia algo, observa qué ocurre. Usa simulaciones de Monte Carlo y los conjuntos de datos del curso para construir tu intuición mediante experimentación práctica." },
  "tutors.card.code.tag.1": { en: "Hands-On", es: "Práctico" },
  "tutors.card.code.tag.2": { en: "Python Code", es: "Código Python" },
  "tutors.card.code.tag.3": { en: "Monte Carlo", es: "Monte Carlo" },
  "tutors.card.code.tag.4": { en: "Google Colab", es: "Google Colab" },
  "tutors.card.code.try": { en: "\"Show me how OLS works with a Monte Carlo simulation\"", es: "\"Muéstrame cómo funciona MCO con una simulación de Monte Carlo\"" },
  "tutors.card.debate.bestFor": { en: "testing deep understanding", es: "comprobar comprensión profunda" },
  "tutors.card.debate.desc": { en: "State a claim about econometrics and it takes the opposite position to stress-test your understanding. It says \"I disagree &mdash; convince me,\" celebrates when you defend well, and corrects when you can't. Sharpens your reasoning under pressure.", es: "Plantea una afirmación sobre econometría y toma la posición contraria para poner a prueba tu comprensión. Te dice \"No estoy de acuerdo — convénceme\", celebra cuando defiendes bien y te corrige cuando no puedes. Afina tu razonamiento bajo presión." },
  "tutors.card.debate.tag.1": { en: "Contrarian", es: "Contrario" },
  "tutors.card.debate.tag.2": { en: "Critical Thinking", es: "Pensamiento crítico" },
  "tutors.card.debate.tag.3": { en: "Defend Your Claims", es: "Defiende tus afirmaciones" },
  "tutors.card.debate.tag.4": { en: "Advanced", es: "Avanzado" },
  "tutors.card.debate.try": { en: "\"I believe a high R-squared means the model is good\"", es: "\"Creo que un R-cuadrado alto significa que el modelo es bueno\"" },
  "tutors.card.exam.bestFor": { en: "midterm & final prep", es: "preparación de parciales y finales" },
  "tutors.card.exam.desc": { en: "Tell it which chapters your exam covers and it generates timed practice sets with realistic questions. It identifies your weak spots, drills common pitfalls, and teaches test-taking strategy. After each answer, it gives targeted feedback.", es: "Dile qué capítulos cubre tu examen y genera series de práctica cronometradas con preguntas realistas. Identifica tus puntos débiles, ejercita los errores comunes y enseña estrategia para los exámenes. Tras cada respuesta da retroalimentación específica." },
  "tutors.card.exam.tag.1": { en: "Timed Drills", es: "Ejercicios cronometrados" },
  "tutors.card.exam.tag.2": { en: "Pitfall Alerts", es: "Avisos de errores" },
  "tutors.card.exam.tag.3": { en: "Weak Spot Diagnosis", es: "Diagnóstico de puntos débiles" },
  "tutors.card.exam.tag.4": { en: "Test Strategy", es: "Estrategia de examen" },
  "tutors.card.exam.try": { en: "\"Quiz me on Chapters 5-7 for my midterm next week\"", es: "\"Pregúntame sobre los capítulos 5-7 para mi examen parcial de la próxima semana\"" },
  "tutors.card.research.bestFor": { en: "advanced / thesis prep", es: "avanzado / preparación de tesis" },
  "tutors.card.research.desc": { en: "Treats you as a junior researcher. Give it a topic and it poses a real economic question, then guides you through the empirical workflow: question, data, model, estimate, interpret. After every step it asks: \"What would a journal referee say about this?\"", es: "Te trata como investigador junior. Dale un tema y plantea una pregunta económica real, luego te guía por el flujo empírico: pregunta, datos, modelo, estimación, interpretación. Tras cada paso pregunta: \"¿Qué diría sobre esto un evaluador de revista?\"" },
  "tutors.card.research.tag.1": { en: "Research Skills", es: "Habilidades de investigación" },
  "tutors.card.research.tag.2": { en: "Causal Thinking", es: "Pensamiento causal" },
  "tutors.card.research.tag.3": { en: "Threats to Validity", es: "Amenazas a la validez" },
  "tutors.card.research.tag.4": { en: "Advanced", es: "Avanzado" },
  "tutors.card.research.try": { en: "\"I want to study the causal effect of education on earnings\"", es: "\"Quiero estudiar el efecto causal de la educación sobre los ingresos\"" },
  "tutors.card.socratic.bestFor": { en: "students with some foundation", es: "estudiantes con algo de base" },
  "tutors.card.socratic.desc": { en: "Never explains directly &mdash; instead, it guides you to discover the answer yourself through carefully sequenced questions. Share a topic you're studying and it will ask probing questions that deepen your understanding step by step.", es: "Nunca explica directamente — en su lugar, te guía a descubrir la respuesta por ti mismo mediante preguntas cuidadosamente secuenciadas. Comparte un tema que estés estudiando y hará preguntas penetrantes que profundizan tu comprensión paso a paso." },
  "tutors.card.socratic.tag.1": { en: "Questions Only", es: "Solo preguntas" },
  "tutors.card.socratic.tag.2": { en: "Deep Thinking", es: "Pensamiento profundo" },
  "tutors.card.socratic.tag.3": { en: "No Direct Answers", es: "Sin respuestas directas" },
  "tutors.card.socratic.tag.4": { en: "Self-Discovery", es: "Autodescubrimiento" },
  "tutors.card.socratic.try": { en: "\"I think I understand R-squared, but I'm not sure\"", es: "\"Creo que entiendo R-cuadrado, pero no estoy seguro\"" },
  "tutors.card.visual.bestFor": { en: "visual learners", es: "aprendices visuales" },
  "tutors.card.visual.desc": { en: "Ask about any concept and it turns it into a picture. Scatter plots, residual diagnostics, before-and-after comparisons. It provides matplotlib code to generate plots you can run in Colab and references the course's interactive web apps.", es: "Pregunta sobre cualquier concepto y lo convierte en una imagen. Diagramas de dispersión, diagnósticos de residuos, comparaciones antes-y-después. Proporciona código matplotlib para generar gráficos que puedes ejecutar en Colab y referencia las aplicaciones web interactivas del curso." },
  "tutors.card.visual.tag.1": { en: "Visualization", es: "Visualización" },
  "tutors.card.visual.tag.2": { en: "Plots & Diagrams", es: "Gráficos y diagramas" },
  "tutors.card.visual.tag.3": { en: "Matplotlib Code", es: "Código matplotlib" },
  "tutors.card.visual.tag.4": { en: "Web Apps", es: "Aplicaciones web" },
  "tutors.card.visual.try": { en: "\"Show me what heteroskedasticity looks like in a residual plot\"", es: "\"Muéstrame cómo se ve la heterocedasticidad en un gráfico de residuos\"" },
  "tutors.chat": { en: "Chat", es: "Chatear" },
  "tutors.featured.cta": { en: "Start chatting", es: "Empezar a chatear" },
  "tutors.featured.desc": { en: "Your friendly, step-by-step guide through econometrics. Tell the Coach what you want to learn, and it builds a personalized lesson plan anchored to Key Concepts. It walks you through one substep at a time, checks your understanding with quiz questions, and offers practice problems. You can also paste a homework question and it will guide you to the solution without giving the answer away. Perfect if you want clear structure and encouragement.", es: "Tu guía amigable, paso a paso, a través de la econometría. Dile al Coach qué quieres aprender y construirá un plan de lecciones personalizado anclado a los conceptos clave. Te lleva un subpaso a la vez, comprueba tu comprensión con preguntas tipo quiz y ofrece problemas de práctica. También puedes pegar una pregunta de tarea y te guiará hacia la solución sin darte la respuesta. Perfecto si quieres una estructura clara y motivación." },
  "tutors.featured.recommended": { en: "Recommended", es: "Recomendado" },
  "tutors.featured.tag.1": { en: "Structured Plans", es: "Planes estructurados" },
  "tutors.featured.tag.2": { en: "Step-by-Step", es: "Paso a paso" },
  "tutors.featured.tag.3": { en: "Practice Quizzes", es: "Quizzes de práctica" },
  "tutors.featured.tag.4": { en: "Homework Help", es: "Ayuda con tareas" },
  "tutors.featured.tag.5": { en: "Encouraging", es: "Motivador" },
  "tutors.featured.tag.6": { en: "Beginner Friendly", es: "Apto para principiantes" },
  "tutors.featured.try.1": { en: "\"Teach me about confidence intervals from Chapter 4\"", es: "\"Enséñame sobre intervalos de confianza del Capítulo 4\"" },
  "tutors.featured.try.2": { en: "\"Help me practice hypothesis testing\"", es: "\"Ayúdame a practicar pruebas de hipótesis\"" },
  "tutors.footer.line1": { en: "<a href=\"index.html\" class=\"text-brand-600 dark:text-brand-400 hover:underline font-medium\">metricsAI</a>: An Introduction to Econometrics with Python and AI in the Cloud", es: "<a href=\"index.html\" class=\"text-brand-600 dark:text-brand-400 hover:underline font-medium\">metricsAI</a>: Una introducción a la econometría con Python e IA en la nube" },
  "tutors.footer.line2": { en: "By <strong class=\"text-slate-600 dark:text-slate-300\">Carlos Mendez</strong> &middot; Based on <a href=\"https://cameron.econ.ucdavis.edu/aed/index.html\" target=\"_blank\" class=\"text-brand-600 dark:text-brand-400 hover:underline\">Cameron (2022)</a>", es: "Por <strong class=\"text-slate-600 dark:text-slate-300\">Carlos Mendez</strong> &middot; Basado en <a href=\"https://cameron.econ.ucdavis.edu/aed/index.html\" target=\"_blank\" class=\"text-brand-600 dark:text-brand-400 hover:underline\">Cameron (2022)</a>" },
  "tutors.hero.badge": { en: "9 AI Tutors, 9 Learning Styles", es: "9 tutores IA, 9 estilos de aprendizaje" },
  "tutors.hero.stat.chapters": { en: "All 17 chapters", es: "Los 17 capítulos" },
  "tutors.hero.stat.code": { en: "Python code & datasets", es: "Código Python y conjuntos de datos" },
  "tutors.hero.stat.concepts": { en: "189 Key Concepts", es: "189 conceptos clave" },
  "tutors.hero.stat.practice": { en: "Practice problems", es: "Problemas de práctica" },
  "tutors.hero.subtitle": { en: "Every student learns differently. Our AI tutors are built as customized <a href=\"https://gemini.google.com/gems\" target=\"_blank\" class=\"text-brand-600 dark:text-brand-400 hover:underline font-medium\">Google Gemini Gems</a> — each with a distinct pedagogical approach, trained on the course content. \"Learn by coding\" is also a key feature of these tutors. You can use the <a href=\"https://colab.research.google.com/notebooks/empty.ipynb\" target=\"_blank\" class=\"text-brand-600 dark:text-brand-400 hover:underline font-medium\">Google Colab scratchpad</a> to easily engage with the code the tutors provide.", es: "Cada estudiante aprende de manera diferente. Nuestros tutores de IA están construidos como <a href=\"https://gemini.google.com/gems\" target=\"_blank\" class=\"text-brand-600 dark:text-brand-400 hover:underline font-medium\">Gems de Google Gemini</a> personalizados — cada uno con un enfoque pedagógico distinto, entrenados sobre el contenido del curso. \"Aprender programando\" también es una característica clave de estos tutores. Puedes usar el <a href=\"https://colab.research.google.com/notebooks/empty.ipynb\" target=\"_blank\" class=\"text-brand-600 dark:text-brand-400 hover:underline font-medium\">scratchpad de Google Colab</a> para interactuar fácilmente con el código que los tutores proporcionan." },
  "tutors.hero.title.accent": { en: "AI Tutor", es: "Tutor IA" },
  "tutors.hero.title.pre": { en: "Choose Your", es: "Elige tu" },
  "tutors.how.heading": { en: "How It Works", es: "Cómo funciona" },
  "tutors.how.step.1.body": { en: "Choose the learning style that fits you. You can switch any time.", es: "Elige el estilo de aprendizaje que se ajuste a ti. Puedes cambiar en cualquier momento." },
  "tutors.how.step.1.title": { en: "Pick a Tutor", es: "Elige un tutor" },
  "tutors.how.step.2.body": { en: "Concepts, homework, Python code, exam prep. All 17 chapters covered.", es: "Conceptos, tareas, código Python, preparación de exámenes. Los 17 capítulos cubiertos." },
  "tutors.how.step.2.title": { en: "Ask Anything", es: "Pregunta lo que quieras" },
  "tutors.how.step.3.body": { en: "Get personalized explanations, practice problems, and Python code you can run in Colab.", es: "Obtén explicaciones personalizadas, problemas de práctica y código Python que puedes ejecutar en Colab." },
  "tutors.how.step.3.title": { en: "Learn & Practice", es: "Aprende y practica" },
  "tutors.or": { en: "or", es: "o" },
  "tutors.poweredBy": { en: "<i class=\"fa-solid fa-wand-magic-sparkles mr-1.5 text-brand-500\"></i>\n                    All tutors are built as customized <a href=\"https://gemini.google.com/gems\" target=\"_blank\" class=\"text-brand-600 dark:text-brand-400 hover:underline font-medium\">Gems</a> on <a href=\"https://gemini.google.com/\" target=\"_blank\" class=\"text-brand-600 dark:text-brand-400 hover:underline font-medium\">Google Gemini</a>, each with tailored instructions for a distinct learning style.", es: "<i class=\"fa-solid fa-wand-magic-sparkles mr-1.5 text-brand-500\"></i> Todos los tutores están construidos como <a href=\"https://gemini.google.com/gems\" target=\"_blank\" class=\"text-brand-600 dark:text-brand-400 hover:underline font-medium\">Gems</a> personalizados en <a href=\"https://gemini.google.com/\" target=\"_blank\" class=\"text-brand-600 dark:text-brand-400 hover:underline font-medium\">Google Gemini</a>, cada uno con instrucciones adaptadas a un estilo de aprendizaje distinto." },
  "tutors.sectionDivider": { en: "Choose your style", es: "Elige tu estilo" },
  "tutors.try": { en: "Try:", es: "Prueba:" }
});
