<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Econometrics Powered by AI - 1. Analysis of Economics Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../notebooks_colab/ch02_Univariate_Data_Summary.html" rel="next">
<link href="../index.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../custom.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../notebooks_colab/ch01_Analysis_of_Economics_Data.html">Statistical Foundations</a></li><li class="breadcrumb-item"><a href="../notebooks_colab/ch01_Analysis_of_Economics_Data.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">1. Analysis of Economics Data</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Econometrics Powered by AI</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Statistical Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch01_Analysis_of_Economics_Data.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">1. Analysis of Economics Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch02_Univariate_Data_Summary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2. Univariate Data Summary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch03_The_Sample_Mean.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3. The Sample Mean</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch04_Statistical_Inference_for_the_Mean.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4. Statistical Inference for the Mean</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Bivariate Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch05_Bivariate_Data_Summary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5. Bivariate Data Summary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch06_The_Least_Squares_Estimator.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6. The Least Squares Estimator</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch07_Statistical_Inference_for_Bivariate_Regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7. Statistical Inference for Bivariate Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch08_Case_Studies_for_Bivariate_Regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">8. Case Studies for Bivariate Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch09_Models_with_Natural_Logarithms.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">9. Models with Natural Logarithms</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Multiple Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch10_Data_Summary_for_Multiple_Regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">10. Data Summary for Multiple Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch11_Statistical_Inference_for_Multiple_Regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11. Statistical Inference for Multiple Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch12_Further_Topics_in_Multiple_Regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12. Further Topics in Multiple Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch13_Case_Studies_for_Multiple_Regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">13. Case Studies for Multiple Regression</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Advanced Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch14_Regression_with_Indicator_Variables.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14. Regression with Indicator Variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch15_Regression_with_Transformed_Variables.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15. Regression with Transformed Variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch16_Checking_the_Model_and_Data.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">16. Checking the Model and Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch17_Panel_Data_Time_Series_Data_Causation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">17. Panel Data, Time Series Data, Causation</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#chapter-overview" id="toc-chapter-overview" class="nav-link active" data-scroll-target="#chapter-overview">Chapter Overview</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#what-is-regression-analysis" id="toc-what-is-regression-analysis" class="nav-link" data-scroll-target="#what-is-regression-analysis">1.1 What is Regression Analysis?</a></li>
  <li><a href="#load-the-data" id="toc-load-the-data" class="nav-link" data-scroll-target="#load-the-data">1.2 Load the Data</a></li>
  <li><a href="#preview-the-data" id="toc-preview-the-data" class="nav-link" data-scroll-target="#preview-the-data">1.3 Preview the Data</a></li>
  <li><a href="#explore-the-data" id="toc-explore-the-data" class="nav-link" data-scroll-target="#explore-the-data">1.4 Explore the Data</a></li>
  <li><a href="#visualizing-the-relationship" id="toc-visualizing-the-relationship" class="nav-link" data-scroll-target="#visualizing-the-relationship">1.5 Visualizing the Relationship</a></li>
  <li><a href="#fitting-a-regression-line" id="toc-fitting-a-regression-line" class="nav-link" data-scroll-target="#fitting-a-regression-line">1.6 Fitting a Regression Line</a></li>
  <li><a href="#interpreting-the-results" id="toc-interpreting-the-results" class="nav-link" data-scroll-target="#interpreting-the-results">1.7 Interpreting the Results</a></li>
  <li><a href="#visualizing-the-fitted-line" id="toc-visualizing-the-fitted-line" class="nav-link" data-scroll-target="#visualizing-the-fitted-line">1.8 Visualizing the Fitted Line</a></li>
  <li><a href="#economic-interpretation-and-examples" id="toc-economic-interpretation-and-examples" class="nav-link" data-scroll-target="#economic-interpretation-and-examples">1.9 Economic Interpretation and Examples</a></li>
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways">Key Takeaways</a></li>
  <li><a href="#practice-exercises" id="toc-practice-exercises" class="nav-link" data-scroll-target="#practice-exercises">Practice Exercises</a></li>
  <li><a href="#case-studies" id="toc-case-studies" class="nav-link" data-scroll-target="#case-studies">Case Studies</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<div id="google_translate_element" style="padding: 8px 0;"></div>
<script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({
    pageLanguage: 'en',
    layout: google.translate.TranslateElement.InlineLayout.HORIZONTAL
  }, 'google_translate_element');
}
</script>
<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">1. Analysis of Economics Data</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><strong>metricsAI: An Introduction to Econometrics with Python and AI in the Cloud</strong></p>
<p><em><a href="https://carlos-mendez.org">Carlos Mendez</a></em></p>
<p><img src="https://raw.githubusercontent.com/quarcs-lab/metricsai/main/images/ch01_visual_summary.jpg" alt="Chapter 01 Visual Summary" width="65%"></p>
<p>This notebook provides an interactive introduction to regression analysis using Python. You can run all code directly in Google Colab without any local setup required. The data streams directly from GitHub, making this notebook fully self-contained.</p>
<a href="https://colab.research.google.com/github/quarcs-lab/metricsai/blob/main/notebooks_colab/ch01_Analysis_of_Economics_Data.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" class="img-fluid" alt="Open In Colab"></a>
<div class="chapter-resources">
<p><a href="https://www.youtube.com/watch?v=RyE01v-zliM" target="_blank" class="resource-btn">🎬 AI Video</a> <a href="https://carlos-mendez.my.canva.site/s01-analysis-of-economics-data-pdf" target="_blank" class="resource-btn">✨ AI Slides</a> <a href="https://cameron.econ.ucdavis.edu/aed/traedv1_01" target="_blank" class="resource-btn">📊 Cameron Slides</a> <a href="https://app.edcafe.ai/quizzes/69715fdb60956f50e60276b9" target="_blank" class="resource-btn">✏️ Quiz</a> <a href="https://app.edcafe.ai/chatbots/6971625960956f50e6028155" target="_blank" class="resource-btn">🤖 AI Tutor</a></p>
</div>
<section id="chapter-overview" class="level2">
<h2 class="anchored" data-anchor-id="chapter-overview">Chapter Overview</h2>
<p>This chapter introduces the fundamental concepts of econometrics and regression analysis. We’ll explore how economists use statistical methods to understand relationships in economic data, focusing on a practical example of house prices and house sizes.</p>
<p><strong>What you’ll learn:</strong></p>
<ul>
<li>What regression analysis is and why it’s the primary tool in econometrics</li>
<li>How to load and explore economic data using Python (pandas)</li>
<li>How to visualize relationships between variables using scatter plots</li>
<li>How to fit a simple linear regression model using Ordinary Least Squares (OLS)</li>
<li>How to interpret regression coefficients in economic terms</li>
<li>How to use Python’s statsmodels package for regression analysis</li>
</ul>
<p><strong>Dataset used:</strong></p>
<ul>
<li><strong>AED_HOUSE.DTA</strong>: House sale prices for 29 houses in Central Davis, California (1999)
<ul>
<li>Variables: price (sale price in dollars), size (house size in square feet), plus 7 other characteristics</li>
</ul></li>
</ul>
<p><strong>Chapter outline:</strong></p>
<ul>
<li>1.1 What is Regression Analysis?</li>
<li>1.2 Load the Data</li>
<li>1.3 Preview the Data</li>
<li>1.4 Explore the Data</li>
<li>1.5 Visualizing the Relationship</li>
<li>1.6 Fitting a Regression Line</li>
<li>1.7 Interpreting the Results</li>
<li>1.8 Visualizing the Fitted Line</li>
<li>1.9 Economic Interpretation and Examples</li>
<li>Practice Exercises</li>
<li>Case Studies</li>
</ul>
</section>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<p>Run this cell first to import all required packages and configure the environment. This sets up:</p>
<ul>
<li>Data manipulation (pandas, numpy)</li>
<li>Statistical modeling (statsmodels)</li>
<li>Visualization (matplotlib)</li>
<li>Reproducibility (random seeds)</li>
</ul>
<div class="cell" data-outputid="1ff552d8-cc1f-40d7-bf12-661c3dbf4208" data-execution_count="41">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import required libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.formula.api <span class="im">import</span> ols</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> random</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Set random seeds for reproducibility</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>RANDOM_SEED <span class="op">=</span> <span class="dv">42</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>random.seed(RANDOM_SEED)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>np.random.seed(RANDOM_SEED)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>os.environ[<span class="st">'PYTHONHASHSEED'</span>] <span class="op">=</span> <span class="bu">str</span>(RANDOM_SEED)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># GitHub data URL (data streams directly from here)</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>GITHUB_DATA_URL <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/"</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Optional: Create directories for saving outputs locally</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>IMAGES_DIR <span class="op">=</span> <span class="st">'images'</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>TABLES_DIR <span class="op">=</span> <span class="st">'tables'</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>os.makedirs(IMAGES_DIR, exist_ok<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>os.makedirs(TABLES_DIR, exist_ok<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"✓ Setup complete! All packages imported successfully."</span>)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"✓ Random seed set to </span><span class="sc">{</span>RANDOM_SEED<span class="sc">}</span><span class="ss"> for reproducibility."</span>)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"✓ Data will stream from: </span><span class="sc">{</span>GITHUB_DATA_URL<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>✓ Setup complete! All packages imported successfully.
✓ Random seed set to 42 for reproducibility.
✓ Data will stream from: https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/</code></pre>
</div>
</div>
</section>
<section id="what-is-regression-analysis" class="level2">
<h2 class="anchored" data-anchor-id="what-is-regression-analysis">1.1 What is Regression Analysis?</h2>
<p><strong>Regression analysis</strong> is the primary tool economists use to understand relationships between variables. At its core, regression answers questions like: “How does Y change when X changes?”</p>
<p>In our example:</p>
<ul>
<li><strong>Y (dependent variable)</strong>: House sale price (in dollars)</li>
<li><strong>X (independent variable)</strong>: House size (in square feet)</li>
</ul>
<p><strong>The regression line</strong> is the “line of best fit” that minimizes the sum of squared distances between actual prices and predicted prices. The mathematical form is:</p>
<p><span class="math display">\[\text{price} = \beta_0 + \beta_1 \times \text{size} + \varepsilon\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> = <strong>intercept</strong> (predicted price when size = 0)</li>
<li><span class="math inline">\(\beta_1\)</span> = <strong>slope</strong> (change in price for each additional square foot)</li>
<li><span class="math inline">\(\varepsilon\)</span> = <strong>error term</strong> (random variation not explained by size)</li>
</ul>
<p><strong>Economic Interpretation:</strong><br>
The slope coefficient <span class="math inline">\(\beta_1\)</span> tells us: “On average, how much more expensive is a house that is 1 square foot larger?” This is a measure of <strong>association</strong>, not necessarily causation.</p>
<blockquote class="blockquote">
<p><strong>Key Concept 1.1: Descriptive vs.&nbsp;Inferential Analysis</strong></p>
<p>Descriptive analysis summarizes data using statistics and visualizations, while statistical inference uses sample data to draw conclusions about the broader population. Most econometric analysis involves statistical inference.</p>
</blockquote>
</section>
<section id="load-the-data" class="level2">
<h2 class="anchored" data-anchor-id="load-the-data">1.2 Load the Data</h2>
<p>Let’s load the house price dataset directly from GitHub. This dataset contains information on 29 house sales in Central Davis, California in 1999.</p>
<div class="cell" data-outputid="7fc23f00-79d1-44f4-acb0-a32744e29db1" data-execution_count="42">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the Stata dataset from GitHub</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>data_house <span class="op">=</span> pd.read_stata(GITHUB_DATA_URL <span class="op">+</span> <span class="st">'AED_HOUSE.DTA'</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"✓ Data loaded successfully!"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Shape: </span><span class="sc">{</span>data_house<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> observations, </span><span class="sc">{</span>data_house<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> variables"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>✓ Data loaded successfully!
  Shape: 29 observations, 8 variables</code></pre>
</div>
</div>
</section>
<section id="preview-the-data" class="level2">
<h2 class="anchored" data-anchor-id="preview-the-data">1.3 Preview the Data</h2>
<p>Let’s look at the first few rows to understand what variables we have available.</p>
<div class="cell" data-outputid="d85e7ae3-2c13-4ff4-bbac-3009a9b5d01f" data-execution_count="43">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Display first 5 rows</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"First 5 observations:"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data_house.head())</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Column names:"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data_house.columns.tolist())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>First 5 observations:
    price  size  bedrooms  bathrooms  lotsize   age  monthsold    list
0  204000  1400         3        2.0        1  31.0          7  199900
1  212000  1600         3        3.0        2  33.0          5  212000
2  213000  1800         3        2.0        2  51.0          4  219900
3  220000  1600         3        2.0        1  49.0          4  229000
4  224500  2100         4        2.5        2  47.0          6  224500

Column names:
['price', 'size', 'bedrooms', 'bathrooms', 'lotsize', 'age', 'monthsold', 'list']</code></pre>
</div>
</div>
<p><strong>Transition:</strong> Before jumping into regression analysis, we need to understand our data. Descriptive statistics reveal the scale, variability, and range of our variables—essential for interpreting regression results.</p>
</section>
<section id="explore-the-data" class="level2">
<h2 class="anchored" data-anchor-id="explore-the-data">1.4 Explore the Data</h2>
<p>Before running any regression, it’s essential to understand the data through <strong>descriptive statistics</strong>. Let’s look at the key statistics for our variables of interest: price and size.</p>
<div class="cell" data-outputid="f6e8e9b7-aab7-47d3-8739-fd15b5b4e4fd" data-execution_count="44">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics for all variables</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"DESCRIPTIVE STATISTICS"</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data_house.describe().<span class="bu">round</span>(<span class="dv">2</span>))</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Focus on our key variables</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span> <span class="op">+</span> <span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"KEY VARIABLES: PRICE AND SIZE"</span>)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data_house[[<span class="st">'price'</span>, <span class="st">'size'</span>]].describe().<span class="bu">round</span>(<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
DESCRIPTIVE STATISTICS
======================================================================
           price     size  bedrooms  bathrooms  lotsize    age  monthsold  \
count      29.00    29.00     29.00      29.00    29.00  29.00      29.00   
mean   253910.34  1882.76      3.79       2.21     2.14  36.41       5.97   
std     37390.71   398.27      0.68       0.34     0.69   7.12       1.68   
min    204000.00  1400.00      3.00       2.00     1.00  23.00       3.00   
25%    233000.00  1600.00      3.00       2.00     2.00  31.00       5.00   
50%    244000.00  1800.00      4.00       2.00     2.00  35.00       6.00   
75%    270000.00  2000.00      4.00       2.50     3.00  39.00       7.00   
max    375000.00  3300.00      6.00       3.00     3.00  51.00       8.00   

            list  
count      29.00  
mean   257824.14  
std     40860.26  
min    199900.00  
25%    239000.00  
50%    245000.00  
75%    269000.00  
max    386000.00  

======================================================================
KEY VARIABLES: PRICE AND SIZE
======================================================================
           price     size
count      29.00    29.00
mean   253910.34  1882.76
std     37390.71   398.27
min    204000.00  1400.00
25%    233000.00  1600.00
50%    244000.00  1800.00
75%    270000.00  2000.00
max    375000.00  3300.00</code></pre>
</div>
</div>
<p><strong>Key observations:</strong></p>
<ul>
<li><strong>Mean house price</strong>: Around $253,910</li>
<li><strong>Mean house size</strong>: Around 1,883 square feet</li>
<li><strong>Price range</strong>: $204,000 to $375,000</li>
<li><strong>Size range</strong>: 1,400 to 3,300 square feet</li>
</ul>
<p>Notice the variation in both variables - this variation is what allows us to estimate a relationship!</p>
<blockquote class="blockquote">
<p><strong>Key Concept 1.2: Observational Data in Economics</strong></p>
<p>Economics primarily uses observational data where we observe behavior in uncontrolled settings. Unlike experimental data where conditions can be controlled, observational data requires careful methods to establish relationships and, when possible, causal effects.</p>
</blockquote>
<p><em>Now that we have explored the data numerically, let’s visualize the relationship between house size and price.</em></p>
</section>
<section id="visualizing-the-relationship" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-the-relationship">1.5 Visualizing the Relationship</h2>
<p><strong>Before running any regression</strong>, it’s good practice to visualize the relationship between X and Y. A scatter plot helps us:</p>
<ol type="1">
<li>Check if there appears to be a linear relationship</li>
<li>Identify any outliers or unusual observations</li>
<li>Get an intuitive sense of the strength of the relationship</li>
</ol>
<p>Let’s create a scatter plot of house price vs.&nbsp;house size.</p>
<div class="cell" data-outputid="3dac4042-af09-476f-eb3d-dbb087a43e76" data-execution_count="45">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create scatter plot</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the data points</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>ax.scatter(data_house[<span class="st">'size'</span>], data_house[<span class="st">'price'</span>],</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>           color<span class="op">=</span><span class="st">'navy'</span>, s<span class="op">=</span><span class="dv">50</span>, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Labels and formatting</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'House Size (square feet)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'House Sale Price (dollars)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'House Price vs Size (29 observations)'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>ax.spines[[<span class="st">'top'</span>, <span class="st">'right'</span>]].set_visible(<span class="va">False</span>)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">What do you see?"</span>)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"- Positive relationship: Larger houses tend to have higher prices"</span>)</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"- Roughly linear: The points follow an upward-sloping pattern"</span>)</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"- Some scatter: Not all points lie exactly on a line (this is the 'error')"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="ch01_Analysis_of_Economics_Data_files/figure-html/cell-6-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
What do you see?
- Positive relationship: Larger houses tend to have higher prices
- Roughly linear: The points follow an upward-sloping pattern
- Some scatter: Not all points lie exactly on a line (this is the 'error')</code></pre>
</div>
</div>
<p><strong>Transition:</strong> Having visualized a clear positive relationship between house size and price, we’re ready to quantify this relationship precisely using regression analysis.</p>
<blockquote class="blockquote">
<p><strong>Key Concept 1.3: Visual Exploration Before Regression</strong></p>
<p>Always plot your data before running a regression. Scatter plots reveal the direction, strength, and form of relationships between variables, and can expose outliers or nonlinearities that summary statistics alone would miss. Visual exploration is the essential first step in any empirical analysis.</p>
</blockquote>
</section>
<section id="fitting-a-regression-line" class="level2">
<h2 class="anchored" data-anchor-id="fitting-a-regression-line">1.6 Fitting a Regression Line</h2>
<p>Now we’ll fit an <strong>Ordinary Least Squares (OLS)</strong> regression line to these data. OLS chooses the intercept (<span class="math inline">\(\beta_0\)</span>) and slope (<span class="math inline">\(\beta_1\)</span>) that <strong>minimize the sum of squared residuals</strong>:</p>
<p><span class="math display">\[\min_{\beta_0, \beta_1} \sum_{i=1}^{n} (\text{price}_i - \beta_0 - \beta_1 \times \text{size}_i)^2\]</span></p>
<p>In other words, we’re finding the line that makes our prediction errors as small as possible (in a squared sense).</p>
<p>We’ll use Python’s <code>statsmodels</code> package, which provides regression output similar to Stata and R.</p>
<blockquote class="blockquote">
<p><strong>Key Concept 1.4: Introduction to Regression Analysis</strong></p>
<p>Regression analysis quantifies the relationship between variables. In a bivariate regression, the slope coefficient tells us how much the outcome variable (<span class="math inline">\(y\)</span>) changes when the explanatory variable (<span class="math inline">\(x\)</span>) increases by one unit.</p>
</blockquote>
<div class="cell" data-outputid="2f2ccdd4-dcd7-42a5-bcea-d6e55b840049" data-execution_count="46">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit OLS regression: price ~ size</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The formula syntax is: 'dependent_variable ~ independent_variable'</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> ols(<span class="st">'price ~ size'</span>, data<span class="op">=</span>data_house).fit()</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the full regression output</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"OLS REGRESSION RESULTS: price ~ size"</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
OLS REGRESSION RESULTS: price ~ size
======================================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  price   R-squared:                       0.617
Model:                            OLS   Adj. R-squared:                  0.603
Method:                 Least Squares   F-statistic:                     43.58
Date:                Sat, 31 Jan 2026   Prob (F-statistic):           4.41e-07
Time:                        02:18:54   Log-Likelihood:                -332.05
No. Observations:                  29   AIC:                             668.1
Df Residuals:                      27   BIC:                             670.8
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    1.15e+05   2.15e+04      5.352      0.000    7.09e+04    1.59e+05
size          73.7710     11.175      6.601      0.000      50.842      96.700
==============================================================================
Omnibus:                        0.576   Durbin-Watson:                   1.219
Prob(Omnibus):                  0.750   Jarque-Bera (JB):                0.638
Skew:                          -0.078   Prob(JB):                        0.727
Kurtosis:                       2.290   Cond. No.                     9.45e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.45e+03. This might indicate that there are
strong multicollinearity or other numerical problems.</code></pre>
</div>
</div>
</section>
<section id="interpreting-the-results" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-the-results">1.7 Interpreting the Results</h2>
<p>The regression output contains a lot of information! Let’s break down the most important parts:</p>
<section id="key-statistics-to-focus-on" class="level3">
<h3 class="anchored" data-anchor-id="key-statistics-to-focus-on">Key Statistics to Focus On:</h3>
<ol type="1">
<li><strong>Coefficients table</strong> (middle section):
<ul>
<li><strong>Intercept</strong>: The predicted price when size = 0 (often not economically meaningful)</li>
<li><strong>size</strong>: The slope coefficient - our main interest!</li>
<li><strong>std err</strong>: Standard error (measures precision of the estimate)</li>
<li><strong>t</strong>: t-statistic (coefficient / standard error)</li>
<li><strong>P&gt;|t|</strong>: p-value (tests if coefficient is significantly different from zero)</li>
</ul></li>
<li><strong>R-squared</strong> (top right section):
<ul>
<li>Proportion of variation in Y explained by X</li>
<li>Ranges from 0 to 1 (higher = better fit)</li>
</ul></li>
<li><strong>F-statistic</strong> (top right section):
<ul>
<li>Tests overall significance of the regression</li>
<li>Low p-value (Prob F-statistic) means the model is statistically significant</li>
</ul></li>
</ol>
<p>Let’s extract and interpret the key coefficients.</p>
<div class="cell" data-outputid="c98030a7-9b7f-48c2-8fb5-16e4b405ddfd" data-execution_count="47">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract key statistics</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>intercept <span class="op">=</span> model.params[<span class="st">'Intercept'</span>]</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>slope     <span class="op">=</span> model.params[<span class="st">'size'</span>]</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>r_squared <span class="op">=</span> model.rsquared</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>n_obs     <span class="op">=</span> <span class="bu">int</span>(model.nobs)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"KEY REGRESSION COEFFICIENTS"</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Intercept (β₀): $</span><span class="sc">{</span>intercept<span class="sc">:,</span><span class="fl">.2</span><span class="er">f</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Slope (β₁):  $</span><span class="sc">{</span>slope<span class="sc">:,</span><span class="fl">.2</span><span class="er">f</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"R-squared: </span><span class="sc">{</span>r_squared<span class="sc">:.4f}</span><span class="ss"> (</span><span class="sc">{</span>r_squared<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%)"</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Number of observations: </span><span class="sc">{</span>n_obs<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span> <span class="op">+</span> <span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"ECONOMIC INTERPRETATION"</span>)</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"📌 For every additional square foot of house size,"</span>)</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"   the sale price increases by approximately $</span><span class="sc">{</span>slope<span class="sc">:,</span><span class="fl">.2</span><span class="er">f</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">📌 The model explains </span><span class="sc">{</span>r_squared<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">% of the variation in house prices"</span>)</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">📌 The remaining </span><span class="sc">{</span>(<span class="dv">1</span><span class="op">-</span>r_squared)<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">% is due to other factors not included"</span>)</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"   (e.g., location, age, condition, neighborhood quality)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
KEY REGRESSION COEFFICIENTS
======================================================================
Intercept (β₀): $115,017.28
Slope (β₁):  $73.77
R-squared: 0.6175 (61.75%)
Number of observations: 29

======================================================================
ECONOMIC INTERPRETATION
======================================================================
📌 For every additional square foot of house size,
   the sale price increases by approximately $73.77

📌 The model explains 61.75% of the variation in house prices

📌 The remaining 38.25% is due to other factors not included
   (e.g., location, age, condition, neighborhood quality)</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Key Concept 1.5: Reading Regression Output</strong></p>
<p>The key elements of regression output are: the coefficient estimate (magnitude and direction of the relationship), the standard error (precision of the estimate), the t-statistic and p-value (statistical significance), and R-squared (proportion of variation explained). Together, these tell us whether the relationship is economically meaningful and statistically reliable.</p>
</blockquote>
</section>
</section>
<section id="visualizing-the-fitted-line" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-the-fitted-line">1.8 Visualizing the Fitted Line</h2>
<p>The <strong>fitted regression line</strong> represents our model’s predictions. For any given house size, the line shows the predicted price according to our equation:</p>
<p><span class="math display">\[\hat{\text{price}} = \beta_0 + \beta_1 \times \text{size}\]</span></p>
<p>Let’s overlay this fitted line on our scatter plot to see how well it captures the relationship.</p>
<div class="cell" data-outputid="97b0151c-7781-42b6-e52a-c5ca2ce58f95" data-execution_count="48">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create scatter plot with fitted regression line</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot actual data points</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>ax.scatter(data_house[<span class="st">'size'</span>], data_house[<span class="st">'price'</span>],</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>           color<span class="op">=</span><span class="st">'navy'</span>, s<span class="op">=</span><span class="dv">50</span>, label<span class="op">=</span><span class="st">'Actual prices'</span>, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot fitted regression line</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>ax.plot(data_house[<span class="st">'size'</span>], model.fittedvalues,</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span><span class="st">'purple'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">'Fitted regression line'</span>)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Add equation to plot</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>equation_text <span class="op">=</span> <span class="ss">f'price = </span><span class="sc">{</span>intercept<span class="sc">:,</span><span class="fl">.0</span><span class="er">f</span><span class="sc">}</span><span class="ss"> + </span><span class="sc">{</span>slope<span class="sc">:.2f}</span><span class="ss"> × size'</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">0.05</span>, <span class="fl">0.95</span>, equation_text,</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>        transform<span class="op">=</span>ax.transAxes, fontsize<span class="op">=</span><span class="dv">11</span>,</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>        verticalalignment<span class="op">=</span><span class="st">'top'</span>,</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>        bbox<span class="op">=</span><span class="bu">dict</span>(boxstyle<span class="op">=</span><span class="st">'round'</span>, facecolor<span class="op">=</span><span class="st">'wheat'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>))</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Labels and formatting</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'House Size (square feet)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'House Sale Price (dollars)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'House Price vs Size with Fitted Regression Line'</span>,</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>             fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="st">'lower right'</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>ax.spines[[<span class="st">'top'</span>, <span class="st">'right'</span>]].set_visible(<span class="va">False</span>)</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">📊 The purple line is our 'line of best fit'"</span>)</span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"   It minimizes the sum of squared vertical distances from each point"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="ch01_Analysis_of_Economics_Data_files/figure-html/cell-9-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
📊 The purple line is our 'line of best fit'
   It minimizes the sum of squared vertical distances from each point</code></pre>
</div>
</div>
<p><strong>Transition:</strong> Statistical output is only meaningful when translated into economic insights. Let’s explore what our regression coefficients tell us about housing markets and the limitations of our analysis.</p>
<p><em>Having fitted and visualized our regression model, let’s now interpret what these results mean in economic terms.</em></p>
</section>
<section id="economic-interpretation-and-examples" class="level2">
<h2 class="anchored" data-anchor-id="economic-interpretation-and-examples">1.9 Economic Interpretation and Examples</h2>
<p>Now that we’ve estimated the regression, let’s think about what it means in economic terms.</p>
<section id="practical-implications" class="level3">
<h3 class="anchored" data-anchor-id="practical-implications">Practical Implications:</h3>
<p>Our estimated slope of approximately <strong>$74 per square foot</strong> means:</p>
<ul>
<li>A house that’s 100 sq ft larger is predicted to sell for $74 × 100 = $7,400 more</li>
<li>A house that’s 500 sq ft larger is predicted to sell for $74 × 500 = $37,000 more</li>
</ul>
</section>
<section id="making-predictions" class="level3">
<h3 class="anchored" data-anchor-id="making-predictions">Making Predictions:</h3>
<p>We can use our regression equation to predict prices for houses of different sizes. For example, for a 2,000 sq ft house:</p>
<p><span class="math display">\[\hat{\text{price}} = 115,952 + 74.03 \times 2000 = \$264,012\]</span></p>
</section>
<section id="important-caveats" class="level3">
<h3 class="anchored" data-anchor-id="important-caveats">Important Caveats:</h3>
<ol type="1">
<li><p><strong>This is association, not causation</strong>: We can’t conclude that adding square footage to a house will increase its value by $74/sq ft. Other factors (like quality of construction) might be correlated with size.</p></li>
<li><p><strong>Omitted variables</strong>: Many other factors affect house prices (location, age, condition, amenities). Our simple model ignores these - we’ll learn how to include them in later chapters.</p></li>
<li><p><strong>Sample-specific</strong>: These results are from 29 houses in Davis, CA in 1999. The relationship might differ in other locations or time periods.</p></li>
<li><p><strong>Don’t extrapolate too far</strong>: Our data ranges from 1,400 to 3,300 sq ft. Predictions far outside this range (e.g., for a 10,000 sq ft house) may not be reliable.</p></li>
</ol>
<blockquote class="blockquote">
<p><strong>Key Concept 1.6: Interpreting Regression Results</strong></p>
<p>Regression results must be interpreted with caution. Association does not imply causation, omitted variables can bias estimates, and predictions should not extrapolate beyond the range of the data.</p>
</blockquote>
</section>
</section>
<section id="key-takeaways" class="level2">
<h2 class="anchored" data-anchor-id="key-takeaways">Key Takeaways</h2>
<p><strong>Statistical Methods and Data Types:</strong></p>
<ul>
<li>Econometrics uses two main approaches: descriptive analysis (summarizing data) and statistical inference (drawing population conclusions from samples)</li>
<li>Economic data are primarily continuous and numerical, though categorical and discrete data are also important</li>
<li>Economics relies mainly on observational data, making causal inference more challenging than with experimental data</li>
<li>The three data collection methods are cross-section (individuals at one time), time series (one individual over time), and panel data (individuals over time)</li>
<li>Each data type requires different considerations for statistical inference, particularly when computing standard errors</li>
<li>This textbook focuses on continuous numerical data and cross-section analysis as the foundation for more advanced methods</li>
</ul>
<p><strong>Regression Analysis and Interpretation:</strong></p>
<ul>
<li>Regression analysis is the primary tool in econometrics, quantifying how outcome variables (y) vary with explanatory variables (x)</li>
<li>The simple linear regression model has the form: <span class="math inline">\(y = \beta_0 + \beta_1 x + \varepsilon\)</span>, where <span class="math inline">\(\beta_0\)</span> is the intercept and <span class="math inline">\(\beta_1\)</span> is the slope</li>
<li>The slope coefficient measures association: how much y changes when x increases by one unit</li>
<li>OLS (Ordinary Least Squares) finds the best-fitting line by minimizing the sum of squared prediction errors</li>
<li>R-squared measures the proportion of variation in y explained by x, ranging from 0 to 1 (higher = better fit)</li>
<li>Economic interpretation focuses on magnitude (size of effect), statistical significance, and practical importance</li>
</ul>
<p><strong>Practical Application:</strong></p>
<ul>
<li>Our house price example: Each additional square foot is associated with a $73.77 increase in price (R² = 61.75%)</li>
<li>Visualization is essential: scatter plots reveal the nature of relationships before fitting regression models</li>
<li>Regression shows association, not causation—omitted variables and confounding factors require careful consideration</li>
<li>Predictions should not extrapolate beyond the range of observed data</li>
<li>Sample-specific results may not generalize to other locations, time periods, or populations</li>
</ul>
<p><strong>Python Tools and Workflow:</strong></p>
<ul>
<li><code>pandas</code> handles data loading, manipulation, and descriptive statistics</li>
<li><code>statsmodels.formula.api.ols()</code> estimates OLS regression models with R-style formula syntax</li>
<li><code>matplotlib</code> creates publication-quality scatter plots and visualizations</li>
<li>Standard workflow: load data → explore descriptively → visualize → model → interpret → validate</li>
<li>Random seeds ensure reproducibility of results across different runs</li>
</ul>
<p><strong>Prerequisites and Mathematical Background:</strong></p>
<ul>
<li>Summation notation (Σ) expresses formulas concisely and appears throughout econometrics</li>
<li>Calculus concepts (derivatives, rates of change) help understand marginal effects but are not essential</li>
<li>Expected values (E[X]) define population parameters like means and variances</li>
<li>“Learning-by-doing” is the most effective approach: practice with real data and software is essential for mastery</li>
</ul>
<hr>
<p><strong>Next Steps:</strong></p>
<ul>
<li><strong>Chapter 2</strong>: Univariate data summary (describing single variables)</li>
<li><strong>Chapter 3</strong>: The sample mean and sampling distributions</li>
<li><strong>Chapter 4</strong>: Statistical inference for the mean (confidence intervals, hypothesis tests)</li>
<li><strong>Chapters 5-7</strong>: Deep dive into bivariate regression (extending what we learned here)</li>
</ul>
<p><strong>You have now mastered:</strong> Loading and exploring economic data in Python Creating scatter plots to visualize relationships Estimating simple linear regression models with OLS Interpreting regression coefficients economically Understanding the limitations of regression analysis</p>
<p>These foundational concepts are the building blocks for all of econometrics. Everything that follows builds on this introduction!</p>
</section>
<section id="practice-exercises" class="level2">
<h2 class="anchored" data-anchor-id="practice-exercises">Practice Exercises</h2>
<p>Test your understanding of regression analysis with these exercises:</p>
<p><strong>Exercise 1:</strong> Conceptual understanding</p>
<ul>
<li><ol type="a">
<li>What is the difference between descriptive analysis and statistical inference?</li>
</ol></li>
<li><ol start="2" type="a">
<li>Why do economists primarily use observational data rather than experimental data?</li>
</ol></li>
<li><ol start="3" type="a">
<li>Name the three main types of data collection methods and give an example of each.</li>
</ol></li>
</ul>
<p><strong>Exercise 2:</strong> Data types</p>
<ul>
<li>Classify each of the following as continuous numerical, discrete numerical, or categorical:
<ul>
<li><ol type="a">
<li>Annual household income</li>
</ol></li>
<li><ol start="2" type="a">
<li>Number of children in a family</li>
</ol></li>
<li><ol start="3" type="a">
<li>Employment status (employed, unemployed, not in labor force)</li>
</ol></li>
<li><ol start="4" type="a">
<li>Temperature in degrees Celsius</li>
</ol></li>
</ul></li>
</ul>
<p><strong>Exercise 3:</strong> Regression interpretation</p>
<ul>
<li>Suppose you estimate: earnings = 20,000 + 5,000 × education
<ul>
<li><ol type="a">
<li>Interpret the intercept coefficient</li>
</ol></li>
<li><ol start="2" type="a">
<li>Interpret the slope coefficient</li>
</ol></li>
<li><ol start="3" type="a">
<li>Predict earnings for someone with 16 years of education</li>
</ol></li>
<li><ol start="4" type="a">
<li>What is the predicted difference in earnings between someone with 12 vs.&nbsp;16 years of education?</li>
</ol></li>
</ul></li>
</ul>
<p><strong>Exercise 4:</strong> Using our house price model</p>
<ul>
<li>Using the regression equation: price = 115,017 + 73.77 × size
<ul>
<li><ol type="a">
<li>Predict the price for a 1,800 sq ft house</li>
</ol></li>
<li><ol start="2" type="a">
<li>Predict the price for a 2,500 sq ft house</li>
</ol></li>
<li><ol start="3" type="a">
<li>What is the predicted price difference between these two houses?</li>
</ol></li>
<li><ol start="4" type="a">
<li>Is the intercept economically meaningful in this context? Why or why not?</li>
</ol></li>
</ul></li>
</ul>
<p><strong>Exercise 5:</strong> Critical thinking about causation</p>
<ul>
<li>Our regression shows larger houses have higher prices. Does this mean:
<ul>
<li><ol type="a">
<li>Adding square footage to a house will increase its value by $73.77 per sq ft?</li>
</ol></li>
<li><ol start="2" type="a">
<li>What other factors might be correlated with both house size and price?</li>
</ol></li>
<li><ol start="3" type="a">
<li>How would you design a study to establish a causal relationship?</li>
</ol></li>
</ul></li>
</ul>
<p><strong>Exercise 6:</strong> R-squared interpretation</p>
<ul>
<li>Our model has R² = 0.6175 (61.75%)
<ul>
<li><ol type="a">
<li>What does this number tell us about our model?</li>
</ol></li>
<li><ol start="2" type="a">
<li>What factors might explain the remaining 38.25% of variation in prices?</li>
</ol></li>
<li><ol start="3" type="a">
<li>Would R² = 1.0 be realistic for real-world economic data? Why or why not?</li>
</ol></li>
</ul></li>
</ul>
<p><strong>Exercise 7:</strong> Summation notation</p>
<ul>
<li>Calculate: <span class="math inline">\(\sum_{i=1}^{4} (3 + 2i)\)</span></li>
<li>Show all steps in your calculation</li>
</ul>
<p><strong>Exercise 8:</strong> Python practice</p>
<ul>
<li>Load the house dataset and:
<ul>
<li><ol type="a">
<li>Calculate the correlation between price and bedrooms</li>
</ol></li>
<li><ol start="2" type="a">
<li>Create a scatter plot of price vs.&nbsp;bedrooms</li>
</ol></li>
<li><ol start="3" type="a">
<li>Estimate the regression: price ~ bedrooms</li>
</ol></li>
<li><ol start="4" type="a">
<li>Compare the R² to our size regression. Which predictor is better?</li>
</ol></li>
</ul></li>
</ul>
<hr>
</section>
<section id="case-studies" class="level2">
<h2 class="anchored" data-anchor-id="case-studies">Case Studies</h2>
<p>Now let’s apply what you’ve learned to real economic research! In this section, you’ll explore data from actual published studies, using the same tools and techniques from this chapter.</p>
<p><strong>Why case studies matter:</strong></p>
<ul>
<li>See how regression analysis is used in real research</li>
<li>Practice applying Chapter 1 tools to authentic data</li>
<li>Develop intuition for economic relationships</li>
<li>Bridge the gap between textbook examples and research practice</li>
</ul>
<section id="case-study-1-economic-convergence-clubs" class="level3">
<h3 class="anchored" data-anchor-id="case-study-1-economic-convergence-clubs">Case Study 1: Economic Convergence Clubs</h3>
<p><strong>Research Question</strong>: Do countries converge toward similar levels of economic development, or do they form distinct “convergence clubs” with different trajectories?</p>
<p><strong>Background</strong>: Traditional economic theory suggests that poor countries should grow faster than rich countries, eventually “catching up” in terms of income and productivity. This is called the convergence hypothesis. However, empirical evidence shows a more complex picture: countries may form distinct groups (clubs) that converge toward different long-run equilibrium levels rather than a single global level.</p>
<p><strong>This Research</strong> (<a href="https://github.com/quarcs-lab/mendez2020-convergence-clubs-code-data">Mendez, 2020</a>): Uses modern econometric methods to identify convergence clubs in labor productivity across countries. The analysis examines whether countries follow one common development path or multiple distinct paths, and what factors (capital accumulation, technology, institutions) drive these patterns.</p>
<p><strong>The Data</strong>: Panel dataset tracking multiple countries over several years, with 26 variables including:</p>
<ul>
<li><strong>Output measures</strong>: GDP, GDP per capita</li>
<li><strong>Productivity</strong>: Labor productivity, total factor productivity (TFP)</li>
<li><strong>Capital</strong>: Physical capital stock, capital per worker</li>
<li><strong>Human capital</strong>: Years of schooling, human capital index</li>
<li><strong>Classifications</strong>: Country codes, regions, income groups</li>
</ul>
<p><strong>Your Task</strong>: Use the descriptive analysis and regression tools from Chapter 1 to explore patterns in the convergence clubs data. You’ll investigate productivity gaps, visualize relationships, and begin to understand why some countries develop differently than others.</p>
<blockquote class="blockquote">
<p><strong>Key Concept 1.7: Economic Convergence and Productivity Drivers</strong></p>
<p><strong>Beta convergence</strong> refers to the hypothesis that poor countries will grow faster than rich countries, eventually “catching up” in terms of income and productivity. However, evidence suggests countries may form distinct <strong>convergence clubs</strong>—groups that converge toward different long-run equilibrium levels rather than a single global level.</p>
<p>Labor productivity (output per worker) depends on <strong>capital accumulation</strong> (capital per worker) and <strong>aggregate efficiency</strong> (total factor productivity or TFP). The regression of productivity on capital captures this association, allowing us to quantify how much of cross-country productivity differences are explained by capital versus efficiency factors.</p>
</blockquote>
<section id="load-the-convergence-clubs-data" class="level4">
<h4 class="anchored" data-anchor-id="load-the-convergence-clubs-data">Load the Convergence Clubs Data</h4>
<p>Let’s load two datasets:</p>
<ol type="1">
<li><strong>Main dataset</strong> (<code>dat.csv</code>): Country-year panel data with economic variables</li>
<li><strong>Data dictionary</strong> (<code>dat-definitions.csv</code>): Explains what each variable means</li>
</ol>
<p>The data uses a <strong>multi-index</strong> structure with (country, year) pairs, allowing us to track each country over time.</p>
<div class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import data with sorted multi-index</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>df1 <span class="op">=</span> pd.read_csv(</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"https://raw.githubusercontent.com/quarcs-lab/mendez2020-convergence-clubs-code-data/master/assets/dat.csv"</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    index_col<span class="op">=</span>[<span class="st">"country"</span>, <span class="st">"year"</span>]</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>).sort_index()</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Import data dictionary</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>df2 <span class="op">=</span> pd.read_csv(</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"https://raw.githubusercontent.com/quarcs-lab/mendez2020-convergence-clubs-code-data/master/assets/dat-definitions.csv"</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Display basic information</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"CONVERGENCE CLUBS DATASET"</span>)</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Dataset shape: </span><span class="sc">{</span>df1<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> observations (country-year pairs), </span><span class="sc">{</span>df1<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> variables"</span>)</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Countries: </span><span class="sc">{</span><span class="bu">len</span>(df1.index.get_level_values(<span class="st">'country'</span>).unique())<span class="sc">}</span><span class="ss"> unique countries"</span>)</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Years: </span><span class="sc">{</span>df1<span class="sc">.</span>index<span class="sc">.</span>get_level_values(<span class="st">'year'</span>)<span class="sc">.</span><span class="bu">min</span>()<span class="sc">}</span><span class="ss"> to </span><span class="sc">{</span>df1<span class="sc">.</span>index<span class="sc">.</span>get_level_values(<span class="st">'year'</span>)<span class="sc">.</span><span class="bu">max</span>()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span> <span class="op">+</span> <span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"FIRST 5 OBSERVATIONS"</span>)</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df1.head(<span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
CONVERGENCE CLUBS DATASET
======================================================================
Dataset shape: 2700 observations (country-year pairs), 27 variables

Countries: 108 unique countries
Years: 1990 to 2014

======================================================================
FIRST 5 OBSERVATIONS
======================================================================
              id          Y      K       pop         L         s  alpha_it  \
country year                                                                 
Albania 1990   1  12449.999  31217  3.281453  1.250096  8.497386       NaN   
        1991   1  11310.000  30082  3.275438  1.243719  8.442703       NaN   
        1992   1  10122.000  28968  3.240613  0.993492  8.388020       NaN   
        1993   1  11636.000  29010  3.189623  0.935928  8.333337       NaN   
        1994   1  13120.000  29634  3.140634  1.008687  8.278653       NaN   

                  GDPpc          lp         h  ...  log_h_raw  log_tfp_raw  \
country year                                   ...                           
Albania 1990  3794.0508   9959.2344  3.165140  ...   1.152197     5.560511   
        1991  3452.9731   9093.6943  3.150347  ...   1.147513     5.479933   
        1992  3123.4832  10188.3060  3.135588  ...   1.142817     5.457089   
        1993  3648.0798  12432.5870  3.120863  ...   1.138110     5.617254   
        1994  4177.5005  13007.0080  3.106171  ...   1.133391     5.707116   

              log_GDPpc    log_lp    log_ky     log_h   log_tfp  isocode  \
country year                                                               
Albania 1990   8.130327  9.209681  0.880770  1.125790  5.541879      ALB   
        1991   8.170837  9.268303  0.869605  1.133772  5.574306      ALB   
        1992   8.211625  9.326916  0.858536  1.141821  5.606780      ALB   
        1993   8.252907  9.385130  0.847930  1.150036  5.639110      ALB   
        1994   8.294488  9.442308  0.838639  1.158521  5.670734      ALB   

              hi1990  region  
country year                  
Albania 1990      no  Europe  
        1991      no  Europe  
        1992      no  Europe  
        1993      no  Europe  
        1994      no  Europe  

[5 rows x 27 columns]</code></pre>
</div>
</div>
<div class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span> <span class="op">+</span> <span class="st">"="</span> <span class="op">*</span> <span class="dv">75</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"VARIABLE DEFINITIONS"</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">75</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===========================================================================
VARIABLE DEFINITIONS
===========================================================================
         var_name                                            var_def     type
0         country               Standardized country name (from PWT)    cs_id
1            year                                               Year    ts_id
2               Y                                                GDP  numeric
3               K                                   Physical Capital  numeric
4             pop                                         Population  numeric
5               L                                        Labor Force  numeric
6               s                                 Years of Schooling  numeric
7        alpha_it                             Variable Capital Share  numeric
8           GDPpc                                     GDP per capita  numeric
9              lp                                 Labor Productivity  numeric
10              h                                Human Capital Index  numeric
11             kl                                 Capital per Worker  numeric
12             kp                               Capital Productivity  numeric
13             ky                               Capital-Output Ratio  numeric
14            TFP                               Aggregate Efficiency  numeric
15  log_GDPpc_raw                              Log of GDP per capita  numeric
16     log_lp_raw                          Log of Labor Productivity  numeric
17     log_ky_raw                        Log of Capital-Output Ratio  numeric
18      log_h_raw                               Log of Human Capital  numeric
19    log_tfp_raw                   Log of Total Factor Productivity  numeric
20      log_GDPpc             Trend (HP400) of log of GDP per capita  numeric
21         log_lp         Trend (HP400) of log of labor productivity  numeric
22         log_ky       Trend (HP400) of log of Capital-Output Ratio  numeric
23          log_h              Trend (HP400) of log of Human Capital  numeric
24        log_tfp       Trend (HP400) of log of Aggregate Efficiency  numeric
25         region          Regional group (Classification of the UN)   factor
26         hi1990  High income country (as of 1990, World Bank cl...   factor
27        isocode                           ISO code from the PWT9.0   factor</code></pre>
</div>
</div>
</section>
<section id="task-1-data-exploration-guided" class="level4">
<h4 class="anchored" data-anchor-id="task-1-data-exploration-guided">Task 1: Data Exploration (Guided)</h4>
<p><strong>Objective</strong>: Understand the dataset structure and available variables.</p>
<p><strong>Instructions</strong>:</p>
<ol type="1">
<li>Examine the output above to understand the multi-index (country, year) structure</li>
<li>Review the data dictionary to identify key productivity variables</li>
<li>Check for missing values in key variables</li>
<li>Identify the variable names you’ll use for subsequent analyses</li>
</ol>
<p><strong>Key variables to focus on</strong> (check exact names in the data dictionary):</p>
<ul>
<li>Labor productivity variables</li>
<li>Capital per worker variables</li>
<li>GDP per capita measures</li>
<li>Country classification variables (region, income group)</li>
</ul>
<p>Run the code above and study the output. What patterns do you notice? How many time periods does each country have?</p>
<div class="cell" data-execution_count="51">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Your code here: Explore the dataset structure</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Suggested explorations:</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Check column names: df1.columns.tolist()</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Check for missing values: df1.isnull().sum()</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Examine a specific country's data</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Count observations per country</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Example: Examine USA's data</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="co"># df1.loc['USA']</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-2-descriptive-statistics-semi-guided" class="level4">
<h4 class="anchored" data-anchor-id="task-2-descriptive-statistics-semi-guided">Task 2: Descriptive Statistics (Semi-guided)</h4>
<p><strong>Objective</strong>: Generate summary statistics for key productivity variables.</p>
<p><strong>Instructions</strong>:</p>
<ol type="1">
<li>Select 3-4 key variables related to productivity and capital</li>
<li>Generate descriptive statistics (mean, median, std, min, max)</li>
<li>Identify countries with highest and lowest productivity levels</li>
<li>Calculate the productivity gap between top and bottom performers</li>
</ol>
<p><strong>Apply what you learned in sections 1.4</strong>: Use <code>.describe()</code> method like we did with the house price data.</p>
<p><strong>Hint</strong>: You’ll need to identify the exact variable names from the data dictionary. Look for variables measuring labor productivity, GDP per capita, or capital per worker.</p>
<div class="cell" data-execution_count="52">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Your code here: Generate descriptive statistics</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Steps:</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Identify variable names from data dictionary (check df2)</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Select key variables from df1</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Generate summary statistics using .describe()</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Find countries with max/min values using .idxmax() and .idxmin()</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. Calculate gaps between high and low performers</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Example structure:</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="co"># key_vars = ['variable1', 'variable2', 'variable3']  # Replace with actual names</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="co"># df1[key_vars].describe()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p><strong>Key Concept 1.8: Panel Data Structure</strong></p>
<p>Panel data combines cross-section and time series dimensions, tracking multiple entities (countries) over multiple time periods (years). This structure allows us to study both differences between countries (cross-sectional variation) and changes within countries over time (time series variation). The data is indexed by (country, year) pairs.</p>
</blockquote>
</section>
<section id="task-3-visualizing-productivity-patterns-semi-guided" class="level4">
<h4 class="anchored" data-anchor-id="task-3-visualizing-productivity-patterns-semi-guided">Task 3: Visualizing Productivity Patterns (Semi-guided)</h4>
<p><strong>Objective</strong>: Create scatter plots to visualize productivity relationships.</p>
<p><strong>Instructions</strong>:</p>
<ol type="1">
<li>Create a scatter plot comparing two productivity-related variables</li>
<li>Add appropriate axis labels and a descriptive title</li>
<li>Optionally: Color-code points by region or income group</li>
<li>Interpret the pattern you observe</li>
</ol>
<p><strong>Apply what you learned in section 1.5</strong>: Use matplotlib to create scatter plots like the house price visualization.</p>
<p><strong>Suggested relationships to explore</strong>:</p>
<ul>
<li>GDP per capita vs.&nbsp;labor productivity</li>
<li>Capital per worker vs.&nbsp;labor productivity</li>
<li>Human capital vs.&nbsp;GDP per capita</li>
</ul>
<div class="cell" data-execution_count="53">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Your code here: Create scatter plot</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Steps:</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Prepare data (select variables, remove missing values)</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Create figure and axis: fig, ax = plt.subplots(figsize=(10, 6))</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Create scatter plot: ax.scatter(x, y, ...)</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Add labels, title, and formatting</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. Display and interpret</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Example structure:</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="co"># plot_data = df1[['var_x', 'var_y']].dropna()</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="co"># fig, ax = plt.subplots(figsize=(10, 6))</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="co"># ax.scatter(plot_data['var_x'], plot_data['var_y'], alpha=0.6)</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="co"># ax.set_xlabel('Variable X')</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a><span class="co"># ax.set_ylabel('Variable Y')</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a><span class="co"># plt.show()</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a><span class="co"># What pattern do you observe? Positive or negative relationship?</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-4-time-series-exploration-more-independent" class="level4">
<h4 class="anchored" data-anchor-id="task-4-time-series-exploration-more-independent">Task 4: Time Series Exploration (More Independent)</h4>
<p><strong>Objective</strong>: Examine productivity trends over time for specific countries.</p>
<p><strong>Instructions</strong>:</p>
<ol type="1">
<li>Select 2-3 countries of interest (e.g., USA, China, India, Japan, or countries from your region)</li>
<li>Plot labor productivity over time for each country</li>
<li>Compare their trajectories: Which countries are growing faster?</li>
<li>Calculate the average annual growth rate (optional: percentage change per year)</li>
</ol>
<p><strong>Hint</strong>: Remember that panel data is indexed by (country, year). Use <code>.loc[country]</code> to filter data for a specific country.</p>
<p><strong>Questions to answer</strong>:</p>
<ul>
<li>Are productivity levels converging (getting closer) or diverging (spreading apart)?</li>
<li>Which country experienced the fastest productivity growth?</li>
<li>Do you see evidence of convergence clubs (groups following similar paths)?</li>
</ul>
<div class="cell" data-execution_count="54">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Your code here: Time series plots</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Steps:</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Select countries (e.g., countries = ['USA', 'CHN', 'JPN'])</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. For each country, extract time series data</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Create line plot over time</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Compare trajectories</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Example structure:</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="co"># countries = ['USA', 'CHN', 'IND']  # Adjust based on actual country codes</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="co"># fig, ax = plt.subplots(figsize=(10, 6))</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a><span class="co"># for country in countries:</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a><span class="co">#     country_data = df1.loc[country]</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a><span class="co">#     ax.plot(country_data.index, country_data['productivity_var'], label=country)</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a><span class="co"># ax.set_xlabel('Year')</span></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a><span class="co"># ax.set_ylabel('Labor Productivity')</span></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a><span class="co"># ax.legend()</span></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a><span class="co"># plt.show()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-5-simple-regression-analysis-independent" class="level4">
<h4 class="anchored" data-anchor-id="task-5-simple-regression-analysis-independent">Task 5: Simple Regression Analysis (INDEPENDENT)</h4>
<p><strong>Objective</strong>: Estimate the relationship between capital and productivity.</p>
<p><strong>Research Question</strong>: Does higher capital per worker lead to higher labor productivity?</p>
<p><strong>Instructions</strong>:</p>
<ol type="1">
<li>Prepare regression data (select variables, remove missing values)</li>
<li>Estimate OLS regression: <code>labor_productivity ~ capital_per_worker</code></li>
<li>Display the regression summary</li>
<li>Interpret the slope coefficient economically</li>
<li>Report the R-squared value</li>
<li><strong>Critical thinking</strong>: Discuss whether this is association or causation</li>
</ol>
<p><strong>Apply what you learned in sections 1.6-1.7</strong>: Use <code>ols()</code> from statsmodels and interpret coefficients.</p>
<p><strong>Important questions</strong>:</p>
<ul>
<li>What does the slope coefficient tell us?</li>
<li>Could there be omitted variables affecting both capital and productivity?</li>
<li>Could reverse causality be a concern (does higher productivity lead to more capital accumulation)?</li>
</ul>
<div class="cell" data-execution_count="55">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Your code here: Regression analysis</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Steps:</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Prepare data: reg_data = df1[['productivity_var', 'capital_var']].dropna()</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Reset index if needed: reg_data = reg_data.reset_index()</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Estimate regression: model = ols('productivity_var ~ capital_var', data=reg_data).fit()</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Display summary: print(model.summary())</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. Extract and interpret coefficients</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Example structure:</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="co"># from statsmodels.formula.api import ols</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a><span class="co"># reg_data = df1[['var_y', 'var_x']].dropna().reset_index()</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a><span class="co"># model = ols('var_y ~ var_x', data=reg_data).fit()</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a><span class="co"># print(model.summary())</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Interpretation:</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Slope = ___: For every unit increase in capital per worker, </span></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a><span class="co">#               labor productivity increases by ___ units</span></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a><span class="co"># R² = ___: Capital explains ___% of variation in productivity</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-6-comparative-analysis-independent" class="level4">
<h4 class="anchored" data-anchor-id="task-6-comparative-analysis-independent">Task 6: Comparative Analysis (Independent)</h4>
<p><strong>Objective</strong>: Compare productivity patterns between country groups.</p>
<p><strong>Research Question</strong>: Does the capital-productivity relationship differ between high-income and developing countries?</p>
<p><strong>Instructions</strong>:</p>
<ol type="1">
<li>If the data has an income group variable, group countries by income level</li>
<li>Calculate average productivity and capital for each group</li>
<li>Create comparative scatter plots (one color per group)</li>
<li>(Advanced) Run separate regressions for each group</li>
<li>Compare the slope coefficients: Is the relationship stronger in one group?</li>
</ol>
<p><strong>This extends Chapter 1 concepts</strong>: You’re using grouping and comparative analysis to see if relationships vary across subsamples.</p>
<p><strong>Questions to explore</strong>:</p>
<ul>
<li>Do high-income countries have uniformly higher productivity?</li>
<li>Is the capital-productivity relationship steeper in developing countries?</li>
<li>What might explain differences between groups?</li>
</ul>
<div class="cell" data-execution_count="56">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Your code here: Comparative analysis</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Steps:</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Identify grouping variable (income level, region, etc.)</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Group data: df1.groupby('group_var').mean()</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Create comparative visualizations</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Run regressions by group (optional)</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Example structure for comparative scatter plot:</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="co"># fig, ax = plt.subplots(figsize=(10, 6))</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="co"># for group in df1['group_var'].unique():</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="co">#     group_data = df1[df1['group_var'] == group]</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="co">#     ax.scatter(group_data['var_x'], group_data['var_y'], label=group, alpha=0.6)</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a><span class="co"># ax.set_xlabel('Capital per Worker')</span></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a><span class="co"># ax.set_ylabel('Labor Productivity')</span></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a><span class="co"># ax.legend()</span></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a><span class="co"># plt.show()</span></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Advanced: Separate regressions</span></span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a><span class="co"># for group in groups:</span></span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a><span class="co">#     group_data = df1[df1['group_var'] == group].dropna()</span></span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a><span class="co">#     model = ols('var_y ~ var_x', data=group_data).fit()</span></span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a><span class="co">#     print(f"\n{group}: Slope = {model.params['var_x']:.4f}, R² = {model.rsquared:.4f}")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="what-youve-learned-from-this-case-study" class="level4">
<h4 class="anchored" data-anchor-id="what-youve-learned-from-this-case-study">What You’ve Learned from This Case Study</h4>
<p>Through this hands-on exploration of economic convergence data, you’ve applied all the core Chapter 1 tools:</p>
<ul>
<li><strong>Data loading and exploration</strong>: Worked with real panel data from research</li>
<li><strong>Descriptive statistics</strong>: Summarized productivity patterns across countries</li>
<li><strong>Visualization</strong>: Created scatter plots and time series to reveal relationships</li>
<li><strong>Regression analysis</strong>: Quantified the capital-productivity relationship</li>
<li><strong>Critical thinking</strong>: Distinguished association from causation</li>
<li><strong>Comparative analysis</strong>: Explored differences between country groups</li>
</ul>
<p><strong>Connection to the research</strong>: The patterns you’ve discovered—productivity gaps, the role of capital, differences between country groups—are the empirical motivation for the convergence clubs analysis in Mendez (2020). The full research uses advanced methods (covered in later chapters) to formally identify clubs and test convergence hypotheses.</p>
<p><strong>Looking ahead</strong>:</p>
<ul>
<li><strong>Chapter 2</strong> will teach you more sophisticated descriptive analysis for univariate data</li>
<li><strong>Chapter 3-4</strong> cover statistical inference, allowing you to test hypotheses formally</li>
<li><strong>Chapter 5-9</strong> extend regression analysis to multiple predictors and transformations</li>
<li><strong>Chapter 10-17</strong> introduce advanced methods like panel data regression—perfect for convergence clubs!</li>
</ul>
<hr>
<p><strong>Great work!</strong> You’ve completed Chapter 1 and applied your new skills to real economic research. Continue to Chapter 2 to learn more about data summary and distributions.</p>
</section>
</section>
<section id="case-study-2-can-satellites-see-poverty-predicting-local-development-in-bolivia" class="level3">
<h3 class="anchored" data-anchor-id="case-study-2-can-satellites-see-poverty-predicting-local-development-in-bolivia">Case Study 2: Can Satellites See Poverty? Predicting Local Development in Bolivia</h3>
<p><strong>Research Question</strong>: Can satellite data—nighttime lights and satellite image embeddings—predict local economic development across Bolivia’s municipalities?</p>
<p><strong>Background</strong>: Monitoring progress toward the United Nations Sustainable Development Goals (SDGs) requires timely, granular data on economic conditions. However, many developing countries lack comprehensive municipality-level statistics. Recent advances in remote sensing and machine learning offer a promising alternative: using satellite data to <em>predict</em> local development outcomes.</p>
<p>Two types of satellite data have proven particularly useful:</p>
<ol type="1">
<li><p><strong>Nighttime lights (NTL)</strong>: Satellite images of Earth at night reveal the intensity of artificial lighting. Brighter areas typically correspond to greater economic activity, electrification, and urbanization. NTL data is available globally and annually, making it a powerful proxy for economic development in data-scarce regions (<a href="https://doi.org/10.1257/aer.102.2.994">Henderson et al., 2012</a>).</p></li>
<li><p><strong>Satellite image embeddings</strong>: Deep learning models trained on daytime satellite imagery (Sentinel-2, Landsat) can extract 64-dimensional feature vectors that capture visual patterns—road networks, building density, vegetation cover, agricultural activity—without requiring manual labeling. These abstract features often correlate strongly with socioeconomic outcomes (<a href="https://doi.org/10.1126/science.aaf7894">Jean et al., 2016</a>).</p></li>
</ol>
<p><strong>This Research</strong> (<a href="https://github.com/quarcs-lab/ds4bolivia">DS4Bolivia Project</a>): A comprehensive data science initiative that integrates satellite data with Bolivia’s Municipal SDG Atlas (<a href="https://atlas.sdsnbolivia.org">Andersen et al., 2020</a>) to study geospatial development patterns across all <strong>339 municipalities</strong>. The project demonstrates how machine learning models can predict SDG indicators from satellite features, achieving meaningful predictive accuracy for poverty and energy access indicators.</p>
<p><strong>The Data</strong>: Cross-sectional dataset covering 339 Bolivian municipalities with over 350 variables, including:</p>
<ul>
<li><strong>Development outcomes</strong>: Municipal Sustainable Development Index (IMDS, 0-100 composite), individual SDG indices (SDG 1-17)</li>
<li><strong>Satellite data</strong>: Log nighttime lights per capita (2012-2020), 64 satellite embedding dimensions (2017)</li>
<li><strong>Demographics</strong>: Population (2001-2020), municipality and department names</li>
<li><strong>Socioeconomic indicators</strong>: Unsatisfied basic needs, literacy rates, electricity coverage, health outcomes</li>
</ul>
<p><strong>Your Task</strong>: Use the descriptive analysis and regression tools from Chapter 1 to explore the DS4Bolivia dataset. You’ll investigate whether nighttime lights predict municipal development, visualize satellite-development relationships, and begin to assess how useful remote sensing data is for SDG monitoring. This case study introduces a dataset that we will revisit throughout the textbook, applying increasingly sophisticated econometric methods in each chapter.</p>
<blockquote class="blockquote">
<p><strong>Key Concept 1.9: Satellite Data as Economic Proxy</strong></p>
<p><strong>Nighttime lights (NTL)</strong> captured by satellites measure the intensity of artificial illumination on Earth’s surface. Because lighting requires electricity and economic activity, NTL intensity strongly correlates with GDP, income levels, and urbanization. The log of NTL per capita transforms the highly skewed raw luminosity into a more symmetric variable suitable for regression analysis.</p>
<p><strong>Satellite embeddings</strong> are 64-dimensional feature vectors extracted by deep learning models from daytime satellite imagery. Each dimension captures abstract visual patterns (building density, road networks, vegetation) that correlate with socioeconomic conditions. Together, NTL and embeddings provide complementary information: NTL captures <em>nighttime economic activity</em> while embeddings capture <em>daytime physical infrastructure</em>.</p>
</blockquote>
<section id="load-the-ds4bolivia-data" class="level4">
<h4 class="anchored" data-anchor-id="load-the-ds4bolivia-data">Load the DS4Bolivia Data</h4>
<p>Let’s load the comprehensive DS4Bolivia dataset directly from GitHub. This dataset integrates satellite data, SDG indicators, and demographic information for all 339 Bolivian municipalities.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the DS4Bolivia dataset</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>url_bol <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/quarcs-lab/ds4bolivia/master/ds4bolivia_v20250523.csv"</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>bol <span class="op">=</span> pd.read_csv(url_bol)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Display basic information</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"DS4BOLIVIA DATASET"</span>)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Dataset shape: </span><span class="sc">{</span>bol<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> municipalities, </span><span class="sc">{</span>bol<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> variables"</span>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Departments: </span><span class="sc">{</span>bol[<span class="st">'dep'</span>]<span class="sc">.</span>nunique()<span class="sc">}</span><span class="ss"> unique departments"</span>)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Department names: </span><span class="sc">{</span><span class="bu">sorted</span>(bol[<span class="st">'dep'</span>].unique())<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Select key variables for this case study</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>key_vars <span class="op">=</span> [<span class="st">'mun'</span>, <span class="st">'dep'</span>, <span class="st">'imds'</span>, <span class="st">'ln_NTLpc2017'</span>, <span class="st">'pop2017'</span>,</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>            <span class="st">'index_sdg1'</span>, <span class="st">'index_sdg4'</span>, <span class="st">'index_sdg8'</span>, <span class="st">'sdg1_1_ubn'</span>]</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>bol_key <span class="op">=</span> bol[key_vars].copy()</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Key variables selected: </span><span class="sc">{</span><span class="bu">len</span>(key_vars)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span> <span class="op">+</span> <span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"FIRST 10 MUNICIPALITIES"</span>)</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(bol_key.head(<span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Variable descriptions for this case study</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"KEY VARIABLE DESCRIPTIONS"</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>descriptions <span class="op">=</span> {</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'mun'</span>: <span class="st">'Municipality name'</span>,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'dep'</span>: <span class="st">'Department (administrative region, 9 total)'</span>,</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'imds'</span>: <span class="st">'Municipal Sustainable Development Index (0-100, composite of all SDGs)'</span>,</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'ln_NTLpc2017'</span>: <span class="st">'Log of nighttime lights per capita (2017, satellite-based)'</span>,</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'pop2017'</span>: <span class="st">'Population in 2017'</span>,</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'index_sdg1'</span>: <span class="st">'SDG 1 Index: No Poverty (0-100)'</span>,</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'index_sdg4'</span>: <span class="st">'SDG 4 Index: Quality Education (0-100)'</span>,</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">'index_sdg8'</span>: <span class="st">'SDG 8 Index: Decent Work and Economic Growth (0-100)'</span>,</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">'sdg1_1_ubn'</span>: <span class="st">'Unsatisfied Basic Needs (</span><span class="sc">% o</span><span class="st">f population, 2012)'</span>,</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> var, desc <span class="kw">in</span> descriptions.items():</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>var<span class="sc">:20s}</span><span class="ss"> — </span><span class="sc">{</span>desc<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-1-data-exploration-guided-1" class="level4">
<h4 class="anchored" data-anchor-id="task-1-data-exploration-guided-1">Task 1: Data Exploration (Guided)</h4>
<p><strong>Objective</strong>: Understand the DS4Bolivia dataset structure and key variables.</p>
<p><strong>Instructions</strong>:</p>
<ol type="1">
<li>Examine the output above: How many municipalities? How many departments?</li>
<li>Check for missing values in the key variables</li>
<li>Identify the range of the IMDS index (development measure)</li>
<li>Explore the distribution of departments (how many municipalities per department?)</li>
</ol>
<p><strong>Key variables to focus on</strong>:</p>
<ul>
<li><code>imds</code>: Overall development index (our main dependent variable)</li>
<li><code>ln_NTLpc2017</code>: Log nighttime lights per capita (our main predictor)</li>
<li><code>dep</code>: Department (for regional comparisons)</li>
<li><code>pop2017</code>: Population (for context)</li>
</ul>
<p>Run the code below to explore the data structure.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Your code here: Explore the DS4Bolivia dataset</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Suggested explorations:</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Check for missing values: bol_key.isnull().sum()</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Municipalities per department: bol_key['dep'].value_counts()</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Range of IMDS: bol_key['imds'].describe()</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Largest/smallest municipalities: bol_key.nlargest(5, 'pop2017')</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Example: Check missing values</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Missing values per variable:"</span>)</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(bol_key.isnull().<span class="bu">sum</span>())</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Total municipalities: </span><span class="sc">{</span><span class="bu">len</span>(bol_key)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Complete cases (no missing in key vars): </span><span class="sc">{</span>bol_key<span class="sc">.</span>dropna()<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-2-descriptive-statistics-guided" class="level4">
<h4 class="anchored" data-anchor-id="task-2-descriptive-statistics-guided">Task 2: Descriptive Statistics (Guided)</h4>
<p><strong>Objective</strong>: Generate summary statistics for key development and satellite variables.</p>
<p><strong>Instructions</strong>:</p>
<ol type="1">
<li>Calculate descriptive statistics for <code>imds</code>, <code>ln_NTLpc2017</code>, and <code>pop2017</code></li>
<li>Identify the municipality with the highest and lowest IMDS</li>
<li>Compare average IMDS across departments</li>
<li>Discuss what the summary statistics reveal about inequality across municipalities</li>
</ol>
<p><strong>Apply what you learned in section 1.4</strong>: Use <code>.describe()</code> and <code>.groupby()</code> methods like we did with the house price data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Your code here: Descriptive statistics for DS4Bolivia</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Steps:</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Summary statistics for key variables</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Identify top/bottom municipalities</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Compare departments</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Example: Summary statistics</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"DESCRIPTIVE STATISTICS: KEY VARIABLES"</span>)</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(bol_key[[<span class="st">'imds'</span>, <span class="st">'ln_NTLpc2017'</span>, <span class="st">'pop2017'</span>, <span class="st">'sdg1_1_ubn'</span>]].describe().<span class="bu">round</span>(<span class="dv">2</span>))</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Top and bottom municipalities by IMDS</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span> <span class="op">+</span> <span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"TOP 5 MUNICIPALITIES BY DEVELOPMENT (IMDS)"</span>)</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(bol_key.nlargest(<span class="dv">5</span>, <span class="st">'imds'</span>)[[<span class="st">'mun'</span>, <span class="st">'dep'</span>, <span class="st">'imds'</span>, <span class="st">'ln_NTLpc2017'</span>]].to_string(index<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span> <span class="op">+</span> <span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"BOTTOM 5 MUNICIPALITIES BY DEVELOPMENT (IMDS)"</span>)</span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span> <span class="op">*</span> <span class="dv">70</span>)</span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(bol_key.nsmallest(<span class="dv">5</span>, <span class="st">'imds'</span>)[[<span class="st">'mun'</span>, <span class="st">'dep'</span>, <span class="st">'imds'</span>, <span class="st">'ln_NTLpc2017'</span>]].to_string(index<span class="op">=</span><span class="va">False</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p><strong>Key Concept 1.10: Subnational Development Analysis</strong></p>
<p>National-level statistics can mask enormous variation in development outcomes within a country. Bolivia’s 339 municipalities span a wide range of development levels—from highly urbanized departmental capitals with strong infrastructure to remote rural communities with limited services. Municipality-level analysis reveals this <strong>within-country inequality</strong> and helps identify specific areas where SDG progress lags behind. Satellite data is particularly valuable for subnational analysis because it provides spatially granular measurements even where traditional surveys are scarce or infrequent.</p>
</blockquote>
</section>
<section id="task-3-visualize-the-ntl-development-relationship-semi-guided" class="level4">
<h4 class="anchored" data-anchor-id="task-3-visualize-the-ntl-development-relationship-semi-guided">Task 3: Visualize the NTL-Development Relationship (Semi-guided)</h4>
<p><strong>Objective</strong>: Create scatter plots to visualize the relationship between nighttime lights and development.</p>
<p><strong>Instructions</strong>:</p>
<ol type="1">
<li>Create a scatter plot of <code>ln_NTLpc2017</code> (x-axis) vs <code>imds</code> (y-axis)</li>
<li>Add appropriate axis labels and title</li>
<li>Optionally: Color-code points by department</li>
<li>Interpret the pattern: Is there a positive relationship? How strong does it look?</li>
</ol>
<p><strong>Apply what you learned in section 1.5</strong>: Use matplotlib to create scatter plots like the house price visualization.</p>
<p><strong>Hint</strong>: Drop missing values before plotting with <code>.dropna()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Your code here: Scatter plot of NTL vs Development</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Steps:</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Prepare data (drop missing values)</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Create scatter plot</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Add labels and formatting</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Interpret the pattern</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Example structure:</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="co"># plot_data = bol_key[['ln_NTLpc2017', 'imds']].dropna()</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="co"># fig, ax = plt.subplots(figsize=(10, 6))</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a><span class="co"># ax.scatter(plot_data['ln_NTLpc2017'], plot_data['imds'], alpha=0.5, color='navy')</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a><span class="co"># ax.set_xlabel('Log Nighttime Lights per Capita (2017)')</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a><span class="co"># ax.set_ylabel('Municipal Development Index (IMDS)')</span></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a><span class="co"># ax.set_title('Can Satellites See Development? NTL vs IMDS in Bolivia')</span></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a><span class="co"># plt.show()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-4-simple-regression-analysis-semi-guided" class="level4">
<h4 class="anchored" data-anchor-id="task-4-simple-regression-analysis-semi-guided">Task 4: Simple Regression Analysis (Semi-guided)</h4>
<p><strong>Objective</strong>: Estimate the relationship between nighttime lights and development using OLS.</p>
<p><strong>Research Question</strong>: How much does nighttime light intensity predict municipal development levels?</p>
<p><strong>Instructions</strong>:</p>
<ol type="1">
<li>Prepare regression data (drop missing values in key variables)</li>
<li>Estimate OLS regression: <code>imds ~ ln_NTLpc2017</code></li>
<li>Display the regression summary</li>
<li>Interpret the slope coefficient: What does a 1-unit increase in log NTL mean for IMDS?</li>
<li>Report and interpret R-squared: How much variation in development does NTL explain?</li>
</ol>
<p><strong>Apply what you learned in sections 1.6-1.7</strong>: Use <code>ols()</code> from statsmodels.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Your code here: OLS regression of IMDS on NTL</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Steps:</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Prepare data</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Estimate regression</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Display and interpret results</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Example structure:</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="co"># reg_data = bol_key[['imds', 'ln_NTLpc2017']].dropna()</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="co"># model_bol = ols('imds ~ ln_NTLpc2017', data=reg_data).fit()</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="co"># print(model_bol.summary())</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="co"># # Extract key statistics</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a><span class="co"># print(f"\nSlope: {model_bol.params['ln_NTLpc2017']:.4f}")</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a><span class="co"># print(f"R-squared: {model_bol.rsquared:.4f}")</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a><span class="co"># print(f"\nInterpretation: A 1-unit increase in log NTL per capita")</span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a><span class="co"># print(f"is associated with a {model_bol.params['ln_NTLpc2017']:.2f}-point increase in IMDS")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-5-regional-comparison-independent" class="level4">
<h4 class="anchored" data-anchor-id="task-5-regional-comparison-independent">Task 5: Regional Comparison (Independent)</h4>
<p><strong>Objective</strong>: Compare development and NTL patterns across Bolivia’s nine departments.</p>
<p><strong>Research Question</strong>: Do satellite-development patterns vary across Bolivia’s regions?</p>
<p><strong>Instructions</strong>:</p>
<ol type="1">
<li>Calculate mean IMDS and mean NTL by department</li>
<li>Create a bar chart or dot plot comparing department averages</li>
<li>Identify which departments are the most and least developed</li>
<li>Create scatter plots colored by department to see if the NTL-IMDS relationship differs by region</li>
<li>Discuss what might explain regional differences (geography, urbanization, economic structure)</li>
</ol>
<p><strong>This extends Chapter 1 concepts</strong>: You’re using grouping and comparative analysis to explore heterogeneity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Your code here: Regional comparison</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Steps:</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Group by department: bol_key.groupby('dep')[['imds', 'ln_NTLpc2017']].mean()</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Create comparative bar chart</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Create scatter plot colored by department</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Identify top/bottom departments</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Example structure:</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="co"># dept_means = bol_key.groupby('dep')[['imds', 'ln_NTLpc2017']].mean().sort_values('imds')</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a><span class="co"># print(dept_means.round(2))</span></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a><span class="co"># fig, ax = plt.subplots(figsize=(10, 6))</span></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a><span class="co"># dept_means['imds'].plot(kind='barh', ax=ax, color='purple', alpha=0.7)</span></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a><span class="co"># ax.set_xlabel('Mean IMDS')</span></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a><span class="co"># ax.set_title('Average Municipal Development by Department')</span></span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a><span class="co"># plt.tight_layout()</span></span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a><span class="co"># plt.show()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-6-policy-brief-on-satellite-data-for-sdg-monitoring-independent" class="level4">
<h4 class="anchored" data-anchor-id="task-6-policy-brief-on-satellite-data-for-sdg-monitoring-independent">Task 6: Policy Brief on Satellite Data for SDG Monitoring (Independent)</h4>
<p><strong>Objective</strong>: Write a 200-300 word policy brief summarizing your findings.</p>
<p><strong>Your brief should address</strong>:</p>
<ol type="1">
<li><strong>Key finding</strong>: What is the relationship between nighttime lights and municipal development in Bolivia?</li>
<li><strong>Magnitude</strong>: How strong is the association? What does the R-squared tell us about predictive power?</li>
<li><strong>Regional variation</strong>: Do some departments show higher development levels? Is there a geographic pattern?</li>
<li><strong>Policy implications</strong>: How could satellite data be used for SDG monitoring in Bolivia?</li>
<li><strong>Limitations</strong>: What can satellite data <em>not</em> tell us about development? What other data sources are needed?</li>
</ol>
<p><strong>Connection to Research</strong>: The DS4Bolivia project uses machine learning (Random Forest, XGBoost) to predict SDG indicators from satellite embeddings, achieving R² up to 0.57 for extreme energy poverty. Your simple OLS regression provides a baseline for understanding how much satellite data captures about development outcomes.</p>
<p><strong>Looking ahead</strong>: In subsequent chapters, we will revisit this dataset to:</p>
<ul>
<li>Summarize the distribution of development indicators (Chapter 2)</li>
<li>Test whether development differences are statistically significant (Chapter 4)</li>
<li>Explore bivariate relationships between NTL and specific SDG outcomes (Chapter 5)</li>
<li>Add multiple satellite features as predictors (Chapters 10-12)</li>
<li>Test for regional structural differences (Chapter 14)</li>
<li>Check model assumptions and diagnostics (Chapter 16)</li>
<li>Analyze NTL panel data over time (Chapter 17)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Your code here: Additional analysis for the policy brief</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co"># You might want to:</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Create a summary table of key results</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Generate a visualization that tells a compelling story</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Calculate specific statistics to cite in your brief</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Example: Summary of key results</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="co"># print("KEY RESULTS FOR POLICY BRIEF")</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="co"># print(f"Sample: {len(reg_data)} municipalities")</span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="co"># print(f"NTL coefficient: {model_bol.params['ln_NTLpc2017']:.2f}")</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a><span class="co"># print(f"R-squared: {model_bol.rsquared:.2%}")</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a><span class="co"># print(f"Most developed department: {dept_means['imds'].idxmax()}")</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a><span class="co"># print(f"Least developed department: {dept_means['imds'].idxmin()}")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="what-youve-learned-from-this-case-study-1" class="level4">
<h4 class="anchored" data-anchor-id="what-youve-learned-from-this-case-study-1">What You’ve Learned from This Case Study</h4>
<p>Through this exploration of satellite data and municipal development in Bolivia, you’ve applied the Chapter 1 toolkit to a cutting-edge research application:</p>
<ul>
<li><strong>Data loading and exploration</strong>: Worked with a real geospatial dataset covering 339 municipalities</li>
<li><strong>Descriptive statistics</strong>: Summarized development indicators and identified high/low performers</li>
<li><strong>Visualization</strong>: Created scatter plots revealing the satellite-development relationship</li>
<li><strong>Regression analysis</strong>: Quantified how nighttime lights predict development outcomes</li>
<li><strong>Regional comparison</strong>: Explored how the relationship varies across Bolivia’s departments</li>
<li><strong>Critical thinking</strong>: Assessed the potential and limitations of satellite data for SDG monitoring</li>
</ul>
<p><strong>Connection to the research</strong>: The DS4Bolivia project extends this simple analysis by incorporating 64-dimensional satellite embeddings and advanced machine learning methods. Your OLS baseline provides the foundation for understanding what these more complex models improve upon.</p>
<p><strong>This dataset returns throughout the textbook</strong>: Each subsequent chapter applies its specific econometric tools to the DS4Bolivia data, building progressively from univariate summaries (Chapter 2) through panel data analysis (Chapter 17). By the end of the book, you’ll have a comprehensive econometric analysis of satellite-based development prediction.</p>
<hr>
<p><strong>Well done!</strong> You’ve now explored two real-world datasets—cross-country convergence and Bolivian municipal development—using the fundamental tools of econometrics.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'alternate';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
          // default icon
          link.classList.add("external");
      }
    }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../index.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Preface</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../notebooks_colab/ch02_Univariate_Data_Summary.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-title">2. Univariate Data Summary</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script>
document.addEventListener('DOMContentLoaded', function() {
  var tocNav = document.getElementById('TOC');
  if (tocNav) {
    var coverDiv = document.createElement('div');
    coverDiv.id = 'toc-cover-image';
    var img = document.createElement('img');
    var path = window.location.pathname;
    if (path.indexOf('/notebooks_colab/') !== -1) {
      img.src = '../images/book1cover.jpg';
    } else {
      img.src = 'images/book1cover.jpg';
    }
    img.alt = 'Econometrics Powered by AI';
    coverDiv.appendChild(img);
    tocNav.parentNode.insertBefore(coverDiv, tocNav);
  }
});
</script>



<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>