<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Chapter 9: Models with Natural Logarithms – Econometrics Powered by AI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../notebooks_colab/ch10_Data_Summary_for_Multiple_Regression.html" rel="next">
<link href="../notebooks_colab/ch08_Case_Studies_for_Bivariate_Regression.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-27c261d06b905028a18691de25d09dde.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../custom.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../notebooks_colab/ch05_Bivariate_Data_Summary.html">Bivariate Regression</a></li><li class="breadcrumb-item"><a href="../notebooks_colab/ch09_Models_with_Natural_Logarithms.html"><span class="chapter-title">Chapter 9: Models with Natural Logarithms</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Econometrics Powered by AI</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch00_Preface.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Preface: Econometrics Powered by AI</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch01_Analysis_of_Economics_Data.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 1: Analysis of Economics Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch02_Univariate_Data_Summary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 2: Univariate Data Summary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch03_The_Sample_Mean.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 3: The Sample Mean</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch04_Statistical_Inference_for_the_Mean.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 4: Statistical Inference for the Mean</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Bivariate Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch05_Bivariate_Data_Summary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 5: Bivariate Data Summary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch06_The_Least_Squares_Estimator.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 6: The Least Squares Estimator</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch07_Statistical_Inference_for_Bivariate_Regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 7: Statistical Inference for Bivariate Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch08_Case_Studies_for_Bivariate_Regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 8: Case Studies for Bivariate Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch09_Models_with_Natural_Logarithms.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Chapter 9: Models with Natural Logarithms</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Multiple Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch10_Data_Summary_for_Multiple_Regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 10: Data Summary for Multiple Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch11_Statistical_Inference_for_Multiple_Regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 11: Statistical Inference for Multiple Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch12_Further_Topics_in_Multiple_Regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 12: Further Topics in Multiple Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch13_Case_Studies_for_Multiple_Regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 13: Case Studies for Multiple Regression</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Advanced Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch14_Regression_with_Indicator_Variables.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 14: Regression with Indicator Variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch15_Regression_with_Transformed_Variables.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 15: Regression with Transformed Variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch16_Checking_the_Model_and_Data.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 16: Checking the Model and Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks_colab/ch17_Panel_Data_Time_Series_Data_Causation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 17: Panel Data, Time Series Data, Causation</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#chapter-overview" id="toc-chapter-overview" class="nav-link active" data-scroll-target="#chapter-overview">Chapter Overview</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#natural-logarithm-function" id="toc-natural-logarithm-function" class="nav-link" data-scroll-target="#natural-logarithm-function">9.1 Natural Logarithm Function</a></li>
  <li><a href="#semi-elasticities-and-elasticities" id="toc-semi-elasticities-and-elasticities" class="nav-link" data-scroll-target="#semi-elasticities-and-elasticities">9.2 Semi-Elasticities and Elasticities</a>
  <ul class="collapse">
  <li><a href="#semi-elasticity" id="toc-semi-elasticity" class="nav-link" data-scroll-target="#semi-elasticity">Semi-Elasticity</a></li>
  <li><a href="#elasticity" id="toc-elasticity" class="nav-link" data-scroll-target="#elasticity">Elasticity</a></li>
  <li><a href="#approximations-using-logarithms" id="toc-approximations-using-logarithms" class="nav-link" data-scroll-target="#approximations-using-logarithms">Approximations Using Logarithms</a></li>
  </ul></li>
  <li><a href="#example-earnings-and-education" id="toc-example-earnings-and-education" class="nav-link" data-scroll-target="#example-earnings-and-education">9.3 Example: Earnings and Education</a></li>
  <li><a href="#model-1-linear-model" id="toc-model-1-linear-model" class="nav-link" data-scroll-target="#model-1-linear-model">Model 1: Linear Model</a></li>
  <li><a href="#model-2-log-linear-model" id="toc-model-2-log-linear-model" class="nav-link" data-scroll-target="#model-2-log-linear-model">Model 2: Log-Linear Model</a></li>
  <li><a href="#model-3-log-log-model" id="toc-model-3-log-log-model" class="nav-link" data-scroll-target="#model-3-log-log-model">Model 3: Log-Log Model</a></li>
  <li><a href="#model-4-linear-log-model" id="toc-model-4-linear-log-model" class="nav-link" data-scroll-target="#model-4-linear-log-model">Model 4: Linear-Log Model</a></li>
  <li><a href="#comparison-of-all-four-models" id="toc-comparison-of-all-four-models" class="nav-link" data-scroll-target="#comparison-of-all-four-models">Comparison of All Four Models</a></li>
  <li><a href="#visualizing-all-four-models" id="toc-visualizing-all-four-models" class="nav-link" data-scroll-target="#visualizing-all-four-models">Visualizing All Four Models</a></li>
  <li><a href="#further-uses-exponential-growth" id="toc-further-uses-exponential-growth" class="nav-link" data-scroll-target="#further-uses-exponential-growth">9.4 Further Uses: Exponential Growth</a></li>
  <li><a href="#visualizing-exponential-growth" id="toc-visualizing-exponential-growth" class="nav-link" data-scroll-target="#visualizing-exponential-growth">Visualizing Exponential Growth</a></li>
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways">Key Takeaways</a></li>
  <li><a href="#practice-exercises" id="toc-practice-exercises" class="nav-link" data-scroll-target="#practice-exercises">Practice Exercises</a></li>
  <li><a href="#case-studies" id="toc-case-studies" class="nav-link" data-scroll-target="#case-studies">Case Studies</a>
  <ul class="collapse">
  <li><a href="#case-study-logarithmic-models-for-global-labor-productivity" id="toc-case-study-logarithmic-models-for-global-labor-productivity" class="nav-link" data-scroll-target="#case-study-logarithmic-models-for-global-labor-productivity">Case Study: Logarithmic Models for Global Labor Productivity</a></li>
  <li><a href="#how-to-use-these-tasks" id="toc-how-to-use-these-tasks" class="nav-link" data-scroll-target="#how-to-use-these-tasks">How to Use These Tasks</a></li>
  <li><a href="#your-development-policy-brief" id="toc-your-development-policy-brief" class="nav-link" data-scroll-target="#your-development-policy-brief">Your Development Policy Brief</a></li>
  <li><a href="#what-youve-learned-from-this-case-study" id="toc-what-youve-learned-from-this-case-study" class="nav-link" data-scroll-target="#what-youve-learned-from-this-case-study">What You’ve Learned from This Case Study</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<div id="google_translate_element" style="padding: 8px 0;"></div>
<script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({
    pageLanguage: 'en',
    layout: google.translate.TranslateElement.InlineLayout.HORIZONTAL
  }, 'google_translate_element');
}
</script>
<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../notebooks_colab/ch05_Bivariate_Data_Summary.html">Bivariate Regression</a></li><li class="breadcrumb-item"><a href="../notebooks_colab/ch09_Models_with_Natural_Logarithms.html"><span class="chapter-title">Chapter 9: Models with Natural Logarithms</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Chapter 9: Models with Natural Logarithms</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>metricsAI: An Introduction to Econometrics with Python and AI in the Cloud</strong></p>
<p><em><a href="https://carlos-mendez.org">Carlos Mendez</a></em></p>
<p><img src="https://raw.githubusercontent.com/quarcs-lab/metricsai/main/images/ch09_visual_summary.jpg" alt="Chapter 09 Visual Summary" width="65%"></p>
<p>This notebook teaches you how to use natural logarithms in regression analysis to measure elasticities, semi-elasticities, and percentage changes—essential tools for empirical economics.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://colab.research.google.com/github/quarcs-lab/metricsai/blob/main/notebooks_colab/ch09_Models_with_Natural_Logarithms.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" class="img-fluid figure-img"></a></p>
<figcaption>Open In Colab</figcaption>
</figure>
</div>
<section id="chapter-overview" class="level2">
<h2 class="anchored" data-anchor-id="chapter-overview">Chapter Overview</h2>
<p><strong>Why logarithms in economics?</strong></p>
<p>Economists care about <strong>proportionate changes</strong> more than absolute changes: - A $10,000 salary increase means different things at $30,000 vs $300,000 income - A $1 price change matters differently for a $2 item vs a $100 item - Economic theory often predicts <strong>percentage</strong> responses (e.g., price elasticity of demand)</p>
<p><strong>Natural logarithms</strong> let us work with proportionate changes easily in regression models.</p>
<p><strong>What you’ll learn:</strong> - Understand the natural logarithm function and its basic properties - Use logarithmic transformations to approximate proportionate and percentage changes - Distinguish between semi-elasticity and elasticity - Interpret coefficients in log-linear, log-log, and linear-log regression models - Apply logarithmic models to analyze the relationship between earnings and education - Linearize exponential growth patterns using natural logarithms - Apply the Rule of 72 to calculate doubling times for compound growth - Choose the appropriate model specification for different economic questions</p>
<p><strong>Datasets used:</strong> - <strong>AED_EARNINGS.DTA</strong>: Annual earnings and education for 171 full-time workers aged 30 (2010) - <strong>AED_SP500INDEX.DTA</strong>: S&amp;P 500 stock market index, annual data 1927-2019 (93 years)</p>
<p><strong>Chapter outline:</strong> - 9.1 Natural Logarithm Function - 9.2 Semi-Elasticities and Elasticities - 9.3 Example: Earnings and Education - 9.4 Further Uses: Exponential Growth - Key Takeaways - Practice Exercises - Case Studies</p>
</section>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<p>Run this cell first to import all required packages and configure the environment.</p>
<div id="cell-3" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import required libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.formula.api <span class="im">import</span> ols</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> random</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Set random seeds for reproducibility</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>RANDOM_SEED <span class="op">=</span> <span class="dv">42</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>random.seed(RANDOM_SEED)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>np.random.seed(RANDOM_SEED)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>os.environ[<span class="st">'PYTHONHASHSEED'</span>] <span class="op">=</span> <span class="bu">str</span>(RANDOM_SEED)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co"># GitHub data URL (data streams directly from here)</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>GITHUB_DATA_URL <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/"</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Optional: Create directories for saving outputs locally</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>IMAGES_DIR <span class="op">=</span> <span class="st">'images'</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>TABLES_DIR <span class="op">=</span> <span class="st">'tables'</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>os.makedirs(IMAGES_DIR, exist_ok<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>os.makedirs(TABLES_DIR, exist_ok<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Set plotting style</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>sns.set_style(<span class="st">"whitegrid"</span>)</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">'figure.figsize'</span>] <span class="op">=</span> (<span class="dv">10</span>, <span class="dv">6</span>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"✓ Setup complete! All packages imported successfully."</span>)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"✓ Random seed set to </span><span class="sc">{</span>RANDOM_SEED<span class="sc">}</span><span class="ss"> for reproducibility."</span>)</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"✓ Data will stream from: </span><span class="sc">{</span>GITHUB_DATA_URL<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>✓ Setup complete! All packages imported successfully.
✓ Random seed set to 42 for reproducibility.
✓ Data will stream from: https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/</code></pre>
</div>
</div>
</section>
<section id="natural-logarithm-function" class="level2">
<h2 class="anchored" data-anchor-id="natural-logarithm-function">9.1 Natural Logarithm Function</h2>
<p>The <strong>natural logarithm</strong> ln(x) is the logarithm to base <strong>e</strong> ≈ 2.71828…</p>
<p><strong>Definition:</strong> <span class="math display">\[\ln(x) = \log_e(x), \quad x &gt; 0\]</span></p>
<p><strong>Key properties:</strong> 1. ln(1) = 0 2. ln(e) = 1 3. ln(ab) = ln(a) + ln(b) (product rule) 4. ln(a/b) = ln(a) - ln(b) (quotient rule) 5. ln(aᵇ) = b·ln(a) (power rule) 6. exp(ln(x)) = x (inverse function)</p>
<p><strong>Most important property for economics:</strong> <span class="math display">\[\Delta \ln(x) \approx \frac{\Delta x}{x} \quad \text{(for small changes)}\]</span></p>
<p>This means: <strong>Change in ln(x) ≈ proportionate change in x</strong></p>
<p>Multiplying by 100: <strong>100 × Δln(x) ≈ percentage change in x</strong></p>
<p><strong>Example:</strong> If x increases from 40 to 40.4: - Exact proportionate change: (40.4 - 40)/40 = 0.01 (1%) - Log approximation: ln(40.4) - ln(40) = 0.00995 ≈ 0.01</p>
<div id="cell-5" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Demonstrate logarithm properties</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"PROPERTIES OF NATURAL LOGARITHM"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>x_values <span class="op">=</span> np.array([<span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">100</span>])</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>ln_values <span class="op">=</span> np.log(x_values)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>log_table <span class="op">=</span> pd.DataFrame({</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'x'</span>: x_values,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'ln(x)'</span>: ln_values,</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'exp(ln(x))'</span>: np.exp(ln_values)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(log_table.to_string(index<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span> <span class="op">+</span> <span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"KEY PROPERTIES DEMONSTRATED"</span>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"1. ln(1) = </span><span class="sc">{</span>np<span class="sc">.</span>log(<span class="dv">1</span>)<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"2. ln(e) = </span><span class="sc">{</span>np<span class="sc">.</span>log(np.e)<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"3. ln(2×5) = ln(2) + ln(5):  </span><span class="sc">{</span>np<span class="sc">.</span>log(<span class="dv">2</span><span class="op">*</span><span class="dv">5</span>)<span class="sc">:.4f}</span><span class="ss"> = </span><span class="sc">{</span>np<span class="sc">.</span>log(<span class="dv">2</span>) <span class="op">+</span> np<span class="sc">.</span>log(<span class="dv">5</span>)<span class="sc">:.4f}</span><span class="ss"> ✓"</span>)</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"4. ln(10/2) = ln(10) - ln(2): </span><span class="sc">{</span>np<span class="sc">.</span>log(<span class="dv">10</span><span class="op">/</span><span class="dv">2</span>)<span class="sc">:.4f}</span><span class="ss"> = </span><span class="sc">{</span>np<span class="sc">.</span>log(<span class="dv">10</span>) <span class="op">-</span> np<span class="sc">.</span>log(<span class="dv">2</span>)<span class="sc">:.4f}</span><span class="ss"> ✓"</span>)</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span> <span class="op">+</span> <span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"APPROXIMATING PROPORTIONATE CHANGES"</span>)</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>x0, x1 <span class="op">=</span> <span class="dv">40</span>, <span class="fl">40.4</span></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>exact_prop_change <span class="op">=</span> (x1 <span class="op">-</span> x0) <span class="op">/</span> x0</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>log_approx <span class="op">=</span> np.log(x1) <span class="op">-</span> np.log(x0)</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Change from </span><span class="sc">{</span>x0<span class="sc">}</span><span class="ss"> to </span><span class="sc">{</span>x1<span class="sc">}</span><span class="ss">:"</span>)</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Exact proportionate change:    </span><span class="sc">{</span>exact_prop_change<span class="sc">:.6f}</span><span class="ss"> (</span><span class="sc">{</span>exact_prop_change<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%)"</span>)</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Log approximation Δln(x):      </span><span class="sc">{</span>log_approx<span class="sc">:.6f}</span><span class="ss"> (</span><span class="sc">{</span>log_approx<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%)"</span>)</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Difference:                    </span><span class="sc">{</span><span class="bu">abs</span>(exact_prop_change <span class="op">-</span> log_approx)<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">  → The approximation is excellent for small changes!"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
PROPERTIES OF NATURAL LOGARITHM
======================================================================
    x     ln(x)  exp(ln(x))
  0.5 -0.693147         0.5
  1.0  0.000000         1.0
  2.0  0.693147         2.0
  5.0  1.609438         5.0
 10.0  2.302585        10.0
 20.0  2.995732        20.0
100.0  4.605170       100.0

======================================================================
KEY PROPERTIES DEMONSTRATED
======================================================================
1. ln(1) = 0.0000
2. ln(e) = 1.0000
3. ln(2×5) = ln(2) + ln(5):  2.3026 = 2.3026 ✓
4. ln(10/2) = ln(10) - ln(2): 1.6094 = 1.6094 ✓

======================================================================
APPROXIMATING PROPORTIONATE CHANGES
======================================================================
Change from 40 to 40.4:
  Exact proportionate change:    0.010000 (1.00%)
  Log approximation Δln(x):      0.009950 (1.00%)
  Difference:                    0.000050

  → The approximation is excellent for small changes!</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Key Concept 9.1: Logarithmic Approximation of Proportionate Change</strong></p>
<p>The most important property of the natural logarithm for economics is:</p>
<p><span class="math display">\[\Delta \ln(x) \approx \frac{\Delta x}{x} \quad \text{(proportionate change)}\]</span></p>
<p>Multiplying by 100 gives the <strong>percentage change</strong>: 100 × Δln(x) ≈ %Δx.</p>
<p><strong>Why this matters:</strong> This approximation allows us to interpret regression coefficients involving logged variables as <strong>proportionate or percentage changes</strong> — exactly what economists care about when analyzing earnings, prices, GDP, and other economic variables.</p>
<p><strong>Accuracy:</strong> The approximation is excellent for changes under 10%. For larger changes, use the exact formula: %Δx = 100 × (e^Δln(x) - 1).</p>
</blockquote>
<p>Now that we understand the mathematical properties of logarithms, we can apply them to define two key economic concepts: <strong>semi-elasticity</strong> and <strong>elasticity</strong>.</p>
</section>
<section id="semi-elasticities-and-elasticities" class="level2">
<h2 class="anchored" data-anchor-id="semi-elasticities-and-elasticities">9.2 Semi-Elasticities and Elasticities</h2>
<p>Two key concepts in economics:</p>
<section id="semi-elasticity" class="level3">
<h3 class="anchored" data-anchor-id="semi-elasticity">Semi-Elasticity</h3>
<p><strong>Definition:</strong> Proportionate change in y for a <strong>unit change</strong> in x <span class="math display">\[\text{Semi-elasticity}_{yx} = \frac{\Delta y / y}{\Delta x}\]</span></p>
<p>Multiplied by 100: <strong>percentage change in y when x increases by 1 unit</strong></p>
<p><strong>Example:</strong> Semi-elasticity of earnings with respect to education = 0.08</p>
<ul>
<li>One more year of schooling → 8% increase in earnings</li>
</ul>
</section>
<section id="elasticity" class="level3">
<h3 class="anchored" data-anchor-id="elasticity">Elasticity</h3>
<p><strong>Definition:</strong> Proportionate change in y for a <strong>proportionate change</strong> in x <span class="math display">\[\text{Elasticity}_{yx} = \frac{\Delta y / y}{\Delta x / x}\]</span></p>
<p><strong>Example:</strong> Price elasticity of demand = -2</p>
<ul>
<li>1% increase in price → 2% decrease in demand</li>
</ul>
</section>
<section id="approximations-using-logarithms" class="level3">
<h3 class="anchored" data-anchor-id="approximations-using-logarithms">Approximations Using Logarithms</h3>
<p>Since Δy/y ≈ Δln(y) and Δx/x ≈ Δln(x):</p>
<p><span class="math display">\[\text{Semi-elasticity} \approx \frac{\Delta \ln(y)}{\Delta x}\]</span></p>
<p><span class="math display">\[\text{Elasticity} \approx \frac{\Delta \ln(y)}{\Delta \ln(x)}\]</span></p>
<p><strong>This is why we use logarithms in regression!</strong> The slope coefficient directly estimates the semi-elasticity or elasticity.</p>
<div id="cell-9" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"MODEL INTERPRETATIONS"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">1. LINEAR MODEL: y = β₀ + β₁x"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"   Interpretation: Δy = β₁Δx"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"   Example: β₁ = 5000 means $5,000 increase in y when x increases by 1"</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">2. LOG-LINEAR MODEL: ln(y) = β₀ + β₁x"</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"   Interpretation: %Δy ≈ 100β₁Δx (semi-elasticity)"</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"   Example: β₁ = 0.08 means 8</span><span class="sc">% i</span><span class="st">ncrease in y when x increases by 1"</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">3. LOG-LOG MODEL: ln(y) = β₀ + β₁ln(x)"</span>)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"   Interpretation: %Δy ≈ β₁%Δx (elasticity)"</span>)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"   Example: β₁ = 1.5 means 1.5</span><span class="sc">% i</span><span class="st">ncrease in y when x increases by 1%"</span>)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">4. LINEAR-LOG MODEL: y = β₀ + β₁ln(x)"</span>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"   Interpretation: Δy ≈ (β₁/100)%Δx"</span>)</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"   Example: β₁ = 500 means $5 increase in y when x increases by 1%"</span>)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span> <span class="op">+</span> <span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"KEY TAKEAWAY"</span>)</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The choice of model specification determines the interpretation:"</span>)</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"  - Which model to use depends on economic theory and data properties"</span>)</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"  - Log transformations are especially useful for:"</span>)</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"    • Right-skewed variables (earnings, prices, firm size)"</span>)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"    • Multiplicative relationships"</span>)</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"    • Proportionate/percentage effects"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
MODEL INTERPRETATIONS
======================================================================

1. LINEAR MODEL: y = β₀ + β₁x
   Interpretation: Δy = β₁Δx
   Example: β₁ = 5000 means $5,000 increase in y when x increases by 1

2. LOG-LINEAR MODEL: ln(y) = β₀ + β₁x
   Interpretation: %Δy ≈ 100β₁Δx (semi-elasticity)
   Example: β₁ = 0.08 means 8% increase in y when x increases by 1

3. LOG-LOG MODEL: ln(y) = β₀ + β₁ln(x)
   Interpretation: %Δy ≈ β₁%Δx (elasticity)
   Example: β₁ = 1.5 means 1.5% increase in y when x increases by 1%

4. LINEAR-LOG MODEL: y = β₀ + β₁ln(x)
   Interpretation: Δy ≈ (β₁/100)%Δx
   Example: β₁ = 500 means $5 increase in y when x increases by 1%

======================================================================
KEY TAKEAWAY
======================================================================
The choice of model specification determines the interpretation:
  - Which model to use depends on economic theory and data properties
  - Log transformations are especially useful for:
    • Right-skewed variables (earnings, prices, firm size)
    • Multiplicative relationships
    • Proportionate/percentage effects</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Key Concept 9.2: Semi-Elasticity vs.&nbsp;Elasticity</strong></p>
<p>These two concepts measure how y responds to changes in x, but in different ways:</p>
<ul>
<li><strong>Semi-elasticity</strong> = (Δy/y) / Δx — proportionate change in y per <strong>unit</strong> change in x</li>
<li><strong>Elasticity</strong> = (Δy/y) / (Δx/x) — proportionate change in y per <strong>proportionate</strong> change in x</li>
</ul>
<p><strong>In regression models:</strong> - Semi-elasticity ≈ Δln(y)/Δx → estimated by the slope in a <strong>log-linear</strong> model - Elasticity ≈ Δln(y)/Δln(x) → estimated by the slope in a <strong>log-log</strong> model</p>
<p><strong>When to use each:</strong> - <strong>Semi-elasticity:</strong> When x is measured in natural units (years of education, age) - <strong>Elasticity:</strong> When both variables are measured in proportions (price and quantity, GDP and investment)</p>
</blockquote>
<p>With the concepts of semi-elasticity and elasticity defined, let’s apply all four model specifications to a <strong>real dataset</strong> to compare interpretations.</p>
</section>
</section>
<section id="example-earnings-and-education" class="level2">
<h2 class="anchored" data-anchor-id="example-earnings-and-education">9.3 Example: Earnings and Education</h2>
<p><strong>Research Question:</strong> How do earnings vary with years of education?</p>
<p>We’ll estimate <strong>four different models</strong> and compare their interpretations:</p>
<ol type="1">
<li><strong>Linear:</strong> earnings = β₀ + β₁(education)</li>
<li><strong>Log-linear:</strong> ln(earnings) = β₀ + β₁(education)</li>
<li><strong>Log-log:</strong> ln(earnings) = β₀ + β₁ln(education)</li>
<li><strong>Linear-log:</strong> earnings = β₀ + β₁ln(education)</li>
</ol>
<p><strong>Dataset:</strong> 171 full-time workers aged 30 in 2010 - earnings: Annual earnings in dollars - education: Years of completed schooling</p>
<p>Each model answers a slightly different question and has different economic interpretation.</p>
<div id="cell-13" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load and explore the data</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>data_earnings <span class="op">=</span> pd.read_stata(GITHUB_DATA_URL <span class="op">+</span> <span class="st">'AED_EARNINGS.DTA'</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"DATA SUMMARY: EARNINGS AND EDUCATION"</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data_earnings[[<span class="st">'earnings'</span>, <span class="st">'education'</span>]].describe())</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">First 5 observations:"</span>)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data_earnings[[<span class="st">'earnings'</span>, <span class="st">'education'</span>]].head())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
DATA SUMMARY: EARNINGS AND EDUCATION
======================================================================
            earnings   education
count     171.000000  171.000000
mean    41412.690058   14.432749
std     25527.053396    2.735364
min      1050.000000    3.000000
25%     25000.000000   12.000000
50%     36000.000000   14.000000
75%     49000.000000   16.000000
max    172000.000000   20.000000

First 5 observations:
   earnings  education
0     25000         14
1     40000         12
2     25000         13
3     38000         13
4     28800         12</code></pre>
</div>
</div>
<div id="cell-14" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create log-transformed variables</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>data_earnings[<span class="st">'lnearn'</span>] <span class="op">=</span> np.log(data_earnings[<span class="st">'earnings'</span>])</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>data_earnings[<span class="st">'lneduc'</span>] <span class="op">=</span> np.log(data_earnings[<span class="st">'education'</span>])</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"VARIABLES (ORIGINAL AND LOG-TRANSFORMED)"</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>table_vars <span class="op">=</span> [<span class="st">'earnings'</span>, <span class="st">'lnearn'</span>, <span class="st">'education'</span>, <span class="st">'lneduc'</span>]</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data_earnings[table_vars].describe())</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Notice:"</span>)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"  - Log(earnings) has much less variability (std = 0.62 vs 25,527)"</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"  - Log transformation reduces right skewness in earnings"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
VARIABLES (ORIGINAL AND LOG-TRANSFORMED)
======================================================================
            earnings      lnearn   education      lneduc
count     171.000000  171.000000  171.000000  171.000000
mean    41412.690058   10.457638   14.432749    2.648438
std     25527.053396    0.622062    2.735364    0.225220
min      1050.000000    6.956545    3.000000    1.098633
25%     25000.000000   10.126631   12.000000    2.484375
50%     36000.000000   10.491274   14.000000    2.638672
75%     49000.000000   10.799367   16.000000    2.773438
max    172000.000000   12.055250   20.000000    2.996094

Notice:
  - Log(earnings) has much less variability (std = 0.62 vs 25,527)
  - Log transformation reduces right skewness in earnings</code></pre>
</div>
</div>
</section>
<section id="model-1-linear-model" class="level2">
<h2 class="anchored" data-anchor-id="model-1-linear-model">Model 1: Linear Model</h2>
<p><strong>Specification:</strong> earnings = β₀ + β₁(education) + ε</p>
<p><strong>Interpretation:</strong> β₁ = change in earnings (in dollars) for one additional year of education</p>
<div id="cell-16" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 1: Linear</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"MODEL 1: LINEAR - earnings = β₀ + β₁(education)"</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>model_linear <span class="op">=</span> ols(<span class="st">'earnings ~ education'</span>, data<span class="op">=</span>data_earnings).fit()</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_linear.summary())</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span> <span class="op">+</span> <span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"INTERPRETATION"</span>)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Coefficient on education: $</span><span class="sc">{</span>model_linear<span class="sc">.</span>params[<span class="st">'education'</span>]<span class="sc">:,.2f}</span><span class="ss">"</span>)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Economic meaning:"</span>)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Each additional year of education is associated with a"</span>)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  $</span><span class="sc">{</span>model_linear<span class="sc">.</span>params[<span class="st">'education'</span>]<span class="sc">:,.2f}</span><span class="ss"> increase in annual earnings."</span>)</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">R² = </span><span class="sc">{</span>model_linear<span class="sc">.</span>rsquared<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  → Education explains </span><span class="sc">{</span>model_linear<span class="sc">.</span>rsquared<span class="op">*</span><span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">% of variation in earnings."</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
MODEL 1: LINEAR - earnings = β₀ + β₁(education)
======================================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:               earnings   R-squared:                       0.289
Model:                            OLS   Adj. R-squared:                  0.285
Method:                 Least Squares   F-statistic:                     68.86
Date:                Wed, 21 Jan 2026   Prob (F-statistic):           3.22e-14
Time:                        00:01:47   Log-Likelihood:                -1948.1
No. Observations:                 171   AIC:                             3900.
Df Residuals:                     169   BIC:                             3907.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -3.106e+04   8887.835     -3.494      0.001   -4.86e+04   -1.35e+04
education   5021.1229    605.101      8.298      0.000    3826.593    6215.653
==============================================================================
Omnibus:                       78.232   Durbin-Watson:                   1.783
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              292.688
Skew:                           1.791   Prob(JB):                     2.78e-64
Kurtosis:                       8.315   Cond. No.                         79.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

======================================================================
INTERPRETATION
======================================================================
Coefficient on education: $5,021.12

Economic meaning:
  Each additional year of education is associated with a
  $5,021.12 increase in annual earnings.

R² = 0.289
  → Education explains 28.9% of variation in earnings.</code></pre>
</div>
</div>
</section>
<section id="model-2-log-linear-model" class="level2">
<h2 class="anchored" data-anchor-id="model-2-log-linear-model">Model 2: Log-Linear Model</h2>
<p><strong>Specification:</strong> ln(earnings) = β₀ + β₁(education) + ε</p>
<p><strong>Interpretation:</strong> β₁ = <strong>semi-elasticity</strong> = proportionate change in earnings for one more year of education</p>
<p><strong>Practical interpretation:</strong> 100β₁ = <strong>percentage change</strong> in earnings for one more year of education</p>
<p>This is the <strong>most common</strong> specification for earnings equations!</p>
<div id="cell-18" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 2: Log-linear</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"MODEL 2: LOG-LINEAR - ln(earnings) = β₀ + β₁(education)"</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>model_loglin <span class="op">=</span> ols(<span class="st">'lnearn ~ education'</span>, data<span class="op">=</span>data_earnings).fit()</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_loglin.summary())</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span> <span class="op">+</span> <span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"INTERPRETATION"</span>)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Coefficient on education: </span><span class="sc">{</span>model_loglin<span class="sc">.</span>params[<span class="st">'education'</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Economic meaning:"</span>)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Each additional year of education is associated with a"</span>)</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span><span class="dv">100</span><span class="op">*</span>model_loglin<span class="sc">.</span>params[<span class="st">'education'</span>]<span class="sc">:.2f}</span><span class="ss">% increase in earnings."</span>)</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Why this is better than Model 1:"</span>)</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  - Percentage interpretation is more meaningful (scales automatically)"</span>)</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  - 13.1% increase applies whether you earn $30k or $100k"</span>)</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  - Better fit (R² = </span><span class="sc">{</span>model_loglin<span class="sc">.</span>rsquared<span class="sc">:.3f}</span><span class="ss"> vs </span><span class="sc">{</span>model_linear<span class="sc">.</span>rsquared<span class="sc">:.3f}</span><span class="ss">)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
MODEL 2: LOG-LINEAR - ln(earnings) = β₀ + β₁(education)
======================================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 lnearn   R-squared:                       0.334
Model:                            OLS   Adj. R-squared:                  0.330
Method:                 Least Squares   F-statistic:                     84.74
Date:                Wed, 21 Jan 2026   Prob (F-statistic):           1.28e-16
Time:                        00:01:47   Log-Likelihood:                -126.21
No. Observations:                 171   AIC:                             256.4
Df Residuals:                     169   BIC:                             262.7
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      8.5608      0.210     40.825      0.000       8.147       8.975
education      0.1314      0.014      9.206      0.000       0.103       0.160
==============================================================================
Omnibus:                       58.560   Durbin-Watson:                   1.809
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              351.030
Skew:                          -1.091   Prob(JB):                     5.96e-77
Kurtosis:                       9.671   Cond. No.                         79.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

======================================================================
INTERPRETATION
======================================================================
Coefficient on education: 0.1314

Economic meaning:
  Each additional year of education is associated with a
  13.14% increase in earnings.

Why this is better than Model 1:
  - Percentage interpretation is more meaningful (scales automatically)
  - 13.1% increase applies whether you earn $30k or $100k
  - Better fit (R² = 0.334 vs 0.289)</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Key Concept 9.3: Interpreting Log-Linear Model Coefficients</strong></p>
<p>In the <strong>log-linear model</strong> ln(y) = β₀ + β₁x, the slope coefficient β₁ is the <strong>semi-elasticity</strong> of y with respect to x:</p>
<p><span class="math display">\[100 \times \beta_1 = \text{percentage change in } y \text{ when } x \text{ increases by 1 unit}\]</span></p>
<p>This is the most common specification in labor economics because a percentage interpretation <strong>scales automatically</strong> — a 13% return to education applies equally whether you earn $30,000 or $100,000.</p>
<p><strong>Important:</strong> The exact percentage change for large β₁ is 100 × (e^β₁ - 1), not 100 × β₁. The approximation works well when β₁ &lt; 0.10.</p>
</blockquote>
</section>
<section id="model-3-log-log-model" class="level2">
<h2 class="anchored" data-anchor-id="model-3-log-log-model">Model 3: Log-Log Model</h2>
<p><strong>Specification:</strong> ln(earnings) = β₀ + β₁ln(education) + ε</p>
<p><strong>Interpretation:</strong> β₁ = <strong>elasticity</strong> = percentage change in earnings for a 1% change in education</p>
<p><strong>Note:</strong> A “1% increase in education” is a bit artificial (what does 0.14 more years mean?), but this model captures diminishing returns to education.</p>
<div id="cell-21" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 3: Log-log</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"MODEL 3: LOG-LOG - ln(earnings) = β₀ + β₁ln(education)"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>model_loglog <span class="op">=</span> ols(<span class="st">'lnearn ~ lneduc'</span>, data<span class="op">=</span>data_earnings).fit()</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_loglog.summary())</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span> <span class="op">+</span> <span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"INTERPRETATION"</span>)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Coefficient on ln(education): </span><span class="sc">{</span>model_loglog<span class="sc">.</span>params[<span class="st">'lneduc'</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Economic meaning:"</span>)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  A 1% increase in education is associated with a"</span>)</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>model_loglog<span class="sc">.</span>params[<span class="st">'lneduc'</span>]<span class="sc">:.3f}</span><span class="ss">% increase in earnings (elasticity)."</span>)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Alternative interpretation:"</span>)</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  If education increases from 14 to 14.14 years (1% increase),"</span>)</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  earnings increase by approximately </span><span class="sc">{</span>model_loglog<span class="sc">.</span>params[<span class="st">'lneduc'</span>]<span class="sc">:.2f}</span><span class="ss">%."</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
MODEL 3: LOG-LOG - ln(earnings) = β₀ + β₁ln(education)
======================================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 lnearn   R-squared:                       0.286
Model:                            OLS   Adj. R-squared:                  0.282
Method:                 Least Squares   F-statistic:                     67.78
Date:                Wed, 21 Jan 2026   Prob (F-statistic):           4.76e-14
Time:                        00:01:47   Log-Likelihood:                -132.13
No. Observations:                 171   AIC:                             268.3
Df Residuals:                     169   BIC:                             274.5
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      6.5454      0.477     13.725      0.000       5.604       7.487
lneduc         1.4775      0.179      8.233      0.000       1.123       1.832
==============================================================================
Omnibus:                       56.464   Durbin-Watson:                   1.786
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              332.274
Skew:                          -1.048   Prob(JB):                     7.04e-73
Kurtosis:                       9.499   Cond. No.                         35.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

======================================================================
INTERPRETATION
======================================================================
Coefficient on ln(education): 1.4775

Economic meaning:
  A 1% increase in education is associated with a
  1.478% increase in earnings (elasticity).

Alternative interpretation:
  If education increases from 14 to 14.14 years (1% increase),
  earnings increase by approximately 1.48%.</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Key Concept 9.4: Interpreting Log-Log Model Coefficients</strong></p>
<p>In the <strong>log-log model</strong> ln(y) = β₀ + β₁ln(x), the slope coefficient β₁ is the <strong>elasticity</strong> of y with respect to x:</p>
<p><span class="math display">\[\beta_1 = \frac{\%\Delta y}{\%\Delta x}\]</span></p>
<p>A 1% increase in x is associated with a β₁% change in y. Unlike semi-elasticity, elasticity is a <strong>unit-free</strong> measure — it does not depend on the units of measurement.</p>
<p><strong>Economic interpretation:</strong> If β₁ &lt; 1, there are <strong>diminishing returns</strong> (each additional percent of x yields less than one percent of y). If β₁ &gt; 1, there are <strong>increasing returns</strong>.</p>
</blockquote>
</section>
<section id="model-4-linear-log-model" class="level2">
<h2 class="anchored" data-anchor-id="model-4-linear-log-model">Model 4: Linear-Log Model</h2>
<p><strong>Specification:</strong> earnings = β₀ + β₁ln(education) + ε</p>
<p><strong>Interpretation:</strong> β₁/100 = dollar change in earnings for a 1% increase in education</p>
<p>This model is less common but captures <strong>diminishing returns</strong> (additional years of education have decreasing marginal effects).</p>
<div id="cell-24" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 4: Linear-log</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"MODEL 4: LINEAR-LOG - earnings = β₀ + β₁ln(education)"</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>model_linlog <span class="op">=</span> ols(<span class="st">'earnings ~ lneduc'</span>, data<span class="op">=</span>data_earnings).fit()</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_linlog.summary())</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span> <span class="op">+</span> <span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"INTERPRETATION"</span>)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Coefficient on ln(education): </span><span class="sc">{</span>model_linlog<span class="sc">.</span>params[<span class="st">'lneduc'</span>]<span class="sc">:,.2f}</span><span class="ss">"</span>)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Economic meaning:"</span>)</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  A 1% increase in education is associated with a"</span>)</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  $</span><span class="sc">{</span>model_linlog<span class="sc">.</span>params[<span class="st">'lneduc'</span>]<span class="op">/</span><span class="dv">100</span><span class="sc">:,.2f}</span><span class="ss"> increase in annual earnings."</span>)</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Note: This model has the lowest R² = </span><span class="sc">{</span>model_linlog<span class="sc">.</span>rsquared<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
MODEL 4: LINEAR-LOG - earnings = β₀ + β₁ln(education)
======================================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:               earnings   R-squared:                       0.231
Model:                            OLS   Adj. R-squared:                  0.226
Method:                 Least Squares   F-statistic:                     50.69
Date:                Wed, 21 Jan 2026   Prob (F-statistic):           2.96e-11
Time:                        00:01:47   Log-Likelihood:                -1954.9
No. Observations:                 171   AIC:                             3914.
Df Residuals:                     169   BIC:                             3920.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -1.027e+05   2.03e+04     -5.056      0.000   -1.43e+05   -6.26e+04
lneduc      5.443e+04   7645.805      7.119      0.000    3.93e+04    6.95e+04
==============================================================================
Omnibus:                       79.258   Durbin-Watson:                   1.794
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              284.125
Skew:                           1.843   Prob(JB):                     2.01e-62
Kurtosis:                       8.128   Cond. No.                         35.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

======================================================================
INTERPRETATION
======================================================================
Coefficient on ln(education): 54,433.42

Economic meaning:
  A 1% increase in education is associated with a
  $544.33 increase in annual earnings.

Note: This model has the lowest R² = 0.231</code></pre>
</div>
</div>
</section>
<section id="comparison-of-all-four-models" class="level2">
<h2 class="anchored" data-anchor-id="comparison-of-all-four-models">Comparison of All Four Models</h2>
<div id="cell-26" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create comparison table</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"MODEL COMPARISON SUMMARY"</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>comparison_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Model'</span>: [<span class="st">'Linear'</span>, <span class="st">'Log-linear'</span>, <span class="st">'Log-log'</span>, <span class="st">'Linear-log'</span>],</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Specification'</span>: [<span class="st">'y ~ x'</span>, <span class="st">'ln(y) ~ x'</span>, <span class="st">'ln(y) ~ ln(x)'</span>, <span class="st">'y ~ ln(x)'</span>],</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Slope Coefficient'</span>: [</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>model_linear<span class="sc">.</span>params[<span class="dv">1</span>]<span class="sc">:,.2f}</span><span class="ss">"</span>,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>model_loglin<span class="sc">.</span>params[<span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss">"</span>,</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>model_loglog<span class="sc">.</span>params[<span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss">"</span>,</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>model_linlog<span class="sc">.</span>params[<span class="dv">1</span>]<span class="sc">:,.2f}</span><span class="ss">"</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Interpretation'</span>: [</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"$</span><span class="sc">{</span>model_linear<span class="sc">.</span>params[<span class="dv">1</span>]<span class="sc">:,.0f}</span><span class="ss"> per year"</span>,</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span><span class="dv">100</span><span class="op">*</span>model_loglin<span class="sc">.</span>params[<span class="dv">1</span>]<span class="sc">:.1f}</span><span class="ss">% per year"</span>,</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>model_loglog<span class="sc">.</span>params[<span class="dv">1</span>]<span class="sc">:.2f}</span><span class="ss">% per 1% change"</span>,</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"$</span><span class="sc">{</span>model_linlog<span class="sc">.</span>params[<span class="dv">1</span>]<span class="op">/</span><span class="dv">100</span><span class="sc">:,.0f}</span><span class="ss"> per 1% change"</span></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">'R²'</span>: [</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>model_linear<span class="sc">.</span>rsquared<span class="sc">:.3f}</span><span class="ss">"</span>,</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>model_loglin<span class="sc">.</span>rsquared<span class="sc">:.3f}</span><span class="ss">"</span>,</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>model_loglog<span class="sc">.</span>rsquared<span class="sc">:.3f}</span><span class="ss">"</span>,</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>model_linlog<span class="sc">.</span>rsquared<span class="sc">:.3f}</span><span class="ss">"</span></span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(comparison_df.to_string(index<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span> <span class="op">+</span> <span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"WHICH MODEL IS BEST?"</span>)</span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"For this data:"</span>)</span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  - Best fit (highest R²): Log-linear (R² = </span><span class="sc">{</span>model_loglin<span class="sc">.</span>rsquared<span class="sc">:.3f}</span><span class="ss">)"</span>)</span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  - Most interpretable: Log-linear (13.1% return per year of education)"</span>)</span>
<span id="cb19-37"><a href="#cb19-37" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  - Most common in labor economics: Log-linear"</span>)</span>
<span id="cb19-38"><a href="#cb19-38" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">General guidance:"</span>)</span>
<span id="cb19-39"><a href="#cb19-39" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"  - Use log-linear when dependent variable is right-skewed"</span>)</span>
<span id="cb19-40"><a href="#cb19-40" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"  - Use log-log when both variables are right-skewed"</span>)</span>
<span id="cb19-41"><a href="#cb19-41" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"  - Compare models using R², economic interpretation, and theory"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
MODEL COMPARISON SUMMARY
======================================================================
     Model Specification Slope Coefficient      Interpretation    R²
    Linear         y ~ x          5,021.12     $5,021 per year 0.289
Log-linear     ln(y) ~ x            0.1314      13.1% per year 0.334
   Log-log ln(y) ~ ln(x)            1.4775 1.48% per 1% change 0.286
Linear-log     y ~ ln(x)         54,433.42  $544 per 1% change 0.231

======================================================================
WHICH MODEL IS BEST?
======================================================================
For this data:
  - Best fit (highest R²): Log-linear (R² = 0.334)
  - Most interpretable: Log-linear (13.1% return per year of education)
  - Most common in labor economics: Log-linear

General guidance:
  - Use log-linear when dependent variable is right-skewed
  - Use log-log when both variables are right-skewed
  - Compare models using R², economic interpretation, and theory</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/tq/t98kb27n6djgrh085g476yhc0000gn/T/ipykernel_94143/1404078335.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  f"{model_linear.params[1]:,.2f}",
/var/folders/tq/t98kb27n6djgrh085g476yhc0000gn/T/ipykernel_94143/1404078335.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  f"{model_loglin.params[1]:.4f}",
/var/folders/tq/t98kb27n6djgrh085g476yhc0000gn/T/ipykernel_94143/1404078335.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  f"{model_loglog.params[1]:.4f}",
/var/folders/tq/t98kb27n6djgrh085g476yhc0000gn/T/ipykernel_94143/1404078335.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  f"{model_linlog.params[1]:,.2f}"
/var/folders/tq/t98kb27n6djgrh085g476yhc0000gn/T/ipykernel_94143/1404078335.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  f"${model_linear.params[1]:,.0f} per year",
/var/folders/tq/t98kb27n6djgrh085g476yhc0000gn/T/ipykernel_94143/1404078335.py:17: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  f"{100*model_loglin.params[1]:.1f}% per year",
/var/folders/tq/t98kb27n6djgrh085g476yhc0000gn/T/ipykernel_94143/1404078335.py:18: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  f"{model_loglog.params[1]:.2f}% per 1% change",
/var/folders/tq/t98kb27n6djgrh085g476yhc0000gn/T/ipykernel_94143/1404078335.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  f"${model_linlog.params[1]/100:,.0f} per 1% change"</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Key Concept 9.5: Choosing the Right Functional Form</strong></p>
<p>The choice between linear, log-linear, log-log, and linear-log specifications should be guided by:</p>
<ol type="1">
<li><strong>Economic theory</strong> — Does the theory predict absolute or percentage effects?</li>
<li><strong>Data properties</strong> — Is the dependent variable right-skewed? Are both variables positive?</li>
<li><strong>Model fit</strong> — Which specification yields the highest R²?</li>
<li><strong>Interpretation needs</strong> — Do you need elasticities, semi-elasticities, or dollar amounts?</li>
</ol>
<p><strong>In practice:</strong> The <strong>log-linear model</strong> is most common in economics because many economic relationships involve percentage changes (returns to education, inflation effects, price responses). When in doubt, start with log-linear.</p>
</blockquote>
</section>
<section id="visualizing-all-four-models" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-all-four-models">Visualizing All Four Models</h2>
<div id="cell-29" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create 2x2 comparison plot</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">16</span>, <span class="dv">12</span>))</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 1: Linear</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].scatter(data_earnings[<span class="st">'education'</span>], data_earnings[<span class="st">'earnings'</span>],</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>                   alpha<span class="op">=</span><span class="fl">0.5</span>, s<span class="op">=</span><span class="dv">20</span>, color<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].plot(data_earnings[<span class="st">'education'</span>], model_linear.fittedvalues,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>                color<span class="op">=</span><span class="st">'blue'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="ss">f'R² = </span><span class="sc">{</span>model_linear<span class="sc">.</span>rsquared<span class="sc">:.3f}</span><span class="ss">'</span>)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].set_xlabel(<span class="st">'Education (years)'</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].set_ylabel(<span class="st">'Earnings ($)'</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].set_title(<span class="st">'Model 1: Linear</span><span class="ch">\n</span><span class="st">y = β₀ + β₁x</span><span class="ch">\n</span><span class="st">Slope: $5,021 per year'</span>,</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>                     fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].legend()</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 2: Log-linear</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].scatter(data_earnings[<span class="st">'education'</span>], data_earnings[<span class="st">'lnearn'</span>],</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>                   alpha<span class="op">=</span><span class="fl">0.5</span>, s<span class="op">=</span><span class="dv">20</span>, color<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].plot(data_earnings[<span class="st">'education'</span>], model_loglin.fittedvalues,</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>                color<span class="op">=</span><span class="st">'blue'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="ss">f'R² = </span><span class="sc">{</span>model_loglin<span class="sc">.</span>rsquared<span class="sc">:.3f}</span><span class="ss">'</span>)</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].set_xlabel(<span class="st">'Education (years)'</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].set_ylabel(<span class="st">'ln(Earnings)'</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].set_title(<span class="st">'Model 2: Log-linear</span><span class="ch">\n</span><span class="st">ln(y) = β₀ + β₁x</span><span class="ch">\n</span><span class="st">Slope: 13.1% per year'</span>,</span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>                     fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].legend()</span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 3: Log-log</span></span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].scatter(data_earnings[<span class="st">'lneduc'</span>], data_earnings[<span class="st">'lnearn'</span>],</span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a>                   alpha<span class="op">=</span><span class="fl">0.5</span>, s<span class="op">=</span><span class="dv">20</span>, color<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].plot(data_earnings[<span class="st">'lneduc'</span>], model_loglog.fittedvalues,</span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a>                color<span class="op">=</span><span class="st">'blue'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="ss">f'R² = </span><span class="sc">{</span>model_loglog<span class="sc">.</span>rsquared<span class="sc">:.3f}</span><span class="ss">'</span>)</span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].set_xlabel(<span class="st">'ln(Education)'</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].set_ylabel(<span class="st">'ln(Earnings)'</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb22-35"><a href="#cb22-35" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].set_title(<span class="st">'Model 3: Log-log</span><span class="ch">\n</span><span class="st">ln(y) = β₀ + β₁ln(x)</span><span class="ch">\n</span><span class="st">Elasticity: 1.48'</span>,</span>
<span id="cb22-36"><a href="#cb22-36" aria-hidden="true" tabindex="-1"></a>                     fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-37"><a href="#cb22-37" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].legend()</span>
<span id="cb22-38"><a href="#cb22-38" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">0</span>].grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb22-39"><a href="#cb22-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-40"><a href="#cb22-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 4: Linear-log</span></span>
<span id="cb22-41"><a href="#cb22-41" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].scatter(data_earnings[<span class="st">'lneduc'</span>], data_earnings[<span class="st">'earnings'</span>],</span>
<span id="cb22-42"><a href="#cb22-42" aria-hidden="true" tabindex="-1"></a>                   alpha<span class="op">=</span><span class="fl">0.5</span>, s<span class="op">=</span><span class="dv">20</span>, color<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb22-43"><a href="#cb22-43" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].plot(data_earnings[<span class="st">'lneduc'</span>], model_linlog.fittedvalues,</span>
<span id="cb22-44"><a href="#cb22-44" aria-hidden="true" tabindex="-1"></a>                color<span class="op">=</span><span class="st">'blue'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="ss">f'R² = </span><span class="sc">{</span>model_linlog<span class="sc">.</span>rsquared<span class="sc">:.3f}</span><span class="ss">'</span>)</span>
<span id="cb22-45"><a href="#cb22-45" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].set_xlabel(<span class="st">'ln(Education)'</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb22-46"><a href="#cb22-46" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].set_ylabel(<span class="st">'Earnings ($)'</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb22-47"><a href="#cb22-47" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].set_title(<span class="st">'Model 4: Linear-log</span><span class="ch">\n</span><span class="st">y = β₀ + β₁ln(x)</span><span class="ch">\n</span><span class="st">Slope: $545 per 1</span><span class="sc">% c</span><span class="st">hange'</span>,</span>
<span id="cb22-48"><a href="#cb22-48" aria-hidden="true" tabindex="-1"></a>                     fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-49"><a href="#cb22-49" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].legend()</span>
<span id="cb22-50"><a href="#cb22-50" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>, <span class="dv">1</span>].grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb22-51"><a href="#cb22-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-52"><a href="#cb22-52" aria-hidden="true" tabindex="-1"></a>plt.suptitle(<span class="st">'Four Model Specifications: Earnings and Education'</span>,</span>
<span id="cb22-53"><a href="#cb22-53" aria-hidden="true" tabindex="-1"></a>             fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>, y<span class="op">=</span><span class="fl">1.00</span>)</span>
<span id="cb22-54"><a href="#cb22-54" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb22-55"><a href="#cb22-55" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb22-56"><a href="#cb22-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-57"><a href="#cb22-57" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">📊 Visual Insights:"</span>)</span>
<span id="cb22-58"><a href="#cb22-58" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"   - Model 1 (linear): Straight line fit, but residuals may be heteroskedastic"</span>)</span>
<span id="cb22-59"><a href="#cb22-59" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"   - Model 2 (log-linear): Best fit, captures curvature in original data"</span>)</span>
<span id="cb22-60"><a href="#cb22-60" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"   - Model 3 (log-log): Both axes logged, captures elasticity"</span>)</span>
<span id="cb22-61"><a href="#cb22-61" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"   - Model 4 (linear-log): Captures diminishing returns to education"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/tq/t98kb27n6djgrh085g476yhc0000gn/T/ipykernel_94143/1405591350.py:54: UserWarning: Glyph 8320 (\N{SUBSCRIPT ZERO}) missing from current font.
  plt.tight_layout()
/var/folders/tq/t98kb27n6djgrh085g476yhc0000gn/T/ipykernel_94143/1405591350.py:54: UserWarning: Glyph 8321 (\N{SUBSCRIPT ONE}) missing from current font.
  plt.tight_layout()
/Users/carlosmendez/miniforge3/lib/python3.10/site-packages/IPython/core/pylabtools.py:170: UserWarning: Glyph 8320 (\N{SUBSCRIPT ZERO}) missing from current font.
  fig.canvas.print_figure(bytes_io, **kw)
/Users/carlosmendez/miniforge3/lib/python3.10/site-packages/IPython/core/pylabtools.py:170: UserWarning: Glyph 8321 (\N{SUBSCRIPT ONE}) missing from current font.
  fig.canvas.print_figure(bytes_io, **kw)</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="ch09_Models_with_Natural_Logarithms_files/figure-html/cell-12-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
📊 Visual Insights:
   - Model 1 (linear): Straight line fit, but residuals may be heteroskedastic
   - Model 2 (log-linear): Best fit, captures curvature in original data
   - Model 3 (log-log): Both axes logged, captures elasticity
   - Model 4 (linear-log): Captures diminishing returns to education</code></pre>
</div>
</div>
<p>Beyond cross-sectional analysis, logarithms are equally powerful for <strong>time series data</strong>. Next, we explore how exponential growth becomes linear in logs.</p>
</section>
<section id="further-uses-exponential-growth" class="level2">
<h2 class="anchored" data-anchor-id="further-uses-exponential-growth">9.4 Further Uses: Exponential Growth</h2>
<p><strong>Application:</strong> Modeling exponential growth in time series data</p>
<p>Many economic series grow <strong>exponentially</strong> over time: <span class="math display">\[x_t = x_0 \times (1+r)^t\]</span></p>
<p>Where: - x₀ = initial value - r = constant growth rate - t = time period</p>
<p><strong>Taking logarithms:</strong> <span class="math display">\[\ln(x_t) = \ln(x_0) + \ln(1+r) \times t \approx \ln(x_0) + r \times t\]</span></p>
<p><strong>Key insight:</strong> Exponential growth in levels → <strong>linear growth in logs</strong>!</p>
<p><strong>Regression model:</strong> <span class="math display">\[\ln(x_t) = \beta_0 + \beta_1 \times t + \varepsilon\]</span></p>
<p>The slope β₁ directly estimates the growth rate r.</p>
<p><strong>Example:</strong> S&amp;P 500 stock index 1927-2019</p>
<div id="cell-32" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load S&amp;P 500 data</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>data_sp500 <span class="op">=</span> pd.read_stata(GITHUB_DATA_URL <span class="op">+</span> <span class="st">'AED_SP500INDEX.DTA'</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"S&amp;P 500 INDEX DATA (1927-2019)"</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data_sp500[[<span class="st">'year'</span>, <span class="st">'sp500'</span>, <span class="st">'lnsp500'</span>]].describe())</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">First and last years:"</span>)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data_sp500[[<span class="st">'year'</span>, <span class="st">'sp500'</span>, <span class="st">'lnsp500'</span>]].head(<span class="dv">3</span>))</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"..."</span>)</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data_sp500[[<span class="st">'year'</span>, <span class="st">'sp500'</span>, <span class="st">'lnsp500'</span>]].tail(<span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
S&amp;P 500 INDEX DATA (1927-2019)
======================================================================
             year        sp500    lnsp500
count    93.00000    93.000000  93.000000
mean   1973.00000   473.664307   4.817428
std      26.99074   710.751831   1.801842
min    1927.00000     6.920000   1.934416
25%    1950.00000    23.770000   3.168424
50%    1973.00000    96.470001   4.569232
75%    1996.00000   740.739990   6.607650
max    2019.00000  3230.780029   8.080479

First and last years:
     year      sp500   lnsp500
0  1927.0  17.660000  2.871302
1  1928.0  24.350000  3.192532
2  1929.0  21.450001  3.065725
...
      year        sp500   lnsp500
90  2017.0  2673.610107  7.891185
91  2018.0  2506.850098  7.826782
92  2019.0  3230.780029  8.080479</code></pre>
</div>
</div>
<div id="cell-33" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate exponential growth model</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"EXPONENTIAL GROWTH MODEL: ln(sp500) = β₀ + β₁(year)"</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>model_sp500 <span class="op">=</span> ols(<span class="st">'lnsp500 ~ year'</span>, data<span class="op">=</span>data_sp500).fit()</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_sp500.summary())</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>growth_rate <span class="op">=</span> model_sp500.params[<span class="st">'year'</span>]</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span> <span class="op">+</span> <span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"INTERPRETATION"</span>)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Estimated annual growth rate: </span><span class="sc">{</span><span class="dv">100</span><span class="op">*</span>growth_rate<span class="sc">:.4f}</span><span class="ss">% per year"</span>)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">This means the S&amp;P 500 grew at an average rate of </span><span class="sc">{</span><span class="dv">100</span><span class="op">*</span>growth_rate<span class="sc">:.2f}</span><span class="ss">% per year"</span>)</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"from 1927 to 2019 (not accounting for inflation or dividends)."</span>)</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Rule of 72: At </span><span class="sc">{</span><span class="dv">100</span><span class="op">*</span>growth_rate<span class="sc">:.2f}</span><span class="ss">% annual growth,"</span>)</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"the index doubles approximately every </span><span class="sc">{</span><span class="dv">72</span><span class="op">/</span>(<span class="dv">100</span><span class="op">*</span>growth_rate)<span class="sc">:.1f}</span><span class="ss"> years."</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
EXPONENTIAL GROWTH MODEL: ln(sp500) = β₀ + β₁(year)
======================================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                lnsp500   R-squared:                       0.958
Model:                            OLS   Adj. R-squared:                  0.957
Method:                 Least Squares   F-statistic:                     2071.
Date:                Wed, 21 Jan 2026   Prob (F-statistic):           2.16e-64
Time:                        00:01:48   Log-Likelihood:                -38.919
No. Observations:                  93   AIC:                             81.84
Df Residuals:                      91   BIC:                             86.90
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -124.0933      2.833    -43.798      0.000    -129.721    -118.465
year           0.0653      0.001     45.503      0.000       0.062       0.068
==============================================================================
Omnibus:                       19.480   Durbin-Watson:                   0.271
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               26.547
Skew:                           0.981   Prob(JB):                     1.72e-06
Kurtosis:                       4.732   Cond. No.                     1.45e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

======================================================================
INTERPRETATION
======================================================================
Estimated annual growth rate: 6.5337% per year

This means the S&amp;P 500 grew at an average rate of 6.53% per year
from 1927 to 2019 (not accounting for inflation or dividends).

Rule of 72: At 6.53% annual growth,
the index doubles approximately every 11.0 years.</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Key Concept 9.6: Linearizing Exponential Growth</strong></p>
<p>When a variable grows <strong>exponentially</strong> (x_t = x₀(1+r)^t), its logarithm grows <strong>linearly</strong>:</p>
<p><span class="math display">\[\ln(x_t) \approx \ln(x_0) + r \times t\]</span></p>
<p>This transformation is powerful because it converts a <strong>nonlinear</strong> growth pattern into a <strong>linear</strong> regression model, where the slope coefficient directly estimates the <strong>constant growth rate</strong> r.</p>
<p><strong>Practical implication:</strong> To estimate the average growth rate of any exponentially growing series (GDP, stock prices, population), simply regress ln(x) on time. The slope is the growth rate.</p>
</blockquote>
</section>
<section id="visualizing-exponential-growth" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-exponential-growth">Visualizing Exponential Growth</h2>
<div id="cell-36" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create visualization showing exponential vs linear in logs</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">16</span>, <span class="dv">6</span>))</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Panel A: Exponential growth in levels</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply retransformation bias correction</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="bu">len</span>(data_sp500)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>k <span class="op">=</span> <span class="dv">2</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>MSE <span class="op">=</span> np.<span class="bu">sum</span>(model_sp500.resid<span class="op">**</span><span class="dv">2</span>) <span class="op">/</span> (n <span class="op">-</span> k)</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>psp500 <span class="op">=</span> np.exp(model_sp500.fittedvalues) <span class="op">*</span> np.exp(MSE<span class="op">/</span><span class="dv">2</span>)</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(data_sp500[<span class="st">'year'</span>], data_sp500[<span class="st">'sp500'</span>], linewidth<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>             label<span class="op">=</span><span class="st">'Actual'</span>, color<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(data_sp500[<span class="st">'year'</span>], psp500, linewidth<span class="op">=</span><span class="dv">2</span>, linestyle<span class="op">=</span><span class="st">'--'</span>,</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>             label<span class="op">=</span><span class="st">'Fitted (exponential)'</span>, color<span class="op">=</span><span class="st">'blue'</span>)</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">'Year'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">'S&amp;P 500 Index'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">'Panel A: Exponential Growth in Levels'</span>,</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>                  fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend()</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Panel B: Linear growth in logs</span></span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].plot(data_sp500[<span class="st">'year'</span>], data_sp500[<span class="st">'lnsp500'</span>], linewidth<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a>             label<span class="op">=</span><span class="st">'Actual'</span>, color<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].plot(data_sp500[<span class="st">'year'</span>], model_sp500.fittedvalues, linewidth<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a>             linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="st">'Fitted (linear)'</span>, color<span class="op">=</span><span class="st">'blue'</span>)</span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">'Year'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">'ln(S&amp;P 500 Index)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb29-29"><a href="#cb29-29" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">'Panel B: Linear Growth in Logarithms'</span>,</span>
<span id="cb29-30"><a href="#cb29-30" aria-hidden="true" tabindex="-1"></a>                  fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb29-31"><a href="#cb29-31" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].legend()</span>
<span id="cb29-32"><a href="#cb29-32" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb29-33"><a href="#cb29-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-34"><a href="#cb29-34" aria-hidden="true" tabindex="-1"></a>plt.suptitle(<span class="st">'S&amp;P 500 Index: Exponential Growth Linearized by Logarithms'</span>,</span>
<span id="cb29-35"><a href="#cb29-35" aria-hidden="true" tabindex="-1"></a>             fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>, y<span class="op">=</span><span class="fl">1.00</span>)</span>
<span id="cb29-36"><a href="#cb29-36" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb29-37"><a href="#cb29-37" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb29-38"><a href="#cb29-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-39"><a href="#cb29-39" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">📊 Key Observation:"</span>)</span>
<span id="cb29-40"><a href="#cb29-40" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"   - Left panel: Exponential curve in levels (hard to model)"</span>)</span>
<span id="cb29-41"><a href="#cb29-41" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"   - Right panel: Straight line in logs (easy to model with OLS!)"</span>)</span>
<span id="cb29-42"><a href="#cb29-42" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"   - The slope of the line = average growth rate"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="ch09_Models_with_Natural_Logarithms_files/figure-html/cell-15-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
📊 Key Observation:
   - Left panel: Exponential curve in levels (hard to model)
   - Right panel: Straight line in logs (easy to model with OLS!)
   - The slope of the line = average growth rate</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Key Concept 9.7: The Rule of 72</strong></p>
<p>The <strong>Rule of 72</strong> provides a quick estimate of <strong>doubling time</strong> for compound growth:</p>
<p><span class="math display">\[\text{Doubling time} \approx \frac{72}{r}\]</span></p>
<p>where r is the <strong>percentage</strong> growth rate. This approximation derives from the logarithmic identity: ln(2) ≈ 0.693, combined with ln(1+r) ≈ r for small r.</p>
<p><strong>Examples:</strong> - S&amp;P 500 at 6.5% growth → doubles every 72/6.5 ≈ 11 years - GDP at 3% growth → doubles every 72/3 = 24 years - Population at 1% growth → doubles every 72/1 = 72 years</p>
<p><strong>Practical value:</strong> The Rule of 72 converts growth rates into an intuitive time horizon without needing a calculator.</p>
</blockquote>
</section>
<section id="key-takeaways" class="level2">
<h2 class="anchored" data-anchor-id="key-takeaways">Key Takeaways</h2>
<p><strong>Key Takeaways:</strong></p>
<ol type="1">
<li><strong>Natural logarithms</strong> let us work with <strong>proportionate changes</strong> instead of absolute changes.
<ul>
<li>Key approximation: Δln(x) ≈ Δx/x (proportionate change)</li>
<li>100 × Δln(x) ≈ percentage change in x</li>
<li>This approximation is excellent for small changes (&lt; 10%)</li>
</ul></li>
<li><strong>Four model specifications</strong> give different interpretations:</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th>Specification</th>
<th>Interpretation of β₁</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Linear</strong></td>
<td>y = β₀ + β₁x</td>
<td>Δy/Δx (absolute change)</td>
</tr>
<tr class="even">
<td><strong>Log-linear</strong></td>
<td>ln(y) = β₀ + β₁x</td>
<td>Semi-elasticity: (Δy/y)/Δx</td>
</tr>
<tr class="odd">
<td><strong>Log-log</strong></td>
<td>ln(y) = β₀ + β₁ln(x)</td>
<td>Elasticity: (Δy/y)/(Δx/x)</td>
</tr>
<tr class="even">
<td><strong>Linear-log</strong></td>
<td>y = β₀ + β₁ln(x)</td>
<td>Δy/(Δx/x)</td>
</tr>
</tbody>
</table>
<ol start="3" type="1">
<li><strong>Model selection</strong> depends on economic theory, data properties, and interpretation needs:
<ul>
<li>R² comparison (higher is better, but not the only criterion)</li>
<li>Economic theory should guide functional form choice</li>
<li>Log-linear is most common in applied economics (earnings, prices)</li>
</ul></li>
<li><strong>Earnings-Education results</strong> illustrate the four specifications:
<ul>
<li><strong>Linear:</strong> Each year of education → $5,021 more earnings</li>
<li><strong>Log-linear:</strong> Each year of education → 13.1% more earnings (best fit, R² = 0.334)</li>
<li><strong>Log-log:</strong> 1% more education → 1.48% more earnings (elasticity)</li>
<li><strong>Linear-log:</strong> 1% more education → $545 more earnings</li>
</ul></li>
<li><strong>Exponential growth</strong> becomes <strong>linear in logs:</strong>
<ul>
<li>If x grows exponentially: x_t = x₀(1+r)^t</li>
<li>Then ln(x) grows linearly: ln(x_t) ≈ ln(x₀) + r·t</li>
<li>Regression slope directly estimates the growth rate</li>
<li>S&amp;P 500: 6.5% annual growth (1927-2019), doubling every 11 years</li>
</ul></li>
<li><strong>When to use logarithmic transformations:</strong>
<ul>
<li>Dependent variable is right-skewed (earnings, prices, firm size)</li>
<li>Economic theory predicts percentage effects (elasticities)</li>
<li>Multiplicative relationships between variables</li>
<li>Exponential growth or decay patterns</li>
<li>Not when variables can be zero or negative (ln is undefined)</li>
</ul></li>
</ol>
<p><strong>Python Tools Used:</strong> - <code>numpy.log()</code>: Natural logarithm transformation - <code>numpy.exp()</code>: Exponential function (inverse of log) - <code>statsmodels.ols()</code>: OLS regression estimation - <code>pandas</code>: Data manipulation and summary statistics - <code>matplotlib</code>: Visualization of models and growth patterns</p>
<p><strong>Next Steps:</strong> - <strong>Chapter 10</strong>: Extend to multiple regression with several explanatory variables - <strong>Chapter 11</strong>: Statistical inference for multiple regression models - <strong>Chapter 15</strong>: Further variable transformations (polynomials, interactions)</p>
<hr>
<p><strong>Congratulations!</strong> You now understand how to choose between model specifications, interpret coefficients in log models, and estimate elasticities and semi-elasticities. These tools are fundamental to empirical work in labor economics, industrial organization, macroeconomics, and development economics!</p>
</section>
<section id="practice-exercises" class="level2">
<h2 class="anchored" data-anchor-id="practice-exercises">Practice Exercises</h2>
<p><strong>Exercise 1: Logarithmic Approximation Accuracy</strong></p>
<p>The logarithmic approximation Δln(x) ≈ Δx/x works well for small changes. Test its accuracy:</p>
<ol type="a">
<li>Compute the exact proportionate change and the log approximation for x increasing from 100 to 101 (1% change). How close are they?</li>
<li>Repeat for x increasing from 100 to 110 (10% change). Is the approximation still good?</li>
<li>Repeat for x increasing from 100 to 150 (50% change). What happens to the approximation error?</li>
<li>At what percentage change does the approximation error exceed 1 percentage point?</li>
</ol>
<p><strong>Exercise 2: Interpreting Semi-Elasticity</strong></p>
<p>A researcher estimates the following log-linear model: ln(wage) = 1.50 + 0.085 × experience, where wage is hourly wage in dollars and experience is years of work experience.</p>
<ol type="a">
<li>Interpret the coefficient 0.085 in economic terms.</li>
<li>What is the predicted percentage change in wages for a worker gaining 5 more years of experience?</li>
<li>Calculate the exact percentage change using 100 × (e^(0.085×5) - 1). How does it compare to the approximation?</li>
</ol>
<p><strong>Exercise 3: Interpreting Elasticity</strong></p>
<p>An economist estimates a demand function: ln(Q) = 5.2 - 1.3 × ln(P), where Q is quantity demanded and P is price.</p>
<ol type="a">
<li>What is the price elasticity of demand? Is demand elastic or inelastic?</li>
<li>If the price increases by 10%, what is the predicted percentage change in quantity demanded?</li>
<li>Why is the log-log specification natural for demand analysis?</li>
</ol>
<p><strong>Exercise 4: Model Specification Choice</strong></p>
<p>For each research question below, recommend the most appropriate model specification (linear, log-linear, log-log, or linear-log) and explain your reasoning:</p>
<ol type="a">
<li>How much does an additional bedroom add to house price (in dollars)?</li>
<li>What is the percentage return to each additional year of education?</li>
<li>What is the price elasticity of demand for gasoline?</li>
<li>How does GDP growth relate to years since a policy reform?</li>
</ol>
<p><strong>Exercise 5: Exponential Growth and Rule of 72</strong></p>
<p>A country’s real GDP per capita was $5,000 in 1990 and grew at an average rate of 4% per year.</p>
<ol type="a">
<li>Using the Rule of 72, approximately when did GDP per capita reach $10,000?</li>
<li>Write the exponential growth equation for this country’s GDP.</li>
<li>What regression model would you estimate to find the growth rate from data? Write the specification.</li>
<li>If another country grew at 2% per year, how many times longer would it take to double its GDP?</li>
</ol>
<p><strong>Exercise 6: Comparing Model Specifications with Data</strong></p>
<p>Using the earnings-education results from Section 9.3:</p>
<ol type="a">
<li>A worker has 12 years of education. Using the linear model, predict their earnings. Using the log-linear model, predict their earnings (hint: you need to exponentiate).</li>
<li>Repeat for a worker with 18 years of education. Which model gives a larger predicted difference between 12 and 18 years?</li>
<li>The log-linear model predicts a 13.1% increase per year of education regardless of current earnings. Explain why this is economically more appealing than a fixed dollar increase.</li>
<li>Why can’t we directly compare R² values between the linear model (R² = 0.289) and the log-linear model (R² = 0.334)?</li>
</ol>
</section>
<section id="case-studies" class="level2">
<h2 class="anchored" data-anchor-id="case-studies">Case Studies</h2>
<section id="case-study-logarithmic-models-for-global-labor-productivity" class="level3">
<h3 class="anchored" data-anchor-id="case-study-logarithmic-models-for-global-labor-productivity">Case Study: Logarithmic Models for Global Labor Productivity</h3>
<p>In this case study, you’ll apply logarithmic model specifications to analyze <strong>cross-country labor productivity</strong> — a central question in development economics. You’ll use the same Convergence Clubs dataset from earlier chapters, but now focus on how log transformations reveal economic relationships that linear models miss.</p>
<p><strong>Research Question:</strong> How do logarithmic transformations improve our understanding of cross-country productivity relationships and growth patterns?</p>
<p><strong>Background:</strong> Labor productivity varies enormously across countries — from less than $1,000 per worker in the poorest nations to over $100,000 in the richest. This extreme right-skewness makes logarithmic transformations essential for meaningful analysis. Development economists use semi-elasticities and elasticities to measure how factors like human capital and physical capital contribute to productivity differences.</p>
<p><strong>Dataset:</strong> We’ll use the <strong>Mendez Convergence Clubs dataset</strong> containing: - <strong>country</strong>: Country name (108 countries) - <strong>year</strong>: Year of observation (1990-2014) - <strong>lp</strong>: Labor productivity (output per worker, in dollars) - <strong>rk</strong>: Capital per worker (physical capital stock, in thousands of dollars) - <strong>hc</strong>: Human capital index (based on years of schooling and returns to education)</p>
<div id="cell-41" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the Convergence Clubs dataset</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>url_mendez <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/quarcs-lab/mendez2020-convergence-clubs-code-data/master/assets/dat.csv"</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>data_cc <span class="op">=</span> pd.read_csv(url_mendez)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"CONVERGENCE CLUBS DATASET"</span>)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Observations: </span><span class="sc">{</span><span class="bu">len</span>(data_cc)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Countries: </span><span class="sc">{</span>data_cc[<span class="st">'country'</span>]<span class="sc">.</span>nunique()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Years: </span><span class="sc">{</span>data_cc[<span class="st">'year'</span>]<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.0f}</span><span class="ss"> to </span><span class="sc">{</span>data_cc[<span class="st">'year'</span>]<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.0f}</span><span class="ss">"</span>)</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Variables: </span><span class="sc">{</span><span class="bu">list</span>(data_cc.columns)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">First 10 observations:"</span>)</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data_cc[[<span class="st">'country'</span>, <span class="st">'year'</span>, <span class="st">'lp'</span>, <span class="st">'rk'</span>, <span class="st">'hc'</span>]].head(<span class="dv">10</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="how-to-use-these-tasks" class="level3">
<h3 class="anchored" data-anchor-id="how-to-use-these-tasks">How to Use These Tasks</h3>
<ol type="1">
<li><strong>Read</strong> each task carefully before starting</li>
<li><strong>Write your code</strong> in the provided cells (replace <code>_____</code> blanks in guided tasks)</li>
<li><strong>Run your code</strong> to see results</li>
<li><strong>Answer the questions</strong> by interpreting your output</li>
<li><strong>Check your understanding</strong> against the Key Concepts</li>
</ol>
<p><strong>Progressive difficulty:</strong></p>
<ul>
<li>Tasks 1-2: <strong>Guided</strong> (fill in blanks with <code>_____</code>)</li>
<li>Tasks 3-4: <strong>Semi-guided</strong> (partial code structure provided)</li>
<li>Tasks 5-6: <strong>Independent</strong> (write from outline)</li>
</ul>
<p><strong>Tip:</strong> Type the code rather than copying — it helps reinforce the concepts!</p>
<section id="task-1-explore-productivity-data-guided" class="level4">
<h4 class="anchored" data-anchor-id="task-1-explore-productivity-data-guided">Task 1: Explore Productivity Data (Guided)</h4>
<p><strong>Objective:</strong> Understand why logarithmic transformations are essential for cross-country productivity data.</p>
<p><strong>Connection:</strong> Section 9.1 (Natural Logarithm Function)</p>
<p><strong>Your task:</strong> Filter the data to 2014, compute summary statistics for productivity in levels and logs, and compare the distributions.</p>
<ol type="a">
<li>What is the ratio of the highest to lowest labor productivity? What does this tell you about skewness?</li>
<li>How does the standard deviation change after log transformation?</li>
<li>Compare the mean and median in levels vs.&nbsp;logs. Which distribution is more symmetric?</li>
</ol>
<div id="cell-44" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Task 1: Explore Productivity Data (Guided)</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter to 2014 cross-section</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>data_2014 <span class="op">=</span> data_cc[data_cc[<span class="st">'year'</span>] <span class="op">==</span> _____].copy()</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Countries in 2014: </span><span class="sc">{</span><span class="bu">len</span>(data_2014)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create log-transformed variable</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>data_2014[<span class="st">'ln_lp'</span>] <span class="op">=</span> np.log(_____)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics: levels vs logs</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span> <span class="op">+</span> <span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"LABOR PRODUCTIVITY: LEVELS VS. LOGS"</span>)</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">In levels (lp):"</span>)</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data_2014[<span class="st">'lp'</span>].describe())</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Skewness: </span><span class="sc">{</span>data_2014[<span class="st">'lp'</span>]<span class="sc">.</span>skew()<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">In logarithms (ln_lp):"</span>)</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data_2014[<span class="st">'ln_lp'</span>].describe())</span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Skewness: </span><span class="sc">{</span>data_2014[<span class="st">'_____'</span>]<span class="sc">.</span>skew()<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Ratio of highest to lowest</span></span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Max/Min ratio: </span><span class="sc">{</span>data_2014[<span class="st">'lp'</span>]<span class="sc">.</span><span class="bu">max</span>() <span class="op">/</span> data_2014[<span class="st">'lp'</span>]<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.1f}</span><span class="ss">x"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="task-2-log-linear-model-for-productivity-guided" class="level4">
<h4 class="anchored" data-anchor-id="task-2-log-linear-model-for-productivity-guided">Task 2: Log-Linear Model for Productivity (Guided)</h4>
<p><strong>Objective:</strong> Estimate a log-linear model to measure the semi-elasticity of productivity with respect to human capital.</p>
<p><strong>Connection:</strong> Section 9.2 (Semi-Elasticities)</p>
<p><strong>Your task:</strong> Estimate ln(lp) = β₀ + β₁ × hc and interpret the coefficient as a semi-elasticity.</p>
<ol type="a">
<li>What is the estimated semi-elasticity of productivity with respect to human capital?</li>
<li>By what percentage does productivity increase for each additional unit of the human capital index?</li>
<li>Is the coefficient statistically significant at the 5% level?</li>
</ol>
<div id="cell-46" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Task 2: Log-Linear Model for Productivity (Guided)</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate: ln(lp) = β₀ + β₁ × hc</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>model_hc <span class="op">=</span> ols(<span class="st">'_____ ~ _____'</span>, data<span class="op">=</span>data_2014).fit()</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"LOG-LINEAR MODEL: ln(productivity) ~ human capital"</span>)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_hc.summary())</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Interpret the semi-elasticity</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>beta_hc <span class="op">=</span> model_hc.params[<span class="st">'hc'</span>]</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Semi-elasticity: </span><span class="sc">{</span>beta_hc<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Interpretation: Each unit increase in human capital is associated with"</span>)</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  a </span><span class="sc">{</span><span class="dv">100</span><span class="op">*</span>beta_hc<span class="sc">:.1f}</span><span class="ss">% _____ in labor productivity."</span>)</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">R² = </span><span class="sc">{</span>model_hc<span class="sc">.</span>rsquared<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="task-3-comparing-model-specifications-semi-guided" class="level4">
<h4 class="anchored" data-anchor-id="task-3-comparing-model-specifications-semi-guided">Task 3: Comparing Model Specifications (Semi-guided)</h4>
<p><strong>Objective:</strong> Estimate all four model specifications using productivity and capital per worker, then compare.</p>
<p><strong>Connection:</strong> Section 9.3 (Example with four models)</p>
<p><strong>Your tasks:</strong></p>
<ol type="a">
<li>Estimate four models: linear (lp ~ rk), log-linear (ln_lp ~ rk), log-log (ln_lp ~ ln_rk), and linear-log (lp ~ ln_rk)</li>
<li>Create a comparison table showing the specification, slope coefficient, interpretation, and R² for each model</li>
<li>Which model provides the best fit? Which provides the most economically meaningful interpretation?</li>
<li>Why might the log-log specification be particularly appropriate for the productivity-capital relationship?</li>
</ol>
<div id="cell-48" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Task 3: Comparing Model Specifications (Semi-guided)</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Create log-transformed variables</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>data_2014[<span class="st">'ln_rk'</span>] <span class="op">=</span> np.log(data_2014[<span class="st">'rk'</span>])</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate four models (fill in the formulas)</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>m1_linear  <span class="op">=</span> ols(<span class="st">'lp ~ rk'</span>, data<span class="op">=</span>data_2014).fit()</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>m2_loglin  <span class="op">=</span> ols(<span class="st">'ln_lp ~ rk'</span>, data<span class="op">=</span>data_2014).fit()</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>m3_loglog  <span class="op">=</span> ols(<span class="st">'ln_lp ~ ln_rk'</span>, data<span class="op">=</span>data_2014).fit()</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>m4_linlog  <span class="op">=</span> ols(<span class="st">'lp ~ ln_rk'</span>, data<span class="op">=</span>data_2014).fit()</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Create comparison table</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: Follow the pattern from Section 9.3</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"MODEL COMPARISON: Productivity and Capital"</span>)</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Your comparison table here</span></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a><span class="co"># ...</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<blockquote class="blockquote">
<p><strong>Key Concept 9.8: Functional Form and Cross-Country Comparisons</strong></p>
<p>When analyzing cross-country data, <strong>logarithmic models</strong> are essential because:</p>
<ol type="1">
<li><strong>Skewed distributions</strong> — Economic variables like GDP, productivity, and capital vary by factors of 100x or more across countries. Log transformations compress this range.</li>
<li><strong>Multiplicative relationships</strong> — Production functions in economics are multiplicative (Y = A × K^α × L^β), which become linear in logs.</li>
<li><strong>Meaningful comparisons</strong> — Percentage differences are more meaningful than absolute differences when comparing Malawi to the United States.</li>
</ol>
<p><strong>In practice:</strong> The log-log specification is standard in cross-country growth analysis because the slope coefficient directly estimates the <strong>output elasticity of capital</strong> — a key parameter in growth theory.</p>
</blockquote>
</section>
<section id="task-4-elasticity-of-productivity-with-respect-to-capital-semi-guided" class="level4">
<h4 class="anchored" data-anchor-id="task-4-elasticity-of-productivity-with-respect-to-capital-semi-guided">Task 4: Elasticity of Productivity with Respect to Capital (Semi-guided)</h4>
<p><strong>Objective:</strong> Estimate the elasticity of labor productivity with respect to capital and interpret it in the context of economic growth theory.</p>
<p><strong>Connection:</strong> Section 9.2 (Elasticities)</p>
<p><strong>Your tasks:</strong></p>
<ol type="a">
<li>Estimate the log-log model: ln(lp) = β₀ + β₁ × ln(rk). Report β₁ and R².</li>
<li>Interpret β₁ as an elasticity. Is there evidence of diminishing returns to capital (β₁ &lt; 1)?</li>
<li>Construct a 95% confidence interval for the elasticity. Does it include 1?</li>
<li>In growth theory, the output elasticity of capital is often assumed to be about 1/3. Test H₀: β₁ = 0.33 against H₁: β₁ ≠ 0.33.</li>
</ol>
<div id="cell-51" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Task 4: Elasticity of Productivity (Semi-guided)</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the log-log model from Task 3</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"LOG-LOG MODEL: ln(productivity) ~ ln(capital per worker)"</span>)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(m3_loglog.summary())</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Elasticity and confidence interval</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>elasticity <span class="op">=</span> m3_loglog.params[<span class="st">'ln_rk'</span>]</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>ci <span class="op">=</span> m3_loglog.conf_int().loc[<span class="st">'ln_rk'</span>]</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Elasticity: </span><span class="sc">{</span>elasticity<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"95% CI: [</span><span class="sc">{</span>ci[<span class="dv">0</span>]<span class="sc">:.4f}</span><span class="ss">, </span><span class="sc">{</span>ci[<span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss">]"</span>)</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Test H0: beta = 0.33</span></span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Your hypothesis test here</span></span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a><span class="co"># ...</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="task-5-productivity-growth-rates-independent" class="level4">
<h4 class="anchored" data-anchor-id="task-5-productivity-growth-rates-independent">Task 5: Productivity Growth Rates (Independent)</h4>
<p><strong>Objective:</strong> Estimate exponential growth rates for labor productivity across countries and apply the Rule of 72.</p>
<p><strong>Connection:</strong> Section 9.4 (Exponential Growth)</p>
<p><strong>Your tasks:</strong></p>
<ol type="a">
<li>Compute the average labor productivity across all countries for each year (1990-2014)</li>
<li>Estimate the exponential growth model: ln(avg_lp) = β₀ + β₁ × year. What is the estimated average annual growth rate?</li>
<li>Apply the Rule of 72: approximately how many years does it take for average global labor productivity to double?</li>
<li>Repeat the growth rate estimation for two regions or groups of countries (e.g., high-income vs.&nbsp;low-income). Do growth rates differ?</li>
</ol>
<div id="cell-53" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Task 5: Productivity Growth Rates (Independent)</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute average productivity per year</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Your code here</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="co"># ...</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="task-6-development-policy-brief-independent" class="level4">
<h4 class="anchored" data-anchor-id="task-6-development-policy-brief-independent">Task 6: Development Policy Brief (Independent)</h4>
<p><strong>Objective:</strong> Synthesize your findings into a policy-relevant summary.</p>
<p><strong>Connection:</strong> All sections</p>
<p><strong>Your task:</strong> Write a 200-300 word summary analyzing cross-country labor productivity using logarithmic models. Your brief should include:</p>
<ol type="1">
<li><strong>Data description:</strong> How many countries, what time period, key variables</li>
<li><strong>Model selection:</strong> Which logarithmic specification best captures the productivity-capital relationship and why</li>
<li><strong>Key findings:</strong> Elasticity estimates, semi-elasticity of human capital, growth rates</li>
<li><strong>Policy implications:</strong> What do these results suggest for developing countries seeking to increase productivity?</li>
</ol>
</section>
</section>
<section id="your-development-policy-brief" class="level3">
<h3 class="anchored" data-anchor-id="your-development-policy-brief">Your Development Policy Brief</h3>
<p><em>(Write your 200-300 word summary here)</em></p>
<hr>
<blockquote class="blockquote">
<p><strong>Key Concept 9.9: Logarithmic Models in Development Economics</strong></p>
<p>Logarithmic model specifications are the <strong>standard tool</strong> in development economics for analyzing cross-country differences because:</p>
<ul>
<li><strong>Semi-elasticities</strong> measure the percentage return to factors like education and human capital — directly informing policy about where to invest</li>
<li><strong>Elasticities</strong> from log-log models estimate production function parameters (output elasticity of capital) — testing whether countries face diminishing returns</li>
<li><strong>Growth rates</strong> from log-time regressions enable comparisons across countries growing at very different speeds</li>
</ul>
<p><strong>The bottom line:</strong> Without logarithmic transformations, cross-country analysis would be dominated by a few rich outliers and miss the economic relationships that matter for development policy.</p>
</blockquote>
</section>
<section id="what-youve-learned-from-this-case-study" class="level3">
<h3 class="anchored" data-anchor-id="what-youve-learned-from-this-case-study">What You’ve Learned from This Case Study</h3>
<p><strong>Congratulations!</strong> You’ve applied logarithmic model specifications to real cross-country economic data.</p>
<p><strong>Statistical Skills:</strong></p>
<ul>
<li>Applied log transformations to highly skewed cross-country data</li>
<li>Estimated and compared all four model specifications (linear, log-linear, log-log, linear-log)</li>
<li>Interpreted semi-elasticities (human capital → productivity)</li>
<li>Interpreted elasticities (capital → productivity, with diminishing returns)</li>
<li>Estimated exponential growth rates and applied the Rule of 72</li>
</ul>
<p><strong>Economic Insights:</strong></p>
<ul>
<li>Cross-country productivity distributions are highly right-skewed, requiring log transformations</li>
<li>Human capital and physical capital both contribute to productivity, but with diminishing returns</li>
<li>Log-log models connect directly to production function theory in economics</li>
<li>Growth rates vary substantially across countries and regions</li>
</ul>
<p><strong>Next Steps:</strong></p>
<ul>
<li><strong>Chapter 10</strong>: Add multiple explanatory variables simultaneously (multiple regression)</li>
<li><strong>Chapter 11</strong>: Test joint hypotheses about capital AND human capital effects</li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../notebooks_colab/ch08_Case_Studies_for_Bivariate_Regression.html" class="pagination-link" aria-label="Chapter 8: Case Studies for Bivariate Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Chapter 8: Case Studies for Bivariate Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../notebooks_colab/ch10_Data_Summary_for_Multiple_Regression.html" class="pagination-link" aria-label="Chapter 10: Data Summary for Multiple Regression">
        <span class="nav-page-text"><span class="chapter-title">Chapter 10: Data Summary for Multiple Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>