# ch03_The_Sample_Mean.R
# Updated for online execution portability

########## OVERVIEW ##########

# R Program
# copyright C 2021 by A. Colin Cameron
# Used for "Analysis of Economics Data: AN Introduction to Econometrics"
# by A. Colin Cameron (2021)

# To run you need file
#   AED_COINTOSSMEANS.DTA
#   AED_CENSUSAGEMEANS.DTA
# in your directory

########## SETUP ##########

# Clear the workspace
rm(list=ls())

# Set random seed for reproducibility
set.seed(42)

# GitHub data URL
github_data_url <- "https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/"

# Create output directories (optional - for saving figures and tables locally)
images_dir <- "images"
tables_dir <- "tables"
dir.create(images_dir, showWarnings = FALSE, recursive = TRUE)
dir.create(tables_dir, showWarnings = FALSE, recursive = TRUE)

# Load required libraries (install if needed)
if (!require("haven")) install.packages("haven")
library(haven)

# Function to load data from GitHub
load_data <- function(filename) {
  url <- paste0(github_data_url, filename)
  tryCatch({
    read_dta(url)
  }, error = function(e) {
    message("Error loading from GitHub: ", e$message)
    message("Attempting to load from local directory...")
    read_dta(file.path("../data_stata", filename))
  })
}

############

# This R program covers Chapter 3 of "Analysis of Economics Data"
#   3.1 RANDOM VARIABLES
#   3.2 SAMPLE GENERATED BY AN EXPERIMENT: COIN TOSSES
#   3.3 PROPERTIES OF THE SAMPLE MEAM
#   3.4 SAMPLING FROM A FINITE POPULATION: 1880 U.S. CENSUS
#   3.5 ESTIMATION OF THE POPULATION MEAN
#   3.6 SAMPLES OTHER THAN RANDOM SAMPLES
#   3.7 COMPUTER GENERATION OF A RANDOM SAMPLE


####   3.2 SAMPLE GENERATED BY AN EXPERIMENT: COIN TOSSES

# Draw one sample of size 30 from Bernoulli mu = p = 0.5
# Different draws from text as R uses different random number generator
rm(list=ls())
github_data_url <- "https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/"
library(haven)
load_data <- function(filename) {
  url <- paste0(github_data_url, filename)
  tryCatch({
    read_dta(url)
  }, error = function(e) {
    message("Error loading from GitHub: ", e$message)
    message("Attempting to load from local directory...")
    read_dta(file.path("../data_stata", filename))
  })
}
set.seed(10101)
u = runif(30,min=0,max=1)
x = ifelse(u > 0.5, 1, 0)
summary(cbind(x,u))
table(x)

# label variable x "Heads = 1 and Tails = 0"

# Figure 3.1: First panel
hist(x,xlab="Heads = 1 and Tails = 0")

# Way to directly write Figure 3.1 first panel to file
github_data_url <- "https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/"
images_dir <- "images"
png(file.path(images_dir, "ch03_fig1_cointoss.png"), width=800, height=600)
hist(x,xlab="Heads = 1 and Tails = 0")
dev.off()

# Means from 400 samples of 30 coin tosses for a fair coin
# This was created by Stata
# See the code at the end of this file that creates
# a qualitatively similar dataset in R

# Read in data for 400 coin tosses
rm(list=ls())
# Restore necessary variables
github_data_url <- "https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/"
images_dir <- "images"
library(haven)
load_data <- function(filename) {
  url <- paste0(github_data_url, filename)
  tryCatch({
    read_dta(url)
  }, error = function(e) {
    message("Error loading from GitHub: ", e$message)
    message("Attempting to load from local directory...")
    read_dta(file.path("../data_stata", filename))
  })
}
data.COINTOSSMEANS = load_data("AED_COINTOSSMEANS.DTA")

# Allow variables in database to be accessed simply by giving names
attach(data.COINTOSSMEANS)

# Summarize the data set
summary(data.COINTOSSMEANS)
head(data.COINTOSSMEANS, n=5)
summary(xbar)

# Figure 3.1: Second panel with histogram only
# Default histogram may have empty bins as xbar can only take values
#   0, 1/30, 2/30, ...., 29/30, 1
hist(xbar,xlab="Sample mean from each of 400 samples")

# Figure 3.1: Second panel with histogram plus normal density
hist(xbar, freq=FALSE)
x<-seq(0, 1, by=0.02)    # need x here and not some other name
curve(dnorm(x,mean(xbar),sd(xbar)), add=TRUE)

####  3.4 SAMPLING FROM A FINITE POPULATION: 1880 U.S. CENSUS

# These data based on a very large dataset not given here.

# Figure 3.2  Histogram of the very large dataset
# Not given here

# Figure 3.3 first panel - again from the very large dataset
# Not given here

# Figure 3.3 second panel - uses the following data

# Means from 100 samples of size 25
rm(list=ls())
github_data_url <- "https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/"
images_dir <- "images"
library(haven)
load_data <- function(filename) {
  url <- paste0(github_data_url, filename)
  tryCatch({
    read_dta(url)
  }, error = function(e) {
    message("Error loading from GitHub: ", e$message)
    message("Attempting to load from local directory...")
    read_dta(file.path("../data_stata", filename))
  })
}
data.CENSUSAGEMEANS = load_data("AED_CENSUSAGEMEANS.DTA")
attach(data.CENSUSAGEMEANS)
summary(data.CENSUSAGEMEANS)
head(data.CENSUSAGEMEANS, n=5)

# Figure 3.3 second panel  Histogram for 100 means
hist(mean, freq=FALSE)

# Figure 3.2 second panel  Histogram for 100 means plus normal curve
hist(mean, freq=FALSE)
x<-seq(0, 50, by=0.2)
curve(dnorm(x, mean(mean), sd(mean)), add=TRUE)

####   3.7 COMPUTER GENERATION OF A RANDOM SAMPLE

# Single sample
set.seed(10101)
x=runif(100,min=3,max=9)
y=rnorm(100,5,2)

# Mean of 400 coin toss samples each of size 30
set.seed(10101)
result.mean=array(dim=400)
result.stdev=array(dim=400)
for(i in 1:400){
    x=rbinom(30,1,0.5)
    result.mean[i]=mean(x)
    result.stdev[i]=sd(x)
}
mean(result.mean)
sd(result.mean)
summary(result.mean)

########## CLOSE OUTPUT

cat("Chapter 3 analysis complete.\n")
