{
  "hash": "d6abad587f26c0b9572e3fcd9d9f20ff",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 2. Univariate Data Summary\nexecute:\n  enabled: true\n  warning: false\n---\n\n\n**metricsAI: An Introduction to Econometrics with Python and AI in the Cloud**\n\n*[Carlos Mendez](https://carlos-mendez.org)*\n\n<img src=\"https://raw.githubusercontent.com/quarcs-lab/metricsai/main/images/ch02_visual_summary.jpg\" alt=\"Chapter 02 Visual Summary\" width=\"100%\">\n\nThis notebook provides an interactive introduction to univariate data analysis using Python. You'll learn how to summarize and visualize single-variable datasets using summary statistics and various chart types.\n\n[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/quarcs-lab/metricsai/blob/main/notebooks_colab/ch02_Univariate_Data_Summary.ipynb)\n<div class=\"chapter-resources\">\n<a href=\"https://www.youtube.com/watch?v=qegfQaM9UGE\" target=\"_blank\" class=\"resource-btn\">🎬 AI Video</a>\n<a href=\"https://carlos-mendez.my.canva.site/s02-univariate-data-summary-pdf\" target=\"_blank\" class=\"resource-btn\">✨ AI Slides</a>\n<a href=\"https://cameron.econ.ucdavis.edu/aed/traedv1_02\" target=\"_blank\" class=\"resource-btn\">📊 Cameron Slides</a>\n<a href=\"https://app.edcafe.ai/quizzes/6978644a2f5d08069e046930\" target=\"_blank\" class=\"resource-btn\">✏️ Quiz</a>\n<a href=\"https://app.edcafe.ai/chatbots/69789c1e2f5d08069e06f856\" target=\"_blank\" class=\"resource-btn\">🤖 AI Tutor</a>\n</div>\n\n\n## Chapter Overview\n\n**Univariate data** consists of observations on a single variable—for example, annual earnings, individual income, or GDP over time. This chapter teaches you how to summarize and visualize such data effectively.\n\n**What you'll learn:**\n\n- Calculate summary statistics (mean, median, standard deviation, quartiles, skewness, kurtosis)\n- Create visualizations for numerical data (box plots, histograms, kernel density estimates, line charts)\n- Visualize categorical data (bar charts, pie charts)\n- Apply data transformations (logarithms, standardization)\n- Work with time series transformations (moving averages, seasonal adjustment)\n\n**Datasets used:**\n\n- **AED_EARNINGS.DTA**: Annual earnings for 171 full-time working women aged 30 in 2010\n- **AED_REALGDPPC.DTA**: U.S. quarterly real GDP per capita from 1959 to 2020\n- **AED_HEALTHCATEGORIES.DTA**: U.S. health expenditures by category in 2018\n- **AED_FISHING.DTA**: Fishing site choices for 1,182 fishers\n- **AED_MONTHLYHOMESALES.DTA**: Monthly U.S. home sales from 1999 to 2015\n\n**Chapter outline:**\n\n- 2.1 Summary Statistics for Numerical Data\n- 2.2 Charts for Numerical Data\n- 2.3 Charts for Numerical Data by Category\n- 2.4 Charts for Categorical Data\n- 2.5 Data Transformation\n- 2.6 Data Transformations for Time Series Data\n- Practice Exercises\n- Case Studies\n\n## Setup\n\nRun this cell first to import all required packages and configure the environment.\n\n::: {#a28f97c6 .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Setup: Import libraries and configure environment\"}\n# --- Libraries ---\nimport numpy as np                        # numerical operations\nimport pandas as pd                       # data manipulation\nimport matplotlib.pyplot as plt           # plotting\nimport seaborn as sns                     # statistical visualizations\nfrom scipy import stats                   # statistical functions\nimport random\nimport os\n\n# --- Reproducibility ---\nRANDOM_SEED = 42\nrandom.seed(RANDOM_SEED)\nnp.random.seed(RANDOM_SEED)\nos.environ['PYTHONHASHSEED'] = str(RANDOM_SEED)\n\n# --- Data source ---\nGITHUB_DATA_URL = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/\"\n\n# --- Output directories ---\nIMAGES_DIR = 'images'\nTABLES_DIR = 'tables'\nos.makedirs(IMAGES_DIR, exist_ok=True)\nos.makedirs(TABLES_DIR, exist_ok=True)\n\n# --- Plotting style ---\nplt.style.use('dark_background')\nsns.set_style(\"darkgrid\")\nplt.rcParams.update({\n    'axes.facecolor': '#1a2235',\n    'figure.facecolor': '#12162c',\n    'grid.color': '#3a4a6b',\n    'figure.figsize': (10, 6),\n    'text.color': 'white',\n    'axes.labelcolor': 'white',\n    'xtick.color': 'white',\n    'ytick.color': 'white',\n    'axes.edgecolor': '#1a2235',\n})\n\nprint(\"✓ Setup complete! All packages imported successfully.\")\nprint(f\"✓ Random seed set to {RANDOM_SEED} for reproducibility.\")\nprint(f\"✓ Data will stream from: {GITHUB_DATA_URL}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Setup complete! All packages imported successfully.\n✓ Random seed set to 42 for reproducibility.\n✓ Data will stream from: https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/\n```\n:::\n:::\n\n\n## 2.1 Summary Statistics for Numerical Data\n\n**Summary statistics** provide a concise numerical description of a dataset. For a sample of size $n$, observations are denoted: $$x_1, x_2, \\ldots, x_n$$\n\n**Key summary statistics:**\n\n1. **Mean (average)**: $$\\bar{x} = \\frac{1}{n} \\sum_{i=1}^{n} x_i$$\n\n2. **Median**: The middle value when data are ordered\n\n3. **Standard deviation**: Measures the spread of data around the mean\n   $$s = \\sqrt{\\frac{1}{n-1} \\sum_{i=1}^{n} (x_i - \\bar{x})^2}$$\n\n4. **Quartiles**: Values that divide ordered data into fourths (25th, 50th, 75th percentiles)\n\n5. **Skewness**: Measures asymmetry of the distribution (positive = right-skewed)\n\n6. **Kurtosis**: Measures heaviness of distribution tails (higher = fatter tails)\n\n**Economic Example:** We'll examine annual earnings for full-time working women aged 30 in 2010.\n\n### Load Earnings Data\n\n::: {#f8cce459 .cell execution_count=2}\n``` {.python .cell-code}\n# Load the earnings dataset from GitHub\ndata_earnings = pd.read_stata(GITHUB_DATA_URL + 'AED_EARNINGS.DTA')\n\nprint(f\"✓ Data loaded successfully!\")\nprint(f\"  Shape: {data_earnings.shape[0]} observations, {data_earnings.shape[1]} variables\")\n# First 5 observations\ndata_earnings.head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Data loaded successfully!\n  Shape: 171 observations, 4 variables\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>earnings</th>\n      <th>education</th>\n      <th>age</th>\n      <th>gender</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>25000</td>\n      <td>14</td>\n      <td>30</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>40000</td>\n      <td>12</td>\n      <td>30</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>25000</td>\n      <td>13</td>\n      <td>30</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>38000</td>\n      <td>13</td>\n      <td>30</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>28800</td>\n      <td>12</td>\n      <td>30</td>\n      <td>0.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Summary Statistics\n\n::: {#4aae49d8 .cell execution_count=3}\n``` {.python .cell-code}\n# Basic descriptive statistics\ndata_earnings.describe()\n\n# Detailed statistics for earnings\nearnings = data_earnings['earnings']\n\nstats_dict = {\n    'Count': len(earnings),\n    'Mean': earnings.mean(),\n    'Std Dev': earnings.std(),\n    'Min': earnings.min(),\n    '25th percentile': earnings.quantile(0.25),\n    'Median': earnings.median(),\n    '75th percentile': earnings.quantile(0.75),\n    'Max': earnings.max(),\n    'Skewness': stats.skew(earnings),\n    'Kurtosis': stats.kurtosis(earnings)  # Excess kurtosis (raw kurtosis - 3)\n}\n\n# Summary statistics for earnings\nfor key, value in stats_dict.items():\n    if key in ['Count']:\n        print(f\"{key:20s}: {value:,.0f}\")\n    elif key in ['Skewness', 'Kurtosis']:\n        print(f\"{key:20s}: {value:.2f}\")\n    else:\n        print(f\"{key:20s}: ${value:,.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCount               : 171\nMean                : $41,412.69\nStd Dev             : $25,527.05\nMin                 : $1,050.00\n25th percentile     : $25,000.00\nMedian              : $36,000.00\n75th percentile     : $49,000.00\nMax                 : $172,000.00\nSkewness            : 1.71\nKurtosis            : 4.32\n```\n:::\n:::\n\n\n**Key findings from the 171 full-time working women aged 30:**\n\n**1. Central Tendency - Mean vs Median:**\n\n- **Mean = \\$41,412.69**: The arithmetic average\n- **Median = \\$36,000**: The middle value\n- **Gap = \\$5,412** (mean is 15% higher than median)\n- **Why?** This signals right skewness—some high earners pull the mean upward\n\n**2. Spread - Standard Deviation:**\n\n- **Std Dev = \\$25,527.05**\n- This equals 61.6% of the mean (substantial variation)\n- **Rule of thumb:** About 68% of women earn within \\$41,413 ± \\$25,527 = \\$15,886 to \\$66,940\n\n**3. Range and Quartiles:**\n\n- **Minimum = \\$1,050** (possibly part-time misclassified, or very low earner)\n- **25th percentile = \\$25,000** (bottom quarter earns ≤\\$25k)\n- **75th percentile = \\$49,000** (top quarter earns ≥\\$49k)\n- **Maximum = \\$172,000** (highest earner makes 164× more than lowest!)\n- **Interquartile range (IQR) = \\$24,000** (middle 50% span \\$24k)\n\n**4. Shape Measures:**\n\n- **Skewness = 1.71** (strongly positive)\n  - Values > 1 indicate strong right skew\n  - **Interpretation guidelines:**\n    - |Skewness| < 0.5: approximately symmetric\n    - 0.5 < |Skewness| < 1: moderately skewed\n    - |Skewness| > 1: highly skewed (like our data)\n\n  - Long right tail with high earners\n  - Distribution is NOT symmetric\n- **Kurtosis = 4.32** (excess kurtosis, compared to normal = 0)\n  - **Note:** Python's `scipy.stats.kurtosis()` reports *excess kurtosis* by default (raw kurtosis - 3)\n  - Raw kurtosis = 7.32; Excess kurtosis = 4.32 (what we report here)\n  - Normal distribution has raw kurtosis = 3, so excess kurtosis = 0\n  - Heavier tails than normal distribution\n  - More extreme values than a bell curve would predict\n  - **Interpretation guidelines (excess kurtosis):**\n    - Excess kurtosis < 0: light tails (platykurtic)\n    - Excess kurtosis ≈ 0: normal tails (mesokurtic)\n    - Excess kurtosis > 0: heavy tails (leptokurtic - like our data)\n\n  - Greater chance of outliers\n\n**Economic interpretation:**\nEarnings distributions are typically right-skewed because:\n\n- **Lower bound exists**: Can't earn less than zero (or minimum wage)\n- **No upper bound**: Some professionals earn very high incomes\n- **Labor market structure**: Most workers cluster around median, but executives, specialists, and entrepreneurs create a long right tail\n\n**Practical implication:** The median (36,000) is a better measure of \"typical\" earnings than the mean (41,413) because it's not inflated by high earners.\n\n> **Key Concept 2.1: Summary Statistics**\n>\n> Summary statistics condense datasets into interpretable measures of central tendency (mean, median) and dispersion (standard deviation, quartiles). The median is more robust to outliers than the mean, making it preferred for skewed distributions common in economic data like earnings and wealth.\n\n### Box Plot\n\nA **box plot** (or box-and-whisker plot) visualizes key summary statistics:\n\n- **Box**: Extends from the 25th to 75th percentile (interquartile range)\n- **Red line**: Median (50th percentile)\n- **Whiskers**: Extend to minimum and maximum values (or 1.5 × IQR from quartiles)\n- **Dots**: Outliers beyond the whiskers\n\n::: {#9bd31996 .cell execution_count=4}\n``` {.python .cell-code}\n# Create box plot of earnings\nfig, ax = plt.subplots(figsize=(10, 6))\nbp = ax.boxplot(earnings, vert=False, patch_artist=True,\n                boxprops=dict(facecolor='lightblue', alpha=0.7),  # alpha = transparency (0 = invisible, 1 = opaque)\n                medianprops=dict(color='red', linewidth=2))\nax.set_xlabel('Annual earnings (in dollars)', fontsize=12)\nax.set_title('Box Plot of Annual Earnings', fontsize=14, fontweight='bold')\nax.grid(True, alpha=0.3)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch02_Univariate_Data_Summary_files/figure-html/cell-5-output-1.png){width=950 height=565}\n:::\n:::\n\n\n**What the box plot reveals:**\n\n**1. The Box (Interquartile Range):**\n\n- Extends from \\$25,000 (Q1) to \\$49,000 (Q3)\n- Contains the middle 50% of earners\n- Width of \\$24,000 shows moderate spread in the middle\n\n**2. The Red Line (Median):**\n\n- Located at \\$36,000\n- Positioned closer to the LOWER edge of the box\n- This leftward position confirms right skewness\n\n**3. The Whiskers:**\n\n- Lower whisker extends to \\$1,050 (minimum)\n- Upper whisker extends to outliers\n- Right whisker is MUCH longer than left whisker (asymmetry)\n\n**4. The Outliers (dots on right):**\n\n- Several points beyond the upper whisker\n- Represent high earners (likely \\$100k+)\n- Maximum at \\$172,000 is an extreme outlier\n\n**Visual insights:**\n\n- **NOT symmetric**: If symmetric, median would be in center of box\n- **Right tail dominates**: Upper whisker + outliers extend much farther than lower whisker\n- **Concentration**: Most data packed in the 25k-49k range\n- **Rare extremes**: A few very high earners create the long right tail\n\n**Comparison to summary statistics:**\n\n- Box plot VISUALLY confirms what skewness (1.71) told us numerically\n- Quartiles (25k, 36k, 49k) match the box structure\n- Outliers explain why kurtosis (4.32) is high—heavy tails\n\n**Economic story:** The typical woman in this sample earns 25k-49k, but a small group of high earners (doctors, lawyers, executives?) creates substantial inequality within this age-30 cohort.\n\n## 2.2 Charts for Numerical Data\n\nBeyond summary statistics, **visualizations** reveal patterns in data that numbers alone might miss.\n\n**Common charts for numerical data:**\n\n1. **Histogram**: Shows the frequency distribution by grouping data into bins\n2. **Kernel density estimate**: A smoothed histogram that estimates the underlying continuous distribution\n3. **Line chart**: For ordered data (especially time series)\n\n**Bin width matters:** Wider bins give a coarse overview; narrower bins show more detail but can be noisy.\n\n### Histograms with Different Bin Widths\n\n::: {#d2b4696a .cell execution_count=5}\n``` {.python .cell-code}\n# Create histograms with different bin widths\nfig, axes = plt.subplots(1, 2, figsize=(14, 5))\n\n# Panel A: Wider bins ($15,000)\naxes[0].hist(earnings, bins=range(0, int(earnings.max()) + 15000, 15000),\n             edgecolor='black', alpha=0.7, color='steelblue')  # alpha = transparency (0 = invisible, 1 = opaque)\naxes[0].set_xlabel('Annual Earnings (in dollars)', fontsize=11)\naxes[0].set_ylabel('Frequency', fontsize=11)\naxes[0].set_title('Panel A: Bin width = $15,000', fontsize=12, fontweight='bold')\naxes[0].grid(True, alpha=0.3)\n\n# Panel B: Narrower bins ($7,500)\naxes[1].hist(earnings, bins=range(0, int(earnings.max()) + 7500, 7500),\n             edgecolor='black', alpha=0.7, color='steelblue')\naxes[1].set_xlabel('Annual Earnings (in dollars)', fontsize=11)\naxes[1].set_ylabel('Frequency', fontsize=11)\naxes[1].set_title('Panel B: Bin width = $7,500', fontsize=12, fontweight='bold')\naxes[1].grid(True, alpha=0.3)\n\nplt.suptitle('Histograms of Annual Earnings', fontsize=14, fontweight='bold', y=1.02)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch02_Univariate_Data_Summary_files/figure-html/cell-6-output-1.png){width=1330 height=494}\n:::\n:::\n\n\n**Panel A: Wider bins (\\$15,000):**\n\n- **Reveals overall shape**: Right-skewed distribution with long right tail\n- **Peak location**: Highest bar is in the \\$15k-\\$30k range\n- **Pattern**: Frequencies decline as earnings increase\n- **Advantages**: Simple, clear overall pattern, less \"noisy\"\n- **Disadvantages**: Hides fine details, obscures multiple modes\n\n**Panel B: Narrower bins (\\$7,500):**\n\n- **Reveals more detail**: Multiple peaks visible within the distribution\n- **Peak location**: Clearer concentration around \\$22.5k-\\$30k\n- **Secondary peaks**: Visible around \\$37.5k-\\$45k (possible clustering at round numbers?)\n- **Advantages**: Shows fine structure, reveals potential clustering\n- **Disadvantages**: More \"jagged,\" can look noisy\n\n**Key observations across both panels:**\n\n1. **Right skewness confirmed**: Both histograms show long right tail extending to \\$172,000\n\n2. **Modal region**: Most common earnings are in the \\$15k-\\$45k range\n   - This contains ~75% of observations\n   - Consistent with Q1 (\\$25k) and Q3 (\\$49k)\n\n3. **Sparse right tail**: Very few observations above \\$90k\n   - But these high earners substantially influence the mean\n   - This is why mean (\\$41,413) > median (\\$36,000)\n\n4. **Bin width matters**: - **Too wide**: Oversimplifies, may miss important features\n   - **Too narrow**: Introduces noise, harder to see overall pattern\n   - **Rule of thumb**: Try multiple bin widths to understand your data\n\n**Economic interpretation:**\nThe clustering in the \\$25k-\\$45k range likely reflects:\n\n- **Entry-level professional salaries** for college graduates\n- **Regional wage variations** within the sample\n- **Occupational differences** (teachers vs. nurses vs. business professionals)\n- **Experience effects** (all are age 30, but different career progressions)\n\n**Statistical lesson:** Always experiment with bin widths in histograms—different choices reveal different aspects of the data!\n\n> **Key Concept 2.2: Histograms and Density Plots**\n>\n> Histograms visualize distributions using bins whose width determines the level of detail. Kernel density estimates provide smooth approximations of the underlying distribution, while line charts are ideal for time series data to show trends and patterns over time.\n\n### Kernel Density Estimate\n\nA **kernel density estimate (KDE)** is a smoothed version of a histogram. It estimates the underlying continuous probability density function.\n\n**Advantages:**\n\n- Smooth, continuous curve (no arbitrary bin edges)\n- Easier to see the overall shape\n- Can compare to theoretical distributions (e.g., normal distribution)\n\n**How it works:** Instead of fixed bins, KDE uses overlapping \"windows\" that give more weight to nearby observations.\n\n::: {#d147c098 .cell execution_count=6}\n``` {.python .cell-code}\n# Create kernel density estimate\nfig, ax = plt.subplots(figsize=(10, 6))\nearnings.plot.kde(ax=ax, linewidth=2, color='#22d3ee', bw_method=0.3)  # bandwidth: lower = more detail, higher = smoother\nax.set_xlabel('Annual Earnings (in dollars)', fontsize=12)\nax.set_ylabel('Density', fontsize=12)\nax.set_title('Kernel Density Estimate of Earnings', fontsize=14, fontweight='bold')\nax.grid(True, alpha=0.3)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch02_Univariate_Data_Summary_files/figure-html/cell-7-output-1.png){width=950 height=565}\n:::\n:::\n\n\n**What is KDE showing?**\n\nThe KDE is a smooth, continuous estimate of the probability density function—think of it as a \"smoothed histogram without arbitrary bins.\"\n\n**Key features of the earnings KDE:**\n\n**1. Peak (Mode):**\n\n- Highest density around **\\$30,000-\\$35,000**\n- This is the most \"probable\" earnings level\n- Slightly below the median (\\$36,000), consistent with right skew\n\n**2. Shape:**\n\n- **Clear right skew**: Long tail extending to \\$172,000\n- **NOT bell-shaped**: Would be symmetric if normally distributed\n- **Unimodal**: Single dominant peak (not bimodal)\n- **Steep left side**: Density drops quickly below \\$20k\n- **Gradual right side**: Density tapers slowly above \\$50k\n\n**3. Tail behavior:**\n\n- **Left tail**: Short and bounded (can't go below ~\\$0)\n- **Right tail**: Long and heavy (extends to \\$172k)\n- **Asymmetry ratio**: Right tail is ~5× longer than left tail\n\n**4. Concentration:**\n\n- Most density (probability mass) is between **\\$15k-\\$60k**\n- Above \\$80k, density is very low but not zero\n- This confirms that high earners are rare but present\n\n**Comparison to normal distribution:**\nIf earnings were normally distributed, the KDE would be:\n\n- **Symmetric** (it's not—it's right-skewed)\n- **Bell-shaped** (it's not—it's asymmetric)\n- **Same mean and median** (they differ by \\$5,413)\n- **Unimodal** (it's not—there is another peak around \\$70k)\n\n**Advantages of KDE over histograms:**\n\n1. **No arbitrary bins**: Smooth curve independent of bin choices\n2. **Shows probability density**: Y-axis represents likelihood, not counts\n3. **Easier to compare**: Can overlay multiple KDEs (e.g., male vs. female earnings)\n4. **Professional appearance**: Smooth curves for publications\n\n**Statistical insight:** \nThe KDE reveals that earnings are NOT normally distributed—they follow a log-normal-like distribution common in economic data. This justifies logarithmic transformations (see Section 2.5) for statistical modeling.\n\n**Practical implication:** \nWhen predicting earnings, the \"most likely\" value is around \\$30k-\\$35k, NOT the mean (\\$41,413). The mean is inflated by rare high earners.\n\n### Time Series Plot\n\n**Line charts** are ideal for **time series data**—observations ordered by time. They show how a variable changes over time.\n\n**Example:** U.S. real GDP per capita from 1959 to 2020 (in constant 2012 dollars). This measures average economic output per person, adjusted for inflation.\n\n::: {#4499ea28 .cell execution_count=7}\n``` {.python .cell-code}\n# Load GDP data\ndata_gdp = pd.read_stata(GITHUB_DATA_URL + 'AED_REALGDPPC.DTA')\n\n# GDP data summary\ndata_gdp[['realgdppc', 'year']].describe()\n\n# Create time series plot\nfig, ax = plt.subplots(figsize=(12, 6))\nax.plot(data_gdp['daten'], data_gdp['realgdppc'], linewidth=2, color='#22d3ee')\nax.set_xlabel('Year', fontsize=12)\nax.set_ylabel('Real GDP per capita (in 2012 dollars)', fontsize=12)\nax.set_title('U.S. Real GDP per Capita', fontsize=14, fontweight='bold')\nax.grid(True, alpha=0.3)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch02_Univariate_Data_Summary_files/figure-html/cell-8-output-1.png){width=1142 height=565}\n:::\n:::\n\n\n**What this chart shows:**\n\nU.S. real GDP per capita from 1959 to 2020, measured in constant 2012 dollars (inflation-adjusted).\n\n**Key trends observed:**\n\n**1. Long-run growth:**\n\n- **1959**: ~\\$17,000 per person\n- **2020**: ~\\$60,000 per person\n- **Total growth**: 253% increase (3.5× larger)\n- **Annual growth rate**: ~2.1% per year (compound)\n\n**2. Business cycle patterns (recessions visible as dips):**\n\n- **Early 1960s**: Mild slowdown\n- **1973-1975**: Oil crisis recession (OPEC embargo)\n- **1980-1982**: Double-dip recession (Volcker's inflation fight)\n- **1990-1991**: Gulf War recession (brief)\n- **2001**: Dot-com bubble burst\n- **2008-2009**: GREAT RECESSION (deepest post-war decline)\n  - GDP per capita fell from \\$55k to \\$51k\n  - Took until 2015 to recover pre-crisis level\n- **2020**: COVID-19 pandemic (sharp, sudden drop)\n\n**3. Trend characteristics:**\n\n- **Not a straight line**: Growth punctuated by recessions\n- **Recessions are temporary**: Economy always recovers to trend\n- **Growth is the norm**: Upward drift dominates short-term fluctuations\n- **Increasing volatility?** Recent cycles seem larger (2008, 2020)\n\n**4. Summary statistics from the data:**\n\n- **Mean GDP per capita**: \\$37,941 (over full 1959-2020 period)\n- **Median**: \\$35,500 (slightly below mean due to recent growth)\n- **Min**: ~\\$17,000 (1959 start)\n- **Max**: ~\\$60,000 (pre-COVID peak 2019)\n\n**Economic interpretation:**\n\n**Why does GDP per capita grow?**\n\n1. **Technological progress**: Better machines, software, processes\n2. **Capital accumulation**: More factories, infrastructure, equipment\n3. **Human capital**: Better education, training, skills\n4. **Productivity gains**: Workers produce more per hour worked\n\n**Why the recessions?**\n\n- **Demand shocks**: Sudden drops in spending (2008 financial crisis, 2020 lockdowns)\n- **Supply shocks**: Oil crises, disruptions (1973, 2020)\n- **Policy errors**: Monetary policy too tight (1980-82)\n- **Financial crises**: Credit crunches, asset bubbles bursting\n\n**Why does it matter?**\n\n- **Living standards**: GDP per capita measures average prosperity\n- **Real vs. nominal**: Chart uses 2012 dollars, so it's REAL growth, not inflation\n- **Per capita matters**: Total GDP could grow just from population increase; per capita shows individual prosperity\n\n**Statistical lesson:** Time series plots are essential for understanding economic trends, cycles, and structural breaks that cross-sectional data would miss.\n\n> **Key Concept 2.3: Time Series Visualization**\n>\n> Line charts display time-ordered data, revealing trends, cycles, and structural breaks. For economic time series, visualizing the full historical context helps identify patterns like recessions, growth periods, and policy impacts.\n\nThe previous section focused on visualizing single numerical variables. Now we shift to *categorical breakdowns*—how to display numerical data when it's naturally divided into groups or categories (like health spending by service type).\n\n## 2.3 Charts for Numerical Data by Category\n\nSometimes numerical data are naturally divided into **categories**. For example, total health expenditures broken down by type of service.\n\n**Bar charts** (or column charts) are the standard visualization:\n\n- Each category gets a bar\n- Bar height represents the category's value\n- Useful for comparing values across categories\n\n**Example:** U.S. health expenditures in 2018 totaled \\$3,653 billion (18% of GDP), split across 13 categories.\n\n::: {#c928339e .cell execution_count=8}\n``` {.python .cell-code}\n# Load health expenditure data\ndata_health = pd.read_stata(GITHUB_DATA_URL + 'AED_HEALTHCATEGORIES.DTA')\n\n# Health expenditure categories (2018)\ndisplay(data_health)\nprint(f\"Total expenditures: ${data_health['expenditures'].sum():,.0f} billion\")\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>category</th>\n      <th>expenditures</th>\n      <th>cat_short</th>\n      <th>exp_short</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Hospital</td>\n      <td>1192</td>\n      <td>Hospital</td>\n      <td>1192.0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Physician and clinical</td>\n      <td>726</td>\n      <td>Physician</td>\n      <td>726.0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Other Professional</td>\n      <td>104</td>\n      <td>Other</td>\n      <td>104.0</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Dental</td>\n      <td>136</td>\n      <td>Drugs</td>\n      <td>136.0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Other Health &amp; Personal</td>\n      <td>192</td>\n      <td></td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Home Health Care</td>\n      <td>102</td>\n      <td></td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Nursing Care</td>\n      <td>169</td>\n      <td></td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>Drugs &amp; Supplies</td>\n      <td>456</td>\n      <td></td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>Govt. Administration</td>\n      <td>48</td>\n      <td></td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>Net Cost Insurance</td>\n      <td>259</td>\n      <td></td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>Govt. Public Health</td>\n      <td>94</td>\n      <td></td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>Noncommercial Research</td>\n      <td>53</td>\n      <td></td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>Structures &amp; Equipment</td>\n      <td>122</td>\n      <td></td>\n      <td>NaN</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nTotal expenditures: $3,653 billion\n```\n:::\n:::\n\n\n### Bar Chart\n\n::: {#65590dfc .cell execution_count=9}\n``` {.python .cell-code}\n# Create bar chart (sorted by expenditure)\nfig, ax = plt.subplots(figsize=(12, 6))\ndata_health_sorted = data_health.sort_values('expenditures', ascending=False)\nbars = ax.bar(range(len(data_health_sorted)), data_health_sorted['expenditures'],\n              color='steelblue', edgecolor='black', alpha=0.7)\nax.set_xticks(range(len(data_health_sorted)))\nax.set_xticklabels(data_health_sorted['category'], rotation=45, ha='right', fontsize=10)\nax.set_ylabel('Expenditures (in $ billions)', fontsize=12)\nax.set_title('U.S. Health Expenditures by Category (2018)',\n             fontsize=14, fontweight='bold')\nax.grid(True, alpha=0.3, axis='y')\n\nplt.tight_layout()\nplt.show()\n\n# Top 3 categories\nprint(f\"1. {data_health_sorted.iloc[0]['category']}: ${data_health_sorted.iloc[0]['expenditures']:.0f}B\")\nprint(f\"2. {data_health_sorted.iloc[1]['category']}: ${data_health_sorted.iloc[1]['expenditures']:.0f}B\")\nprint(f\"3. {data_health_sorted.iloc[2]['category']}: ${data_health_sorted.iloc[2]['expenditures']:.0f}B\")\n```\n\n::: {.cell-output .cell-output-display}\n![](ch02_Univariate_Data_Summary_files/figure-html/cell-10-output-1.png){width=1142 height=565}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n1. Hospital: $1192B\n2. Physician and clinical: $726B\n3. Drugs & Supplies: $456B\n```\n:::\n:::\n\n\n**Total U.S. health spending in 2018: \\$3,653 billion (18% of GDP)**\n\n**Top 5 categories (ranked by spending):**\n\n**1. Hospital care: \\$1,192 billion (32.6%)**\n\n- By far the largest category\n- Inpatient care, emergency rooms, outpatient hospital services\n- Dominated by labor costs (nurses, doctors, staff) and overhead\n\n**2. Physician and clinical services: \\$726 billion (19.9%)**\n\n- Doctor visits, outpatient clinics, medical specialists\n- Second-largest but still 39% less than hospitals\n- Growing due to aging population and chronic disease management\n\n**3. Drugs and supplies: \\$456 billion (12.5%)**\n\n- Prescription drugs, over-the-counter medications, medical supplies\n- Controversial due to high U.S. drug prices vs. other countries\n- Rising rapidly due to specialty biologics and new therapies\n\n**4. Net cost of insurance: \\$259 billion (7.1%)**\n\n- Administrative costs of private health insurance\n- Overhead, marketing, profit margins\n- Does not include government administration (separate category)\n\n**5. Other health and personal: \\$192 billion (5.3%)**\n\n- Various services not classified elsewhere\n- Home health aides, personal care, etc.\n\n**Bottom categories:**\n\n- **Government administration: \\$48 billion** (Medicare, Medicaid overhead)\n- **Noncommercial research: \\$53 billion** (NIH, university research)\n- **Government public health: \\$94 billion** (CDC, state/local health departments)\n\n**Key insights:**\n\n**1. Hospital dominance:**\n\n- Hospitals alone account for nearly **1/3 of all health spending**\n- More than physicians, drugs, and nursing care COMBINED\n- Reflects high fixed costs of hospital infrastructure\n\n**2. Concentration:**\n\n- Top 3 categories (Hospital, Physician, Drugs) = **65% of total**\n- Middle 50% of spending across just 3 categories\n- Long tail of smaller categories\n\n**3. Administrative costs:**\n\n- Insurance administration (\\$259B) + Government admin (\\$48B) = **\\$307B total**\n- That's 8.4% of health spending just on paperwork and administration\n- For comparison: Administrative costs are ~2% in single-payer systems\n\n**4. Prevention vs. treatment:**\n\n- Public health: \\$94B (2.6% of total)\n- Hospital care: \\$1,192B (32.6% of total)\n- **Ratio: 12.7× more on treatment than prevention**\n\n**Economic interpretation:**\n\n**Why so expensive?**\n\n- **Labor-intensive**: Healthcare requires highly-trained, expensive workers\n- **Technology**: Advanced equipment and facilities are costly\n- **Fragmentation**: Multiple payers, complex billing increases administrative costs\n- **Aging population**: Older Americans consume more healthcare\n- **Chronic diseases**: Diabetes, heart disease, obesity drive spending\n\n**International comparison:** U.S. spends ~18% of GDP on healthcare vs. 9-12% in other developed countries, yet doesn't have better health outcomes. Much debate centers on the efficiency of this spending.\n\n**Statistical lesson:** Bar charts are ideal for comparing categorical data—they make it immediately obvious that hospital care dominates U.S. health spending.\n\n> **Key Concept 2.4: Bar Charts for Categorical Data**\n>\n> Bar charts and column charts effectively display categorical data by using bar length to represent values. This makes comparisons across categories immediate and intuitive, highlighting which categories dominate.\n\n## 2.4 Charts for Categorical Data\n\n**Categorical data** consist of observations that fall into discrete categories (e.g., fishing site choice: beach, pier, private boat, charter boat).\n\n**How to summarize:**\n\n- **Frequency table**: Count observations in each category\n- **Relative frequency**: Express as proportions or percentages\n\n**How to visualize:**\n\n- **Pie chart**: Slices represent proportion of total\n- **Bar chart**: Bars represent frequency or proportion\n\n**Example:** Fishing site chosen by 1,182 recreational fishers (4 possible sites).\n\n::: {#a702d534 .cell execution_count=10}\n``` {.python .cell-code}\n# Load fishing data\ndata_fishing = pd.read_stata(GITHUB_DATA_URL + 'AED_FISHING.DTA')\n\n# Create frequency table\nmode_freq = data_fishing['mode'].value_counts()\nmode_relfreq = data_fishing['mode'].value_counts(normalize=True)\nmode_table = pd.DataFrame({\n    'Frequency': mode_freq,\n    'Relative Frequency (%)': (mode_relfreq * 100).round(2)\n})\n\n# Frequency distribution of fishing mode\ndisplay(mode_table)\nprint(f\"Total observations: {len(data_fishing):,}\")\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Frequency</th>\n      <th>Relative Frequency (%)</th>\n    </tr>\n    <tr>\n      <th>mode</th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>charter</th>\n      <td>452</td>\n      <td>38.24</td>\n    </tr>\n    <tr>\n      <th>private</th>\n      <td>418</td>\n      <td>35.36</td>\n    </tr>\n    <tr>\n      <th>pier</th>\n      <td>178</td>\n      <td>15.06</td>\n    </tr>\n    <tr>\n      <th>beach</th>\n      <td>134</td>\n      <td>11.34</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nTotal observations: 1,182\n```\n:::\n:::\n\n\n### Pie Chart\n\n::: {#3b03c5a1 .cell execution_count=11}\n``` {.python .cell-code}\n# Create pie chart\nfig, ax = plt.subplots(figsize=(8, 8))\ncolors = plt.cm.Set3(range(len(mode_freq)))\nwedges, texts, autotexts = ax.pie(mode_freq.values,\n                                    labels=mode_freq.index,\n                                    autopct='%1.1f%%',\n                                    colors=colors,\n                                    startangle=90,\n                                    textprops={'fontsize': 11})\nax.set_title('Distribution of Fishing Modes',\n             fontsize=14, fontweight='bold', pad=20)\n\nplt.tight_layout()\nplt.show()\n\n# Most popular fishing modes\nprint(f\"1. {mode_freq.index[0]}: {mode_freq.values[0]:,} ({mode_relfreq.values[0]*100:.1f}%)\")\nprint(f\"2. {mode_freq.index[1]}: {mode_freq.values[1]:,} ({mode_relfreq.values[1]*100:.1f}%)\")\n```\n\n::: {.cell-output .cell-output-display}\n![](ch02_Univariate_Data_Summary_files/figure-html/cell-12-output-1.png){width=718 height=758}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n1. charter: 452 (38.2%)\n2. private: 418 (35.4%)\n```\n:::\n:::\n\n\n**Sample: 1,182 recreational fishers choosing among 4 fishing sites**\n\n**Distribution of choices:**\n\n**1. Charter boat: 452 fishers (38.2%)**\n\n- Most popular choice\n- Guided fishing trip with captain and crew\n- Higher cost but convenience, equipment provided, and expert guidance\n\n**2. Private boat: 418 fishers (35.4%)**\n\n- Second-most popular (nearly tied with charter)\n- Requires boat ownership or rental\n- More freedom and privacy, but higher upfront costs\n\n**3. Pier: 178 fishers (15.1%)**\n\n- Third choice\n- Low-cost option (minimal equipment needed)\n- Accessible, but limited fishing locations\n\n**4. Beach: 134 fishers (11.3%)**\n\n- Least popular\n- Lowest cost and most accessible\n- But more limited fishing success rates\n\n**Key patterns:**\n\n**1. Boat fishing dominates:**\n\n- **Charter + Private = 870 fishers (73.6%)**\n- Nearly 3/4 of fishers prefer boat-based fishing\n- Suggests willingness to pay premium for better fishing access\n\n**2. Shore fishing is minority:**\n\n- **Pier + Beach = 312 fishers (26.4%)**\n- About 1/4 choose shore-based options\n- Likely cost-constrained or casual fishers\n\n**3. Charter vs. private nearly equal:**\n\n- Charter: 452 (38.2%)\n- Private: 418 (35.4%)\n- **Difference: only 34 fishers (2.9%)**\n- Suggests these are close substitutes for many fishers\n\n**4. Large variation in popularity:**\n\n- Most popular (Charter) is **3.4× more popular** than least popular (Beach)\n- Not evenly distributed across categories\n- Strong revealed preferences for certain modes\n\n**Economic interpretation:**\n\n**Why do people choose different modes?**\n\n**Charter boats chosen for:**\n\n- No boat ownership required\n- Expert captain knows best spots\n- Social experience (fishing with others)\n- Equipment and bait provided\n\n**Private boats chosen for:**\n\n- Flexibility in timing and location\n- Privacy and control\n- Cost-effective if you fish frequently\n- Pride of ownership\n\n**Pier/Beach chosen for:**\n\n- Budget constraints\n- No transportation to boat launch\n- Casual, occasional fishing\n- Family-friendly accessibility\n\n**Revealed preference theory:**\nThe distribution reveals what fishers VALUE:\n\n- **73.6% value boat access** enough to pay for it\n- **38.2% value convenience** of charter over ownership\n- **26.4% value low cost/accessibility** over catch rates\n\n**Statistical lesson:** \nFor categorical data, frequency tables and pie charts reveal the distribution of choices. This is the foundation for discrete choice models (Chapter 15) that estimate why people make different choices.\n\n> **Key Concept 2.5: Frequency Tables and Pie Charts**\n>\n> Categorical data are summarized using frequency tables showing counts and percentages. Pie charts display proportions visually, with slice area corresponding to relative frequency. Bar charts are often preferred over pie charts for easier comparison of categories.\n\nVisualization helps us *see* patterns, but sometimes the raw data obscures relationships. *Data transformations* (like logarithms and z-scores) can normalize skewed distributions, stabilize variance, and make statistical modeling more effective.\n\n## 2.5 Data Transformation\n\n**Data transformations** can make patterns clearer or satisfy statistical assumptions.\n\n**(a) Logarithmic transformation** is especially useful for right-skewed economic data (prices, income, wealth): $$\\text{log of earnings} = \\ln(\\text{earnings})$$\n\n**Why use logs?**\n\n- Converts right-skewed data to a more symmetric distribution\n- Makes multiplicative relationships additive\n- Coefficients have percentage interpretation (see Chapter 9)\n- Reduces influence of extreme values\n\n**(b) Standardized scores (z-scores)** are another common transformation:\n$$z_i = \\frac{x_i - \\bar{x}}{s}$$\n\nThis centers data at 0 with standard deviation 1—useful for comparing variables on different scales.\n\n### Log Transformation Effect\n\n::: {#aa16f6a7 .cell execution_count=12}\n``` {.python .cell-code}\n# Create log transformation\ndata_earnings['lnearnings'] = np.log(data_earnings['earnings'])\n\n# Comparison of earnings and log(earnings)\ndata_earnings[['earnings', 'lnearnings']].describe()\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>earnings</th>\n      <th>lnearnings</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>171.000000</td>\n      <td>171.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>41412.690058</td>\n      <td>10.457638</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>25527.053396</td>\n      <td>0.622062</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>1050.000000</td>\n      <td>6.956545</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>25000.000000</td>\n      <td>10.126631</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>36000.000000</td>\n      <td>10.491274</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>49000.000000</td>\n      <td>10.799367</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>172000.000000</td>\n      <td>12.055250</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#a047d080 .cell execution_count=13}\n``` {.python .cell-code}\n# Compare original and log-transformed earnings\nfig, axes = plt.subplots(1, 2, figsize=(14, 5))\n\n# Panel A: Original earnings\naxes[0].hist(data_earnings['earnings'], bins=30,\n             edgecolor='black', alpha=0.7, color='steelblue')\naxes[0].set_xlabel('Annual Earnings (in dollars)', fontsize=11)\naxes[0].set_ylabel('Frequency', fontsize=11)\naxes[0].set_title('Panel A: Earnings', fontsize=12, fontweight='bold')\naxes[0].grid(True, alpha=0.3)\n\n# Panel B: Log earnings\naxes[1].hist(data_earnings['lnearnings'], bins=30,\n             edgecolor='black', alpha=0.7, color='coral')\naxes[1].set_xlabel('Log of Annual Earnings', fontsize=11)\naxes[1].set_ylabel('Frequency', fontsize=11)\naxes[1].set_title('Panel B: Log(Earnings)', fontsize=12, fontweight='bold')\naxes[1].grid(True, alpha=0.3)\n\nplt.suptitle('Log Transformation Effects',\n             fontsize=14, fontweight='bold', y=1.02)\nplt.tight_layout()\nplt.show()\n\nprint(f\"Skewness reduced from {stats.skew(earnings):.2f} to {stats.skew(data_earnings['lnearnings']):.2f}\")\n```\n\n::: {.cell-output .cell-output-display}\n![](ch02_Univariate_Data_Summary_files/figure-html/cell-14-output-1.png){width=1335 height=494}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nSkewness reduced from 1.71 to -0.91\n```\n:::\n:::\n\n\n**Panel A: Original Earnings (dollars)**\n\n- **Shape**: Strongly right-skewed\n- **Skewness**: 1.71 (highly asymmetric)\n- **Mean**: \\$41,412.69\n- **Median**: \\$36,000.00\n- **Std Dev**: \\$25,527.05 (62% of mean)\n- **Range**: \\$1,050 to \\$172,000\n\n**Panel B: Log(Earnings) (natural logarithm)**\n\n- **Shape**: Much more symmetric, approximately normal\n- **Skewness**: -0.91 (nearly symmetric, slight left skew)\n- **Mean**: 10.46 (log dollars)\n- **Median**: 10.49 (log dollars)\n- **Std Dev**: 0.62 (only 6% of mean)\n- **Range**: 6.96 to 12.06\n\n**What the transformation achieved:**\n\n**1. Reduced skewness dramatically:**\n\n- Original skewness: **1.71** → Log skewness: **-0.91**\n- Reduction of **122%** in absolute skewness\n- Now nearly symmetric (close to 0)\n\n**2. Normalized the distribution:**\n\n- Original: Long right tail, NOT normal\n- Log: Bell-shaped, MUCH closer to normal distribution\n- This matters for statistical tests that assume normality\n\n**3. Equalized variance (stabilization):**\n\n- Original std dev: 62% of mean (high coefficient of variation)\n- Log std dev: 6% of mean (much more stable)\n- High earners no longer dominate the variance\n\n**4. Brought mean and median closer:**\n\n- Original: Mean - Median = \\$5,413 (15% gap)\n- Log: Mean - Median = -0.03 (0.3% gap)\n- Nearly identical in log scale\n\n**Why use log transformation for earnings?**\n\n**Statistical reasons:**\n\n1. **Normality**: Many statistical tests (t-tests, ANOVA, regression) assume normal distribution\n2. **Variance stabilization**: Constant variance across income levels\n3. **Linearity**: Log models often fit better (log-linear relationships)\n4. **Outlier reduction**: Compresses extreme values\n\n**Economic reasons:**\n\n1. **Multiplicative relationships**: Income growth is often proportional (e.g., 10% raise)\n2. **Percentage interpretation**: A 1-unit increase in log(income) ≈ 100% increase in income\n3. **Economic theory**: Utility functions often logarithmic (diminishing marginal utility)\n4. **Cross-country comparisons**: Log scale makes it easier to compare countries with vastly different GDP levels\n\n**How to interpret log(earnings) = 10.46?**\n\n- Take exponential: e^10.46 = \\$34,762\n- This is close to the median earnings (\\$36,000)\n- Each 1-unit increase in log(earnings) ≈ 2.718× increase in earnings\n\n**Example interpretation:**\n\n- Log(earnings) = 10.0 → Earnings = e^10.0 = \\$22,026\n- Log(earnings) = 11.0 → Earnings = e^11.0 = \\$59,874\n- **Difference of 1 in log scale = 2.72× in dollar scale**\n\n**When NOT to use log transformation:**\n\n- When data include zero or negative values (log undefined)\n- When you care about absolute differences (e.g., policy targeting specific dollar amounts)\n- When original scale is more interpretable for your audience\n\n**Statistical lesson:** Log transformation is one of the most powerful tools in econometrics for dealing with skewed, multiplicative data like income, prices, GDP, and wealth.\n\n> **Key Concept 2.6: Logarithmic Transformations**\n>\n> Natural logarithm transformations convert right-skewed economic data (earnings, prices, wealth) to more symmetric distributions, facilitating analysis. Z-scores standardize data to have mean 0 and standard deviation 1, enabling comparison across different scales.\n\nTime series data presents unique challenges—seasonal fluctuations, inflation, and population growth can mask underlying trends. Specialized transformations like moving averages and seasonal adjustment are essential for time-ordered economic data.\n\n## 2.6 Data Transformations for Time Series Data\n\nTime series data often require special transformations: 1. **Moving averages**: Smooth short-term fluctuations by averaging over several periods\n\n   - Example: 11-month moving average removes monthly noise\n\n2. **Seasonal adjustment**: Remove predictable seasonal patterns\n   - Example: Home sales peak in summer, drop in winter\n\n3. **Real vs. nominal adjustments**: Adjust for inflation using price indices\n   - Real values are in constant dollars (e.g., 2012 dollars)\n\n4. **Per capita adjustments**: Divide by population to account for population growth\n\n**Example:** Monthly U.S. home sales (2005-2015) showing original, moving average, and seasonally adjusted series.\n\n::: {#9d8e9256 .cell execution_count=14}\n``` {.python .cell-code}\n# Load monthly home sales data\ndata_homesales = pd.read_stata(GITHUB_DATA_URL + 'AED_MONTHLYHOMESALES.DTA')\n\n# Filter data for year >= 2005\ndata_homesales_filtered = data_homesales[data_homesales['year'] >= 2005]\n\n# Home sales data (2005 onwards)\ndata_homesales_filtered[['year', 'exsales', 'exsales_ma11', 'exsales_sa']].describe()\n```\n\n::: {.cell-output .cell-output-display execution_count=14}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>year</th>\n      <th>exsales</th>\n      <th>exsales_ma11</th>\n      <th>exsales_sa</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>121.000000</td>\n      <td>121.000000</td>\n      <td>116.000000</td>\n      <td>121.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>2009.545410</td>\n      <td>416851.239669</td>\n      <td>418300.125000</td>\n      <td>418071.625000</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>2.915476</td>\n      <td>111931.278110</td>\n      <td>81757.234375</td>\n      <td>83326.734375</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>2005.000000</td>\n      <td>218000.000000</td>\n      <td>324818.187500</td>\n      <td>287500.000000</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>2007.000000</td>\n      <td>347000.000000</td>\n      <td>357613.625000</td>\n      <td>355833.343750</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>2010.000000</td>\n      <td>401000.000000</td>\n      <td>394000.000000</td>\n      <td>401666.656250</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>2012.000000</td>\n      <td>473000.000000</td>\n      <td>436727.281250</td>\n      <td>440833.343750</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>2015.000000</td>\n      <td>754000.000000</td>\n      <td>608545.437500</td>\n      <td>605000.000000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Time Series Transformations for Home Sales\n\n::: {#7ffc184c .cell execution_count=15}\n``` {.python .cell-code}\n# Create time series plots with transformations\nfig, axes = plt.subplots(2, 1, figsize=(12, 10))\n\n# Panel A: Original and Moving Average\naxes[0].plot(data_homesales_filtered['daten'], data_homesales_filtered['exsales'],\n            linewidth=2, label='Original', color='#22d3ee')\naxes[0].plot(data_homesales_filtered['daten'], data_homesales_filtered['exsales_ma11'],\n            linewidth=2, linestyle='--', label='11-month Moving Average', color='red')\naxes[0].set_xlabel('Year', fontsize=11)\naxes[0].set_ylabel('Monthly Home Sales', fontsize=11)\naxes[0].set_title('Panel A: Original Series and Moving Average',\n                  fontsize=12, fontweight='bold')\naxes[0].legend()\naxes[0].grid(True, alpha=0.3)\n\n# Panel B: Original and Seasonally Adjusted\naxes[1].plot(data_homesales_filtered['daten'], data_homesales_filtered['exsales'],\n            linewidth=2, label='Original', color='#22d3ee')\naxes[1].plot(data_homesales_filtered['daten'], data_homesales_filtered['exsales_sa'],\n            linewidth=2, linestyle='--', label='Seasonally Adjusted', color='green')\naxes[1].set_xlabel('Year', fontsize=11)\naxes[1].set_ylabel('Monthly Home Sales', fontsize=11)\naxes[1].set_title('Panel B: Original Series and Seasonally Adjusted',\n                  fontsize=12, fontweight='bold')\naxes[1].legend()\naxes[1].grid(True, alpha=0.3)\n\nplt.suptitle('Time Series Transformations for Home Sales',\n             fontsize=14, fontweight='bold', y=0.995)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch02_Univariate_Data_Summary_files/figure-html/cell-16-output-1.png){width=1142 height=960}\n:::\n:::\n\n\n**Data: Monthly U.S. existing home sales (2005-2015)**\n\n**Three series compared:**\n\n1. **Original series** (blue solid line)\n2. **11-month moving average** (red dashed line, Panel A)\n3. **Seasonally adjusted** (green dashed line, Panel B)\n\n\n**Panel A: Original vs. Moving Average**\n\n**What the original series shows:**\n\n- **High volatility**: Sharp month-to-month fluctuations\n- **Seasonal peaks**: Regular spikes (summer buying season)\n- **Seasonal troughs**: Regular dips (winter slowdown)\n- **Trend**: Underlying long-term pattern (housing crash 2007-2011)\n- **Range**: 218,000 to 754,000 homes per month\n\n**What the 11-month moving average reveals:**\n\n**1. Smooths out noise:**\n\n- Eliminates month-to-month volatility\n- Shows the underlying trend clearly\n- Each point = average of surrounding 11 months\n\n**2. Housing market cycle becomes visible:**\n\n- **2005-2006**: Peak (~600,000 homes/month)\n- **2007-2008**: SHARP DECLINE (housing crash begins)\n- **2008-2011**: Bottom (~325,000 homes/month)\n  - Lost nearly 50% of sales volume\n  - Took 5+ years to reach bottom\n- **2011-2015**: Gradual recovery\n  - Sales climbing back toward ~450,000/month\n  - Still well below pre-crash peak\n\n**3. Trend is NOT linear:**\n\n- Not a straight line up or down\n- Shows boom-bust-recovery cycle\n- Moving average captures this nonlinear pattern\n\n\n**Panel B: Original vs. Seasonally Adjusted**\n\n**What seasonal adjustment does:**\n\n- **Removes predictable seasonal patterns**\n- Answers: \"What would sales be without seasonal effects?\"\n- Allows you to see whether changes are \"real\" or just seasonal\n\n**Key differences between seasonally adjusted and original:**\n\n**1. Amplitude reduction:**\n\n- Original: Wild swings from 218k to 754k\n- Seasonally adjusted: Smoother, swings from 288k to 605k\n- **Seasonal component accounts for ~30-40% of monthly variation**\n\n**2. Pattern changes:**\n\n- Original: Regular summer peaks (May-July) and winter troughs (Jan-Feb)\n- Seasonally adjusted: These regular peaks/troughs removed\n- **Remaining variation = true economic changes + random noise**\n\n**3. Trend clarity:**\n\n- Original: Hard to tell if uptick is recovery or just seasonal\n- Seasonally adjusted: Clearer signal of true economic trend\n- **Fed and policymakers watch seasonally adjusted data**\n\n**Comparison of transformation methods:**\n\n| Feature | Moving Average | Seasonal Adjustment |\n|---------|---------------|---------------------|\n| **Removes** | High-frequency noise | Predictable seasonal patterns |\n| **Preserves** | Trend and cycles | Trend, cycles, and irregular movements |\n| **Lags** | Yes (centered average) | No (real-time adjustment) |\n| **Use case** | Visualizing long-term trends | Policy decisions and forecasting |\n\n\n**Economic interpretation:**\n\n**Why does housing have strong seasonality?**\n\n1. **Weather**: Hard to move in winter (northern states)\n2. **School calendar**: Families move in summer to avoid disrupting school year\n3. **Tax refunds**: Spring refunds provide down payment money\n4. **Daylight**: More daylight hours for house hunting in summer\n\n**Why did the housing market crash?**\n\n- **2005-2006**: Subprime mortgage boom (easy credit)\n- **2007**: Mortgage defaults begin, housing prices fall\n- **2008**: Financial crisis (Lehman Brothers bankruptcy)\n- **2008-2009**: Credit crunch, massive foreclosures\n- **2009-2011**: Deleveraging, excess inventory\n\n**Why the slow recovery?**\n\n- **Underwater mortgages**: Many homeowners owed more than home value\n- **Tighter credit**: Banks required higher down payments, better credit scores\n- **Job losses**: 2008-2009 recession reduced demand\n- **Psychological**: Homebuyers became risk-averse after crash\n\n\n**Statistical lessons:**\n\n**1. Moving averages:**\n\n- Smooth time series to reveal trends\n- Width matters: 11-month average removes seasonal + noise\n- Trade-off: Smoothness vs. lag (delayed signal)\n\n**2. Seasonal adjustment:**\n\n- Essential for economic data with strong seasonal patterns\n- Allows comparison across months/quarters\n- Standard practice: Always report seasonally adjusted for policy\n\n**3. Which to use?**\n\n- **Moving average**: Historical analysis, visualization\n- **Seasonal adjustment**: Real-time monitoring, forecasting, policy\n- **Both together**: Comprehensive understanding of time series dynamics\n\n**Practical implication:** When the news reports \"Home sales up 5% this month,\" ALWAYS check if it's seasonally adjusted. Raw data might just show normal summer increase!\n\n> **Key Concept 2.7: Time Series Transformations**\n>\n> Time series data often requires transformations: moving averages smooth short-term fluctuations, seasonal adjustment removes recurring patterns, real values adjust for inflation, per capita values adjust for population, and growth rates measure proportionate changes. These transformations reveal underlying trends and enable meaningful comparisons.\n\n### GDP Comparisons - Nominal vs Real\n\n::: {#22527ced .cell execution_count=16}\n``` {.python .cell-code}\n# Compare nominal and real GDP\nfig, axes = plt.subplots(1, 2, figsize=(16, 6))\n\n# Panel A: GDP and Real GDP\naxes[0].plot(data_gdp['daten'], data_gdp['gdp'],\n            linewidth=2, label='GDP (nominal)', color='#22d3ee')\naxes[0].plot(data_gdp['daten'], data_gdp['realgdp'],\n            linewidth=2, linestyle='--', label='Real GDP (2012 dollars)', color='red')\naxes[0].set_xlabel('Year', fontsize=11)\naxes[0].set_ylabel('GDP (in $ billions)', fontsize=11)\naxes[0].set_title('Panel A: GDP and Real GDP', fontsize=12, fontweight='bold')\naxes[0].legend()\naxes[0].grid(True, alpha=0.3)\n\n# Panel B: GDP per capita and Real GDP per capita\naxes[1].plot(data_gdp['daten'], data_gdp['gdppc'],\n            linewidth=2, label='GDP per capita (nominal)', color='#22d3ee')\naxes[1].plot(data_gdp['daten'], data_gdp['realgdppc'],\n            linewidth=2, linestyle='--', label='Real GDP per capita (2012 dollars)', color='red')\naxes[1].set_xlabel('Year', fontsize=11)\naxes[1].set_ylabel('GDP per capita (in dollars)', fontsize=11)\naxes[1].set_title('Panel B: GDP per Capita and Real GDP per Capita',\n                  fontsize=12, fontweight='bold')\naxes[1].legend()\naxes[1].grid(True, alpha=0.3)\n\nplt.suptitle('GDP Comparisons - Nominal vs Real',\n             fontsize=14, fontweight='bold', y=1.0)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch02_Univariate_Data_Summary_files/figure-html/cell-17-output-1.png){width=1527 height=581}\n:::\n:::\n\n\n## Key Takeaways\n\n**Summary Statistics and Data Distributions:**\n\n- Summary statistics (mean, median, standard deviation, quartiles, skewness, kurtosis) efficiently describe large datasets by quantifying central tendency and dispersion\n- The mean is sensitive to outliers; the median is robust and preferred for skewed distributions\n- Standard deviation measures typical distance from the mean; for normal distributions, ~68% of data falls within 1 standard deviation, ~95% within 2\n- Skewness measures asymmetry (positive for right-skewed data common in economics like earnings and wealth); guideline: |skewness| > 1 indicates strong skewness\n- Kurtosis measures tail heaviness; excess kurtosis > 0 indicates fatter tails than the normal distribution\n- Box plots visually summarize key statistics: median, quartiles, and potential outliers\n\n**Visualizations for Different Data Types:**\n\n- Histograms display distributions of numerical data using bins; bin width affects detail level (smaller bins show more detail but may be noisier)\n- Kernel density estimates provide smooth approximations of underlying continuous distributions without arbitrary bin choices\n- Line charts are ideal for time series data to reveal trends, cycles, and structural breaks over time\n- Bar charts and column charts effectively display categorical data, with bar length representing values for easy comparison\n- Pie charts show proportions for categorical data, though bar charts often facilitate easier comparison across categories\n- Choosing the right visualization depends on data type (numerical vs. categorical), dimensionality (univariate vs. categorical breakdown), and whether data are time-ordered\n\n**Data Transformations and Their Applications:**\n\n- Natural logarithm transformations convert right-skewed economic data (earnings, prices, wealth) to more symmetric distributions, facilitating statistical analysis\n- Z-scores standardize data to mean 0 and standard deviation 1, enabling comparison across different scales and identifying outliers\n- Moving averages smooth short-term fluctuations in time series data by averaging over several periods (e.g., 11-month MA removes seasonality)\n- Seasonal adjustment removes recurring patterns to reveal underlying trends; essential for comparing economic indicators across months/quarters\n- Real values adjust for price inflation using deflators; per capita values adjust for population size—both are crucial for meaningful comparisons over time\n- Growth rates measure proportionate changes; distinguish between percentage point changes and percentage changes to avoid confusion\n- For time series, the change in natural log approximates the proportionate change (useful property: Δln(x) ≈ Δx/x for small changes)\n\n**Python Tools and Methods:**\n\n- `pandas` provides `.describe()`, `.mean()`, `.median()`, `.std()`, `.quantile()` for summary statistics\n- `scipy.stats` provides `skew()` and `kurtosis()` for distribution shape measures (note: `kurtosis()` returns excess kurtosis by default)\n- `matplotlib` and `seaborn` enable professional visualizations (histograms, KDE, line charts, box plots, bar charts)\n- `numpy.log()` applies natural logarithm transformation; z-scores computed as `(x - x.mean()) / x.std()`\n- Moving averages can be computed with `pandas.rolling().mean()`; seasonal adjustment typically requires specialized packages like `statsmodels`\n\n**Python Libraries and Code:**\n\nThis single code block reproduces the core workflow of Chapter 2. It is self-contained — copy it into an empty notebook and run it to review the complete pipeline from summary statistics and visualizations to data transformations and time series smoothing.\n\n```python\n# =============================================================================\n# CHAPTER 2 CHEAT SHEET: Univariate Data Summary\n# =============================================================================\n\n# --- Libraries ---\nimport numpy as np                        # numerical operations (log, mean)\nimport pandas as pd                       # data loading and manipulation\nimport matplotlib.pyplot as plt           # creating plots and visualizations\nfrom scipy import stats                   # skewness, kurtosis, distribution shape\n\n# =============================================================================\n# STEP 1: Load data directly from a URL\n# =============================================================================\n# pd.read_stata() reads Stata .dta files; this dataset has 171 observations\nurl_earnings = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/AED_EARNINGS.DTA\"\ndata_earnings = pd.read_stata(url_earnings)\n\nearnings = data_earnings['earnings']\nprint(f\"Dataset: {data_earnings.shape[0]} observations, {data_earnings.shape[1]} variables\")\n\n# =============================================================================\n# STEP 2: Summary statistics — mean vs median reveals skewness\n# =============================================================================\n# .describe() gives count, mean, std, min, quartiles, max in one call\nprint(data_earnings[['earnings']].describe().round(2))\n\n# Skewness and kurtosis measure the shape of the distribution\nprint(f\"\\nSkewness:        {stats.skew(earnings):.2f}  (> 1 = strongly right-skewed)\")\nprint(f\"Excess kurtosis: {stats.kurtosis(earnings):.2f}  (> 0 = heavier tails than normal)\")\nprint(f\"Mean - Median:   ${earnings.mean() - earnings.median():,.0f}  (positive gap signals right skew)\")\n\n# =============================================================================\n# STEP 3: Histogram with KDE overlay — see the distribution shape\n# =============================================================================\n# Bin width is a choice: narrower = more detail (and noise), wider = smoother\nfig, ax = plt.subplots(figsize=(10, 6))\nax.hist(earnings, bins=20, edgecolor='black', alpha=0.7, density=True, label='Histogram')\nearnings.plot.kde(ax=ax, linewidth=2, color='red', label='KDE')\nax.set_xlabel('Annual Earnings ($)')\nax.set_ylabel('Density')\nax.set_title('Earnings Distribution: Histogram + Kernel Density Estimate')\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n\n# =============================================================================\n# STEP 4: Box plot — visualize quartiles and outliers\n# =============================================================================\n# The box spans Q1 to Q3 (IQR); whiskers extend 1.5×IQR; dots are outliers\nfig, ax = plt.subplots(figsize=(10, 4))\nax.boxplot(earnings, vert=False, patch_artist=True,\n           boxprops=dict(facecolor='lightblue', alpha=0.7),\n           medianprops=dict(color='red', linewidth=2))\nax.set_xlabel('Annual Earnings ($)')\nax.set_title('Box Plot of Earnings — Median, Quartiles, and Outliers')\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n\n# =============================================================================\n# STEP 5: Log transformation — taming right skew\n# =============================================================================\n# np.log() compresses big values and stretches small ones, making skewed\n# distributions more symmetric — a prerequisite for many statistical methods\ndata_earnings['lnearnings'] = np.log(earnings)\n\nfig, axes = plt.subplots(1, 2, figsize=(14, 5))\naxes[0].hist(earnings, bins=20, edgecolor='black', alpha=0.7, color='steelblue')\naxes[0].set_title(f'Original  (skewness = {stats.skew(earnings):.2f})')\naxes[0].set_xlabel('Earnings ($)')\n\naxes[1].hist(data_earnings['lnearnings'], bins=20, edgecolor='black', alpha=0.7, color='coral')\naxes[1].set_title(f'Log-transformed  (skewness = {stats.skew(data_earnings[\"lnearnings\"]):.2f})')\naxes[1].set_xlabel('ln(Earnings)')\n\nplt.suptitle('Effect of Log Transformation on Skewness', fontweight='bold')\nplt.tight_layout()\nplt.show()\n\n# =============================================================================\n# STEP 6: Z-scores — how unusual is each observation?\n# =============================================================================\n# z = (x - mean) / std  puts every value on a common \"standard deviations\n# from the mean\" scale: |z| > 2 is unusual, |z| > 3 is very unusual\nz_scores = (earnings - earnings.mean()) / earnings.std()\n\nprint(f\"Highest earner: ${earnings.max():,.0f}  →  z = {z_scores.max():.2f}\")\nprint(f\"Median earner:  ${earnings.median():,.0f}  →  z = {(earnings.median() - earnings.mean()) / earnings.std():.2f}\")\nprint(f\"Observations with |z| > 2: {(z_scores.abs() > 2).sum()} out of {len(z_scores)}\")\n\n# =============================================================================\n# STEP 7: Time series — moving average smooths seasonal noise\n# =============================================================================\n# Monthly home sales zigzag with the seasons; an 11-month moving average\n# cancels one full seasonal cycle, revealing the underlying trend\nurl_homesales = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/AED_MONTHLYHOMESALES.DTA\"\ndata_hs = pd.read_stata(url_homesales)\ndata_hs = data_hs[data_hs['year'] >= 2005]\n\nfig, ax = plt.subplots(figsize=(12, 6))\nax.plot(data_hs['daten'], data_hs['exsales'], linewidth=1, alpha=0.6, label='Original (monthly)')\nax.plot(data_hs['daten'], data_hs['exsales_ma11'], linewidth=2, color='red',\n        linestyle='--', label='11-month Moving Average')\nax.set_xlabel('Year')\nax.set_ylabel('Monthly Home Sales')\nax.set_title('U.S. Home Sales: Raw Series vs. Moving Average (2005–2015)')\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n```\n\n**Try it yourself!** Copy this code into an empty Google Colab notebook and run it: [Open Colab](https://colab.research.google.com/notebooks/empty.ipynb)\n\n---\n\n**Next Steps:**\n\n- **Chapter 3**: Statistical inference and confidence intervals for the mean\n- **Chapter 5**: Bivariate data summary and correlation analysis\n- **Chapter 6-9**: Simple linear regression and interpretation\n\n**You have now mastered:**\n Calculating and interpreting summary statistics\n Creating effective visualizations for different data types\n Applying transformations to reveal patterns and normalize distributions\n Handling time series data with moving averages and seasonal adjustment\n\nThese foundational skills prepare you for inferential statistics and regression analysis in the following chapters!\n\n> **Common Mistakes to Avoid**\n>\n> - **Confusing mean and median**: The mean is sensitive to outliers, the median is not\n> - **Ignoring skewness**: Using the mean to summarize a skewed distribution is misleading\n> - **Forgetting to check for missing values before computing statistics**\n\n## Practice Exercises\n\nTest your understanding of univariate data analysis with these exercises: **Exercise 1:** Calculate summary statistics\n\n- For the sample {5, 2, 2, 8, 3}, calculate: - (a) Mean\n  - (b) Median\n  - (c) Variance\n  - (d) Standard deviation\n\n**Exercise 2:** Interpret skewness\n\n- A dataset has skewness = -0.85. What does this tell you about the distribution?\n- Would you expect the mean to be greater than or less than the median? Why?\n\n**Exercise 3:** Choose visualization types\n\n- For each scenario, recommend the best chart type and explain why: - (a) Quarterly GDP growth rates from 2000 to 2025\n  - (b) Market share of 5 smartphone brands\n  - (c) Distribution of household incomes in a city\n  - (d) Monthly temperature readings over a year\n\n**Exercise 4:** Log transformation\n\n- Why is log transformation particularly useful for economic variables like income and GDP?\n- If log(earnings) increases by 0.5, approximately what percentage increase does this represent in earnings?\n\n**Exercise 5:** Standard deviation interpretation\n\n- A dataset has mean = 50 and standard deviation = 10. If the data are approximately normally distributed: - (a) What percentage of observations fall between 40 and 60?\n  - (b) What percentage fall between 30 and 70?\n\n**Exercise 6:** Time series transformations\n\n- Explain the difference between: - (a) Moving average vs. seasonal adjustment\n  - (b) Nominal GDP vs. Real GDP\n  - (c) Total GDP vs. GDP per capita\n\n**Exercise 7:** Z-scores\n\n- For a sample with mean = 100 and standard deviation = 15: - (a) Calculate the z-score for an observation of 130\n  - (b) Interpret what this z-score means\n\n**Exercise 8:** Data interpretation\n\n- A box plot shows: - Lower quartile (Q1) = 25\n  - Median (Q2) = 35\n  - Upper quartile (Q3) = 60\n- Calculate: - (a) Interquartile range (IQR)\n  - (b) Describe the skewness based on quartile positions\n\n---\n\n## Case Studies\n\n### Case Study 1: Global Labor Productivity Distribution\n\n**Research Question:** How is labor productivity distributed across countries? Are there distinct groups or is it continuous?\n\nIn Chapter 1, you examined *relationships between variables*—specifically, how productivity relates to capital stock through regression analysis. Now we shift perspective to analyze a *single variable*—labor productivity—but focus on its **distribution across countries** rather than its associations.\n\nThis case study builds on Chapter 1's dataset (Convergence Clubs) but asks fundamentally different questions: What does the distribution of productivity look like across the 108 countries in our sample? Is it symmetric or skewed? Have productivity gaps widened or narrowed over time? These distributional questions are central to development economics and understanding global inequality.\n\nBy completing this case study, you'll apply all the univariate analysis tools from Chapter 2 to a real dataset with genuine economic relevance—exploring whether productivity converges globally or if divergence persists.\n\n> **Key Concept 2.8: Cross-Country Distributions**\n>\n> Cross-country distributions of economic variables (productivity, GDP per capita, income) are typically right-skewed with long upper tails, reflecting substantial inequality between rich and poor countries. Summary statistics like the median are often more representative than the mean for these distributions, and exploring the shape of the distribution reveals whether gaps between countries are widening or narrowing.\n\n### Load the Productivity Data\n\nWe'll use the same Convergence Clubs dataset from Chapter 1, but focus exclusively on the labor productivity variable (`lp`) across countries and years. This gives us 2,700 observations (108 countries × 25 years, from 1990 to 2014) of international productivity.\n\n::: {#1279a804 .cell execution_count=17}\n``` {.python .cell-code}\n# Load convergence clubs data (same as Chapter 1)\ndf1 = pd.read_csv(\n    \"https://raw.githubusercontent.com/quarcs-lab/mendez2020-convergence-clubs-code-data/master/assets/dat.csv\",\n    index_col=[\"country\", \"year\"]\n).sort_index()\n\n# For Chapter 2, focus on labor productivity variable\nproductivity = df1['lp']\n\n# Labor productivity distribution analysis\nprint(f\"Total observations: {len(productivity)}\")\nprint(f\"Countries: {len(df1.index.get_level_values('country').unique())}\")\nprint(f\"Time period: {df1.index.get_level_values('year').min()} to {df1.index.get_level_values('year').max()}\")\n\n# First 10 observations (sample)\ndf1[['lp']].head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTotal observations: 2700\nCountries: 108\nTime period: 1990 to 2014\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=17}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th></th>\n      <th>lp</th>\n    </tr>\n    <tr>\n      <th>country</th>\n      <th>year</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th rowspan=\"10\" valign=\"top\">Albania</th>\n      <th>1990</th>\n      <td>9959.2344</td>\n    </tr>\n    <tr>\n      <th>1991</th>\n      <td>9093.6943</td>\n    </tr>\n    <tr>\n      <th>1992</th>\n      <td>10188.3060</td>\n    </tr>\n    <tr>\n      <th>1993</th>\n      <td>12432.5870</td>\n    </tr>\n    <tr>\n      <th>1994</th>\n      <td>13007.0080</td>\n    </tr>\n    <tr>\n      <th>1995</th>\n      <td>14813.8990</td>\n    </tr>\n    <tr>\n      <th>1996</th>\n      <td>18248.9860</td>\n    </tr>\n    <tr>\n      <th>1997</th>\n      <td>15008.6750</td>\n    </tr>\n    <tr>\n      <th>1998</th>\n      <td>15001.0220</td>\n    </tr>\n    <tr>\n      <th>1999</th>\n      <td>17351.6020</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### How to Use These Tasks\n\n**Instructions:**\n\n1. **Read the task objectives and instructions** in each section below\n2. **Review the example code structure** provided\n3. **Create a NEW code cell** to write your solution\n4. **Follow the structure and fill in the blanks** or write complete code\n5. **Run and test your code**\n6. **Answer the interpretation questions**\n\n**Progressive difficulty:**\n\n- **Tasks 1-2:** Guided (fill in specific blanks with `_____`)\n- **Task 3:** Semi-guided (complete partial code structure)\n- **Tasks 4-6:** Independent (write full code from outline)\n\n**Tip:** Type the code yourself rather than copying—it builds understanding!\n\n#### Task 1: Data Exploration (Guided)\n\n**Objective:** Load and explore the structure of the global productivity distribution.\n\n**Instructions:**\n\n1. Examine the productivity variable's basic structure (length, data type, any missing values)\n2. Get summary statistics (count, mean, std, min, max)\n3. Display observations for 5 different countries to see variation across countries\n4. Check: Is there variation across countries? Does it seem large or small?\n\n**Chapter 2 connection:** This applies the concepts from Section 2.1 (Summary Statistics).\n\n**Starter code guidance:**\n\n- Use `productivity.describe()` for summary statistics\n- Check for missing values with `productivity.isnull().sum()`\n- Use `.loc[]` or `.xs()` to select specific countries' observations\n- Calculate min and max productivity values globally\n\n**Example code structure:**\n\n```python\n# Task 1: Data Exploration (GUIDED)\n# Complete the code below by filling in the blanks (_____)\n\n# Step 1: Check data structure\nprint(\"Data Structure:\")\nprint(f\"Total observations: {_____}\")\nprint(f\"Data type: {productivity.dtype}\")\nprint(f\"Missing values: {_____}\")\n\n# Step 2: Summary statistics\nprint(\"\\n\" + \"=\" * 70)\nprint(\"Summary Statistics for Global Productivity\")\nprint(\"=\" * 70)\nprint(productivity.describe())\n\n# Step 3: Variation across countries - look at a few countries\nprint(\"\\n\" + \"=\" * 70)\nprint(\"Productivity across 5 sample countries:\")\nprint(\"=\" * 70)\nsample_countries = ['Australia', 'Brazil', 'China', 'France', 'Nigeria']\nfor country in sample_countries: country_data = df1.loc[country, 'lp']\n    print(f\"\\n{country}:\")\n    print(f\"  Mean productivity: {_____:.3f}\")\n    print(f\"  Min: {_____:.3f}, Max: {_____:.3f}\")\n    print(f\"  Range: {_____:.3f}\")\n\n# Step 4: Global variation\nprint(\"\\n\" + \"=\" * 70)\nprint(\"Global Variation:\")\nprint(\"=\" * 70)\nmin_prod = productivity.min()\nmax_prod = productivity.max()\nratio = max_prod / min_prod\nprint(f\"Minimum global productivity: {min_prod:.3f}\")\nprint(f\"Maximum global productivity: {max_prod:.3f}\")\nprint(f\"Ratio (max/min): {ratio:.1f}x\")\nprint(f\"\\nInterpretation: The most productive country is {ratio:.0f}× more productive than the least productive country!\")\n\n```\n\n#### Task 2: Summary Statistics (Semi-guided)\n\n**Objective:** Calculate comprehensive summary statistics for the global productivity distribution.\n\n**Instructions:**\n\n1. Compute mean, median, standard deviation, quartiles (25th, 50th, 75th percentiles)\n2. Calculate skewness and kurtosis for the overall productivity distribution\n3. Identify which countries have the highest and lowest productivity (across all years)\n4. Compare productivity statistics for two time periods: 1990 and 2014\n\n**Chapter 2 connection:** Applies Section 2.1 (Summary Statistics) and distribution shape measures.\n\n**Starter code guidance:**\n\n- Use `.describe()` for the main statistics\n- Use `scipy.stats.skew()` and `scipy.stats.kurtosis()` for shape measures\n- Filter by year: `df1.xs(1990, level='year')['lp']`\n- Use `.nlargest()` and `.nsmallest()` to find extreme values\n- Create a comparison table of statistics for different time periods\n\n**Example code structure:**\n\n```python\n# Task 2: Summary Statistics (SEMI-GUIDED)\n# Complete the code by implementing each step\n\n# Step 1: Overall summary statistics\noverall_stats = {\n    'Mean': productivity.mean(),\n    'Median': _____,  # Calculate median\n    'Std Dev': _____,  # Calculate standard deviation\n    'Skewness': stats.skew(_____),\n    'Kurtosis': _____,  # Calculate kurtosis\n    '25th percentile': productivity.quantile(0.25),\n    '75th percentile': productivity.quantile(_____),\n    'IQR': productivity.quantile(0.75) - productivity.quantile(0.25)\n}\n\nfor key, value in overall_stats.items(): print(f\"{key:20s}: {value:.4f}\")\n\n# Step 2: Countries with highest/lowest productivity\nprint(\"\\n\" + \"=\" * 70)\nprint(\"Top 5 Most Productive Countries (average across years)\")\nprint(\"=\" * 70)\ncountry_means = df1.groupby(_____)['lp'].mean().sort_values(_____)\nprint(country_means.head())\n\nprint(\"\\n\" + \"=\" * 70)\nprint(\"Top 5 Least Productive Countries (average across years)\")\nprint(\"=\" * 70)\nprint(country_means.tail())\n\n# Step 3: Compare 1990 vs 2014\nproductivity_1990 = df1.xs(1990, level=_____)['lp']\nproductivity_2014 = df1.xs(_____, level='year')['lp']\n\n# Your code here: Create a comparison DataFrame\n# Hint: Use pd. DataFrame() with statistics for both years\n# Include: mean, median, std, skewness, min, max\n\n```\n\n**Hints:**\n\n- Use `.median()`, `.std()` for missing statistics\n- `stats.kurtosis()` requires the data series as input\n- `.groupby('country')` groups by country name\n- `.sort_values(ascending=False)` sorts from high to low\n- `.xs(year, level='year')` extracts data for a specific year\n\n#### Task 3: Visualizing Distributions (Semi-guided)\n\n**Objective:** Create multiple visualizations to understand the shape of the productivity distribution.\n\n**Instructions:**\n\n1. Create a histogram of productivity (try different bin widths)\n2. Create a box plot to identify outliers and quartiles\n3. Create a kernel density estimate to see the smooth shape\n4. Compare the original distribution to the log-transformed distribution\n\n**Chapter 2 connection:** Applies Section 2.2 (Charts for Numerical Data).\n\n**Starter code guidance:**\n\n- Use `plt.hist()` for histogram with different bin widths (try 10, 15, 20 bins)\n- Use `plt.boxplot()` for box plot visualization\n- Use `.plot.kde()` for kernel density estimate\n- Create side-by-side panels to compare original vs log-transformed\n- Label axes clearly and add titles\n\n**Example code structure:**\n\n```python\n# Task 3: Visualizing Distributions (SEMI-GUIDED)\n# Create comprehensive visualizations of the productivity distribution\n\n# Create a 2x2 figure with 4 subplots\nfig, axes = plt.subplots(_____, _____, figsize=(14, 10))\n\n# Panel 1: Histogram (original productivity)\naxes[0, 0].hist(productivity, bins=_____, edgecolor='black', alpha=0.7, color='steelblue')\naxes[0, 0].set_xlabel(_____, fontsize=11)\naxes[0, 0].set_ylabel(_____, fontsize=11)\naxes[0, 0].set_title('Panel 1: Histogram of Productivity (20 bins)', fontsize=12, fontweight='bold')\naxes[0, 0].grid(True, alpha=0.3)\n\n# Panel 2: Box plot (original productivity)\naxes[0, 1].boxplot(_____, vert=True, patch_artist=True)\naxes[0, 1].set_ylabel('Labor Productivity', fontsize=11)\naxes[0, 1].set_title('Panel 2: Box Plot of Productivity', fontsize=12, fontweight='bold')\naxes[0, 1].grid(True, alpha=0.3, axis='y')\n\n# Panel 3: KDE (original productivity)\nproductivity.plot.kde(ax=_____, linewidth=2, color='darkblue')\naxes[1, 0].set_xlabel('Labor Productivity', fontsize=11)\naxes[1, 0].set_ylabel('Density', fontsize=11)\naxes[1, 0].set_title('Panel 3: Kernel Density Estimate', fontsize=12, fontweight='bold')\naxes[1, 0].grid(True, alpha=0.3)\n\n# Panel 4: KDE comparison (original vs log-transformed)\n# Your code here: Create log-transformed productivity\nlog_productivity = np.log(productivity)\n\n# Your code here: Plot both KDE curves on the same axes\n# Hint: Use .plot.kde() with label='Original' and label='Log-transformed'\n# Use different colors and linestyles for clarity\n\nplt.suptitle('Figure: Global Productivity Distribution Visualizations', fontsize=14, fontweight='bold', y=1.00)\nplt.tight_layout()\nplt.show()\n\n```\n\n**Hints:**\n\n- `plt.subplots(2, 2)` creates 2 rows and 2 columns\n- Try `bins=20` for the histogram\n- Set xlabel to 'Labor Productivity'\n- For boxplot, pass the productivity series directly\n- Use `axes[1, 0]` to reference the bottom-left panel\n- For KDE comparison, plot two curves with different colors (e.g., 'darkblue' and 'red')\n\n#### Task 4: Comparing Distributions Across Time (More Independent)\n\n**Objective:** Analyze how the productivity distribution has changed from 1990 to 2014.\n\n**Instructions:**\n\n1. Extract productivity data for 1990 and 2014\n2. Calculate summary statistics for each year separately\n3. Create overlapping KDE plots to compare the distributions visually\n4. Analyze: Has the distribution shifted right (convergence/improvement)? Widened (divergence)? Changed shape?\n\n**Chapter 2 connection:** Applies Section 2.2 (comparing distributions across groups).\n\n**Starter code guidance:**\n\n- Use `df1.xs(year, level='year')` to extract data for specific years\n- Create summary statistics tables for comparison\n- Plot two KDE curves on the same axes with different colors\n- Use the 25th and 75th percentiles to measure spread\n- Calculate the coefficient of variation (std/mean) to compare relative dispersion\n\n**Example code structure:**\n\n```python\n# Task 4: Comparing Distributions Across Time (MORE INDEPENDENT)\n# Analyze how global productivity distribution evolved from 1990 to 2014\n\n# Step 1: Extract data for 1990 and 2014\nprod_1990 = df1.xs(_____, level='year')['lp']\nprod_2014 = _____  # Extract 2014 data (same pattern as above)\n\n# Step 2: Create comparison visualization\n# Your code here: Create figure with 2 subplots (1 row, 2 columns)\n# Hint: fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n\n# Panel A: Overlapping KDE plots\n# Your code here: Plot KDE for both years on the same axes\n# - Use prod_1990.plot.kde() and prod_2014.plot.kde()\n# - Different colors for each year (e.g., 'darkblue' and 'red')\n# - Add labels and legend\n\n# Panel B: Side-by-side box plots\n# Your code here: Create box plots for both years\n# Hint: axes[1].boxplot([prod_1990, prod_2014], labels=['1990', '2014'])\n# Set different colors for each box using patch_artist=True\n\n# Step 3: Calculate comparison statistics\n# Your code here: Create a DataFrame comparing statistics for both years\n# Include: mean, median, std, coefficient of variation, skewness, min, max, range\n# Hint: Use pd.DataFrame() with a dictionary of statistics\n\n```\n\n**Hints:**\n\n- Coefficient of variation = std / mean (relative dispersion)\n- Use `stats.skew()` from scipy.stats for skewness\n- For KDE plots, use `label='1990'` and `label='2014'` for legend\n- Range = max - min\n\n**Questions to consider:**\n\n- Did mean productivity increase from 1990 to 2014?\n- Did the spread (std dev) increase or decrease? (Convergence vs divergence)\n- Did the coefficient of variation change?\n- Did skewness change?\n\n#### Task 5: Transformation Analysis (Independent)\n\n**Objective:** Apply log transformation to productivity data and analyze the effect.\n\n**Instructions:**\n\n1. Create log-transformed productivity variable: log_productivity = ln(productivity)\n2. Compare skewness before and after transformation\n3. Create side-by-side histograms (original vs log-transformed)\n4. Calculate z-scores for both variables to standardize them\n5. Interpret: Why does log transformation help? When would you use it?\n\n**Chapter 2 connection:** Applies Section 2.5 (Data Transformation).\n\n**Starter code guidance:**\n\n- Use `np.log()` to create log transformation\n- Compare skewness values before/after using `stats.skew()`\n- Create z-scores with: `(x - x.mean()) / x.std()`\n- Visualize both original and log distributions in histograms\n- Discuss why log-normal distributions are common in economics\n\n**Example code structure:**\n\n```python\n# Task 5: Transformation Analysis (INDEPENDENT)\n# Apply log transformation to understand how it affects the distribution\n\n# Step 1: Create log transformation\n# Your code here: log_productivity = np.log(_____)\n\n# Step 2: Create z-scores (standardized values)\n# Your code here: Calculate z-scores for both distributions\n# Formula: z = (x - mean) / std\n# z_productivity = (productivity - productivity.mean()) / productivity.std()\n# z_log_productivity = ?\n\n# Step 3: Create side-by-side histograms\n# Your code here: Use plt.subplots(1, 2) for 2 panels\n# Panel A: Original productivity histogram (20 bins, blue color)\n# Panel B: Log-transformed histogram (20 bins, coral/red color)\n\n# Step 4: Compare skewness\n# Your code here: Calculate skewness using stats.skew()\n# Calculate percentage reduction: (1 - |skew_log| / |skew_original|) * 100\n# Print comparison table showing: mean, median, std, skewness, kurtosis, min, max\n\n```\n\n**Hints:**\n\n- `np.log()` computes natural logarithm\n- Z-scores standardize data to mean=0, std=1\n- Use `stats.skew()` and `stats.kurtosis()` for shape measures\n- Compare absolute skewness values to quantify reduction\n\n**Questions to consider:**\n\n- Is the log-transformed distribution more symmetric?\n- When would you use log transformation in economic analysis?\n- What happened to skewness and kurtosis after transformation?\n\n> **Key Concept 2.9: Distributional Convergence**\n>\n> Distributional convergence (σ-convergence) asks whether the spread (variance) of productivity across countries is narrowing over time. This differs from β-convergence (poor countries growing faster than rich ones). If cross-country distributions are becoming more compressed (lower variance), it suggests countries are converging toward similar productivity levels—important for understanding whether global inequality is increasing or decreasing.\n\n#### Task 6: Regional Patterns (Independent)\n\n**Objective:** Compare productivity distributions across geographic regions.\n\n**Instructions:**\n\n1. Add a region column to your dataframe (you'll need to manually assign regions based on country names)\n2. Group countries by region (at minimum: Africa, Asia, Europe, Americas)\n3. Create box plots for each region side-by-side\n4. Calculate summary statistics by region\n5. Identify: Which regions have highest/lowest productivity? Most inequality?\n\n**Chapter 2 connection:** Applies Sections 2.3-2.4 (Charts for categorical breakdowns).\n\n**Starter code guidance:**\n\n- Create a dictionary mapping countries to regions\n- Use `.groupby()` to calculate statistics by region\n- Create side-by-side box plots for visual comparison\n- Calculate mean and standard deviation by region\n- Compare median productivity across regions\n\n**Example code structure:**\n\n```python\n# Task 6: Regional Patterns (INDEPENDENT)\n# Compare productivity distributions across geographic regions\n\n# Step 1: Create region mapping dictionary\n# Your code here: Define region_mapping\n# Map each country to its region (Africa, Americas, Asia, Europe, Middle East, Asia-Pacific)\n# Example structure:\n# region_mapping = {\n#     'Australia': 'Asia-Pacific',\n#     'Austria': 'Europe',\n#     'Brazil': 'Americas',\n#     # ... continue for all ~50 countries\n# }\n\n# Step 2: Add region column to dataframe\n# Your code here: Create a copy of df1 and add region column\n# Hint: df_with_region['region'] = df_with_region.index.get_level_values('country').map(region_mapping)\n# Remove rows with missing regions: .dropna(subset=['region'])\n\n# Step 3: Calculate regional statistics\n# Your code here: Group by region and aggregate statistics\n# Hint: df_with_region.groupby('region')['lp'].agg(['count', 'mean', 'median', 'std', 'min', 'max'])\n# Sort by mean productivity (descending)\n\n# Step 4: Create box plots by region\n# Your code here: Create boxplot visualization comparing regions\n# - Extract data for each region: [df[df['region'] == r]['lp'].values for r in regions]\n# - Sort regions by mean productivity for better readability\n# - Use plt.boxplot() with labels for each region\n# - Rotate x-axis labels for readability\n\n```\n\n**Hints:**\n\n- There are ~50 countries in the dataset - you'll need to map each one\n- Regions: Africa (Kenya, Nigeria, etc.), Americas (USA, Brazil, etc.), Asia (China, India, etc.)\n- Europe (France, Germany, etc.), Middle East (Israel, Turkey), Asia-Pacific (Australia, Japan, NZ)\n- Use `.groupby('region')['lp'].agg([...])` to calculate statistics by region\n- Sort regions by mean before plotting for better visualization\n\n**Questions to consider:**\n\n- Which region has the highest average productivity?\n- Which region has the most internal inequality (widest box)?\n- Are there clear regional clusters or is variation continuous?\n\n### What You've Learned from This Case Study\n\nBy completing this case study on global labor productivity distribution, you've applied the full toolkit of univariate data analysis to a real international economics question. You've moved beyond calculating statistics and making charts to asking substantive economic questions: Are countries converging or diverging? How has global inequality in productivity evolved? Which regions drive global disparity?\n\nSpecifically, you've practiced:\n\n- **Summary statistics** to quantify central tendency and spread\n- **Visualizations** (histograms, box plots, KDE) to see distributional shape\n- **Comparisons** across time periods to detect changes\n- **Transformations** (log) to normalize skewed economic data\n- **Categorical breakdowns** (regions) to identify subgroup patterns\n\nThese skills extend far beyond productivity. The same analytical approach applies to wealth distribution, income inequality, student test scores, health outcomes, and countless other univariate datasets in economics and social science.\n\nYour next steps (in later chapters) will be to ask *relational* questions: How does productivity relate to capital? Does inequality depend on development level? Can we *predict* a country's productivity from other variables? Those questions require bivariate analysis (Chapter 5) and regression (Chapter 6+).\n\n### Case Study 2: The Geography of Development: Summarizing Bolivia's Municipal SDG Data\n\n**Research Question:** What does the distribution of municipal development look like across Bolivia's 339 municipalities, and how do these distributions vary across departments?\n\nIn Chapter 1, we introduced the DS4Bolivia project and explored the relationship between nighttime lights and municipal development in Bolivia. In this case study, we apply Chapter 2's univariate summary tools to characterize the *distribution* of development indicators across Bolivia's 339 municipalities.\n\n**The Data**: The [DS4Bolivia project](https://github.com/quarcs-lab/ds4bolivia) provides a comprehensive dataset covering 339 Bolivian municipalities with over 350 variables, including the Municipal Sustainable Development Index (IMDS), individual SDG indices, nighttime lights per capita (2012-2020), population, and socioeconomic indicators. Here we focus on understanding the *shape* of these distributions—their central tendency, spread, skewness, and multimodality—using the univariate tools from this chapter.\n\n#### Load the DS4Bolivia Data\n\nLet's load the DS4Bolivia dataset and select the key variables for univariate analysis.\n\n::: {#177dbb73 .cell execution_count=18}\n``` {.python .cell-code}\n# Load the DS4Bolivia dataset\nurl_bol = \"https://raw.githubusercontent.com/quarcs-lab/ds4bolivia/master/ds4bolivia_v20250523.csv\"\nbol = pd.read_csv(url_bol)\n\n# Display basic information\nprint(f\"Dataset shape: {bol.shape[0]} municipalities, {bol.shape[1]} variables\")\nprint(f\"Departments: {bol['dep'].nunique()} unique departments\")\nprint(f\"Department names: {sorted(bol['dep'].unique())}\")\n\n# Select key variables for this case study\nkey_vars = ['mun', 'dep', 'imds', 'ln_NTLpc2017', 'pop2017',\n            'index_sdg1', 'sdg1_1_ubn',\n            'ln_NTLpc2012', 'ln_NTLpc2013', 'ln_NTLpc2014',\n            'ln_NTLpc2015', 'ln_NTLpc2016', 'ln_NTLpc2017',\n            'ln_NTLpc2018', 'ln_NTLpc2019', 'ln_NTLpc2020']\n# Remove duplicates while preserving order\nkey_vars = list(dict.fromkeys(key_vars))\nbol_key = bol[key_vars].copy()\n\nprint(f\"Key variables selected: {len(key_vars)}\")\n\n# First 10 municipalities\nbol_key.head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDataset shape: 339 municipalities, 351 variables\nDepartments: 9 unique departments\nDepartment names: ['Beni', 'Chuquisaca', 'Cochabamba', 'La Paz', 'Oruro', 'Pando', 'Potosí', 'Santa Cruz', 'Tarija']\nKey variables selected: 15\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=18}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>mun</th>\n      <th>dep</th>\n      <th>imds</th>\n      <th>ln_NTLpc2017</th>\n      <th>pop2017</th>\n      <th>index_sdg1</th>\n      <th>sdg1_1_ubn</th>\n      <th>ln_NTLpc2012</th>\n      <th>ln_NTLpc2013</th>\n      <th>ln_NTLpc2014</th>\n      <th>ln_NTLpc2015</th>\n      <th>ln_NTLpc2016</th>\n      <th>ln_NTLpc2018</th>\n      <th>ln_NTLpc2019</th>\n      <th>ln_NTLpc2020</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Esmeralda</td>\n      <td>Oruro</td>\n      <td>53.200001</td>\n      <td>13.647187</td>\n      <td>4065.64790</td>\n      <td>34.759998</td>\n      <td>78.300003</td>\n      <td>11.729473</td>\n      <td>12.111817</td>\n      <td>10.962022</td>\n      <td>11.699198</td>\n      <td>13.085610</td>\n      <td>13.667681</td>\n      <td>13.595437</td>\n      <td>13.489282</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Quillacas</td>\n      <td>Oruro</td>\n      <td>50.500000</td>\n      <td>13.821883</td>\n      <td>4517.64500</td>\n      <td>27.950001</td>\n      <td>73.599998</td>\n      <td>12.965525</td>\n      <td>13.142761</td>\n      <td>13.074501</td>\n      <td>13.143079</td>\n      <td>12.948340</td>\n      <td>13.822321</td>\n      <td>13.803769</td>\n      <td>14.016370</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Pampa Aullagas</td>\n      <td>Oruro</td>\n      <td>47.299999</td>\n      <td>13.406137</td>\n      <td>2951.34470</td>\n      <td>18.910000</td>\n      <td>85.199997</td>\n      <td>12.763059</td>\n      <td>12.927601</td>\n      <td>12.876277</td>\n      <td>12.199938</td>\n      <td>12.289141</td>\n      <td>13.358246</td>\n      <td>12.982080</td>\n      <td>13.722827</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Llallagua</td>\n      <td>Potosí</td>\n      <td>58.099998</td>\n      <td>14.827301</td>\n      <td>43508.59400</td>\n      <td>60.480000</td>\n      <td>37.500000</td>\n      <td>14.275025</td>\n      <td>14.395530</td>\n      <td>14.490864</td>\n      <td>14.518698</td>\n      <td>14.763354</td>\n      <td>14.902343</td>\n      <td>14.960201</td>\n      <td>14.870754</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Caripuyo</td>\n      <td>Potosí</td>\n      <td>43.500000</td>\n      <td>12.510039</td>\n      <td>9163.95310</td>\n      <td>18.889999</td>\n      <td>88.800003</td>\n      <td>11.708997</td>\n      <td>12.142770</td>\n      <td>11.809417</td>\n      <td>11.976866</td>\n      <td>11.590055</td>\n      <td>12.694351</td>\n      <td>12.807661</td>\n      <td>13.150372</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Aiquile</td>\n      <td>Cochabamba</td>\n      <td>50.400002</td>\n      <td>14.606511</td>\n      <td>22833.01600</td>\n      <td>41.880001</td>\n      <td>69.099998</td>\n      <td>14.106005</td>\n      <td>14.155921</td>\n      <td>14.098324</td>\n      <td>14.249661</td>\n      <td>14.412630</td>\n      <td>14.694560</td>\n      <td>14.667776</td>\n      <td>14.758524</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Villa de Sacaca</td>\n      <td>Potosí</td>\n      <td>42.200001</td>\n      <td>12.586779</td>\n      <td>20121.35500</td>\n      <td>19.320000</td>\n      <td>88.900002</td>\n      <td>11.849950</td>\n      <td>12.121868</td>\n      <td>12.064876</td>\n      <td>12.086696</td>\n      <td>12.208024</td>\n      <td>12.856441</td>\n      <td>12.830930</td>\n      <td>12.948944</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>Acasio</td>\n      <td>Potosí</td>\n      <td>42.099998</td>\n      <td>12.358384</td>\n      <td>6426.26170</td>\n      <td>20.730000</td>\n      <td>82.699997</td>\n      <td>11.160867</td>\n      <td>11.181058</td>\n      <td>11.304965</td>\n      <td>11.214730</td>\n      <td>10.936804</td>\n      <td>12.405064</td>\n      <td>12.700905</td>\n      <td>12.953930</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>Huanuni</td>\n      <td>Oruro</td>\n      <td>56.799999</td>\n      <td>14.774255</td>\n      <td>27025.19900</td>\n      <td>65.089996</td>\n      <td>24.000000</td>\n      <td>14.401511</td>\n      <td>14.563268</td>\n      <td>14.571879</td>\n      <td>14.534027</td>\n      <td>14.616848</td>\n      <td>14.824553</td>\n      <td>14.874644</td>\n      <td>14.895752</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>Huachacalla</td>\n      <td>Oruro</td>\n      <td>61.299999</td>\n      <td>15.581995</td>\n      <td>675.42578</td>\n      <td>69.680000</td>\n      <td>22.299999</td>\n      <td>14.866138</td>\n      <td>14.909245</td>\n      <td>14.816506</td>\n      <td>14.798038</td>\n      <td>15.247589</td>\n      <td>15.627427</td>\n      <td>15.579352</td>\n      <td>15.647954</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n#### Task 1: Summary Statistics (Guided)\n\n**Objective**: Compute and interpret descriptive statistics for key development indicators.\n\n**Instructions**:\n\n1. Use `.describe()` to generate summary statistics for `imds`, `index_sdg1`, `sdg1_1_ubn`, and `ln_NTLpc2017`\n2. Calculate the mean, median, standard deviation, skewness, and kurtosis for each variable\n3. Discuss what these statistics reveal about the distribution of municipal development in Bolivia\n\n**Apply what you learned in section 2.1**: Use `describe()`, `.mean()`, `.median()`, `.std()`, `.skew()`, and `.kurtosis()` to characterize these distributions.\n\n::: {#42d2daec .cell execution_count=19}\n``` {.python .cell-code}\n# Task 1: Summary Statistics\n# ----------------------------------------------------------\n\n# 1. Basic descriptive statistics\nanalysis_vars = ['imds', 'index_sdg1', 'sdg1_1_ubn', 'ln_NTLpc2017']\n# Descriptive statistics: key development indicators\ndisplay(bol_key[analysis_vars].describe().round(2))\n\n# Distributional shape measures\nfor var in analysis_vars:\n    series = bol_key[var].dropna()\n    print(f\"\\n{var}:\")\n    print(f\"  Mean:     {series.mean():.2f}\")\n    print(f\"  Median:   {series.median():.2f}\")\n    print(f\"  Std Dev:  {series.std():.2f}\")\n    print(f\"  Skewness: {series.skew():.3f}\")\n    print(f\"  Kurtosis: {series.kurtosis():.3f}\")\n\n# Interpretation\n# Compare mean vs median for each variable:\n# If mean > median -> right-skewed (long upper tail)\n# If mean < median -> left-skewed (long lower tail)\n# High kurtosis (>3) indicates heavy tails (extreme municipalities)\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>imds</th>\n      <th>index_sdg1</th>\n      <th>sdg1_1_ubn</th>\n      <th>ln_NTLpc2017</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>339.00</td>\n      <td>339.00</td>\n      <td>339.00</td>\n      <td>333.00</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>51.05</td>\n      <td>37.46</td>\n      <td>70.36</td>\n      <td>13.88</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>6.77</td>\n      <td>20.95</td>\n      <td>18.95</td>\n      <td>1.18</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>35.70</td>\n      <td>0.06</td>\n      <td>14.30</td>\n      <td>9.06</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>47.00</td>\n      <td>21.64</td>\n      <td>59.65</td>\n      <td>13.13</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>50.50</td>\n      <td>34.76</td>\n      <td>73.60</td>\n      <td>13.91</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>54.85</td>\n      <td>51.88</td>\n      <td>85.85</td>\n      <td>14.77</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>80.20</td>\n      <td>90.46</td>\n      <td>97.90</td>\n      <td>17.06</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nimds:\n  Mean:     51.05\n  Median:   50.50\n  Std Dev:  6.77\n  Skewness: 0.590\n  Kurtosis: 1.179\n\nindex_sdg1:\n  Mean:     37.46\n  Median:   34.76\n  Std Dev:  20.95\n  Skewness: 0.417\n  Kurtosis: -0.642\n\nsdg1_1_ubn:\n  Mean:     70.36\n  Median:   73.60\n  Std Dev:  18.95\n  Skewness: -0.813\n  Kurtosis: -0.030\n\nln_NTLpc2017:\n  Mean:     13.88\n  Median:   13.91\n  Std Dev:  1.18\n  Skewness: -0.511\n  Kurtosis: 0.571\n```\n:::\n:::\n\n\n#### Task 2: Histograms and Density Plots (Guided)\n\n**Objective**: Visualize the distributions of `imds` and `ln_NTLpc2017` using histograms and kernel density estimation (KDE) plots.\n\n**Instructions**:\n\n1. Create histograms for `imds` and `ln_NTLpc2017` (side by side)\n2. Overlay KDE curves on the histograms\n3. Discuss the shape: Is each distribution unimodal or bimodal? Symmetric or skewed?\n4. What might explain any multimodality? (Think about the urban-rural divide)\n\n**Apply what you learned in section 2.2**: Use `plt.hist()` with `density=True` and overlay `.plot.kde()` or `sns.kdeplot()`.\n\n::: {#ebe33066 .cell execution_count=20}\n``` {.python .cell-code}\n# Task 2: Histograms and Density Plots\n# ----------------------------------------------------------\n\nfig, axes = plt.subplots(1, 2, figsize=(14, 5))\n\n# IMDS histogram with KDE\naxes[0].hist(bol_key['imds'].dropna(), bins=25, density=True,\n             color='steelblue', alpha=0.7, edgecolor='white')\nbol_key['imds'].dropna().plot.kde(ax=axes[0], color='darkblue', linewidth=2)\naxes[0].set_xlabel('Municipal Development Index (IMDS)')\naxes[0].set_ylabel('Density')\naxes[0].set_title('Distribution of IMDS across 339 Municipalities')\naxes[0].axvline(bol_key['imds'].mean(), color='red', linestyle='--',\n                label=f\"Mean = {bol_key['imds'].mean():.1f}\")\naxes[0].axvline(bol_key['imds'].median(), color='orange', linestyle='--',\n                label=f\"Median = {bol_key['imds'].median():.1f}\")\naxes[0].legend()\n\n# Log NTL histogram with KDE\naxes[1].hist(bol_key['ln_NTLpc2017'].dropna(), bins=25, density=True,\n             color='purple', alpha=0.7, edgecolor='white')\nbol_key['ln_NTLpc2017'].dropna().plot.kde(ax=axes[1], color='darkviolet', linewidth=2)\naxes[1].set_xlabel('Log Nighttime Lights per Capita (2017)')\naxes[1].set_ylabel('Density')\naxes[1].set_title('Distribution of Log NTL per Capita')\naxes[1].axvline(bol_key['ln_NTLpc2017'].mean(), color='red', linestyle='--',\n                label=f\"Mean = {bol_key['ln_NTLpc2017'].mean():.2f}\")\naxes[1].axvline(bol_key['ln_NTLpc2017'].median(), color='orange', linestyle='--',\n                label=f\"Median = {bol_key['ln_NTLpc2017'].median():.2f}\")\naxes[1].legend()\n\nplt.tight_layout()\nplt.show()\n\n# Discussion prompts:\n# 1. Is the IMDS distribution unimodal or multimodal?\n# 2. Is the NTL distribution symmetric or skewed?\n# 3. What might explain any bimodality? (urban vs rural)\n```\n\n::: {.cell-output .cell-output-display}\n![](ch02_Univariate_Data_Summary_files/figure-html/cell-21-output-1.png){width=1334 height=469}\n:::\n:::\n\n\n> **Key Concept 2.10: Spatial Data Distributions**\n>\n> Municipal-level data often exhibits **multimodality** reflecting the urban-rural divide. Unlike national statistics that produce single averages, municipality-level distributions can reveal distinct subpopulations—highly developed urban centers and less developed rural areas. Identifying these subgroups is essential for targeted policy interventions.\n\n#### Task 3: Box Plots by Department (Semi-guided)\n\n**Objective**: Create box plots of `imds` grouped by department (`dep`) to compare development across Bolivia's 9 departments.\n\n**Instructions**:\n\n1. Create a box plot of `imds` grouped by `dep` (9 departments)\n2. Order departments by median IMDS for clarity\n3. Identify which departments have the highest and lowest median development\n4. Which departments show the most spread (variability)?\n\n**Apply what you learned in section 2.3-2.4**: Use grouped box plots to compare distributions across categories.\n\n::: {#04517feb .cell execution_count=21}\n``` {.python .cell-code}\n# Task 3: Box Plots by Department\n# ----------------------------------------------------------\n\n# Your code here: Create box plots of IMDS by department\n#\n# Steps:\n# 1. Order departments by median IMDS\n# 2. Create horizontal box plot\n# 3. Add labels and formatting\n\n# Example structure:\n# dept_order = bol_key.groupby('dep')['imds'].median().sort_values().index\n# fig, ax = plt.subplots(figsize=(10, 7))\n# bol_key.boxplot(column='imds', by='dep', ax=ax, vert=False,\n#                 positions=range(len(dept_order)))\n# ax.set_xlabel('Municipal Development Index (IMDS)')\n# ax.set_ylabel('Department')\n# ax.set_title('Development Distribution by Department')\n# plt.suptitle('')  # Remove automatic title\n# plt.tight_layout()\n# plt.show()\n\n# Hint: You can also use seaborn for cleaner grouped box plots:\nimport seaborn as sns\ndept_order = bol_key.groupby('dep')['imds'].median().sort_values().index.tolist()\n\nfig, ax = plt.subplots(figsize=(10, 7))\nsns.boxplot(data=bol_key, x='imds', y='dep', order=dept_order,\n            palette='viridis', ax=ax)\nax.set_xlabel('Municipal Development Index (IMDS)')\nax.set_ylabel('Department')\nax.set_title('Municipal Development Distribution by Department')\nplt.tight_layout()\nplt.show()\n\n# IMDS by department: median and IQR\ndept_stats = bol_key.groupby('dep')['imds'].describe()[['50%', '25%', '75%', 'std']].round(1)\ndept_stats.columns = ['Median', 'Q1', 'Q3', 'Std Dev']\ndept_stats.sort_values('Median')\n```\n\n::: {.cell-output .cell-output-display}\n![](ch02_Univariate_Data_Summary_files/figure-html/cell-22-output-1.png){width=950 height=661}\n:::\n\n::: {.cell-output .cell-output-display execution_count=21}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Median</th>\n      <th>Q1</th>\n      <th>Q3</th>\n      <th>Std Dev</th>\n    </tr>\n    <tr>\n      <th>dep</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Pando</th>\n      <td>46.0</td>\n      <td>41.4</td>\n      <td>48.4</td>\n      <td>5.6</td>\n    </tr>\n    <tr>\n      <th>Chuquisaca</th>\n      <td>47.5</td>\n      <td>44.1</td>\n      <td>50.8</td>\n      <td>6.6</td>\n    </tr>\n    <tr>\n      <th>Potosí</th>\n      <td>47.5</td>\n      <td>40.9</td>\n      <td>51.7</td>\n      <td>7.6</td>\n    </tr>\n    <tr>\n      <th>Oruro</th>\n      <td>50.0</td>\n      <td>47.1</td>\n      <td>53.0</td>\n      <td>5.0</td>\n    </tr>\n    <tr>\n      <th>La Paz</th>\n      <td>50.5</td>\n      <td>47.5</td>\n      <td>53.0</td>\n      <td>5.4</td>\n    </tr>\n    <tr>\n      <th>Beni</th>\n      <td>51.0</td>\n      <td>47.0</td>\n      <td>52.9</td>\n      <td>4.5</td>\n    </tr>\n    <tr>\n      <th>Cochabamba</th>\n      <td>52.0</td>\n      <td>46.3</td>\n      <td>57.2</td>\n      <td>8.5</td>\n    </tr>\n    <tr>\n      <th>Santa Cruz</th>\n      <td>54.2</td>\n      <td>51.5</td>\n      <td>57.7</td>\n      <td>4.8</td>\n    </tr>\n    <tr>\n      <th>Tarija</th>\n      <td>59.5</td>\n      <td>57.4</td>\n      <td>63.5</td>\n      <td>5.5</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n#### Task 4: Log Transformations (Semi-guided)\n\n**Objective**: Compare the distribution of raw population (`pop2017`) with its log transformation to demonstrate how log transformations improve symmetry for skewed data.\n\n**Instructions**:\n\n1. Plot the histogram of raw `pop2017` — observe the extreme right skew\n2. Apply `np.log(pop2017)` and plot its histogram\n3. Compare summary statistics (skewness, kurtosis) before and after transformation\n4. Discuss why log transformations are standard practice for population and income data\n\n**Apply what you learned in section 2.5**: Log transformations convert multiplicative relationships into additive ones and reduce skewness.\n\n::: {#d2e0c7b2 .cell execution_count=22}\n``` {.python .cell-code}\n# Task 4: Log Transformations\n# ----------------------------------------------------------\n\n# Your code here: Compare raw vs log-transformed population\n#\n# Steps:\n# 1. Plot raw pop2017 histogram\n# 2. Plot np.log(pop2017) histogram\n# 3. Compare skewness and kurtosis\n\nimport numpy as np\n\npop = bol_key['pop2017'].dropna()\nlog_pop = np.log(pop)\n\nfig, axes = plt.subplots(1, 2, figsize=(14, 5))\n\n# Raw population\naxes[0].hist(pop, bins=30, color='coral', alpha=0.7, edgecolor='white')\naxes[0].set_xlabel('Population (2017)')\naxes[0].set_ylabel('Frequency')\naxes[0].set_title('Raw Population Distribution')\naxes[0].axvline(pop.mean(), color='red', linestyle='--',\n                label=f\"Mean = {pop.mean():,.0f}\")\naxes[0].axvline(pop.median(), color='blue', linestyle='--',\n                label=f\"Median = {pop.median():,.0f}\")\naxes[0].legend()\n\n# Log-transformed population\naxes[1].hist(log_pop, bins=30, color='teal', alpha=0.7, edgecolor='white')\naxes[1].set_xlabel('Log Population (2017)')\naxes[1].set_ylabel('Frequency')\naxes[1].set_title('Log-Transformed Population Distribution')\naxes[1].axvline(log_pop.mean(), color='red', linestyle='--',\n                label=f\"Mean = {log_pop.mean():.2f}\")\naxes[1].axvline(log_pop.median(), color='blue', linestyle='--',\n                label=f\"Median = {log_pop.median():.2f}\")\naxes[1].legend()\n\nplt.tight_layout()\nplt.show()\n\n# Effect of log transformation on population\nprint(f\"{'Measure':<15} {'Raw pop2017':>15} {'log(pop2017)':>15}\")\nprint(f\"{'Skewness':<15} {pop.skew():>15.3f} {log_pop.skew():>15.3f}\")\nprint(f\"{'Kurtosis':<15} {pop.kurtosis():>15.3f} {log_pop.kurtosis():>15.3f}\")\nprint(f\"{'Mean':<15} {pop.mean():>15,.0f} {log_pop.mean():>15.2f}\")\nprint(f\"{'Median':<15} {pop.median():>15,.0f} {log_pop.median():>15.2f}\")\n```\n\n::: {.cell-output .cell-output-display}\n![](ch02_Univariate_Data_Summary_files/figure-html/cell-23-output-1.png){width=1335 height=469}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nMeasure             Raw pop2017    log(pop2017)\nSkewness                  9.712           0.641\nKurtosis                110.387           2.119\nMean                     32,859            9.43\nMedian                   11,628            9.36\n```\n:::\n:::\n\n\n> **Key Concept 2.11: Development Indicator Interpretation**\n>\n> SDG composite indices like IMDS (0-100) aggregate multiple dimensions of development into a single score. While convenient for ranking, composite indices can mask important variation in specific dimensions. For example, a municipality may score well on education (SDG 4) but poorly on health (SDG 3). Examining individual SDG variables alongside composite indices provides a more complete picture.\n\n#### Task 5: Time Series of NTL (Independent)\n\n**Objective**: Calculate and plot the mean nighttime lights across municipalities for each year from 2012 to 2020 to examine the evolution of satellite-measured economic activity.\n\n**Instructions**:\n\n1. Calculate the mean of `ln_NTLpc2012` through `ln_NTLpc2020` across all municipalities for each year\n2. Plot the resulting time series (year on x-axis, mean log NTL on y-axis)\n3. Discuss: Is there a trend? Any notable changes? What might explain the pattern?\n\n**Apply what you learned in section 2.6**: Use time series visualization to identify trends and patterns.\n\n::: {#da05fd3a .cell execution_count=23}\n``` {.python .cell-code}\n# Task 5: Time Series of NTL\n# ----------------------------------------------------------\n\n# Your code here: Calculate mean NTL across municipalities for each year\n#\n# Steps:\n# 1. Select NTL columns for 2012-2020\n# 2. Calculate means\n# 3. Plot time series\n\n# Example structure:\n# ntl_cols = [f'ln_NTLpc{yr}' for yr in range(2012, 2021)]\n# years = list(range(2012, 2021))\n# mean_ntl = [bol_key[col].mean() for col in ntl_cols]\n#\n# fig, ax = plt.subplots(figsize=(10, 5))\n# ax.plot(years, mean_ntl, marker='o', color='navy', linewidth=2)\n# ax.set_xlabel('Year')\n# ax.set_ylabel('Mean Log NTL per Capita')\n# ax.set_title('Evolution of Nighttime Lights across Bolivian Municipalities')\n# ax.grid(True, alpha=0.3)\n# plt.tight_layout()\n# plt.show()\n```\n:::\n\n\n#### Task 6: Regional Distribution Analysis (Independent)\n\n**Objective**: Compare the distributions of `imds` across departments using overlapping histograms or violin plots. Write a 200-word summary of regional inequality in Bolivia.\n\n**Instructions**:\n\n1. Create overlapping histograms or violin plots of `imds` for at least 3 departments\n2. Compare the distributional shapes: Do some departments have more spread? More bimodality?\n3. Write a 200-word summary discussing what these distributions reveal about regional inequality in Bolivia\n4. Which departments might need the most targeted development interventions? Why?\n\n**Apply your skills**: This task combines histogram/density visualization with substantive economic interpretation.\n\n::: {#6a2e0db7 .cell execution_count=24}\n``` {.python .cell-code}\n# Task 6: Regional Distribution Analysis\n# ----------------------------------------------------------\n\n# Your code here: Compare IMDS distributions across departments\n#\n# Option A: Overlapping histograms (select 3-4 key departments)\n# Option B: Violin plots for all 9 departments\n# Option C: Ridge plot (multiple KDE curves stacked vertically)\n\n# Example structure (violin plots):\n# fig, ax = plt.subplots(figsize=(12, 7))\n# dept_order = bol_key.groupby('dep')['imds'].median().sort_values().index.tolist()\n# sns.violinplot(data=bol_key, x='imds', y='dep', order=dept_order,\n#                palette='coolwarm', ax=ax, inner='quartile')\n# ax.set_xlabel('Municipal Development Index (IMDS)')\n# ax.set_ylabel('Department')\n# ax.set_title('Distribution of Municipal Development by Department')\n# plt.tight_layout()\n# plt.show()\n\n# After creating your visualization, write a 200-word summary below:\n# print(\"REGIONAL INEQUALITY SUMMARY\")\n# print(\"=\" * 70)\n# print(\"Write your 200-word analysis here...\")\n```\n:::\n\n\n### What You've Learned from This Case Study\n\nBy applying Chapter 2's univariate analysis tools to Bolivia's municipal SDG data, you've characterized the *distribution* of development outcomes across 339 municipalities. Specifically, you've practiced:\n\n- **Descriptive statistics** for development indicators—mean, median, SD, skewness, and kurtosis\n- **Visualization of distributions** using histograms, box plots, and kernel density estimation (KDE)\n- **Log transformations** for highly skewed data like population\n- **Time series summary** of satellite-measured nighttime lights (2012-2020)\n- **Regional comparison** of development distributions across Bolivia's 9 departments\n\nThese univariate tools reveal the *shape* of Bolivia's development distribution—its central tendency, spread, and the urban-rural divide reflected in multimodal patterns. Understanding these distributional properties is the essential first step before more advanced analysis.\n\n**Connection to future chapters**: In Chapter 4, we'll test whether differences across departments are statistically significant. In Chapter 5, we'll explore *bivariate* relationships between satellite data and development. Later chapters will build progressively more sophisticated models for predicting and explaining municipal development outcomes.\n\n---\n\n**Well done!** You've now explored Bolivia's municipal development data using the full univariate analysis toolkit—from summary statistics to distributional visualization and transformation.\n\n",
    "supporting": [
      "ch02_Univariate_Data_Summary_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}