{
  "hash": "3488e999091b935eb41ae3a500c6f2a3",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 10. Data Summary for Multiple Regression\nexecute:\n  enabled: true\n  warning: false\n---\n\n\n**metricsAI: An Introduction to Econometrics with Python and AI in the Cloud**\n\n*[Carlos Mendez](https://carlos-mendez.org)*\n\n<img src=\"https://raw.githubusercontent.com/quarcs-lab/metricsai/main/images/ch10_visual_summary.jpg\" alt=\"Chapter 10 Visual Summary\" width=\"100%\">\n\nThis notebook provides an interactive introduction to multiple regression analysis. You'll learn how to work with multiple explanatory variables, interpret partial effects, assess model fit, and detect multicollinearity. All code runs directly in Google Colab without any local setup.\n\n[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/quarcs-lab/metricsai/blob/main/notebooks_colab/ch10_Data_Summary_for_Multiple_Regression.ipynb)\n<div class=\"chapter-resources\">\n<a href=\"https://www.youtube.com/watch?v=9398KshS_JA\" target=\"_blank\" class=\"resource-btn\">🎬 AI Video</a>\n<a href=\"https://carlos-mendez.my.canva.site/s10-data-summary-for-multiple-regression-pdf\" target=\"_blank\" class=\"resource-btn\">✨ AI Slides</a>\n<a href=\"https://cameron.econ.ucdavis.edu/aed/traedv1_10\" target=\"_blank\" class=\"resource-btn\">📊 Cameron Slides</a>\n<a href=\"https://app.edcafe.ai/quizzes/697868212f5d08069e04add5\" target=\"_blank\" class=\"resource-btn\">✏️ Quiz</a>\n<a href=\"https://app.edcafe.ai/chatbots/6978a0fd2f5d08069e0715f8\" target=\"_blank\" class=\"resource-btn\">🤖 AI Tutor</a>\n</div>\n\n\n## Chapter Overview\n\nThis chapter extends bivariate regression to the more realistic case where we want to predict an outcome using **multiple explanatory variables** simultaneously. Multiple regression allows us to estimate the partial effect of each variable while controlling for others—a crucial feature for empirical economic analysis.\n\n**Learning Objectives:**\n\nBy the end of this chapter, you will be able to:\n\n1. Extend bivariate regression concepts to multiple regression with several regressors\n2. Interpret pairwise correlations and use them for exploratory data analysis\n3. Understand the ordinary least squares (OLS) method for multiple regression\n4. Interpret partial effects: how one regressor affects $y$ while holding others constant\n5. Distinguish between partial effects and total effects\n6. Evaluate model fit using R-squared and adjusted R-squared\n7. Understand information criteria (AIC, BIC) for model selection\n8. Recognize when regression coefficients cannot be estimated (perfect collinearity)\n\n**Dataset used:**\n\n- **AED_HOUSE.DTA**: 29 houses sold in Davis, California (1999) with price, size, bedrooms, bathrooms, lot size, age, and month sold\n\n**Key economic question:**\nWhat is the effect of house size on price **after controlling** for other characteristics like bedrooms, bathrooms, and age?\n\n**Chapter outline:**\n\n- 10.1 Example: House Price and Characteristics\n- 10.2 Two-Way Scatterplots\n- 10.3 Correlation Analysis\n- 10.4 Multiple Regression Estimation\n- 10.5 Partial Effects — The FWL Theorem\n- 10.6 Model Fit Statistics\n- 10.7 Model Comparison\n- 10.8 Inestimable Models and Multicollinearity\n- Key Takeaways\n- Practice Exercises\n- Case Studies\n\n\n## Setup\n\nFirst, we import the necessary Python packages and configure the environment for reproducibility. All data will stream directly from GitHub.\n\n::: {#ce6f36bb .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Setup: Import libraries and configure environment\"}\n# --- Libraries ---\nimport numpy as np                        # numerical operations\nimport pandas as pd                       # data manipulation\nimport matplotlib.pyplot as plt           # plotting\nimport seaborn as sns                     # statistical visualization\nimport statsmodels.api as sm              # statistical models\nfrom statsmodels.formula.api import ols   # OLS with formula syntax\nfrom scipy import stats                   # statistical distributions\nimport random\nimport os\n\n# --- Reproducibility ---\nRANDOM_SEED = 42\nrandom.seed(RANDOM_SEED)\nnp.random.seed(RANDOM_SEED)\nos.environ['PYTHONHASHSEED'] = str(RANDOM_SEED)\n\n# --- Data source ---\nGITHUB_DATA_URL = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/\"\n\n# --- Plotting style (dark theme matching book design) ---\nplt.style.use('dark_background')\nsns.set_style(\"darkgrid\")\nplt.rcParams.update({\n    'axes.facecolor': '#1a2235',\n    'figure.facecolor': '#12162c',\n    'grid.color': '#3a4a6b',\n    'figure.figsize': (10, 6),\n    'text.color': 'white',\n    'axes.labelcolor': 'white',\n    'xtick.color': 'white',\n    'ytick.color': 'white',\n    'axes.edgecolor': '#1a2235',\n})\n\nprint(\"Setup complete! Ready to analyze house price data.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSetup complete! Ready to analyze house price data.\n```\n:::\n:::\n\n\n## 10.1: Example - House Price and Characteristics\n\nWe begin with a real estate dataset from Davis, California. Understanding house prices is a classic economic application because prices reflect both fundamental characteristics (size, bedrooms) and market conditions.\n\n**The dataset contains:**\n\n- **Price**: Sale price in dollars\n- **Size**: House size in square feet\n- **Bedrooms**: Number of bedrooms\n- **Bathrooms**: Number of bathrooms\n- **Lotsize**: Size of lot (1=small, 2=medium, 3=large)\n- **Age**: House age in years\n- **Monthsold**: Month of year house was sold\n\n**Economic motivation:** A simple regression of price on bedrooms might find a positive relationship, but is this because bedrooms directly add value, or because houses with more bedrooms tend to be larger? Multiple regression helps us disentangle these effects.\n\n::: {#49bc803a .cell execution_count=2}\n``` {.python .cell-code}\n# Load house price data\ndata_house = pd.read_stata(GITHUB_DATA_URL + 'AED_HOUSE.DTA')\n\n# Display first few observations\nprint(\"First 10 observations:\")\ndata_house[['price', 'size', 'bedrooms', 'bathrooms', 'lotsize', 'age', 'monthsold']].head(10)\n\n# Display data summary\nprint(\"\\nSummary statistics:\")\ndata_house.describe()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFirst 10 observations:\n\nSummary statistics:\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>price</th>\n      <th>size</th>\n      <th>bedrooms</th>\n      <th>bathrooms</th>\n      <th>lotsize</th>\n      <th>age</th>\n      <th>monthsold</th>\n      <th>list</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>29.000000</td>\n      <td>29.000000</td>\n      <td>29.000000</td>\n      <td>29.000000</td>\n      <td>29.000000</td>\n      <td>29.000000</td>\n      <td>29.000000</td>\n      <td>29.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>253910.344828</td>\n      <td>1882.758621</td>\n      <td>3.793103</td>\n      <td>2.206897</td>\n      <td>2.137931</td>\n      <td>36.413792</td>\n      <td>5.965517</td>\n      <td>257824.137931</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>37390.710695</td>\n      <td>398.272130</td>\n      <td>0.675030</td>\n      <td>0.341144</td>\n      <td>0.693034</td>\n      <td>7.118975</td>\n      <td>1.679344</td>\n      <td>40860.264099</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>204000.000000</td>\n      <td>1400.000000</td>\n      <td>3.000000</td>\n      <td>2.000000</td>\n      <td>1.000000</td>\n      <td>23.000000</td>\n      <td>3.000000</td>\n      <td>199900.000000</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>233000.000000</td>\n      <td>1600.000000</td>\n      <td>3.000000</td>\n      <td>2.000000</td>\n      <td>2.000000</td>\n      <td>31.000000</td>\n      <td>5.000000</td>\n      <td>239000.000000</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>244000.000000</td>\n      <td>1800.000000</td>\n      <td>4.000000</td>\n      <td>2.000000</td>\n      <td>2.000000</td>\n      <td>35.000000</td>\n      <td>6.000000</td>\n      <td>245000.000000</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>270000.000000</td>\n      <td>2000.000000</td>\n      <td>4.000000</td>\n      <td>2.500000</td>\n      <td>3.000000</td>\n      <td>39.000000</td>\n      <td>7.000000</td>\n      <td>269000.000000</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>375000.000000</td>\n      <td>3300.000000</td>\n      <td>6.000000</td>\n      <td>3.000000</td>\n      <td>3.000000</td>\n      <td>51.000000</td>\n      <td>8.000000</td>\n      <td>386000.000000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Bivariate vs. Multiple Regression\n\nLet's compare a simple regression (price on bedrooms only) with a multiple regression (price on bedrooms AND size). This illustrates how controlling for other variables changes coefficient estimates.\n\n**Key insight:** In the bivariate regression, the bedrooms coefficient captures both the direct effect of bedrooms and the indirect effect through correlation with size. In multiple regression, we isolate the **partial effect** of bedrooms holding size constant.\n\n::: {#c0350887 .cell execution_count=3}\n``` {.python .cell-code}\n# Bivariate regression: price ~ bedrooms\nmodel_bivariate = ols('price ~ bedrooms', data=data_house).fit()\n\n# Key results: bivariate\nprint(f\"Bivariate: bedrooms coef = ${model_bivariate.params['bedrooms']:,.2f}, R² = {model_bivariate.rsquared:.4f}\")\n\n# Full regression output\nmodel_bivariate.summary()\n\n# Multiple regression: price ~ bedrooms + size\nmodel_multiple = ols('price ~ bedrooms + size', data=data_house).fit()\n\n# Key results: multiple\nprint(f\"Multiple: bedrooms coef = ${model_multiple.params['bedrooms']:,.2f}, R² = {model_multiple.rsquared:.4f}\")\n\n# Full regression output\nmodel_multiple.summary()\n\n# Compare bedrooms coefficient\n# COEFFICIENT COMPARISON\nprint(f\"Bedrooms coefficient (bivariate):  ${model_bivariate.params['bedrooms']:,.2f}\")\nprint(f\"Bedrooms coefficient (multiple):   ${model_multiple.params['bedrooms']:,.2f}\")\nprint(f\"Change: ${model_multiple.params['bedrooms'] - model_bivariate.params['bedrooms']:,.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBivariate: bedrooms coef = $23,667.30, R² = 0.1826\nMultiple: bedrooms coef = $1,553.46, R² = 0.6180\nBedrooms coefficient (bivariate):  $23,667.30\nBedrooms coefficient (multiple):   $1,553.46\nChange: $-22,113.84\n```\n:::\n:::\n\n\n> **Key Concept 10.1: Partial Effects vs. Total Effects in Multiple Regression**\n>\n> In bivariate regression, the bedrooms coefficient (\\$23,667) captures both the direct effect of bedrooms and the indirect effect through correlation with size. In multiple regression, the bedrooms coefficient drops to \\$1,553 — the **partial effect** holding size constant. This dramatic change illustrates why controlling for confounders is essential for isolating individual variable effects.\n\n## 10.2: Two-Way Scatterplots\n\nBefore running multiple regression, it's useful to visualize pairwise relationships between variables. A **scatterplot matrix** shows all two-way scatterplots simultaneously.\n\n**What to look for:**\n\n- Strong linear relationships (potential predictors of price)\n- Correlation between explanatory variables (potential multicollinearity)\n- Outliers or non-linear patterns\n\nThe diagonal shows the distribution of each variable using kernel density estimates (KDE).\n\n::: {#e827caec .cell execution_count=4}\n``` {.python .cell-code}\n# Create scatterplot matrix\nplot_vars = ['price', 'size', 'bedrooms', 'age']\ng = sns.pairplot(data_house[plot_vars], diag_kind='kde',\n                 plot_kws={'alpha': 0.6, 's': 50})  # alpha = transparency, s = marker size\ng.fig.suptitle('Figure 10.1: Scatterplot Matrix - House Price Data', \n               fontsize=14, fontweight='bold', y=1.00)\nplt.tight_layout()\nplt.show()\n\nprint(\"Scatterplot matrix created.\")\nprint(\"Notice: Price shows strongest relationship with Size.\")\n```\n\n::: {.cell-output .cell-output-display}\n![](ch10_Data_Summary_for_Multiple_Regression_files/figure-html/cell-5-output-1.png){width=950 height=965}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nScatterplot matrix created.\nNotice: Price shows strongest relationship with Size.\n```\n:::\n:::\n\n\n> **Key Concept 10.2: Exploratory Data Analysis with Scatterplot Matrices**\n>\n> Pairwise scatterplot matrices display all two-way relationships simultaneously, revealing linear associations, nonlinearities, clusters, and outliers before formal modeling. They also highlight potential multicollinearity: if two regressors are tightly correlated (e.g., size and bedrooms), their individual effects may be hard to separate in a regression.\n\n## 10.3: Correlation Analysis\n\nThe **correlation coefficient** measures the strength of linear association between two variables, ranging from -1 (perfect negative) to +1 (perfect positive).\n\n**Correlation matrix insights:**\n\n- **Price is most correlated with Size** (r = 0.79), then Bedrooms (r = 0.43)\n- **Size and Bedrooms are correlated** (r = 0.52), which can cause multicollinearity\n- Correlation ≠ causation (merely shows association)\n\nA correlation heatmap provides visual representation with color intensity showing strength of correlation.\n\n::: {#658fa235 .cell execution_count=5}\n``` {.python .cell-code}\n# Calculate correlation matrix\ncorr_vars = ['price', 'size', 'bedrooms', 'bathrooms', 'lotsize', 'age', 'monthsold']\ncorr_matrix = data_house[corr_vars].corr()\n\nprint(\"Correlation Matrix:\")\ncorr_matrix\n\n# Visualize correlation matrix as heatmap\nfig, ax = plt.subplots(figsize=(10, 8))\nsns.heatmap(corr_matrix, annot=True, fmt='.3f', cmap='coolwarm', center=0,\n            square=True, linewidths=1, cbar_kws={\"shrink\": 0.8})\nax.set_title('Correlation Matrix Heatmap', fontsize=14, fontweight='bold')\nplt.tight_layout()\nplt.show()\n\nprint(f\"Price-Size correlation: {corr_matrix.loc['price', 'size']:.3f}\")\nprint(f\"Size-Bedrooms correlation: {corr_matrix.loc['size', 'bedrooms']:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCorrelation Matrix:\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](ch10_Data_Summary_for_Multiple_Regression_files/figure-html/cell-6-output-2.png){width=845 height=758}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nPrice-Size correlation: 0.786\nSize-Bedrooms correlation: 0.518\n```\n:::\n:::\n\n\n> **Key Concept 10.3: Correlation vs. Causation in Multivariate Analysis**\n>\n> High bivariate correlation (e.g., bedrooms-price, $r = 0.43$) may diminish or vanish after controlling for confounders. In our data, bedrooms correlate with price largely because bigger houses have more bedrooms. Multiple regression isolates each variable's partial contribution, revealing that size — not bedrooms — drives most of the price variation.\n\n## 10.4: Multiple Regression Estimation\n\nNow we estimate the **full multiple regression model** with all available predictors. The regression equation is:\n\n$$\\widehat{\\text{price}} = b_1 + b_2 \\times \\text{size} + b_3 \\times \\text{bedrooms} + b_4 \\times \\text{bathrooms} + b_5 \\times \\text{lotsize} + b_6 \\times \\text{age} + b_7 \\times \\text{monthsold}$$\n\n**Ordinary Least Squares (OLS)** chooses coefficients $b_1, ..., b_7$ to minimize the sum of squared residuals:\n\n$$\\min \\sum_{i=1}^{n} (y_i - \\widehat{y}_i)^2$$\n\nwhere $y_i$ is the actual price and $\\widehat{y}_i$ is the predicted price.\n\n::: {#d7ab5fbc .cell execution_count=6}\n``` {.python .cell-code}\n# Estimate full multiple regression model\nmodel_full = ols('price ~ size + bedrooms + bathrooms + lotsize + age + monthsold',\n                 data=data_house).fit()\n\n# Key results\nr_squared_full = model_full.rsquared\nadj_r_squared_full = model_full.rsquared_adj\nsize_coef = model_full.params['size']\n\nprint(f\"Estimated equation: price = {model_full.params['Intercept']:,.0f} + {size_coef:.2f} x size + ...\")\nprint(f\"Size effect: each additional sq ft is associated with ${size_coef:,.2f} higher price\")\nprint(f\"R-squared: {r_squared_full:.4f} ({r_squared_full*100:.1f}% of variation explained)\")\nprint(f\"Adjusted R-squared: {adj_r_squared_full:.4f}\")\n\n# Full regression output\nmodel_full.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEstimated equation: price = 137,791 + 68.37 x size + ...\nSize effect: each additional sq ft is associated with $68.37 higher price\nR-squared: 0.6506 (65.1% of variation explained)\nAdjusted R-squared: 0.5552\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=6}\n```{=html}\n<table class=\"simpletable\">\n<caption>OLS Regression Results</caption>\n<tr>\n  <th>Dep. Variable:</th>          <td>price</td>      <th>  R-squared:         </th> <td>   0.651</td>\n</tr>\n<tr>\n  <th>Model:</th>                   <td>OLS</td>       <th>  Adj. R-squared:    </th> <td>   0.555</td>\n</tr>\n<tr>\n  <th>Method:</th>             <td>Least Squares</td>  <th>  F-statistic:       </th> <td>   6.826</td>\n</tr>\n<tr>\n  <th>Date:</th>             <td>Sat, 18 Apr 2026</td> <th>  Prob (F-statistic):</th> <td>0.000342</td>\n</tr>\n<tr>\n  <th>Time:</th>                 <td>18:42:31</td>     <th>  Log-Likelihood:    </th> <td> -330.74</td>\n</tr>\n<tr>\n  <th>No. Observations:</th>      <td>    29</td>      <th>  AIC:               </th> <td>   675.5</td>\n</tr>\n<tr>\n  <th>Df Residuals:</th>          <td>    22</td>      <th>  BIC:               </th> <td>   685.1</td>\n</tr>\n<tr>\n  <th>Df Model:</th>              <td>     6</td>      <th>                     </th>     <td> </td>   \n</tr>\n<tr>\n  <th>Covariance Type:</th>      <td>nonrobust</td>    <th>                     </th>     <td> </td>   \n</tr>\n</table>\n<table class=\"simpletable\">\n<tr>\n      <td></td>         <th>coef</th>     <th>std err</th>      <th>t</th>      <th>P>|t|</th>  <th>[0.025</th>    <th>0.975]</th>  \n</tr>\n<tr>\n  <th>Intercept</th> <td> 1.378e+05</td> <td> 6.15e+04</td> <td>    2.242</td> <td> 0.035</td> <td> 1.03e+04</td> <td> 2.65e+05</td>\n</tr>\n<tr>\n  <th>size</th>      <td>   68.3694</td> <td>   15.389</td> <td>    4.443</td> <td> 0.000</td> <td>   36.454</td> <td>  100.285</td>\n</tr>\n<tr>\n  <th>bedrooms</th>  <td> 2685.3151</td> <td> 9192.526</td> <td>    0.292</td> <td> 0.773</td> <td>-1.64e+04</td> <td> 2.17e+04</td>\n</tr>\n<tr>\n  <th>bathrooms</th> <td> 6832.8800</td> <td> 1.57e+04</td> <td>    0.435</td> <td> 0.668</td> <td>-2.58e+04</td> <td> 3.94e+04</td>\n</tr>\n<tr>\n  <th>lotsize</th>   <td> 2303.2214</td> <td> 7226.535</td> <td>    0.319</td> <td> 0.753</td> <td>-1.27e+04</td> <td> 1.73e+04</td>\n</tr>\n<tr>\n  <th>age</th>       <td> -833.0386</td> <td>  719.335</td> <td>   -1.158</td> <td> 0.259</td> <td>-2324.847</td> <td>  658.770</td>\n</tr>\n<tr>\n  <th>monthsold</th> <td>-2088.5036</td> <td> 3520.898</td> <td>   -0.593</td> <td> 0.559</td> <td>-9390.399</td> <td> 5213.392</td>\n</tr>\n</table>\n<table class=\"simpletable\">\n<tr>\n  <th>Omnibus:</th>       <td> 1.317</td> <th>  Durbin-Watson:     </th> <td>   1.259</td>\n</tr>\n<tr>\n  <th>Prob(Omnibus):</th> <td> 0.518</td> <th>  Jarque-Bera (JB):  </th> <td>   0.980</td>\n</tr>\n<tr>\n  <th>Skew:</th>          <td> 0.151</td> <th>  Prob(JB):          </th> <td>   0.612</td>\n</tr>\n<tr>\n  <th>Kurtosis:</th>      <td> 2.152</td> <th>  Cond. No.          </th> <td>2.59e+04</td>\n</tr>\n</table><br/><br/>Notes:<br/>[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.<br/>[2] The condition number is large, 2.59e+04. This might indicate that there are<br/>strong multicollinearity or other numerical problems.\n```\n:::\n:::\n\n\n### Coefficient Interpretation with Confidence Intervals\n\nEach regression coefficient represents a **partial effect**: the expected change in price when that variable increases by one unit, **holding all other variables constant**.\n\n**Example interpretation (Size coefficient):**\n\n- Coefficient ≈ \\$68.37 per square foot\n- Interpretation: A one square foot increase in house size is associated with a \\$68.37 increase in price, holding bedrooms, bathrooms, lot size, age, and month sold constant.\n\nThe 95% confidence interval tells us the range of plausible values for each coefficient.\n\n::: {#39390ad6 .cell execution_count=7}\n``` {.python .cell-code}\n# Display coefficients with 95% confidence intervals\nconf_int = model_full.conf_int(alpha=0.05)\ncoef_table = pd.DataFrame({\n    'Coefficient': model_full.params,\n    'Std. Error': model_full.bse,\n    'CI Lower': conf_int.iloc[:, 0],\n    'CI Upper': conf_int.iloc[:, 1],\n    't-statistic': model_full.tvalues,\n    'p-value': model_full.pvalues\n})\n\nprint(\"Coefficients with 95% Confidence Intervals:\")\ncoef_table\n\n# Size is the only statistically significant predictor (p < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCoefficients with 95% Confidence Intervals:\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Coefficient</th>\n      <th>Std. Error</th>\n      <th>CI Lower</th>\n      <th>CI Upper</th>\n      <th>t-statistic</th>\n      <th>p-value</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Intercept</th>\n      <td>137791.065699</td>\n      <td>61464.951869</td>\n      <td>10320.557398</td>\n      <td>265261.573999</td>\n      <td>2.241783</td>\n      <td>0.035387</td>\n    </tr>\n    <tr>\n      <th>size</th>\n      <td>68.369419</td>\n      <td>15.389472</td>\n      <td>36.453608</td>\n      <td>100.285230</td>\n      <td>4.442610</td>\n      <td>0.000205</td>\n    </tr>\n    <tr>\n      <th>bedrooms</th>\n      <td>2685.315122</td>\n      <td>9192.525674</td>\n      <td>-16378.816300</td>\n      <td>21749.446543</td>\n      <td>0.292119</td>\n      <td>0.772932</td>\n    </tr>\n    <tr>\n      <th>bathrooms</th>\n      <td>6832.880015</td>\n      <td>15721.191544</td>\n      <td>-25770.875723</td>\n      <td>39436.635753</td>\n      <td>0.434629</td>\n      <td>0.668065</td>\n    </tr>\n    <tr>\n      <th>lotsize</th>\n      <td>2303.221371</td>\n      <td>7226.535205</td>\n      <td>-12683.695364</td>\n      <td>17290.138107</td>\n      <td>0.318717</td>\n      <td>0.752947</td>\n    </tr>\n    <tr>\n      <th>age</th>\n      <td>-833.038602</td>\n      <td>719.334544</td>\n      <td>-2324.847139</td>\n      <td>658.769936</td>\n      <td>-1.158068</td>\n      <td>0.259254</td>\n    </tr>\n    <tr>\n      <th>monthsold</th>\n      <td>-2088.503625</td>\n      <td>3520.897859</td>\n      <td>-9390.398871</td>\n      <td>5213.391620</td>\n      <td>-0.593174</td>\n      <td>0.559114</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n> **Key Concept 10.4: Interpreting Partial Effects in Multiple Regression**\n>\n> Each coefficient $b_j$ measures the expected change in $y$ when $x_j$ increases by one unit, **holding all other regressors constant**. For example, a size coefficient of \\$68.37 means each additional square foot is associated with a \\$68.37 price increase, controlling for bedrooms, bathrooms, lot size, age, and month sold. Statistical significance is assessed through confidence intervals and $t$-tests.\n\n## 10.5: Partial Effects - The FWL Theorem\n\nThe **Frisch-Waugh-Lovell (FWL) Theorem** states that the coefficient on any variable in multiple regression equals the coefficient from a bivariate regression of $y$ on the **residualized** version of that variable.\n\n**Demonstration:**\n\n1. Regress `size` on all other variables, obtain residuals $\\widetilde{\\text{size}}$\n2. Regress `price` on $\\widetilde{\\text{size}}$ only\n3. The coefficient will exactly match the `size` coefficient from the full multiple regression\n\n**Intuition:** The residual $\\widetilde{\\text{size}}$ represents the variation in size that is **not explained** by other variables. This is why multiple regression isolates partial effects.\n\n::: {#02a73b18 .cell execution_count=8}\n``` {.python .cell-code}\n# Step 1: Regress size on all other variables\nmodel_size_on_others = ols('size ~ bedrooms + bathrooms + lotsize + age + monthsold',\n                            data=data_house).fit()\nresid_size = model_size_on_others.resid\n\n# Step 2: Regress price on residualized size\ndata_house['resid_size'] = resid_size\nmodel_price_on_resid = ols('price ~ resid_size', data=data_house).fit()\n\n# Compare coefficients\n# DEMONSTRATION: FWL THEOREM (Partial Effects)\nprint(f\"Size coefficient from FULL multiple regression:  {model_full.params['size']:.10f}\")\nprint(f\"Coefficient on residualized size (bivariate):    {model_price_on_resid.params['resid_size']:.10f}\")\nprint(f\"Difference (numerical precision):                 {abs(model_full.params['size'] - model_price_on_resid.params['resid_size']):.15f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSize coefficient from FULL multiple regression:  68.3694189767\nCoefficient on residualized size (bivariate):    68.3694189767\nDifference (numerical precision):                 0.000000000000071\n```\n:::\n:::\n\n\n> **Key Concept 10.5: The Frisch-Waugh-Lovell (FWL) Theorem**\n>\n> The partial effect of $x_j$ in a multiple regression equals the slope from a bivariate regression of $y$ on $\\widetilde{x}_j$, where $\\widetilde{x}_j$ is the residual from regressing $x_j$ on all other regressors. Intuitively, $\\widetilde{x}_j$ captures the variation in $x_j$ that is independent of the other variables — this is exactly what multiple regression uses to estimate partial effects.\n\n## 10.6: Model Fit Statistics\n\nSeveral statistics summarize how well the regression model fits the data:\n\n**R-squared ($R^2$):**\n\n- Fraction of variation in $y$ explained by the regressors\n- Formula: $R^2 = \\frac{\\text{Explained SS}}{\\text{Total SS}} = 1 - \\frac{\\text{Residual SS}}{\\text{Total SS}}$\n- Range: 0 to 1 (higher is better fit)\n- **Problem:** Always increases when adding variables (even irrelevant ones)\n\n**Adjusted R-squared ($\\bar{R}^2$):**\n\n- Penalizes model complexity (number of parameters $k$)\n- Formula: $\\bar{R}^2 = 1 - \\frac{\\text{RSS}/(n-k)}{\\text{TSS}/(n-1)}$\n- Can decrease when adding unhelpful variables\n- Preferred for model comparison\n\n**Root MSE (Standard error of regression):**\n\n- Typical size of prediction error\n- Formula: $s_e = \\sqrt{\\frac{1}{n-k}\\sum (y_i - \\widehat{y}_i)^2}$\n- Same units as $y$ (dollars in our case)\n\n::: {#18a24ad3 .cell execution_count=9}\n``` {.python .cell-code}\n# Calculate and display model fit statistics\nn = len(data_house)\nk = len(model_full.params)  # includes intercept\ndf = n - k\n\n# MODEL FIT STATISTICS\nprint(f\"Sample size (n):               {n}\")\nprint(f\"Number of parameters (k):      {k}\")\nprint(f\"Degrees of freedom (n-k):      {df}\")\nprint(f\"\\nR-squared:                     {model_full.rsquared:.6f}\")\nprint(f\"Adjusted R-squared:            {model_full.rsquared_adj:.6f}\")\nprint(f\"Root MSE:                      ${np.sqrt(model_full.mse_resid):,.2f}\")\n\n# Verify R² = [Corr(y, ŷ)]²\npredicted = model_full.fittedvalues\ncorr_y_yhat = np.corrcoef(data_house['price'], predicted)[0, 1]\nprint(f\"\\nVerification: R² = [Corr(y, ŷ)]²\")\nprint(f\"  Correlation(y, ŷ):           {corr_y_yhat:.6f}\")\nprint(f\"  [Correlation(y, ŷ)]²:        {corr_y_yhat**2:.6f}\")\nprint(f\"  R² from model:                {model_full.rsquared:.6f}\")\nprint(f\"  Match: {np.isclose(corr_y_yhat**2, model_full.rsquared)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSample size (n):               29\nNumber of parameters (k):      7\nDegrees of freedom (n-k):      22\n\nR-squared:                     0.650553\nAdjusted R-squared:            0.555249\nRoot MSE:                      $24,935.73\n\nVerification: R² = [Corr(y, ŷ)]²\n  Correlation(y, ŷ):           0.806569\n  [Correlation(y, ŷ)]²:        0.650553\n  R² from model:                0.650553\n  Match: True\n```\n:::\n:::\n\n\n### Information Criteria (AIC and BIC)\n\n**Akaike Information Criterion (AIC)** and **Bayesian Information Criterion (BIC)** are more sophisticated measures that penalize model complexity:\n\n$$\\text{AIC} = n \\times \\ln(\\widehat{\\sigma}_e^2) + n(1 + \\ln 2\\pi) + 2k$$\n$$\\text{BIC} = n \\times \\ln(\\widehat{\\sigma}_e^2) + n(1 + \\ln 2\\pi) + k \\times \\ln(n)$$\n\n**Key points:**\n\n- **Lower values are better** (unlike R²)\n- BIC penalizes complexity more heavily than AIC\n- Useful for comparing non-nested models\n- Different software packages may use different conventions (scaling by $n$)\n\n::: {#691ab298 .cell execution_count=10}\n``` {.python .cell-code}\n# Calculate information criteria\n# INFORMATION CRITERIA\n\n# AIC and BIC from statsmodels\nprint(f\"AIC (statsmodels):             {model_full.aic:.4f}\")\nprint(f\"BIC (statsmodels):             {model_full.bic:.4f}\")\n\n# Manual calculation (Stata convention)\nrss = np.sum(model_full.resid ** 2)\naic_stata = n * np.log(rss/n) + n * (1 + np.log(2*np.pi)) + 2*k\nbic_stata = n * np.log(rss/n) + n * (1 + np.log(2*np.pi)) + k*np.log(n)\n\nprint(f\"\\nAIC (Stata convention):        {aic_stata:.4f}\")\nprint(f\"BIC (Stata convention):        {bic_stata:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAIC (statsmodels):             675.4824\nBIC (statsmodels):             685.0535\n\nAIC (Stata convention):        675.4824\nBIC (Stata convention):        685.0535\n```\n:::\n:::\n\n\n> **Key Concept 10.6: Model Selection with Adjusted R-squared vs. Information Criteria**\n>\n> Adjusted $R^2$ penalizes complexity mildly by dividing sums of squares by degrees of freedom. Information criteria (AIC, BIC) impose stronger penalties: BIC = $n \\ln(\\hat{\\sigma}_e^2) + k \\ln(n)$. Smaller AIC/BIC values indicate better models. BIC is generally preferred because its penalty grows with sample size, favoring more parsimonious specifications.\n\n## 10.7: Model Comparison\n\nIt's often useful to compare multiple model specifications side-by-side. Here we compare:\n\n- **Simple model:** Price predicted by size only\n- **Full model:** Price predicted by all variables\n\n**Key comparison points:**\n\n- How much does R² improve?\n- Does adjusted R² improve (accounting for added complexity)?\n- How do coefficient estimates change?\n\n**Economic interpretation:** If adding 5 more variables only modestly improves fit, the simple model may be preferred (parsimony principle).\n\n::: {#36d17553 .cell execution_count=11}\n``` {.python .cell-code}\n# Estimate simple model (size only)\nmodel_simple = ols('price ~ size', data=data_house).fit()\n\n# Create comparison table\n# MODEL COMPARISON: Simple vs. Full\n\ncomparison_stats = pd.DataFrame({\n    'Model': ['Simple (size only)', 'Full (all variables)'],\n    'R²': [model_simple.rsquared, model_full.rsquared],\n    'Adj R²': [model_simple.rsquared_adj, model_full.rsquared_adj],\n    'AIC': [model_simple.aic, model_full.aic],\n    'BIC': [model_simple.bic, model_full.bic],\n    'N': [n, n]\n})\n\ncomparison_stats.to_string(index=False)\n\nprint(f\"R² increases from {model_simple.rsquared:.3f} to {model_full.rsquared:.3f}\")\nprint(f\"Adj R² decreases from {model_simple.rsquared_adj:.3f} to {model_full.rsquared_adj:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR² increases from 0.617 to 0.651\nAdj R² decreases from 0.603 to 0.555\n```\n:::\n:::\n\n\n> **Key Concept 10.7: The Parsimony Principle**\n>\n> Simpler models are preferred unless additional variables meaningfully improve fit. In our house price example, adding five variables beyond size barely increased $R^2$ (0.618 $\\to$ 0.651) while adjusted $R^2$ actually fell (0.603 $\\to$ 0.555). Check adjusted $R^2$, AIC, and BIC — if they don't improve, the simpler model is preferred.\n\n## 10.8: Inestimable Models and Multicollinearity\n\n**Perfect multicollinearity** occurs when one regressor is an exact linear combination of others. In this case, OLS cannot estimate all coefficients (the model is \"inestimable\").\n\n**Example:** If we create `size_twice = 2 × size` and include both `size` and `size_twice` as regressors, the model is perfectly collinear.\n\n**Variance Inflation Factor (VIF)** detects multicollinearity:\n\n- VIF measures how much a variable's variance is inflated due to correlation with other regressors\n- Formula: $VIF_j = \\frac{1}{1 - R_j^2}$ where $R_j^2$ is from regressing $x_j$ on all other $x$'s\n- **Rule of thumb:** VIF > 10 indicates problematic multicollinearity\n\n**Consequences of high multicollinearity:**\n\n- Large standard errors (imprecise estimates)\n- Unstable coefficients (small data changes → big estimate changes)\n- Difficulty interpreting individual effects\n\n::: {#1f7998ba .cell execution_count=12}\n``` {.python .cell-code}\n# Demonstrate perfect multicollinearity\n# DEMONSTRATION: Perfect Multicollinearity\n\n# Create a perfectly collinear variable\ndata_house['size_twice'] = 2 * data_house['size']\n\nprint(\"Creating variable: size_twice = 2 × size\")\nprint(\"Attempting to estimate: price ~ size + size_twice + bedrooms\\n\")\n\ntry:\n    model_collinear = ols('price ~ size + size_twice + bedrooms', data=data_house).fit()\n    print(\"Model estimated (software automatically dropped one variable):\")\n    model_collinear.summary()\nexcept Exception as e:\n    print(f\"Error: {type(e).__name__}\")\n    print(f\"Message: {str(e)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCreating variable: size_twice = 2 × size\nAttempting to estimate: price ~ size + size_twice + bedrooms\n\nModel estimated (software automatically dropped one variable):\n```\n:::\n:::\n\n\n### Variance Inflation Factors (VIF)\n\nNow let's calculate VIF for each variable in our full model to check for multicollinearity problems.\n\n::: {#fa4e21fb .cell execution_count=13}\n``` {.python .cell-code}\n# Calculate VIF for each variable in the full model\nfrom statsmodels.stats.outliers_influence import variance_inflation_factor\n\nX = data_house[['size', 'bedrooms', 'bathrooms', 'lotsize', 'age', 'monthsold']]\nvif_data = pd.DataFrame()\nvif_data[\"Variable\"] = X.columns\nvif_data[\"VIF\"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]\n\n# VARIANCE INFLATION FACTORS (VIF)\nvif_data.to_string(index=False)\n\n\nmax_vif = vif_data['VIF'].max()\nif max_vif > 10:\n    print(f\"\\nWarning: Maximum VIF = {max_vif:.2f} indicates multicollinearity issues.\")\nelif max_vif > 5:\n    print(f\"\\nNote: Maximum VIF = {max_vif:.2f} shows moderate multicollinearity.\")\nelse:\n    print(f\"\\nGood: Maximum VIF = {max_vif:.2f} - no serious multicollinearity detected.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nWarning: Maximum VIF = 57.82 indicates multicollinearity issues.\n```\n:::\n:::\n\n\n> **Key Concept 10.8: Detecting Multicollinearity with VIF**\n>\n> The Variance Inflation Factor (VIF) quantifies how much a coefficient's variance is inflated due to correlation with other regressors. VIF$_j = 1/(1 - R_j^2)$, where $R_j^2$ is from regressing $x_j$ on all other regressors. A VIF above 5 suggests moderate concern; above 10 indicates severe multicollinearity that inflates standard errors and destabilizes estimates. Perfect collinearity (VIF $\\to \\infty$) makes coefficients inestimable.\n\n### Visualization: Actual vs. Predicted Values\n\nA plot of actual vs. predicted values helps visualize model fit. Points close to the 45-degree line indicate accurate predictions.\n\n::: {#ad1009fe .cell execution_count=14}\n``` {.python .cell-code}\n# Create actual vs predicted plot\nfig, ax = plt.subplots(figsize=(10, 6))\nax.scatter(data_house['price'], model_full.fittedvalues, alpha=0.6, s=50, color='#22d3ee')  # alpha = transparency, s = marker size\nax.plot([data_house['price'].min(), data_house['price'].max()],\n        [data_house['price'].min(), data_house['price'].max()],\n        'r--', linewidth=2, label='Perfect prediction (45° line)')\nax.set_xlabel('Actual Price ($1000s)', fontsize=12)\nax.set_ylabel('Predicted Price ($1000s)', fontsize=12)\nax.set_title('Actual vs Predicted House Prices', fontsize=14, fontweight='bold')\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n\nprint(\"Points close to the red line indicate accurate predictions.\")\n```\n\n::: {.cell-output .cell-output-display}\n![](ch10_Data_Summary_for_Multiple_Regression_files/figure-html/cell-15-output-1.png){width=950 height=565}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nPoints close to the red line indicate accurate predictions.\n```\n:::\n:::\n\n\n**What to look for in this actual vs. predicted plot:**\n\n- **Alignment with 45-degree line**: Points close to the red dashed line indicate accurate predictions\n- **Systematic deviations**: Clusters above or below the line suggest the model over- or under-predicts for certain price ranges\n- **Spread**: Wider scatter around the line means larger prediction errors\n\n### Visualization: Residual Plot\n\nA **residual plot** (residuals vs. fitted values) helps diagnose model problems:\n\n- **Random scatter around zero:** Good (model assumptions satisfied)\n- **Patterns (curves, funnels):** Bad (model misspecification or heteroskedasticity)\n- **Outliers:** Investigate unusual observations\n\n::: {#86856c76 .cell execution_count=15}\n``` {.python .cell-code}\n# Create residual plot\nfig, ax = plt.subplots(figsize=(10, 6))\nax.scatter(model_full.fittedvalues, model_full.resid, alpha=0.6, s=50, color='#22d3ee')  # alpha = transparency, s = marker size\nax.axhline(y=0, color='red', linestyle='--', linewidth=2, label='Zero residual line')\nax.set_xlabel('Fitted values ($1000s)', fontsize=12)\nax.set_ylabel('Residuals ($1000s)', fontsize=12)\nax.set_title('Residual Plot: Multiple Regression', fontsize=14, fontweight='bold')\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n\nprint(\"Random scatter around zero suggests model assumptions are reasonable.\")\n```\n\n::: {.cell-output .cell-output-display}\n![](ch10_Data_Summary_for_Multiple_Regression_files/figure-html/cell-16-output-1.png){width=947 height=565}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nRandom scatter around zero suggests model assumptions are reasonable.\n```\n:::\n:::\n\n\n**What to look for in this residual plot:**\n\n- **Random scatter**: Residuals should appear randomly distributed around the zero line (no pattern)\n- **Funnel shape**: A widening or narrowing pattern suggests heteroskedasticity (non-constant error variance)\n- **Outliers**: Points far from the zero line may indicate unusual observations worth investigating\n\n### Visualization: Coefficient Plot with Confidence Intervals\n\nA **coefficient plot** displays estimated coefficients with their 95% confidence intervals. This makes it easy to see:\n\n- Which coefficients are significantly different from zero (CI doesn't include zero)\n- Relative magnitude of effects\n- Precision of estimates (narrow vs. wide CIs)\n\n::: {#1700cdce .cell execution_count=16}\n``` {.python .cell-code}\n# Create coefficient plot with confidence intervals\nfig, ax = plt.subplots(figsize=(10, 8))\n\n# Exclude intercept for better visualization\nparams_no_int = model_full.params[1:]\nci_no_int = conf_int.iloc[1:, :]\n\ny_pos = np.arange(len(params_no_int))\nax.errorbar(params_no_int.values, y_pos,\n            xerr=[params_no_int.values - ci_no_int.iloc[:, 0].values,\n                  ci_no_int.iloc[:, 1].values - params_no_int.values],\n            fmt='o', markersize=8, capsize=5, capthick=2, linewidth=2)\nax.set_yticks(y_pos)\nax.set_yticklabels(params_no_int.index)\nax.axvline(x=0, color='red', linestyle='--', linewidth=1, alpha=0.5, label='Zero effect')\nax.set_xlabel('Coefficient Value', fontsize=12)\nax.set_title('Coefficient Estimates with 95% Confidence Intervals',\n             fontsize=14, fontweight='bold')\nax.legend()\nax.grid(True, alpha=0.3, axis='x')\nplt.tight_layout()\nplt.show()\n\nprint(\"Coefficients whose CI crosses zero are not statistically significant.\")\n```\n\n::: {.cell-output .cell-output-display}\n![](ch10_Data_Summary_for_Multiple_Regression_files/figure-html/cell-17-output-1.png){width=950 height=757}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nCoefficients whose CI crosses zero are not statistically significant.\n```\n:::\n:::\n\n\n**What to look for in this coefficient plot:**\n\n- **Zero crossing**: Coefficients whose error bars cross the red dashed line are not statistically significant at 5%\n- **Relative magnitude**: Size has the largest positive effect; other variables cluster near zero\n- **Precision**: Narrow error bars indicate more precisely estimated coefficients\n\n## Key Takeaways\n\n**Data Exploration and Correlation:**\n\n- Multiple regression extends bivariate regression to include several regressors simultaneously\n- Summary statistics and two-way scatterplots provide initial overview of variable relationships\n- Correlation matrices reveal pairwise associations (e.g., price-size correlation of 0.79)\n- Correlation can be misleading — bedrooms correlate with price, but may simply reflect house size\n\n**OLS Estimation:**\n\n- Multiple regression model: $\\widehat{y} = b_1 + b_2 x_2 + b_3 x_3 + \\cdots + b_k x_k$\n- OLS minimizes the sum of squared residuals: $\\min \\sum (y_i - \\widehat{y}_i)^2$\n- The coefficient $b_j$ can be computed by bivariate regression of $y$ on $\\widetilde{x}_j$ (residualized $x_j$)\n\n**Partial Effects:**\n\n- Each coefficient $b_j$ measures the partial effect: the change in $\\widehat{y}$ when $x_j$ changes by one unit, **holding all other regressors constant**\n- Partial effects differ from total effects (which allow other regressors to vary)\n- OLS measures association, not causation — use careful language (\"associated with\")\n\n**Model Fit:**\n\n- $R^2$ measures the fraction of variation in $y$ explained by all regressors (0 to 1)\n- Adjusted $R^2$ penalizes model complexity: can decrease when adding weak regressors\n- Standard error of regression $s_e$ measures typical prediction error in units of $y$\n- Example: Adding 5 regressors increased $R^2$ from 0.618 to 0.651 but decreased $\\bar{R}^2$ from 0.603 to 0.555\n\n**Information Criteria:**\n\n- AIC, BIC, and HQIC penalize larger models more heavily than adjusted $R^2$\n- Smaller values indicate better models\n- BIC is generally preferred (stronger complexity penalty than AIC)\n\n**Multicollinearity:**\n\n- Perfect collinearity makes some coefficients inestimable (computer shows \"omitted\")\n- VIF detects multicollinearity: VIF > 10 indicates problematic, VIF > 5 moderate concern\n- High multicollinearity inflates standard errors and makes estimates unstable\n\n**Python Libraries and Code:**\n\nThis single code block reproduces the core workflow of Chapter 10. It is self-contained — copy it into an empty notebook and run it to review the complete pipeline from data exploration and correlation analysis through multiple regression estimation, partial effects, model comparison, and multicollinearity diagnostics.\n\n```python\n# =============================================================================\n# CHAPTER 10 CHEAT SHEET: Data Summary for Multiple Regression\n# =============================================================================\n\n# --- Libraries ---\nimport numpy as np                                          # numerical operations\nimport pandas as pd                                         # data loading and manipulation\nimport matplotlib.pyplot as plt                             # creating plots and visualizations\nimport seaborn as sns                                       # statistical visualization (heatmaps, pairplots)\nfrom statsmodels.formula.api import ols                     # OLS regression with R-style formulas\nfrom statsmodels.stats.outliers_influence import variance_inflation_factor  # multicollinearity detection\n\n# =============================================================================\n# STEP 1: Load data and explore\n# =============================================================================\n# pd.read_stata() reads Stata .dta files directly from a URL\nurl = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/AED_HOUSE.DTA\"\ndata_house = pd.read_stata(url)\n\nprint(f\"Dataset: {data_house.shape[0]} observations, {data_house.shape[1]} variables\")\nprint(data_house[['price', 'size', 'bedrooms', 'bathrooms', 'lotsize', 'age']].describe().round(2))\n\n# =============================================================================\n# STEP 2: Partial effects vs. total effects — why controls matter\n# =============================================================================\n# Bivariate regression captures TOTAL effect (direct + indirect through size)\nmodel_bivariate = ols('price ~ bedrooms', data=data_house).fit()\n\n# Multiple regression isolates the PARTIAL effect (holding size constant)\nmodel_partial = ols('price ~ bedrooms + size', data=data_house).fit()\n\nprint(f\"Bedrooms coefficient (bivariate):  ${model_bivariate.params['bedrooms']:,.2f}\")\nprint(f\"Bedrooms coefficient (multiple):   ${model_partial.params['bedrooms']:,.2f}\")\nprint(f\"Change: ${model_partial.params['bedrooms'] - model_bivariate.params['bedrooms']:,.2f}\")\n# The coefficient drops from ~$23,667 to ~$1,553 once we control for size\n\n# =============================================================================\n# STEP 3: Correlation matrix — check pairwise associations before modeling\n# =============================================================================\n# High correlations between regressors signal potential multicollinearity\ncorr_vars = ['price', 'size', 'bedrooms', 'bathrooms', 'lotsize', 'age']\ncorr_matrix = data_house[corr_vars].corr()\n\nfig, ax = plt.subplots(figsize=(10, 8))\nsns.heatmap(corr_matrix, annot=True, fmt='.3f', cmap='coolwarm', center=0,\n            square=True, linewidths=1)\nax.set_title('Correlation Matrix Heatmap')\nplt.tight_layout()\nplt.show()\n\nprint(f\"Price-Size correlation: {corr_matrix.loc['price', 'size']:.3f}\")\nprint(f\"Size-Bedrooms correlation: {corr_matrix.loc['size', 'bedrooms']:.3f}\")\n\n# =============================================================================\n# STEP 4: Full multiple regression — estimate partial effects\n# =============================================================================\n# Each coefficient measures the change in price for a one-unit change in that\n# variable, holding ALL other regressors constant\nmodel_full = ols('price ~ size + bedrooms + bathrooms + lotsize + age + monthsold',\n                 data=data_house).fit()\n\nsize_coef = model_full.params['size']\nprint(f\"Size effect: each additional sq ft is associated with ${size_coef:,.2f} higher price\")\nprint(f\"R-squared: {model_full.rsquared:.4f} ({model_full.rsquared*100:.1f}% of variation explained)\")\nprint(f\"Adjusted R-squared: {model_full.rsquared_adj:.4f}\")\n\n# Full regression table (coefficients, std errors, t-stats, p-values)\nmodel_full.summary()\n\n# =============================================================================\n# STEP 5: FWL theorem — how \"holding constant\" actually works\n# =============================================================================\n# Step A: Regress size on all other regressors, keep residuals\nmodel_size_on_others = ols('size ~ bedrooms + bathrooms + lotsize + age + monthsold',\n                            data=data_house).fit()\nresid_size = model_size_on_others.resid\n\n# Step B: Regress price on those residuals — the slope matches the full model\ndata_house['resid_size'] = resid_size\nmodel_fwl = ols('price ~ resid_size', data=data_house).fit()\n\nprint(f\"Size coef from FULL regression:     {model_full.params['size']:.10f}\")\nprint(f\"Coef from FWL residual regression:  {model_fwl.params['resid_size']:.10f}\")\n# These are identical — the FWL theorem in action\n\n# =============================================================================\n# STEP 6: Model comparison — parsimony vs. complexity\n# =============================================================================\n# Compare simple (size only) vs. full model using fit statistics\nmodel_simple = ols('price ~ size', data=data_house).fit()\n\ncomparison = pd.DataFrame({\n    'Model': ['Size only', 'Full (all variables)'],\n    'R²':     [model_simple.rsquared,     model_full.rsquared],\n    'Adj R²': [model_simple.rsquared_adj, model_full.rsquared_adj],\n    'AIC':    [model_simple.aic,          model_full.aic],\n    'BIC':    [model_simple.bic,          model_full.bic],\n})\nprint(comparison.to_string(index=False))\n# Adj R² DECREASES when adding 5 weak predictors — parsimony wins\n\n# =============================================================================\n# STEP 7: VIF — detect multicollinearity\n# =============================================================================\n# VIF_j = 1 / (1 - R²_j), where R²_j is from regressing x_j on all other x's\n# VIF > 5: moderate concern; VIF > 10: severe multicollinearity\nX = data_house[['size', 'bedrooms', 'bathrooms', 'lotsize', 'age', 'monthsold']]\nvif_data = pd.DataFrame({\n    'Variable': X.columns,\n    'VIF': [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]\n})\nprint(vif_data.to_string(index=False))\n\n# =============================================================================\n# STEP 8: Diagnostics — actual vs. predicted and residual plots\n# =============================================================================\n# Good fit: points hug the 45° line; residuals scatter randomly around zero\nfig, axes = plt.subplots(1, 2, figsize=(14, 6))\n\n# Actual vs. predicted\naxes[0].scatter(data_house['price'], model_full.fittedvalues, alpha=0.7, s=50)\naxes[0].plot([data_house['price'].min(), data_house['price'].max()],\n             [data_house['price'].min(), data_house['price'].max()],\n             'r--', linewidth=2, label='Perfect prediction (45° line)')\naxes[0].set_xlabel('Actual Price ($)')\naxes[0].set_ylabel('Predicted Price ($)')\naxes[0].set_title('Actual vs Predicted')\naxes[0].legend()\naxes[0].grid(True, alpha=0.3)\n\n# Residual plot\naxes[1].scatter(model_full.fittedvalues, model_full.resid, alpha=0.7, s=50)\naxes[1].axhline(y=0, color='red', linestyle='--', linewidth=2)\naxes[1].set_xlabel('Fitted Values ($)')\naxes[1].set_ylabel('Residuals ($)')\naxes[1].set_title('Residual Plot')\naxes[1].grid(True, alpha=0.3)\n\nplt.tight_layout()\nplt.show()\n```\n\n**Try it yourself!** Copy this code into an empty Google Colab notebook and run it: [Open Colab](https://colab.research.google.com/notebooks/empty.ipynb)\n\n**Python tools used:** `statsmodels` (OLS, VIF), `seaborn` (pairplot, heatmap), `pandas` (DataFrames), `matplotlib` (coefficient plots, diagnostics)\n\n**Next steps:** Chapter 11 covers **statistical inference** for multiple regression — hypothesis tests, confidence intervals, and overall F-tests for model significance.\n\nCongratulations on completing Chapter 10! You now have the tools to estimate and evaluate multiple regression models, a foundation for the rest of the course.\n\n> **Common Mistakes to Avoid**\n>\n> - **Omitting relevant variables**: Leads to omitted variable bias in the remaining coefficients\n> - **Including too many variables**: Can cause multicollinearity and inflate standard errors\n> - **Ignoring high VIF values**: VIF > 10 suggests problematic multicollinearity\n\n## Practice Exercises\n\nTest your understanding of multiple regression concepts with these exercises.\n\n---\n\n**Exercise 1: Residuals and Fitted Values**\n\nA regression leads to the fitted equation $\\widehat{y} = 2 + 3x_2 + 4x_3$.\n\na) What is the predicted value for observation $(x_2, x_3) = (2, 1)$?\n\nb) If the actual value is $y = 9$, what is the residual?\n\nc) Is this observation over-predicted or under-predicted?\n\n---\n\n**Exercise 2: Partial vs. Total Effects**\n\nSuppose OLS regression on the same dataset leads to:\n\n- Bivariate: $\\widehat{y} = 6 + 5x_2$\n- Multiple: $\\widehat{y} = 2 + 3x_2 + 4x_3$\n\na) Why does the coefficient on $x_2$ change from 5 to 3?\n\nb) Which coefficient (5 or 3) represents the partial effect of $x_2$? Explain.\n\nc) Under what condition would the bivariate and multiple regression coefficients on $x_2$ be equal?\n\n---\n\n**Exercise 3: R-squared and Adjusted R-squared**\n\nOLS regression of $y$ on $x$ for a sample of size $n = 53$ leads to Residual SS = 20 and Total SS = 50.\n\na) Compute $R^2$.\n\nb) Compute the standard error of the regression $s_e$.\n\nc) Compute the correlation between $y$ and $\\widehat{y}$.\n\nd) If we add 3 more regressors and the Residual SS drops to 18, compute the new $R^2$ and adjusted $R^2$. Does the model improve?\n\n---\n\n**Exercise 4: Information Criteria**\n\nConsider two models estimated on $n = 29$ observations:\n\n- Model A (2 parameters): AIC = 668.1, BIC = 670.8\n- Model B (7 parameters): AIC = 675.5, BIC = 685.1\n\na) Which model is preferred by AIC? By BIC?\n\nb) Why does BIC penalize Model B more heavily than AIC?\n\nc) What economic reasoning supports the simpler model in this case?\n\n---\n\n**Exercise 5: Multicollinearity Detection**\n\nA multiple regression of house prices yields the following VIF values:\n\n| Variable | VIF |\n|----------|-----|\n| Size | 40.1 |\n| Bedrooms | 57.8 |\n| Bathrooms | 34.7 |\n| Age | 21.0 |\n\na) Which variables show the most severe multicollinearity?\n\nb) What consequences does high VIF have for coefficient estimates and inference?\n\nc) Suggest a strategy to reduce multicollinearity in this model.\n\n---\n\n**Exercise 6: Model Building**\n\nYou have data on employee wages with variables: education (years), experience (years), age, tenure (years at current firm), and gender.\n\na) Why might including both age and experience create multicollinearity?\n\nb) Propose two alternative model specifications and explain the trade-offs.\n\nc) How would you use adjusted $R^2$ and BIC to select the preferred specification?\n\n## Case Studies\n\n### Case Study 1: Multiple Regression for Cross-Country Productivity\n\nIn this case study, you will apply multiple regression techniques to investigate how human capital and physical capital jointly explain cross-country differences in labor productivity. Using data from 108 countries over 1990-2014, you will explore correlations, estimate multiple regression models, interpret partial effects, and compare model specifications.\n\n**Dataset:** Mendez Convergence Clubs Data\n\n- **Source:** Mendez (2020), 108 countries, 1990-2014\n- **Key variables:**\n  - `lp` — Labor productivity (GDP per worker)\n  - `rk` — Physical capital per worker\n  - `hc` — Human capital index\n  - `rgdppc` — Real GDP per capita\n  - `region` — Geographic region\n\n**Research question:** How do human capital and physical capital jointly explain cross-country productivity differences?\n\n```python\n# Load the Mendez convergence clubs dataset\nurl = \"https://raw.githubusercontent.com/quarcs-lab/mendez2020-convergence-clubs-code-data/master/assets/dat.csv\"\ndat = pd.read_csv(url)\ndat_2014 = dat[dat['year'] == 2014].dropna(subset=['lp', 'rk', 'hc']).copy()\nprint(f\"Cross-section sample: {len(dat_2014)} countries (year 2014)\")\ndat_2014.head()\n```\n\n#### Task 1: Explore Productivity Data (Guided)\n\nExplore the cross-country productivity dataset.\n\n```python\n# Step 1: Create log-transformed variables\ndat_2014['ln_lp'] = np.log(dat_2014['lp'])\ndat_2014['ln_rk'] = np.log(dat_2014['rk'])\n\n# Step 2: Summary statistics for key variables\nprint(dat_2014[['lp', 'rk', 'hc', 'ln_lp', 'ln_rk']].describe())\n\n# Step 3: Create a scatterplot matrix\nsns.pairplot(dat_2014[['ln_lp', 'ln_rk', 'hc']], diag_kind='kde')\nplt.suptitle('Scatterplot Matrix: Productivity Variables', y=1.02)\nplt.show()\n```\n\n**Questions:**\n\n- Which variable shows the strongest visual association with $\\ln(\\text{lp})$?\n- Do you see any nonlinear patterns or outliers?\n\n#### Task 2: Correlation Analysis (Guided)\n\nCompute and visualize the correlation matrix.\n\n```python\n# Step 1: Compute correlation matrix\ncorr = dat_2014[['ln_lp', 'ln_rk', 'hc']].corr()\nprint(corr)\n\n# Step 2: Visualize as heatmap\nsns.heatmap(corr, annot=True, fmt='.3f', cmap='coolwarm', center=0, square=True)\nplt.title('Correlation Matrix: Productivity Variables')\nplt.show()\n```\n\n**Questions:**\n\n- Which predictor is most strongly correlated with $\\ln(\\text{lp})$?\n- Are $\\ln(\\text{rk})$ and hc correlated with each other? What implications does this have for multiple regression?\n\n> **Key Concept 10.9: Functional Form and Cross-Country Comparisons**\n>\n> When comparing countries with vastly different income levels, logarithmic transformations are essential. Using $\\ln(\\text{lp})$ and $\\ln(\\text{rk})$ compresses the scale so that both Luxembourg and Malawi can be meaningfully compared. Coefficients on log-transformed variables have elasticity interpretations, while coefficients on level variables (like hc) represent semi-elasticities.\n\n#### Task 3: Multiple Regression Estimation (Semi-guided)\n\nEstimate bivariate and multiple regression models for labor productivity.\n\n```python\n# Model 1: ln(lp) ~ ln(rk) only\nmodel1 = ols('ln_lp ~ ln_rk', data=dat_2014).fit()\nprint(model1.summary())\n\n# Model 2: ln(lp) ~ hc only\nmodel2 = ols('ln_lp ~ hc', data=dat_2014).fit()\nprint(model2.summary())\n\n# Model 3: ln(lp) ~ ln(rk) + hc (multiple regression)\nmodel3 = ols('ln_lp ~ ln_rk + hc', data=dat_2014).fit()\nprint(model3.summary())\n```\n\n**Questions:**\n\n- How do the coefficients on $\\ln(\\text{rk})$ change between Model 1 and Model 3?\n- Does adding human capital improve the model? Compare $R^2$ and adjusted $R^2$.\n\n#### Task 4: Interpret Partial Effects (Semi-guided)\n\nInterpret the coefficients from the multiple regression model.\n\n```python\n# Display coefficients with confidence intervals\nprint(\"Model 3 Coefficients:\")\nprint(model3.params)\nprint(\"\\n95% Confidence Intervals:\")\nprint(model3.conf_int())\n```\n\n**Questions:**\n\n- Interpret the coefficient on $\\ln(\\text{rk})$ in Model 3. What does it mean in economic terms?\n- Interpret the coefficient on hc. How does a one-unit increase in human capital relate to productivity?\n- Are both coefficients statistically significant? How do you know?\n\n#### Task 5: Model Selection (Independent)\n\nCompare models using fit statistics and information criteria.\n\n**Your tasks:**\n\n1. Create a comparison table with $R^2$, adjusted $R^2$, AIC, and BIC for all three models\n2. Which model is preferred by adjusted $R^2$? By AIC? By BIC?\n3. Does the parsimony principle favor one model over another?\n4. Calculate VIF for Model 3 — is multicollinearity a concern?\n\n*Hint: Use `model.rsquared`, `model.rsquared_adj`, `model.aic`, `model.bic` and `variance_inflation_factor()` from statsmodels.*\n\n#### Task 6: Development Policy Brief (Independent)\n\nWrite a 200-300 word policy brief summarizing your findings.\n\n**Your brief should address:**\n\n1. What are the key determinants of cross-country labor productivity?\n2. What is the relative importance of physical capital vs. human capital?\n3. How do partial effects differ from bivariate associations?\n4. What policy implications follow from your analysis?\n5. What limitations should policymakers keep in mind (association vs. causation)?\n\n> **Key Concept 10.10: Multiple Regression in Development Economics**\n>\n> Cross-country productivity regressions are central to development economics. By controlling for both physical capital ($\\ln(\\text{rk})$) and human capital (hc), we can assess each factor's **partial contribution** to productivity. This addresses a key policy question: should developing countries invest in machines or education? Multiple regression helps disentangle these effects, though causal claims require careful identification strategies.\n\n### What You've Learned\n\nIn this case study, you applied the full multiple regression toolkit to cross-country productivity data:\n\n- Explored data with scatterplot matrices and correlation analysis\n- Estimated bivariate and multiple regression models, observing how coefficients change\n- Interpreted partial effects of physical and human capital on productivity\n- Compared model specifications using adjusted $R^2$, AIC, and BIC\n- Connected statistical findings to development policy questions\n\nThese skills form the foundation for more advanced empirical analysis in the chapters ahead.\n\n### Case Study 2: Multiple Satellite Predictors of Development\n\n**Research Question**: Do satellite image embeddings improve our ability to predict municipal development beyond nighttime lights alone?\n\nIn Chapter 1, we introduced the DS4Bolivia project and estimated a bivariate regression of development on nighttime lights. Now we extend this analysis using Chapter 10's **multiple regression** tools, adding satellite image embeddings as additional predictors to test whether they improve our ability to predict municipal development.\n\n**Background**: Nighttime lights (NTL) are a well-established proxy for economic activity, but they capture only one dimension of a municipality's characteristics — nocturnal luminosity. Daytime satellite imagery contains far richer information: building density, road networks, agricultural patterns, vegetation cover. Deep learning models can extract this information as **64-dimensional embedding vectors**, where each dimension captures abstract visual patterns learned automatically from the data.\n\n**The key question for multiple regression**: Does adding these satellite embeddings as extra regressors significantly improve explanatory power compared to NTL alone? And if so, which embeddings matter most?\n\n**Variables for this case study:**\n\n- `imds` — Municipal Sustainable Development Index (0-100, outcome variable)\n- `ln_NTLpc2017` — Log nighttime lights per capita (established predictor from Chapter 1)\n- `A00`, `A10`, `A20`, `A30`, `A40` — Selected satellite image embedding dimensions (new predictors)\n- `mun`, `dep` — Municipality and department identifiers\n\n**Your Task**: Use correlation analysis, multiple regression, the FWL theorem, and model comparison tools from Chapter 10 to evaluate whether satellite embeddings add predictive value beyond nighttime lights.\n\n#### Load the DS4Bolivia Data\n\nLet's load the DS4Bolivia dataset and select the variables needed for our multiple regression analysis. We focus on the development index, nighttime lights, and five selected satellite embedding dimensions.\n\n::: {#0972e454 .cell execution_count=17}\n``` {.python .cell-code}\n# Load the DS4Bolivia dataset\nurl_bol = \"https://raw.githubusercontent.com/quarcs-lab/ds4bolivia/master/ds4bolivia_v20250523.csv\"\nbol = pd.read_csv(url_bol)\n\n# Load and merge satellite image embeddings\nurl_sat = \"https://raw.githubusercontent.com/quarcs-lab/ds4bolivia/master/satelliteEmbeddings/satelliteEmbeddings2017.csv\"\nsat = pd.read_csv(url_sat)\nbol = bol.merge(sat[['asdf_id', 'A00', 'A10', 'A20', 'A30', 'A40']], on='asdf_id', how='left')\n\n# Select key variables for this case study\nkey_vars = ['mun', 'dep', 'imds', 'ln_NTLpc2017', 'A00', 'A10', 'A20', 'A30', 'A40']\nbol_sat = bol[key_vars].copy()\n\n# DS4BOLIVIA DATASET — SATELLITE PREDICTORS\nprint(f\"Dataset shape: {bol_sat.shape[0]} municipalities, {bol_sat.shape[1]} variables\")\nprint(f\"Departments: {bol['dep'].nunique()} unique departments\")\nprint(f\"Complete cases: {bol_sat.dropna().shape[0]}\")\n# FIRST 10 MUNICIPALITIES\nbol_sat.head(10).to_string(index=False)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDataset shape: 339 municipalities, 9 variables\nDepartments: 9 unique departments\nComplete cases: 333\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=17}\n```\n'            mun        dep      imds  ln_NTLpc2017       A00      A10      A20       A30       A40\\n      Esmeralda      Oruro 53.200001     13.647187 -0.060433 0.276589 0.132779 -0.021201  0.027739\\n      Quillacas      Oruro 50.500000     13.821883 -0.104140 0.210359 0.143159  0.013397  0.006337\\n Pampa Aullagas      Oruro 47.299999     13.406137 -0.107063 0.187294 0.159752 -0.035909  0.050702\\n      Llallagua     Potosí 58.099998     14.827301 -0.130482 0.200049 0.126726  0.074560 -0.078046\\n       Caripuyo     Potosí 43.500000     12.510039 -0.123298 0.201647 0.120984  0.068288 -0.076545\\n        Aiquile Cochabamba 50.400002     14.606511  0.011109 0.038179 0.079780 -0.025559 -0.138114\\nVilla de Sacaca     Potosí 42.200001     12.586779 -0.145689 0.140690 0.134057  0.084465 -0.090000\\n         Acasio     Potosí 42.099998     12.358384 -0.098959 0.108831 0.094674  0.068063 -0.096150\\n        Huanuni      Oruro 56.799999     14.774255 -0.141211 0.218252 0.110193  0.050727 -0.039102\\n    Huachacalla      Oruro 61.299999     15.581995 -0.139633 0.223694 0.132744  0.037684 -0.062146'\n```\n:::\n:::\n\n\n#### Task 1: Explore Variables (Guided)\n\n**Objective**: Understand the satellite embedding variables and how they compare to nighttime lights.\n\n**Instructions**:\n\n1. Generate summary statistics for all predictor variables using `describe()`\n2. Compare the scale and distribution of NTL vs. embedding variables\n3. Check for missing values across all selected variables\n4. Consider: What are satellite embeddings? How do they differ from NTL?\n\n**Key insight**: Unlike NTL (which has a clear physical interpretation — light intensity), embedding dimensions are **abstract features** extracted by neural networks. Dimension `A00` doesn't mean \"vegetation\" or \"roads\" — it captures a learned combination of visual patterns.\n\n::: {#c462439c .cell execution_count=18}\n``` {.python .cell-code}\n# Your code here: Explore the satellite predictor variables\n#\n# Step 1: Summary statistics for all numeric variables\n# DESCRIPTIVE STATISTICS: DEVELOPMENT AND SATELLITE PREDICTORS\nbol_sat[['imds', 'ln_NTLpc2017', 'A00', 'A10', 'A20', 'A30', 'A40']].describe().round(3)\n\n# Step 2: Check for missing values\n# MISSING VALUES\nprint(bol_sat.isnull().sum())\n\n# Step 3: Compare variable ranges\n# VARIABLE RANGES\nfor var in ['imds', 'ln_NTLpc2017', 'A00', 'A10', 'A20', 'A30', 'A40']:\n    col = bol_sat[var].dropna()\n    print(f\"  {var:16s}  range: [{col.min():.3f}, {col.max():.3f}]  std: {col.std():.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmun             0\ndep             0\nimds            0\nln_NTLpc2017    6\nA00             0\nA10             0\nA20             0\nA30             0\nA40             0\ndtype: int64\n  imds              range: [35.700, 80.200]  std: 6.772\n  ln_NTLpc2017      range: [9.064, 17.064]  std: 1.181\n  A00               range: [-0.165, 0.164]  std: 0.082\n  A10               range: [-0.096, 0.277]  std: 0.093\n  A20               range: [-0.057, 0.193]  std: 0.046\n  A30               range: [-0.169, 0.206]  std: 0.063\n  A40               range: [-0.205, 0.058]  std: 0.059\n```\n:::\n:::\n\n\n#### Task 2: Correlation Analysis (Guided)\n\n**Objective**: Compute and visualize the correlation structure among all predictors and the outcome variable.\n\n**Instructions**:\n\n1. Compute the correlation matrix for `imds`, `ln_NTLpc2017`, and all five embedding variables\n2. Display the correlation matrix as a heatmap\n3. Identify: Which embeddings correlate most strongly with `imds`?\n4. Identify: Do the embeddings correlate with each other (potential multicollinearity)?\n5. Do the embeddings correlate with NTL, or do they capture different information?\n\n**Apply what you learned in section 10.3**: Use `seaborn.heatmap()` with annotated correlation values.\n\n::: {#7c67abed .cell execution_count=19}\n``` {.python .cell-code}\n# Your code here: Correlation analysis of satellite predictors\n#\n# Step 1: Compute correlation matrix\ncorr_vars = ['imds', 'ln_NTLpc2017', 'A00', 'A10', 'A20', 'A30', 'A40']\ncorr_sat = bol_sat[corr_vars].dropna().corr()\n\n# CORRELATION MATRIX: DEVELOPMENT AND SATELLITE PREDICTORS\ncorr_sat.round(3)\n\n# Step 2: Visualize as heatmap\nfig, ax = plt.subplots(figsize=(10, 8))\nsns.heatmap(corr_sat, annot=True, fmt='.3f', cmap='coolwarm', center=0,\n            square=True, linewidths=1, cbar_kws={\"shrink\": 0.8})\nax.set_title('Correlation Matrix: IMDS, NTL, and Satellite Embeddings',\n             fontsize=14, fontweight='bold')\nplt.tight_layout()\nplt.show()\n\n# Step 3: Highlight strongest correlations with IMDS\n# Correlations with IMDS\nimds_corr = corr_sat['imds'].drop('imds').sort_values(key=abs, ascending=False)\nfor var, r in imds_corr.items():\n    print(f\"  {var:16s}  r = {r:+.3f}\")\n```\n\n::: {.cell-output .cell-output-display}\n![](ch10_Data_Summary_for_Multiple_Regression_files/figure-html/cell-20-output-1.png){width=853 height=758}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n  ln_NTLpc2017      r = +0.589\n  A30               r = -0.360\n  A00               r = +0.221\n  A10               r = -0.195\n  A20               r = -0.102\n  A40               r = -0.077\n```\n:::\n:::\n\n\n> **Key Concept 10.12: High-Dimensional Satellite Features**\n>\n> Satellite embeddings are **64 abstract features** extracted by deep learning models (convolutional neural networks) from daytime satellite imagery. Unlike handcrafted variables (e.g., NDVI for vegetation), each embedding dimension captures complex visual patterns — road density, building structures, agricultural layouts — learned automatically from the data. These features are not directly interpretable (dimension A00 doesn't have a specific meaning), but they collectively encode rich information about a municipality's physical landscape.\n\n#### Task 3: Multiple Regression (Semi-guided)\n\n**Objective**: Estimate a multiple regression model with NTL and satellite embeddings as predictors.\n\n**Instructions**:\n\n1. Estimate the full model: `imds ~ ln_NTLpc2017 + A00 + A10 + A20 + A30 + A40`\n2. Display the regression summary\n3. Compare $R^2$ with the bivariate NTL-only model from Chapter 1\n4. Interpret: How much does adding embeddings improve explanatory power?\n5. Which embedding coefficients are statistically significant?\n\n**Apply what you learned in section 10.4**: Use `ols()` from statsmodels and interpret partial effects.\n\n::: {#e367e227 .cell execution_count=20}\n``` {.python .cell-code}\n# Your code here: Multiple regression with satellite predictors\n#\n# Step 1: Prepare data (drop missing values)\nreg_data = bol_sat[['imds', 'ln_NTLpc2017', 'A00', 'A10', 'A20', 'A30', 'A40']].dropna()\nprint(f\"Regression sample: {len(reg_data)} municipalities (complete cases)\")\n\n# Step 2: Bivariate model (NTL only — baseline from Chapter 1)\nmodel_ntl = ols('imds ~ ln_NTLpc2017', data=reg_data).fit()\n# MODEL 1: BIVARIATE — imds ~ ln_NTLpc2017\nmodel_ntl.summary()\n\n# Step 3: Multiple regression (NTL + all 5 embeddings)\nmodel_full_sat = ols('imds ~ ln_NTLpc2017 + A00 + A10 + A20 + A30 + A40',\n                     data=reg_data).fit()\n# MODEL 2: MULTIPLE — imds ~ ln_NTLpc2017 + A00 + A10 + A20 + A30 + A40\nmodel_full_sat.summary()\n\n# Step 4: Compare R-squared\n# R-SQUARED COMPARISON\nprint(f\"NTL only:           R² = {model_ntl.rsquared:.4f}\")\nprint(f\"NTL + 5 embeddings: R² = {model_full_sat.rsquared:.4f}\")\nprint(f\"Improvement:        ΔR² = {model_full_sat.rsquared - model_ntl.rsquared:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRegression sample: 333 municipalities (complete cases)\nNTL only:           R² = 0.3466\nNTL + 5 embeddings: R² = 0.4316\nImprovement:        ΔR² = 0.0851\n```\n:::\n:::\n\n\n#### Task 4: Partial Effects via FWL (Semi-guided)\n\n**Objective**: Demonstrate the Frisch-Waugh-Lovell theorem by showing that the NTL coefficient in the multiple regression equals the coefficient from regressing residualized IMDS on residualized NTL.\n\n**Instructions**:\n\n1. Regress `imds` on all embedding variables (`A00`, `A10`, `A20`, `A30`, `A40`), save residuals $e_y$\n2. Regress `ln_NTLpc2017` on all embedding variables, save residuals $e_x$\n3. Regress $e_y$ on $e_x$ (bivariate regression of residuals)\n4. Verify that the coefficient matches the NTL coefficient from the full multiple regression\n\n**Apply what you learned in section 10.5**: This demonstrates that the partial effect of NTL is computed from the variation in NTL that is *independent* of the satellite embeddings.\n\n::: {#23e135c5 .cell execution_count=21}\n``` {.python .cell-code}\n# Your code here: FWL theorem demonstration\n#\n# Step 1: Regress imds on embeddings only, save residuals e_y\nmodel_y_on_emb = ols('imds ~ A00 + A10 + A20 + A30 + A40', data=reg_data).fit()\ne_y = model_y_on_emb.resid\n\n# Step 2: Regress ln_NTLpc2017 on embeddings only, save residuals e_x\nmodel_x_on_emb = ols('ln_NTLpc2017 ~ A00 + A10 + A20 + A30 + A40', data=reg_data).fit()\ne_x = model_x_on_emb.resid\n\n# Step 3: Regress e_y on e_x\nfwl_data = pd.DataFrame({'e_y': e_y, 'e_x': e_x})\nmodel_fwl = ols('e_y ~ e_x', data=fwl_data).fit()\n\n# Step 4: Compare coefficients\n# FWL THEOREM DEMONSTRATION\nprint(f\"NTL coefficient from FULL multiple regression:  {model_full_sat.params['ln_NTLpc2017']:.10f}\")\nprint(f\"Coefficient from FWL residual regression:       {model_fwl.params['e_x']:.10f}\")\nprint(f\"Difference (numerical precision):                {abs(model_full_sat.params['ln_NTLpc2017'] - model_fwl.params['e_x']):.15f}\")\n# The coefficients are identical — confirming the FWL theorem\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNTL coefficient from FULL multiple regression:  3.4402848933\nCoefficient from FWL residual regression:       3.4402848933\nDifference (numerical precision):                0.000000000000002\n```\n:::\n:::\n\n\n#### Task 5: Model Comparison (Independent)\n\n**Objective**: Compare multiple model specifications using fit statistics and information criteria.\n\n**Your tasks**:\n\n1. Estimate three models:\n   - **Model 1**: `imds ~ ln_NTLpc2017` (NTL only)\n   - **Model 2**: `imds ~ ln_NTLpc2017 + A00 + A10` (NTL + 2 embeddings)\n   - **Model 3**: `imds ~ ln_NTLpc2017 + A00 + A10 + A20 + A30 + A40` (NTL + 5 embeddings)\n\n2. Create a comparison table reporting $R^2$, adjusted $R^2$, AIC, and BIC for each model\n3. Use `model.rsquared`, `model.rsquared_adj`, `model.aic`, `model.bic`\n4. Which model is \"best\" by each criterion?\n5. Does the parsimony principle favor fewer or more embedding variables?\n\n*Hint: Use `pd.DataFrame()` to create a clean comparison table.*\n\n::: {#64647d5e .cell execution_count=22}\n``` {.python .cell-code}\n# Your code here: Model comparison\n#\n# Step 1: Estimate three models\n# model_1 = ols('imds ~ ln_NTLpc2017', data=reg_data).fit()\n# model_2 = ols('imds ~ ln_NTLpc2017 + A00 + A10', data=reg_data).fit()\n# model_3 = ols('imds ~ ln_NTLpc2017 + A00 + A10 + A20 + A30 + A40', data=reg_data).fit()\n#\n# Step 2: Create comparison table\n# comparison = pd.DataFrame({\n#     'Model': ['NTL only', 'NTL + 2 embeddings', 'NTL + 5 embeddings'],\n#     'R²': [model_1.rsquared, model_2.rsquared, model_3.rsquared],\n#     'Adj R²': [model_1.rsquared_adj, model_2.rsquared_adj, model_3.rsquared_adj],\n#     'AIC': [model_1.aic, model_2.aic, model_3.aic],\n#     'BIC': [model_1.bic, model_2.bic, model_3.bic],\n#     'N': [len(reg_data)] * 3\n# })\n# print(comparison.to_string(index=False))\n#\n# Step 3: Interpret — which model is preferred by each criterion?\n```\n:::\n\n\n> **Key Concept 10.13: Incremental Predictive Power**\n>\n> When adding predictors to a regression model, $R^2$ can only increase or stay the same — it never decreases. This makes $R^2$ misleading for model comparison when models have different numbers of predictors. **Adjusted $R^2$** penalizes for additional variables, while **AIC** and **BIC** balance fit against complexity. In the satellite prediction context, adding all 64 embeddings would maximize $R^2$ but might overfit; information criteria help identify the most parsimonious model.\n\n#### Task 6: Policy Brief on Satellite Prediction (Independent)\n\n**Objective**: Write a 200-300 word policy brief summarizing the value of satellite embeddings for development prediction.\n\n**Your brief should address:**\n\n1. **Improvement**: How much does adding satellite embeddings improve development prediction compared to NTL alone?\n2. **Complexity trade-off**: Is the improvement worth the added model complexity? What do adjusted $R^2$, AIC, and BIC suggest?\n3. **Partial effects**: After controlling for embeddings, does NTL remain a significant predictor? What does the FWL theorem reveal about NTL's independent contribution?\n4. **SDG monitoring implications**: How could multi-source satellite data enhance SDG monitoring in data-scarce countries like Bolivia?\n5. **Limitations**: What can satellite data *not* capture about development? What are the risks of relying on abstract embedding features for policy decisions?\n\n**Connection to Research**: The DS4Bolivia project uses all 64 embedding dimensions plus machine learning methods (Random Forest, XGBoost) to predict SDG indicators, achieving meaningful predictive accuracy. Your multiple regression analysis provides a transparent, interpretable baseline for comparison.\n\n::: {#6b438bb9 .cell execution_count=23}\n``` {.python .cell-code}\n# Your code here: Additional analysis for the policy brief\n#\n# You might want to:\n# 1. Create a summary table of key results across models\n# 2. Generate a visualization comparing model fit\n# 3. Calculate the percentage improvement in R² from adding embeddings\n# 4. Discuss which embeddings contribute most to prediction\n#\n# Example:\n# print(\"KEY RESULTS FOR POLICY BRIEF\")\n# print(f\"NTL-only R²:          {model_1.rsquared:.4f}\")\n# print(f\"NTL + 5 embed R²:     {model_3.rsquared:.4f}\")\n# print(f\"R² improvement:       {(model_3.rsquared - model_1.rsquared) / model_1.rsquared * 100:.1f}%\")\n# print(f\"NTL coef (bivariate): {model_1.params['ln_NTLpc2017']:.4f}\")\n# print(f\"NTL coef (multiple):  {model_3.params['ln_NTLpc2017']:.4f}\")\n```\n:::\n\n\n#### What You've Learned from This Case Study\n\nThrough this analysis of multiple satellite predictors of Bolivian municipal development, you've applied the full Chapter 10 toolkit to a cutting-edge research application:\n\n- **Correlation analysis**: Explored the correlation structure among NTL, satellite embeddings, and development outcomes\n- **Multiple regression**: Estimated models with multiple satellite predictors and interpreted partial effects\n- **FWL theorem**: Demonstrated that the partial effect of NTL equals the coefficient from regressing residualized IMDS on residualized NTL\n- **Model comparison**: Evaluated competing specifications using $R^2$, adjusted $R^2$, AIC, and BIC\n- **Critical assessment**: Weighed the predictive gains from additional satellite features against model complexity\n\n**Connection to upcoming chapters**: In Chapter 11, we'll test whether the satellite embeddings are *statistically* significant using F-tests for joint significance. In Chapter 12, we'll address robust inference and prediction intervals.\n\n**This dataset returns throughout the textbook**: Each subsequent chapter applies its specific econometric tools to the DS4Bolivia data, building progressively toward a comprehensive satellite-based development prediction framework.\n\n---\n\n**Well done!** You've now analyzed how multiple satellite data sources can predict development outcomes, moving from simple bivariate regression (Chapter 1) to the richer multiple regression framework of Chapter 10.\n\n",
    "supporting": [
      "ch10_Data_Summary_for_Multiple_Regression_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}