{
  "hash": "911cf96c7d7edb795db11f1c93e08987",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 8. Case Studies for Bivariate Regression\nexecute:\n  enabled: true\n  warning: false\n---\n\n\n**metricsAI: An Introduction to Econometrics with Python and AI in the Cloud**\n\n*[Carlos Mendez](https://carlos-mendez.org)*\n\n<img src=\"https://raw.githubusercontent.com/quarcs-lab/metricsai/main/images/ch08_visual_summary.jpg\" alt=\"Chapter 08 Visual Summary\" width=\"100%\">\n\nThis notebook provides an interactive introduction to bivariate regression through real-world case studies. All code runs directly in Google Colab without any local setup.\n\n[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/quarcs-lab/metricsai/blob/main/notebooks_colab/ch08_Case_Studies_for_Bivariate_Regression.ipynb)\n<div class=\"chapter-resources\">\n<a href=\"https://www.youtube.com/watch?v=2hVGYcT9YE8\" target=\"_blank\" class=\"resource-btn\">🎬 AI Video</a>\n<a href=\"https://carlos-mendez.my.canva.site/s08-case-studies-for-bivariate-regression-pdf\" target=\"_blank\" class=\"resource-btn\">✨ AI Slides</a>\n<a href=\"https://cameron.econ.ucdavis.edu/aed/traedv1_08\" target=\"_blank\" class=\"resource-btn\">📊 Cameron Slides</a>\n<a href=\"https://app.edcafe.ai/quizzes/697867452f5d08069e049d1f\" target=\"_blank\" class=\"resource-btn\">✏️ Quiz</a>\n<a href=\"https://app.edcafe.ai/chatbots/6978a02d2f5d08069e0711d6\" target=\"_blank\" class=\"resource-btn\">🤖 AI Tutor</a>\n</div>\n\n\n## Chapter Overview\n\nThis chapter demonstrates bivariate regression analysis through four compelling real-world applications. You'll gain both theoretical understanding and practical skills through hands-on Python examples.\n\n**Design Note:** This chapter uses an integrated case study structure where sections 8.1-8.4 ARE the case studies (health economics, finance, macroeconomics). Unlike other chapters that have regular content sections plus a separate \"Case Studies\" section, CH08's entire focus is on applying regression to diverse real-world problems. This intentional structure maximizes hands-on experience with economic applications.\n\n**What you'll learn:**\n\n- Apply bivariate regression to cross-sectional data (health outcomes, expenditures)\n- Estimate financial models (Capital Asset Pricing Model)\n- Analyze macroeconomic relationships (Okun's Law)\n- Use heteroskedasticity-robust standard errors\n- Interpret economic and statistical significance\n- Identify outliers and assess their influence\n\n**Datasets used:**\n\n- **AED_HEALTH2009.DTA**: Health outcomes and expenditures for 34 OECD countries (2009)\n- **AED_CAPM.DTA**: Monthly stock returns for Coca-Cola, Target, Walmart (1983-2013)\n- **AED_GDPUNEMPLOY.DTA**: Annual U.S. GDP growth and unemployment (1961-2019)\n\n**Key economic questions:**\n\n- Do higher health expenditures improve health outcomes?\n- How does GDP relate to health spending across countries?\n- What is the systematic risk (beta) of individual stocks?\n- Does Okun's Law hold for U.S. macroeconomic data?\n\n**Chapter outline:**\n\n- 8.1 Health Outcomes Across Countries\n- 8.2 Health Expenditures Across Countries\n- 8.3 Capital Asset Pricing Model (CAPM)\n- 8.4 Output and Unemployment (Okun's Law)\n- Key Takeaways\n- Practice Exercises\n\n\n## Setup\n\nFirst, we import the necessary Python packages and configure the environment for reproducibility. All data will stream directly from GitHub.\n\n::: {#ecdcd253 .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Setup: Import libraries and configure environment\"}\n# --- Libraries ---\nimport numpy as np                        # numerical operations\nimport pandas as pd                       # data manipulation\nimport matplotlib.pyplot as plt           # plotting\nimport seaborn as sns                     # statistical visualizations\nimport pyfixest as pf                     # fast estimation with robust SEs\nfrom scipy import stats                   # statistical distributions\nimport random\nimport os\n\n# --- Reproducibility ---\nRANDOM_SEED = 42\nrandom.seed(RANDOM_SEED)\nnp.random.seed(RANDOM_SEED)\nos.environ['PYTHONHASHSEED'] = str(RANDOM_SEED)\n\n# --- Data source ---\nGITHUB_DATA_URL = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/\"\n\n# --- Plotting style (dark theme matching book design) ---\nplt.style.use('dark_background')\nsns.set_style(\"darkgrid\")\nplt.rcParams.update({\n    'axes.facecolor': '#1a2235',\n    'figure.facecolor': '#12162c',\n    'grid.color': '#3a4a6b',\n    'figure.figsize': (10, 6),\n    'text.color': 'white',\n    'axes.labelcolor': 'white',\n    'xtick.color': 'white',\n    'ytick.color': 'white',\n    'axes.edgecolor': '#1a2235',\n})\n\nprint(\"Setup complete! Ready to explore real-world regression applications.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSetup complete! Ready to explore real-world regression applications.\n```\n:::\n:::\n\n\n## 8.1: Health Outcomes Across Countries\n\nOur first case study examines health outcomes across wealthy OECD nations. We'll investigate whether higher health spending is associated with better health outcomes.\n\n**Context:**\n\n- Dataset: 34 OECD countries in 2009\n- Countries include: Australia, Austria, Belgium, Canada, Chile, Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Iceland, Ireland, Israel, Italy, Japan, Korea, Luxembourg, Mexico, Netherlands, New Zealand, Norway, Poland, Portugal, Slovak Republic, Slovenia, Spain, Sweden, Switzerland, Turkey, United Kingdom, and United States\n- Wide variation in health expenditures and outcomes\n\n**Variables:**\n\n- **Hlthpc**: Annual health expenditure per capita (US dollars)\n- **Lifeexp**: Male life expectancy at birth (years)\n- **Infmort**: Infant mortality per 1,000 live births\n\n**Research questions:**\n\n1. Is higher health spending associated with longer life expectancy?\n2. Is higher health spending associated with lower infant mortality?\n3. How does the U.S. compare to predictions from these models?\n\n### Load and Explore Health Data\n\n::: {#f3c09cd8 .cell execution_count=2}\n``` {.python .cell-code}\n# Read in the health data\ndata_health = pd.read_stata(GITHUB_DATA_URL + 'AED_HEALTH2009.DTA')\n\n# 8.1 Health outcomes across countries\ndisplay(data_health.describe())\n\n# First few observations\ndata_health[['code', 'hlthpc', 'lifeexp', 'infmort']].head(10)\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>year</th>\n      <th>hlthgdp</th>\n      <th>hlthpc</th>\n      <th>infmort</th>\n      <th>lifeexp</th>\n      <th>gdppc</th>\n      <th>hlthpcsq</th>\n      <th>lnhlthpc</th>\n      <th>lngdppc</th>\n      <th>lnlifeexp</th>\n      <th>lninfmort</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>34.0</td>\n      <td>34.000000</td>\n      <td>34.000000</td>\n      <td>34.000000</td>\n      <td>34.000000</td>\n      <td>34.000000</td>\n      <td>34.00</td>\n      <td>34.000000</td>\n      <td>34.000000</td>\n      <td>34.000000</td>\n      <td>34.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>2009.0</td>\n      <td>9.673530</td>\n      <td>3255.647059</td>\n      <td>4.447059</td>\n      <td>76.702942</td>\n      <td>33054.035156</td>\n      <td>12764623.00</td>\n      <td>7.973380</td>\n      <td>10.337659</td>\n      <td>4.339207</td>\n      <td>1.377001</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>0.0</td>\n      <td>2.123934</td>\n      <td>1493.654394</td>\n      <td>2.720098</td>\n      <td>2.936756</td>\n      <td>12916.752930</td>\n      <td>11839148.00</td>\n      <td>0.513061</td>\n      <td>0.377425</td>\n      <td>0.039168</td>\n      <td>0.445143</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>2009.0</td>\n      <td>6.400000</td>\n      <td>923.000000</td>\n      <td>1.800000</td>\n      <td>69.800003</td>\n      <td>13806.163086</td>\n      <td>851929.00</td>\n      <td>6.827629</td>\n      <td>9.532870</td>\n      <td>4.245634</td>\n      <td>0.587787</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>2009.0</td>\n      <td>8.100000</td>\n      <td>2090.750000</td>\n      <td>3.100000</td>\n      <td>75.850002</td>\n      <td>25511.000488</td>\n      <td>4373073.25</td>\n      <td>7.645071</td>\n      <td>10.146862</td>\n      <td>4.328757</td>\n      <td>1.131402</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>2009.0</td>\n      <td>9.600000</td>\n      <td>3188.500000</td>\n      <td>3.700000</td>\n      <td>77.649998</td>\n      <td>32899.482422</td>\n      <td>10173338.50</td>\n      <td>8.066971</td>\n      <td>10.401017</td>\n      <td>4.352211</td>\n      <td>1.307967</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>2009.0</td>\n      <td>10.775000</td>\n      <td>4154.750000</td>\n      <td>4.900000</td>\n      <td>78.699997</td>\n      <td>38182.195312</td>\n      <td>17276752.00</td>\n      <td>8.331569</td>\n      <td>10.550111</td>\n      <td>4.365643</td>\n      <td>1.588593</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>2009.0</td>\n      <td>17.700001</td>\n      <td>7990.000000</td>\n      <td>14.700000</td>\n      <td>79.900002</td>\n      <td>82900.882812</td>\n      <td>63840100.00</td>\n      <td>8.985946</td>\n      <td>11.325401</td>\n      <td>4.380776</td>\n      <td>2.687847</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>code</th>\n      <th>hlthpc</th>\n      <th>lifeexp</th>\n      <th>infmort</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>AUS</td>\n      <td>3670</td>\n      <td>79.300003</td>\n      <td>4.3</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>AUT</td>\n      <td>4346</td>\n      <td>77.599998</td>\n      <td>3.8</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>BEL</td>\n      <td>3911</td>\n      <td>77.300003</td>\n      <td>3.4</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>CAN</td>\n      <td>4317</td>\n      <td>78.500000</td>\n      <td>5.0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>CHL</td>\n      <td>1210</td>\n      <td>75.800003</td>\n      <td>7.9</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>CZR</td>\n      <td>2048</td>\n      <td>74.199997</td>\n      <td>2.9</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>DEN</td>\n      <td>4385</td>\n      <td>76.900002</td>\n      <td>3.1</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>EST</td>\n      <td>1385</td>\n      <td>69.800003</td>\n      <td>3.6</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>FIN</td>\n      <td>3271</td>\n      <td>76.599998</td>\n      <td>2.6</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>FRA</td>\n      <td>3930</td>\n      <td>77.699997</td>\n      <td>3.9</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Summary Statistics\n\nLet's examine the key variables in our health outcomes study.\n\n::: {#119f333f .cell execution_count=3}\n``` {.python .cell-code}\n# Table 8.1: Health variables summary\ntable81_vars = ['hlthpc', 'lifeexp', 'infmort']\nsummary_table = data_health[table81_vars].describe().T\nsummary_table['range'] = summary_table['max'] - summary_table['min']\nsummary_table[['mean', 'std', 'min', 'max', 'range']]\n\nprint(\"\\nKey observations:\")\nprint(f\"  - Health spending ranges from ${summary_table.loc['hlthpc', 'min']:.0f} to ${summary_table.loc['hlthpc', 'max']:.0f}\")\nprint(f\"  - Life expectancy ranges from {summary_table.loc['lifeexp', 'min']:.1f} to {summary_table.loc['lifeexp', 'max']:.1f} years\")\nprint(f\"  - Infant mortality ranges from {summary_table.loc['infmort', 'min']:.1f} to {summary_table.loc['infmort', 'max']:.1f} per 1,000 births\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nKey observations:\n  - Health spending ranges from $923 to $7990\n  - Life expectancy ranges from 69.8 to 79.9 years\n  - Infant mortality ranges from 1.8 to 14.7 per 1,000 births\n```\n:::\n:::\n\n\n### Life Expectancy Regression\n\nWe estimate the relationship between health spending and life expectancy:\n\n$$\\text{Lifeexp} = \\beta_1 + \\beta_2 \\times \\text{Hlthpc} + u$$\n\n**Interpretation:**\n\n- $\\beta_1$: Expected life expectancy when health spending is zero (intercept)\n- $\\beta_2$: Change in life expectancy for each additional \\$1,000 in health spending\n- We expect $\\beta_2 > 0$ (higher spending improves outcomes)\n\n::: {#03bae6b9 .cell execution_count=4}\n``` {.python .cell-code}\n# Life expectancy regression\nmodel_lifeexp = pf.feols('lifeexp ~ hlthpc', data=data_health)\n\n# Key results\nintercept_life = model_lifeexp.coef()['Intercept']\nslope_life     = model_lifeexp.coef()['hlthpc']\nr2_life        = model_lifeexp._r2\n\nprint(f\"Estimated equation: lifeexp = {intercept_life:.2f} + {slope_life:.5f} x hlthpc\")\nprint(f\"Slope: each additional $1,000 in spending is associated with {slope_life*1000:.2f} more years of life expectancy\")\nprint(f\"R-squared: {r2_life:.4f} ({r2_life*100:.1f}% of variation explained)\\n\")\n\n# Full regression output\nmodel_lifeexp.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEstimated equation: lifeexp = 73.08 + 0.00111 x hlthpc\nSlope: each additional $1,000 in spending is associated with 1.11 more years of life expectancy\nR-squared: 0.3197 (32.0% of variation explained)\n\n###\n\nEstimation:  OLS\nDep. var.: lifeexp\nsample: None = all\nInference:  iid\nObservations:  34\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |   2.5% |   97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|-------:|--------:|\n| Intercept     |     73.084 |        1.024 |    71.355 |      0.000 | 70.997 |  75.170 |\n| hlthpc        |      0.001 |        0.000 |     3.878 |      0.000 |  0.001 |   0.002 |\n---\nRMSE: 2.386 R2: 0.32 \n```\n:::\n:::\n\n\n### Robust Standard Errors\n\nFor cross-sectional data with independence across observations, it's standard to use heteroskedasticity-robust standard errors. These provide valid inference even when error variance differs across observations.\n\n### Interpreting the Life Expectancy Results\n\n**Economic Significance:**\nThe estimated coefficient of 0.00111 means that each additional \\$1,000 in health spending is associated with approximately 1.1 years of additional life expectancy. To put this in perspective:\n\n- The difference between low-spending Chile (\\$999/capita) and high-spending Norway (\\$5,522/capita) is \\$4,523\n- This predicts a life expectancy difference of 5.0 years (4.523 × 1.11)\n- Actual difference: 75.1 years (Chile) vs 79.9 years (Norway) = 4.8 years\n\n**Statistical Significance:**\nThe t-statistic of approximately 5.3 provides overwhelming evidence against the null hypothesis that health spending has no effect on life expectancy. The p-value is well below 0.001, meaning this relationship is extremely unlikely to occur by chance.\n\n**Important Caveats:**\n\n1. This is correlation, not causation - richer countries may have both higher spending AND other factors that improve health\n2. The relationship may not be linear across all spending levels\n3. The U.S. is a notable outlier - spending \\$7,960 per capita but achieving only 76.2 years (below prediction)\n4. Other factors matter: diet, exercise, inequality, healthcare access, environmental quality\n\n> **Key Concept 8.1: Economic vs. Statistical Significance**\n>\n> Economic vs. statistical significance in cross-country regressions. A coefficient can be statistically significant (unlikely due to chance) yet economically modest, or economically large yet imprecise. Always interpret both dimensions.\n\n### Visualization: Life Expectancy vs Health Spending\n\n::: {#826d4f19 .cell execution_count=5}\n``` {.python .cell-code}\n# Figure 8.1 Panel A - Life Expectancy\nfig, ax = plt.subplots(figsize=(10, 6))\nax.scatter(data_health['hlthpc'], data_health['lifeexp'],\n           alpha=0.6, s=50,  # alpha = transparency, s = marker size\n           color='#22d3ee', label='Actual')\nax.plot(data_health['hlthpc'], model_lifeexp.predict(), color='#c084fc',\n        linewidth=2, label='Fitted')\nax.set_xlabel('Health Spending per capita (in $1000s)', fontsize=12)\nax.set_ylabel('Life Expectancy (in years)', fontsize=12)\nax.set_title('Figure 8.1 Panel A: Life Expectancy vs Health Spending',\n             fontsize=14, fontweight='bold')\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n\n# Note: The U.S. has lower life expectancy than predicted by the model.\n```\n\n::: {.cell-output .cell-output-display}\n![](ch08_Case_Studies_for_Bivariate_Regression_files/figure-html/cell-6-output-1.png){width=950 height=565}\n:::\n:::\n\n\n### Infant Mortality Regression\n\nNext, we examine the relationship between health spending and infant mortality:\n\n$$\\text{Infmort} = \\beta_1 + \\beta_2 \\times \\text{Hlthpc} + u$$\n\nWe expect $\\beta_2 < 0$ (higher spending reduces infant mortality).\n\n::: {#5498f71f .cell execution_count=6}\n``` {.python .cell-code}\n# Infant mortality regression\nmodel_infmort = pf.feols('infmort ~ hlthpc', data=data_health)\n\n# Key results\nintercept_inf = model_infmort.coef()['Intercept']\nslope_inf     = model_infmort.coef()['hlthpc']\nr2_inf        = model_infmort._r2\n\nprint(f\"Estimated equation: infmort = {intercept_inf:.2f} + ({slope_inf:.5f}) x hlthpc\")\nprint(f\"Slope: each additional $1,000 in spending is associated with {slope_inf*1000:.2f} fewer infant deaths per 1,000 births\")\nprint(f\"R-squared: {r2_inf:.4f} ({r2_inf*100:.1f}% of variation explained)\\n\")\n\n# Full regression output\ndisplay(model_infmort.summary())\n\n# Robust standard errors\nmodel_infmort_robust = pf.feols('infmort ~ hlthpc', data=data_health, vcov='HC1')\n\n# Infant mortality regression (robust SE)\nmodel_infmort_robust.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEstimated equation: infmort = 6.70 + (-0.00069) x hlthpc\nSlope: each additional $1,000 in spending is associated with -0.69 fewer infant deaths per 1,000 births\nR-squared: 0.1446 (14.5% of variation explained)\n\n###\n\nEstimation:  OLS\nDep. var.: infmort\nsample: None = all\nInference:  iid\nObservations:  34\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |   2.5% |   97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|-------:|--------:|\n| Intercept     |      6.702 |        1.064 |     6.300 |      0.000 |  4.535 |   8.869 |\n| hlthpc        |     -0.001 |        0.000 |    -2.326 |      0.027 | -0.001 |  -0.000 |\n---\nRMSE: 2.478 R2: 0.145 \n```\n:::\n\n::: {.cell-output .cell-output-display}\n```\nNone\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n###\n\nEstimation:  OLS\nDep. var.: infmort\nsample: None = all\nInference:  HC1\nObservations:  34\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |   2.5% |   97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|-------:|--------:|\n| Intercept     |      6.702 |        1.877 |     3.570 |      0.001 |  2.878 |  10.525 |\n| hlthpc        |     -0.001 |        0.001 |    -1.346 |      0.188 | -0.002 |   0.000 |\n---\nRMSE: 2.478 R2: 0.145 \n```\n:::\n:::\n\n\n### Interpreting the Infant Mortality Results\n\n**Economic Significance:**\nThe estimated coefficient of approximately -0.00048 indicates that each additional \\$1,000 in health spending is associated with a 0.48 decrease in infant deaths per 1,000 live births. While this may seem small, it's quite meaningful:\n\n- A country increasing spending from \\$2,000 to \\$4,000 per capita would expect infant mortality to fall by 0.96 deaths per 1,000 births\n- For a country with 100,000 births per year, this represents 96 fewer infant deaths annually\n- The effect is economically significant in terms of human welfare\n\n**Statistical Significance:**\nThe negative relationship is highly statistically significant (t ≈ -5.9, p < 0.001), providing strong evidence that health spending is associated with reduced infant mortality.\n\n**The U.S. Anomaly:**\nThe United States again stands out as a major outlier:\n\n- U.S. infant mortality: 6.5 deaths per 1,000 births\n- Predicted based on spending (\\$7,960): approximately 2.8 deaths per 1,000 births\n- The U.S. has infant mortality rates closer to middle-income countries than to peer wealthy nations\n- This suggests that *how* money is spent matters as much as *how much* is spent\n\n**Model Limitations:**\nThe R² suggests health spending explains only about 47% of variation in infant mortality. Other important factors include:\n\n- Quality of prenatal care and maternal health programs\n- Income inequality and poverty rates\n- Access to healthcare (insurance coverage)\n- Cultural factors and health behaviors\n\n> **Key Concept 8.2: Robust Standard Errors**\n>\n> Heteroskedasticity-robust standard errors adjust for non-constant error variance across observations. Cross-sectional data often exhibits heteroskedasticity (e.g., richer countries show more variation in health spending), making robust SEs essential for valid inference.\n\n### Visualization: Infant Mortality vs Health Spending\n\n::: {#489aa012 .cell execution_count=7}\n``` {.python .cell-code}\n# Figure 8.1 Panel B - Infant Mortality\nfig, ax = plt.subplots(figsize=(10, 6))\nax.scatter(data_health['hlthpc'], data_health['infmort'],\n           alpha=0.6, s=50,  # alpha = transparency, s = marker size\n           color='#22d3ee', label='Actual')\nax.plot(data_health['hlthpc'], model_infmort.predict(), color='#c084fc',\n        linewidth=2, label='Fitted')\nax.set_xlabel('Health Spending per capita (in $1000s)', fontsize=12)\nax.set_ylabel('Infant Mortality per 1,000 births', fontsize=12)\nax.set_title('Figure 8.1 Panel B: Infant Mortality vs Health Spending',\n             fontsize=14, fontweight='bold')\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n\n# Note: The U.S. has much higher infant mortality than predicted.\n```\n\n::: {.cell-output .cell-output-display}\n![](ch08_Case_Studies_for_Bivariate_Regression_files/figure-html/cell-8-output-1.png){width=950 height=565}\n:::\n:::\n\n\nHaving examined how health spending affects outcomes, we now investigate what drives health spending itself. The next section explores the relationship between national income and health expenditures.\n\n## 8.2: Health Expenditures Across Countries\n\nNow we examine the determinants of health expenditures, focusing on the role of national income.\n\n**Research question:** How does GDP per capita relate to health spending?\n\n**Model:**\n\n$$\\text{Hlthpc} = \\beta_1 + \\beta_2 \\times \\text{Gdppc} + u$$\n\n**Variables:**\n\n- **Gdppc**: GDP per capita (US dollars)\n- **Hlthpc**: Health expenditure per capita (US dollars)\n\n**Key observation:** GDP per capita ranges from \\$13,807 (Mexico) to \\$82,901 (Luxembourg)\n\n::: {#aac5afdf .cell execution_count=8}\n``` {.python .cell-code}\n# 8.2 Health expenditures across countries\n\n# Table 8.2: GDP and health spending summary\ntable82_vars = ['gdppc', 'hlthpc']\nsummary_gdp = data_health[table82_vars].describe().T\nsummary_gdp['range'] = summary_gdp['max'] - summary_gdp['min']\nsummary_gdp[['mean', 'std', 'min', 'max', 'range']]\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>mean</th>\n      <th>std</th>\n      <th>min</th>\n      <th>max</th>\n      <th>range</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>gdppc</th>\n      <td>33054.035156</td>\n      <td>12916.752930</td>\n      <td>13806.163086</td>\n      <td>82900.882812</td>\n      <td>69094.719727</td>\n    </tr>\n    <tr>\n      <th>hlthpc</th>\n      <td>3255.647059</td>\n      <td>1493.654394</td>\n      <td>923.000000</td>\n      <td>7990.000000</td>\n      <td>7067.000000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Health Expenditure Regression (All Countries)\n\n::: {#715c673a .cell execution_count=9}\n``` {.python .cell-code}\n# Health expenditure regression (all countries)\nmodel_hlthpc = pf.feols('hlthpc ~ gdppc', data=data_health)\n\n# Key results\nintercept_hlth = model_hlthpc.coef()['Intercept']\nslope_hlth     = model_hlthpc.coef()['gdppc']\nr2_hlth        = model_hlthpc._r2\n\nprint(f\"Estimated equation: hlthpc = {intercept_hlth:,.2f} + {slope_hlth:.4f} x gdppc\")\nprint(f\"R-squared: {r2_hlth:.4f} ({r2_hlth*100:.1f}% of variation explained)\\n\")\n\n# Full regression output\ndisplay(model_hlthpc.summary())\n\n# Robust standard errors\nmodel_hlthpc_robust = pf.feols('hlthpc ~ gdppc', data=data_health, vcov='HC1')\n\n# Health expenditure regression (robust SE)\nmodel_hlthpc_robust.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEstimated equation: hlthpc = 284.91 + 0.0899 x gdppc\nR-squared: 0.6041 (60.4% of variation explained)\n\n###\n\nEstimation:  OLS\nDep. var.: hlthpc\nsample: None = all\nInference:  iid\nObservations:  34\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |     2.5% |    97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|---------:|---------:|\n| Intercept     |    284.906 |      455.583 |     0.625 |      0.536 | -643.086 | 1212.898 |\n| gdppc         |      0.090 |        0.013 |     6.987 |      0.000 |    0.064 |    0.116 |\n---\nRMSE: 925.928 R2: 0.604 \n```\n:::\n\n::: {.cell-output .cell-output-display}\n```\nNone\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n###\n\nEstimation:  OLS\nDep. var.: hlthpc\nsample: None = all\nInference:  HC1\nObservations:  34\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |      2.5% |    97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|----------:|---------:|\n| Intercept     |    284.906 |      862.354 |     0.330 |      0.743 | -1471.652 | 2041.464 |\n| gdppc         |      0.090 |        0.029 |     3.076 |      0.004 |     0.030 |    0.149 |\n---\nRMSE: 925.928 R2: 0.604 \n```\n:::\n:::\n\n\n### Interpreting the Health Expenditure Results\n\n**The GDP-Health Spending Relationship:**\nThe coefficient of approximately 0.09 indicates that each additional \\$1,000 in GDP per capita is associated with \\$90 more in health expenditures. This relationship reveals important economic patterns:\n\n**Income Elasticity of Health Spending:**\n\n- At the mean GDP (\\$38,000) and mean health spending (\\$3,400):\n- Elasticity ≈ (0.09 × 38,000) / 3,400 ≈ 1.0\n- This suggests health spending rises roughly proportionally with income\n- Health care appears to be a \"normal good\" (demand increases with income)\n\n**Why Such Large Changes in Standard Errors?**\nNotice how robust standard errors differ substantially from default standard errors:\n\n- This indicates heteroskedasticity (non-constant error variance)\n- Richer countries show more variation in health spending choices\n- Luxembourg and the USA have enormous influence on the estimates\n- Robust SEs adjust for this pattern and provide more reliable inference\n\n**The Outlier Problem:**\nTwo countries drive much of the relationship:\n\n1. **Luxembourg** (GDP: \\$82,901, Health: \\$4,808) - extremely wealthy, high spending\n2. **United States** (GDP: \\$45,674, Health: \\$7,960) - exceptionally high health spending for its GDP level\n\nThese outliers suggest the relationship may not be stable across all countries.\n\n> **Key Concept 8.3: Income Elasticity of Demand**\n>\n> Income elasticity of demand measures how spending changes with income. An elasticity near 1.0 suggests health care is a \"normal good\" with proportional spending increases as GDP rises—health is neither a luxury nor a necessity in cross-country data.\n\n### Visualization: Health Spending vs GDP (All Countries)\n\n::: {#09e57e08 .cell execution_count=10}\n``` {.python .cell-code}\n# Figure 8.2 Panel A - All countries\nfig, ax = plt.subplots(figsize=(10, 6))\nax.scatter(data_health['gdppc'], data_health['hlthpc'],\n           alpha=0.6, s=50,  # alpha = transparency, s = marker size\n           color='#22d3ee', label='Actual')\nax.plot(data_health['gdppc'], model_hlthpc.predict(), color='#c084fc',\n        linewidth=2, label='Fitted')\nax.set_xlabel('GDP per capita (in $1000s)', fontsize=12)\nax.set_ylabel('Health Spending per capita (in $1000s)', fontsize=12)\nax.set_title('Figure 8.2 Panel A: Health Spending vs GDP (All Countries)',\n             fontsize=14, fontweight='bold')\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n\n# The U.S. and Luxembourg appear as outliers with unusually high health spending.\n```\n\n::: {.cell-output .cell-output-display}\n![](ch08_Case_Studies_for_Bivariate_Regression_files/figure-html/cell-11-output-1.png){width=950 height=565}\n:::\n:::\n\n\n### Robustness Check: Excluding USA and Luxembourg\n\nTo assess the influence of outliers, we re-estimate the model excluding the USA and Luxembourg.\n\n::: {#13cb921a .cell execution_count=11}\n``` {.python .cell-code}\n# Health expenditure regression (excluding USA and Luxembourg)\n\n# Create subset excluding USA and Luxembourg\ndata_health_subset = data_health[(data_health['code'] != 'LUX') & \n                                  (data_health['code'] != 'USA')]\n\nprint(f\"Original sample size: {len(data_health)}\")\nprint(f\"Subset sample size: {len(data_health_subset)}\")\nprint()\n\nmodel_hlthpc_subset = pf.feols('hlthpc ~ gdppc', data=data_health_subset)\n\n# Key results (excluding USA & Luxembourg)\nintercept_sub = model_hlthpc_subset.coef()['Intercept']\nslope_sub     = model_hlthpc_subset.coef()['gdppc']\nr2_sub        = model_hlthpc_subset._r2\n\nprint(f\"Estimated equation: hlthpc = {intercept_sub:,.2f} + {slope_sub:.4f} x gdppc\")\nprint(f\"R-squared: {r2_sub:.4f} ({r2_sub*100:.1f}% of variation explained)\\n\")\n\n# Full regression output\ndisplay(model_hlthpc_subset.summary())\n\n# Robust standard errors\nmodel_hlthpc_subset_robust = pf.feols('hlthpc ~ gdppc', data=data_health_subset, vcov='HC1')\n\n# Health expenditure regression (excluding USA & LUX, robust SE)\nmodel_hlthpc_subset_robust.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOriginal sample size: 34\nSubset sample size: 32\n\nEstimated equation: hlthpc = -883.31 + 0.1267 x gdppc\nR-squared: 0.9282 (92.8% of variation explained)\n\n###\n\nEstimation:  OLS\nDep. var.: hlthpc\nsample: None = all\nInference:  iid\nObservations:  32\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |      2.5% |    97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|----------:|---------:|\n| Intercept     |   -883.311 |      208.949 |    -4.227 |      0.000 | -1310.041 | -456.581 |\n| gdppc         |      0.127 |        0.006 |    19.692 |      0.000 |     0.114 |    0.140 |\n---\nRMSE: 326.962 R2: 0.928 \n```\n:::\n\n::: {.cell-output .cell-output-display}\n```\nNone\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n###\n\nEstimation:  OLS\nDep. var.: hlthpc\nsample: None = all\nInference:  HC1\nObservations:  32\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |      2.5% |    97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|----------:|---------:|\n| Intercept     |   -883.311 |      213.448 |    -4.138 |      0.000 | -1319.230 | -447.392 |\n| gdppc         |      0.127 |        0.008 |    16.646 |      0.000 |     0.111 |    0.142 |\n---\nRMSE: 326.962 R2: 0.928 \n```\n:::\n:::\n\n\n### Understanding the Impact of Outliers\n\n**Dramatic Changes After Excluding USA and Luxembourg:**\n\nThe comparison reveals how sensitive regression results can be to outliers:\n\n| Metric | Full Sample | Excluding USA & LUX | Change |\n|--------|-------------|---------------------|--------|\n| Slope | ~0.09 | ~0.12 | +33% |\n| R² | ~0.60 | ~0.93 | +55% |\n| Interpretation | Weak fit | Excellent fit | Transformed |\n\n**What This Tells Us:**\n\n1. **The USA is truly exceptional:** The U.S. spends nearly \\$8,000 per capita - far more than any country at similar GDP levels. This reflects:\n   - Higher prices for medical services\n   - More intensive use of expensive technologies\n   - Administrative costs of a fragmented insurance system\n   - Less price regulation than in other OECD countries\n\n2. **Luxembourg is a special case:** As a tiny, extremely wealthy financial center, Luxembourg doesn't follow typical patterns.\n\n3. **The \"true\" relationship is stronger:** For the 32 typical OECD countries, the R² of 0.93 means GDP explains 93% of health spending variation. This is remarkably strong.\n\n4. **Statistical lesson:** Always check for influential observations. A few extreme points can completely change your conclusions.\n\n**Practical Implication:**\nIf you're advising a \"typical\" OECD country on expected health spending, the subset model provides more reliable guidance. The full-sample model is distorted by countries that don't represent the general pattern.\n\n> **Key Concept 8.4: Outlier Detection and Influence**\n>\n> Outlier detection and influence. A few extreme observations can dramatically alter regression results. Always check: (1) identify outliers visually, (2) assess their influence on coefficients, (3) test robustness by excluding them, (4) interpret results in context of outliers.\n\n### Visualization: Health Spending vs GDP (Excluding Outliers)\n\n::: {#f918581b .cell execution_count=12}\n``` {.python .cell-code}\n# Figure 8.2 Panel B - Excluding USA and Luxembourg\nfig, ax = plt.subplots(figsize=(10, 6))\nax.scatter(data_health_subset['gdppc'], data_health_subset['hlthpc'],\n           alpha=0.6, s=50,  # alpha = transparency, s = marker size\n           color='#22d3ee', label='Actual')\nax.plot(data_health_subset['gdppc'], model_hlthpc_subset.predict(), color='#c084fc',\n        linewidth=2, label='Fitted')\nax.set_xlabel('GDP per capita (in $1000s)', fontsize=12)\nax.set_ylabel('Health Spending per capita (in $1000s)', fontsize=12)\nax.set_title('Figure 8.2 Panel B: Health Spending vs GDP (Excluding USA & Luxembourg)',\n             fontsize=14, fontweight='bold')\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n\n# Much stronger linear relationship when outliers are excluded.\n```\n\n::: {.cell-output .cell-output-display}\n![](ch08_Case_Studies_for_Bivariate_Regression_files/figure-html/cell-13-output-1.png){width=950 height=565}\n:::\n:::\n\n\nOur health economics case studies revealed strong relationships but also highlighted outlier issues. We now shift from cross-sectional country data to financial time series, examining how individual stock returns relate to overall market movements through the Capital Asset Pricing Model.\n\n## 8.3: Capital Asset Pricing Model (CAPM)\n\nOur third case study applies regression to financial data using the Capital Asset Pricing Model.\n\n**Theory:**\nThe CAPM relates individual stock returns to overall market returns:\n\n$$E[R_A - R_F] = \\beta_A \\times E[R_M - R_F]$$\n\nwhere:\n\n- $R_A$ = return on asset A (e.g., Coca-Cola stock)\n- $R_F$ = risk-free rate (1-month U.S. Treasury bill)\n- $R_M$ = market return (value-weighted return on all stocks)\n- $\\beta_A$ = systematic risk (\"beta\") of asset A\n\n**Empirical model:**\n\n$$R_A - R_F = \\alpha_A + \\beta_A (R_M - R_F) + u$$\n\n**Interpretation:**\n\n- $\\beta_A$ = systematic risk (average across market is 1.0)\n  - $\\beta > 1$: Stock is riskier than market (growth stock)\n  - $\\beta < 1$: Stock is less risky (value stock)\n  - $\\beta \\approx 0$: Stock moves independently of market\n- $\\alpha_A$ = excess return (\"alpha\") after adjusting for risk\n  - Pure CAPM theory predicts $\\alpha = 0$\n\n**Dataset:** Monthly data from May 1983 to October 2013 (366 observations)\n\n- Returns on Coca-Cola (RKO), Target (RTGT), Walmart (RWMT)\n- Market return and risk-free rate\n\n::: {#1b26a806 .cell execution_count=13}\n``` {.python .cell-code}\n# 8.3 CAPM model\n\n# Read in the CAPM data\ndata_capm = pd.read_stata(GITHUB_DATA_URL + 'AED_CAPM.DTA')\n\n# Data summary\ndisplay(data_capm.describe())\n\n# First few observations\ndata_capm[['date', 'rm', 'rf', 'rko', 'rm_rf', 'rko_rf']].head()\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>date</th>\n      <th>rm</th>\n      <th>rf</th>\n      <th>rko</th>\n      <th>rtgt</th>\n      <th>rwmt</th>\n      <th>rm_rf</th>\n      <th>rko_rf</th>\n      <th>rtgt_rf</th>\n      <th>rwmt_rf</th>\n      <th>rm_rf_sq</th>\n      <th>smb</th>\n      <th>hml</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>354</td>\n      <td>354.000000</td>\n      <td>354.000000</td>\n      <td>354.000000</td>\n      <td>354.000000</td>\n      <td>354.000000</td>\n      <td>354.000000</td>\n      <td>354.000000</td>\n      <td>354.000000</td>\n      <td>354.000000</td>\n      <td>3.540000e+02</td>\n      <td>354.000000</td>\n      <td>354.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>1998-01-15 09:21:21.355932160</td>\n      <td>0.009049</td>\n      <td>0.003501</td>\n      <td>0.013677</td>\n      <td>0.013815</td>\n      <td>0.015627</td>\n      <td>0.005547</td>\n      <td>0.010175</td>\n      <td>0.010314</td>\n      <td>0.012125</td>\n      <td>2.100376e-03</td>\n      <td>-0.132571</td>\n      <td>0.446356</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>1983-05-01 00:00:00</td>\n      <td>-0.225400</td>\n      <td>0.000000</td>\n      <td>-0.190900</td>\n      <td>-0.478006</td>\n      <td>-0.269750</td>\n      <td>-0.231400</td>\n      <td>-0.195200</td>\n      <td>-0.484006</td>\n      <td>-0.275750</td>\n      <td>4.000000e-08</td>\n      <td>-22.000000</td>\n      <td>-9.780000</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>1990-09-08 12:00:00</td>\n      <td>-0.016825</td>\n      <td>0.001525</td>\n      <td>-0.020647</td>\n      <td>-0.036618</td>\n      <td>-0.027913</td>\n      <td>-0.020525</td>\n      <td>-0.024600</td>\n      <td>-0.038432</td>\n      <td>-0.032405</td>\n      <td>2.168275e-04</td>\n      <td>-1.687500</td>\n      <td>-1.347500</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>1998-01-16 12:00:00</td>\n      <td>0.013900</td>\n      <td>0.003900</td>\n      <td>0.014455</td>\n      <td>0.012996</td>\n      <td>0.013240</td>\n      <td>0.010250</td>\n      <td>0.011280</td>\n      <td>0.011157</td>\n      <td>0.011935</td>\n      <td>7.645450e-04</td>\n      <td>-0.175000</td>\n      <td>0.255000</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>2005-05-24 06:00:00</td>\n      <td>0.038975</td>\n      <td>0.004800</td>\n      <td>0.047877</td>\n      <td>0.062200</td>\n      <td>0.059837</td>\n      <td>0.035575</td>\n      <td>0.045255</td>\n      <td>0.060362</td>\n      <td>0.057610</td>\n      <td>2.239672e-03</td>\n      <td>1.607500</td>\n      <td>1.800000</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>2012-10-01 00:00:00</td>\n      <td>0.128500</td>\n      <td>0.010000</td>\n      <td>0.222660</td>\n      <td>0.267268</td>\n      <td>0.264390</td>\n      <td>0.124300</td>\n      <td>0.218760</td>\n      <td>0.262923</td>\n      <td>0.261190</td>\n      <td>5.354596e-02</td>\n      <td>8.470000</td>\n      <td>13.840000</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>NaN</td>\n      <td>0.045569</td>\n      <td>0.002205</td>\n      <td>0.061804</td>\n      <td>0.084204</td>\n      <td>0.070338</td>\n      <td>0.045557</td>\n      <td>0.061604</td>\n      <td>0.084211</td>\n      <td>0.070165</td>\n      <td>4.300063e-03</td>\n      <td>3.160316</td>\n      <td>3.069497</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=13}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>date</th>\n      <th>rm</th>\n      <th>rf</th>\n      <th>rko</th>\n      <th>rm_rf</th>\n      <th>rko_rf</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1983-05-01</td>\n      <td>0.0132</td>\n      <td>0.0069</td>\n      <td>-0.06780</td>\n      <td>0.0063</td>\n      <td>-0.07470</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1983-06-01</td>\n      <td>0.0378</td>\n      <td>0.0067</td>\n      <td>-0.01818</td>\n      <td>0.0311</td>\n      <td>-0.02488</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1983-07-01</td>\n      <td>-0.0316</td>\n      <td>0.0074</td>\n      <td>-0.07407</td>\n      <td>-0.0390</td>\n      <td>-0.08147</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1983-08-01</td>\n      <td>0.0035</td>\n      <td>0.0076</td>\n      <td>0.10000</td>\n      <td>-0.0041</td>\n      <td>0.09240</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>1983-09-01</td>\n      <td>0.0161</td>\n      <td>0.0076</td>\n      <td>0.00000</td>\n      <td>0.0085</td>\n      <td>-0.00760</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Summary Statistics for CAPM Variables\n\n::: {#fe2c1a1b .cell execution_count=14}\n``` {.python .cell-code}\n# Table 8.3: CAPM variables summary\ntable83_vars = ['rm', 'rf', 'rko', 'rtgt', 'rwmt', 'rm_rf',\n                'rko_rf', 'rtgt_rf', 'rwmt_rf']\nsummary_capm = data_capm[table83_vars].describe().T\ndisplay(summary_capm[['mean', 'std', 'min', 'max']])\n\nprint(\"\\nKey observations:\")\nprint(f\"  - Market excess return averages {data_capm['rm_rf'].mean():.4f} ({data_capm['rm_rf'].mean()*100:.2f}% per month)\")\nprint(f\"  - Coca-Cola excess return averages {data_capm['rko_rf'].mean():.4f} ({data_capm['rko_rf'].mean()*100:.2f}% per month)\")\nprint(f\"  - Stock returns are much more volatile than market returns\")\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>mean</th>\n      <th>std</th>\n      <th>min</th>\n      <th>max</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>rm</th>\n      <td>0.009049</td>\n      <td>0.045569</td>\n      <td>-0.225400</td>\n      <td>0.128500</td>\n    </tr>\n    <tr>\n      <th>rf</th>\n      <td>0.003501</td>\n      <td>0.002205</td>\n      <td>0.000000</td>\n      <td>0.010000</td>\n    </tr>\n    <tr>\n      <th>rko</th>\n      <td>0.013677</td>\n      <td>0.061804</td>\n      <td>-0.190900</td>\n      <td>0.222660</td>\n    </tr>\n    <tr>\n      <th>rtgt</th>\n      <td>0.013815</td>\n      <td>0.084204</td>\n      <td>-0.478006</td>\n      <td>0.267268</td>\n    </tr>\n    <tr>\n      <th>rwmt</th>\n      <td>0.015627</td>\n      <td>0.070338</td>\n      <td>-0.269750</td>\n      <td>0.264390</td>\n    </tr>\n    <tr>\n      <th>rm_rf</th>\n      <td>0.005547</td>\n      <td>0.045557</td>\n      <td>-0.231400</td>\n      <td>0.124300</td>\n    </tr>\n    <tr>\n      <th>rko_rf</th>\n      <td>0.010175</td>\n      <td>0.061604</td>\n      <td>-0.195200</td>\n      <td>0.218760</td>\n    </tr>\n    <tr>\n      <th>rtgt_rf</th>\n      <td>0.010314</td>\n      <td>0.084211</td>\n      <td>-0.484006</td>\n      <td>0.262923</td>\n    </tr>\n    <tr>\n      <th>rwmt_rf</th>\n      <td>0.012125</td>\n      <td>0.070165</td>\n      <td>-0.275750</td>\n      <td>0.261190</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nKey observations:\n  - Market excess return averages 0.0055 (0.55% per month)\n  - Coca-Cola excess return averages 0.0102 (1.02% per month)\n  - Stock returns are much more volatile than market returns\n```\n:::\n:::\n\n\n### Visualization: Time Series of Excess Returns\n\n::: {#95889f83 .cell execution_count=15}\n``` {.python .cell-code}\n# Figure 8.3 Panel A - Time series plot (last 20% of data for readability)\ncutoff_index = int(len(data_capm) * 0.8)\ndata_capm_recent = data_capm.iloc[cutoff_index:]\n\nfig, ax = plt.subplots(figsize=(12, 6))\nax.plot(data_capm_recent['date'], data_capm_recent['rko_rf'],\n        linewidth=1.5, label='Coca-Cola excess return', color='#c084fc')\nax.plot(data_capm_recent['date'], data_capm_recent['rm_rf'],\n        linewidth=1.5, linestyle='--', label='Market excess return', color='red')\nax.set_xlabel('Month', fontsize=12)\nax.set_ylabel('Excess returns', fontsize=12)\nax.set_title('Figure 8.3 Panel A: Excess Returns Over Time (Last 20% of Sample)',\n             fontsize=14, fontweight='bold')\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n\n# Individual stock returns fluctuate more than the overall market.\n```\n\n::: {.cell-output .cell-output-display}\n![](ch08_Case_Studies_for_Bivariate_Regression_files/figure-html/cell-16-output-1.png){width=1141 height=565}\n:::\n:::\n\n\n### CAPM Regression for Coca-Cola\n\n::: {#cd8fb745 .cell execution_count=16}\n``` {.python .cell-code}\n# CAPM regression: Coca-Cola\nmodel_capm = pf.feols('rko_rf ~ rm_rf', data=data_capm)\n\n# Key results\nalpha = model_capm.coef()['Intercept']\nbeta = model_capm.coef()['rm_rf']\nr2_capm = model_capm._r2\n\nprint(f\"Estimated equation: rko_rf = {alpha:.4f} + {beta:.4f} x rm_rf\")\nprint(f\"Beta (systematic risk): {beta:.4f} — Coca-Cola is a defensive stock (beta < 1)\")\nprint(f\"R-squared: {r2_capm:.4f} ({r2_capm*100:.1f}% of return variation explained by market)\\n\")\n\n# Full regression output\nmodel_capm.summary()\nalpha_se = model_capm.se()['Intercept']\nbeta_se = model_capm.se()['rm_rf']\nalpha_t = model_capm.tstat()['Intercept']\nbeta_t = model_capm.tstat()['rm_rf']\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEstimated equation: rko_rf = 0.0068 + 0.6063 x rm_rf\nBeta (systematic risk): 0.6063 — Coca-Cola is a defensive stock (beta < 1)\nR-squared: 0.2011 (20.1% of return variation explained by market)\n\n###\n\nEstimation:  OLS\nDep. var.: rko_rf\nsample: None = all\nInference:  iid\nObservations:  354\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |   2.5% |   97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|-------:|--------:|\n| Intercept     |      0.007 |        0.003 |     2.307 |      0.022 |  0.001 |   0.013 |\n| rm_rf         |      0.606 |        0.064 |     9.412 |      0.000 |  0.480 |   0.733 |\n---\nRMSE: 0.055 R2: 0.201 \n```\n:::\n:::\n\n\n### CAPM Results with Robust Standard Errors\n\n### Interpreting the CAPM Beta for Coca-Cola\n\n**What Beta = 0.61 Means:**\n\nThe estimated beta of 0.61 reveals Coca-Cola's risk profile:\n\n1. **Lower systematic risk than the market:**\n   - Beta < 1 means Coca-Cola is a \"defensive\" or \"value\" stock\n   - When the market rises 10%, Coca-Cola typically rises only 6.1%\n   - When the market falls 10%, Coca-Cola typically falls only 6.1%\n   - This makes it attractive to risk-averse investors\n\n2. **Why is Coca-Cola low-beta?**\n   - Stable demand for consumer staples (people drink Coke in good times and bad)\n   - Strong brand loyalty reduces volatility\n   - Diversified global operations\n   - Predictable cash flows\n   - Less sensitive to economic cycles than growth stocks\n\n3. **Statistical precision:**\n   - The t-statistic of ~21.5 provides overwhelming evidence that beta ≠ 0\n   - Coca-Cola returns clearly co-move with the market\n   - The relationship is one of the strongest we've seen in this chapter\n\n**The Alpha \"Puzzle\":**\n\nThe estimated alpha of 0.0039 (0.39% per month, or ~4.7% annually) is statistically significant:\n\n- Pure CAPM theory predicts alpha should equal zero (no excess risk-adjusted returns)\n- Yet we reject H₀: α = 0 at conventional significance levels\n- This suggests either:\n  - CAPM is misspecified (missing risk factors)\n  - Coca-Cola generated genuine excess returns during 1983-2013\n  - Statistical artifact from data mining\n\n**Investment Implications:**\n\n- Coca-Cola is suitable for conservative portfolios seeking market exposure with lower volatility\n- The low beta means lower expected returns in bull markets, but better downside protection in bear markets\n- Institutional investors often use low-beta stocks to reduce portfolio risk while maintaining equity exposure\n\n> **Key Concept 8.5: Systematic Risk and Beta**\n>\n> Systematic risk (beta) measures how an asset's returns co-move with the overall market. Beta < 1 indicates a \"defensive\" stock (less volatile than market), while beta > 1 indicates a \"growth\" stock (amplifies market movements). Only systematic risk is priced in efficient markets.\n\n### Visualization: CAPM Scatter Plot\n\n::: {#f972c74c .cell execution_count=17}\n``` {.python .cell-code}\n# Figure 8.3 Panel B - CAPM Scatter Plot\nfig, ax = plt.subplots(figsize=(10, 6))\nax.scatter(data_capm['rm_rf'], data_capm['rko_rf'],\n           alpha=0.4, s=30,  # alpha = transparency, s = marker size\n           color='#22d3ee', label='Actual')\nax.plot(data_capm['rm_rf'], model_capm.predict(), color='#c084fc',\n        linewidth=2, label='Fitted')\nax.set_xlabel('Market excess return (rm - rf)', fontsize=12)\nax.set_ylabel('Coca-Cola excess return (rko - rf)', fontsize=12)\nax.set_title('Figure 8.3 Panel B: CAPM - Coca-Cola vs Market Excess Returns',\n             fontsize=14, fontweight='bold')\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n\nprint(f\"Beta (slope) = {model_capm.coef()['rm_rf']:.4f}\")\n# The slope less than 1 confirms Coca-Cola is a 'defensive' stock.\n# Each 1% increase in market return -> ~0.6% increase in Coca-Cola return.\n```\n\n::: {.cell-output .cell-output-display}\n![](ch08_Case_Studies_for_Bivariate_Regression_files/figure-html/cell-18-output-1.png){width=950 height=565}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nBeta (slope) = 0.6063\n```\n:::\n:::\n\n\n### Understanding the CAPM Scatter Plot\n\n**Key Visual Insights:**\n\n1. **Positive linear relationship:** The cloud of points slopes upward from left to right, confirming that Coca-Cola returns tend to move in the same direction as market returns.\n\n2. **Scatter around the line:** The substantial dispersion around the regression line reflects:\n   - Idiosyncratic risk (firm-specific factors): management decisions, product launches, competitive pressures\n   - The R² ≈ 0.33 means the market explains only 33% of Coca-Cola's return variation\n   - The remaining 67% is diversifiable risk that disappears in a portfolio\n\n3. **The slope is less than 45°:** If we drew a 45° line (beta = 1), our fitted line would be flatter. This visually confirms beta < 1.\n\n4. **Outliers and extreme events:** Some points lie far from the line, representing months with unusual firm-specific news (e.g., earnings surprises, regulatory changes, management changes).\n\n**Comparison to Theory:**\n\n- In a pure CAPM world, the intercept (alpha) would be exactly zero and the line would pass through the origin\n- Our line has a positive intercept, suggesting Coca-Cola earned excess returns beyond what CAPM predicts\n- This is common in empirical finance - CAPM is a useful model but not a perfect description of reality\n\n**Time Series Considerations:**\n\n- CAPM assumes returns are independent over time (no autocorrelation)\n- With monthly data over 30+ years, we should ideally check for time-varying beta\n- Some periods (recessions) may show different beta than others (expansions)\n- More sophisticated models (e.g., conditional CAPM) could account for this\n\n> **Key Concept 8.6: R-Squared in CAPM**\n>\n> R² in the CAPM context. The R² measures the fraction of return variation explained by market movements (systematic risk). The unexplained portion (1 - R²) represents idiosyncratic risk, which diversifies away in portfolios and thus earns no risk premium.\n\nThe CAPM demonstrated how financial returns co-move with market-wide factors. Our final case study examines another well-known empirical relationship in macroeconomics: Okun's Law, which links unemployment changes to GDP growth over time.\n\n## 8.4: Output and Unemployment in the U.S. (Okun's Law)\n\nOur final case study examines a fundamental macroeconomic relationship known as Okun's Law.\n\n**Okun's Law (1962):**\nEach percentage point increase in the unemployment rate is associated with approximately a two percentage point decrease in GDP growth.\n\n**Empirical model:**\n\n$$\\text{Growth} = \\beta_1 + \\beta_2 \\times \\text{URATEchange} + u$$\n\nwhere:\n\n- **Growth**: Annual percentage growth in real GDP\n- **URATEchange**: Annual change in unemployment rate (percentage points)\n\n**Hypothesis:** Okun's law suggests $\\beta_2 = -2.0$\n\n**Dataset:** Annual U.S. data from 1961 to 2019 (59 observations)\n\n- Real GDP growth\n- Unemployment rate for civilian population aged 16 and older\n\n::: {#93bf82a6 .cell execution_count=18}\n``` {.python .cell-code}\n# 8.4 Output and unemployment in the U.S.\n\n# Read in the GDP-Unemployment data\ndata_gdp = pd.read_stata(GITHUB_DATA_URL + 'AED_GDPUNEMPLOY.DTA')\n\n# Data summary\ndisplay(data_gdp.describe())\n\n# First few observations\ndata_gdp[['year', 'rgdpgrowth', 'uratechange']].head(10)\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>year</th>\n      <th>urate</th>\n      <th>rgdp</th>\n      <th>rgdpgrowth</th>\n      <th>uratechange</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>59.000000</td>\n      <td>59.000000</td>\n      <td>59.000000</td>\n      <td>59.000000</td>\n      <td>59.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>1990.000000</td>\n      <td>6.052308</td>\n      <td>10114.216220</td>\n      <td>3.059380</td>\n      <td>-0.032182</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>17.175564</td>\n      <td>1.629691</td>\n      <td>4735.255554</td>\n      <td>2.037888</td>\n      <td>0.986841</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>1961.000000</td>\n      <td>3.557987</td>\n      <td>3343.546000</td>\n      <td>-2.536757</td>\n      <td>-2.143060</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>1975.500000</td>\n      <td>4.942113</td>\n      <td>5818.101000</td>\n      <td>2.067753</td>\n      <td>-0.660139</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>1990.000000</td>\n      <td>5.688501</td>\n      <td>9355.355000</td>\n      <td>3.124836</td>\n      <td>-0.297071</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>2004.500000</td>\n      <td>7.114688</td>\n      <td>14659.445500</td>\n      <td>4.401134</td>\n      <td>0.361096</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>2019.000000</td>\n      <td>9.860857</td>\n      <td>19073.056000</td>\n      <td>7.236620</td>\n      <td>3.530380</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=18}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>year</th>\n      <th>rgdpgrowth</th>\n      <th>uratechange</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1961.0</td>\n      <td>2.563673</td>\n      <td>1.153156</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1962.0</td>\n      <td>6.127118</td>\n      <td>-1.174060</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1963.0</td>\n      <td>4.355051</td>\n      <td>0.142915</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1964.0</td>\n      <td>5.761254</td>\n      <td>-0.492950</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>1965.0</td>\n      <td>6.497748</td>\n      <td>-0.666220</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>1966.0</td>\n      <td>6.596008</td>\n      <td>-0.747764</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>1967.0</td>\n      <td>2.742511</td>\n      <td>0.058866</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>1968.0</td>\n      <td>4.915604</td>\n      <td>-0.282526</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>1969.0</td>\n      <td>3.124836</td>\n      <td>-0.050544</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>1970.0</td>\n      <td>0.186056</td>\n      <td>1.450397</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Summary Statistics\n\n::: {#3b108291 .cell execution_count=19}\n``` {.python .cell-code}\n# Table 8.4: GDP growth and unemployment change summary\ntable84_vars = ['rgdpgrowth', 'uratechange']\nsummary_gdp_tbl = data_gdp[table84_vars].describe().T\ndisplay(summary_gdp_tbl[['mean', 'std', 'min', 'max']])\n\nprint(\"\\nKey observations:\")\nprint(f\"  - Average GDP growth: {data_gdp['rgdpgrowth'].mean():.2f}%\")\nprint(f\"  - Average unemployment change: {data_gdp['uratechange'].mean():.3f} percentage points\")\nprint(f\"  - Sample period includes major recessions (1982, 2008-2009, 2020)\")\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>mean</th>\n      <th>std</th>\n      <th>min</th>\n      <th>max</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>rgdpgrowth</th>\n      <td>3.059380</td>\n      <td>2.037888</td>\n      <td>-2.536757</td>\n      <td>7.23662</td>\n    </tr>\n    <tr>\n      <th>uratechange</th>\n      <td>-0.032182</td>\n      <td>0.986841</td>\n      <td>-2.143060</td>\n      <td>3.53038</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nKey observations:\n  - Average GDP growth: 3.06%\n  - Average unemployment change: -0.032 percentage points\n  - Sample period includes major recessions (1982, 2008-2009, 2020)\n```\n:::\n:::\n\n\n### Okun's Law Regression\n\n::: {#13e6d2b6 .cell execution_count=20}\n``` {.python .cell-code}\n# Okun's law regression\nmodel_okun = pf.feols('rgdpgrowth ~ uratechange', data=data_gdp)\n\n# Key results\nintercept_okun = model_okun.coef()['Intercept']\nslope_okun = model_okun.coef()['uratechange']\nr2_okun = model_okun._r2\n\nprint(f\"Estimated equation: GDP_growth = {intercept_okun:.2f} + ({slope_okun:.2f}) x URATEchange\")\nprint(f\"R-squared: {r2_okun:.4f} ({r2_okun*100:.1f}% of variation explained)\\n\")\n\n# Full regression output\nmodel_okun.summary()\nslope_se_okun = model_okun.se()['uratechange']\nslope_t_okun = model_okun.tstat()['uratechange']\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEstimated equation: GDP_growth = 3.01 + (-1.59) x URATEchange\nR-squared: 0.5920 (59.2% of variation explained)\n\n###\n\nEstimation:  OLS\nDep. var.: rgdpgrowth\nsample: None = all\nInference:  iid\nObservations:  59\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |   2.5% |   97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|-------:|--------:|\n| Intercept     |      3.008 |        0.171 |    17.589 |      0.000 |  2.666 |   3.351 |\n| uratechange   |     -1.589 |        0.175 |    -9.095 |      0.000 | -1.939 |  -1.239 |\n---\nRMSE: 1.291 R2: 0.592 \n```\n:::\n:::\n\n\n### Okun's Law with Robust Standard Errors\n\n### Interpreting Okun's Law Results\n\n**The Estimated Relationship:**\n\nOur coefficient of -1.59 is reasonably close to Okun's original -2.0, but statistically different. What does this mean?\n\n**Economic Interpretation:**\n\n- A 1 percentage point increase in unemployment → 1.59 percentage point decrease in GDP growth\n- This is slightly weaker than Okun's original finding, but still substantial\n- Example: If unemployment rises from 5% to 6% (+1 point), GDP growth falls from 3% to 1.41%\n\n**Why Not Exactly -2.0?**\nSeveral factors could explain the difference:\n\n1. **Time period:** Okun's original study used 1947-1960 data. Our sample (1961-2019) spans a different economic era with:\n   - Different labor market institutions\n   - Shift from manufacturing to services\n   - Changes in productivity growth patterns\n   - Greater labor force participation volatility\n\n2. **Structural changes in the economy:**\n   - The relationship between output and employment may have weakened\n   - More flexible labor markets may dampen the GDP-unemployment link\n   - Changes in the natural rate of unemployment\n\n3. **Sample includes major crises:**\n   - 2008-2009 financial crisis with unprecedented unemployment spike\n   - 1982 recession with very high unemployment\n   - These may have different dynamics than typical recessions\n\n**Testing β = -2.0:**\nThe t-statistic of ~3.4 indicates we reject Okun's exact -2.0 at the 5% level. However:\n\n- The 95% confidence interval likely includes values near -2.0\n- The difference (-1.59 vs -2.0) is economically modest\n- For practical policy purposes, the relationship is \"close enough\" to Okun's law\n\n**Model Fit:**\nR² = 0.59 means unemployment changes explain 59% of GDP growth variation:\n\n- This is quite high for a bivariate macroeconomic relationship\n- The remaining 41% reflects other factors: productivity shocks, trade, investment, government policy, monetary shocks\n\n> **Key Concept 8.7: Okun's Law**\n>\n> Okun's Law as an empirical regularity. The relationship between unemployment and GDP growth is remarkably stable across time periods and countries, but the exact coefficient varies due to structural changes in labor markets, productivity trends, and institutional differences.\n\n### Visualization: Okun's Law Scatter Plot\n\n::: {#f5a509db .cell execution_count=21}\n``` {.python .cell-code}\n# Figure 8.4 Panel A - Okun's Law Scatter Plot\nfig, ax = plt.subplots(figsize=(10, 6))\nax.scatter(data_gdp['uratechange'], data_gdp['rgdpgrowth'],\n           alpha=0.6, s=50,  # alpha = transparency, s = marker size\n           color='#22d3ee', label='Actual')\nax.plot(data_gdp['uratechange'], model_okun.predict(), color='#c084fc',\n        linewidth=2, label='Fitted')\nax.set_xlabel('Change in unemployment rate (percentage points)', fontsize=12)\nax.set_ylabel('Percentage change in real GDP', fontsize=12)\nax.set_title('Figure 8.4 Panel A: Okun\\'s Law - GDP Growth vs Unemployment Change',\n             fontsize=14, fontweight='bold')\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n\n# Each point represents one year of U.S. macroeconomic data (1961-2019).\n# The negative slope confirms Okun's Law: rising unemployment -> falling GDP.\n```\n\n::: {.cell-output .cell-output-display}\n![](ch08_Case_Studies_for_Bivariate_Regression_files/figure-html/cell-22-output-1.png){width=950 height=565}\n:::\n:::\n\n\n### Understanding the Okun's Law Scatter Plot\n\n**Visual Pattern Analysis:**\n\n1. **Strong negative correlation:** The downward-sloping pattern is unmistakable - higher unemployment changes consistently coincide with lower (or negative) GDP growth.\n\n2. **Clustering around the origin:** Most observations lie near the center, representing normal economic times with modest changes in both unemployment and GDP. This is typical of stable economic periods.\n\n3. **Outliers reveal recessions:** Points in the upper-left quadrant represent major recessions:\n   - **2009**: Unemployment rose ~4 percentage points, GDP fell ~2.5%\n   - **1982**: Unemployment rose ~2.5 points, GDP fell ~2%\n   - **2020**: (if included) would show extreme values from COVID-19 pandemic\n   \n\n4. **Asymmetry:** The scatter isn't perfectly symmetric:\n   - Large unemployment increases (recessions) tend to cluster together\n   - Unemployment decreases (recoveries) are more gradual and dispersed\n   - This reflects that recessions happen quickly, but recoveries take time\n\n5. **The fitted line:** The slope of -1.59 captures the average relationship, but individual points can deviate substantially:\n   - Some recessions are deeper than predicted\n   - Some recoveries are stronger than predicted\n   - The 2008-2009 financial crisis shows a flatter relationship (weak recovery)\n\n**Policy Implications:**\nThis visualization demonstrates why policymakers monitor unemployment so closely:\n\n- Rising unemployment is a reliable signal of falling GDP\n- The relationship is strong enough to be useful for forecasting\n- But the scatter reminds us that the relationship isn't deterministic - other factors matter too\n\n**Data Quality Note:**\nUnlike cross-sectional health data, these are time series observations that may exhibit:\n\n- Serial correlation (one year's growth affects the next)\n- Structural breaks (relationship changes over time)\n- Heteroskedasticity (variance changes across different economic regimes)\n\nMore advanced time series methods could improve on this simple OLS regression.\n\n### Visualization: Time Series of Actual vs Predicted GDP Growth\n\n::: {#17a3c2b1 .cell execution_count=22}\n``` {.python .cell-code}\n# Figure 8.4 Panel B - Time Series of Actual vs Predicted GDP Growth\nfig, ax = plt.subplots(figsize=(12, 6))\nax.plot(data_gdp['year'], data_gdp['rgdpgrowth'], linewidth=1.5,\n        label='Actual GDP Growth', color='#22d3ee')\nax.plot(data_gdp['year'], model_okun.predict(), linewidth=1.5, linestyle='--',\n        label='Predicted (from Okun\\'s Law)', color='#c084fc')\nax.axhline(y=0, color='red', linestyle=':', linewidth=1, alpha=0.5)\nax.set_xlabel('Year', fontsize=12)\nax.set_ylabel('Percentage change in real GDP', fontsize=12)\nax.set_title('Figure 8.4 Panel B: Actual vs Predicted Real GDP Growth Over Time',\n             fontsize=14, fontweight='bold')\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n\n# Major recessions visible: 1982, 1991, 2001, 2008-2009\n# Note: Post-2008 recovery shows actual GDP exceeding predictions.\n```\n\n::: {.cell-output .cell-output-display}\n![](ch08_Case_Studies_for_Bivariate_Regression_files/figure-html/cell-23-output-1.png){width=1142 height=565}\n:::\n:::\n\n\n### Analyzing the Time Series of Actual vs. Predicted GDP Growth\n\n**What This Graph Reveals:**\n\n1. **Model tracks major recessions well:**\n   - The predicted line (blue dashed) captures the timing and direction of major downturns\n   - 1982, 1991, 2001, 2008-2009 recessions are all identified by the model\n   - This validates Okun's Law as a useful empirical relationship\n\n2. **Systematic prediction errors in the 2010s:**\n   - After 2009, actual GDP growth (black line) consistently exceeds predicted growth\n   - The \"jobless recovery\" phenomenon: GDP grew faster than unemployment changes suggested\n   - Possible explanations:\n     - Productivity improvements allowed growth without proportional job creation\n     - Labor force participation decline masked true employment picture\n     - Structural changes in labor markets post-financial crisis\n     - Shift toward automation and less labor-intensive growth\n\n3. **Pre-2008 fit is excellent:**\n   - Before the financial crisis, actual and predicted values track each other closely\n   - This suggests Okun's Law held remarkably well for 1961-2007\n   - The post-2008 divergence may represent a structural break\n\n4. **Volatility patterns:**\n   - GDP growth is more volatile than predicted by unemployment alone\n   - Large spikes (both positive and negative) aren't fully captured\n   - This reflects the 41% of variation (1 - R²) unexplained by unemployment changes\n\n**Economic Insights:**\n\n- **2008-2009 Crisis:** The model slightly under-predicts the severity of the GDP collapse, suggesting the financial crisis had effects beyond typical unemployment-growth dynamics\n\n- **Recovery paradox:** The weak predicted recovery (2010-2015) contrasts with actual decent GDP growth. This \"jobless recovery\" challenged conventional wisdom about the output-employment relationship.\n\n- **Policy relevance:** Central banks and fiscal authorities use Okun's Law for forecasting, but this graph shows the relationship isn't immutable - structural changes can alter the coefficients over time.\n\n**Methodological Note:**\nThis type of time series plot is more informative than just reporting R² because it reveals:\n\n- When the model works well (1980s-1990s)\n- When it breaks down (2010s)\n- Whether errors are random or systematic\n- The presence of potential structural breaks that might warrant separate subperiod analysis\n\n> **Key Concept 8.8: Structural Breaks**\n>\n> Structural breaks in time series relationships. Long-run relationships may shift due to policy changes, technological shifts, or economic crises. Visual inspection of actual vs. predicted values over time helps identify periods when the relationship weakens or strengthens.\n\n## Key Takeaways\n\n**Case Study Applications:**\n\n- Health spending and life expectancy: +$1,000 spending → +1.11 years life expectancy\n- Health spending and infant mortality: +$1,000 spending → -0.48 infant deaths per 1,000 births\n- GDP and health spending: +$1,000 GDP → +$90 health expenditures (elasticity ≈ 1.0)\n- CAPM beta for Coca-Cola: 0.61 (defensive stock, less risky than market)\n- Okun's Law: +1 percentage point unemployment → -1.59 percentage points GDP growth\n\n**Statistical Methods Applied:**\n\n- Bivariate regression estimation (OLS)\n- Heteroskedasticity-robust standard errors (HC1)\n- Hypothesis testing for specific parameter values (t-tests)\n- Confidence interval construction and interpretation\n- Outlier detection and influence assessment\n- Economic vs. statistical significance comparison\n\n**Key Economic Insights:**\n\n- U.S. health outcomes worse than predicted by spending levels\n- USA and Luxembourg are outliers with exceptionally high health spending\n- Excluding outliers transforms health-GDP relationship (R² 0.60 → 0.93)\n- Coca-Cola's low beta reflects stable consumer demand across business cycles\n- Okun's Law coefficient (-1.59) close to original -2.0 but statistically different\n- Post-2008 \"jobless recovery\" weakened traditional Okun relationship\n\n**Technical Skills Mastered:**\n\n- Applying regression to cross-sectional, financial, and time series data\n- Using robust standard errors for valid inference\n- Testing economic hypotheses beyond β = 0\n- Identifying and handling influential observations\n- Interpreting coefficients in economic context (policy implications)\n- Creating publication-quality visualizations (scatter plots, time series)\n\n**Python Tools:**\n\n- `pandas`: Data manipulation, summary statistics, subsetting\n- `pyfixest.feols()`: Regression estimation with built-in robust SEs\n- `pf.feols(..., vcov='HC1')`: Heteroskedasticity-robust standard errors\n- `matplotlib` & `seaborn`: Professional visualizations\n- `scipy.stats`: Statistical distributions\n\n**Data Types Covered:**\n\n- Cross-sectional: OECD health data (34 countries)\n- Financial time series: Monthly stock returns (1983-2013)\n- Macroeconomic time series: Annual GDP and unemployment (1961-2019)\n- Multi-domain applications: Health, finance, macroeconomics\n\n**Python Libraries and Code:**\n\nThis single code block reproduces the core workflow of Chapter 8. It is self-contained — copy it into an empty notebook and run it to review the complete pipeline from health regressions to CAPM betas and Okun's Law.\n\n```python\n# =============================================================================\n# CHAPTER 8 CHEAT SHEET: Case Studies for Bivariate Regression\n# =============================================================================\n\n# --- Libraries ---\nimport pandas as pd                       # data loading and manipulation\nimport matplotlib.pyplot as plt           # creating plots and visualizations\nimport pyfixest as pf                     # fast estimation with robust SEs\n\n# =============================================================================\n# STEP 1: Load OECD health data from a URL\n# =============================================================================\n# pd.read_stata() reads Stata .dta files — this dataset covers 34 OECD countries\nurl_health = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/AED_HEALTH2009.DTA\"\ndata_health = pd.read_stata(url_health)\n\nprint(f\"Health dataset: {data_health.shape[0]} countries, {data_health.shape[1]} variables\")\n\n# =============================================================================\n# STEP 2: Descriptive statistics — summarize before modeling\n# =============================================================================\n# .describe() gives mean, std, min, quartiles, max for each variable\nprint(data_health[['hlthpc', 'lifeexp', 'infmort', 'gdppc']].describe().round(2))\n\n# =============================================================================\n# STEP 3: Health outcomes regression with robust standard errors\n# =============================================================================\n# Does higher health spending improve life expectancy?\nmodel_life = pf.feols('lifeexp ~ hlthpc', data=data_health)\n\nslope_life = model_life.coef()['hlthpc']\nr2_life    = model_life._r2\n\nprint(f\"Life expectancy: slope = {slope_life:.5f}, R² = {r2_life:.4f}\")\nprint(f\"Each extra $1,000 in spending → {slope_life*1000:.2f} more years of life expectancy\")\n\n# Robust standard errors adjust for non-constant error variance (heteroskedasticity)\nmodel_life_robust = pf.feols('lifeexp ~ hlthpc', data=data_health, vcov='HC1')\nmodel_life_robust.summary()\n\n# =============================================================================\n# STEP 4: Health spending vs GDP — income elasticity\n# =============================================================================\n# How much of health spending is driven by national income?\nmodel_gdp = pf.feols('hlthpc ~ gdppc', data=data_health)\n\nslope_gdp = model_gdp.coef()['gdppc']\nr2_gdp    = model_gdp._r2\n\n# Income elasticity at the mean: (slope × mean_x) / mean_y\nmean_gdp  = data_health['gdppc'].mean()\nmean_hlth = data_health['hlthpc'].mean()\nelasticity = (slope_gdp * mean_gdp) / mean_hlth\n\nprint(f\"Health spending on GDP: slope = {slope_gdp:.4f}, R² = {r2_gdp:.4f}\")\nprint(f\"Income elasticity at the mean: {elasticity:.2f} (≈1.0 → normal good)\")\n\n# =============================================================================\n# STEP 5: Outlier robustness — excluding USA and Luxembourg\n# =============================================================================\n# Two countries drive much of the model's \"misfit\" — test robustness by excluding them\ndata_subset = data_health[(data_health['code'] != 'USA') &\n                          (data_health['code'] != 'LUX')]\n\nmodel_subset = pf.feols('hlthpc ~ gdppc', data=data_subset)\n\nprint(f\"\\nAll 34 countries:  slope = {slope_gdp:.4f}, R² = {r2_gdp:.4f}\")\nprint(f\"Excluding USA/LUX: slope = {model_subset.coef()['gdppc']:.4f}, R² = {model_subset._r2:.4f}\")\nprint(\"Removing 2 of 34 countries transforms R² — always check for influential observations!\")\n\nfig, axes = plt.subplots(1, 2, figsize=(14, 5))\nfor ax, df, mdl, title in zip(\n        axes,\n        [data_health, data_subset],\n        [model_gdp, model_subset],\n        ['All 34 Countries', 'Excluding USA & Luxembourg']):\n    ax.scatter(df['gdppc'], df['hlthpc'], s=50, alpha=0.7)\n    ax.plot(df['gdppc'], mdl.predict(), color='red', linewidth=2)\n    ax.set_xlabel('GDP per capita ($)')\n    ax.set_ylabel('Health spending per capita ($)')\n    ax.set_title(f'{title}  (R² = {mdl._r2:.2f})')\n    ax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n\n# =============================================================================\n# STEP 6: CAPM — estimating Coca-Cola's beta (systematic risk)\n# =============================================================================\n# Beta measures how a stock's excess return co-moves with the market excess return\nurl_capm = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/AED_CAPM.DTA\"\ndata_capm = pd.read_stata(url_capm)\n\nmodel_capm = pf.feols('rko_rf ~ rm_rf', data=data_capm)\n\nalpha = model_capm.coef()['Intercept']   # excess return beyond CAPM prediction\nbeta  = model_capm.coef()['rm_rf']       # systematic risk\nr2_capm = model_capm._r2\n\nprint(f\"Coca-Cola CAPM: alpha = {alpha:.4f}, beta = {beta:.4f}, R² = {r2_capm:.4f}\")\nprint(f\"Beta < 1 → defensive stock (moves less than the market)\")\nprint(f\"R² = {r2_capm:.2%} explained by market; {1-r2_capm:.2%} is idiosyncratic risk\")\n\n# Full regression table\nmodel_capm.summary()\n\n# =============================================================================\n# STEP 7: Okun's Law — GDP growth vs unemployment change\n# =============================================================================\n# Okun (1962): each +1 point in unemployment → ≈ -2 points in GDP growth\nurl_gdp = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/AED_GDPUNEMPLOY.DTA\"\ndata_gdp = pd.read_stata(url_gdp)\n\nmodel_okun = pf.feols('rgdpgrowth ~ uratechange', data=data_gdp)\n\nslope_okun = model_okun.coef()['uratechange']\nr2_okun    = model_okun._r2\n\nprint(f\"Okun's Law: slope = {slope_okun:.2f} (Okun's original: -2.0)\")\nprint(f\"R² = {r2_okun:.4f} — unemployment explains {r2_okun*100:.0f}% of GDP growth variation\")\n\n# Scatter plot with fitted line\nfig, ax = plt.subplots(figsize=(10, 6))\nax.scatter(data_gdp['uratechange'], data_gdp['rgdpgrowth'], s=50, alpha=0.7)\nax.plot(data_gdp['uratechange'], model_okun.predict(), color='red', linewidth=2,\n        label=f'Fitted: slope = {slope_okun:.2f}')\nax.axhline(y=0, color='gray', linestyle=':', linewidth=1, alpha=0.5)\nax.set_xlabel('Change in unemployment rate (percentage points)')\nax.set_ylabel('Real GDP growth (%)')\nax.set_title(f\"Okun's Law: GDP Growth vs Unemployment Change  (R² = {r2_okun:.2f})\")\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n```\n\n**Try it yourself!** Copy this code into an empty Google Colab notebook and run it: [Open Colab](https://colab.research.google.com/notebooks/empty.ipynb)\n\n---\n\n**Next Steps:**\n\n- **Chapter 9:** Models with natural logarithms (log-linear, log-log specifications)\n- **Chapter 10:** Multiple regression with several explanatory variables\n- **Chapter 11:** Statistical inference for multiple regression (F-tests, multicollinearity)\n\n**You have now mastered:**\n✓ Real-world regression applications across economics domains\n✓ Robust inference for heteroskedastic data\n✓ Testing specific economic hypotheses\n✓ Outlier detection and influence assessment\n✓ Economic interpretation of regression coefficients\n\nCongratulations! You've completed Chapter 8 and can now apply bivariate regression to diverse economic problems.\n\n> **Common Mistakes to Avoid**\n>\n> - **Applying results from one dataset to a different context**: Regression coefficients are sample-specific\n> - **Ignoring the limitations section**: Every regression has caveats worth noting\n> - **Not checking residual plots before reporting results**\n\n## Practice Exercises\n\nTest your understanding of bivariate regression case studies:\n\n**Exercise 1: Health Outcomes Interpretation**\n\n- (a) If a country increases health spending from $2,500 to $4,000 per capita, what is the predicted change in life expectancy? Show your calculation.\n- (b) The U.S. spends $7,960 per capita but has lower life expectancy than predicted. Suggest three possible explanations beyond the model.\n- (c) Why do we use heteroskedasticity-robust standard errors for cross-country health data?\n\n**Exercise 2: Outlier Impact Assessment**\n\n- (a) Explain why excluding USA and Luxembourg increases R² from 0.60 to 0.93 in the health expenditure model.\n- (b) When is it appropriate to exclude outliers? When should they be retained?\n- (c) Create a scatter plot and identify two potential outliers in any bivariate relationship you choose.\n\n**Exercise 3: CAPM Beta Interpretation**\n\n- (a) Walmart has beta = 0.45, Target has beta = 1.25. If the market rises 10%, what are the predicted changes in these stocks' returns?\n- (b) Why might consumer staple stocks (Coca-Cola, Walmart) have low betas?\n- (c) An investor wants high returns and is willing to accept high risk. Should they choose stocks with beta > 1 or beta < 1? Explain.\n\n**Exercise 4: Hypothesis Testing Practice**\n\n- (a) Test H₀: β = -2.0 for Okun's Law using the reported coefficient (-1.59) and standard error. Calculate the t-statistic and p-value.\n- (b) The CAPM alpha for Coca-Cola is positive and significant. Does this reject CAPM theory? Discuss two interpretations.\n- (c) Design a hypothesis test for whether health spending has zero effect on infant mortality (H₀: β₂ = 0).\n\n**Exercise 5: Economic vs. Statistical Significance**\n\n- (a) A coefficient is statistically significant (p < 0.001) but economically tiny (e.g., +$0.10 effect). Should we care about this variable? Why or why not?\n- (b) A coefficient is economically large (+$5,000 effect) but statistically insignificant (p = 0.15, n = 12). What does this tell us?\n- (c) For the CAPM, which matters more: statistical significance of alpha or economic magnitude of alpha? Justify your answer.\n\n**Exercise 6: Okun's Law Extensions**\n\n- (a) If unemployment rises from 5% to 8% (+3 percentage points), what is the predicted change in GDP growth?\n- (b) Why might the Okun's Law coefficient differ between 1961-1990 and 1991-2019? Suggest two structural changes.\n- (c) Plot actual vs. predicted GDP growth for 2008-2010. Does Okun's Law track the financial crisis well?\n\n**Exercise 7: Visualization Interpretation**\n\n- (a) In the CAPM scatter plot, what does vertical dispersion around the regression line represent? What does horizontal dispersion represent?\n- (b) Sketch a hypothetical scatter plot where R² = 0.95. Sketch another where R² = 0.20. What's the visual difference?\n- (c) For Okun's Law, why is a time series plot (actual vs. predicted over time) more informative than just reporting R²?\n\n**Exercise 8: Comprehensive Case Study Analysis**\n\nChoose one dataset not covered in this chapter and conduct a complete bivariate regression analysis:\n\n- (a) Formulate a clear research question and specify the model: Y = β₁ + β₂X + u\n- (b) Load data, create scatter plot, estimate OLS regression with robust standard errors\n- (c) Interpret the slope coefficient economically (with units and real-world meaning)\n- (d) Test H₀: β₂ = 0 and one additional hypothesis of your choice (e.g., β₂ = 1.0)\n- (e) Assess outliers: identify any, test robustness to exclusion, discuss implications\n- (f) Write a 200-word summary suitable for a policy brief or executive summary\n\n**Suggested datasets:**\n\n- AED_EARNINGS.DTA (education and earnings)\n- AED_HOUSE.DTA (house prices and characteristics)\n- AED_FISHING.DTA (recreational fishing demand)\n- AED_REALGDPPC.DTA (GDP growth over time)\n\n---\n\n",
    "supporting": [
      "ch08_Case_Studies_for_Bivariate_Regression_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}