{
  "hash": "1a2791f3353b5796b62d99861fb6ade3",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 13. Case Studies for Multiple Regression\nexecute:\n  enabled: true\n  warning: false\n---\n\n\n**metricsAI: An Introduction to Econometrics with Python and AI in the Cloud**\n\n*[Carlos Mendez](https://carlos-mendez.org)*\n\n<img src=\"https://raw.githubusercontent.com/quarcs-lab/metricsai/main/images/ch13_visual_summary.jpg\" alt=\"Chapter 13 Visual Summary\" width=\"100%\">\n\nThis notebook presents comprehensive case studies applying multiple regression to real-world economic problems.\n\n[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/quarcs-lab/metricsai/blob/main/notebooks_colab/ch13_Case_Studies_for_Multiple_Regression.ipynb)\n<div class=\"chapter-resources\">\n<a href=\"https://www.youtube.com/watch?v=auS4yrgbAQA\" target=\"_blank\" class=\"resource-btn\">🎬 AI Video</a>\n<a href=\"https://carlos-mendez.my.canva.site/s13-case-studies-for-multiple-regression-pdf\" target=\"_blank\" class=\"resource-btn\">✨ AI Slides</a>\n<a href=\"https://cameron.econ.ucdavis.edu/aed/traedv1_13\" target=\"_blank\" class=\"resource-btn\">📊 Cameron Slides</a>\n<a href=\"https://app.edcafe.ai/quizzes/697869f02f5d08069e04c94f\" target=\"_blank\" class=\"resource-btn\">✏️ Quiz</a>\n<a href=\"https://app.edcafe.ai/chatbots/6978a2122f5d08069e071d09\" target=\"_blank\" class=\"resource-btn\">🤖 AI Tutor</a>\n</div>\n\n\n## Chapter Overview\n\nThis chapter presents **nine comprehensive case studies** that apply multiple regression techniques to real-world economic questions. From analyzing school performance to estimating production functions to testing causal relationships, these case studies demonstrate the breadth and power of regression analysis.\n\n**Design Note:** This chapter uses an integrated case study structure where sections 13.1–13.9 ARE the case studies, each demonstrating different regression techniques and applications.\n\n### What You'll Learn\n\nBy the end of this chapter, you will be able to:\n\n1. Apply multiple regression to analyze school performance and socioeconomic factors\n2. Use logarithmic transformations to estimate production functions\n3. Understand and test for constant returns to scale\n4. Identify and correct for omitted variables bias\n5. Apply cluster-robust standard errors for grouped data\n6. Understand randomized control trials and difference-in-differences methods\n7. Apply regression discontinuity design to causal questions\n8. Use instrumental variables to estimate causal effects\n9. Navigate the data cleaning and preparation process\n\n### Chapter Outline\n\n- **13.1** School Academic Performance Index\n- **13.2** Cobb-Douglas Production Function\n- **13.3** Phillips Curve and Omitted Variables Bias\n- **13.4** Automobile Fuel Efficiency\n- **13.5** RAND Health Insurance Experiment (RCT)\n- **13.6** Health Care Access (Difference-in-Differences)\n- **13.7** Political Incumbency (Regression Discontinuity)\n- **13.8** Institutions and GDP (Instrumental Variables)\n- **13.9** From Raw Data to Final Data\n- **Key Takeaways** — Chapter review and consolidated lessons\n- **Practice Exercises** — Reinforce your understanding\n\n**Datasets used:**\n\n- **AED_API99.DTA**: 807 California high schools, Academic Performance Index (1999) — Case Study 13.1\n- **AED_CobbDouglas.DTA**: 24 years of U.S. manufacturing data (1899–1922) — Case Study 13.2\n- **AED_PhillipsCurve.DTA**: 66 years of U.S. macroeconomic data (1949–2014) — Case Study 13.3\n- **AED_AutoEfficiency.DTA**: 26,995 vehicles, fuel efficiency data (1980–2006) — Case Study 13.4\n- **AED_RandHealthInsurance.DTA**: RAND health insurance experiment (RCT) — Case Study 13.5\n- **AED_SouthAfricaHealth.DTA**: South Africa cross-sectional health data (DiD) — Case Study 13.6\n- **AED_SenateIncumbency.DTA**: U.S. Senate election results (RD) — Case Study 13.7\n- **AED_InstitutionsGDP.DTA**: Cross-country institutions and GDP data (IV) — Case Study 13.8\n\n\n## Setup\n\n::: {#f40e221d .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Setup: Import libraries and configure environment\"}\n# --- Libraries ---\nimport numpy as np                        # numerical operations\nimport pandas as pd                       # data manipulation\nimport matplotlib.pyplot as plt           # plotting\nimport seaborn as sns                     # statistical visualizations\nimport pyfixest as pf                    # fast OLS/IV estimation\nfrom scipy import stats                   # statistical tests\nimport warnings\nwarnings.filterwarnings('ignore')\n\n# --- Reproducibility ---\nnp.random.seed(42)\n\n# --- Data source ---\nGITHUB_DATA_URL = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/\"\n\n# --- Plotting style (dark theme matching book design) ---\nplt.style.use('dark_background')\nsns.set_style(\"darkgrid\")\nplt.rcParams.update({\n    'axes.facecolor': '#1a2235',\n    'figure.facecolor': '#12162c',\n    'grid.color': '#3a4a6b',\n    'figure.figsize': (10, 6),\n    'text.color': 'white',\n    'axes.labelcolor': 'white',\n    'xtick.color': 'white',\n    'ytick.color': 'white',\n    'axes.edgecolor': '#1a2235',\n})\n\nprint(\"✓ Setup complete!\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Setup complete!\n```\n:::\n:::\n\n\n## 13.1 School Academic Performance Index\n\nAnalyzing factors that determine school test scores in California.\n\n::: {#7f39ed47 .cell execution_count=2}\n``` {.python .cell-code}\n# Load API data\ndata_api = pd.read_stata(GITHUB_DATA_URL + 'AED_API99.DTA')\nprint(f\"Loaded {len(data_api)} California high schools\")\nprint(f\"Variables: {list(data_api.columns)}\")\ndata_api.head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLoaded 807 California high schools\nVariables: ['sch_code', 'api99', 'edparent', 'meals', 'englearn', 'yearround', 'credteach', 'emerteach', 'avg_ed_raw', 'pct_af_am', 'pct_am_ind', 'pct_asian', 'pct_fil', 'pct_hisp', 'pct_pac', 'pct_white', 'mobility']\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>sch_code</th>\n      <th>api99</th>\n      <th>edparent</th>\n      <th>meals</th>\n      <th>englearn</th>\n      <th>yearround</th>\n      <th>credteach</th>\n      <th>emerteach</th>\n      <th>avg_ed_raw</th>\n      <th>pct_af_am</th>\n      <th>pct_am_ind</th>\n      <th>pct_asian</th>\n      <th>pct_fil</th>\n      <th>pct_hisp</th>\n      <th>pct_pac</th>\n      <th>pct_white</th>\n      <th>mobility</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>130054</td>\n      <td>633</td>\n      <td>12.78</td>\n      <td>21</td>\n      <td>6</td>\n      <td>0</td>\n      <td>88</td>\n      <td>13</td>\n      <td>2.89</td>\n      <td>6</td>\n      <td>1</td>\n      <td>12</td>\n      <td>9</td>\n      <td>30</td>\n      <td>3</td>\n      <td>39</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>130062</td>\n      <td>646</td>\n      <td>13.42</td>\n      <td>16</td>\n      <td>17</td>\n      <td>0</td>\n      <td>86</td>\n      <td>24</td>\n      <td>3.21</td>\n      <td>5</td>\n      <td>1</td>\n      <td>27</td>\n      <td>6</td>\n      <td>17</td>\n      <td>1</td>\n      <td>43</td>\n      <td>12.0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>130096</td>\n      <td>797</td>\n      <td>14.90</td>\n      <td>1</td>\n      <td>2</td>\n      <td>0</td>\n      <td>100</td>\n      <td>4</td>\n      <td>3.95</td>\n      <td>1</td>\n      <td>1</td>\n      <td>9</td>\n      <td>2</td>\n      <td>5</td>\n      <td>0</td>\n      <td>81</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>130229</td>\n      <td>693</td>\n      <td>13.66</td>\n      <td>0</td>\n      <td>18</td>\n      <td>0</td>\n      <td>93</td>\n      <td>7</td>\n      <td>3.33</td>\n      <td>5</td>\n      <td>1</td>\n      <td>33</td>\n      <td>7</td>\n      <td>10</td>\n      <td>1</td>\n      <td>38</td>\n      <td>7.0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>130450</td>\n      <td>773</td>\n      <td>14.94</td>\n      <td>0</td>\n      <td>9</td>\n      <td>0</td>\n      <td>98</td>\n      <td>7</td>\n      <td>3.97</td>\n      <td>8</td>\n      <td>0</td>\n      <td>28</td>\n      <td>1</td>\n      <td>9</td>\n      <td>1</td>\n      <td>46</td>\n      <td>0.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### **About the Dataset**\n\nThis dataset contains information on **807 California high schools** from 1999. The Academic Performance Index (API) is a score from 200-1000 that measures school performance based on standardized test results.\n\n**Key Variables:**\n\n- `api99`: Academic Performance Index (outcome variable)\n- `edparent`: Average parental education level (1-5 scale)\n- `mealpct`: Percent of students eligible for free/reduced meals (poverty proxy)\n- `elpct`: Percent of English language learners\n- `yrs_teach`: Average teacher experience in years\n- `totcredpc`: Per-pupil total credentials\n- `emrpct`: Percent of emergency credential teachers\n\n**Economic Question:** What factors determine school performance? Is it resources (teachers, funding) or student demographics (poverty, language, parental education)?\n\n::: {#5898be16 .cell execution_count=3}\n``` {.python .cell-code}\n# Summary statistics\nvars_api = ['api99', 'edparent', 'meals', 'englearn', 'yearround', 'credteach', 'emerteach']\ndata_api[vars_api].describe()\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>api99</th>\n      <th>edparent</th>\n      <th>meals</th>\n      <th>englearn</th>\n      <th>yearround</th>\n      <th>credteach</th>\n      <th>emerteach</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>807.000000</td>\n      <td>807.000000</td>\n      <td>807.000000</td>\n      <td>807.000000</td>\n      <td>807.000000</td>\n      <td>807.000000</td>\n      <td>807.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>620.944238</td>\n      <td>12.841289</td>\n      <td>21.918216</td>\n      <td>14.003717</td>\n      <td>0.023544</td>\n      <td>89.836431</td>\n      <td>10.464684</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>107.440771</td>\n      <td>1.234461</td>\n      <td>23.667952</td>\n      <td>12.786517</td>\n      <td>0.151717</td>\n      <td>8.437510</td>\n      <td>8.214762</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>355.000000</td>\n      <td>9.620000</td>\n      <td>0.000000</td>\n      <td>0.000000</td>\n      <td>0.000000</td>\n      <td>33.000000</td>\n      <td>0.000000</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>542.000000</td>\n      <td>12.020000</td>\n      <td>0.000000</td>\n      <td>4.000000</td>\n      <td>0.000000</td>\n      <td>85.000000</td>\n      <td>4.000000</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>620.000000</td>\n      <td>12.880000</td>\n      <td>14.000000</td>\n      <td>10.000000</td>\n      <td>0.000000</td>\n      <td>92.000000</td>\n      <td>9.000000</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>695.000000</td>\n      <td>13.680000</td>\n      <td>36.500000</td>\n      <td>21.000000</td>\n      <td>0.000000</td>\n      <td>96.000000</td>\n      <td>15.000000</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>966.000000</td>\n      <td>16.000000</td>\n      <td>98.000000</td>\n      <td>66.000000</td>\n      <td>1.000000</td>\n      <td>100.000000</td>\n      <td>56.000000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#4924f230 .cell execution_count=4}\n``` {.python .cell-code}\n# Histogram of API scores\nplt.figure(figsize=(10, 6))\nplt.hist(data_api['api99'], bins=30, color='steelblue', alpha=0.7, edgecolor='#3a4a6b')  # bins = number of bars, alpha = transparency\nplt.axvline(data_api['api99'].mean(), color='red', linestyle='--', linewidth=2,\n            label=f'Mean = {data_api[\"api99\"].mean():.1f}')\nplt.axvline(800, color='green', linestyle='--', linewidth=2, label='Target = 800')\nplt.xlabel('Academic Performance Index (API)')\nplt.ylabel('Number of Schools')\nplt.title('Figure 13.1: Distribution of API Scores')\nplt.legend()\nplt.grid(True, alpha=0.3)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch13_Case_Studies_for_Multiple_Regression_files/figure-html/cell-5-output-1.png){width=805 height=521}\n:::\n:::\n\n\n**What to look for in this histogram:**\n\n- **Shape**: Roughly symmetric, slightly left-skewed -- most schools cluster around the middle of the API range\n- **Spread**: Scores range widely from below 400 to above 900, indicating large performance differences across schools\n- **Benchmarks**: The red dashed line (mean) and green dashed line (target of 800) show that most schools fall short of the state target\n\n::: {#7482f278 .cell execution_count=5}\n``` {.python .cell-code}\n# Bivariate regression: API ~ Edparent\nfit_api_biv = pf.feols('api99 ~ edparent', data=data_api, vcov='HC1')\n\n# Key results\nintercept_api = fit_api_biv.coef()['Intercept']\nslope_api     = fit_api_biv.coef()['edparent']\nr2_api        = fit_api_biv._r2\n\nprint(f\"Estimated equation: API = {intercept_api:.1f} + {slope_api:.1f} x edparent\")\nprint(f\"Slope: each additional year of parent education is associated with {slope_api:.1f} higher API\")\nprint(f\"R-squared: {r2_api:.4f} ({r2_api*100:.1f}% of variation explained)\")\n\n# Full regression output\nfit_api_biv.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEstimated equation: API = -400.3 + 79.5 x edparent\nSlope: each additional year of parent education is associated with 79.5 higher API\nR-squared: 0.8350 (83.5% of variation explained)\n###\n\nEstimation:  OLS\nDep. var.: api99\nsample: None = all\nInference:  HC1\nObservations:  807\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |     2.5% |    97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|---------:|---------:|\n| Intercept     |   -400.314 |       15.993 |   -25.030 |      0.000 | -431.707 | -368.920 |\n| edparent      |     79.529 |        1.219 |    65.247 |      0.000 |   77.137 |   81.922 |\n---\nRMSE: 43.62 R2: 0.835 \n```\n:::\n:::\n\n\n::: {#b9668598 .cell execution_count=6}\n``` {.python .cell-code}\n# Scatter plot with regression line\nplt.figure(figsize=(10, 6))\nplt.scatter(data_api['edparent'], data_api['api99'], alpha=0.5, s=30, color='#22d3ee')  # s = marker size, alpha = transparency\nplt.plot(data_api['edparent'], fit_api_biv.predict(), color='#c084fc', linewidth=2,\n         label='Fitted line')\nplt.xlabel('Average Years of Parent Education')\nplt.ylabel('Academic Performance Index (API)')\nplt.title('Figure 13.2: API vs Parent Education')\nplt.legend()\nplt.grid(True, alpha=0.3)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch13_Case_Studies_for_Multiple_Regression_files/figure-html/cell-7-output-1.png){width=812 height=521}\n:::\n:::\n\n\n**What to look for in this scatter plot:**\n\n- **Direction**: Strong positive relationship -- higher parental education is associated with higher API scores\n- **Form**: Roughly linear -- the fitted line captures the trend well\n- **Scatter**: Considerable variation around the line, suggesting other factors also matter\n\n::: {#76a78eb7 .cell execution_count=7}\n``` {.python .cell-code}\n# Correlation matrix\ncorr_matrix = data_api[vars_api].corr()\n# Correlation Matrix\ncorr_matrix.round(2)\n\n# Heatmap\nplt.figure(figsize=(10, 8))\nsns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', center=0,\n            square=True, linewidths=1)\nplt.title('Figure 13.3: Correlation Matrix')\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch13_Case_Studies_for_Multiple_Regression_files/figure-html/cell-8-output-1.png){width=861 height=757}\n:::\n:::\n\n\n### **What the Correlation Matrix Reveals**\n\nThe correlation matrix shows the **linear relationships** between all variables:\n\n**Strong negative correlations** (darker blues):\n\n- `api99` and `mealpct` (-0.90): Schools with more poverty have much lower test scores\n- `api99` and `elpct` (-0.76): More English learners → lower scores\n- These suggest **socioeconomic factors strongly predict performance**\n\n**Positive correlations** (reds):\n\n- `api99` and `edparent` (0.76): Parental education strongly predicts scores\n- Teacher experience and credentials show weaker correlations\n\n**Multicollinearity concerns:**\n\n- `mealpct` and `edparent` are highly correlated (-0.79)\n- This makes it difficult to separate their individual effects\n- Standard errors may be inflated in multiple regression\n\n::: {#2e7b965f .cell execution_count=8}\n``` {.python .cell-code}\n# Multiple regression\nfit_api_mult = pf.feols('api99 ~ edparent + meals + englearn + yearround + credteach + emerteach',\n                         data=data_api)\n# Multiple Regression\nfit_api_mult.summary()\n\n# Coefficient table\ncoef_df = pd.DataFrame({\n    'Coefficient': fit_api_mult.coef(),\n    'Std Error': fit_api_mult.se(),\n    't-stat': fit_api_mult.tstat(),\n    'p-value': fit_api_mult.pvalue()\n}).round(3)\nprint(\"\\n\", coef_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n###\n\nEstimation:  OLS\nDep. var.: api99\nsample: None = all\nInference:  iid\nObservations:  807\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |     2.5% |    97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|---------:|---------:|\n| Intercept     |   -345.328 |       39.954 |    -8.643 |      0.000 | -423.755 | -266.900 |\n| edparent      |     73.942 |        1.883 |    39.273 |      0.000 |   70.246 |   77.638 |\n| meals         |      0.079 |        0.081 |     0.980 |      0.327 |   -0.079 |    0.238 |\n| englearn      |     -0.358 |        0.167 |    -2.145 |      0.032 |   -0.685 |   -0.030 |\n| yearround     |     25.956 |       10.185 |     2.548 |      0.011 |    5.963 |   45.949 |\n| credteach     |      0.387 |        0.311 |     1.247 |      0.213 |   -0.222 |    0.997 |\n| emerteach     |     -1.470 |        0.315 |    -4.672 |      0.000 |   -2.088 |   -0.853 |\n---\nRMSE: 41.22 R2: 0.853 \n\n              Coefficient  Std Error  t-stat  p-value\nCoefficient                                         \nIntercept       -345.328     39.954  -8.643    0.000\nedparent          73.942      1.883  39.273    0.000\nmeals              0.079      0.081   0.980    0.327\nenglearn          -0.358      0.167  -2.145    0.032\nyearround         25.956     10.185   2.548    0.011\ncredteach          0.387      0.311   1.247    0.213\nemerteach         -1.470      0.315  -4.672    0.000\n```\n:::\n:::\n\n\n> **Key Concept 13.1: Multiple Regression and Socioeconomic Determinants**\n>\n> In multiple regression, the coefficient for parent education remains strong (~74 points) even after controlling for meals, English learners, year-round schools, and teacher quality. The high correlation among socioeconomic variables makes it difficult to isolate their separate effects — a common challenge in observational studies.\n\n## 13.2 Cobb-Douglas Production Function\n\nEstimating returns to scale using log transformations.\n\n### **The Cobb-Douglas Production Function**\n\nThe **Cobb-Douglas production function** is one of the most famous models in economics. It describes how inputs (capital K and labor L) combine to produce output Q:\n\n$$Q = \\alpha K^{\\beta_2} L^{\\beta_3}$$\n\n**Parameters:**\n\n- $\\alpha$: Total factor productivity (technology level)\n- $\\beta_2$: Output elasticity of capital (% change in Q from 1% change in K)\n- $\\beta_3$: Output elasticity of labor (% change in Q from 1% change in L)\n\n**Returns to Scale:**\n\n- If $\\beta_2 + \\beta_3 = 1$: **Constant returns** (doubling inputs doubles output)\n- If $\\beta_2 + \\beta_3 > 1$: **Increasing returns** (doubling inputs more than doubles output)\n- If $\\beta_2 + \\beta_3 < 1$: **Decreasing returns** (doubling inputs less than doubles output)\n\n**Why Log-Transform?**\n\nTaking natural logs of both sides converts the **multiplicative model** into a **linear model**:\n\n$$\\ln(Q) = \\beta_1 + \\beta_2 \\ln(K) + \\beta_3 \\ln(L) + u$$\n\nwhere $\\beta_1 = \\ln(\\alpha)$. Now we can use **ordinary least squares (OLS)** regression!\n\n**Dataset:** Douglas (1976) used U.S. manufacturing data from **1899-1922** (24 years) to estimate this function.\n\n::: {#f43693ef .cell execution_count=9}\n``` {.python .cell-code}\n# Load Cobb-Douglas data\ndata_cobb = pd.read_stata(GITHUB_DATA_URL + 'AED_COBBDOUGLAS.DTA')\nprint(f\"Loaded {len(data_cobb)} years of US manufacturing data (1899-1922)\")\nprint(f\"Variables: {list(data_cobb.columns)}\")\ndata_cobb.head(12)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLoaded 24 years of US manufacturing data (1899-1922)\nVariables: ['year', 'q', 'k', 'l', 'lnq', 'lnk', 'lnl']\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=9}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>year</th>\n      <th>q</th>\n      <th>k</th>\n      <th>l</th>\n      <th>lnq</th>\n      <th>lnk</th>\n      <th>lnl</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1899</td>\n      <td>100</td>\n      <td>100</td>\n      <td>100</td>\n      <td>4.605170</td>\n      <td>4.605170</td>\n      <td>4.605170</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1900</td>\n      <td>101</td>\n      <td>107</td>\n      <td>105</td>\n      <td>4.615120</td>\n      <td>4.672829</td>\n      <td>4.653960</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1901</td>\n      <td>112</td>\n      <td>114</td>\n      <td>110</td>\n      <td>4.718499</td>\n      <td>4.736198</td>\n      <td>4.700480</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1902</td>\n      <td>122</td>\n      <td>122</td>\n      <td>118</td>\n      <td>4.804021</td>\n      <td>4.804021</td>\n      <td>4.770685</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>1903</td>\n      <td>124</td>\n      <td>131</td>\n      <td>123</td>\n      <td>4.820282</td>\n      <td>4.875197</td>\n      <td>4.812184</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>1904</td>\n      <td>122</td>\n      <td>138</td>\n      <td>116</td>\n      <td>4.804021</td>\n      <td>4.927254</td>\n      <td>4.753590</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>1905</td>\n      <td>143</td>\n      <td>149</td>\n      <td>125</td>\n      <td>4.962845</td>\n      <td>5.003946</td>\n      <td>4.828314</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>1906</td>\n      <td>152</td>\n      <td>163</td>\n      <td>133</td>\n      <td>5.023880</td>\n      <td>5.093750</td>\n      <td>4.890349</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>1907</td>\n      <td>151</td>\n      <td>176</td>\n      <td>138</td>\n      <td>5.017280</td>\n      <td>5.170484</td>\n      <td>4.927254</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>1908</td>\n      <td>126</td>\n      <td>185</td>\n      <td>121</td>\n      <td>4.836282</td>\n      <td>5.220356</td>\n      <td>4.795791</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>1909</td>\n      <td>155</td>\n      <td>198</td>\n      <td>140</td>\n      <td>5.043425</td>\n      <td>5.288267</td>\n      <td>4.941642</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>1910</td>\n      <td>159</td>\n      <td>208</td>\n      <td>144</td>\n      <td>5.068904</td>\n      <td>5.337538</td>\n      <td>4.969813</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#9734c72f .cell execution_count=10}\n``` {.python .cell-code}\n# Create log transformations\ndata_cobb['lnq'] = np.log(data_cobb['q'])\ndata_cobb['lnk'] = np.log(data_cobb['k'])\ndata_cobb['lnl'] = np.log(data_cobb['l'])\n\nprint(\"Summary statistics (original and log-transformed):\")\ndata_cobb[['q', 'k', 'l', 'lnq', 'lnk', 'lnl']].describe()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSummary statistics (original and log-transformed):\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=10}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>q</th>\n      <th>k</th>\n      <th>l</th>\n      <th>lnq</th>\n      <th>lnk</th>\n      <th>lnl</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>24.000000</td>\n      <td>24.000000</td>\n      <td>24.000000</td>\n      <td>24.000000</td>\n      <td>24.000000</td>\n      <td>24.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>165.916667</td>\n      <td>234.166667</td>\n      <td>145.791667</td>\n      <td>5.077336</td>\n      <td>5.356483</td>\n      <td>4.962723</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>43.753178</td>\n      <td>106.266550</td>\n      <td>29.616357</td>\n      <td>0.269234</td>\n      <td>0.459178</td>\n      <td>0.201077</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>100.000000</td>\n      <td>100.000000</td>\n      <td>100.000000</td>\n      <td>4.605170</td>\n      <td>4.605170</td>\n      <td>4.605170</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>125.500000</td>\n      <td>146.250000</td>\n      <td>122.500000</td>\n      <td>4.832282</td>\n      <td>4.984773</td>\n      <td>4.808086</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>157.000000</td>\n      <td>212.000000</td>\n      <td>144.500000</td>\n      <td>5.056165</td>\n      <td>5.356408</td>\n      <td>4.973274</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>196.250000</td>\n      <td>307.250000</td>\n      <td>155.750000</td>\n      <td>5.277434</td>\n      <td>5.726353</td>\n      <td>5.048065</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>240.000000</td>\n      <td>431.000000</td>\n      <td>200.000000</td>\n      <td>5.480639</td>\n      <td>6.066108</td>\n      <td>5.298317</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#e7597001 .cell execution_count=11}\n``` {.python .cell-code}\n# Estimate Cobb-Douglas with HAC standard errors\ndata_cobb['_time'] = range(len(data_cobb))\nfit_cobb = pf.feols('lnq ~ lnk + lnl', data=data_cobb,\n                    vcov='NW', vcov_kwargs={'time_id': '_time', 'lag': 3})\n\n# Key results\nbeta_k = fit_cobb.coef()['lnk']\nbeta_l = fit_cobb.coef()['lnl']\nr2_cobb = fit_cobb._r2\n\nprint(f\"Estimated equation: ln(Q) = {fit_cobb.coef()['Intercept']:.3f} + {beta_k:.3f} ln(K) + {beta_l:.3f} ln(L)\")\nprint(f\"Capital elasticity: {beta_k:.3f} (1% increase in K raises output by {beta_k:.3f}%)\")\nprint(f\"Labor elasticity: {beta_l:.3f} (1% increase in L raises output by {beta_l:.3f}%)\")\nprint(f\"Sum of coefficients: {beta_k:.3f} + {beta_l:.3f} = {beta_k + beta_l:.3f}\")\nprint(f\"R-squared: {r2_cobb:.4f}\")\n\n# Full regression output\nfit_cobb.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEstimated equation: ln(Q) = -0.177 + 0.233 ln(K) + 0.807 ln(L)\nCapital elasticity: 0.233 (1% increase in K raises output by 0.233%)\nLabor elasticity: 0.807 (1% increase in L raises output by 0.807%)\nSum of coefficients: 0.233 + 0.807 = 1.040\nR-squared: 0.9574\n###\n\nEstimation:  OLS\nDep. var.: lnq\nsample: None = all\nInference:  NW\nObservations:  24\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |   2.5% |   97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|-------:|--------:|\n| Intercept     |     -0.177 |        0.398 |    -0.446 |      0.660 | -1.000 |   0.646 |\n| lnk           |      0.233 |        0.063 |     3.720 |      0.001 |  0.103 |   0.363 |\n| lnl           |      0.807 |        0.135 |     5.995 |      0.000 |  0.529 |   1.086 |\n---\nRMSE: 0.054 R2: 0.957 \n```\n:::\n:::\n\n\n> **Key Concept 13.2: Logarithmic Transformation of Production Functions**\n>\n> Taking natural logarithms of the Cobb-Douglas production function $Q = AK^\\alpha L^\\beta$ transforms it into the linear model $\\ln Q = \\ln A + \\alpha \\ln K + \\beta \\ln L$, suitable for OLS estimation. The resulting coefficients are **elasticities** — directly interpretable as percentage changes.\n\n### **Understanding the Results**\n\n**Estimated Coefficients:**\n\n- $\\hat{\\beta}_2$ (capital) ≈ 0.23: A 1% increase in capital raises output by 0.23%\n- $\\hat{\\beta}_3$ (labor) ≈ 0.81: A 1% increase in labor raises output by 0.81%\n- Sum: 0.23 + 0.81 ≈ **1.04** → Very close to constant returns to scale!\n\n**Why HAC Standard Errors?**\n\nThis is **time series data** (24 consecutive years). Two problems arise:\n\n1. **Autocorrelation**: Output in year t is correlated with output in year t-1\n - Recessions/booms span multiple years\n - Technology shocks persist over time\n\n2. **Heteroskedasticity**: Variance of errors may change over time\n - Economy was more volatile in early 1900s\n - Structural changes during WWI\n\n**HAC (Heteroskedasticity and Autocorrelation Consistent)** standard errors correct for both problems. We use **maxlags=3**, allowing correlations up to 3 years apart.\n\n**Comparison:**\n\n- Default SEs: Assume errors are uncorrelated and homoskedastic (WRONG here!)\n- Robust (HC1) SEs: Fix heteroskedasticity but ignore autocorrelation\n- HAC SEs: Fix BOTH problems (correct choice for time series)\n\n**Economic Interpretation:**\n\nLabor's output elasticity (0.81) is **much larger** than capital's (0.23). This suggests that in early 20th century U.S. manufacturing:\n\n- Labor was the dominant input\n- Capital was relatively less important\n- Consistent with labor-intensive production before automation\n\n::: {#c5d10af2 .cell execution_count=12}\n``` {.python .cell-code}\n# Test constant returns to scale\n# H0: beta_k + beta_l = 1\nsum_betas = beta_k + beta_l\nprint(f\"Testing constant returns to scale:\")\nprint(f\"H0: beta_capital + beta_labor = 1\")\nprint(f\"Estimated sum: {sum_betas:.3f}\")\n\n# Restricted model: ln(Q/L) ~ ln(K/L)\ndata_cobb['lnq_per_l'] = data_cobb['lnq'] - data_cobb['lnl']\ndata_cobb['lnk_per_l'] = data_cobb['lnk'] - data_cobb['lnl']\nfit_restricted = pf.feols('lnq_per_l ~ lnk_per_l', data=data_cobb)\n\n# F-test\nrss_unr = np.sum(fit_cobb._u_hat**2)\nrss_r = np.sum(fit_restricted._u_hat**2)\ndf_resid = fit_cobb._N - len(fit_cobb.coef())\nf_stat = ((rss_r - rss_unr) / 1) / (rss_unr / df_resid)\np_value = 1 - stats.f.cdf(f_stat, 1, df_resid)\n\nprint(f\"F-statistic: {f_stat:.2f}\")\nprint(f\"p-value: {p_value:.3f}\")\nprint(f\"Conclusion: {'Reject' if p_value < 0.05 else 'Fail to reject'} H0 at 5% level\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTesting constant returns to scale:\nH0: beta_capital + beta_labor = 1\nEstimated sum: 1.040\nF-statistic: 0.20\np-value: 0.663\nConclusion: Fail to reject H0 at 5% level\n```\n:::\n:::\n\n\n> **Key Concept 13.3: Testing Constant Returns to Scale**\n>\n> Constant returns to scale implies $\\alpha + \\beta = 1$: doubling all inputs exactly doubles output. The estimated sum of 1.040 is not significantly different from 1 (F-test p = 0.636), consistent with the theoretical prediction for competitive markets. This is a **joint hypothesis test** on the coefficients.\n\n::: {#af682137 .cell execution_count=13}\n``` {.python .cell-code}\n# Predicted output with bias correction\nse = np.sqrt(np.mean(fit_cobb._u_hat**2))\nbias_correction = np.exp(se**2 / 2)\ndata_cobb['q_pred'] = bias_correction * np.exp(fit_cobb.predict())\n\n# Plot actual vs predicted\nplt.figure(figsize=(10, 6))\nplt.plot(data_cobb['year'], data_cobb['q'], 'o-', color='#22d3ee', linewidth=2,\n         markersize=6, label='Actual Q')\nplt.plot(data_cobb['year'], data_cobb['q_pred'], 's--', color='#c084fc', linewidth=2,\n         markersize=5, label='Predicted Q')\nplt.xlabel('Year')\nplt.ylabel('Output Index')\nplt.title('Figure 13.4: Actual vs Predicted Output (1899-1922)')\nplt.legend()\nplt.grid(True, alpha=0.3)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch13_Case_Studies_for_Multiple_Regression_files/figure-html/cell-14-output-1.png){width=812 height=521}\n:::\n:::\n\n\n## 13.3 Phillips Curve and Omitted Variables Bias\n\nDemonstrating omitted variables bias through the breakdown of the Phillips curve.\n\n### **The Phillips Curve and Its Breakdown**\n\nThe **Phillips Curve** describes a **negative relationship** between unemployment and inflation:\n\n- When unemployment is low → workers demand higher wages → prices rise → inflation increases\n- When unemployment is high → workers accept lower wages → prices fall → inflation decreases\n\n**Historical Context:**\n\nA.W. Phillips (1958) found this negative relationship in UK data from 1861-1957. It became a cornerstone of macroeconomic policy:\n\n- Governments believed they could \"trade off\" unemployment for inflation\n- Want lower unemployment? Accept higher inflation\n- Want lower inflation? Accept higher unemployment\n\n**The 1970s Crisis:**\n\nThe relationship **broke down** in the 1970s! Economies experienced **stagflation** (high unemployment AND high inflation simultaneously). This was a major crisis in economic theory.\n\n**The Solution: Expected Inflation**\n\nMilton Friedman and Edmund Phelps showed the original Phillips curve suffered from **omitted variables bias**. The correct model includes **expected inflation**:\n\n$$\\text{Inflation}_t = \\beta_1 + \\beta_2 \\text{Urate}_t + \\beta_3 \\text{Expected Inflation}_t + u_t$$\n\nWe'll demonstrate this using U.S. data from **1949-2014** (66 years).\n\n::: {#00c2dee3 .cell execution_count=14}\n``` {.python .cell-code}\n# Load Phillips curve data\ndata_phillips = pd.read_stata(GITHUB_DATA_URL + 'AED_PHILLIPS.DTA')\nprint(f\"Loaded {len(data_phillips)} years of US data (1949-2014)\")\nprint(f\"Variables: {list(data_phillips.columns)}\")\ndata_phillips.head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLoaded 66 years of US data (1949-2014)\nVariables: ['year', 'urate', 'gdpdef', 'inflgdp', 'pastinflgdp', 'inflgdp1yr', 'cpi', 'inflcpi', 'pastinflcpi', 'infcpi1yr', 'infcpi10yr', 'mich', 'date', 'daten']\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=14}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>year</th>\n      <th>urate</th>\n      <th>gdpdef</th>\n      <th>inflgdp</th>\n      <th>pastinflgdp</th>\n      <th>inflgdp1yr</th>\n      <th>cpi</th>\n      <th>inflcpi</th>\n      <th>pastinflcpi</th>\n      <th>infcpi1yr</th>\n      <th>infcpi10yr</th>\n      <th>mich</th>\n      <th>date</th>\n      <th>daten</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1949.0</td>\n      <td>6.6</td>\n      <td>13.518</td>\n      <td>-1.965335</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>23.6</td>\n      <td>-2.074689</td>\n      <td>7.698837</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>1949-10-01</td>\n      <td>1949-10-01</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1950.0</td>\n      <td>4.3</td>\n      <td>14.090</td>\n      <td>4.231395</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>25.0</td>\n      <td>5.932203</td>\n      <td>3.648189</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>1950-10-01</td>\n      <td>1950-10-01</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1951.0</td>\n      <td>3.1</td>\n      <td>14.869</td>\n      <td>5.528744</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>26.5</td>\n      <td>6.000000</td>\n      <td>3.232486</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>1951-10-01</td>\n      <td>1951-10-01</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1952.0</td>\n      <td>2.7</td>\n      <td>15.091</td>\n      <td>1.493039</td>\n      <td>3.474261</td>\n      <td>NaN</td>\n      <td>26.7</td>\n      <td>0.754717</td>\n      <td>4.063869</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>1952-10-01</td>\n      <td>1952-10-01</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>1953.0</td>\n      <td>4.5</td>\n      <td>15.219</td>\n      <td>0.848188</td>\n      <td>2.905584</td>\n      <td>NaN</td>\n      <td>26.9</td>\n      <td>0.749064</td>\n      <td>3.080858</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>1953-10-01</td>\n      <td>1953-10-01</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#117e259c .cell execution_count=15}\n``` {.python .cell-code}\n# Pre-1970 regression\ndata_pre1970 = data_phillips[data_phillips['year'] < 1970].copy()\ndata_pre1970['_time'] = range(len(data_pre1970))\nfit_pre = pf.feols('inflgdp ~ urate', data=data_pre1970,\n                   vcov='NW', vcov_kwargs={'time_id': '_time', 'lag': 3})\n# Phillips Curve Pre-1970 (1949-1969)\nfit_pre.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n###\n\nEstimation:  OLS\nDep. var.: inflgdp\nsample: None = all\nInference:  NW\nObservations:  21\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |   2.5% |   97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|-------:|--------:|\n| Intercept     |      7.106 |        1.581 |     4.493 |      0.000 |  3.807 |  10.405 |\n| urate         |     -1.030 |        0.325 |    -3.167 |      0.005 | -1.708 |  -0.352 |\n---\nRMSE: 1.251 R2: 0.454 \n```\n:::\n:::\n\n\n### **Pre-1970: Phillips Curve Works!**\n\n**Results:**\n\n- Coefficient on unemployment ≈ **-0.89**\n- **Negative** relationship (as theory predicts!)\n- Statistically significant\n- 1% increase in unemployment → 0.89% decrease in inflation\n\nThe scatter plot shows a clear downward slope. This is the classic Phillips curve that policymakers relied on in the 1950s-60s.\n\n**Why did it work?**\n\nIn the 1950s-60s, expected inflation was **stable and low** (around 2-3%). Since it didn't vary much, omitting it from the regression didn't cause serious bias.\n\n::: {#cf14587c .cell execution_count=16}\n``` {.python .cell-code}\n# Plot pre-1970\nplt.figure(figsize=(10, 6))\nplt.scatter(data_pre1970['urate'], data_pre1970['inflgdp'], alpha=0.7, s=50, color='#22d3ee')  # s = marker size, alpha = transparency\nplt.plot(data_pre1970['urate'], fit_pre.predict(), color='#c084fc', linewidth=2,\n         label='Fitted line')\nplt.xlabel('Unemployment Rate (%)')\nplt.ylabel('Inflation Rate (%)')\nplt.title('Figure 13.5: Phillips Curve Pre-1970 (Negative Relationship)')\nplt.legend()\nplt.grid(True, alpha=0.3)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch13_Case_Studies_for_Multiple_Regression_files/figure-html/cell-17-output-1.png){width=805 height=521}\n:::\n:::\n\n\n**What to look for in this scatter plot:**\n\n- **Direction**: Negative slope -- higher unemployment is associated with lower inflation (the classic Phillips curve trade-off)\n- **Strength**: Reasonably tight clustering around the fitted line for this small sample (21 years)\n- **Context**: This downward-sloping pattern is what policymakers relied on in the 1950s-60s\n\n::: {#f6f46a69 .cell execution_count=17}\n``` {.python .cell-code}\n# Post-1970 regression\ndata_post1970 = data_phillips[data_phillips['year'] >= 1970].copy()\ndata_post1970['_time'] = range(len(data_post1970))\nfit_post = pf.feols('inflgdp ~ urate', data=data_post1970,\n                    vcov='NW', vcov_kwargs={'time_id': '_time', 'lag': 5})\n# Phillips Curve Post-1970 (1970-2014)\nfit_post.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n###\n\nEstimation:  OLS\nDep. var.: inflgdp\nsample: None = all\nInference:  NW\nObservations:  45\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |   2.5% |   97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|-------:|--------:|\n| Intercept     |      1.928 |        1.868 |     1.032 |      0.308 | -1.837 |   5.693 |\n| urate         |      0.265 |        0.326 |     0.814 |      0.420 | -0.392 |   0.922 |\n---\nRMSE: 2.387 R2: 0.028 \n```\n:::\n:::\n\n\n> **Key Concept 13.4: The Phillips Curve Breakdown**\n>\n> Pre-1970, higher unemployment was associated with lower inflation (the classic Phillips curve trade-off). Post-1970, this relationship **reversed** — suggesting the simple bivariate model was misspecified. The breakdown motivated the **expectations-augmented Phillips curve**, which includes expected inflation as a regressor.\n\n### **Post-1970: Phillips Curve Breaks Down!**\n\n**Results:**\n\n- Coefficient on unemployment ≈ **+0.27**\n- **Positive** relationship (opposite of theory!)\n- The sign reversed!\n\nThe scatter plot shows an upward slope - higher unemployment is associated with higher inflation. This is **stagflation**.\n\n**What went wrong?**\n\nIn the 1970s, expected inflation became:\n\n- Much higher (reached 10%+ during oil shocks)\n- Much more variable (changed frequently)\n- Correlated with unemployment (both rose together)\n\nOmitting expected inflation now causes **severe omitted variables bias** that reverses the sign of the unemployment coefficient!\n\n::: {#08791755 .cell execution_count=18}\n``` {.python .cell-code}\n# Plot post-1970\nplt.figure(figsize=(10, 6))\nplt.scatter(data_post1970['urate'], data_post1970['inflgdp'], alpha=0.7, s=50, color='#22d3ee')  # s = marker size, alpha = transparency\nplt.plot(data_post1970['urate'], fit_post.predict(), color='red', linewidth=2,\n         label='Fitted line')\nplt.xlabel('Unemployment Rate (%)')\nplt.ylabel('Inflation Rate (%)')\nplt.title('Figure 13.6: Phillips Curve Post-1970 (Positive Relationship - Breakdown!)')\nplt.legend()\nplt.grid(True, alpha=0.3)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch13_Case_Studies_for_Multiple_Regression_files/figure-html/cell-19-output-1.png){width=805 height=521}\n:::\n:::\n\n\n**What to look for in this scatter plot:**\n\n- **Direction**: Positive slope -- the relationship has **reversed** compared to pre-1970\n- **Scatter**: Much wider dispersion around the line, reflecting the turbulent 1970s-80s\n- **Implication**: The simple bivariate Phillips curve is misspecified post-1970 (omitted variables bias)\n\n::: {#3d7684d0 .cell execution_count=19}\n``` {.python .cell-code}\n# Augmented Phillips curve (adding expected inflation)\n\ndata_post1970_exp = data_post1970.dropna(subset=['inflgdp1yr'])\n\ndata_post1970_exp = data_post1970_exp.copy()\ndata_post1970_exp['_time'] = range(len(data_post1970_exp))\nfit_augmented = pf.feols('inflgdp ~ urate + inflgdp1yr', data=data_post1970_exp,\n                         vcov='NW', vcov_kwargs={'time_id': '_time', 'lag': 5})\n\n\n# Augmented Phillips Curve Post-1970\n\n\nfit_augmented.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n###\n\nEstimation:  OLS\nDep. var.: inflgdp\nsample: None = all\nInference:  NW\nObservations:  45\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |   2.5% |   97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|-------:|--------:|\n| Intercept     |      0.270 |        0.634 |     0.426 |      0.672 | -1.007 |   1.547 |\n| urate         |     -0.128 |        0.081 |    -1.575 |      0.122 | -0.291 |   0.036 |\n| inflgdp1yr    |      1.146 |        0.085 |    13.480 |      0.000 |  0.975 |   1.318 |\n---\nRMSE: 0.835 R2: 0.881 \n```\n:::\n:::\n\n\n::: {#4c64bfd4 .cell execution_count=20}\n``` {.python .cell-code}\n# Demonstrate omitted variables bias\n\n# Bivariate regression of Expinflation on Urate\nfit_aux = pf.feols('inflgdp1yr ~ urate', data=data_post1970_exp)\n\ngamma = fit_aux.coef()['urate']\nbeta3 = fit_augmented.coef()['inflgdp1yr']\nbeta2 = fit_augmented.coef()['urate']\n\n# Omitted Variables Bias Calculation\n# True model: Inflation = β1 + β2*Urate + β3*Expinflation\n# Omitted model: Inflation = b1 + b2*Urate\n# Omitted variables bias formula: E[b2] = β2 + β3*γ\n# where γ = coefficient from Expinflation ~ Urate regression\n\nprint(f\"\\nγ (from auxiliary regression): {gamma:.3f}\")\nprint(f\"β3 (from full model): {beta3:.3f}\")\nprint(f\"β2 (from full model): {beta2:.3f}\")\n\nprint(\n    f\"\\nPredicted E[b2] = {beta2:.3f} + {beta3:.3f} * {gamma:.3f} \"\n    f\"= {beta2 + beta3 * gamma:.3f}\"\n)\nprint(f\"Actual b2 (from bivariate): {fit_post.coef()['urate']:.3f}\")\n\nprint(\"\\n✓ Omitted variables bias explains the sign reversal!\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nγ (from auxiliary regression): 0.343\nβ3 (from full model): 1.146\nβ2 (from full model): -0.128\n\nPredicted E[b2] = -0.128 + 1.146 * 0.343 = 0.265\nActual b2 (from bivariate): 0.265\n\n✓ Omitted variables bias explains the sign reversal!\n```\n:::\n:::\n\n\n> **Key Concept 13.5: Omitted Variables Bias**\n>\n> When a relevant variable (expected inflation) is omitted from the regression, its effect gets absorbed into the included variable's coefficient. The **OVB formula** shows that the bias equals the omitted variable's coefficient times its correlation with the included regressor. In the Phillips curve, this bias reversed the sign of the unemployment coefficient.\n\n### **Understanding Omitted Variables Bias**\n\nThe **omitted variables bias formula** tells us how the coefficient in the bivariate (wrong) model relates to the true coefficients:\n\n$$E[b_2] = \\beta_2 + \\beta_3 \\gamma$$\n\nwhere:\n\n- $b_2$: coefficient on Urate in **bivariate model** (omits expected inflation)\n- $\\beta_2$: true coefficient on Urate in **full model**\n- $\\beta_3$: true coefficient on expected inflation in **full model**\n- $\\gamma$: coefficient from regressing expected inflation on Urate (**auxiliary regression**)\n\n**What we found:**\n\n- $\\beta_2 \\approx -1.15$ (true negative effect of unemployment)\n- $\\beta_3 \\approx +1.15$ (expected inflation has 1-to-1 effect on actual inflation)\n- $\\gamma \\approx +0.34$ (when unemployment rises, expected inflation also rises in 1970s!)\n\n**Predicted bias:**\n$$E[b_2] = -1.15 + 1.15 \\times 0.34 \\approx +0.26$$\n\n**Actual $b_2$ from bivariate model:** +0.27\n\n**Perfect match!** The omitted variables bias formula **exactly explains** why the sign reversed.\n\n**Economic Interpretation:**\n\nIn the 1970s:\n\n1. Oil shocks raised unemployment (supply shocks)\n2. Same oil shocks raised expected inflation (cost-push)\n3. Unemployment and expected inflation moved **together**\n4. Omitting expected inflation makes unemployment look like it **causes** inflation\n5. But really, both are caused by the same underlying shocks\n\n**The Lesson:**\n\nThe Phillips curve didn't \"disappear\" - it was always conditional on expected inflation. Once we control for expectations, the negative relationship returns. This revolutionized central bank policy: to fight inflation, must manage expectations!\n\n## 13.4 Automobile Fuel Efficiency\n\nLarge dataset analysis with cluster-robust standard errors.\n\n### **Case Study: Automobile Fuel Efficiency (1980-2006)**\n\n**The Policy Question**: What determines vehicle fuel efficiency, and why didn't MPG improve more despite technological advances?\n\n**Economic Context:**\n\nFrom 1980-2006, the U.S. auto industry faced:\n\n- **1970s oil shocks**: Created demand for fuel efficiency\n- **CAFE standards**: Government regulations on average MPG\n- **Consumer preferences**: Growing demand for SUVs and trucks\n- **Technological progress**: Better engines, materials, aerodynamics\n\nYet average fuel economy **stagnated**. Why?\n\n**The Data**: 26,995 vehicles sold in the U.S. market (1980-2006)\n\n**Key Variables**:\n\n- `mpg`: Miles per gallon (fuel efficiency)\n- `curbwt`: Vehicle weight in pounds\n- `hp`: Horsepower (engine power)\n- `torque`: Engine torque (pulling power)\n- `year`: Model year (captures technology trends)\n- `mfr`: Manufacturer (for clustering)\n\n**The Research Question:**\n\nHow much does each factor contribute to fuel efficiency?\n\n- Weight vs power vs technology\n- Are efficiency gains \"spent\" on other attributes?\n\n**Methodological Challenge**:\n\nVehicles from the same manufacturer share:\n\n- Common technology platforms\n- Similar design philosophy\n- Shared engineering teams\n\nThis creates **clustered errors** → need cluster-robust standard errors!\n\n**Method**: Log-log regression with cluster-robust SEs (by manufacturer)\n\n::: {#8ebb6e88 .cell execution_count=21}\n``` {.python .cell-code}\n# Load automobile data\ndata_auto = pd.read_stata(GITHUB_DATA_URL + 'AED_AUTOSMPG.DTA')\nprint(f\"Loaded {len(data_auto)} vehicle observations (1980-2006)\")\nprint(f\"\\nKey variables: {['year', 'mfr', 'mpg', 'curbwt', 'hp', 'torque']}\")\nprint(f\"\\nNote: Dataset has pre-computed log transformations (lmpg, lcurbwt, lhp, ltorque)\")\ndata_auto[['year', 'mfr', 'mpg', 'curbwt', 'hp', 'torque']].head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLoaded 26995 vehicle observations (1980-2006)\n\nKey variables: ['year', 'mfr', 'mpg', 'curbwt', 'hp', 'torque']\n\nNote: Dataset has pre-computed log transformations (lmpg, lcurbwt, lhp, ltorque)\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=21}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>year</th>\n      <th>mfr</th>\n      <th>mpg</th>\n      <th>curbwt</th>\n      <th>hp</th>\n      <th>torque</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1980.0</td>\n      <td>FIAT</td>\n      <td>21.700001</td>\n      <td>2455</td>\n      <td>111</td>\n      <td>149.199997</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1980.0</td>\n      <td>AMC</td>\n      <td>22.400000</td>\n      <td>2807</td>\n      <td>90</td>\n      <td>176.300003</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1980.0</td>\n      <td>AMC</td>\n      <td>24.600000</td>\n      <td>2767</td>\n      <td>90</td>\n      <td>176.300003</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1980.0</td>\n      <td>AMC</td>\n      <td>20.400000</td>\n      <td>2856</td>\n      <td>110</td>\n      <td>284.799988</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>1980.0</td>\n      <td>AMC</td>\n      <td>20.500000</td>\n      <td>2816</td>\n      <td>110</td>\n      <td>284.799988</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#051be20d .cell execution_count=22}\n``` {.python .cell-code}\n# Summary statistics\nkey_vars = ['mpg', 'curbwt', 'hp', 'torque', 'year']\n# Summary Statistics\ndata_auto[key_vars].describe()\n\n# Manufacturer distribution\n# TOP 10 MANUFACTURERS BY OBSERVATIONS\ndata_auto['mfr'].value_counts().head(10)\n```\n\n::: {.cell-output .cell-output-display execution_count=22}\n```\nmfr\nGMC           7979\nCHRYSLER      4172\nFORD          3709\nTOYOTA        1554\nNISSAN        1079\nVOLKSWAGEN     831\nHONDA          743\nBMW            740\nMITSUBISHI     685\nMAZDA          612\nName: count, dtype: int64\n```\n:::\n:::\n\n\n**Key Observations from Summary Statistics:**\n\n- **Sample size**: 26,995 vehicles (1980-2006)\n- **Time span**: 27 years of data\n- **MPG range**: 8.7 to 76.4 (huge variation!)\n- **Weight**: 1,450 to 6,700 lbs (compact cars to large trucks)\n\n**Top manufacturers**: General Motors, Ford, Chrysler dominate (this is U.S. market data)\n\n**Why log-log specification?**\n\nWe use logs of both outcome (MPG) and predictors (weight, HP, torque) because:\n\n1. **Elasticity interpretation**: Coefficients = percentage changes\n   - β = -0.5 means: 1% ↑ in weight → 0.5% ↓ in MPG\n\n2. **Nonlinear relationships**: MPG doesn't change linearly with weight\n   - Going from 2,000→2,100 lbs has different effect than 4,000→4,100 lbs\n   - Logs capture this naturally\n\n3. **Reduces heteroskedasticity**: Log transformation stabilizes variance\n\n::: {#08c35b36 .cell execution_count=23}\n``` {.python .cell-code}\n# Log-log regression with cluster-robust standard errors\n# Use pre-computed log variables\nfit_auto = pf.feols('lmpg ~ lhp + lcurbwt + ltorque + year', data=data_auto, vcov={'CRV1': 'mfr'})\n\n# Log-Log Regression: Fuel Efficiency\nfit_auto.summary()\n\n# Interpretation\n# ELASTICITY INTERPRETATION\nprint(f\"Horsepower elasticity: {fit_auto.coef()['lhp']:.3f}\")\nprint(f\"  → 1% increase in HP → {fit_auto.coef()['lhp']:.2f}% change in MPG\")\nprint(f\"\\nWeight elasticity: {fit_auto.coef()['lcurbwt']:.3f}\")\nprint(f\"  → 1% increase in weight → {fit_auto.coef()['lcurbwt']:.2f}% change in MPG\")\nprint(f\"\\nTorque elasticity: {fit_auto.coef()['ltorque']:.3f}\")\nprint(f\"  → 1% increase in torque → {fit_auto.coef()['ltorque']:.2f}% change in MPG\")\nprint(f\"\\nYear trend: {fit_auto.coef()['year']:.4f}\")\nprint(f\"  → Efficiency improves {fit_auto.coef()['year']*100:.2f}% per year\")\n\n# CLUSTER-ROBUST STANDARD ERRORS\nprint(f\"Clustered by manufacturer (mfr)\")\nprint(f\"Number of clusters: {data_auto['mfr'].nunique()}\")\nprint(f\"Average observations per cluster: {len(data_auto)/data_auto['mfr'].nunique():.0f}\")\nprint(f\"\\nWhy cluster? Vehicles from same manufacturer likely have correlated errors\")\nprint(f\"due to common technology, design philosophy, and engineering teams.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n###\n\nEstimation:  OLS\nDep. var.: lmpg\nsample: None = all\nInference:  CRV1\nObservations:  26995\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |    2.5% |   97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|--------:|--------:|\n| Intercept     |    -20.843 |        1.988 |   -10.484 |      0.000 | -24.868 | -16.818 |\n| lhp           |     -0.181 |        0.065 |    -2.786 |      0.008 |  -0.313 |  -0.050 |\n| lcurbwt       |     -0.562 |        0.057 |    -9.938 |      0.000 |  -0.677 |  -0.448 |\n| ltorque       |     -0.141 |        0.064 |    -2.211 |      0.033 |  -0.271 |  -0.012 |\n| year          |      0.015 |        0.001 |    13.840 |      0.000 |   0.013 |   0.017 |\n---\nRMSE: 0.125 R2: 0.777 \nHorsepower elasticity: -0.181\n  → 1% increase in HP → -0.18% change in MPG\n\nWeight elasticity: -0.562\n  → 1% increase in weight → -0.56% change in MPG\n\nTorque elasticity: -0.141\n  → 1% increase in torque → -0.14% change in MPG\n\nYear trend: 0.0152\n  → Efficiency improves 1.52% per year\nClustered by manufacturer (mfr)\nNumber of clusters: 39\nAverage observations per cluster: 692\n\nWhy cluster? Vehicles from same manufacturer likely have correlated errors\ndue to common technology, design philosophy, and engineering teams.\n```\n:::\n:::\n\n\n> **Key Concept 13.6: Cluster-Robust Standard Errors for Grouped Data**\n>\n> When observations are grouped (e.g., vehicles by manufacturer), errors within groups may be correlated. **Cluster-robust standard errors** account for this within-group correlation. Using default SEs when clustering exists **understates uncertainty**, leading to false rejections of the null hypothesis.\n\n### **Interpreting the Results**\n\n**Key Findings:**\n\n1. **Weight Elasticity**: ≈ -0.56\n - 1% increase in vehicle weight → 0.56% decrease in MPG\n - **Largest effect** among all variables\n - Heavier vehicles are substantially less efficient\n\n2. **Horsepower Elasticity**: ≈ -0.30 to -0.35\n - 1% increase in HP → ~0.3% decrease in MPG\n - More powerful engines burn more fuel\n\n3. **Torque Elasticity**: ≈ -0.10 to -0.15\n - Smaller effect than weight or HP\n - Torque affects efficiency but less than other factors\n\n4. **Year Trend**: ≈ +0.01 to +0.02\n - Technology improves efficiency ~1-2% per year\n - But this is **offset** by increasing weight!\n\n**The Weight Paradox:**\n\nDespite technological improvements:\n\n- Vehicles got **heavier** (better safety, more features)\n- Average MPG didn't improve much from 1980-2005\n- Efficiency gains were \"spent\" on weight/power instead of MPG\n\n**Why Cluster-Robust Standard Errors?**\n\nWe cluster by manufacturer because:\n\n- Ford vehicles share common technology\n- Toyota vehicles share design philosophy\n- Errors within manufacturer are **correlated**\n\n**Number of clusters**: 40+ manufacturers\n**Average per cluster**: ~600 vehicles\n\nClustering increases SEs → more conservative inference\n\n**Policy Implications:**\n\n1. **CAFE Standards**: Corporate Average Fuel Economy regulations\n - Weight matters more than technology\n - Encouraging lighter vehicles could have large impact\n\n2. **Consumer Trade-offs**:\n - Safety (heavier) vs Efficiency (lighter)\n - Power (higher HP) vs MPG (lower HP)\n - Consumers chose weight/power over efficiency\n\n3. **Recent Trends** (post-2005, not in data):\n - Hybrid/electric technology\n - Lightweight materials (aluminum, carbon fiber)\n - Smaller turbocharged engines\n\n**Model Quality:**\n\nR² ≈ 0.78 means the model explains 78% of MPG variation\n\n- Excellent fit!\n- Weight, HP, torque are key predictors\n- But 22% remains unexplained (aerodynamics, transmission, etc.)\n\n## 13.5 Rand Health Insurance Experiment (RCT)\n\nRandomized control trial for causal inference.\n\n### **Case Study: The RAND Health Insurance Experiment (Randomized Control Trial)**\n\n**The Gold Standard for Causal Inference**: Randomized Control Trials (RCTs)\n\n**The Policy Question**: Does health insurance coverage affect medical spending?\n\n**Why This Matters**:\n\nThis is the **moral hazard** question in health economics:\n\n- If insurance is free, do people overuse healthcare?\n- Should insurance have cost-sharing (deductibles, co-pays)?\n- What's the right balance between access and efficiency?\n\n**The Challenge**:\n\nObservational studies are biased because:\n\n- People who buy insurance are different (sicker? richer?)\n- Can't separate insurance effect from selection effect\n- Reverse causation: health affects insurance choice\n\n**The RCT Solution:**\n\n**The RAND Health Insurance Experiment (1974-1982):**\n\n- Randomly assigned 5,809 individuals to different insurance plans\n- Plans varied in cost-sharing: 0%, 25%, 50%, 95%, individual deductible\n- Followed families for 3-5 years\n- Measured healthcare utilization and spending\n\n**Why Randomization Enables Causal Inference:**\n\n```\nRandom Assignment → Insurance Plan → Medical Spending\n```\n\nBecause assignment is random:\n\n- Treatment and control groups are identical in expectation\n- No confounding variables\n- Any difference in outcomes is caused by insurance\n- **Selection bias eliminated!**\n\n**Data**: Year 1 data (5,639 observations)\n\n**Variables**:\n\n- `spending`: Total medical expenditure\n- `plan`: Insurance plan assignment\n- Plan indicators: `coins0` (free care), `coins25`, `coins50`, `coins95`, `coinsmixed`, `coinsindiv`\n\n**Method**: Regression with cluster-robust SEs (by family)\n\n::: {#7871c90f .cell execution_count=24}\n``` {.python .cell-code}\n# Load health insurance experiment data\ndata_health = pd.read_stata(GITHUB_DATA_URL + 'AED_HEALTHINSEXP.DTA')\n\n# Use first year data only (as per textbook)\ndata_health_y1 = data_health[data_health['year'] == 1]\n\nprint(f\"Loaded {len(data_health)} total observations\")\nprint(f\"Using Year 1 only: {len(data_health_y1)} observations\")\nprint(f\"\\nInsurance plans: {sorted(data_health_y1['plan'].unique())}\")\nprint(f\"\\nKey variables:\")\nprint(f\"  - plan: Insurance plan assignment (randomized)\")\nprint(f\"  - spending: Total medical spending\")\nprint(f\"  - Plan indicators: coins0, coins25, coins50, coins95, coinsmixed, coinsindiv\")\n\n# Summary statistics by plan\n# MEAN SPENDING BY INSURANCE PLAN\nspending_by_plan = data_health_y1.groupby('plan')['spending'].agg(['mean', 'std', 'count'])\nprint(spending_by_plan)\n\n# Regression with plan indicators\nfit_rct = pf.feols('spending ~ coins25 + coins50 + coins95 + coinsmixed + coinsindiv',\n                data=data_health_y1, vcov={'CRV1': 'idfamily'})\n\n# RCT REGRESSION: SPENDING ON INSURANCE PLANS\nprint(\"Omitted category: Free Care (coins0)\")\nfit_rct.summary()\n\n# F-test for joint significance\n# JOINT F-TEST: DO PLANS MATTER?\nfrom scipy.stats import f as f_dist\ncoef_names = ['coins25', 'coins50', 'coins95', 'coinsmixed', 'coinsindiv']\ncoefs = np.array([fit_rct.coef()[c] for c in coef_names])\nV = fit_rct._vcov\nidx = [list(fit_rct.coef().index).index(c) for c in coef_names]\nV_sub = V[np.ix_(idx, idx)]\nf_val = float(coefs @ np.linalg.inv(V_sub) @ coefs / len(coef_names))\np_val = 1 - f_dist.cdf(f_val, len(coef_names), fit_rct._N - len(fit_rct.coef()))\nprint(f\"H0: All plan coefficients = 0\")\nprint(f\"F-statistic: {f_val:.2f}\")\nprint(f\"p-value: {p_val:.4f}\")\nprint(f\"Conclusion: {'Reject H0' if p_val < 0.05 else 'Fail to reject H0'} at 5% level\")\n\n# CAUSAL INTERPRETATION\nprint(\"✓ Randomized Control Trial enables causal inference\")\nprint(\"✓ Random assignment eliminates selection bias\")\nprint(\"✓ Free care → highest spending (omitted baseline)\")\nprint(\"✓ Higher cost-sharing → lower spending\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLoaded 20203 total observations\nUsing Year 1 only: 5639 observations\n\nInsurance plans: ['25% Coins', '50% Coins', '95%/100% Coins', 'Free Care', 'Indv Deduct', 'Mixed Coins']\n\nKey variables:\n  - plan: Insurance plan assignment (randomized)\n  - spending: Total medical spending\n  - Plan indicators: coins0, coins25, coins50, coins95, coinsmixed, coinsindiv\n                       mean           std  count\nplan                                            \nFree Care       2153.570365   4959.743126   1873\n25% Coins       1396.663070   3458.960029    639\nMixed Coins     1701.874211   4328.165674    480\n50% Coins       1785.845449  11643.607841    374\n95%/100% Coins  1045.820283   2634.823581   1057\nIndv Deduct     1607.071473   3815.953001   1216\nOmitted category: Free Care (coins0)\n###\n\nEstimation:  OLS\nDep. var.: spending\nsample: None = all\nInference:  CRV1\nObservations:  5639\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |      2.5% |    97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|----------:|---------:|\n| Intercept     |   2153.570 |      118.315 |    18.202 |      0.000 |  1921.532 | 2385.608 |\n| coins25       |   -756.907 |      190.041 |    -3.983 |      0.000 | -1129.615 | -384.200 |\n| coins50       |   -367.725 |      618.044 |    -0.595 |      0.552 | -1579.830 |  844.380 |\n| coins95       |  -1107.750 |      150.366 |    -7.367 |      0.000 | -1402.647 | -812.853 |\n| coinsmixed    |   -451.696 |      239.424 |    -1.887 |      0.059 |  -921.254 |   17.862 |\n| coinsindiv    |   -546.499 |      162.151 |    -3.370 |      0.001 |  -864.508 | -228.490 |\n---\nRMSE: 4951.405 R2: 0.007 \nH0: All plan coefficients = 0\nF-statistic: 11.39\np-value: 0.0000\nConclusion: Reject H0 at 5% level\n✓ Randomized Control Trial enables causal inference\n✓ Random assignment eliminates selection bias\n✓ Free care → highest spending (omitted baseline)\n✓ Higher cost-sharing → lower spending\n```\n:::\n:::\n\n\n> **Key Concept 13.7: Randomized Control Trials as the Gold Standard**\n>\n> In a **randomized control trial (RCT)**, subjects are randomly assigned to treatment and control groups. Random assignment ensures the groups are comparable on both observed and unobserved characteristics, eliminating selection bias and omitted variable concerns. The RAND experiment showed that better insurance coverage increases healthcare utilization.\n\n### **Interpreting the RCT Results**\n\n**Key Findings:**\n\n1. **Insurance Plans Matter**: F-test strongly rejects H₀ (F = 11.39, p < 0.001)\n - Different insurance plans lead to significantly different spending\n - Cost-sharing reduces medical utilization\n\n2. **Spending by Plan** (relative to Free Care):\n\n Free Care (baseline): Highest spending\n\n - People use more healthcare when it's free\n\n Cost-sharing plans (25%, 50%, 95%): Lower spending\n\n - Higher cost-sharing → less utilization\n - This is **moral hazard**: insurance affects behavior\n\n3. **Why This is Causal**:\n\n **Randomization**: Families randomly assigned to plans\n\n - No selection bias (unlike observational studies)\n - Treated and control groups are balanced on all characteristics\n\n **Experimental control**: RAND ensured compliance\n\n **Large sample**: 5,639 person-years in first year\n\n4. **R² is Low (0.007)** - This is Actually Good!\n - Most variation in spending is random (health shocks)\n - Insurance explains small fraction (as expected)\n - But effects are **statistically significant** and **policy-relevant**\n\n**Policy Implications:**\n\n**Trade-offs in health insurance design:**\n\n **Free care**:\n\n- More utilization\n- Better access for poor\n- But: higher costs, potential overuse\n\n **Cost-sharing**:\n\n- Lower spending\n- Reduced \"unnecessary\" care\n- But: may also reduce necessary care (problematic!)\n\n**The RAND Health Insurance Experiment (HIE) Legacy:**\n\nThis 1970s experiment fundamentally shaped U.S. health policy:\n\n- Informed Medicare/Medicaid design\n- Influenced Affordable Care Act\n- Demonstrated feasibility of large-scale RCTs\n- Showed moral hazard exists but is moderate\n\n**Limitations:**\n\n 1970s data (healthcare has changed)\n Selected sites (may not generalize)\n Ethical concerns (denying some families full coverage)\n\n**Modern Relevance:**\n\nThe fundamental trade-off remains:\n\n- Universal free care (equity) vs\n- Cost-sharing (efficiency)\n\n## 13.6 Health Care Access (Difference-in-Differences)\n\nCausal inference using DiD methodology.\n\n### **Case Study: Health Care Access and Child Nutrition (Difference-in-Differences)**\n\n**The Policy Question**: Does building health clinics improve child health outcomes?\n\n**The Setting**: Rural South Africa, 1990s\n\nAfter apartheid ended (1994), the new government built primary health care clinics in underserved rural areas. Some communities got many new clinics (high treatment), others got few (low treatment).\n\n**The Challenge**: Simple before/after comparison is biased because:\n\n- Child health was improving nationally due to many factors\n- Communities that got clinics may have been different\n- Cannot separate clinic effect from other trends\n\n**The Difference-in-Differences Solution:**\n\n**Key Idea**: Compare change in treated communities to change in control communities\n\n$$\\text{DiD} = (\\text{Treated}_{after} - \\text{Treated}_{before}) - (\\text{Control}_{after} - \\text{Control}_{before})$$\n\n**Why This Works:**\n\nThe first difference removes:\n\n- Permanent differences between communities\n- Baseline health levels\n\nThe second difference removes:\n\n- Common time trends\n- National-level changes\n\n**What remains**: The differential impact of clinic access!\n\n**The Design:**\n\n| Group | 1993 (Pre) | 1998 (Post) | Change |\n|-------|------------|-------------|---------|\n| High Treatment | $\\bar{Y}_{T,0}$ | $\\bar{Y}_{T,1}$ | $\\Delta_T$ |\n| Low Treatment | $\\bar{Y}_{C,0}$ | $\\bar{Y}_{C,1}$ | $\\Delta_C$ |\n\nDiD = $\\Delta_T - \\Delta_C$\n\n**Data**: 1,071 children aged 0-4 in rural KwaZulu-Natal\n\n**Outcome**: `waz` (weight-for-age z-score, measure of nutrition)\n\n**Method**: DiD regression with cluster-robust SEs (by community)\n\n::: {#26346450 .cell execution_count=25}\n``` {.python .cell-code}\n# Load health care access data (South Africa)\ndata_access = pd.read_stata(GITHUB_DATA_URL + 'AED_HEALTHACCESS.DTA')\n\nprint(f\"Loaded {len(data_access)} observations (South African children 0-4)\")\nprint(f\"\\nDifference-in-Differences Setup:\")\nprint(f\"  - Treatment: High treatment communities (hightreat=1)\")\nprint(f\"  - Control: Low treatment communities (hightreat=0)\")\nprint(f\"  - Pre period: 1993 (post=0)\")\nprint(f\"  - Post period: 1998 (post=1)\")\nprint(f\"  - Outcome: waz (weight-for-age z-score)\")\n\n# Summary statistics by treatment and time\n# MEAN WEIGHT-FOR-AGE Z-SCORE (WAZ)\ndid_table = data_access.groupby(['hightreat', 'post'])['waz'].agg(['mean', 'count'])\nprint(did_table)\n\n# Calculate DiD manually\npre_control = data_access[(data_access['hightreat']==0) & (data_access['post']==0)]['waz'].mean()\npost_control = data_access[(data_access['hightreat']==0) & (data_access['post']==1)]['waz'].mean()\npre_treat = data_access[(data_access['hightreat']==1) & (data_access['post']==0)]['waz'].mean()\npost_treat = data_access[(data_access['hightreat']==1) & (data_access['post']==1)]['waz'].mean()\n\ndid_estimate = (post_treat - pre_treat) - (post_control - pre_control)\n\nprint(f\"\\nManual DiD calculation:\")\nprint(f\"  Control change: {post_control:.3f} - {pre_control:.3f} = {post_control - pre_control:.3f}\")\nprint(f\"  Treated change: {post_treat:.3f} - {pre_treat:.3f} = {post_treat - pre_treat:.3f}\")\nprint(f\"  DiD estimate: ({post_treat:.3f} - {pre_treat:.3f}) - ({post_control:.3f} - {pre_control:.3f}) = {did_estimate:.3f}\")\n\n# DiD regression\nfit_did = pf.feols('waz ~ hightreat + post + postXhigh', data=data_access, vcov={'CRV1': 'idcommunity'})\n\n# DiD REGRESSION\nfit_did.summary()\n\n# INTERPRETATION\nprint(f\"DiD coefficient (postXhigh): {fit_did.coef()['postXhigh']:.3f}\")\nprint(f\"Matches manual calculation: {did_estimate:.3f} ✓\")\nprint(f\"\\nCausal interpretation:\")\nprint(f\"Clinic access improved child nutrition by {fit_did.coef()['postXhigh']:.2f} standard deviations\")\nprint(f\"This is a {'statistically significant' if fit_did.pvalue()['postXhigh'] < 0.05 else 'not significant'} effect\")\nprint(f\"\\nCluster-robust SEs by community account for within-community correlation\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLoaded 1071 observations (South African children 0-4)\n\nDifference-in-Differences Setup:\n  - Treatment: High treatment communities (hightreat=1)\n  - Control: Low treatment communities (hightreat=0)\n  - Pre period: 1993 (post=0)\n  - Post period: 1998 (post=1)\n  - Outcome: waz (weight-for-age z-score)\n                    mean  count\nhightreat post                 \n0.0       0.0  -0.414185    325\n          1.0  -0.069097    288\n1.0       0.0  -0.545244    246\n          1.0   0.321462    212\n\nManual DiD calculation:\n  Control change: -0.069 - -0.414 = 0.345\n  Treated change: 0.321 - -0.545 = 0.867\n  DiD estimate: (0.321 - -0.545) - (-0.069 - -0.414) = 0.522\n###\n\nEstimation:  OLS\nDep. var.: waz\nsample: None = all\nInference:  CRV1\nObservations:  1071\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |   2.5% |   97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|-------:|--------:|\n| Intercept     |     -0.414 |        0.115 |    -3.597 |      0.001 | -0.645 |  -0.183 |\n| hightreat     |     -0.131 |        0.197 |    -0.666 |      0.508 | -0.526 |   0.264 |\n| post          |      0.345 |        0.137 |     2.517 |      0.015 |  0.070 |   0.620 |\n| postXhigh     |      0.522 |        0.235 |     2.217 |      0.031 |  0.050 |   0.994 |\n---\nRMSE: 1.555 R2: 0.04 \nDiD coefficient (postXhigh): 0.522\nMatches manual calculation: 0.522 ✓\n\nCausal interpretation:\nClinic access improved child nutrition by 0.52 standard deviations\nThis is a statistically significant effect\n\nCluster-robust SEs by community account for within-community correlation\n```\n:::\n:::\n\n\n> **Key Concept 13.8: Difference-in-Differences for Causal Inference**\n>\n> **Difference-in-differences (DiD)** compares changes over time between treatment and control groups. The key assumption is **parallel trends**: both groups would have followed the same trajectory absent treatment. DiD removes time-invariant confounders and common time effects, isolating the treatment effect.\n\n### **Interpreting the DiD Results**\n\n**Key Findings:**\n\n1. **Treatment Effect**: DiD coefficient ≈ 0.52 standard deviations\n - Clinic access improved child weight-for-age by 0.52 SD\n - **Statistically significant** (p = 0.027 < 0.05)\n - Large and meaningful effect size\n\n2. **Verification**: Manual calculation matches regression\n - This confirms our DiD estimate is correct\n - The interaction term `postXhigh` captures the treatment effect\n\n3. **Effect Size Interpretation**:\n\n 0.52 SD improvement means:\n\n - Moving from 25th percentile → 45th percentile in weight distribution\n - Substantial reduction in malnutrition\n - Comparable to 6-12 months of normal growth\n\n**Why This is Causal (Under Assumptions):**\n\nThe DiD design requires **parallel trends assumption**:\n\n- Without treatment, treated and control groups would have followed parallel trends\n- Treatment assignment (clinic placement) is exogenous\n- No other interventions differentially affected treated communities\n\n**Evidence for validity:**\n\n- Communities were similar at baseline\n- Clinic placement based on need, not outcomes\n- No other major health programs during this period\n\n**Policy Implications:**\n\n **Primary health care access works**: Even basic clinics improve child health\n\n **Targeting matters**: High-treatment communities saw larger benefits\n\n **Cost-effective**: Clinic construction is relatively inexpensive\n\n**External Validity:**\n\nThese results from rural South Africa likely generalize to other:\n\n- Low-income settings\n- Areas with limited health infrastructure\n- Populations with high baseline malnutrition\n\n**Limitations:**\n\n Short-term effects (1998 vs 1993)\n Self-reported data (possible measurement error)\n Cluster-level treatment (less statistical power)\n\n## 13.7 Political Incumbency (Regression Discontinuity)\n\nCausal inference using RD design.\n\n### **Case Study: The Incumbency Advantage in U.S. Senate Elections**\n\n**The Question**: Does being an incumbent senator give you an advantage in the next election?\n\n**The Challenge**: Simple comparison of incumbents vs challengers is biased because:\n\n- Incumbents are generally stronger candidates (that's why they won before!)\n- Districts that elect incumbents may be different\n- Selection bias confounds the causal effect\n\n**The Regression Discontinuity Solution:**\n\n**Key Insight**: Compare candidates who **barely won** to those who **barely lost**.\n\nAt the threshold (vote margin ≈ 0):\n\n- Winners and losers are essentially identical in quality\n- Only difference: winners become incumbents\n- This creates **quasi-random assignment** to incumbency status\n\n**The Design:**\n\n```\nRunning variable: margin (vote share in election t - 50%)\nThreshold: margin = 0\nTreatment: win = 1 if margin > 0\n\nOutcome: vote (vote share in election t+1)\n```\n\n**Visual Intuition:**\n\nIf there's an incumbency advantage, we should see a **jump** in next-election vote share exactly at margin = 0:\n\n```\nNext Vote % ▲\n │\n 60─────┤ •\n │ • ← Jump = incumbency advantage\n 50─────┤ •\n │ •\n 40─────┤•\n │\n └──────────────────→\n -10 0 +10\n Lost │ Won\n Margin\n```\n\n**Data**: 1,390 U.S. Senate elections (1914-2010)\n\n**Method**: RD with linear control for margin\n\n::: {#b4c94211 .cell execution_count=26}\n``` {.python .cell-code}\n# Load incumbency data (U.S. Senate elections)\ndata_incumb = pd.read_stata(GITHUB_DATA_URL + 'AED_INCUMBENCY.DTA')\n\nprint(f\"Loaded {len(data_incumb)} Senate elections (1914-2010)\")\nprint(f\"\\nRegression Discontinuity Setup:\")\nprint(f\"  - Running variable: margin (vote margin in election t)\")\nprint(f\"  - Threshold: margin = 0 (barely won vs barely lost)\")\nprint(f\"  - Outcome: vote (vote share in election t+1)\")\nprint(f\"  - win: Indicator for margin > 0\")\n\n# Summary statistics\ndata_incumb[['vote', 'margin', 'win']].describe()\n\n# Keep only elections with non-missing vote in t+1\ndata_rd = data_incumb[data_incumb['vote'].notna()].copy()\nprint(f\"\\nObservations with outcome data: {len(data_rd)}\")\n\n# RD regression (linear)\nfit_rd = pf.feols('vote ~ win + margin', data=data_rd, vcov='HC1')\n\n# REGRESSION DISCONTINUITY ESTIMATION\nfit_rd.summary()\n\n# INCUMBENCY ADVANTAGE\nprint(f\"RD estimate (win coefficient): {fit_rd.coef()['win']:.3f}\")\nci = fit_rd.confint()\nprint(f\"95% CI: [{ci.loc['win', '2.5%']:.3f}, {ci.loc['win', '97.5%']:.3f}]\")\nprint(f\"\\nInterpretation:\")\nprint(f\"Barely winning vs barely losing increases vote share in next election by {fit_rd.coef()['win']:.1f}%\")\nprint(f\"This is the causal effect of incumbency\")\nprint(f\"\\nWhy causal? At the threshold (margin≈0), winning is quasi-random\")\nprint(f\"Candidates just above/below threshold are similar in all respects except incumbency status\")\n\n# Visualization note\n# RD PLOT\nprint(\"To visualize discontinuity:\")\n# - Bin observations by margin\n# - Plot mean vote in next election vs margin\n# - Should see jump at margin=0\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLoaded 1390 Senate elections (1914-2010)\n\nRegression Discontinuity Setup:\n  - Running variable: margin (vote margin in election t)\n  - Threshold: margin = 0 (barely won vs barely lost)\n  - Outcome: vote (vote share in election t+1)\n  - win: Indicator for margin > 0\n\nObservations with outcome data: 1297\n###\n\nEstimation:  OLS\nDep. var.: vote\nsample: None = all\nInference:  HC1\nObservations:  1297\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |   2.5% |   97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|-------:|--------:|\n| Intercept     |     47.331 |        0.526 |    89.945 |      0.000 | 46.299 |  48.363 |\n| win           |      4.785 |        0.860 |     5.565 |      0.000 |  3.098 |   6.471 |\n| margin        |      0.348 |        0.017 |    20.422 |      0.000 |  0.315 |   0.381 |\n---\nRMSE: 11.767 R2: 0.578 \nRD estimate (win coefficient): 4.785\n95% CI: [3.098, 6.471]\n\nInterpretation:\nBarely winning vs barely losing increases vote share in next election by 4.8%\nThis is the causal effect of incumbency\n\nWhy causal? At the threshold (margin≈0), winning is quasi-random\nCandidates just above/below threshold are similar in all respects except incumbency status\nTo visualize discontinuity:\n```\n:::\n:::\n\n\n> **Key Concept 13.9: Regression Discontinuity Design**\n>\n> **Regression discontinuity (RD)** exploits sharp cutoffs in treatment assignment. Units just above and below the threshold are nearly identical in all respects except treatment status, creating a **quasi-experiment**. In U.S. Senate elections, barely winning provides an incumbency advantage of approximately 5–7 percentage points.\n\n### **Interpreting the RD Results**\n\n**Key Findings:**\n\n1. **Incumbency Advantage**: ≈ 4.8 percentage points\n - Barely winning vs barely losing increases vote share by ~4.8% in next election\n - This is **highly statistically significant** (p < 0.001)\n - Robust across different specifications\n\n2. **Why This is Causal**:\n\n At the threshold (margin ≈ 0), winning is **quasi-random**:\n\n - Candidates just above and below 50% are nearly identical\n - Only difference is incumbency status\n - No selection bias (unlike comparing all winners vs all losers)\n\n3. **Magnitude in Context**:\n - 4.8% advantage is **substantial** in close elections\n - Many Senate races decided by < 5%\n - Could explain why incumbents rarely lose\n\n**What Drives the Incumbency Advantage?**\n\nPossible mechanisms:\n\n- **Name recognition**: Incumbents are well-known\n- **Fundraising**: Easier to raise money as incumbent\n- **Media coverage**: Senators get more press\n- **Constituent services**: Can deliver benefits to voters\n- **Experience**: Learn how to campaign effectively\n\n**Policy Implications:**\n\n- Incumbency advantage creates barriers to electoral competition\n- May reduce democratic accountability\n- Term limits could level the playing field\n- Campaign finance reform might reduce fundraising advantage\n\n**RD Design Advantages:**\n\n No need to control for other variables (identification at threshold)\n Transparent and credible\n Robust to model specification\n\n**Limitations:**\n\n Local estimate (only applies near threshold)\n May not generalize to landslide winners/losers\n Assumes no manipulation of vote margin (reasonable for U.S. Senate)\n\n## 13.8 Institutions and GDP (Instrumental Variables)\n\nCausal inference using IV/2SLS.\n\n### **Case Study: Do Institutions Cause Economic Growth?**\n\n**The Fundamental Question**: Why are some countries rich and others poor?\n\n**The Endogeneity Problem:**\n\nIf we simply regress GDP on institutions quality, we get:\n\n- **Reverse causation**: Rich countries can afford better institutions\n- **Omitted variables**: Culture, geography, history all affect both\n- **Measurement error**: How do we measure \"institutions quality\"?\n\nAll of these bias OLS estimates, making causal inference impossible.\n\n**The Instrumental Variables Solution:**\n\nAcemoglu, Johnson, and Robinson (2001) use **settler mortality** as an instrument:\n\n**The Historical Argument:**\n\n1. In the 1600s-1800s, European colonizers faced different disease environments\n2. High mortality areas (Africa, tropical Americas) → extractive institutions\n - Europeans didn't settle permanently\n - Built institutions to extract resources (slavery, forced labor)\n3. Low mortality areas (North America, Australia) → settler institutions\n - Europeans settled permanently\n - Built institutions to protect their own property rights\n\n**Why This Works as an Instrument:**\n\n **Relevant**: Settler mortality strongly predicts colonial institutions\n **Exogenous**: Malaria in 1700s doesn't directly affect GDP in 2000s\n\n**Data**: 64 former colonies\n\n**Variables**:\n\n- `logpgp95`: Log GDP per capita 1995 (outcome)\n- `avexpr`: Protection against expropriation (institutions quality, 0-10)\n- `logem4`: Log settler mortality rate (instrument)\n\n**Method**: Two-Stage Least Squares (2SLS/IV)\n\n::: {#addd386d .cell execution_count=27}\n``` {.python .cell-code}\n# Load institutions data (cross-country)\ndata_inst = pd.read_stata(GITHUB_DATA_URL + 'AED_INSTITUTIONS.DTA')\n\nprint(f\"Loaded {len(data_inst)} countries\")\nprint(f\"\\nInstrumental Variables Setup:\")\nprint(f\"  - Outcome: logpgp95 (log GDP per capita 1995)\")\nprint(f\"  - Endogenous regressor: avexpr (institutions quality)\")\nprint(f\"  - Instrument: logem4 (log settler mortality)\")\nprint(f\"\\nKey idea: Settler mortality affected colonial institutions,\")\nprint(f\"which persist to affect GDP today, but mortality doesn't\")\nprint(f\"directly affect modern GDP\")\n\n# Summary statistics\ndata_inst[['logpgp95', 'avexpr', 'logem4']].describe()\n\n# OLS (biased - endogeneity problem)\nfit_ols = pf.feols('logpgp95 ~ avexpr', data=data_inst, vcov='HC1')\n\n# OLS REGRESSION (BIASED)\nfit_ols.summary()\nprint(f\"\\nOLS coefficient: {fit_ols.coef()['avexpr']:.3f}\")\nprint(\"⚠️ This is biased due to endogeneity (omitted variables, reverse causation)\")\n\n# First stage\nfit_first = pf.feols('avexpr ~ logem4', data=data_inst, vcov='HC1')\n\n# FIRST STAGE: INSTITUTIONS ~ SETTLER MORTALITY\nfit_first.summary()\nfirst_f = fit_first.tstat()['logem4']**2\nprint(f\"\\nFirst stage F-statistic: {first_f:.2f}\")\nprint(f\"Rule of thumb: F > 10 for strong instrument\")\nprint(f\"Instrument strength: {'Strong ✓' if first_f > 10 else 'Weak ⚠️'}\")\n\n# 2SLS using pyfixest IV syntax\n# TWO-STAGE LEAST SQUARES (2SLS)\n\n# Single-call IV estimation: y ~ exog | endog ~ instrument\nfit_iv = pf.feols('logpgp95 ~ 1 | avexpr ~ logem4', data=data_inst, vcov='HC1')\n\nprint(\"\\nIV/2SLS estimation:\")\nfit_iv.summary()\n\n# COMPARISON: OLS vs IV\nprint(f\"OLS coefficient: {fit_ols.coef()['avexpr']:.3f}\")\nprint(f\"IV/2SLS coefficient: {fit_iv.coef()['avexpr']:.3f}\")\nprint(f\"\\nDifference: {fit_iv.coef()['avexpr'] - fit_ols.coef()['avexpr']:.3f}\")\nprint(f\"\\nIV estimate is larger → OLS has attenuation bias\")\nprint(f\"(measurement error and omitted variables bias OLS toward zero)\")\n\n# CAUSAL INTERPRETATION\nprint(f\"1-unit improvement in institutions → {fit_iv.coef()['avexpr']:.2f} increase in log GDP\")\nprint(f\"Exponentiating: {np.exp(fit_iv.coef()['avexpr']):.2f}x increase in GDP level\")\nprint(f\"\\n✓ This is a causal estimate (under IV assumptions)\")\nprint(f\"✓ Instrument (settler mortality) is:\")\nprint(f\"  - Relevant: Strong first stage (F = {first_f:.1f})\")\nprint(f\"  - Exogenous: Mortality in 1700s doesn't directly affect modern GDP\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLoaded 64 countries\n\nInstrumental Variables Setup:\n  - Outcome: logpgp95 (log GDP per capita 1995)\n  - Endogenous regressor: avexpr (institutions quality)\n  - Instrument: logem4 (log settler mortality)\n\nKey idea: Settler mortality affected colonial institutions,\nwhich persist to affect GDP today, but mortality doesn't\ndirectly affect modern GDP\n###\n\nEstimation:  OLS\nDep. var.: logpgp95\nsample: None = all\nInference:  HC1\nObservations:  64\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |   2.5% |   97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|-------:|--------:|\n| Intercept     |      4.660 |        0.320 |    14.558 |      0.000 |  4.020 |   5.300 |\n| avexpr        |      0.522 |        0.050 |    10.458 |      0.000 |  0.422 |   0.622 |\n---\nRMSE: 0.702 R2: 0.54 \n\nOLS coefficient: 0.522\n⚠️ This is biased due to endogeneity (omitted variables, reverse causation)\n###\n\nEstimation:  OLS\nDep. var.: avexpr\nsample: None = all\nInference:  HC1\nObservations:  64\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |   2.5% |   97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|-------:|--------:|\n| Intercept     |      9.341 |        0.704 |    13.264 |      0.000 |  7.934 |  10.749 |\n| logem4        |     -0.607 |        0.150 |    -4.040 |      0.000 | -0.907 |  -0.307 |\n---\nRMSE: 1.245 R2: 0.27 \n\nFirst stage F-statistic: 16.32\nRule of thumb: F > 10 for strong instrument\nInstrument strength: Strong ✓\n\nIV/2SLS estimation:\n###\n\nEstimation:  IV\nDep. var.: logpgp95\nsample: None = all\nInference:  HC1\nObservations:  64\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |   2.5% |   97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|-------:|--------:|\n| Intercept     |      1.910 |        1.193 |     1.601 |      0.114 | -0.475 |   4.294 |\n| avexpr        |      0.944 |        0.179 |     5.278 |      0.000 |  0.587 |   1.302 |\n---\n\nOLS coefficient: 0.522\nIV/2SLS coefficient: 0.944\n\nDifference: 0.422\n\nIV estimate is larger → OLS has attenuation bias\n(measurement error and omitted variables bias OLS toward zero)\n1-unit improvement in institutions → 0.94 increase in log GDP\nExponentiating: 2.57x increase in GDP level\n\n✓ This is a causal estimate (under IV assumptions)\n✓ Instrument (settler mortality) is:\n  - Relevant: Strong first stage (F = 16.3)\n  - Exogenous: Mortality in 1700s doesn't directly affect modern GDP\n```\n:::\n:::\n\n\n> **Key Concept 13.10: Instrumental Variables and Two-Stage Least Squares**\n>\n> When a regressor is **endogenous** (correlated with the error term), OLS is biased. **Instrumental variables (IV)** use an instrument that is correlated with the endogenous regressor but not directly with the outcome. Two-stage least squares (2SLS) first predicts the endogenous variable, then uses these predictions in the second-stage regression.\n\n### **Interpreting the IV Results**\n\n**Key Findings:**\n\n1. **OLS vs IV Comparison**:\n - OLS coefficient: ≈ 0.52 (biased downward)\n - IV coefficient: ≈ 0.94 (causal estimate)\n - IV estimate is **80% larger** than OLS!\n\n2. **Why the Difference?**\n\n **Attenuation bias**: OLS is biased toward zero due to:\n\n - Measurement error in institutions quality\n - Omitted variables (culture, geography)\n - Reverse causation (rich countries build better institutions)\n\n3. **Economic Interpretation**:\n - 1-unit improvement in institutions → 0.94 increase in log GDP\n - Exponentiating: $e^{0.94} \\approx 2.56$ → **156% increase in GDP level**\n - This is a **massive effect**!\n\n4. **Instrument Validity**:\n\n **Relevance**: First stage F = 16.3 > 10 (strong instrument)\n\n **Exogeneity**: Settler mortality in 1700s doesn't directly affect modern GDP\n\n The instrument works through this channel:\n ```\n Settler mortality → Colonial institutions → Modern institutions → GDP\n ```\n\n High mortality areas got \"extractive\" institutions (exploitation).\n Low mortality areas got \"settler\" institutions (property rights, democracy).\n\n**Policy Implications:**\n\nInstitutions are not just correlated with prosperity—they **cause** it. Countries can escape poverty by:\n\n- Strengthening property rights\n- Reducing corruption\n- Improving rule of law\n- Building democratic accountability\n\n**Caveat**: These results apply to former colonies. Institutional change is slow and difficult.\n\n## 13.9 From Raw Data to Final Data\n\nBest practices for data preparation and cleaning.\n\n### **Why Data Wrangling Matters**\n\nReal-world econometric analysis spends **60-80% of time** on data preparation:\n\n- Reading data from various sources\n- Merging multiple datasets\n- Cleaning errors and outliers\n- Transforming variables\n- Creating new variables\n\n**Common Data Challenges:**\n\n1. **Missing values**: How to handle? Drop, impute, or model explicitly?\n2. **Outliers**: Real extreme values or data errors?\n3. **Inconsistent units**: Converting currencies, adjusting for inflation\n4. **Different time frequencies**: Monthly data merged with quarterly\n5. **Measurement error**: Misreported values, typos\n\n**Best Practices:**\n\n- **Document everything**: Keep track of all cleaning steps\n- **Preserve raw data**: Never overwrite original files\n- **Reproducibility**: Write scripts (not manual Excel edits!)\n- **Validation**: Check summary statistics before and after cleaning\n- **Transparency**: Report how many observations dropped and why\n\n::: {#e2c251eb .cell execution_count=28}\n``` {.python .cell-code}\n# Demonstrate reading different file formats\n# Data Reading Examples\n\n# Stata files\nprint(\"\\n1. Reading Stata files (.dta):\")\n# data = pd.read_stata('file.dta')\n\n# CSV files\nprint(\"\\n2. Reading CSV files:\")\n# data = pd.read_csv('file.csv')\n\n# Excel files\nprint(\"\\n3. Reading Excel files:\")\n# data = pd.read_excel('file.xlsx')\n\n# Example: merge operations\n# DATA MERGING EXAMPLE\n\ndf1 = pd.DataFrame({'id': [1, 2, 3], 'value_a': [10, 20, 30]})\ndf2 = pd.DataFrame({'id': [1, 2, 4], 'value_b': [100, 200, 400]})\n\nprint(\"\\nDataFrame 1:\")\nprint(df1)\nprint(\"\\nDataFrame 2:\")\nprint(df2)\n\nmerged = pd.merge(df1, df2, on='id', how='inner')\nprint(\"\\nMerged (inner join):\")\nprint(merged)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n1. Reading Stata files (.dta):\n\n2. Reading CSV files:\n\n3. Reading Excel files:\n\nDataFrame 1:\n   id  value_a\n0   1       10\n1   2       20\n2   3       30\n\nDataFrame 2:\n   id  value_b\n0   1      100\n1   2      200\n2   4      400\n\nMerged (inner join):\n   id  value_a  value_b\n0   1       10      100\n1   2       20      200\n```\n:::\n:::\n\n\n::: {#73595d53 .cell execution_count=29}\n``` {.python .cell-code}\n# Data cleaning examples\n\n# Example dataset\ndf_dirty = pd.DataFrame({\n    'age': [25, 30, -5, 200, 35],\n    'income': [50000, 60000, None, 75000, 80000],\n    'gender': ['M', 'F', 'm', 'Female', 'M']\n})\n\nprint(\"\\nOriginal data (with errors):\")\nprint(df_dirty)\n\n# Clean age (remove impossible values)\ndf_clean = df_dirty.copy()\ndf_clean.loc[df_clean['age'] < 0, 'age'] = np.nan\ndf_clean.loc[df_clean['age'] > 120, 'age'] = np.nan\n\n# Fill missing income with median\ndf_clean['income'].fillna(df_clean['income'].median(), inplace=True)\n\n# Standardize gender coding\ndf_clean['gender'] = df_clean['gender'].str.upper().str[0]\n\nprint(\"\\nCleaned data:\")\nprint(df_clean)\n\nprint(\"\\n✓ Key cleaning steps:\")\n# 1. Detect and handle impossible values (age < 0, age > 120)\n# 2. Impute missing values (median for income)\n# 3. Standardize categorical variables (gender)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nOriginal data (with errors):\n   age   income  gender\n0   25  50000.0       M\n1   30  60000.0       F\n2   -5      NaN       m\n3  200  75000.0  Female\n4   35  80000.0       M\n\nCleaned data:\n    age   income gender\n0  25.0  50000.0      M\n1  30.0  60000.0      F\n2   NaN  67500.0      M\n3   NaN  75000.0      F\n4  35.0  80000.0      M\n\n✓ Key cleaning steps:\n```\n:::\n:::\n\n\n## Key Takeaways\n\n### School Performance and Socioeconomic Factors (Case Study 13.1)\n\n- School performance (API) is strongly associated with socioeconomic factors, particularly **parent education**\n- Bivariate analysis shows ~80 API points per year of parent education\n- Multiple regression maintains a strong effect (~74 points) after controlling for meals, English learners, year-round schools, and teacher quality\n- High correlations among socioeconomic variables make it difficult to isolate individual effects\n- California's \"similar schools\" index controls for socioeconomic characteristics\n\n### Cobb-Douglas Production Function and Returns to Scale (Case Study 13.2)\n\n- Natural logarithm transformation converts the nonlinear Cobb-Douglas model into a linear OLS form\n- Estimated **capital elasticity ≈ 0.23** and **labor elasticity ≈ 0.81**\n- Data support **constant returns to scale** (elasticities sum to 1.040, F-test p = 0.636)\n- HAC-robust standard errors account for time series autocorrelation\n- Predictions require retransformation bias correction when using log models\n\n### Phillips Curve and Omitted Variables Bias (Case Study 13.3)\n\n- Original Phillips curve showed a negative unemployment–inflation trade-off pre-1970\n- The relationship **broke down post-1970** — a classic example of model misspecification\n- **Augmented Phillips curve** adding expected inflation resolves the breakdown (coefficient ≈ 1)\n- The sign reversal demonstrates **omitted variables bias**: excluding a correlated variable biases coefficients\n- Policy implication: limited long-run unemployment–inflation trade-off\n\n### Advanced Causal Methods (Case Studies 13.4–13.8)\n\n- **Log-log models and cluster-robust SEs (13.4):** Automobile efficiency gains offset by larger vehicles; clustering by manufacturer accounts for within-group correlation\n- **Randomized control trials (13.5):** RAND experiment shows better insurance increases healthcare spending; random assignment eliminates selection bias\n- **Difference-in-differences (13.6):** South Africa clinic access improved child health; key assumption is parallel trends\n- **Regression discontinuity (13.7):** Political incumbency provides ~5–7% vote share advantage; exploits sharp cutoffs\n- **Instrumental variables (13.8):** Better institutions causally increase GDP; instruments address endogeneity\n\n### Data Preparation and Practical Workflow (Case Study 13.9)\n\n- Real data analysis requires extensive data carpentry — often 60–80% of project time\n- Reading data from multiple formats: `.csv`, `.xlsx`, `.dta`, `.sav`\n- Merging, recoding, cleaning, and validation are essential before regression analysis\n\n### General Lessons from Multiple Regression Case Studies\n\n- Multiple regression isolates **partial effects** while controlling for other variables\n- Choice of standard errors is critical: HC1 (cross-section), cluster-robust (grouped), HAC (time series)\n- Log transformations enable estimation of **elasticities** and nonlinear relationships\n- Omitted variables bias can **reverse coefficient signs** and lead to incorrect conclusions\n- Causal inference requires additional identification strategies beyond OLS\n\n---\n\n**Python Libraries and Code:**\n\nThis single code block reproduces the core workflow of Chapter 13. It is self-contained — copy it into an empty notebook and run it to review six case studies spanning production functions, omitted variables bias, randomized experiments, difference-in-differences, regression discontinuity, and instrumental variables.\n\n```python\n# =============================================================================\n# CHAPTER 13 CHEAT SHEET: Case Studies for Multiple Regression\n# =============================================================================\n\n# --- Libraries ---\nimport numpy as np                        # numerical operations and log transforms\nimport pandas as pd                       # data loading and manipulation\nimport matplotlib.pyplot as plt           # creating plots and visualizations\nimport pyfixest as pf                     # fast OLS/IV estimation\nfrom scipy import stats                   # F-distribution for hypothesis tests\n# !pip install pyfixest\n\n# --- Data source ---\nURL = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/\"\n\n# =============================================================================\n# STEP 1: Cobb-Douglas Production Function — log-linearize and estimate\n# =============================================================================\n# Taking logs converts Q = A*K^alpha*L^beta into a linear model estimable by OLS\ndata_cobb = pd.read_stata(URL + \"AED_COBBDOUGLAS.DTA\")\ndata_cobb['lnq'] = np.log(data_cobb['q'])\ndata_cobb['lnk'] = np.log(data_cobb['k'])\ndata_cobb['lnl'] = np.log(data_cobb['l'])\n\n# OLS with HAC standard errors (time series: autocorrelation + heteroskedasticity)\ndata_cobb['_time'] = range(len(data_cobb))\nfit_cobb = pf.feols('lnq ~ lnk + lnl', data=data_cobb,\n                    vcov='NW', vcov_kwargs={'time_id': '_time', 'lag': 3})\n\nalpha = fit_cobb.coef()['lnk']   # capital elasticity\nbeta  = fit_cobb.coef()['lnl']   # labor elasticity\n\nprint(f\"Capital elasticity α = {alpha:.3f}, Labor elasticity β = {beta:.3f}\")\nprint(f\"Sum α + β = {alpha + beta:.3f}  (≈1 → constant returns to scale)\")\nprint(f\"R² = {fit_cobb._r2:.4f}\")\nfit_cobb.summary()\n\n# F-test for constant returns to scale: H0: α + β = 1\ndata_cobb['lnq_l'] = data_cobb['lnq'] - data_cobb['lnl']\ndata_cobb['lnk_l'] = data_cobb['lnk'] - data_cobb['lnl']\nfit_r = pf.feols('lnq_l ~ lnk_l', data=data_cobb)\nrss_unr = np.sum(fit_cobb._u_hat**2)\nrss_r = np.sum(fit_r._u_hat**2)\ndf_res = fit_cobb._N - len(fit_cobb.coef())\nf_stat = ((rss_r - rss_unr) / 1) / (rss_unr / df_res)\np_val  = 1 - stats.f.cdf(f_stat, 1, df_res)\nprint(f\"CRS test: F = {f_stat:.2f}, p = {p_val:.3f} → {'Fail to reject' if p_val > 0.05 else 'Reject'} CRS\")\n\n# =============================================================================\n# STEP 2: Phillips Curve — omitted variables bias reverses the sign\n# =============================================================================\n# Pre-1970 the trade-off works; post-1970 it breaks because expected inflation\n# is omitted — a textbook demonstration of OVB\ndata_phil = pd.read_stata(URL + \"AED_PHILLIPS.DTA\")\n\n# Pre-1970: classic negative relationship\npre = data_phil[data_phil['year'] < 1970]\npre = pre.copy()\npre['_time'] = range(len(pre))\nm_pre = pf.feols('inflgdp ~ urate', data=pre,\n                 vcov='NW', vcov_kwargs={'time_id': '_time', 'lag': 3})\nprint(f\"\\nPre-1970 slope: {m_pre.coef()['urate']:.3f}  (negative → classic Phillips curve)\")\n\n# Post-1970: sign flips due to omitted expected inflation\npost = data_phil[data_phil['year'] >= 1970]\npost = post.copy()\npost['_time'] = range(len(post))\nm_post = pf.feols('inflgdp ~ urate', data=post,\n                  vcov='NW', vcov_kwargs={'time_id': '_time', 'lag': 5})\nprint(f\"Post-1970 slope: {m_post.coef()['urate']:.3f}  (positive → breakdown!)\")\n\n# Augmented model: adding expected inflation restores the negative sign\npost_exp = post.dropna(subset=['inflgdp1yr'])\npost_exp = post_exp.copy()\npost_exp['_time'] = range(len(post_exp))\nm_aug = pf.feols('inflgdp ~ urate + inflgdp1yr', data=post_exp,\n                 vcov='NW', vcov_kwargs={'time_id': '_time', 'lag': 5})\nprint(f\"Augmented slope on urate: {m_aug.coef()['urate']:.3f}  (negative again!)\")\nprint(f\"Expected inflation coef:  {m_aug.coef()['inflgdp1yr']:.3f}\")\n\n# OVB formula: E[b2] = β2 + β3*γ\nm_aux = pf.feols('inflgdp1yr ~ urate', data=post_exp)\npredicted = m_aug.coef()['urate'] + m_aug.coef()['inflgdp1yr'] * m_aux.coef()['urate']\nprint(f\"OVB predicted bivariate slope: {predicted:.3f}  (actual: {m_post.coef()['urate']:.3f})\")\n\n# =============================================================================\n# STEP 3: RAND Health Insurance Experiment — RCT as the gold standard\n# =============================================================================\n# Random assignment to insurance plans eliminates selection bias\ndata_rand = pd.read_stata(URL + \"AED_HEALTHINSEXP.DTA\")\ndata_rand_y1 = data_rand[data_rand['year'] == 1]\n\n# Mean spending by plan\nprint(f\"\\n{'Plan':<12} {'Mean $':>10} {'N':>8}\")\nfor plan, grp in data_rand_y1.groupby('plan')['spending']:\n    print(f\"{plan:<12} {grp.mean():>10,.0f} {len(grp):>8,}\")\n\n# Regression with cluster-robust SEs by family\nfit_rct = pf.feols('spending ~ coins25 + coins50 + coins95 + coinsmixed + coinsindiv',\n                data=data_rand_y1, vcov={'CRV1': 'idfamily'})\nfit_rct.summary()\n\n# =============================================================================\n# STEP 4: Difference-in-Differences — health clinic access in South Africa\n# =============================================================================\n# DiD removes both time-invariant confounders and common time trends\ndata_did = pd.read_stata(URL + \"AED_HEALTHACCESS.DTA\")\n\n# Manual DiD calculation\npre_c  = data_did[(data_did['hightreat']==0) & (data_did['post']==0)]['waz'].mean()\npost_c = data_did[(data_did['hightreat']==0) & (data_did['post']==1)]['waz'].mean()\npre_t  = data_did[(data_did['hightreat']==1) & (data_did['post']==0)]['waz'].mean()\npost_t = data_did[(data_did['hightreat']==1) & (data_did['post']==1)]['waz'].mean()\ndid    = (post_t - pre_t) - (post_c - pre_c)\nprint(f\"\\nDiD estimate (manual): {did:.3f} SD improvement in child nutrition\")\n\n# DiD regression with cluster-robust SEs by community\nfit_did = pf.feols('waz ~ hightreat + post + postXhigh', data=data_did, vcov={'CRV1': 'idcommunity'})\nprint(f\"DiD coefficient (regression): {fit_did.coef()['postXhigh']:.3f}\")\nprint(f\"p-value: {fit_did.pvalue()['postXhigh']:.4f}\")\n\n# =============================================================================\n# STEP 5: Regression Discontinuity — incumbency advantage in U.S. Senate\n# =============================================================================\n# Candidates who barely win vs barely lose are quasi-randomly assigned to\n# incumbent status — the jump at margin = 0 is the causal effect\ndata_rd = pd.read_stata(URL + \"AED_INCUMBENCY.DTA\")\ndata_rd = data_rd[data_rd['vote'].notna()].copy()\n\nfit_rd = pf.feols('vote ~ win + margin', data=data_rd, vcov='HC1')\nprint(f\"\\nIncumbency advantage: {fit_rd.coef()['win']:.1f} percentage points\")\nci = fit_rd.confint()\nprint(f\"95% CI: [{ci.loc['win', '2.5%']:.1f}, {ci.loc['win', '97.5%']:.1f}]\")\nprint(f\"p-value: {fit_rd.pvalue()['win']:.4f}\")\n\n# =============================================================================\n# STEP 6: Instrumental Variables — do institutions cause growth?\n# =============================================================================\n# OLS is biased by reverse causation; settler mortality instruments for\n# modern institutions (relevant + exogenous to modern GDP)\ndata_iv = pd.read_stata(URL + \"AED_INSTITUTIONS.DTA\")\n\n# OLS (biased)\nm_ols = pf.feols('logpgp95 ~ avexpr', data=data_iv, vcov='HC1')\n\n# IV/2SLS: y ~ exog | endog ~ instrument\nm_iv = pf.feols('logpgp95 ~ 1 | avexpr ~ logem4', data=data_iv, vcov='HC1')\n\n# First-stage F\nm_1st = pf.feols('avexpr ~ logem4', data=data_iv, vcov='HC1')\nfirst_f = m_1st.tstat()['logem4']**2\nprint(f\"\\nFirst-stage F = {first_f:.1f}  ({'Strong' if first_f > 10 else 'Weak'} instrument)\")\n\nprint(f\"OLS coefficient:  {m_ols.coef()['avexpr']:.3f}  (biased)\")\nprint(f\"IV/2SLS coefficient: {m_iv.coef()['avexpr']:.3f}  (causal)\")\nprint(f\"Causal effect: 1-unit improvement in institutions → \"\n      f\"{np.exp(m_iv.coef()['avexpr']):.1f}x increase in GDP\")\n```\n\n**Try it yourself!** Copy this code into an empty Google Colab notebook and run it: [Open Colab](https://colab.research.google.com/notebooks/empty.ipynb)\n\n---\n\n**Next Steps:**\n\n- **Chapter 14:** Regression with Indicator Variables\n- **Chapter 15:** Regression with Transformed Variables\n\n---\n\n**Congratulations!** You've completed nine comprehensive case studies demonstrating the breadth and power of multiple regression analysis — from school performance to macroeconomic policy to causal inference!\n\n> **Common Mistakes to Avoid**\n>\n> - **Cherry-picking significant results**: Report all specifications, not just the ones that \"work\"\n> - **Ignoring the direction of bias from omitted variables**: Think through the sign of the bias\n> - **Not considering measurement error**: Proxy variables introduce attenuation bias\n\n## Practice Exercises\n\n**Exercise 1: Interpreting Multiple Regression Coefficients**\n\nA regression of school test scores on parent education yields a coefficient of 80. When meals (% free lunch), English learners, and teacher quality are added, the parent education coefficient drops to 74.\n\n**(a)** Why does the coefficient change when additional variables are included?\n\n**(b)** Does the change mean parent education is less important than initially thought? Explain.\n\n**(c)** What does the remaining coefficient of 74 represent in terms of partial effects?\n\n---\n\n**Exercise 2: Log Transformation and Elasticities**\n\nA Cobb-Douglas production function is estimated as: $\\ln Q = 1.45 + 0.23 \\ln K + 0.81 \\ln L$\n\n**(a)** Interpret the coefficient 0.23 in terms of percentage changes.\n\n**(b)** Interpret the coefficient 0.81 in terms of percentage changes.\n\n**(c)** Do these results suggest constant, increasing, or decreasing returns to scale? Conduct a formal test.\n\n---\n\n**Exercise 3: Omitted Variables Bias**\n\nA researcher estimates the effect of unemployment on inflation and finds a positive coefficient. When expected inflation is added, the unemployment coefficient becomes negative.\n\n**(a)** Using the OVB formula, explain why the coefficient changed sign.\n\n**(b)** What are the two conditions required for omitted variables bias to occur?\n\n**(c)** Is the augmented model more reliable? Why or why not?\n\n---\n\n**Exercise 4: Choosing Standard Error Types**\n\nFor each scenario, identify the appropriate type of standard errors and explain why:\n\n**(a)** Cross-sectional data on 500 firms with varying sizes (potential heteroskedasticity)\n\n**(b)** Panel data with 50 schools observed over 10 years (observations clustered by school)\n\n**(c)** Time series data on quarterly GDP growth for 30 years (potential serial correlation)\n\n---\n\n**Exercise 5: Matching Causal Inference Methods**\n\nMatch each research scenario with the most appropriate causal inference method (RCT, DiD, RD, IV) and state the key identifying assumption:\n\n**(a)** A new drug is tested by randomly assigning patients to treatment and placebo groups\n\n**(b)** A scholarship is awarded to students scoring above 80 on an entrance exam\n\n**(c)** A new minimum wage law is implemented in one state but not its neighbor\n\n**(d)** Historical settler mortality is used to explain current institutional quality\n\n---\n\n**Exercise 6: Data Preparation Checklist**\n\nYou receive a dataset containing country-level GDP, population, and education data from three different sources in `.csv`, `.xlsx`, and `.dta` formats.\n\n**(a)** List the steps you would take to prepare this data for regression analysis.\n\n**(b)** What potential issues should you check for when merging datasets from different sources?\n\n**(c)** Why is data validation important before running regressions?\n\n",
    "supporting": [
      "ch13_Case_Studies_for_Multiple_Regression_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}