"""
ch03_The_Sample_Mean.py - January 2026 for Python

Chapter 3: THE SAMPLE MEAN

To run you need files:
  AED_COINTOSSMEANS.DTA
  AED_CENSUSAGEMEANS.DTA
in the data_stata/ directory

Sections covered:
  3.1 RANDOM VARIABLES
  3.2 SAMPLE GENERATED BY AN EXPERIMENT: COIN TOSSES
  3.3 PROPERTIES OF THE SAMPLE MEAN
  3.4 SAMPLING FROM A FINITE POPULATION: 1880 U.S. CENSUS
  3.5 ESTIMATION OF THE POPULATION MEAN
  3.6 SAMPLES OTHER THAN RANDOM SAMPLES
  3.7 COMPUTER GENERATION OF A RANDOM SAMPLE
"""

# ========== SETUP ==========

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import random
import os

# Set random seeds for reproducibility
RANDOM_SEED = 42
random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)
os.environ['PYTHONHASHSEED'] = str(RANDOM_SEED)

# GitHub data URL
GITHUB_DATA_URL = "https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/"

# Output directories (optional - for saving figures and tables locally)
IMAGES_DIR = 'images'
TABLES_DIR = 'tables'
os.makedirs(IMAGES_DIR, exist_ok=True)
os.makedirs(TABLES_DIR, exist_ok=True)

# Set plotting style
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

print("=" * 70)
print("CHAPTER 3: THE SAMPLE MEAN")
print("=" * 70)

# ========== 3.2 SAMPLE GENERATED BY AN EXPERIMENT: COIN TOSSES ==========

print("\n" + "=" * 70)
print("3.2 SAMPLE GENERATED BY AN EXPERIMENT: COIN TOSSES")
print("=" * 70)

# Draw one sample of size 30 from Bernoulli with p = 0.5
np.random.seed(10101)
u = np.random.uniform(0, 1, 30)
x = np.where(u > 0.5, 1, 0)

print("\nSingle coin toss sample (n=30):")
print(f"Number of heads (x=1): {np.sum(x)}")
print(f"Number of tails (x=0): {np.sum(1-x)}")
print(f"Sample mean: {np.mean(x):.4f}")
print(f"Sample std dev: {np.std(x, ddof=1):.4f}")

# Figure 3.1: First panel - histogram of single sample
fig, ax = plt.subplots(figsize=(8, 6))
ax.hist(x, bins=[-0.5, 0.5, 1.5], edgecolor='black', alpha=0.7, color='steelblue')
ax.set_xlabel('Heads = 1 and Tails = 0', fontsize=12)
ax.set_ylabel('Frequency', fontsize=12)
# ax.set_title('Figure 3.1 Panel A: Single Sample of 30 Coin Tosses',
#              fontsize=14, fontweight='bold')  # Removed: redundant with LaTeX caption  # Removed: redundant with LaTeX caption
ax.set_xticks([0, 1])
ax.grid(True, alpha=0.3, axis='y')

output_file = os.path.join(IMAGES_DIR, 'ch03_fig1a_single_coin_toss_sample.png')
plt.tight_layout()
plt.savefig(output_file, dpi=300, bbox_inches='tight')
print(f"\nFigure 3.1 Panel A saved to: {output_file}")
plt.close()

# Read in data for 400 coin toss samples
data_cointoss = pd.read_stata(GITHUB_DATA_URL + 'AED_COINTOSSMEANS.DTA')

print("\n" + "-" * 70)
print("Coin toss means data (400 samples of size 30):")
cointoss_summary = data_cointoss.describe()
print(cointoss_summary)
print("\nFirst 5 observations:")
print(data_cointoss.head())
cointoss_summary.to_csv(os.path.join(TABLES_DIR, 'ch03_cointoss_descriptive_stats.csv'))
print(f"Table saved to: {os.path.join(TABLES_DIR, 'ch03_cointoss_descriptive_stats.csv')}")

xbar = data_cointoss['xbar']

# Figure 3.1: Second panel - distribution of sample means
fig, ax = plt.subplots(figsize=(10, 6))

# Histogram
n, bins, patches = ax.hist(xbar, bins=30, density=True,
                            edgecolor='black', alpha=0.7, color='steelblue',
                            label='Sample means')

# Overlay normal distribution
xbar_range = np.linspace(xbar.min(), xbar.max(), 100)
normal_pdf = stats.norm.pdf(xbar_range, xbar.mean(), xbar.std())
ax.plot(xbar_range, normal_pdf, 'r-', linewidth=2,
        label=f'Normal({xbar.mean():.3f}, {xbar.std():.3f})')

ax.set_xlabel('Sample mean from each of 400 samples', fontsize=12)
ax.set_ylabel('Density', fontsize=12)
# ax.set_title('Figure 3.1 Panel B: Distribution of Sample Means (400 samples)  # Removed: redundant with LaTeX caption',
#              fontsize=14, fontweight='bold')  # Removed: redundant with LaTeX caption
ax.legend()
ax.grid(True, alpha=0.3)

output_file = os.path.join(IMAGES_DIR, 'ch03_fig1b_distribution_sample_means.png')
plt.tight_layout()
plt.savefig(output_file, dpi=300, bbox_inches='tight')
print(f"Figure 3.1 Panel B saved to: {output_file}")
plt.close()

print(f"\nSample mean of the 400 sample means: {xbar.mean():.4f}")
print(f"Standard deviation of the 400 sample means: {xbar.std():.4f}")
print(f"Theoretical: μ = 0.5, σ/√n = √(0.25/30) = {np.sqrt(0.25/30):.4f}")

# ========== 3.4 SAMPLING FROM A FINITE POPULATION: 1880 U.S. CENSUS ==========

print("\n" + "=" * 70)
print("3.4 SAMPLING FROM A FINITE POPULATION: 1880 U.S. CENSUS")
print("=" * 70)

# Read in census age means data
data_census = pd.read_stata(GITHUB_DATA_URL + 'AED_CENSUSAGEMEANS.DTA')

print("\nCensus age means data (100 samples of size 25):")
census_summary = data_census.describe()
print(census_summary)
print("\nFirst 5 observations:")
print(data_census.head())
census_summary.to_csv(os.path.join(TABLES_DIR, 'ch03_census_descriptive_stats.csv'))
print(f"Table saved to: {os.path.join(TABLES_DIR, 'ch03_census_descriptive_stats.csv')}")

# Get the mean variable (may be called 'mean' or 'xmean')
if 'mean' in data_census.columns:
    age_means = data_census['mean']
elif 'xmean' in data_census.columns:
    age_means = data_census['xmean']
else:
    # Use first numeric column
    age_means = data_census.iloc[:, 0]

# Figure 3.3: Distribution of sample means from census data
fig, ax = plt.subplots(figsize=(10, 6))

# Histogram
n, bins, patches = ax.hist(age_means, bins=20, density=True,
                            edgecolor='black', alpha=0.7, color='coral',
                            label='Sample means')

# Overlay normal distribution
age_range = np.linspace(age_means.min(), age_means.max(), 100)
normal_pdf = stats.norm.pdf(age_range, age_means.mean(), age_means.std())
ax.plot(age_range, normal_pdf, 'b-', linewidth=2,
        label=f'Normal({age_means.mean():.2f}, {age_means.std():.2f})')

ax.set_xlabel('Sample mean age from each of 100 samples', fontsize=12)
ax.set_ylabel('Density', fontsize=12)
# ax.set_title('Figure 3.3: Distribution of Sample Means from 1880 U.S. Census',
#              fontsize=14, fontweight='bold')  # Removed: redundant with LaTeX caption  # Removed: redundant with LaTeX caption
ax.legend()
ax.grid(True, alpha=0.3)

output_file = os.path.join(IMAGES_DIR, 'ch03_fig3_census_age_means.png')
plt.tight_layout()
plt.savefig(output_file, dpi=300, bbox_inches='tight')
print(f"\nFigure 3.3 saved to: {output_file}")
plt.close()

print(f"\nMean of sample means: {age_means.mean():.2f}")
print(f"Standard deviation of sample means: {age_means.std():.2f}")

# ========== 3.7 COMPUTER GENERATION OF A RANDOM SAMPLE ==========

print("\n" + "=" * 70)
print("3.7 COMPUTER GENERATION OF A RANDOM SAMPLE")
print("=" * 70)

# Generate single samples from different distributions
np.random.seed(10101)
x_uniform = np.random.uniform(3, 9, 100)
y_normal = np.random.normal(5, 2, 100)

print("\nSingle sample from Uniform(3, 9):")
print(f"  Mean: {x_uniform.mean():.4f}, Std: {x_uniform.std():.4f}")
print(f"  Theoretical: Mean = 6.0, Std = {np.sqrt((9-3)**2/12):.4f}")

print("\nSingle sample from Normal(5, 2):")
print(f"  Mean: {y_normal.mean():.4f}, Std: {y_normal.std():.4f}")
print(f"  Theoretical: Mean = 5.0, Std = 2.0")

# Simulate 400 coin toss samples each of size 30
print("\n" + "-" * 70)
print("Simulation: 400 samples of 30 coin tosses")
print("-" * 70)

np.random.seed(10101)
n_simulations = 400
sample_size = 30

result_mean = np.zeros(n_simulations)
result_std = np.zeros(n_simulations)

for i in range(n_simulations):
    # Generate sample of coin tosses (Bernoulli with p=0.5)
    sample = np.random.binomial(1, 0.5, sample_size)
    result_mean[i] = sample.mean()
    result_std[i] = sample.std(ddof=1)

print(f"\nMean of the 400 sample means: {result_mean.mean():.4f}")
print(f"Std dev of the 400 sample means: {result_mean.std():.4f}")
print(f"Min: {result_mean.min():.4f}, Max: {result_mean.max():.4f}")

print(f"\nTheoretical values:")
print(f"  Expected value of sample mean: 0.5000")
print(f"  Expected std dev of sample mean: {np.sqrt(0.25/30):.4f}")

# Create visualization of simulated distribution
fig, ax = plt.subplots(figsize=(10, 6))

ax.hist(result_mean, bins=30, density=True,
        edgecolor='black', alpha=0.7, color='lightgreen',
        label='Simulated sample means')

# Overlay theoretical normal distribution
x_range = np.linspace(result_mean.min(), result_mean.max(), 100)
theoretical_pdf = stats.norm.pdf(x_range, 0.5, np.sqrt(0.25/30))
ax.plot(x_range, theoretical_pdf, 'r-', linewidth=2,
        label='Theoretical Normal(0.5, 0.091)')

ax.set_xlabel('Sample mean', fontsize=12)
ax.set_ylabel('Density', fontsize=12)
# ax.set_title('Simulated Distribution of Sample Means (400 simulations)  # Removed: redundant with LaTeX caption',
#              fontsize=14, fontweight='bold')  # Removed: redundant with LaTeX caption
ax.legend()
ax.grid(True, alpha=0.3)

output_file = os.path.join(IMAGES_DIR, 'ch03_simulated_sample_means.png')
plt.tight_layout()
plt.savefig(output_file, dpi=300, bbox_inches='tight')
print(f"\nSimulation figure saved to: {output_file}")
plt.close()

# ========== SUMMARY ==========

print("\n" + "=" * 70)
print("CHAPTER 3 ANALYSIS COMPLETE")
print("=" * 70)
print("\nKey concepts demonstrated:")
print("  - Sampling distribution of the sample mean")
print("  - Central Limit Theorem")
print("  - Properties of estimators (unbiasedness, efficiency)")
print("  - Computer simulation of random samples")
print("  - Comparison of theoretical and empirical distributions")
