{
  "hash": "767ee434214e04346ac0ee58eb0110a6",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 9. Models with Natural Logarithms\nexecute:\n  enabled: true\n  warning: false\n---\n\n\n**metricsAI: An Introduction to Econometrics with Python and AI in the Cloud**\n\n*[Carlos Mendez](https://carlos-mendez.org)*\n\n<img src=\"https://raw.githubusercontent.com/quarcs-lab/metricsai/main/images/ch09_visual_summary.jpg\" alt=\"Chapter 09 Visual Summary\" width=\"100%\">\n\nThis notebook teaches you how to use natural logarithms in regression analysis to measure elasticities, semi-elasticities, and percentage changes—essential tools for empirical economics.\n\n[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/quarcs-lab/metricsai/blob/main/notebooks_colab/ch09_Models_with_Natural_Logarithms.ipynb)\n<div class=\"chapter-resources\">\n<a href=\"https://www.youtube.com/watch?v=rPy6m8_Wg4c\" target=\"_blank\" class=\"resource-btn\">🎬 AI Video</a>\n<a href=\"https://carlos-mendez.my.canva.site/s09-models-with-natural-logarithms-pdf\" target=\"_blank\" class=\"resource-btn\">✨ AI Slides</a>\n<a href=\"https://cameron.econ.ucdavis.edu/aed/traedv1_09\" target=\"_blank\" class=\"resource-btn\">📊 Cameron Slides</a>\n<a href=\"https://app.edcafe.ai/quizzes/697867a22f5d08069e04a411\" target=\"_blank\" class=\"resource-btn\">✏️ Quiz</a>\n<a href=\"https://app.edcafe.ai/chatbots/6978a07f2f5d08069e0713c6\" target=\"_blank\" class=\"resource-btn\">🤖 AI Tutor</a>\n</div>\n\n\n## Chapter Overview\n\n**Why logarithms in economics?**\n\nEconomists care about **proportionate changes** more than absolute changes:\n\n- A \\$10,000 salary increase means different things at \\$30,000 vs \\$300,000 income\n- A \\$1 price change matters differently for a \\$2 item vs a \\$100 item\n- Economic theory often predicts **percentage** responses (e.g., price elasticity of demand)\n\n**Natural logarithms** let us work with proportionate changes easily in regression models.\n\n**What you'll learn:**\n\n- Understand the natural logarithm function and its basic properties\n- Use logarithmic transformations to approximate proportionate and percentage changes\n- Distinguish between semi-elasticity and elasticity\n- Interpret coefficients in log-linear, log-log, and linear-log regression models\n- Apply logarithmic models to analyze the relationship between earnings and education\n- Linearize exponential growth patterns using natural logarithms\n- Apply the Rule of 72 to calculate doubling times for compound growth\n- Choose the appropriate model specification for different economic questions\n\n**Datasets used:**\n\n- **AED_EARNINGS.DTA**: Annual earnings and education for 171 full-time workers aged 30 (2010)\n- **AED_SP500INDEX.DTA**: S&P 500 stock market index, annual data 1927-2019 (93 years)\n\n**Chapter outline:**\n\n- 9.1 Natural Logarithm Function\n- 9.2 Semi-Elasticities and Elasticities\n- 9.3 Example: Earnings and Education\n- 9.4 Further Uses: Exponential Growth\n- Key Takeaways\n- Practice Exercises\n- Case Studies\n\n## Setup\n\nRun this cell first to import all required packages and configure the environment.\n\n::: {#3fef4699 .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Setup: Import libraries and configure environment\"}\n# --- Libraries ---\nimport numpy as np                        # numerical operations\nimport pandas as pd                       # data manipulation\nimport matplotlib.pyplot as plt           # plotting\nimport seaborn as sns                     # statistical visualizations\nimport pyfixest as pf                     # fast estimation with robust SEs\nfrom scipy import stats                   # statistical distributions\nimport random\nimport os\n\n# --- Reproducibility ---\nRANDOM_SEED = 42\nrandom.seed(RANDOM_SEED)\nnp.random.seed(RANDOM_SEED)\nos.environ['PYTHONHASHSEED'] = str(RANDOM_SEED)\n\n# --- Data source ---\nGITHUB_DATA_URL = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/\"\n\n# --- Output directories ---\nIMAGES_DIR = 'images'\nTABLES_DIR = 'tables'\nos.makedirs(IMAGES_DIR, exist_ok=True)\nos.makedirs(TABLES_DIR, exist_ok=True)\n\n# --- Plotting style (dark theme matching book design) ---\nplt.style.use('dark_background')\nsns.set_style(\"darkgrid\")\nplt.rcParams.update({\n    'axes.facecolor': '#1a2235',\n    'figure.facecolor': '#12162c',\n    'grid.color': '#3a4a6b',\n    'figure.figsize': (10, 6),\n    'text.color': 'white',\n    'axes.labelcolor': 'white',\n    'xtick.color': 'white',\n    'ytick.color': 'white',\n    'axes.edgecolor': '#1a2235',\n})\n\nprint(\"✓ Setup complete! All packages imported successfully.\")\nprint(f\"✓ Random seed set to {RANDOM_SEED} for reproducibility.\")\nprint(f\"✓ Data will stream from: {GITHUB_DATA_URL}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Setup complete! All packages imported successfully.\n✓ Random seed set to 42 for reproducibility.\n✓ Data will stream from: https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/\n```\n:::\n:::\n\n\n## 9.1 Natural Logarithm Function\n\nThe **natural logarithm** ln(x) is the logarithm to base **e** ≈ 2.71828...\n\n**Definition:**\n$$\\ln(x) = \\log_e(x), \\quad x > 0$$\n\n**Key properties:**\n\n1. ln(1) = 0\n2. ln(e) = 1\n3. ln(ab) = ln(a) + ln(b) (product rule)\n4. ln(a/b) = ln(a) - ln(b) (quotient rule)\n5. ln(aᵇ) = b·ln(a) (power rule)\n6. exp(ln(x)) = x (inverse function)\n\n**Most important property for economics:**\n$$\\Delta \\ln(x) \\approx \\frac{\\Delta x}{x} \\quad \\text{(for small changes)}$$\n\nThis means: **Change in ln(x) ≈ proportionate change in x**\n\nMultiplying by 100: **100 × Δln(x) ≈ percentage change in x**\n\n**Example:** If x increases from 40 to 40.4:\n\n- Exact proportionate change: (40.4 - 40)/40 = 0.01 (1%)\n- Log approximation: ln(40.4) - ln(40) = 0.00995 ≈ 0.01\n\n::: {#2326b6dd .cell execution_count=2}\n``` {.python .cell-code}\n# Demonstrate logarithm properties\n# PROPERTIES OF NATURAL LOGARITHM\n\nx_values = np.array([0.5, 1, 2, 5, 10, 20, 100])\nln_values = np.log(x_values)\n\nlog_table = pd.DataFrame({\n    'x': x_values,\n    'ln(x)': ln_values,\n    'exp(ln(x))': np.exp(ln_values)\n})\nlog_table.to_string(index=False)\n\n# KEY PROPERTIES DEMONSTRATED\nprint(f\"1. ln(1) = {np.log(1):.4f}\")\nprint(f\"2. ln(e) = {np.log(np.e):.4f}\")\nprint(f\"3. ln(2×5) = ln(2) + ln(5):  {np.log(2*5):.4f} = {np.log(2) + np.log(5):.4f} ✓\")\nprint(f\"4. ln(10/2) = ln(10) - ln(2): {np.log(10/2):.4f} = {np.log(10) - np.log(2):.4f} ✓\")\n\n# APPROXIMATING PROPORTIONATE CHANGES\nx0, x1 = 40, 40.4\nexact_prop_change = (x1 - x0) / x0\nlog_approx = np.log(x1) - np.log(x0)\nprint(f\"Change from {x0} to {x1}:\")\nprint(f\"  Exact proportionate change:    {exact_prop_change:.6f} ({exact_prop_change*100:.2f}%)\")\nprint(f\"  Log approximation Δln(x):      {log_approx:.6f} ({log_approx*100:.2f}%)\")\nprint(f\"  Difference:                    {abs(exact_prop_change - log_approx):.6f}\")\n# The approximation is excellent for small changes\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1. ln(1) = 0.0000\n2. ln(e) = 1.0000\n3. ln(2×5) = ln(2) + ln(5):  2.3026 = 2.3026 ✓\n4. ln(10/2) = ln(10) - ln(2): 1.6094 = 1.6094 ✓\nChange from 40 to 40.4:\n  Exact proportionate change:    0.010000 (1.00%)\n  Log approximation Δln(x):      0.009950 (1.00%)\n  Difference:                    0.000050\n```\n:::\n:::\n\n\n> **Key Concept 9.1: Logarithmic Approximation of Proportionate Change**\n>\n> The most important property of the natural logarithm for economics is:\n>\n> $$\\Delta \\ln(x) \\approx \\frac{\\Delta x}{x} \\quad \\text{(proportionate change)}$$\n>\n> Multiplying by 100 gives the **percentage change**: 100 × Δln(x) ≈ %Δx.\n>\n> **Why this matters:** This approximation allows us to interpret regression coefficients involving logged variables as **proportionate or percentage changes** — exactly what economists care about when analyzing earnings, prices, GDP, and other economic variables.\n>\n> **Accuracy:** The approximation is excellent for changes under 10%. For larger changes, use the exact formula: %Δx = 100 × (e^Δln(x) - 1).\n\n## 9.2 Semi-Elasticities and Elasticities\n\nTwo key concepts in economics:\n\n### Semi-Elasticity\n**Definition:** Proportionate change in y for a **unit change** in x\n$$\\text{Semi-elasticity}_{yx} = \\frac{\\Delta y / y}{\\Delta x}$$\n\nMultiplied by 100: **percentage change in y when x increases by 1 unit**\n\n**Example:** Semi-elasticity of earnings with respect to education = 0.08\n\n- One more year of schooling → 8% increase in earnings\n\n### Elasticity\n**Definition:** Proportionate change in y for a **proportionate change** in x\n$$\\text{Elasticity}_{yx} = \\frac{\\Delta y / y}{\\Delta x / x}$$\n\n**Example:** Price elasticity of demand = -2\n\n- 1% increase in price → 2% decrease in demand\n\n### Approximations Using Logarithms\nSince Δy/y ≈ Δln(y) and Δx/x ≈ Δln(x):\n\n$$\\text{Semi-elasticity} \\approx \\frac{\\Delta \\ln(y)}{\\Delta x}$$\n\n$$\\text{Elasticity} \\approx \\frac{\\Delta \\ln(y)}{\\Delta \\ln(x)}$$\n\n**This is why we use logarithms in regression!** The slope coefficient directly estimates the semi-elasticity or elasticity.\n\n::: {#46f8a45b .cell execution_count=3}\n``` {.python .cell-code}\n# MODEL INTERPRETATIONS\n# 1. Linear: y = β₀ + β₁x → Δy = β₁Δx\n# 2. Log-linear: ln(y) = β₀ + β₁x → %Δy ≈ 100β₁Δx (semi-elasticity)\n# 3. Log-log: ln(y) = β₀ + β₁ln(x) → %Δy ≈ β₁%Δx (elasticity)\n# 4. Linear-log: y = β₀ + β₁ln(x) → Δy ≈ (β₁/100)%Δx\n\n# KEY TAKEAWAY\n```\n:::\n\n\n> **Key Concept 9.2: Semi-Elasticity vs. Elasticity**\n>\n> These two concepts measure how y responds to changes in x, but in different ways:\n>\n> - **Semi-elasticity** = (Δy/y) / Δx — proportionate change in y per **unit** change in x\n> - **Elasticity** = (Δy/y) / (Δx/x) — proportionate change in y per **proportionate** change in x\n>\n> **In regression models:**\n> - Semi-elasticity ≈ Δln(y)/Δx → estimated by the slope in a **log-linear** model\n> - Elasticity ≈ Δln(y)/Δln(x) → estimated by the slope in a **log-log** model\n>\n> **When to use each:**\n> - **Semi-elasticity:** When x is measured in natural units (years of education, age)\n> - **Elasticity:** When both variables are measured in proportions (price and quantity, GDP and investment)\n\n## 9.3 Example: Earnings and Education\n\n**Research Question:** How do earnings vary with years of education?\n\nWe'll estimate **four different models** and compare their interpretations:\n\n1. **Linear:** earnings = β₀ + β₁(education)\n2. **Log-linear:** ln(earnings) = β₀ + β₁(education)\n3. **Log-log:** ln(earnings) = β₀ + β₁ln(education)\n4. **Linear-log:** earnings = β₀ + β₁ln(education)\n\n**Dataset:** 171 full-time workers aged 30 in 2010\n\n- earnings: Annual earnings in dollars\n- education: Years of completed schooling\n\nEach model answers a slightly different question and has different economic interpretation.\n\n::: {#833a7734 .cell execution_count=4}\n``` {.python .cell-code}\n# Load and explore the data\ndata_earnings = pd.read_stata(GITHUB_DATA_URL + 'AED_EARNINGS.DTA')\n\n# DATA SUMMARY: EARNINGS AND EDUCATION\ndata_earnings[['earnings', 'education']].describe()\n\nprint(\"\\nFirst 5 observations:\")\ndata_earnings[['earnings', 'education']].head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFirst 5 observations:\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>earnings</th>\n      <th>education</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>25000</td>\n      <td>14</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>40000</td>\n      <td>12</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>25000</td>\n      <td>13</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>38000</td>\n      <td>13</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>28800</td>\n      <td>12</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#52ac8587 .cell execution_count=5}\n``` {.python .cell-code}\n# Create log-transformed variables\ndata_earnings['lnearn'] = np.log(data_earnings['earnings'])\ndata_earnings['lneduc'] = np.log(data_earnings['education'])\n\n# VARIABLES (ORIGINAL AND LOG-TRANSFORMED)\ntable_vars = ['earnings', 'lnearn', 'education', 'lneduc']\ndata_earnings[table_vars].describe()\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>earnings</th>\n      <th>lnearn</th>\n      <th>education</th>\n      <th>lneduc</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>171.000000</td>\n      <td>171.000000</td>\n      <td>171.000000</td>\n      <td>171.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>41412.690058</td>\n      <td>10.457638</td>\n      <td>14.432749</td>\n      <td>2.648438</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>25527.053396</td>\n      <td>0.622062</td>\n      <td>2.735364</td>\n      <td>0.225220</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>1050.000000</td>\n      <td>6.956545</td>\n      <td>3.000000</td>\n      <td>1.098633</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>25000.000000</td>\n      <td>10.126631</td>\n      <td>12.000000</td>\n      <td>2.484375</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>36000.000000</td>\n      <td>10.491274</td>\n      <td>14.000000</td>\n      <td>2.638672</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>49000.000000</td>\n      <td>10.799367</td>\n      <td>16.000000</td>\n      <td>2.773438</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>172000.000000</td>\n      <td>12.055250</td>\n      <td>20.000000</td>\n      <td>2.996094</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Model 1: Linear Model\n\n**Specification:** earnings = β₀ + β₁(education) + ε\n\n**Interpretation:** β₁ = change in earnings (in dollars) for one additional year of education\n\n::: {#aa7bba68 .cell execution_count=6}\n``` {.python .cell-code}\n# Model 1: Linear\n# MODEL 1: LINEAR - earnings = β₀ + β₁(education)\n\nmodel_linear = pf.feols('earnings ~ education', data=data_earnings)\n\n# Key results\nintercept_1 = model_linear.coef()['Intercept']\nslope_1     = model_linear.coef()['education']\nr2_1        = model_linear._r2\n\nprint(f\"Estimated equation: earnings = {intercept_1:,.0f} + {slope_1:,.2f} x education\")\nprint(f\"Slope: each additional year of education is associated with ${slope_1:,.2f} higher annual earnings\")\nprint(f\"R-squared: {r2_1:.4f} ({r2_1*100:.1f}% of variation explained)\")\n\n# Full regression output\nmodel_linear.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEstimated equation: earnings = -31,056 + 5,021.12 x education\nSlope: each additional year of education is associated with $5,021.12 higher annual earnings\nR-squared: 0.2895 (28.9% of variation explained)\n###\n\nEstimation:  OLS\nDep. var.: earnings\nsample: None = all\nInference:  iid\nObservations:  171\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |       2.5% |      97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|-----------:|-----------:|\n| Intercept     | -31055.915 |     8887.835 |    -3.494 |      0.001 | -48601.394 | -13510.435 |\n| education     |   5021.123 |      605.101 |     8.298 |      0.000 |   3826.593 |   6215.653 |\n---\nRMSE: 21454.224 R2: 0.289 \n```\n:::\n:::\n\n\n### Model 2: Log-Linear Model\n\n**Specification:** ln(earnings) = β₀ + β₁(education) + ε\n\n**Interpretation:** β₁ = **semi-elasticity** = proportionate change in earnings for one more year of education\n\n**Practical interpretation:** 100β₁ = **percentage change** in earnings for one more year of education\n\nThis is the **most common** specification for earnings equations!\n\n::: {#4ea46965 .cell execution_count=7}\n``` {.python .cell-code}\n# Model 2: Log-linear\n# MODEL 2: LOG-LINEAR - ln(earnings) = β₀ + β₁(education)\n\nmodel_loglin = pf.feols('lnearn ~ education', data=data_earnings)\n\n# Key results\nintercept_2   = model_loglin.coef()['Intercept']\nsemi_elast    = model_loglin.coef()['education']\nr2_2          = model_loglin._r2\n\nprint(f\"Estimated equation: ln(earnings) = {intercept_2:.4f} + {semi_elast:.4f} x education\")\nprint(f\"Each additional year of education is associated with a {100*semi_elast:.2f}% increase in earnings\")\nprint(f\"R-squared: {r2_2:.4f} ({r2_2*100:.1f}% of variation explained)\")\nprint(f\"Note: percentage interpretation scales automatically — applies whether you earn $30k or $100k\")\n\n# Full regression output\nmodel_loglin.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEstimated equation: ln(earnings) = 8.5608 + 0.1314 x education\nEach additional year of education is associated with a 13.14% increase in earnings\nR-squared: 0.3340 (33.4% of variation explained)\nNote: percentage interpretation scales automatically — applies whether you earn $30k or $100k\n###\n\nEstimation:  OLS\nDep. var.: lnearn\nsample: None = all\nInference:  iid\nObservations:  171\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |   2.5% |   97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|-------:|--------:|\n| Intercept     |      8.561 |        0.210 |    40.825 |      0.000 |  8.147 |   8.975 |\n| education     |      0.131 |        0.014 |     9.206 |      0.000 |  0.103 |   0.160 |\n---\nRMSE: 0.506 R2: 0.334 \n```\n:::\n:::\n\n\n> **Key Concept 9.3: Interpreting Log-Linear Model Coefficients**\n>\n> In the **log-linear model** ln(y) = β₀ + β₁x, the slope coefficient β₁ is the **semi-elasticity** of y with respect to x:\n>\n> $$100 \\times \\beta_1 = \\text{percentage change in } y \\text{ when } x \\text{ increases by 1 unit}$$\n>\n> This is the most common specification in labor economics because a percentage interpretation **scales automatically** — a 13% return to education applies equally whether you earn \\$30,000 or \\$100,000.\n>\n> **Important:** The exact percentage change for large β₁ is 100 × (e^β₁ - 1), not 100 × β₁. The approximation works well when β₁ < 0.10.\n\n### Model 3: Log-Log Model\n\n**Specification:** ln(earnings) = β₀ + β₁ln(education) + ε\n\n**Interpretation:** β₁ = **elasticity** = percentage change in earnings for a 1% change in education\n\n**Note:** A \"1% increase in education\" is a bit artificial (what does 0.14 more years mean?), but this model captures diminishing returns to education.\n\n::: {#7951bf6c .cell execution_count=8}\n``` {.python .cell-code}\n# Model 3: Log-log\n# MODEL 3: LOG-LOG - ln(earnings) = β₀ + β₁ln(education)\n\nmodel_loglog = pf.feols('lnearn ~ lneduc', data=data_earnings)\n\n# Key results\nintercept_3 = model_loglog.coef()['Intercept']\nelasticity  = model_loglog.coef()['lneduc']\nr2_3        = model_loglog._r2\n\nprint(f\"Estimated equation: ln(earnings) = {intercept_3:.4f} + {elasticity:.4f} x ln(education)\")\nprint(f\"Elasticity: a 1% increase in education is associated with a {elasticity:.3f}% increase in earnings\")\nprint(f\"R-squared: {r2_3:.4f} ({r2_3*100:.1f}% of variation explained)\")\n\n# Full regression output\nmodel_loglog.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEstimated equation: ln(earnings) = 6.5454 + 1.4775 x ln(education)\nElasticity: a 1% increase in education is associated with a 1.478% increase in earnings\nR-squared: 0.2862 (28.6% of variation explained)\n###\n\nEstimation:  OLS\nDep. var.: lnearn\nsample: None = all\nInference:  iid\nObservations:  171\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |   2.5% |   97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|-------:|--------:|\n| Intercept     |      6.545 |        0.477 |    13.725 |      0.000 |  5.604 |   7.487 |\n| lneduc        |      1.478 |        0.179 |     8.233 |      0.000 |  1.123 |   1.832 |\n---\nRMSE: 0.524 R2: 0.286 \n```\n:::\n:::\n\n\n> **Key Concept 9.4: Interpreting Log-Log Model Coefficients**\n>\n> In the **log-log model** ln(y) = β₀ + β₁ln(x), the slope coefficient β₁ is the **elasticity** of y with respect to x:\n>\n> $$\\beta_1 = \\frac{\\%\\Delta y}{\\%\\Delta x}$$\n>\n> A 1% increase in x is associated with a β₁% change in y. Unlike semi-elasticity, elasticity is a **unit-free** measure — it does not depend on the units of measurement.\n>\n> **Economic interpretation:** If β₁ < 1, there are **diminishing returns** (each additional percent of x yields less than one percent of y). If β₁ > 1, there are **increasing returns**.\n\n### Model 4: Linear-Log Model\n\n**Specification:** earnings = β₀ + β₁ln(education) + ε\n\n**Interpretation:** β₁/100 = dollar change in earnings for a 1% increase in education\n\nThis model is less common but captures **diminishing returns** (additional years of education have decreasing marginal effects).\n\n::: {#50a527f2 .cell execution_count=9}\n``` {.python .cell-code}\n# Model 4: Linear-log\n# MODEL 4: LINEAR-LOG - earnings = β₀ + β₁ln(education)\n\nmodel_linlog = pf.feols('earnings ~ lneduc', data=data_earnings)\n\n# Key results\nintercept_4 = model_linlog.coef()['Intercept']\nslope_4     = model_linlog.coef()['lneduc']\nr2_4        = model_linlog._r2\n\nprint(f\"Estimated equation: earnings = {intercept_4:,.0f} + {slope_4:,.2f} x ln(education)\")\nprint(f\"A 1% increase in education is associated with a ${slope_4/100:,.2f} increase in annual earnings\")\nprint(f\"R-squared: {r2_4:.4f} ({r2_4*100:.1f}% of variation explained)\")\nprint(f\"Note: This model has the lowest R² among the four specifications\")\n\n# Full regression output\nmodel_linlog.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEstimated equation: earnings = -102,718 + 54,433.42 x ln(education)\nA 1% increase in education is associated with a $544.33 increase in annual earnings\nR-squared: 0.2307 (23.1% of variation explained)\nNote: This model has the lowest R² among the four specifications\n###\n\nEstimation:  OLS\nDep. var.: earnings\nsample: None = all\nInference:  iid\nObservations:  171\n\n| Coefficient   |    Estimate |   Std. Error |   t value |   Pr(>|t|) |        2.5% |      97.5% |\n|:--------------|------------:|-------------:|----------:|-----------:|------------:|-----------:|\n| Intercept     | -102718.169 |    20317.551 |    -5.056 |      0.000 | -142827.055 | -62609.283 |\n| lneduc        |   54433.416 |     7645.805 |     7.119 |      0.000 |   39339.829 |  69527.003 |\n---\nRMSE: 22323.877 R2: 0.231 \n```\n:::\n:::\n\n\n### Comparison of All Four Models\n\n::: {#eefdcc81 .cell execution_count=10}\n``` {.python .cell-code}\n# Create comparison table\n# MODEL COMPARISON SUMMARY\n\ncomparison_df = pd.DataFrame({\n    'Model': ['Linear', 'Log-linear', 'Log-log', 'Linear-log'],\n    'Specification': ['y ~ x', 'ln(y) ~ x', 'ln(y) ~ ln(x)', 'y ~ ln(x)'],\n    'Slope Coefficient': [\n        f\"{model_linear.coef().iloc[1]:,.2f}\",\n        f\"{model_loglin.coef().iloc[1]:.4f}\",\n        f\"{model_loglog.coef().iloc[1]:.4f}\",\n        f\"{model_linlog.coef().iloc[1]:,.2f}\"\n    ],\n    'Interpretation': [\n        f\"${model_linear.coef().iloc[1]:,.0f} per year\",\n        f\"{100*model_loglin.coef().iloc[1]:.1f}% per year\",\n        f\"{model_loglog.coef().iloc[1]:.2f}% per 1% change\",\n        f\"${model_linlog.coef().iloc[1]/100:,.0f} per 1% change\"\n    ],\n    'R²': [\n        f\"{model_linear._r2:.3f}\",\n        f\"{model_loglin._r2:.3f}\",\n        f\"{model_loglog._r2:.3f}\",\n        f\"{model_linlog._r2:.3f}\"\n    ]\n})\n\ncomparison_df.to_string(index=False)\n\n# WHICH MODEL IS BEST?\n# For this data\nprint(f\"  - Best fit (highest R²): Log-linear (R² = {model_loglin._r2:.3f})\")\nprint(f\"  Best fit (highest R²): Log-linear (R² = {model_loglin._r2:.3f})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  - Best fit (highest R²): Log-linear (R² = 0.334)\n  Best fit (highest R²): Log-linear (R² = 0.334)\n```\n:::\n:::\n\n\n> **Key Concept 9.5: Choosing the Right Functional Form**\n>\n> The choice between linear, log-linear, log-log, and linear-log specifications should be guided by:\n>\n> 1. **Economic theory** — Does the theory predict absolute or percentage effects?\n> 2. **Data properties** — Is the dependent variable right-skewed? Are both variables positive?\n> 3. **Model fit** — Which specification yields the highest R²?\n> 4. **Interpretation needs** — Do you need elasticities, semi-elasticities, or dollar amounts?\n>\n> **In practice:** The **log-linear model** is most common in economics because many economic relationships involve percentage changes (returns to education, inflation effects, price responses). When in doubt, start with log-linear.\n\n### Visualizing All Four Models\n\n::: {#b69844fe .cell execution_count=11}\n``` {.python .cell-code}\n# Create 2x2 comparison plot\nfig, axes = plt.subplots(2, 2, figsize=(16, 12))\n\n# Model 1: Linear\naxes[0, 0].scatter(data_earnings['education'], data_earnings['earnings'],\n                   alpha=0.5, s=20, color='#22d3ee')  # alpha = transparency, s = marker size\naxes[0, 0].plot(data_earnings['education'], model_linear.predict(),\n                color='#c084fc', linewidth=2, label=f'R² = {model_linear._r2:.3f}')\naxes[0, 0].set_xlabel('Education (years)', fontsize=11)\naxes[0, 0].set_ylabel('Earnings ($)', fontsize=11)\naxes[0, 0].set_title('Model 1: Linear\\ny = β₀ + β₁x\\nSlope: $5,021 per year',\n                     fontsize=12, fontweight='bold')\naxes[0, 0].legend()\naxes[0, 0].grid(True, alpha=0.3)\n\n# Model 2: Log-linear\naxes[0, 1].scatter(data_earnings['education'], data_earnings['lnearn'],\n                   alpha=0.5, s=20, color='#22d3ee')\naxes[0, 1].plot(data_earnings['education'], model_loglin.predict(),\n                color='#c084fc', linewidth=2, label=f'R² = {model_loglin._r2:.3f}')\naxes[0, 1].set_xlabel('Education (years)', fontsize=11)\naxes[0, 1].set_ylabel('ln(Earnings)', fontsize=11)\naxes[0, 1].set_title('Model 2: Log-linear\\nln(y) = β₀ + β₁x\\nSlope: 13.1% per year',\n                     fontsize=12, fontweight='bold')\naxes[0, 1].legend()\naxes[0, 1].grid(True, alpha=0.3)\n\n# Model 3: Log-log\naxes[1, 0].scatter(data_earnings['lneduc'], data_earnings['lnearn'],\n                   alpha=0.5, s=20, color='#22d3ee')\naxes[1, 0].plot(data_earnings['lneduc'], model_loglog.predict(),\n                color='#c084fc', linewidth=2, label=f'R² = {model_loglog._r2:.3f}')\naxes[1, 0].set_xlabel('ln(Education)', fontsize=11)\naxes[1, 0].set_ylabel('ln(Earnings)', fontsize=11)\naxes[1, 0].set_title('Model 3: Log-log\\nln(y) = β₀ + β₁ln(x)\\nElasticity: 1.48',\n                     fontsize=12, fontweight='bold')\naxes[1, 0].legend()\naxes[1, 0].grid(True, alpha=0.3)\n\n# Model 4: Linear-log\naxes[1, 1].scatter(data_earnings['lneduc'], data_earnings['earnings'],\n                   alpha=0.5, s=20, color='#22d3ee')\naxes[1, 1].plot(data_earnings['lneduc'], model_linlog.predict(),\n                color='#c084fc', linewidth=2, label=f'R² = {model_linlog._r2:.3f}')\naxes[1, 1].set_xlabel('ln(Education)', fontsize=11)\naxes[1, 1].set_ylabel('Earnings ($)', fontsize=11)\naxes[1, 1].set_title('Model 4: Linear-log\\ny = β₀ + β₁ln(x)\\nSlope: $545 per 1% change',\n                     fontsize=12, fontweight='bold')\naxes[1, 1].legend()\naxes[1, 1].grid(True, alpha=0.3)\n\nplt.suptitle('Four Model Specifications: Earnings and Education',\n             fontsize=14, fontweight='bold', y=1.00)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch09_Models_with_Natural_Logarithms_files/figure-html/cell-12-output-1.png){width=1526 height=1157}\n:::\n:::\n\n\n**What to look for across the four panels:**\n\n- **Model 1 (linear)**: Straight line fit, but residuals may be heteroskedastic\n- **Model 2 (log-linear)**: Best fit, captures curvature in original data\n- **Model 3 (log-log)**: Both axes logged, captures elasticity\n- **Model 4 (linear-log)**: Captures diminishing returns to education\n\n## 9.4 Further Uses: Exponential Growth\n\n**Application:** Modeling exponential growth in time series data\n\nMany economic series grow **exponentially** over time:\n$$x_t = x_0 \\times (1+r)^t$$\n\nWhere:\n\n- x₀ = initial value\n- r = constant growth rate\n- t = time period\n\n**Taking logarithms:**\n$$\\ln(x_t) = \\ln(x_0) + \\ln(1+r) \\times t \\approx \\ln(x_0) + r \\times t$$\n\n**Key insight:** Exponential growth in levels → **linear growth in logs**!\n\n**Regression model:**\n$$\\ln(x_t) = \\beta_0 + \\beta_1 \\times t + \\varepsilon$$\n\nThe slope β₁ directly estimates the growth rate r.\n\n**Example:** S&P 500 stock index 1927-2019\n\n::: {#7bb9205f .cell execution_count=12}\n``` {.python .cell-code}\n# Load S&P 500 data\ndata_sp500 = pd.read_stata(GITHUB_DATA_URL + 'AED_SP500INDEX.DTA')\n\n# S&P 500 INDEX DATA (1927-2019)\ndata_sp500[['year', 'sp500', 'lnsp500']].describe()\n\nprint(\"\\nFirst and last years:\")\ndata_sp500[['year', 'sp500', 'lnsp500']].head(3)\nprint(\"...\")\nprint(data_sp500[['year', 'sp500', 'lnsp500']].tail(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFirst and last years:\n...\n      year        sp500   lnsp500\n90  2017.0  2673.610107  7.891185\n91  2018.0  2506.850098  7.826782\n92  2019.0  3230.780029  8.080479\n```\n:::\n:::\n\n\n::: {#fcea76d5 .cell execution_count=13}\n``` {.python .cell-code}\n# Estimate exponential growth model\n# EXPONENTIAL GROWTH MODEL: ln(sp500) = β₀ + β₁(year)\n\nmodel_sp500 = pf.feols('lnsp500 ~ year', data=data_sp500)\n\n# Key results\nintercept_sp = model_sp500.coef()['Intercept']\ngrowth_rate  = model_sp500.coef()['year']\nr2_sp        = model_sp500._r2\n\nprint(f\"Estimated equation: ln(SP500) = {intercept_sp:.4f} + {growth_rate:.6f} x year\")\nprint(f\"Estimated annual growth rate: {100*growth_rate:.4f}% per year\")\nprint(f\"Rule of 72: doubles every {72/(100*growth_rate):.1f} years\")\nprint(f\"R-squared: {r2_sp:.4f} ({r2_sp*100:.1f}% of variation explained)\")\n\n# Full regression output\nmodel_sp500.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEstimated equation: ln(SP500) = -124.0933 + 0.065337 x year\nEstimated annual growth rate: 6.5337% per year\nRule of 72: doubles every 11.0 years\nR-squared: 0.9579 (95.8% of variation explained)\n###\n\nEstimation:  OLS\nDep. var.: lnsp500\nsample: None = all\nInference:  iid\nObservations:  93\n\n| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |     2.5% |    97.5% |\n|:--------------|-----------:|-------------:|----------:|-----------:|---------:|---------:|\n| Intercept     |   -124.093 |        2.833 |   -43.798 |      0.000 | -129.721 | -118.465 |\n| year          |      0.065 |        0.001 |    45.503 |      0.000 |    0.062 |    0.068 |\n---\nRMSE: 0.368 R2: 0.958 \n```\n:::\n:::\n\n\n> **Key Concept 9.6: Linearizing Exponential Growth**\n>\n> When a variable grows **exponentially** (x_t = x₀(1+r)^t), its logarithm grows **linearly**:\n>\n> $$\\ln(x_t) \\approx \\ln(x_0) + r \\times t$$\n>\n> This transformation is powerful because it converts a **nonlinear** growth pattern into a **linear** regression model, where the slope coefficient directly estimates the **constant growth rate** r.\n>\n> **Practical implication:** To estimate the average growth rate of any exponentially growing series (GDP, stock prices, population), simply regress ln(x) on time. The slope is the growth rate.\n\n### Visualizing Exponential Growth\n\n::: {#cfc51deb .cell execution_count=14}\n``` {.python .cell-code}\n# Create visualization showing exponential vs linear in logs\nfig, axes = plt.subplots(1, 2, figsize=(16, 6))\n\n# Panel A: Exponential growth in levels\n# Apply retransformation bias correction (Duan's smearing estimate)\nn = len(data_sp500)\nk = 2  # number of parameters: intercept + slope\nMSE = np.sum(model_sp500._u_hat**2) / (n - k)\npsp500 = np.exp(model_sp500.predict()) * np.exp(MSE/2)  # exp(MSE/2) corrects for log-retransformation bias\n\naxes[0].plot(data_sp500['year'], data_sp500['sp500'], linewidth=2,\n             label='Actual', color='#22d3ee')\naxes[0].plot(data_sp500['year'], psp500, linewidth=2, linestyle='--',\n             label='Fitted (exponential)', color='#c084fc')\naxes[0].set_xlabel('Year', fontsize=12)\naxes[0].set_ylabel('S&P 500 Index', fontsize=12)\naxes[0].set_title('Panel A: Exponential Growth in Levels',\n                  fontsize=13, fontweight='bold')\naxes[0].legend()\naxes[0].grid(True, alpha=0.3)\n\n# Panel B: Linear growth in logs\naxes[1].plot(data_sp500['year'], data_sp500['lnsp500'], linewidth=2,\n             label='Actual', color='#22d3ee')\naxes[1].plot(data_sp500['year'], model_sp500.predict(), linewidth=2,\n             linestyle='--', label='Fitted (linear)', color='#c084fc')\naxes[1].set_xlabel('Year', fontsize=12)\naxes[1].set_ylabel('ln(S&P 500 Index)', fontsize=12)\naxes[1].set_title('Panel B: Linear Growth in Logarithms',\n                  fontsize=13, fontweight='bold')\naxes[1].legend()\naxes[1].grid(True, alpha=0.3)\n\nplt.suptitle('S&P 500 Index: Exponential Growth Linearized by Logarithms',\n             fontsize=14, fontweight='bold', y=1.00)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch09_Models_with_Natural_Logarithms_files/figure-html/cell-15-output-1.png){width=1526 height=580}\n:::\n:::\n\n\n**What to look for in this comparison:**\n\n- **Left panel**: Exponential curve in levels — hard to model with a straight line\n- **Right panel**: Straight line in logs — easy to model with OLS\n- **The slope** of the line in the right panel directly estimates the average growth rate\n\n> **Key Concept 9.7: The Rule of 72**\n>\n> The **Rule of 72** provides a quick estimate of **doubling time** for compound growth:\n>\n> $$\\text{Doubling time} \\approx \\frac{72}{r}$$\n>\n> where r is the **percentage** growth rate. This approximation derives from the logarithmic identity: ln(2) ≈ 0.693, combined with ln(1+r) ≈ r for small r.\n>\n> **Examples:**\n> - S&P 500 at 6.5% growth → doubles every 72/6.5 ≈ 11 years\n> - GDP at 3% growth → doubles every 72/3 = 24 years\n> - Population at 1% growth → doubles every 72/1 = 72 years\n>\n> **Practical value:** The Rule of 72 converts growth rates into an intuitive time horizon without needing a calculator.\n\n## Key Takeaways\n\n**Key Takeaways:**\n\n1. **Natural logarithms** let us work with **proportionate changes** instead of absolute changes.\n   - Key approximation: Δln(x) ≈ Δx/x (proportionate change)\n   - 100 × Δln(x) ≈ percentage change in x\n   - This approximation is excellent for small changes (< 10%)\n\n2. **Four model specifications** give different interpretations:\n\n| Model | Specification | Interpretation of β₁ |\n|-------|---------------|---------------------|\n| **Linear** | y = β₀ + β₁x | Δy/Δx (absolute change) |\n| **Log-linear** | ln(y) = β₀ + β₁x | Semi-elasticity: (Δy/y)/Δx |\n| **Log-log** | ln(y) = β₀ + β₁ln(x) | Elasticity: (Δy/y)/(Δx/x) |\n| **Linear-log** | y = β₀ + β₁ln(x) | Δy/(Δx/x) |\n\n3. **Model selection** depends on economic theory, data properties, and interpretation needs:\n   - R² comparison (higher is better, but not the only criterion)\n   - Economic theory should guide functional form choice\n   - Log-linear is most common in applied economics (earnings, prices)\n\n4. **Earnings-Education results** illustrate the four specifications:\n   - **Linear:** Each year of education → \\$5,021 more earnings\n   - **Log-linear:** Each year of education → 13.1% more earnings (best fit, R² = 0.334)\n   - **Log-log:** 1% more education → 1.48% more earnings (elasticity)\n   - **Linear-log:** 1% more education → \\$545 more earnings\n\n5. **Exponential growth** becomes **linear in logs:**\n   - If x grows exponentially: x_t = x₀(1+r)^t\n   - Then ln(x) grows linearly: ln(x_t) ≈ ln(x₀) + r·t\n   - Regression slope directly estimates the growth rate\n   - S&P 500: 6.5% annual growth (1927-2019), doubling every 11 years\n\n6. **When to use logarithmic transformations:**\n   - Dependent variable is right-skewed (earnings, prices, firm size)\n   - Economic theory predicts percentage effects (elasticities)\n   - Multiplicative relationships between variables\n   - Exponential growth or decay patterns\n   - Not when variables can be zero or negative (ln is undefined)\n\n**Python Libraries and Code:**\n\nThis single code block reproduces the core workflow of Chapter 9. It is self-contained — copy it into an empty notebook and run it to review the complete pipeline from logarithmic approximations to semi-elasticity, elasticity, model comparison, and exponential growth estimation.\n\n```python\n# =============================================================================\n# CHAPTER 9 CHEAT SHEET: Models with Natural Logarithms\n# =============================================================================\n\n# --- Libraries ---\nimport numpy as np                        # logarithms and exponentials\nimport pandas as pd                       # data loading and manipulation\nimport matplotlib.pyplot as plt           # creating plots and visualizations\nimport pyfixest as pf                     # fast estimation with robust SEs\n\n# =============================================================================\n# STEP 1: Load the earnings-education dataset\n# =============================================================================\n# pd.read_stata() reads Stata .dta files directly from a URL\nurl_earn = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/AED_EARNINGS.DTA\"\ndata_earnings = pd.read_stata(url_earn)\n\nprint(f\"Dataset: {data_earnings.shape[0]} observations, {data_earnings.shape[1]} variables\")\n\n# =============================================================================\n# STEP 2: Logarithmic approximation — why economists use logs\n# =============================================================================\n# Key property: Δln(x) ≈ Δx/x (proportionate change)\n# Multiplying by 100 gives the percentage change\nx0, x1 = 40, 40.4\nexact = (x1 - x0) / x0\napprox = np.log(x1) - np.log(x0)\nprint(f\"Change from {x0} to {x1}:\")\nprint(f\"  Exact proportionate change: {exact:.6f} ({exact*100:.2f}%)\")\nprint(f\"  Log approximation Δln(x):   {approx:.6f} ({approx*100:.2f}%)\")\n\n# =============================================================================\n# STEP 3: Descriptive statistics and log transformations\n# =============================================================================\n# Create log-transformed variables for the regression models\ndata_earnings['lnearn'] = np.log(data_earnings['earnings'])\ndata_earnings['lneduc'] = np.log(data_earnings['education'])\n\nprint(data_earnings[['earnings', 'lnearn', 'education', 'lneduc']].describe().round(2))\n\n# =============================================================================\n# STEP 4: Estimate all four model specifications\n# =============================================================================\n# Each model answers a different economic question about earnings and education\n\n# Model 1: Linear — Δy = β₁Δx (dollar change per year of education)\nmodel_linear = pf.feols('earnings ~ education', data=data_earnings)\n\n# Model 2: Log-linear — 100β₁ ≈ % change in y per unit x (semi-elasticity)\nmodel_loglin = pf.feols('lnearn ~ education', data=data_earnings)\n\n# Model 3: Log-log — β₁ ≈ % change in y per % change in x (elasticity)\nmodel_loglog = pf.feols('lnearn ~ lneduc', data=data_earnings)\n\n# Model 4: Linear-log — β₁/100 ≈ dollar change per % change in x\nmodel_linlog = pf.feols('earnings ~ lneduc', data=data_earnings)\n\n# Print the most important model: log-linear (semi-elasticity)\nsemi_elast = model_loglin.coef()['education']\nprint(f\"Log-linear: each year of education → {100*semi_elast:.1f}% higher earnings\")\nprint(f\"Log-log elasticity: {model_loglog.coef()['lneduc']:.3f}\")\n\n# Full regression table for the log-linear model\nmodel_loglin.summary()\n\n# =============================================================================\n# STEP 5: Compare all four models side by side\n# =============================================================================\n# The comparison shows that model choice affects both R² and interpretation\nmodels = {\n    'Linear':     ('earnings ~ education',  model_linear,  'education', '${:,.0f} per year'),\n    'Log-linear': ('ln(y) ~ x',            model_loglin,  'education', '{:.1f}% per year'),\n    'Log-log':    ('ln(y) ~ ln(x)',         model_loglog,  'lneduc',   '{:.2f}% per 1%'),\n    'Linear-log': ('y ~ ln(x)',            model_linlog,  'lneduc',   '${:,.0f} per 1%'),\n}\n\nprint(f\"{'Model':<12} {'Specification':<16} {'Slope':>10} {'R²':>8}  Interpretation\")\nprint(\"-\" * 75)\nfor name, (spec, m, var, fmt) in models.items():\n    slope = m.coef()[var]\n    interp = fmt.format(100*slope if 'per year' in fmt and 'Log' in name else slope/100 if 'per 1%' in fmt and name == 'Linear-log' else slope)\n    print(f\"{name:<12} {spec:<16} {slope:>10.4f} {m._r2:>8.3f}  {interp}\")\n\n# =============================================================================\n# STEP 6: Scatter plot with the log-linear fitted line\n# =============================================================================\n# The log-linear model (semi-elasticity) provides the best fit for earnings data\nfig, ax = plt.subplots(figsize=(10, 6))\nax.scatter(data_earnings['education'], data_earnings['lnearn'], s=50, alpha=0.7)\nax.plot(data_earnings['education'], model_loglin.predict(),\n        color='red', linewidth=2, label='Fitted line')\nax.set_xlabel('Education (years)')\nax.set_ylabel('ln(Earnings)')\nax.set_title(f'Log-Linear Model: semi-elasticity = {semi_elast:.4f}  (R² = {model_loglin._r2:.3f})')\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n\n# =============================================================================\n# STEP 7: Exponential growth — S&P 500 and the Rule of 72\n# =============================================================================\n# Exponential growth in levels becomes linear in logs:\n# ln(x_t) ≈ ln(x₀) + r × t, where slope r = annual growth rate\nurl_sp500 = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/AED_SP500INDEX.DTA\"\ndata_sp500 = pd.read_stata(url_sp500)\n\nmodel_sp500 = pf.feols('lnsp500 ~ year', data=data_sp500)\ngrowth_rate = model_sp500.coef()['year']\n\nprint(f\"S&P 500 estimated growth rate: {100*growth_rate:.2f}% per year\")\nprint(f\"Rule of 72: doubles every {72/(100*growth_rate):.1f} years\")\nprint(f\"R-squared: {model_sp500._r2:.4f}\")\n\n# Visualize: exponential in levels vs. linear in logs\nfig, axes = plt.subplots(1, 2, figsize=(14, 5))\naxes[0].plot(data_sp500['year'], data_sp500['sp500'], linewidth=2)\naxes[0].set_xlabel('Year')\naxes[0].set_ylabel('S&P 500 Index')\naxes[0].set_title('Exponential Growth in Levels')\naxes[0].grid(True, alpha=0.3)\n\naxes[1].plot(data_sp500['year'], data_sp500['lnsp500'], linewidth=2)\naxes[1].plot(data_sp500['year'], model_sp500.predict(),\n             color='red', linewidth=2, linestyle='--', label='Fitted (linear)')\naxes[1].set_xlabel('Year')\naxes[1].set_ylabel('ln(S&P 500 Index)')\naxes[1].set_title(f'Linear in Logs: growth = {100*growth_rate:.2f}%/year')\naxes[1].legend()\naxes[1].grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n```\n\n**Try it yourself!** Copy this code into an empty Google Colab notebook and run it: [Open Colab](https://colab.research.google.com/notebooks/empty.ipynb)\n\n**Next Steps:**\n\n- **Chapter 10**: Extend to multiple regression with several explanatory variables\n- **Chapter 11**: Statistical inference for multiple regression models\n- **Chapter 15**: Further variable transformations (polynomials, interactions)\n\n---\n\n**Congratulations!** You now understand how to choose between model specifications, interpret coefficients in log models, and estimate elasticities and semi-elasticities. These tools are fundamental to empirical work in labor economics, industrial organization, macroeconomics, and development economics!\n\n> **Common Mistakes to Avoid**\n>\n> - **Misinterpreting log-level coefficients**: A one-unit change in X leads to a (b x 100)% change in Y, not b units\n> - **Forgetting that log(0) is undefined**: Log transformations require strictly positive values\n> - **Confusing log-log and log-level elasticities**: The interpretation depends on which variables are logged\n\n## Practice Exercises\n\n**Exercise 1: Logarithmic Approximation Accuracy**\n\nThe logarithmic approximation Δln(x) ≈ Δx/x works well for small changes. Test its accuracy:\n\na) Compute the exact proportionate change and the log approximation for x increasing from 100 to 101 (1% change). How close are they?\nb) Repeat for x increasing from 100 to 110 (10% change). Is the approximation still good?\nc) Repeat for x increasing from 100 to 150 (50% change). What happens to the approximation error?\nd) At what percentage change does the approximation error exceed 1 percentage point?\n\n**Exercise 2: Interpreting Semi-Elasticity**\n\nA researcher estimates the following log-linear model: ln(wage) = 1.50 + 0.085 × experience, where wage is hourly wage in dollars and experience is years of work experience.\n\na) Interpret the coefficient 0.085 in economic terms.\nb) What is the predicted percentage change in wages for a worker gaining 5 more years of experience?\nc) Calculate the exact percentage change using 100 × (e^(0.085×5) - 1). How does it compare to the approximation?\n\n**Exercise 3: Interpreting Elasticity**\n\nAn economist estimates a demand function: ln(Q) = 5.2 - 1.3 × ln(P), where Q is quantity demanded and P is price.\n\na) What is the price elasticity of demand? Is demand elastic or inelastic?\nb) If the price increases by 10%, what is the predicted percentage change in quantity demanded?\nc) Why is the log-log specification natural for demand analysis?\n\n**Exercise 4: Model Specification Choice**\n\nFor each research question below, recommend the most appropriate model specification (linear, log-linear, log-log, or linear-log) and explain your reasoning:\n\na) How much does an additional bedroom add to house price (in dollars)?\nb) What is the percentage return to each additional year of education?\nc) What is the price elasticity of demand for gasoline?\nd) How does GDP growth relate to years since a policy reform?\n\n**Exercise 5: Exponential Growth and Rule of 72**\n\nA country's real GDP per capita was \\$5,000 in 1990 and grew at an average rate of 4% per year.\n\na) Using the Rule of 72, approximately when did GDP per capita reach \\$10,000?\nb) Write the exponential growth equation for this country's GDP.\nc) What regression model would you estimate to find the growth rate from data? Write the specification.\nd) If another country grew at 2% per year, how many times longer would it take to double its GDP?\n\n**Exercise 6: Comparing Model Specifications with Data**\n\nUsing the earnings-education results from Section 9.3:\n\na) A worker has 12 years of education. Using the linear model, predict their earnings. Using the log-linear model, predict their earnings (hint: you need to exponentiate).\nb) Repeat for a worker with 18 years of education. Which model gives a larger predicted difference between 12 and 18 years?\nc) The log-linear model predicts a 13.1% increase per year of education regardless of current earnings. Explain why this is economically more appealing than a fixed dollar increase.\nd) Why can't we directly compare R² values between the linear model (R² = 0.289) and the log-linear model (R² = 0.334)?\n\n## Case Studies\n\n### Case Study: Logarithmic Models for Global Labor Productivity\n\nIn this case study, you'll apply logarithmic model specifications to analyze **cross-country labor productivity** — a central question in development economics. You'll use the same Convergence Clubs dataset from earlier chapters, but now focus on how log transformations reveal economic relationships that linear models miss.\n\n**Research Question:** How do logarithmic transformations improve our understanding of cross-country productivity relationships and growth patterns?\n\n**Background:**\nLabor productivity varies enormously across countries — from less than \\$1,000 per worker in the poorest nations to over \\$100,000 in the richest. This extreme right-skewness makes logarithmic transformations essential for meaningful analysis. Development economists use semi-elasticities and elasticities to measure how factors like human capital and physical capital contribute to productivity differences.\n\n**Dataset:**\nWe'll use the **Mendez Convergence Clubs dataset** containing:\n\n- **country**: Country name (108 countries)\n- **year**: Year of observation (1990-2014)\n- **lp**: Labor productivity (output per worker, in dollars)\n- **rk**: Capital per worker (physical capital stock, in thousands of dollars)\n- **hc**: Human capital index (based on years of schooling and returns to education)\n\n::: {#bebb22f1 .cell execution_count=15}\n``` {.python .cell-code}\n# Load the Convergence Clubs dataset\nurl_mendez = \"https://raw.githubusercontent.com/quarcs-lab/mendez2020-convergence-clubs-code-data/master/assets/dat.csv\"\ndata_cc = pd.read_csv(url_mendez)\n\n# CONVERGENCE CLUBS DATASET\nprint(f\"Observations: {len(data_cc)}\")\nprint(f\"Countries: {data_cc['country'].nunique()}\")\nprint(f\"Years: {data_cc['year'].min():.0f} to {data_cc['year'].max():.0f}\")\nprint(f\"\\nVariables: {list(data_cc.columns)}\")\n\nprint(\"\\nFirst 10 observations:\")\ndata_cc[['country', 'year', 'lp', 'kl', 'h']].head(10)\n```\n:::\n\n\n### How to Use These Tasks\n\n1. **Read** each task carefully before starting\n2. **Write your code** in the provided cells (replace `_____` blanks in guided tasks)\n3. **Run your code** to see results\n4. **Answer the questions** by interpreting your output\n5. **Check your understanding** against the Key Concepts\n\n**Progressive difficulty:**\n\n- Tasks 1-2: **Guided** (fill in blanks with `_____`)\n- Tasks 3-4: **Semi-guided** (partial code structure provided)\n- Tasks 5-6: **Independent** (write from outline)\n\n**Tip:** Type the code rather than copying — it helps reinforce the concepts!\n\n#### Task 1: Explore Productivity Data (Guided)\n\n**Objective:** Understand why logarithmic transformations are essential for cross-country productivity data.\n\n**Connection:** Section 9.1 (Natural Logarithm Function)\n\n**Your task:** Filter the data to 2014, compute summary statistics for productivity in levels and logs, and compare the distributions.\n\na) What is the ratio of the highest to lowest labor productivity? What does this tell you about skewness?\nb) How does the standard deviation change after log transformation?\nc) Compare the mean and median in levels vs. logs. Which distribution is more symmetric?\n\n```python\n# Task 1: Explore Productivity Data (Guided)\n# Filter to 2014 cross-section\ndata_2014 = data_cc[data_cc['year'] == _____].copy()\nprint(f\"Countries in 2014: {len(data_2014)}\")\n\n# Create log-transformed variable\ndata_2014['ln_lp'] = np.log(_____)\n\n# Summary statistics: levels vs logs\n# LABOR PRODUCTIVITY: LEVELS VS. LOGS\nprint(\"\\nIn levels (lp):\")\ndata_2014['lp'].describe()\nprint(f\"\\nSkewness: {data_2014['lp'].skew():.3f}\")\n\nprint(\"\\nIn logarithms (ln_lp):\")\ndata_2014['ln_lp'].describe()\nprint(f\"\\nSkewness: {data_2014['_____'].skew():.3f}\")\n\n# Ratio of highest to lowest\nprint(f\"\\nMax/Min ratio: {data_2014['lp'].max() / data_2014['lp'].min():.1f}x\")\n```\n\n#### Task 2: Log-Linear Model for Productivity (Guided)\n\n**Objective:** Estimate a log-linear model to measure the semi-elasticity of productivity with respect to human capital.\n\n**Connection:** Section 9.2 (Semi-Elasticities)\n\n**Your task:** Estimate ln(lp) = β₀ + β₁ × hc and interpret the coefficient as a semi-elasticity.\n\na) What is the estimated semi-elasticity of productivity with respect to human capital?\nb) By what percentage does productivity increase for each additional unit of the human capital index?\nc) Is the coefficient statistically significant at the 5% level?\n\n```python\n# Task 2: Log-Linear Model for Productivity (Guided)\n# Estimate: ln(lp) = β₀ + β₁ × h\nmodel_hc = pf.feols('_____ ~ _____', data=data_2014)\n\n# LOG-LINEAR MODEL: ln(productivity) ~ human capital\nmodel_hc.summary()\n\n# Interpret the semi-elasticity\nbeta_hc = model_hc.coef()['h']\nprint(f\"\\nSemi-elasticity: {beta_hc:.4f}\")\nprint(f\"Interpretation: Each unit increase in human capital is associated with\")\nprint(f\"  a {100*beta_hc:.1f}% _____ in labor productivity.\")\nprint(f\"\\nR² = {model_hc._r2:.3f}\")\n```\n\n#### Task 3: Comparing Model Specifications (Semi-guided)\n\n**Objective:** Estimate all four model specifications using productivity and capital per worker, then compare.\n\n**Connection:** Section 9.3 (Example with four models)\n\n**Your tasks:**\n\na) Estimate four models: linear (lp ~ rk), log-linear (ln_lp ~ rk), log-log (ln_lp ~ ln_rk), and linear-log (lp ~ ln_rk)\nb) Create a comparison table showing the specification, slope coefficient, interpretation, and R² for each model\nc) Which model provides the best fit? Which provides the most economically meaningful interpretation?\nd) Why might the log-log specification be particularly appropriate for the productivity-capital relationship?\n\n::: {#d5bb236d .cell execution_count=16}\n``` {.python .cell-code}\n# Task 3: Comparing Model Specifications (Semi-guided)\n# Create log-transformed variables\ndata_2014['ln_kl'] = np.log(data_2014['kl'])\n\n# Estimate four models (fill in the formulas)\nm1_linear  = pf.feols('lp ~ kl', data=data_2014)\nm2_loglin  = pf.feols('ln_lp ~ kl', data=data_2014)\nm3_loglog  = pf.feols('ln_lp ~ ln_kl', data=data_2014)\nm4_linlog  = pf.feols('lp ~ ln_kl', data=data_2014)\n\n# Create comparison table\n# Hint: Follow the pattern from Section 9.3\n# MODEL COMPARISON: Productivity and Capital\n\n# Your comparison table here\n# ...\n```\n:::\n\n\n> **Key Concept 9.8: Functional Form and Cross-Country Comparisons**\n>\n> When analyzing cross-country data, **logarithmic models** are essential because:\n>\n> 1. **Skewed distributions** — Economic variables like GDP, productivity, and capital vary by factors of 100x or more across countries. Log transformations compress this range.\n> 2. **Multiplicative relationships** — Production functions in economics are multiplicative (Y = A × K^α × L^β), which become linear in logs.\n> 3. **Meaningful comparisons** — Percentage differences are more meaningful than absolute differences when comparing Malawi to the United States.\n>\n> **In practice:** The log-log specification is standard in cross-country growth analysis because the slope coefficient directly estimates the **output elasticity of capital** — a key parameter in growth theory.\n\n#### Task 4: Elasticity of Productivity with Respect to Capital (Semi-guided)\n\n**Objective:** Estimate the elasticity of labor productivity with respect to capital and interpret it in the context of economic growth theory.\n\n**Connection:** Section 9.2 (Elasticities)\n\n**Your tasks:**\n\na) Estimate the log-log model: ln(lp) = β₀ + β₁ × ln(rk). Report β₁ and R².\nb) Interpret β₁ as an elasticity. Is there evidence of diminishing returns to capital (β₁ < 1)?\nc) Construct a 95% confidence interval for the elasticity. Does it include 1?\nd) In growth theory, the output elasticity of capital is often assumed to be about 1/3. Test H₀: β₁ = 0.33 against H₁: β₁ ≠ 0.33.\n\n::: {#54ab553b .cell execution_count=17}\n``` {.python .cell-code}\n# Task 4: Elasticity of Productivity (Semi-guided)\n# Use the log-log model from Task 3\n\n# LOG-LOG MODEL: ln(productivity) ~ ln(capital per worker)\nm3_loglog.summary()\n\n# Elasticity and confidence interval\nelasticity = m3_loglog.coef()['ln_rk']\nci = m3_loglog.confint().loc['ln_rk']\nprint(f\"\\nElasticity: {elasticity:.4f}\")\nprint(f\"95% CI: [{ci.iloc[0]:.4f}, {ci.iloc[1]:.4f}]\")\n\n# Test H0: beta = 0.33\n# Your hypothesis test here\n# ...\n```\n:::\n\n\n#### Task 5: Productivity Growth Rates (Independent)\n\n**Objective:** Estimate exponential growth rates for labor productivity across countries and apply the Rule of 72.\n\n**Connection:** Section 9.4 (Exponential Growth)\n\n**Your tasks:**\n\na) Compute the average labor productivity across all countries for each year (1990-2014)\nb) Estimate the exponential growth model: ln(avg_lp) = β₀ + β₁ × year. What is the estimated average annual growth rate?\nc) Apply the Rule of 72: approximately how many years does it take for average global labor productivity to double?\nd) Repeat the growth rate estimation for two regions or groups of countries (e.g., high-income vs. low-income). Do growth rates differ?\n\n::: {#844cf96e .cell execution_count=18}\n``` {.python .cell-code}\n# Task 5: Productivity Growth Rates (Independent)\n# Compute average productivity per year\n\n# Your code here\n# ...\n```\n:::\n\n\n#### Task 6: Development Policy Brief (Independent)\n\n**Objective:** Synthesize your findings into a policy-relevant summary.\n\n**Connection:** All sections\n\n**Your task:**\nWrite a 200-300 word summary analyzing cross-country labor productivity using logarithmic models. Your brief should include:\n\n1. **Data description:** How many countries, what time period, key variables\n2. **Model selection:** Which logarithmic specification best captures the productivity-capital relationship and why\n3. **Key findings:** Elasticity estimates, semi-elasticity of human capital, growth rates\n4. **Policy implications:** What do these results suggest for developing countries seeking to increase productivity?\n\n### Your Development Policy Brief\n\n*(Write your 200-300 word summary here)*\n\n---\n\n> **Key Concept 9.9: Logarithmic Models in Development Economics**\n>\n> Logarithmic model specifications are the **standard tool** in development economics for analyzing cross-country differences because:\n>\n> - **Semi-elasticities** measure the percentage return to factors like education and human capital — directly informing policy about where to invest\n> - **Elasticities** from log-log models estimate production function parameters (output elasticity of capital) — testing whether countries face diminishing returns\n> - **Growth rates** from log-time regressions enable comparisons across countries growing at very different speeds\n>\n> **The bottom line:** Without logarithmic transformations, cross-country analysis would be dominated by a few rich outliers and miss the economic relationships that matter for development policy.\n\n### What You've Learned from This Case Study\n\n**Congratulations!** You've applied logarithmic model specifications to real cross-country economic data.\n\n**Statistical Skills:**\n\n- Applied log transformations to highly skewed cross-country data\n- Estimated and compared all four model specifications (linear, log-linear, log-log, linear-log)\n- Interpreted semi-elasticities (human capital → productivity)\n- Interpreted elasticities (capital → productivity, with diminishing returns)\n- Estimated exponential growth rates and applied the Rule of 72\n\n**Economic Insights:**\n\n- Cross-country productivity distributions are highly right-skewed, requiring log transformations\n- Human capital and physical capital both contribute to productivity, but with diminishing returns\n- Log-log models connect directly to production function theory in economics\n- Growth rates vary substantially across countries and regions\n\n**Next Steps:**\n\n- **Chapter 10**: Add multiple explanatory variables simultaneously (multiple regression)\n- **Chapter 11**: Test joint hypotheses about capital AND human capital effects\n\n",
    "supporting": [
      "ch09_Models_with_Natural_Logarithms_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}