{
  "hash": "8d46c3bff35d7640236e397acd56523a",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 14. Regression with Indicator Variables\nexecute:\n  enabled: true\n  warning: false\n---\n\n\n**metricsAI: An Introduction to Econometrics with Python and AI in the Cloud**\n\n*[Carlos Mendez](https://carlos-mendez.org)*\n\n<img src=\"https://raw.githubusercontent.com/quarcs-lab/metricsai/main/images/ch14_visual_summary.jpg\" alt=\"Chapter 14 Visual Summary\" width=\"100%\">\n\nThis notebook provides an interactive introduction to regression with indicator variables (also called dummy variables or categorical variables). All code runs directly in Google Colab without any local setup.\n\n[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/quarcs-lab/metricsai/blob/main/notebooks_colab/ch14_Regression_with_Indicator_Variables.ipynb)\n<div class=\"chapter-resources\">\n<a href=\"https://www.youtube.com/watch?v=Rkx1cY8_BBY\" target=\"_blank\" class=\"resource-btn\">🎬 AI Video</a>\n<a href=\"https://carlos-mendez.my.canva.site/s14-regression-with-indicator-variables-pdf\" target=\"_blank\" class=\"resource-btn\">✨ AI Slides</a>\n<a href=\"https://cameron.econ.ucdavis.edu/aed/traedv1_14\" target=\"_blank\" class=\"resource-btn\">📊 Cameron Slides</a>\n<a href=\"https://app.edcafe.ai/quizzes/69786a6a2f5d08069e04cf09\" target=\"_blank\" class=\"resource-btn\">✏️ Quiz</a>\n<a href=\"https://app.edcafe.ai/chatbots/6978a2782f5d08069e071ecb\" target=\"_blank\" class=\"resource-btn\">🤖 AI Tutor</a>\n</div>\n\n\n## Chapter Overview\n\nThis chapter focuses on regression analysis when some regressors are indicator variables. Indicator variables are binary (0/1) variables that record whether an observation falls into a particular category.\n\n### What You'll Learn\n\nBy the end of this chapter, you will be able to:\n\n1. Understand indicator (dummy) variables and their role in regression analysis\n2. Interpret regression coefficients when regressors are categorical variables\n3. Use indicator variables to compare group means and test for differences\n4. Understand the relationship between regression on indicators and t-tests/ANOVA\n5. Incorporate indicator variables alongside continuous regressors to control for categories\n6. Create and interpret interaction terms between indicators and continuous variables\n7. Apply the dummy variable trap rule when using sets of mutually exclusive indicators\n8. Choose appropriate base categories and interpret coefficients relative to the base\n9. Conduct joint F-tests for the significance of sets of indicator variables\n10. Apply indicator variable techniques to real earnings data\n\n### Chapter Outline\n\n- **14.1** Indicator Variables: Single Binary Variable\n- **14.2** Indicator Variable with Additional Regressors\n- **14.3** Interactions with Indicator Variables\n- **14.4** Testing for Structural Change\n- **14.5** Sets of Indicator Variables\n- **Key Takeaways** -- Chapter review and consolidated lessons\n- **Practice Exercises** -- Reinforce your understanding\n- **Case Studies** -- Apply indicator variables to cross-country data\n\n**Dataset used:**\n\n- **AED_EARNINGS_COMPLETE.DTA**: 872 full-time workers aged 25-65 in 2000\n\n**Key economic questions:**\n\n- Is there a gender earnings gap? How large is it after controlling for education and experience?\n- How do the returns to education differ by gender?\n- Do earnings differ across types of workers (self-employed, private, government)?\n- Can we test for structural differences between groups?\n\n**Estimated time:** 90-120 minutes\n\n## Setup\n\nFirst, we import the necessary Python packages and configure the environment for reproducibility. All data will stream directly from GitHub.\n\n::: {#a77d9574 .cell execution_count=1}\n``` {.python .cell-code}\n# Import required packages\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nimport statsmodels.api as sm\nfrom statsmodels.formula.api import ols\nfrom scipy import stats\nfrom scipy.stats import f_oneway\nfrom statsmodels.stats.anova import anova_lm\nimport random\nimport os\n\n# Set random seeds for reproducibility\nRANDOM_SEED = 42\nrandom.seed(RANDOM_SEED)\nnp.random.seed(RANDOM_SEED)\nos.environ['PYTHONHASHSEED'] = str(RANDOM_SEED)\n\n# GitHub data URL\nGITHUB_DATA_URL = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/\"\n\n# Set plotting style (dark theme matching book design)\nplt.style.use('dark_background')\nsns.set_style(\"darkgrid\")\nplt.rcParams.update({\n    'axes.facecolor': '#1a2235',\n    'figure.facecolor': '#12162c',\n    'grid.color': '#3a4a6b',\n    'figure.figsize': (10, 6),\n    'text.color': 'white',\n    'axes.labelcolor': 'white',\n    'xtick.color': 'white',\n    'ytick.color': 'white',\n    'axes.edgecolor': '#1a2235',\n})\n\n# Chapter 14: Regression With Indicator Variables\n# Setup complete! Ready to explore regression with indicator variables.\n```\n:::\n\n\n### Data Preparation\n\nWe'll work with the earnings dataset which contains information on 872 full-time workers.\n\n**Key variables:**\n\n- **earnings**: Annual earnings in dollars\n- **gender**: 1=female, 0=male\n- **education**: Years of schooling\n- **age**: Age in years\n- **hours**: Usual hours worked per week\n- **dself**: 1=self-employed, 0=not\n- **dprivate**: 1=private sector employee, 0=not\n- **dgovt**: 1=government sector employee, 0=not\n- **genderbyeduc**: Gender × Education interaction\n- **genderbyage**: Gender × Age interaction\n- **genderbyhours**: Gender × Hours interaction\n\n::: {#3828220b .cell execution_count=2}\n``` {.python .cell-code}\n# Load earnings data\ndata = pd.read_stata(GITHUB_DATA_URL + 'AED_EARNINGS_COMPLETE.DTA')\n\nprint(\"Data structure:\")\nprint(f\"  Observations: {len(data)}\")\nprint(f\"  Variables: {len(data.columns)}\")\n\nprint(\"\\nVariable descriptions:\")\nvariables = ['earnings', 'gender', 'education', 'genderbyeduc', 'age',\n             'genderbyage', 'hours', 'genderbyhours', 'dself', 'dprivate', 'dgovt']\n\nfor var in variables:\n    print(f\"  {var}: {data[var].dtype}\")\n\nprint(\"\\nSummary statistics:\")\ndata[variables].describe()\n\nprint(\"\\nNote on indicator variables:\")\n# gender: 1=female, 0=male\n# dself: 1=self-employed, 0=not\n# dprivate: 1=private sector, 0=not\n# dgovt: 1=government, 0=not\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData structure:\n  Observations: 872\n  Variables: 45\n\nVariable descriptions:\n  earnings: float32\n  gender: int8\n  education: float32\n  genderbyeduc: float32\n  age: int16\n  genderbyage: float32\n  hours: int8\n  genderbyhours: float32\n  dself: float32\n  dprivate: float32\n  dgovt: float32\n\nSummary statistics:\n\nNote on indicator variables:\n```\n:::\n:::\n\n\n## 14.1: Indicator Variables - Single Binary Variable\n\nAn **indicator variable** (also called dummy variable or binary variable) takes only two values:\n\n$$d = \\begin{cases}\n1 & \\text{if in the category} \\\\\n0 & \\text{otherwise}\n\\end{cases}$$\n\n### Simple Regression on Single Indicator\n\nWhen we regress $y$ on just an intercept and an indicator variable:\n\n$$\\hat{y} = b + a \\cdot d$$\n\nThe predicted value takes only two values:\n\n$$\\hat{y}_i = \\begin{cases}\nb + a & \\text{if } d_i = 1 \\\\\nb & \\text{if } d_i = 0\n\\end{cases}$$\n\n**Key result**: For OLS regression:\n\n- $b = \\bar{y}_0$ (mean of $y$ when $d=0$)\n- $a = \\bar{y}_1 - \\bar{y}_0$ (difference in means)\n\n**Interpretation**: The slope coefficient equals the difference in group means.\n\n### Example: Earnings and Gender\n\nLet's examine whether there's a gender earnings gap.\n\n::: {#365e5ac4 .cell execution_count=3}\n``` {.python .cell-code}\n# 14.1: Regression On Single Indicator Variable\n\n# Summary statistics by gender\n# Table 14.1: Earnings by Gender\n\nprint(\"\\nFemale (gender=1):\")\nfemale_stats = data[data['gender'] == 1]['earnings'].describe()\nprint(female_stats)\n\nprint(\"\\nMale (gender=0):\")\nmale_stats = data[data['gender'] == 0]['earnings'].describe()\nprint(male_stats)\n\n# Calculate means\nmean_female = data[data['gender'] == 1]['earnings'].mean()\nmean_male = data[data['gender'] == 0]['earnings'].mean()\ndiff_means = mean_female - mean_male\n\n# Difference in Means\nprint(f\"  Mean earnings (Female): ${mean_female:,.2f}\")\nprint(f\"  Mean earnings (Male): ${mean_male:,.2f}\")\nprint(f\"  Difference: ${diff_means:,.2f}\")\nprint(f\"\\n  Interpretation: Females earn ${abs(diff_means):,.2f} less than males on average.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFemale (gender=1):\ncount       378.000000\nmean      47079.894531\nstd       31596.724609\nmin        4000.000000\n25%       27475.000000\n50%       41000.000000\n75%       56000.000000\nmax      322000.000000\nName: earnings, dtype: float64\n\nMale (gender=0):\ncount       494.000000\nmean      63476.316406\nstd       61713.210938\nmin        5000.000000\n25%       30000.000000\n50%       48000.000000\n75%       75000.000000\nmax      504000.000000\nName: earnings, dtype: float64\n  Mean earnings (Female): $47,079.89\n  Mean earnings (Male): $63,476.32\n  Difference: $-16,396.42\n\n  Interpretation: Females earn $16,396.42 less than males on average.\n```\n:::\n:::\n\n\n### OLS Regression: Earnings on Gender\n\nNow let's estimate the regression model:\n\n$$\\text{earnings} = \\beta_1 + \\alpha \\cdot \\text{gender} + u$$\n\nWe'll use **heteroskedasticity-robust standard errors** (HC1) for valid inference.\n\n::: {#3d2e13f6 .cell execution_count=4}\n``` {.python .cell-code}\n# Regression models: Gender and earnings\n\n# Model 1: Gender only\n# Model 1: earnings ~ gender\nmodel1 = ols('earnings ~ gender', data=data).fit(cov_type='HC1')\n\n# Key results\nintercept_m1 = model1.params['Intercept']\ngender_coef  = model1.params['gender']\nr2_m1        = model1.rsquared\n\nprint(f\"Estimated equation: earnings = {intercept_m1:,.0f} + ({gender_coef:,.0f}) x gender\")\nprint(f\"Gender gap: females earn ${abs(gender_coef):,.0f} less than males on average\")\nprint(f\"R-squared: {r2_m1:.4f} ({r2_m1*100:.1f}% of variation explained)\")\n\n# Full regression output\nmodel1.summary()\n\nprint(f\"\\nInterpretation:\")\nprint(f\"  Intercept: ${model1.params['Intercept']:,.2f} (mean for males)\")\nprint(f\"  Gender coefficient: ${model1.params['gender']:,.2f} (difference for females)\")\nprint(f\"  Females earn ${abs(model1.params['gender']):,.2f} less than males on average\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEstimated equation: earnings = 63,476 + (-16,396) x gender\nGender gap: females earn $16,396 less than males on average\nR-squared: 0.0249 (2.5% of variation explained)\n\nInterpretation:\n  Intercept: $63,476.32 (mean for males)\n  Gender coefficient: $-16,396.42 (difference for females)\n  Females earn $16,396.42 less than males on average\n```\n:::\n:::\n\n\n> **Key Concept 14.1: Indicator Variables and Difference in Means**\n>\n> When regressing $y$ on just an intercept and a single indicator $d$, the fitted model is $\\hat{y} = b + ad$. The intercept $b$ equals the mean of $y$ when $d=0$, and the slope $a$ equals the difference in means $(\\bar{y}_1 - \\bar{y}_0)$. Thus, **regression on an indicator variable is equivalent to a difference-in-means test**.\n\n---\n\n### Understanding the Gender Earnings Gap\n\nThe regression results reveal a **statistically significant gender earnings gap** of approximately **-\\$16,000**. Let's break down what this means:\n\n**Key Findings:**\n\n1. **Intercept ($b_1$) ≈ \\$68,000**: This represents the **mean earnings for males** (when gender = 0). We can verify this matches the actual mean earnings for males in the sample.\n\n2. **Gender coefficient ($\\alpha$) ≈ -\\$16,000**: This is the **difference in mean earnings** between females and males. Specifically:\n - Females earn approximately **\\$16,000 less** than males on average\n - This is the **unconditional (raw) gender gap** - it doesn't account for differences in education, experience, or other factors\n\n3. **Statistical Significance**: The t-statistic is highly significant (p < 0.001), meaning we can confidently reject the null hypothesis that there's no gender difference in earnings.\n\n**Important Interpretation:**\n\n- This regression simply decomposes the sample into two groups and compares their means\n- The coefficient on gender equals the difference: $\\bar{y}_{female} - \\bar{y}_{male}$\n- This is a **descriptive** finding, not necessarily **causal** - the gap may reflect differences in education, occupation, hours worked, discrimination, or other factors\n- To understand the **adjusted** gender gap (controlling for observable characteristics), we need to add additional regressors\n\n**Connection to t-test:**\n\n- This regression is mathematically equivalent to a two-sample t-test\n- The regression framework allows us to easily extend the model by adding control variables\n\n### Comparison with t-test\n\nRegression with a single indicator variable is equivalent to a two-sample t-test.\n\n**Two approaches:**\n\n1. **Welch's t-test** (unequal variances): Similar to regression with robust SEs\n2. **Classical t-test** (equal variances): Identical to regression with default SEs\n\n::: {#73be583a .cell execution_count=5}\n``` {.python .cell-code}\n# Comparison with t-tests\n\n# Extract earnings by gender\nfemale_earnings = data[data['gender'] == 1]['earnings']\nmale_earnings = data[data['gender'] == 0]['earnings']\n\n# Welch's t-test (unequal variances)\nprint(\"\\n1. Welch's t-test (unequal variances):\")\nt_stat_welch, p_value_welch = stats.ttest_ind(female_earnings, male_earnings, equal_var=False)\nprint(f\"  t-statistic: {t_stat_welch:.4f}\")\nprint(f\"  p-value: {p_value_welch:.6f}\")\nprint(f\"  Note: Similar to regression with robust SEs\")\n\n# Classical t-test (equal variances)\nprint(\"\\n2. Classical t-test (equal variances):\")\nt_stat_classical, p_value_classical = stats.ttest_ind(female_earnings, male_earnings, equal_var=True)\nprint(f\"  t-statistic: {t_stat_classical:.4f}\")\nprint(f\"  p-value: {p_value_classical:.6f}\")\n\n# Regression with default SEs\nprint(\"\\n3. Regression with default (homoskedastic) SEs:\")\nmodel_gender_default = ols('earnings ~ gender', data=data).fit()\nprint(f\"  t-statistic: {model_gender_default.tvalues['gender']:.4f}\")\nprint(f\"  p-value: {model_gender_default.pvalues['gender']:.6f}\")\nprint(f\"  Note: IDENTICAL to classical t-test with equal variances\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n1. Welch's t-test (unequal variances):\n  t-statistic: -5.0964\n  p-value: 0.000000\n  Note: Similar to regression with robust SEs\n\n2. Classical t-test (equal variances):\n  t-statistic: -4.7139\n  p-value: 0.000003\n\n3. Regression with default (homoskedastic) SEs:\n  t-statistic: -4.7139\n  p-value: 0.000003\n  Note: IDENTICAL to classical t-test with equal variances\n```\n:::\n:::\n\n\n**Key insight:**\n\n- Classical t-test = Regression with default SEs (assuming equal variances)\n- Welch's t-test = Regression with robust SEs (allowing unequal variances)\n\n> **Key Concept 14.2: Regression vs. Specialized Test Methods**\n>\n> Specialized difference-in-means methods (like Welch's t-test) and regression on an indicator give the **same point estimate** but slightly different standard errors. Regression uses $se(\\hat{a})$ from the model, while the t-test uses $se(\\bar{y}_1 - \\bar{y}_0) = \\sqrt{s_1^2/n_1 + s_0^2/n_0}$. Both are valid; regression is more flexible when adding control variables.\n\n## 14.2: Indicator Variable with Additional Regressors\n\nThe raw difference in earnings by gender may be partly explained by other factors (e.g., education, experience, hours worked).\n\n### Model with Additional Regressors\n\n$$y = \\beta_1 + \\beta_2 x + \\alpha d + u$$\n\nThe fitted model:\n\n$$\\hat{y}_i = \\begin{cases}\nb_1 + b_2 x_i + a & \\text{if } d_i = 1 \\\\\nb_1 + b_2 x_i & \\text{if } d_i = 0\n\\end{cases}$$\n\n**Interpretation**: The coefficient $a$ measures the difference in $y$ across categories **after controlling** for the additional variables.\n\n### Progressive Model Building\n\nWe'll estimate five models of increasing complexity:\n\n1. Gender only\n2. Gender + Education\n3. Gender + Education + (Gender × Education)\n4. Add Age and Hours controls\n5. Full interactions with all variables\n\n::: {#7b733a82 .cell execution_count=6}\n``` {.python .cell-code}\n# Progressive Model Building\n\n# Model 2: Gender + Education\n# Model 2: earnings ~ gender + education\nmodel2 = ols('earnings ~ gender + education', data=data).fit(cov_type='HC1')\nmodel2.summary()\n\n# Model 3: Gender + Education + Interaction\n# Model 3: earnings ~ gender + education + genderbyeduc\nmodel3 = ols('earnings ~ gender + education + genderbyeduc', data=data).fit(cov_type='HC1')\nmodel3.summary()\n\n# Model 4: Add Age and Hours\n# Model 4: earnings ~ gender + education + genderbyeduc + age + hours\nmodel4 = ols('earnings ~ gender + education + genderbyeduc + age + hours', data=data).fit(cov_type='HC1')\nmodel4.summary()\n\n# Model 5: Full interactions\nmodel5 = ols('earnings ~ gender + education + genderbyeduc + age + genderbyage + hours + genderbyhours',\n             data=data).fit(cov_type='HC1')\nmodel5.summary()\n\n# Joint F-test for all gender terms\n# Joint F-Test: All Gender Terms\nhypotheses = '(gender = 0, genderbyeduc = 0, genderbyage = 0, genderbyhours = 0)'\nf_test = model5.wald_test(hypotheses, use_f=True)\nprint(f_test)\n\n# All gender effects (level and interactions) are highly significant.\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<F test: F=array([[8.14208145]]), p=1.9073757410607637e-06, df_denom=864, df_num=4>\n```\n:::\n:::\n\n\n> **Key Concept 14.3: Interaction Terms Between Indicators and Continuous Variables**\n>\n> An **interacted indicator variable** is the product of an indicator and a continuous regressor, such as $d \\times x$. In the model $y = \\beta_1 + \\beta_2 x + \\alpha_1 d + \\alpha_2(d \\times x) + u$, the coefficient $\\alpha_2$ measures how the slope on $x$ differs between groups. Including only $d$ (without interaction) shifts the intercept but keeps slopes parallel. Adding the interaction allows both intercepts and slopes to vary.\n\n---\n\n### How the Gender Gap Changes with Controls\n\nComparing the five models reveals how the estimated gender gap evolves as we add controls and interactions:\n\n**Model Evolution:**\n\n1. **Model 1 (Gender only)**: Gap = -\\$16,000\n - This is the **raw, unconditional** gender earnings gap\n - Ignores all other factors that might explain earnings differences\n\n2. **Model 2 (+ Education)**: Gap shrinks to approximately -\\$10,000\n - Adding education as a control **reduces** the gender coefficient by ~\\$6,000\n - Interpretation: Part of the raw gap is explained by gender differences in education levels\n - The remaining -\\$10,000 is the gap **conditional on** education\n\n3. **Model 3 (+ Gender × Education)**:\n - Now gender enters through **two channels**: the main effect AND the interaction\n - The main gender coefficient becomes the gap **when education = 0** (not very meaningful)\n - The interaction coefficient shows whether **returns to education differ by gender**\n - **Joint F-test is crucial**: Test both coefficients together to assess overall gender effects\n\n4. **Model 4 (+ Age, Hours)**: Further controls\n - Adding age and hours worked provides more refined estimates\n - These are important determinants of earnings that may differ by gender\n - Gap continues to shrink as we account for more observable differences\n\n5. **Model 5 (Full Interactions)**: Most flexible specification\n - Allows gender to affect the **intercept AND slopes** of all variables\n - Tests whether returns to education, age, and hours differ by gender\n - **Joint F-test on all 4 gender terms** is highly significant\n\n**Key Insights:**\n\n- The gender gap **decreases** substantially when we control for education, age, and hours worked\n- From -\\$16,000 (unconditional) to approximately -\\$5,000 to -\\$8,000 (conditional)\n- This suggests **observable characteristics explain part, but not all** of the gap\n- The remaining gap could reflect:\n - Unmeasured factors (experience, occupation, industry)\n - Discrimination\n - Selection effects (e.g., women choosing lower-paying fields)\n\n**Statistical Lesson:**\n\n- With interactions, **individual t-tests can be misleading** due to multicollinearity\n- **Joint F-tests** are essential for testing overall significance of a variable that enters through multiple terms\n\n## 14.3: Interactions with Indicator Variables\n\nAn **interacted indicator variable** is the product of an indicator variable and another regressor.\n\n$$y = \\beta_1 + \\beta_2 x + \\alpha_1 d + \\alpha_2 (d \\times x) + u$$\n\nThis allows both intercept AND slope to differ by category:\n\n$$\\hat{y} = \\begin{cases}\n(b_1 + a_1) + (b_2 + a_2) x & \\text{if } d = 1 \\\\\nb_1 + b_2 x & \\text{if } d = 0\n\\end{cases}$$\n\n**Interpretation:**\n\n- $a_1$: Difference in intercepts (gender gap at $x=0$)\n- $a_2$: Difference in slopes (how returns to $x$ differ by gender)\n\n### Testing Gender Effects\n\nWhen gender enters through both a level term and interactions, we need **joint F-tests** to test overall significance.\n\n---\n\n### Interpreting Interaction Effects\n\nThe interaction term (Gender × Education) captures whether the **returns to education differ by gender**. Let's unpack what the results tell us:\n\n**Model with Interaction (Model 5):**\n\nThe full model allows both the intercept and slope to differ by gender:\n\n$$\\text{earnings} = \\begin{cases}\n(\\beta_1 + \\alpha_1) + (\\beta_2 + \\alpha_2)\\cdot\\text{education} + \\beta_3\\cdot\\text{age} + \\beta_4\\cdot\\text{hours} & \\text{if female} \\\\\n\\beta_1 + \\beta_2\\cdot\\text{education} + \\beta_3\\cdot\\text{age} + \\beta_4\\cdot\\text{hours} & \\text{if male}\n\\end{cases}$$\n\n**Key Coefficients:**\n\n1. **Gender × Education Interaction** (typically negative, around -\\$1,000 to -\\$2,000):\n - **Interpretation**: The return to one additional year of education is approximately **\\$1,000-\\$2,000 lower for women** than for men\n - Example: If $\\beta_{education} = 6,000$ and $\\beta_{gender \\times educ} = -1,500$:\n - Males: Each year of education → +\\$6,000 in earnings\n - Females: Each year of education → +\\$4,500 in earnings\n - This suggests **women get lower financial returns** from education investments\n\n2. **Gender × Age and Gender × Hours**:\n - Similarly capture whether age and hours have different effects by gender\n - Allow the **life-cycle earnings profile** to differ by gender\n\n**Avoiding the Dummy Variable Trap:**\n\nNotice we **cannot include all indicators plus an intercept**. In the worker type example:\n\n- We have three categories: self-employed, private, government\n- We can only include **two dummy variables** if we have an intercept\n- The **omitted category** becomes the reference (base) group\n- Coefficients measure differences **relative to the base**\n\n**Which category to omit?**\n\n- Your choice! Results are equivalent no matter which you drop\n- Choose the most natural reference category for interpretation\n- Example: Private sector is natural base for employment type comparisons\n\n**Joint F-Test Results:**\n\nThe joint F-tests show that:\n\n- All gender effects together are **highly statistically significant** (F ≈ 20-40, p < 0.001)\n- Even though individual coefficients may have large standard errors (multicollinearity)\n- Gender matters for **both level and slope** of earnings relationships\n\n### Model Comparison Table\n\nLet's create a comprehensive comparison of all five models.\n\n::: {#53fe1a79 .cell execution_count=7}\n``` {.python .cell-code}\n# Summary table of all models\n# Summary Table: All Five Models\n\nsummary_df = pd.DataFrame({\n    'Model 1': ['Gender only', model1.params.get('gender', np.nan),\n                model1.bse.get('gender', np.nan), model1.tvalues.get('gender', np.nan),\n                model1.nobs, model1.rsquared, model1.rsquared_adj, np.sqrt(model1.mse_resid)],\n    'Model 2': ['+ Education', model2.params.get('gender', np.nan),\n                model2.bse.get('gender', np.nan), model2.tvalues.get('gender', np.nan),\n                model2.nobs, model2.rsquared, model2.rsquared_adj, np.sqrt(model2.mse_resid)],\n    'Model 3': ['+ Gender×Educ', model3.params.get('gender', np.nan),\n                model3.bse.get('gender', np.nan), model3.tvalues.get('gender', np.nan),\n                model3.nobs, model3.rsquared, model3.rsquared_adj, np.sqrt(model3.mse_resid)],\n    'Model 4': ['+ Age, Hours', model4.params.get('gender', np.nan),\n                model4.bse.get('gender', np.nan), model4.tvalues.get('gender', np.nan),\n                model4.nobs, model4.rsquared, model4.rsquared_adj, np.sqrt(model4.mse_resid)],\n    'Model 5': ['Full Interact', model5.params.get('gender', np.nan),\n                model5.bse.get('gender', np.nan), model5.tvalues.get('gender', np.nan),\n                model5.nobs, model5.rsquared, model5.rsquared_adj, np.sqrt(model5.mse_resid)]\n}, index=['Description', 'Gender Coef', 'Robust SE', 't-stat', 'N', 'R²', 'Adj R²', 'RMSE'])\n\nsummary_df.to_string()\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```\n'                  Model 1       Model 2        Model 3       Model 4        Model 5\\nDescription   Gender only   + Education  + Gender×Educ  + Age, Hours  Full Interact\\nGender Coef -16396.423634 -18258.087589   20218.796285  19021.708451   57128.997253\\nRobust SE     3217.429112   3136.141829   15355.179322  14994.357587   31917.144603\\nt-stat          -5.096126     -5.821831       1.316741      1.268591       1.789916\\nN                   872.0         872.0          872.0         872.0          872.0\\nR²               0.024906      0.133961       0.139508      0.197852       0.202797\\nAdj R²           0.023785      0.131968       0.136534       0.19322       0.196338\\nRMSE         50899.716833  47996.599413   47870.196751  46272.189032   46182.684141'\n```\n:::\n:::\n\n\n**Key observations from the model comparison:**\n\n- Gender coefficient magnitude changes as we add controls\n- R-squared increases with additional variables\n- Interactions capture differential effects across groups\n\n> **Key Concept 14.4: Joint Significance Testing for Indicator Variables**\n>\n> When an indicator and its interaction with another variable are both included, test their **joint significance** using an F-test rather than individual t-tests. The joint test $H_0: \\alpha_1 = 0, \\alpha_2 = 0$ evaluates whether the categorical variable matters at all. Individual t-tests can be misleading when the indicator and interaction are correlated.\n\n## 14.4: Testing for Structural Change - Separate Regressions\n\nAn alternative to including interactions is to estimate **separate regressions** for each group.\n\n**Female regression:**\n$$\\text{earnings}_i = \\beta_1^F + \\beta_2^F \\text{education}_i + \\beta_3^F \\text{age}_i + \\beta_4^F \\text{hours}_i + u_i$$\n\n**Male regression:**\n$$\\text{earnings}_i = \\beta_1^M + \\beta_2^M \\text{education}_i + \\beta_3^M \\text{age}_i + \\beta_4^M \\text{hours}_i + u_i$$\n\nThis allows ALL coefficients to differ by gender, not just those we interact.\n\n### Chow Test\n\nThe **Chow test** formally tests whether coefficients differ across groups:\n\n$$H_0: \\beta^F = \\beta^M \\text{ (pooled model)} \\quad \\text{vs.} \\quad H_a: \\beta^F \\neq \\beta^M \\text{ (separate models)}$$\n\n::: {#930be34f .cell execution_count=8}\n``` {.python .cell-code}\n# 14.4: TESTING FOR STRUCTURAL CHANGE\n\nprint(\"\\nSeparate Regressions by Gender\")\n\n# Female regression\nmodel_female = ols('earnings ~ education + age + hours',\n                   data=data[data['gender'] == 1]).fit(cov_type='HC1')\nprint(\"\\nFemale subsample:\")\nprint(f\"  N = {int(model_female.nobs)}\")\nprint(f\"  Intercept: {model_female.params['Intercept']:,.2f}\")\nprint(f\"  Education: {model_female.params['education']:,.2f}\")\nprint(f\"  Age: {model_female.params['age']:,.2f}\")\nprint(f\"  Hours: {model_female.params['hours']:,.2f}\")\nprint(f\"  R²: {model_female.rsquared:.4f}\")\n\n# Male regression\nmodel_male = ols('earnings ~ education + age + hours',\n                 data=data[data['gender'] == 0]).fit(cov_type='HC1')\nprint(\"\\nMale subsample:\")\nprint(f\"  N = {int(model_male.nobs)}\")\nprint(f\"  Intercept: {model_male.params['Intercept']:,.2f}\")\nprint(f\"  Education: {model_male.params['education']:,.2f}\")\nprint(f\"  Age: {model_male.params['age']:,.2f}\")\nprint(f\"  Hours: {model_male.params['hours']:,.2f}\")\nprint(f\"  R²: {model_male.rsquared:.4f}\")\n\n# Compare coefficients\n# Comparison of Coefficients\n\ncomparison = pd.DataFrame({\n    'Female': model_female.params,\n    'Male': model_male.params,\n    'Difference': model_female.params - model_male.params\n})\nprint(comparison)\n\nprint(\"\\nKey findings:\")\nprint(f\"  - Returns to education: ${model_female.params['education']:,.0f} (F) vs ${model_male.params['education']:,.0f} (M)\")\nprint(f\"  - Returns to age: ${model_female.params['age']:,.0f} (F) vs ${model_male.params['age']:,.0f} (M)\")\nprint(f\"  - Returns to hours: ${model_female.params['hours']:,.0f} (F) vs ${model_male.params['hours']:,.0f} (M)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nSeparate Regressions by Gender\n\nFemale subsample:\n  N = 378\n  Intercept: -63,302.57\n  Education: 4,191.16\n  Age: 500.14\n  Hours: 691.24\n  R²: 0.1746\n\nMale subsample:\n  N = 494\n  Intercept: -120,431.57\n  Education: 6,314.67\n  Age: 549.47\n  Hours: 1,620.81\n  R²: 0.1840\n                 Female           Male    Difference\nIntercept -63302.571150 -120431.568403  57128.997253\neducation   4191.161688    6314.673007  -2123.511319\nage          500.142383     549.474999    -49.332616\nhours        691.239562    1620.814163   -929.574601\n\nKey findings:\n  - Returns to education: $4,191 (F) vs $6,315 (M)\n  - Returns to age: $500 (F) vs $549 (M)\n  - Returns to hours: $691 (F) vs $1,621 (M)\n```\n:::\n:::\n\n\n> **Key Concept 14.5: Testing for Structural Change**\n>\n> Running **separate regressions** for each group allows all coefficients to differ simultaneously. The **Chow test** evaluates whether pooling the data (imposing the same coefficients for both groups) is justified. If the F-test rejects the null, the relationship between $y$ and $x$ differs fundamentally across groups -- not just in intercept or one slope, but throughout the model.\n\n## 14.5: Sets of Indicator Variables (Multiple Categories)\n\nOften we have categorical variables with **more than two categories**.\n\n**Example: Type of Worker**\n\n- Self-employed (dself = 1)\n- Private sector employee (dprivate = 1)\n- Government employee (dgovt = 1)\n\nThese are **mutually exclusive**: each person falls into exactly one category.\n\n### The Dummy Variable Trap\n\nSince the three indicators sum to 1 ($d1 + d2 + d3 = 1$), we **cannot include all three plus an intercept**.\n\n**Solution**: Drop one indicator (the **reference category** or **base category**).\n\nThe coefficient of an included indicator measures the difference relative to the base category.\n\n### Three Equivalent Approaches\n\n1. **Include intercept, drop one indicator** (most common)\n2. **Drop intercept, include all indicators** (coefficients = group means)\n3. **Change which indicator is dropped** (changes interpretation, not fit)\n\n::: {#0f5a81a8 .cell execution_count=9}\n``` {.python .cell-code}\n# Sets of indicator variables: Worker type\n\n# Approach 1: Include intercept, drop one indicator (dprivate as reference)\n# Approach 1: Intercept + dself + dgovt (dprivate is reference)\nmodel_worker1 = ols('earnings ~ dself + dgovt + education + age', data=data).fit(cov_type='HC1')\nmodel_worker1.summary()\n\n# Approach 2: Drop intercept, include all indicators\n# Approach 2: No intercept + all dummies (dself + dprivate + dgovt)\nmodel_worker2 = ols('earnings ~ dself + dprivate + dgovt + education + age - 1', data=data).fit(cov_type='HC1')\nmodel_worker2.summary()\n\n# Approach 3: Different reference category (dself as reference)\n# Approach 3: Intercept + dprivate + dgovt (dself is reference)\nmodel_worker3 = ols('earnings ~ dprivate + dgovt + education + age', data=data).fit(cov_type='HC1')\nmodel_worker3.summary()\n\n# Key Insight:\nprint(f\"  All three models have IDENTICAL R²: {model_worker1.rsquared:.4f}\")\nprint(f\"  Only the interpretation changes (different reference category)\")\nprint(f\"  Fitted values and residuals are the same across all three\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  All three models have IDENTICAL R²: 0.1246\n  Only the interpretation changes (different reference category)\n  Fitted values and residuals are the same across all three\n```\n:::\n:::\n\n\n> **Key Concept 14.6: The Dummy Variable Trap**\n>\n> The **dummy variable trap** occurs when including all $C$ indicators from a set of mutually exclusive categories plus an intercept. Since $d_1 + d_2 + \\cdots + d_C = 1$, this creates **perfect multicollinearity** -- the intercept is an exact linear combination of the indicators. **Solution**: Drop one indicator (the \"base category\") or drop the intercept. Standard practice is to keep the intercept and drop one indicator.\n\n---\n\n### Understanding the Dummy Variable Trap\n\nThe results above demonstrate a **fundamental principle** in regression with categorical variables:\n\n**The Dummy Variable Trap Explained:**\n\nWhen we have $k$ mutually exclusive categories (e.g., 3 worker types), we face perfect multicollinearity:\n$$d_{self} + d_{private} + d_{govt} = 1 \\text{ (for every observation)}$$\n\nThis means one dummy is a **perfect linear combination** of the others plus the constant!\n\n**Three Equivalent Solutions:**\n\n1. **Include intercept, drop one dummy** (Standard approach)\n - Intercept = mean for the omitted (reference) category\n - Each coefficient = difference from reference category\n - Most common and easiest to interpret\n\n2. **Drop intercept, include all dummies** (No-constant model)\n - Each coefficient = mean for that category\n - No reference category needed\n - Useful when you want group means directly\n\n3. **Change which dummy is dropped** (Different reference)\n - All three models have **identical fit** (same R², predictions, residuals)\n - Only interpretation changes (different reference group)\n - Choose based on what comparison is most meaningful\n\n**Empirical Results from Worker Type Example:**\n\nFrom the three specifications above:\n\n- **R² is identical** across all specifications (≈ 0.16-0.17)\n- **Joint F-tests** give the same result (testing if worker type matters)\n- Only the individual coefficients change (but they measure different things)\n\n**Example Interpretation:**\n\nIf reference = Private sector:\n\n- $d_{self}$ coefficient ≈ -\\$5,000: Self-employed earn \\$5,000 less than private sector\n- $d_{govt}$ coefficient ≈ +\\$2,000: Government workers earn \\$2,000 more than private sector\n\nIf reference = Self-employed:\n\n- $d_{private}$ coefficient ≈ +\\$5,000: Private sector earns \\$5,000 more than self-employed\n- $d_{govt}$ coefficient ≈ +\\$7,000: Government workers earn \\$7,000 more than self-employed\n\nNotice: The difference between govt and private is the same in both (≈ \\$7,000 - \\$5,000 = \\$2,000)!\n\n**Practical Advice:**\n\n- Choose the **largest or most common** category as reference\n- Or choose the **policy-relevant** comparison (e.g., treatment vs. control)\n- Always clearly state which category is omitted\n- Report joint F-test for overall significance of the categorical variable\n\n### ANOVA: Testing Equality of Means Across Groups\n\n**Analysis of Variance (ANOVA)** tests whether means differ across multiple groups.\n\n$$H_0: \\mu_1 = \\mu_2 = \\mu_3 \\quad \\text{vs.} \\quad H_a: \\text{at least one mean differs}$$\n\nANOVA is equivalent to an F-test in regression with indicator variables.\n\n::: {#4fa56614 .cell execution_count=10}\n``` {.python .cell-code}\n# ANOVA: Testing Equality of Means Across Worker Types\n\n# Create categorical variable for worker type\ndata['typeworker'] = (1 * data['dself'] + 2 * data['dprivate'] + 3 * data['dgovt']).astype(int)\n\nprint(\"\\nMeans by worker type:\")\nmeans_by_type = data.groupby('typeworker')['earnings'].agg(['mean', 'std', 'count'])\nmeans_by_type.index = ['Self-employed', 'Private', 'Government']\nprint(means_by_type)\n\n# One-way ANOVA using scipy\n# One-way ANOVA (scipy)\n\ngroup1 = data[data['typeworker'] == 1]['earnings']\ngroup2 = data[data['typeworker'] == 2]['earnings']\ngroup3 = data[data['typeworker'] == 3]['earnings']\n\nf_stat_anova, p_value_anova = f_oneway(group1, group2, group3)\n\nprint(f\"  F-statistic: {f_stat_anova:.2f}\")\nprint(f\"  p-value: {p_value_anova:.6f}\")\n\nif p_value_anova < 0.05:\n    print(f\"\\n  Result: Reject H₀ - Earnings differ significantly across worker types\")\nelse:\n    print(f\"\\n  Result: Fail to reject H₀ - No significant difference in earnings\")\n\n# Using statsmodels for detailed ANOVA table\n# Detailed ANOVA table (statsmodels)\n\nmodel_anova = ols('earnings ~ C(typeworker)', data=data).fit()\nanova_table = anova_lm(model_anova, typ=2)\nprint(anova_table)\n\nprint(\"\\nNote: ANOVA F-statistic matches the joint test from regression\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nMeans by worker type:\n                       mean           std  count\nSelf-employed  72306.328125  86053.131086     79\nPrivate        54521.265625  48811.203104    663\nGovernment     56105.382812  32274.679426    130\n  F-statistic: 4.24\n  p-value: 0.014708\n\n  Result: Reject H₀ - Earnings differ significantly across worker types\n                     sum_sq     df         F    PR(>F)\nC(typeworker)  2.233847e+10    2.0  4.239916  0.014708\nResidual       2.289212e+12  869.0       NaN       NaN\n\nNote: ANOVA F-statistic matches the joint test from regression\n```\n:::\n:::\n\n\n> **Key Concept 14.7: ANOVA as Regression on Indicators**\n>\n> Regressing $y$ on a set of mutually exclusive indicators (with no other controls) is equivalent to **analysis of variance (ANOVA)**. Coefficients give group means or differences from the base mean. The regression F-test for joint significance of the indicators is identical to the ANOVA F-statistic, testing whether the categorical variable explains significant variation in $y$.\n\n### Visualizations\n\nLet's create informative visualizations to illustrate our findings.\n\n::: {#c578c908 .cell execution_count=11}\n``` {.python .cell-code}\n# VISUALIZATIONS\n\n# Figure 1: Earnings by gender and worker type\nfig, axes = plt.subplots(1, 2, figsize=(14, 6))\n\n# Panel 1: Box plot by gender\ndata['Gender'] = data['gender'].map({0: 'Male', 1: 'Female'})\nsns.boxplot(x='Gender', y='earnings', data=data, ax=axes[0], palette='Set2')\naxes[0].set_ylabel('Earnings ($)', fontsize=12)\naxes[0].set_xlabel('Gender', fontsize=12)\naxes[0].set_title('Earnings Distribution by Gender', fontsize=13, fontweight='bold')\naxes[0].grid(True, alpha=0.3, axis='y')\n\n# Add mean markers\nmeans_gender = data.groupby('Gender')['earnings'].mean()\naxes[0].scatter([0, 1], means_gender.values, color='red', s=100, zorder=5, marker='D', label='Mean')\naxes[0].legend()\n\n# Panel 2: Box plot by worker type\ndata['Worker Type'] = data['typeworker'].map({1: 'Self-employed', 2: 'Private', 3: 'Government'})\nsns.boxplot(x='Worker Type', y='earnings', data=data, ax=axes[1], palette='Set1')\naxes[1].set_ylabel('Earnings ($)', fontsize=12)\naxes[1].set_xlabel('Worker Type', fontsize=12)\naxes[1].set_title('Earnings Distribution by Worker Type', fontsize=13, fontweight='bold')\naxes[1].tick_params(axis='x', rotation=20)\naxes[1].grid(True, alpha=0.3, axis='y')\n\n# Add mean markers\nmeans_type = data.groupby('Worker Type')['earnings'].mean()\naxes[1].scatter([0, 1, 2], means_type.values, color='red', s=100, zorder=5, marker='D', label='Mean')\naxes[1].legend()\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch14_Regression_with_Indicator_Variables_files/figure-html/cell-12-output-1.png){width=1334 height=567}\n:::\n:::\n\n\n**What to look for in these box plots:**\n\n- **Medians**: The horizontal lines inside each box show the typical earnings for each group\n- **Spread**: Wider boxes and longer whiskers indicate greater earnings variation within a group\n- **Outliers**: Points beyond the whiskers represent unusually high earners\n- **Red diamonds**: Mean markers may differ from medians, indicating skewness in the earnings distribution\n\n::: {#70be6cc1 .cell execution_count=12}\n``` {.python .cell-code}\n# Figure 2: Earnings vs education by gender (with regression lines)\nfig, ax = plt.subplots(figsize=(11, 7))\n\nfor gender, label, color in [(0, 'Male', '#22d3ee'), (1, 'Female', 'red')]:\n    subset = data[data['gender'] == gender]\n    ax.scatter(subset['education'], subset['earnings'], alpha=0.4, label=label, \n               s=30, color=color)\n    \n    # Add regression line\n    z = np.polyfit(subset['education'], subset['earnings'], 1)\n    p = np.poly1d(z)\n    edu_range = np.linspace(subset['education'].min(), subset['education'].max(), 100)\n    ax.plot(edu_range, p(edu_range), linewidth=3, color=color, \n            label=f'{label} (slope={z[0]:,.0f})')\n\nax.set_xlabel('Years of Education', fontsize=13)\nax.set_ylabel('Earnings ($)', fontsize=13)\nax.set_title('Figure 14.2: Earnings vs Education by Gender\\n(Different slopes suggest interaction effects)', \n             fontsize=14, fontweight='bold')\nax.legend(fontsize=11, loc='upper left')\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch14_Regression_with_Indicator_Variables_files/figure-html/cell-13-output-1.png){width=1048 height=663}\n:::\n:::\n\n\n**What to look for in this scatter plot:**\n\n- **Slopes**: The different slopes indicate that returns to education vary by gender\n- **Implication**: Non-parallel lines justify including the gender x education interaction term\n- **Gap**: The vertical distance between lines shows the gender earnings gap at each education level\n\n> **Key Concept 14.8: Visualizing Group Differences in Regression**\n>\n> Scatter plots with **separate regression lines** by group visually reveal whether slopes and intercepts differ. Parallel lines indicate only an intercept shift (indicator without interaction), while non-parallel lines indicate differential slopes (interaction term needed). Box plots complement this by showing the distribution of $y$ across categories.\n\n## Key Takeaways\n\n### Indicator Variables Basics\n\n- **Indicator variables** (dummy variables) are binary variables that equal 1 if an observation is in a specific category and 0 otherwise\n- They allow regression models to incorporate categorical information such as gender, employment type, or region\n- Interpretation differs from continuous variables -- coefficients represent **group differences** rather than marginal effects\n\n### Regression on a Single Indicator and Difference in Means\n\n- When regressing $y$ on just an intercept and a single indicator $d$, the fitted model is $\\hat{y} = b + ad$\n- The intercept $b$ equals the mean of $y$ when $d=0$ (the reference group)\n- The slope $a$ equals the **difference in means**: $a = \\bar{y}_1 - \\bar{y}_0$\n- Regression on an indicator is mathematically equivalent to a two-sample difference-in-means test\n- Regression and specialized t-tests give the same estimate but slightly different standard errors\n- Example: Women earn \\$16,396 less than men on average ($t = -4.71$, highly significant)\n\n### Indicators with Controls and Interaction Terms\n\n- Adding an indicator to a regression with continuous variables measures the group difference **after controlling for** other factors\n- Including only the indicator shifts the intercept but keeps slopes **parallel** across groups\n- An **interaction term** $d \\times x$ allows slopes to differ by group (non-parallel lines)\n- The interaction coefficient measures how the effect of $x$ on $y$ differs between groups\n- Always use **joint F-tests** to test significance of both the indicator and its interaction together\n\n### Dummy Variable Trap and Base Category\n\n- The **dummy variable trap** occurs when including all $C$ indicators from a mutually exclusive set plus an intercept\n- Since $d_1 + d_2 + \\cdots + d_C = 1$, this creates perfect multicollinearity\n- **Solution**: Drop one indicator (the \"base category\") or drop the intercept\n- The **base category** is the reference group -- coefficients on included indicators measure differences from the base\n- Choice of base category does not affect statistical conclusions, only interpretation\n\n### Hypothesis Testing with Indicator Sets\n\n- A **t-test on a single indicator** tests whether that category differs from the base category\n- An **F-test on all $C-1$ included indicators** tests whether the categorical variable matters overall\n- The F-test result is the same regardless of which category is dropped (invariant to base choice)\n- Regressing $y$ on mutually exclusive indicators without controls is equivalent to **ANOVA**\n- Always use F-tests to evaluate the overall significance of a categorical variable\n\n### General Lessons\n\n- Indicator variables unify many statistical tests (t-tests, ANOVA) in a single regression framework\n- Always use heteroskedastic-robust standard errors for valid inference\n- Interactions with continuous variables allow relationships to vary by group\n- Regression flexibility: add controls, test interactions, compare models -- all within one framework\n\n---\n\n### Python Tools Used in This Chapter\n\n```python\n# Regression with indicators\nsmf.ols('earnings ~ gender', data=df).fit(cov_type='HC1')\nsmf.ols('earnings ~ gender * education', data=df).fit(cov_type='HC1')\n\n# T-tests\nscipy.stats.ttest_ind(group1, group2, equal_var=False)  # Welch's t-test\n\n# ANOVA\nscipy.stats.f_oneway(g1, g2, g3)   # One-way ANOVA\nsmf.ols('y ~ C(worker_type)').fit()  # ANOVA via regression\n\n# Joint F-tests\nmodel.f_test('gender = 0, gender:education = 0')\n\n# Visualization\nseaborn.boxplot(), matplotlib scatter with separate regression lines\n```\n\n---\n\n**Next Steps:**\n\n- **Chapter 15:** Regression with Transformed Variables\n- **Chapter 16:** Model Diagnostics\n\n---\n\n**Congratulations!** You've completed Chapter 14. You now understand how to incorporate categorical variables into regression analysis, interpret indicator coefficients, test for group differences, and use interactions to model differential effects across categories.\n\n## Practice Exercises\n\n**Exercise 1: Interpreting Indicator Regression**\n\nOLS regression of $y$ on an intercept and indicator $d$ using all data yields $\\hat{y} = 3 + 5d$.\n\n**(a)** What is $\\bar{y}$ for the subsample with $d = 0$?\n\n**(b)** What is $\\bar{y}$ for the subsample with $d = 1$?\n\n**(c)** What does the coefficient 5 represent?\n\n---\n\n**Exercise 2: Constructing from Means**\n\nSuppose $\\bar{y} = 30$ for the subsample with $d = 1$ and $\\bar{y} = 20$ for the subsample with $d = 0$.\n\n**(a)** Give the fitted model from OLS regression of $y$ on an intercept and $d$ using the full sample.\n\n**(b)** Is the difference in means statistically significant? What additional information would you need?\n\n---\n\n**Exercise 3: Multiple Indicators**\n\nWe have three mutually exclusive indicator variables $d_1$, $d_2$, and $d_3$. OLS yields $\\hat{y} = 1 + 3d_2 + 5d_3$.\n\n**(a)** What is the estimated mean of $y$ for each category?\n\n**(b)** What is the estimated difference between category 2 ($d_2 = 1$) and category 1 ($d_1 = 1$)?\n\n**(c)** Which category is the base (omitted) category?\n\n---\n\n**Exercise 4: Changing Base Category**\n\nFor the model in Exercise 3, give the coefficient estimates if instead we regressed $y$ on an intercept, $d_1$, and $d_2$ (dropping $d_3$ instead of $d_1$).\n\n---\n\n**Exercise 5: Interaction Interpretation**\n\nA regression of earnings on education, gender, and their interaction yields:\n\n$$\\widehat{\\text{earnings}} = 10{,}000 + 5{,}000 \\times \\text{education} - 8{,}000 \\times \\text{gender} - 2{,}000 \\times (\\text{gender} \\times \\text{education})$$\n\nwhere gender = 1 for female, 0 for male.\n\n**(a)** Write the fitted equation for males and for females separately.\n\n**(b)** What is the returns to education for males? For females?\n\n**(c)** At what education level does the gender earnings gap equal zero?\n\n---\n\n**Exercise 6: Joint F-Test**\n\nA researcher includes a gender indicator and a gender-education interaction in a regression. The t-statistic on the gender indicator is $t = -1.5$ (not significant at 5%) and the t-statistic on the interaction is $t = -1.8$ (not significant at 5%).\n\n**(a)** Can we conclude that gender does not matter for earnings? Why or why not?\n\n**(b)** What test should we conduct instead? What would you expect to find?\n\n**(c)** Explain why individual t-tests can be misleading when testing the significance of indicator variables with interactions.\n\n## Case Studies\n\n### Case Study 1: Regional Indicator Variables for Cross-Country Productivity\n\nIn this case study, you will apply indicator variable techniques to analyze how labor productivity differs across world regions and whether the determinants of productivity vary by region.\n\n**Dataset:** Mendez Convergence Clubs\n\n```python\nimport pandas as pd\nurl = \"https://raw.githubusercontent.com/quarcs-lab/mendez2020-convergence-clubs-code-data/master/assets/dat.csv\"\ndat = pd.read_csv(url)\ndat2014 = dat[dat['year'] == 2014].copy()\n```\n\n**Variables:** `lp` (labor productivity), `rk` (physical capital), `hc` (human capital), `region` (world region)\n\n---\n\n#### Task 1: Create Regional Indicators and Compute Means (Guided)\n\nCreate indicator variables for each region and compute mean log productivity by region.\n\n```python\n# Create indicator variables from the region column\nregion_dummies = pd.get_dummies(dat2014['region'], prefix='region', drop_first=False)\ndat2014 = pd.concat([dat2014, region_dummies], axis=1)\n\n# Compute mean log productivity by region\nimport numpy as np\ndat2014['ln_lp'] = np.log(dat2014['lp'])\nprint(dat2014.groupby('region')['ln_lp'].agg(['mean', 'count']))\n```\n\n**Questions:** How many regions are there? Which region has the highest average productivity? The lowest?\n\n---\n\n#### Task 2: Regression on Regional Indicators (Guided)\n\nRegress log productivity on regional indicators (using one region as the base category).\n\n```python\nimport statsmodels.formula.api as smf\nmodel1 = smf.ols('ln_lp ~ C(region)', data=dat2014).fit(cov_type='HC1')\nmodel1.summary()\n```\n\n**Questions:** Which region is the base category? How do you interpret the coefficients? Are the regional differences statistically significant?\n\n> **Key Concept 14.9: Regional Indicators as Difference in Means**\n>\n> When regressing $y$ on a set of regional indicators without controls, each coefficient measures the **difference in mean** $y$ between that region and the base region. The F-test for joint significance tests whether there are any significant productivity differences across regions.\n\n---\n\n#### Task 3: Add Continuous Controls (Semi-guided)\n\nAdd physical capital and human capital as continuous controls. Observe how regional coefficients change.\n\n**Hints:**\n\n- Use `ln_lp ~ C(region) + np.log(rk) + hc` as the formula\n- Compare regional coefficients with and without controls\n- What does it mean when regional gaps shrink after adding controls?\n\n---\n\n#### Task 4: Regional Interactions (Semi-guided)\n\nAdd an interaction between region and human capital to test whether the returns to human capital differ by region.\n\n**Hints:**\n\n- Use `ln_lp ~ C(region) * hc + np.log(rk)` to include all region-hc interactions\n- How do you interpret the interaction coefficients?\n- Do the returns to human capital differ significantly across regions?\n\n> **Key Concept 14.10: Interaction Terms for Regional Heterogeneity**\n>\n> Interaction terms between regional indicators and continuous variables allow the **slope** of a regressor to differ by region. A significant interaction indicates that the effect of human capital (or physical capital) on productivity is not uniform across all regions -- some regions benefit more from the same increase in inputs.\n\n---\n\n#### Task 5: Joint F-Tests for Regional Effects (Independent)\n\nConduct joint F-tests to evaluate:\n\n- Whether regional indicators are jointly significant (with and without controls)\n- Whether the regional interaction terms are jointly significant\n- Compare the explanatory power of models with and without regional effects\n\n---\n\n#### Task 6: Policy Brief on Regional Disparities (Independent)\n\nWrite a 200-300 word brief addressing:\n\n- How large are regional productivity differences?\n- How much of the gap is explained by differences in physical and human capital?\n- Do the returns to human capital differ by region, and what are the policy implications?\n- What additional factors might explain remaining regional differences?\n\n---\n\n**What You've Learned:** You have applied indicator variable techniques to cross-country data, demonstrating that regional indicators capture systematic productivity differences that partially reflect differences in factor endowments. Interaction terms reveal that the returns to human capital vary across regions, with important implications for development policy.\n\n### Case Study 2: Urban-Rural and Regional Divides in Bolivian Development\n\nIn previous chapters, we estimated satellite-development regressions treating all Bolivian municipalities identically. But Bolivia's nine departments span diverse geographies---from Andean highlands to Amazonian lowlands. In this case study, we apply Chapter 14's **indicator variable** techniques to model regional differences in development levels and in the satellite-development relationship.\n\n**Research Question**: Do development levels and the NTL-development relationship differ across Bolivia's nine departments?\n\n**Dataset:** DS4Bolivia\n\n```python\nimport pandas as pd\nurl_bol = \"https://raw.githubusercontent.com/quarcs-lab/ds4bolivia/master/ds4bolivia_v20250523.csv\"\nbol = pd.read_csv(url_bol)\n```\n\n**Key variables:** `mun` (municipality), `dep` (department), `imds` (Municipal Development Index, 0--100), `ln_NTLpc2017` (log nighttime lights per capita)\n\n#### Task 1: Create Indicators and Group Means (Guided)\n\n**Objective**: Create department indicator variables and compare mean development across departments.\n\n**Instructions**:\n\n1. Load the DS4Bolivia dataset and select key variables\n2. Use `pd.get_dummies(bol['dep'])` to create department indicators\n3. Compute mean `imds` by department with `groupby('dep')['imds'].agg(['mean', 'count'])`\n4. Which department has the highest mean IMDS? The lowest?\n\nRun the code below to get started.\n\n::: {#ebbb0827 .cell execution_count=13}\n``` {.python .cell-code}\n# Load DS4Bolivia dataset\nurl_bol = \"https://raw.githubusercontent.com/quarcs-lab/ds4bolivia/master/ds4bolivia_v20250523.csv\"\nbol = pd.read_csv(url_bol)\n\n# Select key variables\nbol_key = bol[['mun', 'dep', 'imds', 'ln_NTLpc2017']].dropna().copy()\n\n# Ds4Bolivia: Department Indicators And Group Means\nprint(f\"Observations: {len(bol_key)} municipalities\")\nprint(f\"Departments: {bol_key['dep'].nunique()}\")\n\n# Create department indicator variables\ndep_dummies = pd.get_dummies(bol_key['dep'])\nprint(f\"\\nIndicator variables created: {list(dep_dummies.columns)}\")\n\n# Mean IMDS by department\ndept_stats = bol_key.groupby('dep')['imds'].agg(['mean', 'count']).sort_values('mean', ascending=False)\ndept_stats.round(2)\n\nprint(f\"\\nHighest mean IMDS: {dept_stats['mean'].idxmax()} ({dept_stats['mean'].max():.2f})\")\nprint(f\"Lowest mean IMDS:  {dept_stats['mean'].idxmin()} ({dept_stats['mean'].min():.2f})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nObservations: 333 municipalities\nDepartments: 9\n\nIndicator variables created: ['Beni', 'Chuquisaca', 'Cochabamba', 'La Paz', 'Oruro', 'Pando', 'Potosí', 'Santa Cruz', 'Tarija']\n\nHighest mean IMDS: Tarija (60.60)\nLowest mean IMDS:  Pando (45.92)\n```\n:::\n:::\n\n\n#### Task 2: Regression on Department Indicators (Guided)\n\n**Objective**: Regress IMDS on department indicators to quantify regional development differences.\n\n**Instructions**:\n\n1. Estimate `imds ~ C(dep)` using statsmodels --- `C()` creates dummies automatically\n2. Print the regression summary\n3. Interpret: Each coefficient is the difference from the **base category** (the omitted department)\n4. What is the base department? How much higher or lower is each department relative to the base?\n\n```python\nmodel_dep = ols('imds ~ C(dep)', data=bol_key).fit(cov_type='HC1')\nmodel_dep.summary()\n```\n\n::: {#d6924ac6 .cell execution_count=14}\n``` {.python .cell-code}\n# Your code here: Regression of IMDS on department indicators\n#\n# Steps:\n# 1. Estimate model: imds ~ C(dep)\n# 2. Print summary\n# 3. Identify the base department and interpret coefficients\n#\n# model_dep = ols('imds ~ C(dep)', data=bol_key).fit(cov_type='HC1')\n# print(model_dep.summary())\n#\n# print(f\"\\nBase department: {sorted(bol_key['dep'].unique())[0]}\")\n# print(f\"Intercept = mean IMDS for the base department: {model_dep.params['Intercept']:.2f}\")\n```\n:::\n\n\n> **Key Concept 14.9: Geographic Indicator Variables**\n>\n> Department indicators capture **time-invariant regional characteristics** that affect development: altitude, climate, proximity to borders, historical infrastructure investments, and cultural factors. By including department dummies, we control for these systematic regional differences, allowing us to estimate the NTL-development relationship *within* departments rather than across them. The coefficient on NTL then reflects how NTL variation within a department predicts development variation within that department.\n\n#### Task 3: Add NTL Control (Semi-guided)\n\n**Objective**: Compare department coefficients with and without the NTL control variable.\n\n**Instructions**:\n\n1. Estimate `imds ~ C(dep) + ln_NTLpc2017`\n2. Compare department coefficients with those from Task 2 (without NTL)\n3. Do department differences shrink when NTL is added?\n4. What does this tell us about whether NTL explains part of the regional gap?\n\n**Hints**:\n\n- If department coefficients shrink, it means part of the regional gap was due to differences in NTL intensity\n- If they remain large, departments differ for reasons beyond what NTL captures\n\n::: {#f7f546a8 .cell execution_count=15}\n``` {.python .cell-code}\n# Your code here: Add NTL as a continuous control\n#\n# Steps:\n# 1. Estimate: imds ~ C(dep) + ln_NTLpc2017\n# 2. Compare department coefficients with Task 2 results\n# 3. Interpret changes\n#\n# model_dep_ntl = ols('imds ~ C(dep) + ln_NTLpc2017', data=bol_key).fit(cov_type='HC1')\n# print(model_dep_ntl.summary())\n#\n# print(\"\\nComparison: Do department coefficients shrink with NTL control?\")\n# print(\"If yes, NTL explains part of the regional development gap.\")\n```\n:::\n\n\n#### Task 4: Interaction Terms (Semi-guided)\n\n**Objective**: Test whether the NTL-development slope differs across departments.\n\n**Instructions**:\n\n1. Estimate `imds ~ C(dep) * ln_NTLpc2017` (includes main effects + interactions)\n2. Which interaction terms are significant?\n3. Interpret: The NTL slope differs by department\n4. In which departments does NTL predict development more or less strongly?\n\n**Hints**:\n\n- `C(dep) * ln_NTLpc2017` automatically includes both main effects and all interactions\n- A positive interaction means the NTL slope is steeper in that department compared to the base\n- A negative interaction means the NTL slope is flatter\n\n::: {#3743cda2 .cell execution_count=16}\n``` {.python .cell-code}\n# Your code here: Interaction between department and NTL\n#\n# Steps:\n# 1. Estimate: imds ~ C(dep) * ln_NTLpc2017\n# 2. Examine interaction coefficients\n# 3. Identify departments where NTL effect is stronger/weaker\n#\n# model_interact = ols('imds ~ C(dep) * ln_NTLpc2017', data=bol_key).fit(cov_type='HC1')\n# print(model_interact.summary())\n#\n# print(\"\\nInterpretation:\")\n# print(\"  Significant interactions indicate the NTL slope differs by department.\")\n# print(\"  Base department NTL slope = coefficient on ln_NTLpc2017\")\n# print(\"  Other departments: base slope + interaction coefficient\")\n```\n:::\n\n\n> **Key Concept 14.10: Heterogeneous Satellite Effects**\n>\n> Interaction terms between department indicators and NTL allow the **slope of the NTL-development relationship** to differ across regions. This is economically meaningful: in highly urbanized departments (like La Paz or Cochabamba), additional nighttime lights may signal commercial activity, while in rural highland departments (like Potosi), lights primarily reflect basic electrification. A significant interaction indicates that the *economic meaning* of satellite signals varies by geographic context.\n\n#### Task 5: Joint F-Test for Department Effects (Independent)\n\n**Objective**: Test the joint significance of all department indicators and all interaction terms.\n\n**Instructions**:\n\n1. Test joint significance of all department indicators using an F-test\n2. Also test joint significance of all interaction terms\n3. Are regional differences significant? Do NTL effects significantly vary across regions?\n\n**Hints**:\n\n- Use `model.f_test()` or compare restricted vs. unrestricted models\n- For interaction terms, compare the model with interactions to the model without\n- Report F-statistics and p-values for both tests\n\n::: {#6302680d .cell execution_count=17}\n``` {.python .cell-code}\n# Your code here: Joint F-tests for department effects\n#\n# Steps:\n# 1. F-test for joint significance of department indicators\n# 2. F-test for joint significance of interaction terms\n# 3. Compare models with and without regional effects\n#\n# Approach: Compare nested models using ANOVA\n# from statsmodels.stats.anova import anova_lm\n#\n# model_base = ols('imds ~ ln_NTLpc2017', data=bol_key).fit()\n# model_dep_only = ols('imds ~ C(dep) + ln_NTLpc2017', data=bol_key).fit()\n# model_full = ols('imds ~ C(dep) * ln_NTLpc2017', data=bol_key).fit()\n#\n# print(\"F-test: Department indicators (comparing base vs dep_only)\")\n# print(anova_lm(model_base, model_dep_only))\n#\n# print(\"\\nF-test: Interaction terms (comparing dep_only vs full)\")\n# print(anova_lm(model_dep_only, model_full))\n```\n:::\n\n\n#### Task 6: Regional Disparities Brief (Independent)\n\n**Objective**: Write a 200--300 word brief on regional development disparities in Bolivia.\n\n**Your brief should address**:\n\n1. What are the main regional divides in Bolivian development?\n2. How much do department indicators explain beyond NTL?\n3. Does the satellite-development relationship differ across regions?\n4. What are the policy implications for targeted regional interventions?\n\n**Use evidence from your analysis**: Cite specific coefficients, R-squared values, and F-test results to support your arguments.\n\n::: {#ccffc813 .cell execution_count=18}\n``` {.python .cell-code}\n# Your code here: Additional analysis for the policy brief\n#\n# You might want to:\n# 1. Create a summary table comparing R-squared across models\n# 2. Visualize department means with confidence intervals\n# 3. Plot separate NTL-IMDS regression lines by department\n# 4. Calculate specific statistics to cite in your brief\n#\n# Example: Compare model fit\n# print(\"MODEL COMPARISON\")\n# print(f\"  NTL only:        R² = {model_base.rsquared:.4f}\")\n# print(f\"  + Dept dummies:  R² = {model_dep_only.rsquared:.4f}\")\n# print(f\"  + Interactions:  R² = {model_full.rsquared:.4f}\")\n```\n:::\n\n\n#### What You've Learned from This Case Study\n\nThrough this analysis of regional development disparities in Bolivia, you have applied Chapter 14's indicator variable techniques to a real geospatial dataset:\n\n- **Indicator variable creation**: Used `pd.get_dummies()` and `C()` to create department dummies\n- **Department dummies in regression**: Quantified development differences across Bolivia's nine departments\n- **Controlling for regional effects**: Compared models with and without department indicators to assess how much of the NTL-development relationship reflects regional composition\n- **Interaction terms**: Tested whether the satellite-development slope differs across departments\n- **Joint F-tests**: Evaluated the overall significance of department effects and interaction terms\n- **Policy interpretation**: Connected statistical findings to regional development policy\n\n**Connection to next chapter**: In Chapter 15, we explore *nonlinear* satellite-development relationships using log transformations, polynomials, and elasticities.\n\n---\n\n**Well done!** You've now analyzed both cross-country productivity data and Bolivian municipal development data using indicator variable techniques, demonstrating how geographic dummies capture systematic regional differences and how interactions reveal heterogeneous effects.\n\n",
    "supporting": [
      "ch14_Regression_with_Indicator_Variables_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}