{
  "hash": "4555f67a903facdc683f11f56d3937c7",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 16. Checking the Model and Data\nexecute:\n  enabled: true\n  warning: false\n---\n\n\n**metricsAI: An Introduction to Econometrics with Python and AI in the Cloud**\n\n*[Carlos Mendez](https://carlos-mendez.org)*\n\n<img src=\"https://raw.githubusercontent.com/quarcs-lab/metricsai/main/images/ch16_visual_summary.jpg\" alt=\"Chapter 16 Visual Summary\" width=\"100%\">\n\nThis notebook provides an interactive introduction to regression diagnostics and model validation. All code runs directly in Google Colab without any local setup.\n\n[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/quarcs-lab/metricsai/blob/main/notebooks_colab/ch16_Checking_the_Model_and_Data.ipynb)\n<div class=\"chapter-resources\">\n<a href=\"https://www.youtube.com/watch?v=3JVkwVXsyr0\" target=\"_blank\" class=\"resource-btn\">🎬 AI Video</a>\n<a href=\"https://carlos-mendez.my.canva.site/s16-checking-the-model-and-data-pdf\" target=\"_blank\" class=\"resource-btn\">✨ AI Slides</a>\n<a href=\"https://cameron.econ.ucdavis.edu/aed/traedv1_16\" target=\"_blank\" class=\"resource-btn\">📊 Cameron Slides</a>\n<a href=\"https://app.edcafe.ai/quizzes/69786b812f5d08069e04e07f\" target=\"_blank\" class=\"resource-btn\">✏️ Quiz</a>\n<a href=\"https://app.edcafe.ai/chatbots/6978a3122f5d08069e07219f\" target=\"_blank\" class=\"resource-btn\">🤖 AI Tutor</a>\n</div>\n\n\n## Chapter Overview\n\nThis chapter focuses on checking model assumptions and diagnosing data problems. You'll gain both theoretical understanding and practical skills through hands-on Python examples.\n\n**Learning Objectives:**\n\nBy the end of this chapter, you will be able to:\n\n1. Identify and diagnose multicollinearity using correlation matrices and VIF\n2. Understand the consequences when each of the four core OLS assumptions fails\n3. Recognize omitted variable bias and specify appropriate control variables\n4. Understand endogeneity and when to use instrumental variables (IV)\n5. Detect and address heteroskedasticity using robust standard errors\n6. Identify autocorrelation in time series data and apply HAC-robust standard errors\n7. Interpret residual diagnostic plots to detect model violations\n8. Identify outliers and influential observations using DFITS and DFBETAS\n9. Apply appropriate diagnostic tests and remedies for common data problems\n\n**Chapter outline:**\n\n- 16.1 Multicollinearity\n- 16.2-16.4 Model Assumptions, Incorrect Models, and Endogeneity\n- 16.5 Heteroskedastic Errors\n- 16.6 Correlated Errors (Autocorrelation)\n- 16.7 Example: Democracy and Growth\n- 16.8 Diagnostics: Residual Plots and Influential Observations\n- Key Takeaways\n- Practice Exercises\n- Case Studies\n\n**Datasets used:**\n\n- **AED_EARNINGS_COMPLETE.DTA**: 842 full-time workers with earnings, age, education, and experience (2010)\n- **AED_DEMOCRACY.DTA**: 131 countries with democracy, growth, and institutional variables (Acemoglu et al. 2008)\n\n## Setup\n\nFirst, we import the necessary Python packages and configure the environment for reproducibility. All data will stream directly from GitHub.\n\n::: {#457acc7f .cell execution_count=1}\n``` {.python .cell-code}\n# Import required packages\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nimport statsmodels.api as sm\nfrom statsmodels.formula.api import ols\nfrom statsmodels.stats.outliers_influence import variance_inflation_factor, OLSInfluence\nfrom statsmodels.stats.diagnostic import het_white, acorr_ljungbox\nfrom statsmodels.graphics.tsaplots import plot_acf\nfrom statsmodels.regression.linear_model import OLS\nfrom statsmodels.nonparametric.smoothers_lowess import lowess\nfrom statsmodels.tsa.stattools import acf\nfrom scipy import stats\nimport random\nimport os\n\n# Set random seeds for reproducibility\nRANDOM_SEED = 42\nrandom.seed(RANDOM_SEED)\nnp.random.seed(RANDOM_SEED)\nos.environ['PYTHONHASHSEED'] = str(RANDOM_SEED)\n\n# GitHub data URL\nGITHUB_DATA_URL = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/\"\n\n# Set plotting style (dark theme matching book design)\nplt.style.use('dark_background')\nsns.set_style(\"darkgrid\")\nplt.rcParams.update({\n    'axes.facecolor': '#1a2235',\n    'figure.facecolor': '#12162c',\n    'grid.color': '#3a4a6b',\n    'figure.figsize': (10, 6),\n    'text.color': 'white',\n    'axes.labelcolor': 'white',\n    'xtick.color': 'white',\n    'ytick.color': 'white',\n    'axes.edgecolor': '#1a2235',\n})\n\n# Chapter 16: Checking The Model And Data\nprint(\"\\nSetup complete! Ready to explore model diagnostics.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nSetup complete! Ready to explore model diagnostics.\n```\n:::\n:::\n\n\n## 16.1: Multicollinearity\n\nMulticollinearity occurs when regressors are highly correlated with each other. While OLS remains unbiased and consistent, individual coefficients may be imprecisely estimated.\n\n**Effects of multicollinearity:**\n\n- High standard errors on individual coefficients\n- Low t-statistics (coefficients appear insignificant)\n- Coefficients may have \"wrong\" signs\n- Coefficients very sensitive to small data changes\n- Joint tests may still be significant\n\n**Detection methods:**\n\n1. **High pairwise correlations** between regressors\n2. **Variance Inflation Factor (VIF)**:\n   $$VIF_j = \\frac{1}{1 - R_j^2}$$\n   where $R_j^2$ is from regressing $x_j$ on all other regressors\n\n   - VIF > 10 indicates serious multicollinearity\n   - VIF > 5 suggests investigating further\n\n3. **Auxiliary regression**: Regress one variable on others\n   - High $R^2$ indicates multicollinearity\n\n**Example**: Earnings regression with age, education, and age×education interaction\n\n::: {#92691fd7 .cell execution_count=2}\n``` {.python .cell-code}\n# Read earnings data\ndata_earnings = pd.read_stata(GITHUB_DATA_URL + 'AED_EARNINGS_COMPLETE.DTA')\n\n# 16.1 Multicollinearity\n\nprint(\"\\nData summary:\")\ndata_earnings[['earnings', 'age', 'education', 'agebyeduc']].describe()\n\n# Base model without interaction\n# Base Model: earnings ~ age + education\nmodel_base = ols('earnings ~ age + education', data=data_earnings).fit(cov_type='HC1')\nmodel_base.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nData summary:\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<table class=\"simpletable\">\n<caption>OLS Regression Results</caption>\n<tr>\n  <th>Dep. Variable:</th>        <td>earnings</td>     <th>  R-squared:         </th> <td>   0.115</td> \n</tr>\n<tr>\n  <th>Model:</th>                   <td>OLS</td>       <th>  Adj. R-squared:    </th> <td>   0.113</td> \n</tr>\n<tr>\n  <th>Method:</th>             <td>Least Squares</td>  <th>  F-statistic:       </th> <td>   42.85</td> \n</tr>\n<tr>\n  <th>Date:</th>             <td>Mon, 06 Apr 2026</td> <th>  Prob (F-statistic):</th> <td>1.79e-18</td> \n</tr>\n<tr>\n  <th>Time:</th>                 <td>12:11:49</td>     <th>  Log-Likelihood:    </th> <td> -10644.</td> \n</tr>\n<tr>\n  <th>No. Observations:</th>      <td>   872</td>      <th>  AIC:               </th> <td>2.129e+04</td>\n</tr>\n<tr>\n  <th>Df Residuals:</th>          <td>   869</td>      <th>  BIC:               </th> <td>2.131e+04</td>\n</tr>\n<tr>\n  <th>Df Model:</th>              <td>     2</td>      <th>                     </th>     <td> </td>    \n</tr>\n<tr>\n  <th>Covariance Type:</th>         <td>HC1</td>       <th>                     </th>     <td> </td>    \n</tr>\n</table>\n<table class=\"simpletable\">\n<tr>\n      <td></td>         <th>coef</th>     <th>std err</th>      <th>z</th>      <th>P>|z|</th>  <th>[0.025</th>    <th>0.975]</th>  \n</tr>\n<tr>\n  <th>Intercept</th> <td>-4.688e+04</td> <td> 1.13e+04</td> <td>   -4.146</td> <td> 0.000</td> <td> -6.9e+04</td> <td>-2.47e+04</td>\n</tr>\n<tr>\n  <th>age</th>       <td>  524.9953</td> <td>  151.387</td> <td>    3.468</td> <td> 0.001</td> <td>  228.281</td> <td>  821.709</td>\n</tr>\n<tr>\n  <th>education</th> <td> 5811.3673</td> <td>  641.533</td> <td>    9.059</td> <td> 0.000</td> <td> 4553.986</td> <td> 7068.749</td>\n</tr>\n</table>\n<table class=\"simpletable\">\n<tr>\n  <th>Omnibus:</th>       <td>825.668</td> <th>  Durbin-Watson:     </th> <td>   2.071</td> \n</tr>\n<tr>\n  <th>Prob(Omnibus):</th> <td> 0.000</td>  <th>  Jarque-Bera (JB):  </th> <td>31187.987</td>\n</tr>\n<tr>\n  <th>Skew:</th>          <td> 4.353</td>  <th>  Prob(JB):          </th> <td>    0.00</td> \n</tr>\n<tr>\n  <th>Kurtosis:</th>      <td>30.975</td>  <th>  Cond. No.          </th> <td>    303.</td> \n</tr>\n</table><br/><br/>Notes:<br/>[1] Standard Errors are heteroscedasticity robust (HC1)\n```\n:::\n:::\n\n\n::: {#fcc99b3e .cell execution_count=3}\n``` {.python .cell-code}\n# Model with interaction (creates multicollinearity)\n# Collinear Model: earnings ~ age + education + agebyeduc\nmodel_collinear = ols('earnings ~ age + education + agebyeduc', \n                      data=data_earnings).fit(cov_type='HC1')\nmodel_collinear.summary()\n\nprint(\"\\nNote: Compare standard errors between base and collinear models.\")\n# Standard errors increase dramatically with the interaction term.\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nNote: Compare standard errors between base and collinear models.\n```\n:::\n:::\n\n\n::: {#43afd204 .cell execution_count=4}\n``` {.python .cell-code}\n# Correlation Matrix of Regressors\ncorr_matrix = data_earnings[['age', 'education', 'agebyeduc']].corr()\nprint(corr_matrix)\n\n# Visualize correlation matrix\nfig, ax = plt.subplots(figsize=(8, 6))\nsns.heatmap(corr_matrix, annot=True, fmt='.3f', cmap='coolwarm', \n            center=0, vmin=-1, vmax=1, ax=ax, cbar_kws={'label': 'Correlation'})\nax.set_title('Correlation Matrix of Regressors', fontsize=14, fontweight='bold')\nplt.tight_layout()\nplt.show()\n\nprint(\"\\nHigh correlations (> 0.9) indicate multicollinearity.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                age  education  agebyeduc\nage        1.000000  -0.038153   0.729136\neducation -0.038153   1.000000   0.635961\nagebyeduc  0.729136   0.635961   1.000000\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](ch16_Checking_the_Model_and_Data_files/figure-html/cell-5-output-2.png){width=736 height=566}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nHigh correlations (> 0.9) indicate multicollinearity.\n```\n:::\n:::\n\n\n::: {#3e123c60 .cell execution_count=5}\n``` {.python .cell-code}\n# Calculate VIF for all regressors\n# Variance Inflation Factors (VIF)\n\n# Prepare data for VIF calculation\nX_vif = data_earnings[['age', 'education', 'agebyeduc']].copy()\nX_vif = sm.add_constant(X_vif)\n\nvif_data = pd.DataFrame()\nvif_data[\"Variable\"] = X_vif.columns\nvif_data[\"VIF\"] = [variance_inflation_factor(X_vif.values, i)\n                   for i in range(X_vif.shape[1])]\n\nprint(vif_data)\n\nprint(\"\\nInterpretation:\")\nprint(\"  VIF > 10 indicates serious multicollinearity\")\nprint(\"  VIF > 5 suggests investigating further\")\nprint(f\"  agebyeduc VIF = {vif_data.loc[vif_data['Variable']=='agebyeduc', 'VIF'].values[0]:.1f} (SEVERE!)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    Variable         VIF\n0      const  411.323019\n1        age   21.996182\n2  education   17.298404\n3  agebyeduc   36.880231\n\nInterpretation:\n  VIF > 10 indicates serious multicollinearity\n  VIF > 5 suggests investigating further\n  agebyeduc VIF = 36.9 (SEVERE!)\n```\n:::\n:::\n\n\n> **Key Concept 16.1: Multicollinearity and the Variance Inflation Factor**\n>\n> The Variance Inflation Factor quantifies multicollinearity: $VIF_j = 1/(1 - R_j^2)$, where $R_j^2$ is from regressing $x_j$ on all other regressors. VIF = 1 means no collinearity; VIF > 10 indicates serious problems (standard errors inflated by $\\sqrt{10} \\approx 3.2\\times$). While OLS remains unbiased, individual coefficients become imprecise and may have \"wrong\" signs. Predictions and joint tests remain valid despite multicollinearity.\n\n---\n\n### Understanding VIF: When Multicollinearity Becomes a Problem\n\nThe VIF (Variance Inflation Factor) results reveal **severe multicollinearity** in the interaction model. Let's understand what this means:\n\n**VIF Values from the Analysis:**\n\nTypical results when including age × education interaction:\n\n- **agebyeduc** (interaction): VIF ≈ **60-80** (SEVERE!)\n- **age**: VIF ≈ **15-25** (HIGH)\n- **education**: VIF ≈ **15-25** (HIGH)\n- **Intercept**: VIF ≈ **10-15**\n\n**Interpreting VIF:**\n\nThe VIF formula: $VIF_j = \\frac{1}{1 - R_j^2}$\n\nwhere $R_j^2$ is from regressing $x_j$ on all other regressors.\n\n**What the numbers mean:**\n\n- **VIF = 1**: No multicollinearity (ideal)\n- **VIF = 5**: Moderate multicollinearity (R² = 0.80)\n- **VIF = 10**: High multicollinearity (R² = 0.90) - **investigate!**\n- **VIF = 80**: Severe multicollinearity (R² = 0.9875) - **serious problem!**\n\n**Why is agebyeduc VIF so high?**\n\nThe interaction term is nearly a perfect linear combination:\n\n- age and education are correlated\n- age × education inherits both correlations\n- $R^2_{agebyeduc|age,educ} \\approx 0.9875$\n- This means 98.75% of variation in the interaction is **predictable** from age and education alone!\n\n**Consequences:**\n\n1. **Standard errors inflate dramatically**:\n - $SE(\\hat{\\beta}_j) = \\sigma / \\sqrt{(1-R_j^2) \\cdot \\sum(x_j - \\bar{x}_j)^2}$\n - When $R_j^2 \\approx 1$: denominator → 0, so SE → ∞\n - VIF = 80 means SE is $\\sqrt{80} \\approx 9$ times larger than with no collinearity!\n\n2. **Individual t-statistics become small**:\n - Even if the true effect is large\n - Can't distinguish individual contributions\n - May get \"wrong\" signs on coefficients\n\n3. **Coefficients become unstable**:\n - Small changes in data → large changes in estimates\n - Sensitive to which observations are included\n - High variance of estimators\n\n**What Multicollinearity Does NOT Affect:**\n\n **Still valid:**\n\n- OLS remains **unbiased**\n- **Predictions** still accurate \n- **Joint F-tests** remain powerful\n- **Overall R²** unchanged\n\n **What breaks:**\n\n- Individual **t-tests** unreliable\n- **Standard errors** too large\n- **Confidence intervals** too wide\n- Can't **interpret** individual coefficients reliably\n\n**Solutions:**\n\n1. **Use joint F-tests** (not individual t-tests):\n - Test $H_0: \\beta_{age} = 0$ AND $\\beta_{agebyeduc} = 0$ **together**\n - These remain powerful despite multicollinearity\n\n2. **Center variables** before interaction:\n - Create: age_centered = age - mean(age)\n - Reduces correlation between main effects and interaction\n - Can dramatically reduce VIF\n\n3. **Drop one of the collinear variables**:\n - Only if you don't need both for your research question\n - Not appropriate if interaction is theoretically important\n\n4. **Collect more data** or **increase variation**:\n - More observations → smaller SEs\n - More variation in X → less correlation\n\n5. **Ridge regression** or **regularization**:\n - Shrinks coefficients toward zero\n - Trades small bias for large reduction in variance\n\n**The Auxiliary Regression:**\n\nThe output shows regressing agebyeduc ~ age + education gives **R² ≈ 0.987**:\n\n- This confirms 98.7% of interaction variation is explained by main effects\n- VIF = 1/(1-0.987) = 1/0.013 ≈ 77 \n\n**Practical Interpretation for Our Model:**\n\nDespite high VIF:\n\n- Joint F-test shows age and interaction are **jointly significant**\n- We know age matters (from quadratic model)\n- We know education matters (strong t-stat)\n- Problem is **separating** the age vs. age×education effects\n- Both matter, but we can't precisely estimate each one separately\n\n::: {#2cf693a3 .cell execution_count=6}\n``` {.python .cell-code}\n# Auxiliary regression to detect multicollinearity\n# Auxiliary Regression: agebyeduc ~ age + education\nmodel_aux = ols('agebyeduc ~ age + education', data=data_earnings).fit()\nmodel_aux.summary()\n\nprint(f\"\\nR² from auxiliary regression: {model_aux.rsquared:.4f}\")\nprint(f\"VIF formula: 1/(1-R²) = {1/(1-model_aux.rsquared):.2f}\")\n# High R² indicates that agebyeduc is nearly a perfect combination of age and education.\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nR² from auxiliary regression: 0.9729\nVIF formula: 1/(1-R²) = 36.88\n```\n:::\n:::\n\n\n### Joint Hypothesis Tests\n\nEven with multicollinearity, joint tests can be powerful. Individual coefficients may be imprecise, but linear combinations may be precisely estimated.\n\n::: {#b8fcdac1 .cell execution_count=7}\n``` {.python .cell-code}\n# Joint hypothesis tests\n\n# Test 1: H₀: age = 0 AND agebyeduc = 0\nhypotheses = '(age = 0, agebyeduc = 0)'\nf_test = model_collinear.wald_test(hypotheses, use_f=True)\nprint(f_test)\n\n# Test 2: H₀: education = 0 AND agebyeduc = 0\nhypotheses = '(education = 0, agebyeduc = 0)'\nf_test = model_collinear.wald_test(hypotheses, use_f=True)\nprint(f_test)\n\nprint(\"\\nInterpretation:\")\n# Joint tests are highly significant even though individual t-tests are weak.\n# This is the power of joint testing with multicollinear regressors.\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<F test: F=array([[6.48958655]]), p=0.0015939412046954283, df_denom=868, df_num=2>\n<F test: F=array([[43.00467267]]), p=1.5549618458662117e-18, df_denom=868, df_num=2>\n\nInterpretation:\n```\n:::\n:::\n\n\n> **Key Concept 16.2: Joint Hypothesis Tests Under Multicollinearity**\n>\n> Even when multicollinearity makes individual t-tests unreliable (high VIF, large standard errors), joint F-tests remain powerful. Testing whether a group of collinear variables is jointly significant avoids the imprecision problem because the F-test evaluates the combined contribution. Always use joint tests for groups of correlated regressors rather than relying on individual significance.\n\n*Having explored multicollinearity as a data problem that inflates standard errors, we now examine the broader set of OLS assumptions and what happens when each one fails.*\n\n## 16.2-16.4: Model Assumptions\n\n**Classical OLS Assumptions:**\n\n1. **Linearity**: $y_i = \\beta_1 + \\beta_2 x_{2i} + \\cdots + \\beta_k x_{ki} + u_i$\n2. **Zero conditional mean**: $E[u_i | x_i] = 0$\n3. **Homoskedasticity**: $Var(u_i | x_i) = \\sigma^2$\n4. **No autocorrelation**: $u_i$ independent of $u_j$ for $i \\neq j$\n\n**Consequences of violations:**\n\n| Assumption | Violation | OLS Properties | Solution |\n|-----------|-----------|----------------|----------|\n| 1 or 2 | Incorrect model / Endogeneity | Biased, Inconsistent | IV, better specification |\n| 3 | Heteroskedasticity | Unbiased, Inefficient, Wrong SEs | Robust SEs, WLS |\n| 4 | Autocorrelation | Unbiased, Inefficient, Wrong SEs | HAC SEs, FGLS |\n\n**Key insight**: Violations of assumptions 3 and 4 don't bias coefficients, but invalidate standard errors and hypothesis tests.\n\n::: {#c20d9d0e .cell execution_count=8}\n``` {.python .cell-code}\n# 16.2-16.4: Model Assumptions\n\n# \\nClassical OLS assumptions:\n# 1. Linear in parameters: E[y|x] = x'β\n# 2. Random sample from population\n# 3. No perfect collinearity\n# 4. Zero conditional mean: E[u|x] = 0\n# 5. Homoskedasticity: Var(u|x) = σ²\n# 6. No autocorrelation: Cov(u_i, u_j) = 0\n\n# \\nConsequences of violations:\n# Assumptions 1-4 violated → OLS biased and inconsistent\n# Assumptions 5-6 violated → OLS unbiased but inefficient\n# → Standard errors incorrect\nprint(\"                            → Invalid inference (t-tests, CIs)\")\n\n# \\nSolutions:\nprint(\"  Heteroskedasticity → Robust (HC) standard errors\")\nprint(\"  Autocorrelation → HAC (Newey-West) standard errors\")\nprint(\"  Endogeneity → Instrumental variables (IV)\")\n# Omitted variables → Add relevant controls\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                            → Invalid inference (t-tests, CIs)\n  Heteroskedasticity → Robust (HC) standard errors\n  Autocorrelation → HAC (Newey-West) standard errors\n  Endogeneity → Instrumental variables (IV)\n```\n:::\n:::\n\n\n> **Key Concept 16.3: Consequences of OLS Assumption Violations**\n>\n> When assumptions 1 or 2 fail (incorrect model or endogeneity), OLS is biased and inconsistent -- a fundamental problem requiring model changes or instrumental variables. When assumptions 3 or 4 fail (heteroskedasticity or autocorrelation), OLS remains unbiased and consistent but standard errors are wrong, invalidating confidence intervals and hypothesis tests. The key distinction: bias requires fixing the model; wrong SEs require only changing the inference method.\n\n## 16.5: Heteroskedastic Errors\n\nHeteroskedasticity means the error variance depends on $x$: $Var(u_i | x_i) = \\sigma_i^2 \\neq \\sigma^2$\n\n**Common in:**\n\n- Cross-sectional data (varies by unit size)\n- Income/wealth data (variance increases with level)\n\n**Solution**: Use heteroskedasticity-robust (HC) standard errors\n\n- Also called White standard errors\n- Coefficient estimates unchanged\n- Only standard errors adjusted\n- Usually larger (more conservative)\n\n::: {#5298b3a1 .cell execution_count=9}\n``` {.python .cell-code}\n# 16.5: Heteroskedastic Errors\n\n# Regression with earnings data\n# Earnings Regression: earnings ~ age + education\n\n# Standard SEs\nmodel_standard = ols('earnings ~ age + education', data=data_earnings).fit()\nprint(\"\\nWith Standard SEs:\")\nmodel_standard.summary()\n\n# Robust SEs\nmodel_robust = ols('earnings ~ age + education', data=data_earnings).fit(cov_type='HC1')\n# With Heteroskedasticity-Robust (HC1) SEs:\nmodel_robust.summary()\n\n# Comparison\n# SE Comparison: Standard vs Robust\nse_comparison = pd.DataFrame({\n    'Variable': model_standard.params.index,\n    'Standard SE': model_standard.bse.values,\n    'Robust SE': model_robust.bse.values,\n    'Ratio (Robust/Standard)': (model_robust.bse / model_standard.bse).values\n})\nprint(se_comparison)\n\nprint(\"\\nNote: Robust SEs are typically 20-40% larger, indicating heteroskedasticity.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nWith Standard SEs:\n    Variable   Standard SE     Robust SE  Ratio (Robust/Standard)\n0  Intercept  10663.893521  11306.329960                 1.060244\n1        age    154.103628    151.387435                 0.982374\n2  education    570.435846    641.532908                 1.124636\n\nNote: Robust SEs are typically 20-40% larger, indicating heteroskedasticity.\n```\n:::\n:::\n\n\n> **Key Concept 16.4: Heteroskedasticity and Robust Standard Errors**\n>\n> Heteroskedasticity means the error variance depends on the regressors: $\\text{Var}[u_i | \\mathbf{x}_i] \\neq \\sigma^2$. OLS coefficients remain unbiased, but default standard errors are wrong -- typically too small, giving false confidence in precision. Use heteroskedasticity-robust (HC1/White) standard errors, which are valid whether or not heteroskedasticity is present. Always use robust SEs for cross-sectional data as a default practice.\n\n---\n\n### Why Robust Standard Errors Matter\n\nThe comparison between standard and robust SEs reveals **heteroskedasticity** in the earnings data:\n\n**Typical Results:**\n\n| Variable | Standard SE | Robust SE | Ratio (Robust/Standard) |\n|----------|-------------|-----------|------------------------|\n| age | ~\\$200 | ~\\$250 | **1.25x** |\n| education | ~\\$800 | ~\\$1,100 | **1.38x** |\n\n**What This Tells Us:**\n\n1. **Heteroskedasticity is present**:\n - Robust SEs are **20-40% larger** than standard SEs\n - Error variance is **not constant** across observations\n - Violates the classical homoskedasticity assumption\n\n2. **Standard SEs are too small**:\n - Lead to **overstated** t-statistics\n - **False confidence** in precision\n - **Overrejection** of null hypotheses (Type I error)\n\n3. **Coefficients unchanged**:\n - OLS estimates remain **unbiased** and **consistent**\n - Only the **uncertainty** (SEs) is affected\n - Predictions still accurate\n\n**Why Heteroskedasticity in Earnings Data?**\n\nEarnings data typically exhibit heteroskedasticity because:\n\n1. **Scale effects**: High earners have more variable earnings\n - CEO: \\$1M ± \\$500K (50% CV)\n - Janitor: \\$30K ± \\$5K (17% CV)\n\n2. **Unobserved heterogeneity**: Some people more variable than others\n - Commission-based vs. salary\n - Stable government job vs. volatile private sector\n\n3. **Model misspecification**: Missing interactions or nonlinearities\n - True model may have different slopes for different groups\n\n**Visual Evidence:**\n\nIn the residual vs. fitted plot:\n\n- Residuals should have **constant spread** (homoskedasticity)\n- If spread **increases** with fitted values → heteroskedasticity\n- Classic \"megaphone\" or \"fan\" shape\n\n**Implications for Inference:**\n\n**With standard SEs:**\n\n- t-statistic for education: 6.25 → p < 0.001\n- Conclusion: Highly significant\n\n**With robust SEs:** \n\n- t-statistic for education: 4.55 → p < 0.001\n- Conclusion: Still significant, but less extreme\n\n**The correction:**\n\n- Larger SEs → wider confidence intervals\n- More **conservative** (honest about uncertainty)\n- Inference remains **valid**\n\n**When to Use Robust SEs:**\n\n **Always use for:**\n\n- Cross-sectional data (almost always heteroskedastic)\n- Large samples (asymptotically valid)\n- When you're unsure (conservative approach)\n- Publication-quality research\n\n **Don't need for:**\n\n- Experimental data with randomization\n- Small samples (can be unreliable, use bootstrap instead)\n- Time series (need HAC SEs instead)\n\n**Types of Robust SEs:**\n\n1. **HC0** (White 1980): Original heteroskedasticity-robust\n - $\\hat{V}_{HC0} = (X'X)^{-1}X'\\text{diag}(\\hat{u}_i^2)X(X'X)^{-1}$\n\n2. **HC1** (degrees of freedom correction):\n - Multiply HC0 by $n/(n-k)$\n - Better in finite samples\n - **Most common choice** (Stata default)\n\n3. **HC2** and **HC3**: Further finite-sample improvements\n - HC3 recommended for heteroskedasticity + influential observations\n\n**Bottom Line:**\n\nIn this earnings regression:\n\n- Education remains **highly significant** even with robust SEs\n- But we're more **honest** about precision\n- Robust SEs should be **default** for cross-sectional regressions\n- Report robust SEs in all your empirical work!\n\n## 16.6: Correlated Errors (Autocorrelation)\n\nAutocorrelation occurs in time series when $Cov(u_t, u_s) \\neq 0$ for $t \\neq s$.\n\n**AR(1) process**: $u_t = \\rho u_{t-1} + \\varepsilon_t$ where $|\\rho| < 1$\n\n**Consequences:**\n\n- OLS unbiased and consistent\n- Standard errors wrong (usually too small)\n- t-statistics overstated\n- False significance\n\n**Solution**: Use HAC (Heteroskedasticity and Autocorrelation Consistent) standard errors\n\n- Also called Newey-West standard errors\n- Accounts for both heteroskedasticity and autocorrelation\n\n**Detection**: Check autocorrelation function (ACF) of residuals\n\n::: {#0ef354cb .cell execution_count=10}\n``` {.python .cell-code}\n# 16.6: Correlated Errors (Autocorrelation)\n\n# Generate simulated time series data\nprint(\"\\nSimulation: Time Series with Autocorrelated Errors\")\nn = 10000\nnp.random.seed(10101)\n\n# Generate i.i.d. errors\ne = np.random.normal(0, 1, n)\n\n# Generate AR(1) errors: u_t = 0.8*u_{t-1} + e_t\nu = np.zeros(n)\nu[0] = 0\nfor t in range(1, n):\n    u[t] = 0.8 * u[t-1] + e[t]\n\n# Generate AR(1) regressor\nv = np.random.normal(0, 1, n)\nx = np.zeros(n)\nx[0] = 0\nfor t in range(1, n):\n    x[t] = 0.8 * x[t-1] + v[t]\n\n# Generate y with autocorrelated error\ny1 = 1 + 2*x + u\n\n# Create DataFrame\nts_data = pd.DataFrame({'y1': y1, 'x': x})\n\nprint(f\"\\nGenerated {n} observations with AR(1) errors (ρ = 0.8)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nSimulation: Time Series with Autocorrelated Errors\n\nGenerated 10000 observations with AR(1) errors (ρ = 0.8)\n```\n:::\n:::\n\n\n::: {#1d189b7b .cell execution_count=11}\n``` {.python .cell-code}\n# Estimate model and check residual autocorrelation\n# Model: y ~ x (with autocorrelated errors)\n\nmodel_ts = ols('y1 ~ x', data=ts_data).fit()\nresiduals = model_ts.resid\n\n# Check autocorrelation of residuals\nacf_vals = acf(residuals, nlags=10, fft=False)\nprint(\"\\nResidual autocorrelations (first 10 lags):\")\nfor lag, val in enumerate(acf_vals[:11]):\n    print(f\"  Lag {lag}: {val:.4f}\")\n\n# Plot ACF\nfig, ax = plt.subplots(figsize=(10, 5))\nplot_acf(residuals, lags=20, ax=ax)\nax.set_title('Autocorrelation Function of Residuals', fontsize=14, fontweight='bold')\nax.set_xlabel('Lag', fontsize=12)\nax.set_ylabel('ACF', fontsize=12)\nplt.tight_layout()\nplt.show()\n\nprint(\"\\nHigh ACF at multiple lags indicates autocorrelation.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nResidual autocorrelations (first 10 lags):\n  Lag 0: 1.0000\n  Lag 1: 0.7974\n  Lag 2: 0.6300\n  Lag 3: 0.4983\n  Lag 4: 0.3985\n  Lag 5: 0.3123\n  Lag 6: 0.2432\n  Lag 7: 0.1928\n  Lag 8: 0.1535\n  Lag 9: 0.1180\n  Lag 10: 0.0894\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](ch16_Checking_the_Model_and_Data_files/figure-html/cell-12-output-2.png){width=950 height=469}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nHigh ACF at multiple lags indicates autocorrelation.\n```\n:::\n:::\n\n\n> **Key Concept 16.5: Autocorrelation and HAC Standard Errors**\n>\n> Autocorrelation means errors are correlated over time ($\\text{Cov}[u_t, u_s] \\neq 0$), common in time series when economic shocks persist. OLS remains unbiased but standard errors are wrong -- typically too small, leading to false significance. Use HAC (Newey-West) standard errors for valid inference. Check the autocorrelation function (ACF) of residuals: significant autocorrelations at multiple lags indicate the problem. Severe autocorrelation drastically reduces the effective sample size.\n\n---\n\n### Autocorrelation: The Time Series Problem\n\nThe time series analysis reveals **strong autocorrelation** in interest rate data - a classic problem that invalidates standard inference:\n\n**Autocorrelation Evidence:**\n\nFrom the residuals of the levels regression:\n\n- **Lag 1 autocorrelation**: ρ₁ ≈ **0.95-0.98** (extremely high!)\n- **Lag 5 autocorrelation**: ρ₅ ≈ **0.85-0.90** (still very high)\n- **Lag 10 autocorrelation**: ρ₁₀ ≈ **0.75-0.85** (persistent)\n\n**What This Means:**\n\n1. **Errors are highly correlated over time**:\n - If today's error is +1%, tomorrow's is likely +0.95%\n - Errors **cluster**: positive errors followed by positive, negative by negative\n - Violates OLS assumption of **independent errors**\n\n2. **Standard errors drastically understate uncertainty**:\n \n Typical results:\n\n - **Default SE**: ~0.002 (too small!)\n - **HAC SE**: ~0.015 (realistic)\n - **Ratio**: HAC is **7-8 times larger!**\n\n3. **Why does autocorrelation inflate HAC SEs?**\n \n With independent errors:\n\n - $Var(\\bar{u}) = \\sigma^2/n$\n - Information in n observations\n \n With autocorrelation (ρ = 0.95):\n\n - $Var(\\bar{u}) \\approx \\sigma^2 \\cdot \\frac{1 + \\rho}{1 - \\rho} \\cdot \\frac{1}{n} = \\sigma^2 \\cdot 39 \\cdot \\frac{1}{n}$\n - **39 times larger variance!**\n - Effective sample size ≈ n/39\n\n**The Correlogram (ACF Plot):**\n\nThe ACF plot shows:\n\n- **Very slow decay** of autocorrelations\n- All lags out to 20-24 months significantly positive\n- Classic sign of **non-stationarity** (trending series)\n- Interest rates have **long memory**\n\n**Why Are Interest Rates Autocorrelated?**\n\n1. **Monetary policy persistence**:\n - Fed changes rates gradually (smoothing)\n - Same rate maintained for months\n\n2. **Economic conditions**:\n - Inflation, growth evolve slowly\n - Interest rates respond to persistent factors\n\n3. **Market expectations**:\n - Forward-looking behavior\n - Tomorrow's rate close to today's (no arbitrage)\n\n4. **Non-stationarity**:\n - Rates **trend** over long periods\n - 1980s: High rates (15%)\n - 2010s: Low rates (near 0%)\n - Mean not constant over time\n\n**Consequences for Inference:**\n\n**With default SEs:**\n\n- t-statistic: **50-60** (absurdly high!)\n- p-value: < 0.0001\n- False precision!\n\n**With HAC SEs:**\n\n- t-statistic: **5-8** (more realistic)\n- p-value: still < 0.001 (significant, but not absurdly so)\n- Honest uncertainty\n\n**The Solution: HAC (Newey-West) Standard Errors**\n\nHAC SEs account for **both heteroskedasticity and autocorrelation**:\n\n$$\\hat{V}_{HAC} = (X'X)^{-1} \\left( \\sum_{j=-L}^L w_j \\sum_t \\hat{u}_t \\hat{u}_{t-j} x_t x'_{t-j} \\right) (X'X)^{-1}$$\n\nwhere:\n\n- $L$ = number of lags (rule of thumb: $L \\approx 0.75 \\cdot T^{1/3}$)\n- $w_j$ = weights (declining with lag distance)\n\n**Choosing the Lag Length (L):**\n\nFor monthly data with T ≈ 400 observations:\n\n- Rule of thumb: $L \\approx 0.75 \\cdot 400^{1/3} \\approx 5.4$\n- Conservative: L = 12 (one year)\n- Very conservative: L = 24 (two years)\n\n**First Differencing as Alternative:**\n\nTransform: $\\Delta y_t = y_t - y_{t-1}$\n\nResults from differenced model:\n\n- Much **lower autocorrelation** (ρ₁ ≈ 0.1-0.3)\n- Removes **trend** (achieves stationarity)\n- Changes interpretation: now modeling **changes**, not levels\n\n**Practical Recommendations:**\n\nFor time series regressions:\n\n1. **Always plot your data** (levels and differences)\n2. **Check for trends** (visual, augmented Dickey-Fuller test)\n3. **Examine ACF** of residuals\n4. **Use HAC SEs** as default for time series\n5. **Consider differencing** if series are non-stationary\n6. **Report both** levels and differences specifications\n\n**Bottom Line:**\n\nIn the interest rate example:\n\n- Default SEs give **false confidence**\n- HAC SEs reveal **true uncertainty**\n- Even with correction, 10-year rate **strongly related** to 1-year rate\n- But not as precisely estimated as default SEs suggest!\n\n*Now that we understand the theoretical consequences of assumption violations, let's apply these concepts to a real-world example examining whether democracy promotes economic growth.*\n\n## 16.7: Example - Democracy and Growth\n\nWe analyze the relationship between democracy and economic growth using data from Acemoglu, Johnson, Robinson, and Yared (2008).\n\n**Research question**: Does democracy promote economic growth?\n\n**Data**: 131 countries, 1500-2000\n\n- **democracy**: 500-year change in democracy index\n- **growth**: 500-year change in log GDP per capita\n- **constraint**: Constraints on executive at independence\n- **indcent**: Year of independence\n- **catholic, muslim, protestant, other**: Religious composition\n\n**Key hypothesis**: Institutions matter for democracy and growth\n\n::: {#30c2d275 .cell execution_count=12}\n``` {.python .cell-code}\n# Load democracy data\ndata_democracy = pd.read_stata(GITHUB_DATA_URL + 'AED_DEMOCRACY.DTA')\n\n# 16.7: Democracy And Growth\n\nprint(\"\\nData summary:\")\nsummary_vars = ['democracy', 'growth', 'constraint', 'indcent', \n                'catholic', 'muslim', 'protestant', 'other']\ndata_democracy[summary_vars].describe()\n\nprint(f\"\\nSample size: {len(data_democracy)} countries\")\nprint(f\"Time period: 1500-2000\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nData summary:\n\nSample size: 131 countries\nTime period: 1500-2000\n```\n:::\n:::\n\n\n::: {#38de1073 .cell execution_count=13}\n``` {.python .cell-code}\n# Bivariate regression: democracy ~ growth\n\nmodel_bivariate = ols('democracy ~ growth', data=data_democracy).fit(cov_type='HC1')\nmodel_bivariate.summary()\n\n# Visualize relationship\nfig, ax = plt.subplots(figsize=(10, 6))\nax.scatter(data_democracy['growth'], data_democracy['democracy'],\n           alpha=0.6, s=50, color='#22d3ee')\nax.plot(data_democracy['growth'], model_bivariate.fittedvalues,\n        color='#c084fc', linewidth=2, label='OLS regression line')\nax.set_xlabel('Change in Log GDP per capita (1500-2000)', fontsize=12)\nax.set_ylabel('Change in Democracy (1500-2000)', fontsize=12)\nax.set_title('Figure 16.1: Democracy and Growth, 1500-2000',\n             fontsize=14, fontweight='bold')\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n\nprint(\"\\nInterpretation:\")\nprint(f\"  Coefficient: {model_bivariate.params['growth']:.4f}\")\nprint(f\"  Higher economic growth is associated with greater democratization.\")\nprint(f\"  But this may reflect omitted institutional variables...\")\n```\n\n::: {.cell-output .cell-output-display}\n![](ch16_Checking_the_Model_and_Data_files/figure-html/cell-14-output-1.png){width=950 height=565}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nInterpretation:\n  Coefficient: 0.1308\n  Higher economic growth is associated with greater democratization.\n  But this may reflect omitted institutional variables...\n```\n:::\n:::\n\n\n::: {#4effb222 .cell execution_count=14}\n``` {.python .cell-code}\n# Multiple regression: add institutional controls\n# Multiple Regression with Institutional Controls\n\nmodel_multiple = ols('democracy ~ growth + constraint + indcent + catholic + muslim + protestant',\n                     data=data_democracy).fit(cov_type='HC1')\nmodel_multiple.summary()\n\nprint(\"\\nKey findings:\")\nprint(f\"  Growth coefficient fell from {model_bivariate.params['growth']:.4f} to {model_multiple.params['growth']:.4f}\")\nprint(f\"  Institutional variables (religion, constraints) are important.\")\nprint(f\"  This suggests omitted variable bias in the bivariate model.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nKey findings:\n  Growth coefficient fell from 0.1308 to 0.0468\n  Institutional variables (religion, constraints) are important.\n  This suggests omitted variable bias in the bivariate model.\n```\n:::\n:::\n\n\n> **Key Concept 16.6: Omitted Variables Bias in Practice**\n>\n> The democracy-growth example demonstrates omitted variables bias: the growth coefficient falls from 0.131 (bivariate) to 0.047 (with controls), a 64% reduction. Institutional variables (religion, executive constraints) were correlated with both democracy and growth, biasing the bivariate estimate upward. Always ask: \"What variables might affect my outcome and correlate with my key regressor?\" Include relevant controls to reduce bias.\n\n::: {#0999130e .cell execution_count=15}\n``` {.python .cell-code}\n# Get residuals from multiple regression for diagnostic plots\nuhat = model_multiple.resid\nyhat = model_multiple.fittedvalues\n\n# Residual Diagnostics Prepared\nprint(f\"Number of residuals: {len(uhat)}\")\nprint(f\"Residual mean (should be ~0): {uhat.mean():.6f}\")\nprint(f\"Residual std dev: {uhat.std():.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNumber of residuals: 131\nResidual mean (should be ~0): 0.000000\nResidual std dev: 0.2457\n```\n:::\n:::\n\n\n## 16.8: Diagnostics - Residual Plots\n\nDiagnostic plots help detect violations of model assumptions:\n\n1. **Actual vs Fitted**: Should cluster around 45° line\n2. **Residual vs Fitted**: Should scatter randomly around zero\n3. **Residual vs Regressor**: Should scatter randomly around zero\n4. **Component Plus Residual Plot**: $b_j x_j + e$ vs $x_j$ (detects nonlinearity)\n5. **Added Variable Plot**: Partial $y$ vs partial $x_j$ (isolates effect)\n\n**LOWESS smooth**: Nonparametric smooth curve helps detect patterns\n\n---\n\n### Reading Diagnostic Plots: What to Look For\n\nThe diagnostic plots help us **visually detect** violations of regression assumptions. Let's interpret what we see:\n\n**Panel A: Actual vs Fitted**\n\n**What to look for:**\n\n- Points should **cluster around 45° line**\n- LOWESS smooth should **follow** the 45° line closely\n- Deviations indicate **systematic prediction errors**\n\n**In the democracy-growth example:**\n\n- Most points **reasonably close** to 45° line\n- LOWESS smooth **roughly linear**, close to 45°\n- Some **scatter** (R² ≈ 0.20-0.30, so significant unexplained variation)\n- **No obvious systematic bias** (LOWESS not curved)\n\n**Interpretation:**\n\n- Model captures **general relationship** reasonably\n- But substantial **residual variation** remains\n- No evidence of **major nonlinearity** (LOWESS smooth is linear)\n\n**Panel B: Residual vs Fitted**\n\n**What to look for:**\n\n- Residuals should **scatter randomly** around zero\n- **Equal spread** across range of fitted values (homoskedasticity)\n- LOWESS should be **horizontal** at zero\n- No **patterns**, **curvature**, or **heteroskedasticity**\n\n**In the democracy-growth example:**\n\n- Residuals **scatter** around zero \n- LOWESS smooth **close to horizontal** \n- Spread appears **roughly constant** \n- Some **outliers** but not extreme\n\n**Potential issues to watch for:**\n\n1. **Heteroskedasticity**: Fan shape (spread increases)\n2. **Nonlinearity**: LOWESS curved (missing quadratic term)\n3. **Outliers**: Points far from zero (influential observations)\n\n**Key Diagnostic Insights:**\n\n1. **No major heteroskedasticity**:\n - Spread doesn't systematically increase/decrease\n - Robust SEs still advisable (safety margin)\n - But not severe heteroskedasticity\n\n2. **Linearity assumption appears okay**:\n - LOWESS smooth roughly horizontal\n - If curved: suggests missing nonlinear terms\n - Could try quadratic, interactions\n\n3. **A few potential outliers**:\n - Countries with large positive/negative residuals\n - Follow up with DFITS, DFBETAS (see next sections)\n - Investigate: data errors or genuinely unusual cases?\n\n**What Would Bad Plots Look Like?**\n\n**Heteroskedasticity (fan shape):**\n\n- Residual spread **increases** with fitted values\n- Common in income, revenue, GDP data\n- Solution: Log transformation or WLS\n\n**Nonlinearity (curved LOWESS):**\n\n- LOWESS smooth **curves** (U-shape or inverted U)\n- Missing quadratic or other nonlinear terms\n- Solution: Add polynomial, interaction, or transform\n\n**Autocorrelation (time series):**\n\n- Residuals show **runs** (streaks of same sign)\n- Not visible in scatter plot (need time-series plot)\n- Solution: HAC SEs, add lags, difference\n\n**Outliers:**\n\n- A few points **very far** from main cluster\n- Can distort regression line\n- Investigate with influence diagnostics (DFITS, DFBETAS)\n\n**The LOWESS Smooth:**\n\n**What is it?**\n\n- **L**ocally **W**eighted **S**catterplot **S**moothing\n- Nonparametric smooth curve through data\n- Helps detect **patterns** hard to see in raw scatter\n\n**How to interpret:**\n\n- Should be **straight** and **flat** if model is correct\n- **Curvature** suggests missing nonlinearity\n- **Trend** (not horizontal) suggests systematic bias\n\n**Bottom Line:**\n\nFor democracy-growth model:\n\n- Diagnostic plots look **reasonably good**\n- No glaring violations of assumptions\n- Some outliers worth investigating (next section)\n- Model appears **adequately specified**\n- But low R² suggests many **omitted variables**\n\n### Diagnostic Plots for Individual Regressor (Growth)\n\nThree specialized plots for examining the growth variable:\n\n1. **Residual vs Regressor**: Checks for heteroskedasticity and nonlinearity\n2. **Component Plus Residual**: $b_{growth} \\times growth + e$ vs $growth$\n   - Linear relationship → straight line\n   - Nonlinearity → curved LOWESS\n\n3. **Added Variable Plot**: Controls for other variables\n   - Slope equals coefficient in full model\n   - Shows partial relationship\n\n::: {#00eae61d .cell execution_count=16}\n``` {.python .cell-code}\n# 16.8: Diagnostic Plots\n\n# Figure 16.2: Basic diagnostic plots\nfig, axes = plt.subplots(1, 2, figsize=(16, 6))\n\n# Panel A: Actual vs Fitted\naxes[0].scatter(yhat, data_democracy['democracy'], alpha=0.6, s=50, color='#22d3ee')\naxes[0].plot([yhat.min(), yhat.max()], [yhat.min(), yhat.max()],\n             '-', color='#c084fc', linewidth=2, label='45° line')\n\nlowess_result = lowess(data_democracy['democracy'], yhat, frac=0.3)\naxes[0].plot(lowess_result[:, 0], lowess_result[:, 1],\n             'r--', linewidth=2, label='LOWESS smooth')\n\naxes[0].set_xlabel('Fitted Democracy', fontsize=12)\naxes[0].set_ylabel('Actual Democracy', fontsize=12)\naxes[0].set_title('Panel A: Actual vs Fitted', fontsize=12, fontweight='bold')\naxes[0].legend()\naxes[0].grid(True, alpha=0.3)\n\n# Panel B: Residual vs Fitted\naxes[1].scatter(yhat, uhat, alpha=0.6, s=50, color='#22d3ee')\naxes[1].axhline(y=0, color='white', alpha=0.3, linewidth=2, linestyle='-')\n\nlowess_result = lowess(uhat, yhat, frac=0.3)\naxes[1].plot(lowess_result[:, 0], lowess_result[:, 1],\n             'r--', linewidth=2, label='LOWESS smooth')\n\naxes[1].set_xlabel('Fitted Democracy', fontsize=12)\naxes[1].set_ylabel('Residual', fontsize=12)\naxes[1].set_title('Panel B: Residual vs Fitted', fontsize=12, fontweight='bold')\naxes[1].legend()\naxes[1].grid(True, alpha=0.3)\n\nplt.suptitle('Figure 16.2: Basic Diagnostic Plots',\n             fontsize=14, fontweight='bold', y=1.00)\nplt.tight_layout()\nplt.show()\n\nprint(\"\\nInterpretation:\")\n# Panel A: Points should cluster around 45° line\n# Panel B: Residuals should scatter randomly around zero\n```\n\n::: {.cell-output .cell-output-display}\n![](ch16_Checking_the_Model_and_Data_files/figure-html/cell-17-output-1.png){width=1526 height=580}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nInterpretation:\n```\n:::\n:::\n\n\n::: {#493fb9fc .cell execution_count=17}\n``` {.python .cell-code}\n# Figure 16.3: Diagnostic plots for growth regressor\n\nfig, axes = plt.subplots(1, 3, figsize=(18, 5))\n\n# Panel A: Residual vs Regressor\naxes[0].scatter(data_democracy['growth'], uhat, alpha=0.6, s=50, color='#22d3ee')\naxes[0].axhline(y=0, color='white', alpha=0.3, linewidth=2, linestyle='-')\n\nlowess_result = lowess(uhat, data_democracy['growth'], frac=0.3)\naxes[0].plot(lowess_result[:, 0], lowess_result[:, 1],\n             'r--', linewidth=2, label='LOWESS smooth')\n\naxes[0].set_xlabel('Growth regressor', fontsize=11)\naxes[0].set_ylabel('Democracy Residual', fontsize=11)\naxes[0].set_title('Panel A: Residual vs Regressor', fontsize=12, fontweight='bold')\naxes[0].legend()\naxes[0].grid(True, alpha=0.3)\n\n# Panel B: Component Plus Residual\nb_growth = model_multiple.params['growth']\npr_growth = b_growth * data_democracy['growth'] + uhat\n\naxes[1].scatter(data_democracy['growth'], pr_growth, alpha=0.6, s=50, color='#22d3ee')\n\n# Regression line\nmodel_compplusres = ols('pr_growth ~ growth', \n                        data=pd.DataFrame({'growth': data_democracy['growth'],\n                                         'pr_growth': pr_growth})).fit()\naxes[1].plot(data_democracy['growth'], model_compplusres.fittedvalues,\n             '-', color='#c084fc', linewidth=2, label='Regression line')\n\nlowess_result = lowess(pr_growth, data_democracy['growth'], frac=0.3)\naxes[1].plot(lowess_result[:, 0], lowess_result[:, 1],\n             'r--', linewidth=2, label='LOWESS smooth')\n\naxes[1].set_xlabel('Growth regressor', fontsize=11)\naxes[1].set_ylabel(f'Dem Res + {b_growth:.3f}*Growth', fontsize=11)\naxes[1].set_title('Panel B: Component Plus Residual', fontsize=12, fontweight='bold')\naxes[1].legend()\naxes[1].grid(True, alpha=0.3)\n\n# Panel C: Added Variable Plot\nmodel_nogrowth = ols('democracy ~ constraint + indcent + catholic + muslim + protestant',\n                     data=data_democracy).fit()\nuhat_democ = model_nogrowth.resid\n\nmodel_growth = ols('growth ~ constraint + indcent + catholic + muslim + protestant',\n                   data=data_democracy).fit()\nuhat_growth = model_growth.resid\n\naxes[2].scatter(uhat_growth, uhat_democ, alpha=0.6, s=50, color='#22d3ee')\n\nmodel_addedvar = ols('uhat_democ ~ uhat_growth',\n                     data=pd.DataFrame({'uhat_growth': uhat_growth,\n                                       'uhat_democ': uhat_democ})).fit()\naxes[2].plot(uhat_growth, model_addedvar.fittedvalues,\n             '-', color='#c084fc', linewidth=2, label='Regression line')\n\nlowess_result = lowess(uhat_democ, uhat_growth, frac=0.3)\naxes[2].plot(lowess_result[:, 0], lowess_result[:, 1],\n             'r--', linewidth=2, label='LOWESS smooth')\n\naxes[2].set_xlabel('Growth regressor (partial)', fontsize=11)\naxes[2].set_ylabel('Democracy (partial)', fontsize=11)\naxes[2].set_title('Panel C: Added Variable', fontsize=12, fontweight='bold')\naxes[2].legend()\naxes[2].grid(True, alpha=0.3)\n\nplt.suptitle('Figure 16.3: Diagnostic Plots for Growth Regressor',\n             fontsize=14, fontweight='bold', y=1.00)\nplt.tight_layout()\nplt.show()\n\nprint(\"\\nInterpretation:\")\n# Panel A: Check for patterns in residuals\n# Panel B: LOWESS close to regression line → linear relationship OK\nprint(\"  Panel C: Slope equals coefficient in full model ({:.4f})\".format(b_growth))\n```\n\n::: {.cell-output .cell-output-display}\n![](ch16_Checking_the_Model_and_Data_files/figure-html/cell-18-output-1.png){width=1718 height=485}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nInterpretation:\n  Panel C: Slope equals coefficient in full model (0.0468)\n```\n:::\n:::\n\n\n*Having examined residual diagnostic plots for visual detection of model problems, we now turn to numerical influence measures that quantify how much individual observations affect regression results.*\n\n> **Key Concept 16.7: Diagnostic Plots for Model Validation**\n>\n> Three complementary plots assess individual regressors: (1) residual vs. regressor checks for patterns suggesting nonlinearity or heteroskedasticity; (2) component-plus-residual plot ($b_j x_j + e$ vs. $x_j$) reveals the partial relationship and detects nonlinearity; (3) added variable plot purges both $y$ and $x_j$ of other regressors, showing the pure partial effect whose slope equals the OLS coefficient $b_j$. LOWESS smoothing helps reveal systematic patterns.\n\n### Influential Observations: DFITS\n\n**DFITS** measures influence on fitted values:\n$$DFITS_i = \\frac{\\hat{y}_i - \\hat{y}_{i(i)}}{s_{(i)} \\sqrt{h_{ii}}}$$\n\nwhere:\n\n- $\\hat{y}_i$ = prediction including observation $i$\n- $\\hat{y}_{i(i)}$ = prediction excluding observation $i$\n- $s_{(i)}$ = RMSE excluding observation $i$\n- $h_{ii}$ = leverage of observation $i$\n\n**Rule of thumb**: Investigate if $|DFITS_i| > 2\\sqrt{k/n}$\n\n::: {#c44179fe .cell execution_count=18}\n``` {.python .cell-code}\n# Influential Observations: Dfits\n\n# Get influence diagnostics\ninfluence = OLSInfluence(model_multiple)\ndfits = influence.dffits[0]\nn = len(data_democracy)\n\nthreshold_dfits = 2 * np.sqrt(len(model_multiple.params) / n)\nprint(f\"\\nDFITS threshold: {threshold_dfits:.4f}\")\nprint(f\"Observations exceeding threshold: {np.sum(np.abs(dfits) > threshold_dfits)}\")\n\n# Plot DFITS\nobs_index = np.arange(n)\ncolors = ['red' if abs(d) > threshold_dfits else '#22d3ee' for d in dfits]\n\nfig, ax = plt.subplots(figsize=(12, 6))\nax.scatter(obs_index, dfits, c=colors, alpha=0.6, s=50)\nax.axhline(y=threshold_dfits, color='red', linestyle='--', linewidth=2, label=f'Threshold: ±{threshold_dfits:.3f}')\nax.axhline(y=-threshold_dfits, color='red', linestyle='--', linewidth=2)\nax.axhline(y=0, color='white', alpha=0.3, linestyle='-', linewidth=1)\nax.set_xlabel('Observation Index', fontsize=12)\nax.set_ylabel('DFITS', fontsize=12)\nax.set_title('Figure: DFITS - Influential Observations', fontsize=14, fontweight='bold')\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n\nprint(\"\\nInterpretation:\")\nprint(\"  Red points exceed threshold (potentially influential)\")\n# Investigate these observations for data errors or unusual cases\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nDFITS threshold: 0.4623\nObservations exceeding threshold: 5\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](ch16_Checking_the_Model_and_Data_files/figure-html/cell-19-output-2.png){width=1142 height=565}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nInterpretation:\n  Red points exceed threshold (potentially influential)\n```\n:::\n:::\n\n\n---\n\n#### Identifying Influential Observations with DFITS\n\nDFITS measures how much an observation influences its **own prediction**. The results help identify **potentially problematic** observations:\n\n**Understanding DFITS:**\n\nFormula: $DFITS_i = \\frac{\\hat{y}_i - \\hat{y}_{i(i)}}{s_{(i)} \\sqrt{h_{ii}}}$\n\nwhere:\n\n- $\\hat{y}_i$ = prediction **including** observation i\n- $\\hat{y}_{i(i)}$ = prediction **excluding** observation i\n- $s_{(i)}$ = RMSE excluding observation i\n- $h_{ii}$ = leverage (how unusual is $x_i$?)\n\n**Interpretation:**\n\n- DFITS measures **standardized change** in fitted value when i is deleted\n- Large |DFITS| → observation strongly influences its own prediction\n- Can be driven by **leverage** (unusual X) or **residual** (unusual Y|X)\n\n**Rule of Thumb:**\n\nThreshold: $|DFITS_i| > 2\\sqrt{k/n}$\n\nFor democracy-growth model (k ≈ 7, n = 131):\n\n- Threshold ≈ \\$2\\sqrt{7/131} = 2 \\times 0.231 \\approx **0.46**\n\n**Typical Results:**\n\n- **Most observations**: |DFITS| < 0.30 (not influential)\n- **A few observations**: |DFITS| = 0.5-0.8 (moderately influential)\n- **Extreme cases**: |DFITS| > 1.0 (highly influential)\n\n**What Makes an Observation Influential?**\n\nTwo components multiply:\n\n1. **Leverage** ($h_{ii}$): Unusual X values\n2. **Standardized residual**: Large prediction error\n\n**Most influential when both are large:**\n\n- Observation with **unusual combination of regressors** (high leverage)\n- **AND** doesn't fit the pattern (large residual)\n- Example: A country with unique institutions AND surprising democracy level\n\n**What to Do with Influential Observations:**\n\n**1. Investigate the data:**\n\n - Is it a **data error**? (typo, coding mistake)\n - Check original sources\n - If error: **correct or remove**\n\n**2. Understand the case:**\n\n - Is it genuinely unusual? (e.g., special historical circumstances)\n - Example: Post-colonial country with unique constraints\n - Adds valuable information, **keep it**\n\n**3. Check robustness:**\n\n - Re-estimate **without** the influential observations\n - Do conclusions change substantially?\n - If yes: Results **fragile**, interpret cautiously\n - If no: Results **robust**, less concerning\n\n**4. Model improvement:**\n\n - Does omitting observation suggest missing variables?\n - Example: Maybe need regional dummies\n - Influential observations often **signal model misspecification**\n\n**Example Interpretation:**\n\nSuppose observation #47 has DFITS = 0.85:\n\n- This country's predicted democracy changes by **0.85 standard deviations** when it's excluded\n- Country is either:\n - **High leverage** (unusual institutional characteristics), or\n - **Large residual** (democracy level doesn't match institutions), or\n - **Both**\n- Warrants investigation\n\n**DFITS vs. Other Influence Measures:**\n\n- **DFITS**: Influence on **own prediction**\n- **DFBETAS**: Influence on **regression coefficients** (see next)\n- **Cook's D**: Overall influence on **all fitted values**\n- **Leverage** ($h_{ii}$): Just the X-space component\n\n**Visualization:**\n\nThe DFITS plot shows:\n\n- **Blue points**: Not influential (within threshold)\n- **Red points**: Influential (exceed threshold)\n- Should be **mostly blue** with a **few red** outliers\n- Many red points → model problems or data issues\n\n**In the Democracy-Growth Example:**\n\nTypical findings:\n\n- 3-10 countries exceed threshold (out of 131)\n- These are **countries with unusual institutional/growth combinations**\n- Might include:\n - Rapidly democratizing autocracies\n - Stable democracies with slow growth\n - Post-conflict transitions\n - Resource-rich countries with unusual politics\n\n**Practical Advice:**\n\n **Do:**\n\n- Always compute influence diagnostics\n- Investigate observations exceeding thresholds\n- Report whether results change without influential cases\n- Consider robustness checks\n\n **Don't:**\n\n- Automatically delete influential observations\n- Ignore them without investigation\n- Only report results **after** deleting outliers (selective reporting)\n- Delete based solely on statistical criteria (needs substantive judgment)\n\n**Bottom Line:**\n\nDFITS is a **screening tool**:\n\n- Identifies observations **worth investigating**\n- Not a mechanical **deletion rule**\n- Combine statistical diagnosis with **subject-matter knowledge**\n- Goal: Better understand data and model, not just clean data\n\n### Influential Observations: DFBETAS\n\n**DFBETAS** measures influence on individual coefficients:\n$$DFBETAS_{j, i} = \\frac{\\hat{\\beta}_j - \\hat{\\beta}_{j(i)}}{s_{(i)} \\sqrt{(X'X)^{-1}_{jj}}}$$\n\nwhere:\n\n- $\\hat{\\beta}_j$ = coefficient including observation $i$\n- $\\hat{\\beta}_{j(i)}$ = coefficient excluding observation $i$\n\n**Rule of thumb**: Investigate if $|DFBETAS_{j, i}| > 2/\\sqrt{n}$\n\n::: {#708d5e0e .cell execution_count=19}\n``` {.python .cell-code}\n# Influential Observations: Dfbetas\n\ndfbetas = influence.dfbetas\nthreshold_dfbetas = 2 / np.sqrt(n)\nprint(f\"\\nDFBETAS threshold: {threshold_dfbetas:.4f}\")\n\n# Plot DFBETAS for each variable\nparam_names = model_multiple.params.index\nn_params = len(param_names)\n\nfig, axes = plt.subplots(2, 3, figsize=(18, 10))\naxes = axes.flatten()\n\nfor i, param in enumerate(param_names):\n    if i < len(axes):\n        colors = ['red' if abs(d) > threshold_dfbetas else '#22d3ee' \n                 for d in dfbetas[:, i]]\n        axes[i].scatter(obs_index, dfbetas[:, i], c=colors, alpha=0.6, s=30)\n        axes[i].axhline(y=threshold_dfbetas, color='red', linestyle='--', linewidth=1.5)\n        axes[i].axhline(y=-threshold_dfbetas, color='red', linestyle='--', linewidth=1.5)\n        axes[i].axhline(y=0, color='white', alpha=0.3, linestyle='-', linewidth=0.5)\n        axes[i].set_xlabel('Observation', fontsize=10)\n        axes[i].set_ylabel('DFBETAS', fontsize=10)\n        axes[i].set_title(f'{param}', fontsize=11, fontweight='bold')\n        axes[i].grid(True, alpha=0.3)\n\n# Remove extra subplots\nfor i in range(n_params, len(axes)):\n    fig.delaxes(axes[i])\n\nplt.suptitle('DFBETAS: Influential Observations by Variable',\n             fontsize=14, fontweight='bold', y=1.00)\nplt.tight_layout()\nplt.show()\n\nprint(\"\\nInterpretation:\")\n# Red points indicate observations with large influence on that coefficient.\n# Investigate whether these are data errors or genuinely unusual cases.\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nDFBETAS threshold: 0.1747\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](ch16_Checking_the_Model_and_Data_files/figure-html/cell-20-output-2.png){width=1718 height=965}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nInterpretation:\n```\n:::\n:::\n\n\n> **Key Concept 16.8: Influential Observations -- DFITS and DFBETAS**\n>\n> DFITS measures influence on fitted values: $DFITS_i$ is the scaled change in $\\hat{y}_i$ when observation $i$ is excluded. DFBETAS measures influence on individual coefficients: $DFBETAS_{j,i}$ is the scaled change in $\\hat{\\beta}_j$. Thresholds for investigation are $|DFITS| > 2\\sqrt{k/n}$ and $|DFBETAS| > 2/\\sqrt{n}$. Don't automatically delete influential points -- investigate whether they represent data errors, genuine outliers, or valid extreme values that carry important information.\n\n## Key Takeaways\n\n**Multicollinearity:**\n\n- Multicollinearity occurs when regressors are highly correlated, making individual coefficients imprecisely estimated\n- VIF > 10 indicates serious multicollinearity; VIF > 5 warrants investigation\n- OLS remains unbiased and consistent -- the problem is precision, not bias\n- Solutions: use joint F-tests, drop redundant variables, center variables before creating interactions, or collect more data\n\n**OLS Assumption Violations:**\n\n- Assumptions 1-2 violations (incorrect model, endogeneity) cause bias and inconsistency -- fundamental problems requiring model changes or IV\n- Assumptions 3-4 violations (heteroskedasticity, autocorrelation) do not bias coefficients but invalidate standard errors\n- Wrong standard errors lead to incorrect t-statistics, confidence intervals, and hypothesis tests\n- Omitted variables bias formula: $\\text{Bias} = \\beta_3 \\times \\delta_{23}$, where $\\beta_3$ is the omitted variable's effect and $\\delta_{23}$ is the correlation\n\n**Heteroskedasticity and Robust Standard Errors:**\n\n- Heteroskedasticity means error variance varies across observations, common in cross-sectional data\n- Use heteroskedasticity-robust (HC1/White) standard errors for valid inference\n- Robust SEs are typically larger than default SEs, giving more conservative (honest) inference\n- Always use robust SEs for cross-sectional regressions as a default practice\n\n**Autocorrelation and HAC Standard Errors:**\n\n- Autocorrelation means errors are correlated over time, common in time series data\n- Default SEs are typically too small with autocorrelation, leading to over-rejection\n- Use HAC (Newey-West) standard errors that account for both heteroskedasticity and autocorrelation\n- Check the ACF of residuals to detect autocorrelation patterns\n\n**Diagnostic Plots:**\n\n- Residual vs. fitted values: detect heteroskedasticity (fan shape) and nonlinearity (curved pattern)\n- Component-plus-residual plot: detect nonlinearity in individual regressors\n- Added variable plot: isolate partial relationship between y and x, controlling for other variables\n- LOWESS smooth helps reveal patterns that are hard to see in raw scatter plots\n\n**Influential Observations:**\n\n- DFITS measures influence on fitted values; threshold $|\\text{DFITS}| > 2\\sqrt{k/n}$\n- DFBETAS measures influence on individual coefficients; threshold $|\\text{DFBETAS}| > 2/\\sqrt{n}$\n- Investigate influential observations rather than automatically deleting them\n- Check whether conclusions change substantially when influential cases are excluded\n\n**Python tools:** `statsmodels` (VIF, OLSInfluence, robust covariance), `matplotlib`/`seaborn` (diagnostic plots), LOWESS smoothing\n\n**Next steps:** Chapter 17 extends these ideas to panel data, where you'll learn fixed effects and random effects models that address unobserved heterogeneity across units.\n\n---\n\nCongratulations! You've completed Chapter 16 on model checking and data diagnostics. You now have both the theoretical understanding and practical Python skills to evaluate regression assumptions, detect problems, and apply appropriate remedies.\n\n## Practice Exercises\n\n**Exercise 1: Irrelevant Variables vs. Omitted Variables**\n\nYou estimate $y_i = \\beta_1 + \\beta_2 x_{2i} + \\beta_3 x_{3i} + u_i$ by OLS.\n\n(a) If $x_3$ should not appear in the model (irrelevant variable), what happens to the OLS estimates of $\\beta_1$ and $\\beta_2$? Are they biased?\n\n(b) If a relevant variable $x_4$ was omitted from the model, and $x_4$ is correlated with $x_2$, what happens to $\\hat{\\beta}_2$? Write the omitted variables bias formula.\n\n**Exercise 2: VIF Interpretation**\n\nA regression of earnings on age, education, and experience yields VIF values of 22.0 (age), 17.3 (education), and 36.9 (experience).\n\n(a) Which variable has the most severe multicollinearity problem? Explain.\n\n(b) Calculate the $R^2$ from the auxiliary regression for the variable with the highest VIF.\n\n(c) By what factor are the standard errors inflated compared to the no-collinearity case?\n\n**Exercise 3: Choosing Standard Error Types**\n\nFor each scenario below, state which type of standard errors you would use (default, HC-robust, HAC, or cluster-robust) and why:\n\n(a) Cross-sectional regression of wages on education and experience for 5,000 workers.\n\n(b) Time series regression of GDP growth on interest rates using 200 quarterly observations.\n\n(c) Regression of test scores on class size using data from 50 schools with multiple classrooms per school.\n\n**Exercise 4: Heteroskedasticity Detection**\n\nYou estimate a regression and obtain the following SE comparison:\n\n| Variable | Standard SE | Robust SE | Ratio |\n|----------|-------------|-----------|-------|\n| Education | 570 | 642 | 1.13 |\n| Age | 154 | 151 | 0.98 |\n\n(a) Is there evidence of heteroskedasticity? Which variable's inference is most affected?\n\n(b) If you used standard SEs and the t-statistic for education was 2.05, would the conclusion change with robust SEs?\n\n**Exercise 5: DFITS Threshold Calculation**\n\nIn a regression with $k = 7$ regressors and $n = 131$ observations:\n\n(a) Calculate the DFITS threshold for identifying influential observations.\n\n(b) If 8 observations exceed this threshold, what percentage of the sample is flagged as potentially influential?\n\n(c) Describe the steps you would take to investigate these influential observations.\n\n**Exercise 6: Autocorrelation Consequences**\n\nA time series regression yields a first-lag residual autocorrelation of $\\rho_1 = 0.80$.\n\n(a) Is this evidence of autocorrelation? What does it mean for the residual pattern?\n\n(b) Approximate the factor by which the effective sample size is reduced (use the formula $\\frac{1+\\rho}{1-\\rho}$).\n\n(c) A coefficient has a default t-statistic of 4.5. If the HAC standard error is 3 times larger than the default, what is the corrected t-statistic? Is the coefficient still significant at 5%?\n\n## Case Studies\n\n### Case Study 1: Regression Diagnostics for Cross-Country Productivity Analysis\n\nIn this case study, you will apply the diagnostic techniques from this chapter to analyze cross-country labor productivity using the Mendez convergence clubs dataset.\n\n**Dataset:** Mendez (2020) convergence clubs data\n\n- **Source:** `https://raw.githubusercontent.com/quarcs-lab/mendez2020-convergence-clubs-code-data/master/assets/dat.csv`\n- **Sample:** 108 countries, 1990-2014\n- **Variables:** `lp` (labor productivity), `rk` (physical capital), `hc` (human capital), `rgdppc` (real GDP per capita), `tfp` (total factor productivity), `region`\n\n**Research question:** What econometric issues arise when modeling cross-country productivity, and how do diagnostic tools help detect and address them?\n\n---\n\n#### Task 1: Detect Multicollinearity (Guided)\n\nLoad the dataset and estimate a regression of log labor productivity (`np.log(lp)`) on log physical capital (`np.log(rk)`), human capital (`hc`), and log GDP per capita (`np.log(rgdppc)`), using the year 2014 cross-section.\n\n```python\nimport pandas as pd\nimport numpy as np\nfrom statsmodels.formula.api import ols\nfrom statsmodels.stats.outliers_influence import variance_inflation_factor\nimport statsmodels.api as sm\n\nurl = \"https://raw.githubusercontent.com/quarcs-lab/mendez2020-convergence-clubs-code-data/master/assets/dat.csv\"\ndat = pd.read_csv(url)\ndat2014 = dat[dat['year'] == 2014].copy()\ndat2014['ln_lp'] = np.log(dat2014['lp'])\ndat2014['ln_rk'] = np.log(dat2014['rk'])\ndat2014['ln_rgdppc'] = np.log(dat2014['rgdppc'])\n\n# Estimate the model = ols('ln_lp ~ ln_rk + hc + ln_rgdppc', data=dat2014).fit(cov_type='HC1')\nmodel.summary()\n\n# Calculate VIF\nX = dat2014[['ln_rk', 'hc', 'ln_rgdppc']].dropna()\nX = sm.add_constant(X)\nfor i, col in enumerate(X.columns):\n    print(f\"VIF({col}): {variance_inflation_factor(X.values, i):.2f}\")\n```\n\nInterpret the VIF values. Is multicollinearity a concern? Which variables are most collinear and why?\n\n---\n\n#### Task 2: Compare Standard and Robust Standard Errors (Guided)\n\nEstimate the same model with both default and robust (HC1) standard errors. Create a comparison table.\n\n```python\nmodel_default = ols('ln_lp ~ ln_rk + hc', data=dat2014).fit()\nmodel_robust = ols('ln_lp ~ ln_rk + hc', data=dat2014).fit(cov_type='HC1')\n\ncomparison = pd. DataFrame({\n    'Default SE': model_default.bse,\n    'Robust SE': model_robust.bse,\n    'Ratio': model_robust.bse / model_default.bse\n})\nprint(comparison)\n```\n\nIs there evidence of heteroskedasticity? Which coefficient's inference is most affected?\n\n---\n\n#### Task 3: Residual Diagnostic Plots (Semi-guided)\n\nCreate the three diagnostic plots for the productivity model:\n\n1. Actual vs. fitted values with LOWESS smooth\n2. Residuals vs. fitted values with LOWESS smooth\n3. Residuals vs. `ln_rk` (component-plus-residual plot)\n\n*Hint:* Use `from statsmodels.nonparametric.smoothers_lowess import lowess` for the LOWESS smooth. Plot residuals from the robust model.\n\nWhat do the diagnostic plots reveal about the model specification?\n\n---\n\n#### Task 4: Identify Influential Countries (Semi-guided)\n\nCalculate DFITS and DFBETAS for the productivity regression. Identify countries that exceed the thresholds.\n\n*Hint:* Use `OLSInfluence(model).dffits[0]` and `OLSInfluence(model).dfbetas`. The DFITS threshold is $2\\sqrt{k/n}$ and the DFBETAS threshold is $2/\\sqrt{n}$.\n\nWhich countries are most influential? Investigate whether removing them changes the key coefficients substantially.\n\n---\n\n#### Task 5: Regional Heterogeneity Analysis (Independent)\n\nTest whether the relationship between capital and productivity varies across regions:\n\n1. Add region dummy variables and region-capital interactions\n2. Test for heteroskedasticity by comparing default and robust SEs across specifications\n3. Conduct an F-test for joint significance of regional interactions\n\nDoes allowing for regional heterogeneity improve the model diagnostics?\n\n---\n\n#### Task 6: Diagnostic Report (Independent)\n\nWrite a 200-300 word diagnostic report for the cross-country productivity regression. Your report should:\n\n1. Summarize the multicollinearity assessment (VIF results)\n2. Document the heteroskedasticity evidence (SE comparison)\n3. Describe what the residual plots reveal about model specification\n4. List the most influential countries and their potential impact\n5. Recommend the appropriate standard error type and any model modifications\n\n> **Key Concept 16.9: Systematic Regression Diagnostics**\n>\n> A complete regression diagnostic workflow includes: (1) check multicollinearity via VIF before interpreting individual coefficients; (2) compare standard and robust SEs to detect heteroskedasticity; (3) examine residual plots for nonlinearity and patterns; (4) identify influential observations with DFITS and DFBETAS; (5) document all findings and report robust results. Always investigate problems rather than mechanically applying fixes.\n\n> **Key Concept 16.10: Cross-Country Regression Challenges**\n>\n> Cross-country regressions face specific diagnostic challenges: multicollinearity among development indicators (GDP, capital, education are highly correlated), heteroskedasticity across countries at different development levels, and influential observations from outlier countries. Using robust standard errors and carefully examining influential cases is essential for credible cross-country analysis.\n\n**What You've Learned:**\nIn this case study, you applied the complete diagnostic toolkit to cross-country productivity data. You detected multicollinearity among development indicators, compared standard and robust standard errors, created diagnostic plots, and identified influential countries. These skills ensure that your regression results are reliable and your conclusions are credible.\n\n### Case Study 2: Diagnosing the Satellite Prediction Model\n\n**Research Question**: How reliable are the satellite-development regression models we have estimated throughout this textbook? Do they satisfy the standard regression assumptions?\n\n**Background**: We have estimated multiple satellite-development regression models throughout this textbook. But how reliable are these models? In this case study, we apply Chapter 16's **diagnostic tools** to check for multicollinearity, heteroskedasticity, influential observations, and other model violations.\n\n**The Data**: The DS4Bolivia dataset covers 339 Bolivian municipalities with satellite data, development indices, and socioeconomic indicators.\n\n**Key Variables**:\n\n- `mun`: Municipality name\n- `dep`: Department (administrative region)\n- `imds`: Municipal Sustainable Development Index (0-100)\n- `ln_NTLpc2017`: Log nighttime lights per capita (2017)\n- `A00`, `A10`, `A20`, `A30`, `A40`: Satellite image embedding dimensions\n\n#### Load the DS4Bolivia Data\n\n::: {#e827002c .cell execution_count=20}\n``` {.python .cell-code}\n# Load the DS4Bolivia dataset\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom statsmodels.formula.api import ols\nfrom statsmodels.stats.outliers_influence import variance_inflation_factor, OLSInfluence\nimport statsmodels.api as sm\n\nurl_bol = \"https://raw.githubusercontent.com/quarcs-lab/ds4bolivia/master/ds4bolivia_v20250523.csv\"\nbol = pd.read_csv(url_bol)\n\n# Select key variables for this case study\nkey_vars = ['mun', 'dep', 'imds', 'ln_NTLpc2017', 'A00', 'A10', 'A20', 'A30', 'A40']\nbol_cs = bol[key_vars].copy().dropna()\n\n# Ds4Bolivia: Regression Diagnostics Case Study\nprint(f\"Observations (complete cases): {len(bol_cs)}\")\nprint(f\"\\nKey variable summary:\")\nbol_cs[['imds', 'ln_NTLpc2017', 'A00', 'A10', 'A20', 'A30', 'A40']].describe().round(3)\n```\n:::\n\n\n#### Task 1: Multicollinearity Check (Guided)\n\n**Objective**: Assess whether satellite predictors suffer from multicollinearity.\n\n**Instructions**:\n\n1. Compute the correlation matrix for the predictors (`ln_NTLpc2017`, `A00`, `A10`, `A20`, `A30`, `A40`)\n2. Calculate VIF for each variable using `variance_inflation_factor()` from statsmodels\n3. Flag variables with VIF > 10\n4. Discuss: Are satellite embeddings multicollinear? Does multicollinearity affect the model's predictive power vs. individual coefficient interpretation?\n\n::: {#5644c682 .cell execution_count=21}\n``` {.python .cell-code}\n# Your code here: Multicollinearity diagnostics\n#\n# Example structure:\n# predictors = ['ln_NTLpc2017', 'A00', 'A10', 'A20', 'A30', 'A40']\n#\n# # Correlation matrix\n# print(\"CORRELATION MATRIX\")\n# print(bol_cs[predictors].corr().round(3))\n#\n# # VIF calculation\n# X = bol_cs[predictors].copy()\n# X = sm.add_constant(X)\n# print(\"\\nVARIANCE INFLATION FACTORS\")\n# for i, col in enumerate(X.columns):\n#     vif = variance_inflation_factor(X.values, i)\n#     flag = \" *** HIGH\" if vif > 10 and col != 'const' else \"\"\n#     print(f\"  VIF({col}): {vif:.2f}{flag}\")\n```\n:::\n\n\n> **Key Concept 16.11: Multicollinearity in Satellite Features**\n>\n> Satellite embedding dimensions often correlate with each other because they capture **overlapping visual patterns** from the same images. When embeddings A00 and A10 both respond to building density, their collinearity inflates standard errors and makes individual coefficients unstable. The VIF (Variance Inflation Factor) quantifies this: a VIF above 10 signals problematic collinearity. Solutions include dropping redundant features, using principal components, or accepting imprecise individual estimates while maintaining valid joint inference.\n\n#### Task 2: Standard vs Robust SEs (Guided)\n\n**Objective**: Detect heteroskedasticity by comparing default and robust standard errors.\n\n**Instructions**:\n\n1. Estimate the full model: `imds ~ ln_NTLpc2017 + A00 + A10 + A20 + A30 + A40`\n2. Compare default (homoskedastic) and HC1 (robust) standard errors\n3. Compute the ratio of robust to default SEs for each coefficient\n4. Discuss: Large differences signal heteroskedasticity. Which coefficients are most affected?\n\n::: {#84e7c6c1 .cell execution_count=22}\n``` {.python .cell-code}\n# Your code here: Compare standard and robust SEs\n#\n# Example structure:\n# model_default = ols('imds ~ ln_NTLpc2017 + A00 + A10 + A20 + A30 + A40',\n#                     data=bol_cs).fit()\n# model_robust = ols('imds ~ ln_NTLpc2017 + A00 + A10 + A20 + A30 + A40',\n#                    data=bol_cs).fit(cov_type='HC1')\n#\n# comparison = pd.DataFrame({\n#     'Default SE': model_default.bse,\n#     'Robust SE': model_robust.bse,\n#     'Ratio': model_robust.bse / model_default.bse\n# })\n# print(\"STANDARD ERROR COMPARISON\")\n# print(comparison.round(4))\n# print(f\"\\nMean ratio: {(model_robust.bse / model_default.bse).mean():.3f}\")\n```\n:::\n\n\n#### Task 3: Residual Diagnostics (Semi-guided)\n\n**Objective**: Create diagnostic plots to assess model assumptions visually.\n\n**Instructions**:\n\n1. Estimate the model with robust SEs\n2. Create three diagnostic plots:\n   - (a) Fitted values vs. residuals (check for patterns/heteroskedasticity)\n   - (b) Q-Q plot of residuals (check for normality)\n   - (c) Histogram of residuals (check for skewness/outliers)\n\n3. Interpret each plot: What do the patterns reveal about model adequacy?\n\n**Hint**: Use `model.fittedvalues` and `model.resid` for the plots. For the Q-Q plot, use `from scipy import stats; stats.probplot(residuals, plot=ax)`.\n\n::: {#e1a63488 .cell execution_count=23}\n``` {.python .cell-code}\n# Your code here: Residual diagnostic plots\n#\n# Example structure:\n# from scipy import stats\n# model = ols('imds ~ ln_NTLpc2017 + A00 + A10 + A20 + A30 + A40',\n#             data=bol_cs).fit(cov_type='HC1')\n#\n# fig, axes = plt.subplots(1, 3, figsize=(15, 5))\n#\n# # (a) Residuals vs Fitted\n# axes[0].scatter(model.fittedvalues, model.resid, alpha=0.4)\n# axes[0].axhline(0, color='red', linestyle='--')\n# axes[0].set_xlabel('Fitted Values')\n# axes[0].set_ylabel('Residuals')\n# axes[0].set_title('Residuals vs Fitted')\n#\n# # (b) Q-Q Plot\n# stats.probplot(model.resid, plot=axes[1])\n# axes[1].set_title('Q-Q Plot of Residuals')\n#\n# # (c) Histogram\n# axes[2].hist(model.resid, bins=30, edgecolor='black', alpha=0.7)\n# axes[2].set_xlabel('Residuals')\n# axes[2].set_title('Distribution of Residuals')\n#\n# plt.tight_layout()\n# plt.show()\n```\n:::\n\n\n#### Task 4: Influential Municipalities (Semi-guided)\n\n**Objective**: Identify municipalities that disproportionately influence the regression results.\n\n**Instructions**:\n\n1. Calculate DFITS for all observations\n2. Apply the threshold: $|DFITS| > 2\\sqrt{k/n}$ where $k$ = number of parameters and $n$ = sample size\n3. Identify the municipalities that exceed the threshold\n4. Calculate DFBETAS for the key coefficient (`ln_NTLpc2017`)\n5. Discuss: Are the influential municipalities capital cities or special cases?\n\n**Hint**: Use `OLSInfluence(model)` from statsmodels to compute influence measures.\n\n::: {#48a55f10 .cell execution_count=24}\n``` {.python .cell-code}\n# Your code here: Influential observation analysis\n#\n# Example structure:\n# model = ols('imds ~ ln_NTLpc2017 + A00 + A10 + A20 + A30 + A40',\n#             data=bol_cs).fit()\n# infl = OLSInfluence(model)\n#\n# # DFITS\n# dfits_vals = infl.dffits[0]\n# k = len(model.params)\n# n = len(bol_cs)\n# threshold = 2 * np.sqrt(k / n)\n#\n# influential = bol_cs.copy()\n# influential['dfits'] = dfits_vals\n# influential_muns = influential[np.abs(influential['dfits']) > threshold]\n#\n# print(f\"DFITS threshold: {threshold:.4f}\")\n# print(f\"Influential municipalities: {len(influential_muns)} out of {n}\")\n# print(\"\\nInfluential municipalities:\")\n# print(influential_muns[['mun', 'dep', 'imds', 'ln_NTLpc2017', 'dfits']]\n#       .sort_values('dfits', key=abs, ascending=False).to_string(index=False))\n```\n:::\n\n\n> **Key Concept 16.12: Spatial Outliers and Influential Observations**\n>\n> In municipality-level analysis, **capital cities** and special economic zones often appear as influential observations. These municipalities may have unusually high NTL (from concentrated economic activity) or unusual satellite patterns (dense urban cores). A single influential municipality can shift regression coefficients substantially. DFITS and DFBETAS identify such observations, allowing us to assess whether our conclusions depend on a few exceptional cases.\n\n#### Task 5: Omitted Variable Analysis (Independent)\n\n**Objective**: Assess potential omitted variable bias by adding department controls.\n\n**Instructions**:\n\n1. Estimate models with and without department fixed effects (`C(dep)`)\n2. Compare the satellite coefficients across specifications\n3. Discuss: Do satellite coefficients change when adding department dummies?\n4. What is the direction of potential omitted variable bias?\n5. Consider: What unobserved factors might department dummies capture (geography, climate, policy)?\n\n::: {#971bd12a .cell execution_count=25}\n``` {.python .cell-code}\n# Your code here: Omitted variable analysis\n#\n# Example structure:\n# m_no_dept = ols('imds ~ ln_NTLpc2017 + A00 + A10', data=bol_cs).fit(cov_type='HC1')\n# m_with_dept = ols('imds ~ ln_NTLpc2017 + A00 + A10 + C(dep)', data=bol_cs).fit(cov_type='HC1')\n#\n# print(\"WITHOUT department controls:\")\n# print(f\"  NTL coef: {m_no_dept.params['ln_NTLpc2017']:.4f} (SE: {m_no_dept.bse['ln_NTLpc2017']:.4f})\")\n# print(f\"  R²: {m_no_dept.rsquared:.4f}\")\n#\n# print(\"\\nWITH department controls:\")\n# print(f\"  NTL coef: {m_with_dept.params['ln_NTLpc2017']:.4f} (SE: {m_with_dept.bse['ln_NTLpc2017']:.4f})\")\n# print(f\"  R²: {m_with_dept.rsquared:.4f}\")\n#\n# print(f\"\\nCoefficient change: {m_with_dept.params['ln_NTLpc2017'] - m_no_dept.params['ln_NTLpc2017']:.4f}\")\n```\n:::\n\n\n#### Task 6: Diagnostic Report (Independent)\n\n**Objective**: Write a 200-300 word comprehensive model assessment.\n\n**Your report should address**:\n\n1. **Multicollinearity**: Summarize VIF results for satellite features. Are any problematic?\n2. **Heteroskedasticity**: What does the SE comparison reveal? Should we use robust SEs?\n3. **Residual patterns**: What do the diagnostic plots show about model specification?\n4. **Influential observations**: Which municipalities are most influential? Do they represent special cases?\n5. **Omitted variables**: How do department controls affect the satellite coefficients?\n6. **Recommendations**: What corrections or modifications would you recommend for the satellite prediction model?\n\n::: {#e9199b8a .cell execution_count=26}\n``` {.python .cell-code}\n# Your code here: Additional analysis for the diagnostic report\n#\n# You might want to:\n# 1. Create a summary table of diagnostic findings\n# 2. Re-estimate the model excluding influential observations\n# 3. Compare results with and without corrections\n# 4. Summarize key statistics for your report\n```\n:::\n\n\n#### What You've Learned from This Case Study\n\nThrough this diagnostic analysis of the satellite prediction model, you've applied Chapter 16's complete toolkit to real geospatial data:\n\n- **Multicollinearity assessment**: Computed VIF for satellite features and identified correlated embeddings\n- **Heteroskedasticity detection**: Compared standard and robust SEs to assess variance assumptions\n- **Residual diagnostics**: Created visual diagnostic plots to check model assumptions\n- **Influence analysis**: Used DFITS and DFBETAS to identify municipalities that drive the results\n- **Omitted variable assessment**: Tested sensitivity of results to department controls\n- **Critical thinking**: Formulated recommendations for improving the satellite prediction model\n\n**Connection**: In Chapter 17, we move to *panel data*—analyzing how nighttime lights evolve over time across municipalities, using fixed effects to control for time-invariant characteristics.\n\n---\n\n",
    "supporting": [
      "ch16_Checking_the_Model_and_Data_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}