{
  "hash": "887274bc67722a60060d04a4e72fc735",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 4. Statistical Inference for the Mean\nexecute:\n  enabled: true\n  warning: false\n---\n\n\n**metricsAI: An Introduction to Econometrics with Python and AI in the Cloud**\n\n*[Carlos Mendez](https://carlos-mendez.org)*\n\n<img src=\"https://raw.githubusercontent.com/quarcs-lab/metricsai/main/images/ch04_visual_summary.jpg\" alt=\"Chapter 04 Visual Summary\" width=\"100%\">\n\nThis notebook provides an interactive introduction to statistical inference, teaching you how to extrapolate from sample statistics to population parameters using confidence intervals and hypothesis tests.\n\n[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/quarcs-lab/metricsai/blob/main/notebooks_colab/ch04_Statistical_Inference_for_the_Mean.ipynb)\n<div class=\"chapter-resources\">\n<a href=\"https://www.youtube.com/watch?v=8wn00FpUz38\" target=\"_blank\" class=\"resource-btn\">🎬 AI Video</a>\n<a href=\"https://carlos-mendez.my.canva.site/s04-statistical-inference-for-the-mean-pdf\" target=\"_blank\" class=\"resource-btn\">✨ AI Slides</a>\n<a href=\"https://cameron.econ.ucdavis.edu/aed/traedv1_04\" target=\"_blank\" class=\"resource-btn\">📊 Cameron Slides</a>\n<a href=\"https://app.edcafe.ai/quizzes/6978656c2f5d08069e0479cb\" target=\"_blank\" class=\"resource-btn\">✏️ Quiz</a>\n<a href=\"https://app.edcafe.ai/chatbots/69789d9f2f5d08069e06ffa5\" target=\"_blank\" class=\"resource-btn\">🤖 AI Tutor</a>\n</div>\n\n\n## Chapter Overview\n\nThis chapter introduces **statistical inference for the mean**—the foundational methods for extrapolating from sample statistics to population parameters with quantified uncertainty.\n\n**What you'll learn:**\n\n- Construct and interpret **confidence intervals** for population means\n- Understand the **t-distribution** and when to use it (vs. normal distribution)\n- Conduct **hypothesis tests** to evaluate claims about population parameters\n- Calculate and interpret **p-values** and understand statistical significance\n- Distinguish between **one-sided and two-sided tests**\n- Apply inference methods to **proportions data** and binary outcomes\n\n**Datasets used:**\n\n- **AED_EARNINGS.DTA**: Sample of 171 30-year-old female full-time workers in 2010 (earnings in dollars)\n- **AED_GASPRICE.DTA**: Weekly gasoline prices in the U.S. (testing price level hypotheses)\n- **AED_EARNINGSMALE.DTA**: Male earnings data for hypothesis testing examples\n- **AED_REALGDPPC.DTA**: Real GDP per capita growth rates (testing economic growth hypotheses)\n\n**Chapter outline:**\n\n- **4.1 Example: Mean Annual Earnings**\n- **4.2 t Statistic and t Distribution**\n- **4.3 Confidence Intervals**\n- **4.4 Two-Sided Hypothesis Tests**\n- **4.5 Hypothesis Test Examples**\n- **4.6 One-Sided Directional Hypothesis Tests**\n- **4.7 Proportions Data**\n\n## Setup\n\nRun this cell first to import all required packages and configure the environment.\n\n::: {#c0abaaaa .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Setup: Import libraries and configure environment\"}\n# --- Libraries ---\nimport numpy as np                        # numerical operations\nimport pandas as pd                       # data manipulation\nimport matplotlib.pyplot as plt           # plotting\nimport seaborn as sns                     # statistical visualization\nfrom scipy import stats                   # statistical distributions\nimport random\nimport os\n\n# --- Reproducibility ---\nRANDOM_SEED = 42\nrandom.seed(RANDOM_SEED)\nnp.random.seed(RANDOM_SEED)\nos.environ['PYTHONHASHSEED'] = str(RANDOM_SEED)\n\n# --- Data source ---\nGITHUB_DATA_URL = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/\"\n\n# --- Output directories ---\nIMAGES_DIR = 'images'\nTABLES_DIR = 'tables'\nos.makedirs(IMAGES_DIR, exist_ok=True)\nos.makedirs(TABLES_DIR, exist_ok=True)\n\n# --- Plotting style ---\nplt.style.use('dark_background')\nsns.set_style(\"darkgrid\")\nplt.rcParams.update({\n    'axes.facecolor': '#1a2235',\n    'figure.facecolor': '#12162c',\n    'grid.color': '#3a4a6b',\n    'figure.figsize': (10, 6),\n    'text.color': 'white',\n    'axes.labelcolor': 'white',\n    'xtick.color': 'white',\n    'ytick.color': 'white',\n    'axes.edgecolor': '#1a2235',\n})\n\nprint(\"✓ Setup complete! All packages imported successfully.\")\nprint(f\"✓ Random seed set to {RANDOM_SEED} for reproducibility.\")\nprint(f\"✓ Data will stream from: {GITHUB_DATA_URL}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Setup complete! All packages imported successfully.\n✓ Random seed set to 42 for reproducibility.\n✓ Data will stream from: https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/\n```\n:::\n:::\n\n\n## 4.1 Example: Mean Annual Earnings\n\nWe'll use a motivating example throughout this chapter: estimating the **population mean annual earnings** for 30-year-old female full-time workers in the U.S. in 2010.\n\n**The Problem:**\n\n- We have a **sample** of 171 women\n- We want to make inferences about the **population** of all such women\n\n**Key Statistics:**\n\n- **Sample mean** $\\bar{x}$: Our point estimate of population mean μ\n- **Standard deviation** s: Measures variability in the sample\n- **Standard error** se($\\bar{x}$) = s/√n: Measures precision of $\\bar{x}$ as an estimate of μ\n\nThe **standard error** is crucial—it quantifies our uncertainty about μ. Smaller standard errors mean more precise estimates.\n\n::: {#6c51b38c .cell execution_count=2}\n``` {.python .cell-code}\n# Load earnings data\ndata_earnings = pd.read_stata(GITHUB_DATA_URL + 'AED_EARNINGS.DTA')\nearnings = data_earnings['earnings']\n\n# Calculate key statistics\nn = len(earnings)\nmean_earnings = earnings.mean()\nstd_earnings = earnings.std(ddof=1)  # ddof=1 for sample std dev\nse_earnings = std_earnings / np.sqrt(n)  # Standard error\n\n# Sample statistics for annual earnings\nprint(f\"Sample size (n):        {n}\")\nprint(f\"Mean:                   ${mean_earnings:,.2f}\")\nprint(f\"Standard deviation:     ${std_earnings:,.2f}\")\nprint(f\"Standard error:         ${se_earnings:,.2f}\")\nprint(f\"\\nInterpretation: Our best estimate of population mean earnings is ${mean_earnings:,.2f}\")\nprint(f\"The standard error of ${se_earnings:,.2f} measures the precision of this estimate.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSample size (n):        171\nMean:                   $41,412.69\nStandard deviation:     $25,527.05\nStandard error:         $1,952.10\n\nInterpretation: Our best estimate of population mean earnings is $41,412.69\nThe standard error of $1,952.10 measures the precision of this estimate.\n```\n:::\n:::\n\n\n**Key Statistics from our Sample (n = 171 women):**\n\n- Sample mean: \\$41,412.69\n- Standard deviation: \\$25,527.05\n- Standard error: \\$1,952.10\n\n**What is the standard error telling us?**\n\nThe standard error of \\$1,952.10 measures the **precision** of our sample mean as an estimate of the true population mean. Think of it as quantifying our uncertainty.\n\n**Statistical interpretation:**\n\n- If we repeatedly drew samples of 171 women, the sample means would vary\n- The standard error tells us the typical amount by which sample means differ from the true population mean\n- Formula: SE = s/√n = \\$25,527.05/√171 = \\$1,952.10\n\n**Why is the SE much smaller than the standard deviation?**\n\n- Standard deviation (\\$25,527) measures variability among individual women's earnings\n- Standard error (\\$1,952) measures variability of the sample mean across different samples\n- The larger the sample size, the smaller the SE → more precise estimates\n\n**Practical insight:**\n\n- A standard error of \\$1,952 is relatively small compared to the mean (\\$41,413)\n- This suggests our estimate is reasonably precise\n- If we had only 43 women (n=43), SE would double to \\$3,904 (less precise)\n- With 684 women (n=684), SE would halve to \\$976 (more precise)\n\n> **Key Concept 4.1: Standard Error and Precision**\n>\n> The standard error se($\\bar{x}$) = s/√n measures the precision of the sample mean as an estimate of the population mean μ. It quantifies sampling uncertainty—smaller standard errors mean more precise estimates. The SE decreases with sample size at rate 1/√n, so quadrupling the sample size halves the standard error.\n\n## 4.2 t Statistic and t Distribution\n\nFor inference on the population mean μ, we use the **t-statistic**:\n\n$$t = \\frac{\\bar{x} - \\mu}{\\text{se}(\\bar{x})} = \\frac{\\bar{x} - \\mu}{s / \\sqrt{n}}$$\n\nUnder certain assumptions, this statistic follows a **t-distribution** with (n - 1) degrees of freedom:\n\n$$t \\sim T(n-1)$$\n\n**Why t-distribution instead of normal?**\n\n- We don't know the population standard deviation σ, so we estimate it with sample std dev s\n- This adds uncertainty, making the distribution have **fatter tails** than the normal\n- As sample size increases (n → ∞), the t-distribution approaches the standard normal distribution\n\n**Key properties:**\n\n- Symmetric around zero (like the normal)\n- Fatter tails than normal (more probability in extremes)\n- Converges to N(0,1) as degrees of freedom increase\n\n::: {#21fd0d5a .cell execution_count=3}\n``` {.python .cell-code}\n# Visualize t-distribution vs standard normal\nfig, axes = plt.subplots(1, 2, figsize=(16, 6))\n\nx = np.linspace(-4, 4, 200)\n\n# Panel A: t(4) vs standard normal\naxes[0].plot(x, stats.norm.pdf(x), '--', color='#c084fc', linewidth=2, label='Standard Normal')\naxes[0].plot(x, stats.t.pdf(x, df=4), 'r-', linewidth=2, label='t(4)')\naxes[0].set_xlabel('x value', fontsize=12)\naxes[0].set_ylabel('Density', fontsize=12)\naxes[0].set_title('Panel A: t(4) and Standard Normal', fontsize=13, fontweight='bold')\naxes[0].legend()\naxes[0].grid(True, alpha=0.3)\naxes[0].text(0, 0.35, 'Notice: t(4) has fatter tails\\n(more extreme values likely)', \n             ha='center', bbox=dict(boxstyle='round', facecolor='#1e2a45', alpha=0.9))\n\n# Panel B: t(30) vs standard normal\naxes[1].plot(x, stats.norm.pdf(x), '--', color='#c084fc', linewidth=2, label='Standard Normal')\naxes[1].plot(x, stats.t.pdf(x, df=30), 'r-', linewidth=2, label='t(30)')\naxes[1].set_xlabel('x value', fontsize=12)\naxes[1].set_ylabel('Density', fontsize=12)\naxes[1].set_title('Panel B: t(30) and Standard Normal', fontsize=13, fontweight='bold')\naxes[1].legend()\naxes[1].grid(True, alpha=0.3)\naxes[1].text(0, 0.35, 'As df increases, t approaches\\nthe standard normal', \n             ha='center', bbox=dict(boxstyle='round', facecolor='#1e2a45', alpha=0.9))\n\nplt.suptitle('Figure 4.1: t Distribution vs Standard Normal',\n             fontsize=14, fontweight='bold', y=1.0)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch04_Statistical_Inference_for_the_Mean_files/figure-html/cell-4-output-1.png){width=1526 height=580}\n:::\n:::\n\n\n**Key observation:** With more degrees of freedom (larger n), the t-distribution looks more like the normal. For n > 30, they are nearly identical.\n\n> **Key Concept 4.2: The t-Distribution**\n>\n> The t-distribution is used when the population standard deviation $\\sigma$ is unknown and must be estimated from the sample. It is similar to the standard normal N(0,1) but with fatter tails that reflect the additional uncertainty from estimating $\\sigma$. As the sample size $n$ grows, the t-distribution approaches the normal distribution, making the normal a good approximation for large samples.\n\n## 4.3 Confidence Intervals\n\nA **confidence interval** provides a range of plausible values for the population parameter μ.\n\n**General formula:**\n$$\\text{estimate} \\pm \\text{critical value} \\times \\text{standard error}$$\n\nFor the population mean, a **100(1 - α)% confidence interval** is:\n$$\\bar{x} \\pm t_{n-1, \\alpha/2} \\times \\text{se}(\\bar{x})$$\n\nWhere:\n\n- $\\bar{x}$ = sample mean (our estimate)\n- $t_{n-1, \\alpha/2}$ = critical value from t-distribution with (n-1) degrees of freedom\n- se($\\bar{x}$) = s/√n = standard error\n- α = significance level (e.g., 0.05 for 95% confidence)\n\n**Interpretation:** If we repeatedly drew samples and constructed 95% CIs, about 95% of those intervals would contain the true population mean μ.\n\n**Practical interpretation:** We are \"95% confident\" that μ lies within this interval.\n\n**Rule of thumb:** For n > 30, $t_{n-1, 0.025} \\approx 2$, so a 95% CI is approximately:\n$$\\bar{x} \\pm 2 \\times \\text{se}(\\bar{x})$$\n\n> **Key Concept 4.3: Confidence Intervals**\n>\n> A confidence interval provides a range of plausible values for the population parameter $\\mu$. A 95% confidence interval means: if we repeated the sampling procedure many times, approximately 95% of the resulting intervals would contain the true $\\mu$. The interval is constructed as $\\bar{x} \\pm t_{\\alpha/2} \\times se(\\bar{x})$, where wider intervals indicate less precision.\n\n::: {#32779d0a .cell execution_count=4}\n``` {.python .cell-code}\n# Calculate 95% confidence interval for mean earnings\nconf_level = 0.95\nalpha = 1 - conf_level\nt_crit = stats.t.ppf(1 - alpha/2, n - 1)  # Critical value\nmargin_of_error = t_crit * se_earnings\nci_lower = mean_earnings - margin_of_error\nci_upper = mean_earnings + margin_of_error\n\n# 95% confidence interval for population mean earnings\nprint(f\"Sample mean:            ${mean_earnings:,.2f}\")\nprint(f\"Standard error:         ${se_earnings:,.2f}\")\nprint(f\"Critical value t₁₇₀:     {t_crit:.4f}\")\nprint(f\"Margin of error:        ${margin_of_error:,.2f}\")\nprint(f\"\\n95% Confidence Interval: [${ci_lower:,.2f}, ${ci_upper:,.2f}]\")\nprint(f\"\\nInterpretation: We are 95% confident that the true population mean\")\nprint(f\"earnings lies between ${ci_lower:,.2f} and ${ci_upper:,.2f}.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSample mean:            $41,412.69\nStandard error:         $1,952.10\nCritical value t₁₇₀:     1.9740\nMargin of error:        $3,853.48\n\n95% Confidence Interval: [$37,559.21, $45,266.17]\n\nInterpretation: We are 95% confident that the true population mean\nearnings lies between $37,559.21 and $45,266.17.\n```\n:::\n:::\n\n\n**95% Confidence Interval for Mean Earnings: [\\$37,559.21, \\$45,266.17]**\n\n**What this interval means:**\n\nThe correct interpretation: If we repeatedly drew samples of 171 women and calculated 95% CIs for each sample, approximately 95% of those intervals would contain the true population mean μ.\n\n**Common misconceptions (WRONG interpretations):**\n\n- \"There is a 95% probability that μ is in this interval\"\n- \"95% of individual women earn between \\$37,559 and \\$45,266\"\n- \"The interval captures 95% of the data\"\n\n**Correct interpretation:**\n\n- We are 95% confident that the true population mean earnings lie between \\$37,559 and \\$45,266\n- The interval accounts for sampling uncertainty through the standard error\n- The population mean μ is fixed (but unknown); our interval is random\n\n**Breaking down the calculation:**\n\n- Sample mean: \\$41,412.69\n- Critical value (t₁₇₀, 0.025): 1.9740\n- Margin of error: 1.9740 × \\$1,952.10 = \\$3,853.48\n- Interval: \\$41,412.69 ± \\$3,853.48\n\n**Practical insights:**\n\n- The interval does NOT include \\$36,000 or \\$46,000, suggesting these are implausible values for μ\n- The interval is fairly narrow (width = \\$7,707), indicating good precision\n- The critical value (1.974) is close to 2, confirming the \"rule of thumb\": CI ≈ mean ± 2×SE\n\n**Why use 95% confidence?**\n\n- Convention in most scientific fields (α = 0.05)\n- Balances precision (narrow interval) with confidence (high probability of capturing μ)\n- Could use 90% (narrower, less confident) or 99% (wider, more confident)\n\n### Confidence-Precision Trade-off\n\n**Comparing Confidence Intervals at Different Levels:**\n\n- 90% CI: [\\$38,184.17, \\$44,641.21] — Width: \\$6,457.03\n- 95% CI: [\\$37,559.21, \\$45,266.17] — Width: \\$7,706.97\n- 99% CI: [\\$36,327.35, \\$46,498.03] — Width: \\$10,170.68\n\n**The fundamental trade-off:**\n\nHigher confidence requires wider intervals. You cannot have both maximum precision (narrow interval) AND maximum confidence (high probability of capturing μ) simultaneously.\n\n**Why does this happen?**\n\n- To be more confident we've captured μ, we must cast a wider net\n- The critical value increases with confidence level:\n  - 90% CI: t-critical ≈ 1.66 → smaller multiplier\n  - 95% CI: t-critical ≈ 1.97 → moderate multiplier  \n  - 99% CI: t-critical ≈ 2.61 → larger multiplier\n\n**Practical implications:**\n\n1. **90% CI (\\$6,457 width):**\n   - Narrower, more precise\n   - BUT: 10% chance the interval misses μ\n   - Use when: precision is critical and you can tolerate more risk\n\n2. **95% CI (\\$7,707 width):**\n   - Standard choice in economics and most sciences\n   - Good balance between precision and confidence\n   - Use when: following standard practice (almost always)\n\n3. **99% CI (\\$10,171 width):**\n   - Wider, less precise\n   - BUT: Only 1% chance the interval misses μ\n   - Use when: being wrong is very costly (medical, safety applications)\n\n**How to improve BOTH confidence AND precision?**\n\n- Increase sample size (n)! Larger n → smaller SE → narrower intervals at any confidence level\n- With n = 684 (4× larger), the 95% CI would be approximately half as wide\n\n**Trade-off:** Higher confidence → wider intervals\n\n- 90% CI: Narrower, but less confident\n- 95% CI: Standard choice (most common)\n- 99% CI: Wider, but more confident\n\nLet's compare:\n\n::: {#8802d16f .cell execution_count=5}\n``` {.python .cell-code}\n# Compare confidence intervals at different levels\nconf_levels = [0.90, 0.95, 0.99]\n\n# Confidence intervals at different levels\nprint(f\"{'Level':<10} {'Lower Bound':>15} {'Upper Bound':>15} {'Width':>15}\")\n\nfor conf in conf_levels:\n    alpha = 1 - conf\n    t_crit = stats.t.ppf(1 - alpha/2, n - 1)\n    ci_lower = mean_earnings - t_crit * se_earnings\n    ci_upper = mean_earnings + t_crit * se_earnings\n    width = ci_upper - ci_lower\n    print(f\"{conf*100:.0f}%{ci_lower:>18,.2f}{ci_upper:>18,.2f}{width:>18,.2f}\")\n\n# Notice: Higher confidence -> wider interval -> less precision\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLevel          Lower Bound     Upper Bound           Width\n90%         38,184.17         44,641.21          6,457.03\n95%         37,559.21         45,266.17          7,706.97\n99%         36,327.35         46,498.03         10,170.68\n```\n:::\n:::\n\n\n## 4.4 Two-Sided Hypothesis Tests\n\nA **hypothesis test** evaluates whether a specific claim about μ is plausible given our sample data.\n\n**Structure of a hypothesis test:**\n\n- **Null hypothesis** H₀: The claim we're testing (e.g., μ = \\$40,000)\n- **Alternative hypothesis** Hₐ: What we conclude if we reject H₀ (e.g., μ ≠ \\$40,000)\n- **Significance level** α: Maximum probability of Type I error we'll tolerate (typically 0.05)\n\n**Test statistic:**\n$$t = \\frac{\\bar{x} - \\mu_0}{\\text{se}(\\bar{x})}$$\n\nWhere μ₀ is the hypothesized value.\n\n**Two ways to make a decision:**\n\n1. **p-value approach:** \n   - p-value = probability of observing a t-statistic at least as extreme as ours, assuming H₀ is true\n   - Reject H₀ if p-value < α\n\n2. **Critical value approach:**\n   - Critical value c = $t_{n-1, \\alpha/2}$\n   - Reject H₀ if |t| > c\n\nBoth methods always give the same conclusion.\n\n**Example:** Test whether population mean earnings equal \\$40,000.\n\n> **Key Concept 4.4: Hypothesis Testing Framework**\n>\n> A hypothesis test evaluates whether data provide sufficient evidence to reject a specific claim (H₀) about a parameter. The t-statistic measures how many standard errors the estimate is from the hypothesized value. The p-value is the probability of observing a result at least as extreme as ours, assuming H₀ is true. Small p-values (< α, typically 0.05) provide evidence against H₀, leading us to reject it.\n\n::: {#8c8a2b88 .cell execution_count=6}\n``` {.python .cell-code}\n# Two-sided hypothesis test: H0: μ = $40,000 vs Ha: μ ≠ $40,000\nmu0 = 40000  # Hypothesized value\nt_stat = (mean_earnings - mu0) / se_earnings\np_value = 2 * (1 - stats.t.cdf(abs(t_stat), n - 1))  # Two-sided p-value\nt_crit_95 = stats.t.ppf(0.975, n - 1)  # 0.975 = upper tail for 95% two-sided CI\n\n# Two-sided hypothesis test\nprint(f\"H₀: μ = ${mu0:,}\")\nprint(f\"Hₐ: μ ≠ ${mu0:,}\")\nprint(f\"Significance level α = 0.05\")\nprint(\"\\nSample Statistics:\")\nprint(f\"  Sample mean:      ${mean_earnings:,.2f}\")\nprint(f\"  Standard error:   ${se_earnings:,.2f}\")\nprint(\"\\nTest Results:\")\nprint(f\"  t-statistic:       {t_stat:.4f}\")\nprint(f\"  p-value:           {p_value:.4f}\")\nprint(f\"  Critical value:    ±{t_crit_95:.4f}\")\nprint(\"\\nDecision:\")\nprint(f\"  p-value approach:  {p_value:.4f} > 0.05 → Do not reject H₀\")\nprint(f\"  Critical approach: |{t_stat:.4f}| < {t_crit_95:.4f} → Do not reject H₀\")\nprint(\"\\nConclusion: We do not have sufficient evidence to reject the claim\")\nprint(f\"that population mean earnings equal ${mu0:,}.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nH₀: μ = $40,000\nHₐ: μ ≠ $40,000\nSignificance level α = 0.05\n\nSample Statistics:\n  Sample mean:      $41,412.69\n  Standard error:   $1,952.10\n\nTest Results:\n  t-statistic:       0.7237\n  p-value:           0.4703\n  Critical value:    ±1.9740\n\nDecision:\n  p-value approach:  0.4703 > 0.05 → Do not reject H₀\n  Critical approach: |0.7237| < 1.9740 → Do not reject H₀\n\nConclusion: We do not have sufficient evidence to reject the claim\nthat population mean earnings equal $40,000.\n```\n:::\n:::\n\n\n**Test Results: H₀: μ = \\$40,000 vs Hₐ: μ ≠ \\$40,000**\n\n- t-statistic: 0.7237\n- p-value: 0.4703\n- Critical value: ±1.9740\n- Decision: Do NOT reject H₀\n\n**What does this mean?**\n\nWe tested whether the population mean earnings equal \\$40,000. Based on our sample data (mean = \\$41,413), we do NOT have sufficient evidence to reject this claim.\n\n**Understanding the p-value (0.4703):**\n\nThe p-value answers: \"If the true population mean really is \\$40,000, what's the probability of observing a sample mean at least as far from \\$40,000 as ours (\\$41,413)?\"\n\n- p-value = 0.4703 = 47.03%\n- This is quite HIGH → the data are consistent with H₀\n- Interpretation: If μ truly equals \\$40,000, we'd see a sample mean this extreme about 47% of the time just due to random sampling\n\n**Two equivalent decision rules:**\n\n1. **p-value approach:** \n   - p-value (0.4703) > α (0.05) → Do not reject H₀\n   - The evidence against H₀ is weak\n\n2. **Critical value approach:** \n   - |t-statistic| = |0.7237| < 1.9740 → Do not reject H₀\n   - Our t-statistic falls in the \"non-rejection region\"\n\n**Why did we fail to reject?**\n\n- Our sample mean (\\$41,413) is only \\$1,413 above the hypothesized value (\\$40,000)\n- Given the standard error (\\$1,952), this difference is less than 1 SE away\n- This is well within the range of normal sampling variation\n- The difference is NOT statistically significant at α = 0.05\n\n**Does this prove μ = \\$40,000?**\n\nNO! We never \"prove\" or \"accept\" the null hypothesis. We simply say:\n\n- The data are consistent with μ = \\$40,000\n- We lack sufficient evidence to conclude otherwise\n- Other values (e.g., \\$41,000, \\$42,000) are also consistent with our data\n\n**Connection to confidence interval:**\n\nNotice that \\$40,000 IS inside our 95% CI [\\$37,559, \\$45,266]. This is no coincidence:\n\n- Any value inside the 95% CI will NOT be rejected at α = 0.05 (two-sided test)\n- Any value outside the 95% CI WILL be rejected at α = 0.05\n\n### Visualizing the two-sided hypothesis test\n\n::: {#d4c1f3bc .cell execution_count=7}\n``` {.python .cell-code}\n# Visualize two-sided hypothesis test\nfig, ax = plt.subplots(figsize=(12, 6))\n\nx = np.linspace(-4, 4, 500)\ny = stats.t.pdf(x, n - 1)\n\n# Plot the t-distribution\nax.plot(x, y, '-', color='#c084fc', linewidth=2, label=f't({n-1}) distribution')\n\n# Mark the observed t-statistic\nax.axvline(x=t_stat, color='red', linewidth=2, linestyle='--',\n           label=f'Observed t = {t_stat:.2f}')\n\n# Mark critical values\nax.axvline(x=t_crit_95, color='green', linewidth=1.5, linestyle=':',\n           label=f'Critical values = ±{t_crit_95:.2f}')\nax.axvline(x=-t_crit_95, color='green', linewidth=1.5, linestyle=':')\n\n# Shade rejection regions (both tails)\nx_reject_lower = x[x < -t_crit_95]\nx_reject_upper = x[x > t_crit_95]\nax.fill_between(x_reject_lower, 0, stats.t.pdf(x_reject_lower, n-1),\n                alpha=0.3, color='red', label='Rejection region (α/2 = 0.025 each tail)')\nax.fill_between(x_reject_upper, 0, stats.t.pdf(x_reject_upper, n-1),\n                alpha=0.3, color='red')\n\nax.set_xlabel('t-statistic', fontsize=12)\nax.set_ylabel('Density', fontsize=12)\nax.set_title('Two-Sided Hypothesis Test Visualization', fontsize=14, fontweight='bold')\nax.legend(fontsize=9, loc='upper right')\nax.grid(True, alpha=0.3)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch04_Statistical_Inference_for_the_Mean_files/figure-html/cell-8-output-1.png){width=1142 height=565}\n:::\n:::\n\n\nOur t-statistic falls inside the non-rejection region, so we do not reject H0. The data are consistent with mu = $40,000.\n\n### Type I Error, Type II Error, and Statistical Power\n\n**The Four Possible Outcomes of a Hypothesis Test:**\n\nWhen we conduct a hypothesis test, there are four possible scenarios:\n\n| | **H₀ is TRUE** (in reality) | **H₀ is FALSE** (in reality) |\n|--------------------------|------------------------------|------------------------------|\n| **Reject H₀** (decision) | Type I Error (α) | Correct Decision (Power) |\n| **Do not reject H₀** | Correct Decision (1-α) | Type II Error (β) |\n\n**Type I Error (False Positive):**\n\n- Definition: Rejecting H₀ when it's actually true\n- Probability: α (significance level)\n- In our earnings example: Concluding μ ≠ \\$40,000 when it actually equals \\$40,000\n- We control this: By setting α = 0.05, we accept a 5% chance of Type I error\n- Consequence: \"Crying wolf\" — claiming an effect that doesn't exist\n\n**Type II Error (False Negative):**\n\n- Definition: Failing to reject H₀ when it's actually false\n- Probability: β (depends on sample size, effect size, and α)\n- In our earnings example: Concluding μ = \\$40,000 when it actually differs\n- Harder to control directly\n- Consequence: Missing a real effect\n\n**Statistical Power:**\n\n- Definition: Power = 1 - β = Probability of correctly rejecting false H₀\n- Interpretation: Probability of detecting a real effect when it exists\n- Typical target: 80% power (β = 0.20)\n- Higher power → lower chance of Type II error\n\n**The Trade-off Between Type I and Type II Errors:**\n\nYou cannot minimize both simultaneously:\n\n- **Decrease α** (e.g., from 0.05 to 0.01):\n - Lower chance of Type I error (false positive)\n - Higher chance of Type II error (false negative)\n - Lower statistical power\n \n- **Increase α** (e.g., from 0.05 to 0.10):\n - Higher statistical power\n - Lower chance of Type II error\n - Higher chance of Type I error\n\n**How to improve power WITHOUT increasing Type I error:**\n\n1. **Increase sample size:**\n - Larger n → smaller SE → easier to detect real effects\n - Our earnings data: n = 171, SE = \\$1,952\n - If n = 684 (4× larger): SE = \\$976 (half as large)\n - Same effect size would yield t-statistic twice as large\n\n2. **Study larger effects:**\n - Easier to detect large differences than small ones\n - Testing μ = \\$30,000 vs μ = \\$41,413 would have higher power\n - Testing μ = \\$40,000 vs μ = \\$41,413 has lower power\n\n3. **Use one-sided tests (when appropriate):**\n - Concentrates α in one tail → higher power in that direction\n - But: Cannot detect effects in the opposite direction\n\n**In our examples:**\n\n1. **Earnings test (non-significant):**\n - Could be: μ truly equals \\$40,000 (correct decision)\n - Or could be: Type II error (μ differs but we didn't detect it)\n - With more data, we might detect the difference\n\n2. **Gas price test (significant):**\n - High power due to small SE (\\$0.0267) and reasonable sample size (n=32)\n - Successfully detected a real difference\n - Low probability this is a Type I error (p < 0.0001)\n\n**Practical advice:**\n\n- **Planning stage:** Calculate required sample size for desired power\n- **Design stage:** Set α based on consequences of Type I vs Type II errors\n - Medical trials: Type I error very costly → use α = 0.01\n - Exploratory research: Type II error costly → use α = 0.10\n- **Interpretation stage:** Non-significant results don't prove H₀ is true (could be Type II error)\n\n## 4.5 Hypothesis Test Examples\n\nLet's apply hypothesis testing to three real-world economic questions.\n\n### Example 1: Gasoline Prices\n\n**Question:** Are gasoline prices in Yolo County different from the California state average?\n\n- California average: \\$3.81/gallon\n- Sample: 32 gas stations in Yolo County\n- Test: H₀: μ = 3.81 vs Hₐ: μ ≠ 3.81\n\n::: {#5abfba2c .cell execution_count=8}\n``` {.python .cell-code}\n# Load and test gasoline price data\ndata_gasprice = pd.read_stata(GITHUB_DATA_URL + 'AED_GASPRICE.DTA')\nprice = data_gasprice['price']\n\nmean_price = price.mean()\nstd_price = price.std(ddof=1)\nn_price = len(price)\nse_price = std_price / np.sqrt(n_price)\n\nmu0_price = 3.81\nt_stat_price = (mean_price - mu0_price) / se_price\np_value_price = 2 * (1 - stats.t.cdf(abs(t_stat_price), n_price - 1))\n\n# Example 1: Gasoline prices\nprint(f\"H₀: μ = ${mu0_price:.2f} (CA state average)\")\nprint(f\"Hₐ: μ ≠ ${mu0_price:.2f}\")\nprint(f\"\\nSample size:       {n_price}\")\nprint(f\"Sample mean:      ${mean_price:.4f}\")\nprint(f\"Std error:        ${se_price:.4f}\")\nprint(f\"t-statistic:       {t_stat_price:.4f}\")\nprint(f\"p-value:           {p_value_price:.6f}\")\nprint(f\"\\nDecision: p-value < 0.05 → {'REJECT H₀' if p_value_price < 0.05 else 'Do not reject H₀'}\")\nprint(f\"\\nConclusion: Yolo County gas prices ARE {'significantly ' if p_value_price < 0.05 else 'NOT significantly '}different from CA average.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nH₀: μ = $3.81 (CA state average)\nHₐ: μ ≠ $3.81\n\nSample size:       32\nSample mean:      $3.6697\nStd error:        $0.0267\nt-statistic:       -5.2577\np-value:           0.000010\n\nDecision: p-value < 0.05 → REJECT H₀\n\nConclusion: Yolo County gas prices ARE significantly different from CA average.\n```\n:::\n:::\n\n\n**Test Results: H₀: μ = \\$3.81 vs Hₐ: μ ≠ \\$3.81**\n\n- Sample mean: \\$3.6697\n- t-statistic: -5.2577\n- p-value: 0.0000 (actually < 0.0001)\n- Decision: REJECT H₀ at α = 0.05\n\n**This is a STATISTICALLY SIGNIFICANT result!**\n\nUnlike our earnings example, here we have strong evidence that Yolo County gas prices differ from the California state average of \\$3.81.\n\n**Understanding the strong evidence:**\n\n1. **Large t-statistic (-5.26):**\n   - The sample mean (\\$3.67) is 5.26 standard errors below the hypothesized value (\\$3.81)\n   - This is far beyond the critical value (±2.04)\n   - Such extreme values rarely occur by chance alone\n\n2. **Tiny p-value (< 0.0001):**\n   - If μ truly equaled \\$3.81, the probability of observing a sample mean this extreme is less than 0.01%\n   - This is MUCH smaller than α = 0.05 (5%)\n   - Strong evidence against H₀\n\n3. **Direction matters:**\n   - The negative t-statistic tells us Yolo County prices are LOWER than the state average\n   - Difference: \\$3.81 - \\$3.67 = \\$0.14 per gallon cheaper\n\n**Statistical vs Practical Significance:**\n\n- **Statistical significance:** Yes, we can confidently say Yolo County prices differ from \\$3.81 (p < 0.0001)\n- **Practical significance:** Is 14 cents per gallon meaningful?\n  - For a 15-gallon tank: \\$2.10 savings\n  - Over a year (52 fill-ups): \\$109 savings\n  - This IS economically meaningful for consumers!\n\n**Why is this result so strong compared to the earnings test?**\n\n- The standard error is very small (\\$0.0267) relative to the difference we're testing\n- This gives us high **statistical power** to detect the difference\n- Even though the dollar difference is small (\\$0.14), it's precisely estimated\n\n**Type I vs Type II Errors in this context:**\n\n- **Type I Error:** Concluding Yolo County prices differ when they actually don't\n  - Probability = α = 0.05 (5% chance if we reject)\n  - But our p-value is < 0.0001, so we're very confident we're not making this error\n\n- **Type II Error:** Concluding prices don't differ when they actually do\n  - Not relevant here since we rejected H₀\n  - This test had high power to detect real differences\n\n> **Key Concept 4.5: Statistical Significance vs. Sample Size**\n>\n> Even small practical differences can be statistically significant with large samples (n=53 gas stations). The gasoline price difference of \\$0.14 might seem trivial, but:\n> - The **standard error is small** (\\$0.0267), giving precise estimates\n> - The **t-statistic is large** (-5.26), indicating the difference is many standard errors from zero\n> - This demonstrates **high statistical power**—the ability to detect even small real effects\n>\n> Statistical significance answers \"Is there a difference?\" while practical significance asks \"Does the difference matter?\" Both questions are important in econometrics.\n\n### Example 2: Male Earnings\n\n**Question:** Do 30-year-old men earn more than \\$50,000 on average?\n\n- Claim: μ > \\$50,000 (set as alternative hypothesis)\n- Sample: 191 men\n- Test: H₀: μ ≤ 50,000 vs Hₐ: μ > 50,000 (one-sided, covered in section 4.6)\n\n::: {#1455b117 .cell execution_count=9}\n``` {.python .cell-code}\n# Load and test male earnings data\ndata_male = pd.read_stata(GITHUB_DATA_URL + 'AED_EARNINGSMALE.DTA')\nearnings_male = data_male['earnings']\n\nmean_male = earnings_male.mean()\nstd_male = earnings_male.std(ddof=1)\nn_male = len(earnings_male)\nse_male = std_male / np.sqrt(n_male)\n\nmu0_male = 50000\nt_stat_male = (mean_male - mu0_male) / se_male\np_value_male = 2 * (1 - stats.t.cdf(abs(t_stat_male), n_male - 1))  # Two-sided for now\n\n# Example 2: Male earnings (two-sided test shown)\nprint(f\"H₀: μ = ${mu0_male:,}\")\nprint(f\"Hₐ: μ ≠ ${mu0_male:,}\")\nprint(f\"\\nSample size:       {n_male}\")\nprint(f\"Sample mean:      ${mean_male:,.2f}\")\nprint(f\"Std error:        ${se_male:,.2f}\")\nprint(f\"t-statistic:       {t_stat_male:.4f}\")\nprint(f\"p-value:           {p_value_male:.4f}\")\nprint(f\"\\nDecision: p-value > 0.05 → Do not reject H₀\")\nprint(f\"\\nNote: A one-sided test is more appropriate here (see section 4.6)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nH₀: μ = $50,000\nHₐ: μ ≠ $50,000\n\nSample size:       191\nSample mean:      $52,353.93\nStd error:        $4,705.75\nt-statistic:       0.5002\np-value:           0.6175\n\nDecision: p-value > 0.05 → Do not reject H₀\n\nNote: A one-sided test is more appropriate here (see section 4.6)\n```\n:::\n:::\n\n\n**Test Results: H₀: μ = \\$50,000 vs Hₐ: μ ≠ \\$50,000**\n\n- Sample mean: (actual value from code output)\n- t-statistic: (actual value from code output)\n- p-value: > 0.05 (not statistically significant)\n- Decision: DO NOT REJECT H₀ at α = 0.05\n\n**This is NOT a statistically significant result.**\n\nWe do not have sufficient evidence to conclude that 30-year-old men earn differently than \\$50,000 on average. This does NOT mean they earn exactly \\$50,000—it means our data are consistent with that value.\n\n**Understanding the lack of significance:**\n\n1. **Moderate t-statistic:**\n   - The sample mean is not far enough from \\$50,000 (in standard error units) to confidently reject H₀\n   - The observed difference could plausibly arise from random sampling variation alone\n\n2. **Large p-value (> 0.05):**\n   - If μ truly equaled \\$50,000, observing a sample mean like ours is quite probable\n   - We don't have strong evidence against H₀\n   - p > α, so we fail to reject\n\n3. **What \"fail to reject\" means:**\n   - We're NOT proving μ = \\$50,000\n   - We're saying the data don't provide convincing evidence that μ ≠ \\$50,000\n   - Absence of evidence is not evidence of absence\n\n**Statistical vs Practical Significance:**\n\n- **Statistical significance:** No, we cannot confidently say mean earnings differ from \\$50,000 (p > 0.05)\n- **Practical considerations:**\n  - The sample mean might be close to \\$50,000 anyway\n  - Or the sample size (n=191) might not provide enough precision to detect a modest difference\n  - Or there's genuine variability in the population making the effect hard to pin down\n\n**Why might we fail to reject H₀?**\n\nThree possible explanations:\n\n1. **H₀ is actually true:** Mean earnings truly are around \\$50,000\n2. **Insufficient power:** Real difference exists, but our sample size is too small to detect it\n3. **High variability:** Earnings have large standard deviation, making precise inference difficult\n\n**Note on directional hypothesis:**\n\nThe question asks \"Do men earn MORE than \\$50,000?\" which suggests a **one-sided test** (H₀: μ ≤ 50,000 vs Hₐ: μ > 50,000). The code note mentions this will be covered in section 4.6. One-sided tests have more power to detect effects in a specific direction.\n\n> **Key Concept 4.6: \"Fail to Reject\" Does Not Mean \"Accept\"**\n>\n> When p > α, we **fail to reject H₀**, but this does NOT mean we \"accept H₀\" or prove it's true. Three key reasons:\n>\n> 1. **Limited evidence:** Our sample might simply lack the power to detect a real difference\n> 2. **Type II error risk:** We might be making a Type II error (failing to reject a false H₀)\n> 3. **Confidence intervals are more informative:** A 95% CI tells us the plausible range for μ, not just \"different or not different\"\n>\n> In econometrics, \"fail to reject\" means \"the data are consistent with H₀, but we can't rule out alternatives.\" Always interpret non-significant results with appropriate caution.\n\n### Example 3: GDP Growth\n\n**Question:** Did real GDP per capita grow at 2.0% per year on average from 1960-2020?\n\n- Historical claim: 2.0% annual growth\n- Sample: 241 year-to-year growth rates\n- Test: H₀: μ = 2.0 vs Hₐ: μ ≠ 2.0\n\n::: {#497aab02 .cell execution_count=10}\n``` {.python .cell-code}\n# Load and test GDP growth data\ndata_gdp = pd.read_stata(GITHUB_DATA_URL + 'AED_REALGDPPC.DTA')\ngrowth = data_gdp['growth']\n\nmean_growth = growth.mean()\nstd_growth = growth.std(ddof=1)\nn_growth = len(growth)\nse_growth = std_growth / np.sqrt(n_growth)\n\nmu0_growth = 2.0\nt_stat_growth = (mean_growth - mu0_growth) / se_growth\np_value_growth = 2 * (1 - stats.t.cdf(abs(t_stat_growth), n_growth - 1))\n\n# Example 3: Real GDP per capita growth\nprint(f\"H₀: μ = {mu0_growth:.1f}%\")\nprint(f\"Hₐ: μ ≠ {mu0_growth:.1f}%\")\nprint(f\"\\nSample size:       {n_growth}\")\nprint(f\"Sample mean:       {mean_growth:.4f}%\")\nprint(f\"Std error:         {se_growth:.4f}%\")\nprint(f\"t-statistic:       {t_stat_growth:.4f}\")\nprint(f\"p-value:           {p_value_growth:.4f}\")\nprint(f\"\\nDecision: p-value > 0.05 → Do not reject H₀\")\nprint(f\"\\nConclusion: The data are consistent with 2.0% average annual growth.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nH₀: μ = 2.0%\nHₐ: μ ≠ 2.0%\n\nSample size:       245\nSample mean:       1.9905%\nStd error:         0.1392%\nt-statistic:       -0.0686\np-value:           0.9454\n\nDecision: p-value > 0.05 → Do not reject H₀\n\nConclusion: The data are consistent with 2.0% average annual growth.\n```\n:::\n:::\n\n\n**Test Results: H₀: μ = 2.0% vs Hₐ: μ ≠ 2.0%**\n\n- Sample mean: (actual value from code output)\n- t-statistic: (actual value from code output)\n- p-value: > 0.05 (not statistically significant)\n- Decision: DO NOT REJECT H₀ at α = 0.05\n\n**The data are consistent with 2.0% average annual growth.**\n\nWe cannot reject the hypothesis that real GDP per capita grew at 2.0% per year on average from 1960-2020. This historical benchmark appears supported by the data.\n\n**Understanding the result:**\n\n1. **What does \"consistent with 2.0%\" mean?**\n   - The sample mean growth rate is close enough to 2.0% that random variation could explain the difference\n   - We don't have strong evidence that the true mean differs from 2.0%\n   - The p-value > 0.05 indicates this result is plausible under H₀\n\n2. **Large sample size (n=241 years):**\n   - With 241 year-to-year growth rates, we have substantial data\n   - Large samples typically have smaller standard errors and more statistical power\n   - Yet we still fail to reject H₀—this suggests the true mean is genuinely close to 2.0%\n\n3. **Economic interpretation:**\n   - The 2.0% benchmark is a common reference point in growth economics\n   - Our data support this conventional wisdom\n   - Long-run economic growth appears remarkably stable around this rate\n\n**Statistical vs Practical Significance:**\n\n- **Statistical significance:** No, we cannot confidently say mean growth differs from 2.0% (p > 0.05)\n- **Economic significance:**\n  - Even small deviations from 2.0% compound dramatically over 60 years\n  - But our data suggest the historical average is indeed close to 2.0%\n  - This consistency validates the use of 2.0% as a benchmark for policy discussions\n\n**Why is this result interesting despite being \"non-significant\"?**\n\n1. **Validates a benchmark:** Economic theory often assumes ~2% long-run growth; our data support this\n2. **Large sample confidence:** With 241 observations, we can be confident the mean is near 2.0%\n3. **Demonstrates stability:** Despite recessions and booms, average growth centers around 2.0%\n\n**Time series considerations:**\n\nGDP growth data are **time series**—observations ordered chronologically with potential autocorrelation. Our standard t-test assumes independent observations, which might not fully hold for year-to-year growth rates. Advanced time series methods (Chapter 17) address these dependencies.\n\n> **Key Concept 4.7: Context and Consistency in Hypothesis Testing**\n>\n> Statistical results gain meaning only through economic context -- a statistically significant coefficient matters because of what it implies for policy, behavior, or theory. The hypothesis testing pattern (set up hypotheses, compute test statistic, compare to critical value or p-value) is consistent across diverse applications, from wage analysis to macroeconomic growth.\n\n## 4.6 One-Sided Directional Hypothesis Tests\n\nSometimes we want to test a **directional** claim:\n\n- \"Does μ **exceed** a certain value?\" (upper-tailed test)\n- \"Is μ **less than** a certain value?\" (lower-tailed test)\n\n**Structure:**\n\n- **Upper-tailed test:** H₀: μ ≤ μ* vs Hₐ: μ > μ*\n- **Lower-tailed test:** H₀: μ ≥ μ* vs Hₐ: μ < μ*\n\n**Key difference from two-sided tests:**\n\n- Rejection region is only in **one tail** of the distribution\n- p-value calculation uses one tail instead of two\n- For upper-tailed: p-value = Pr[T ≥ t]\n- For lower-tailed: p-value = Pr[T ≤ t]\n\n**Example:** Test whether mean earnings **exceed** \\$40,000.\n\n- Claim to be tested: μ > 40,000 (set as Hₐ)\n- Test: H₀: μ ≤ 40,000 vs Hₐ: μ > 40,000\n\n> **Key Concept 4.8: One-Sided Tests**\n>\n> One-sided tests concentrate the rejection region in ONE tail of the distribution, making them more powerful for detecting effects in the specified direction. Use when theory predicts a specific direction. The p-value for a one-sided test is exactly half the two-sided p-value (when the effect is in the predicted direction). Critical values are smaller for one-sided tests (e.g., 1.65 vs ±1.96 for α=0.05).\n\n::: {#ef3e0e32 .cell execution_count=11}\n``` {.python .cell-code}\n# One-sided (upper-tailed) test: H0: μ ≤ $40,000 vs Ha: μ > $40,000\nmu0 = 40000\nt_stat = (mean_earnings - mu0) / se_earnings\np_value_upper = 1 - stats.t.cdf(t_stat, n - 1)  # Upper tail only\nt_crit_upper = stats.t.ppf(0.95, n - 1)  # 0.95 for one-sided test\n\n# One-sided hypothesis test (upper-tailed)\nprint(f\"H₀: μ ≤ ${mu0:,}\")\nprint(f\"Hₐ: μ > ${mu0:,} (the claim we're testing)\")\nprint(f\"Significance level α = 0.05\")\nprint(\"\\nTest Results:\")\nprint(f\"  t-statistic:       {t_stat:.4f}\")\nprint(f\"  p-value (upper):   {p_value_upper:.4f}\")\nprint(f\"  Critical value:    {t_crit_upper:.4f}\")\nprint(\"\\nDecision:\")\nprint(f\"  p-value approach:  {p_value_upper:.4f} > 0.05 → Do not reject H₀\")\nprint(f\"  Critical approach: {t_stat:.4f} < {t_crit_upper:.4f} → Do not reject H₀\")\nprint(\"\\nConclusion: We do not have sufficient evidence to support the claim\")\nprint(f\"that mean earnings exceed ${mu0:,}.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nH₀: μ ≤ $40,000\nHₐ: μ > $40,000 (the claim we're testing)\nSignificance level α = 0.05\n\nTest Results:\n  t-statistic:       0.7237\n  p-value (upper):   0.2351\n  Critical value:    1.6539\n\nDecision:\n  p-value approach:  0.2351 > 0.05 → Do not reject H₀\n  Critical approach: 0.7237 < 1.6539 → Do not reject H₀\n\nConclusion: We do not have sufficient evidence to support the claim\nthat mean earnings exceed $40,000.\n```\n:::\n:::\n\n\n### Visualizing One-Sided Test\n\n::: {#82336c53 .cell execution_count=12}\n``` {.python .cell-code}\n# Visualize one-sided hypothesis test\nfig, ax = plt.subplots(figsize=(12, 6))\n\nx = np.linspace(-4, 4, 500)\ny = stats.t.pdf(x, n - 1)\n\n# Plot the t-distribution\nax.plot(x, y, '-', color='#c084fc', linewidth=2, label=f't({n-1}) distribution')\n\n# Mark the observed t-statistic\nax.axvline(x=t_stat, color='red', linewidth=2, linestyle='--',\n           label=f'Observed t = {t_stat:.2f}')\n\n# Mark critical value (upper tail only)\nax.axvline(x=t_crit_upper, color='green', linewidth=1.5, linestyle=':',\n           label=f'Critical value = {t_crit_upper:.2f}')\n\n# Shade rejection region (upper tail only)\nx_reject = x[x > t_crit_upper]\nax.fill_between(x_reject, 0, stats.t.pdf(x_reject, n-1),\n                alpha=0.3, color='red', label='Rejection region (α = 0.05)')\n\nax.set_xlabel('t-statistic', fontsize=12)\nax.set_ylabel('Density', fontsize=12)\nax.set_title('One-Sided Hypothesis Test (Upper-tailed) Visualization',\n             fontsize=14, fontweight='bold')\nax.legend(fontsize=9, loc='upper left')\nax.grid(True, alpha=0.3)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch04_Statistical_Inference_for_the_Mean_files/figure-html/cell-13-output-1.png){width=1142 height=565}\n:::\n:::\n\n\nFor an upper-tailed test, we only reject H0 if t is large and positive. Our t-statistic is below the critical value, so we do not reject.\n\n**One-Sided Test Results: H₀: μ ≤ \\$40,000 vs Hₐ: μ > \\$40,000**\n\n- t-statistic: 0.7237 (same as two-sided test)\n- p-value (one-sided): 0.2351\n- p-value (two-sided): 0.4703\n- Critical value (one-sided, α=0.05): 1.6539\n- Decision: Do NOT reject H₀\n\n**Key differences from two-sided test:**\n\n1. **p-value is exactly half:**\n   - Two-sided p-value: 0.4703\n   - One-sided p-value: 0.2351 = 0.4703/2\n   - Why? We only count probability in ONE tail (upper tail)\n\n2. **Critical value is smaller:**\n   - Two-sided critical value: ±1.9740 (5% split across two tails)\n   - One-sided critical value: 1.6539 (5% all in one tail)\n   - One-sided tests reject H₀ more easily in the specified direction\n\n3. **Directional claim:**\n   - Two-sided: \"μ is different from \\$40,000\" (could be higher OR lower)\n   - One-sided: \"μ exceeds \\$40,000\" (specifically higher)\n\n**When to use one-sided tests?**\n\nUse one-sided tests when:\n\n- Theory or prior research specifies a direction\n- Example: Testing if a new drug is better (not just different) than placebo\n- Example: Testing if a policy increases (not just changes) income\n\n**When NOT to use one-sided tests:**\n\nAvoid one-sided tests when:\n\n- You're genuinely interested in detecting differences in either direction\n- You might want to detect unexpected effects\n- The field convention is two-sided (economics typically uses two-sided)\n\n**Warning about one-sided test abuse:**\n\nResearchers sometimes use one-sided tests to get \"significant\" results when two-sided tests fail. This is questionable practice:\n\n- If p (two-sided) = 0.08 → not significant at α = 0.05\n- If p (one-sided) = 0.04 → significant at α = 0.05\n- Switching to one-sided AFTER seeing the data is \"p-hacking\"\n- The choice between one-sided and two-sided should be made BEFORE collecting data\n\n**In our example:**\n\n- Sample mean (\\$41,413) is above \\$40,000, consistent with Hₐ: μ > \\$40,000\n- But p-value (0.2351) > 0.05, so still not significant\n- The effect is too small relative to sampling variability\n- We cannot conclude that mean earnings exceed \\$40,000\n\n**Power consideration:**\n\nOne advantage of one-sided tests: greater statistical power in the specified direction\n\n- If you're only interested in detecting μ > \\$40,000, the one-sided test is more powerful\n- Trade-off: Cannot detect effects in the opposite direction\n\n## 4.7 Proportions Data\n\nThe methods extend naturally to **proportions** (binary data).\n\n**Example:** Survey data where respondents answer yes (1) or no (0).- Sample proportion: $\\hat{p} = \\bar{x}$ = fraction of \"yes\" responses- Standard error: se($\\hat{p}$) = √[$\\hat{p}$(1 - $\\hat{p}$)/n]\n\n**Confidence interval for population proportion p:**$$\\hat{p} \\pm z_{\\alpha/2} \\times \\sqrt{\\frac{\\hat{p}(1-\\hat{p})}{n}}$$**Note:** For proportions with large n, we use the **normal distribution** (z) instead of t. **Example:** In a sample of 921 voters, 480 intend to vote Democrat. Is this different from 50%?\n\n::: {#4b546e90 .cell execution_count=13}\n``` {.python .cell-code}\n# Proportions example\nn_total = 921\nn_success = 480\np_hat = n_success / n_total\nse_prop = np.sqrt(p_hat * (1 - p_hat) / n_total)\n\n# 95% Confidence interval\nz_crit = 1.96  # z-critical for 95% CI\nci_lower_prop = p_hat - z_crit * se_prop\nci_upper_prop = p_hat + z_crit * se_prop\n\n# Inference for proportions\nprint(f\"Sample size:           {n_total}\")\nprint(f\"Number voting Democrat: {n_success}\")\nprint(f\"Sample proportion:     {p_hat:.4f} ({p_hat*100:.2f}%)\")\nprint(f\"Standard error:        {se_prop:.4f}\")\nprint(f\"95% CI:                [{ci_lower_prop:.4f}, {ci_upper_prop:.4f}]\")\nprint(f\"                        [{ci_lower_prop*100:.2f}%, {ci_upper_prop*100:.2f}%]\")\n\n# Hypothesis test: H0: p = 0.50\np0 = 0.50\nse_under_h0 = np.sqrt(p0 * (1 - p0) / n_total)\nz_stat = (p_hat - p0) / se_under_h0\np_value_prop = 2 * (1 - stats.norm.cdf(abs(z_stat)))\n\nprint(f\"\\nHypothesis Test: H₀: p = {p0:.2f} (50-50 split)\")\nprint(f\"  z-statistic:       {z_stat:.4f}\")\nprint(f\"  p-value:           {p_value_prop:.4f}\")\nprint(f\"  Decision:          {'Reject H₀' if abs(z_stat) > 1.96 else 'Do not reject H₀'}\")\nprint(f\"\\nConclusion: The proportion is {'significantly' if abs(z_stat) > 1.96 else 'NOT significantly'} different from 50%.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSample size:           921\nNumber voting Democrat: 480\nSample proportion:     0.5212 (52.12%)\nStandard error:        0.0165\n95% CI:                [0.4889, 0.5534]\n                        [48.89%, 55.34%]\n\nHypothesis Test: H₀: p = 0.50 (50-50 split)\n  z-statistic:       1.2851\n  p-value:           0.1988\n  Decision:          Do not reject H₀\n\nConclusion: The proportion is NOT significantly different from 50%.\n```\n:::\n:::\n\n\n**Proportion Results: 480 out of 921 voters intend to vote Democrat**\n\n- Sample proportion: p̂ = 0.5212 (52.12%)\n- Standard error: 0.0165\n- 95% CI: [0.4889, 0.5534] or [48.89%, 55.34%]\n- z-statistic (testing H₀: p = 0.50): 1.2851\n- p-value: 0.1988\n- Decision: Do NOT reject H₀\n\n**What this tells us:**\n\nWe have a sample where 52.12% intend to vote Democrat. The question is: does this provide evidence that the population proportion differs from 50% (a tied race)?\n\n**Understanding the confidence interval:**\n\nThe 95% CI [48.89%, 55.34%] suggests:\n\n- We're 95% confident the true population proportion is in this range\n- The interval INCLUDES 50%, indicating 50-50 is plausible\n- The interval is fairly wide (6.45 percentage points), indicating some uncertainty\n\n**Understanding the hypothesis test:**\n\nTesting H₀: p = 0.50 (tied race) vs Hₐ: p ≠ 0.50 (one candidate ahead)\n\n- z-statistic: 1.29 (only 1.29 standard errors above 50%)\n- p-value: 0.1988 (about 20% chance of seeing this result if truly 50-50)\n- Conclusion: We cannot reject the null hypothesis of a tied race\n\n**Why use z-statistic (normal) instead of t-statistic?**\n\nFor proportions with large samples (n = 921):\n\n- The sampling distribution of p̂ is approximately normal\n- We know the exact standard error formula: √[p̂(1-p̂)/n]\n- No need to estimate anything with t-distribution\n- Rule of thumb: Use normal approximation when np ≥ 10 and n(1-p) ≥ 10\n- Here: 921(0.52) = 479 and 921(0.48) = 442, both >> 10 \n\n**Practical interpretation for election forecasting:**\n\nThis sample shows 52% support for Democrats, but:\n\n- This is NOT statistically significant evidence of a Democratic lead (p = 0.20)\n- The confidence interval includes 50%, so the race could be tied\n- Margin of error: ±3.2 percentage points (1.96 × 0.0165 = 0.032)\n- To call the race, we'd want the CI to exclude 50% entirely\n\n**How would a larger sample change things?**\n\nIf we had the same proportion (52%) but with 2,500 voters instead of 921:\n\n- Standard error would shrink: √[0.52(0.48)/2500] = 0.010\n- 95% CI would be narrower: [50.0%, 54.0%]\n- z-statistic would be larger: (0.52 - 0.50)/0.010 = 2.00\n- p-value would be smaller: 0.045 < 0.05 → significant!\n- Conclusion: Same proportion, but with more data, we could detect the difference\n\n**Key insight about proportions:**\n\nProportions are just means of binary (0/1) data:\n\n- Each voter is coded as 1 (Democrat) or 0 (not Democrat)\n- Sample proportion = sample mean of these 0/1 values\n- All inference principles (SE, CI, hypothesis tests) apply identically\n\n> **Key Concept 4.9: Inference for Proportions**\n>\n> Proportions data (like employment rates, approval ratings, or market shares) are binary variables coded as 0 or 1. All inference methods for means—confidence intervals, hypothesis tests, standard errors—extend naturally to proportions. The sample proportion $\\bar{p}$ is simply the sample mean of binary data, and the standard error formula $se(\\bar{p}) = \\sqrt{\\bar{p}(1-\\bar{p})/n}$ follows from the variance formula for binary variables.\n\n## Key Takeaways\n\n### Core Concepts\n\n1. **Statistical inference** lets us extrapolate from sample statistics to population parameters with quantified uncertainty.\n\n2. **Standard error** $\\text{se}(\\bar{x}) = \\frac{s}{\\sqrt{n}}$ measures the precision of the sample mean as an estimate of the population mean.\n\n3. **t-distribution** is used (instead of normal) when we estimate the population standard deviation from the sample\n - Fatter tails than normal (accounts for extra uncertainty)\n - Converges to normal as $n$ increases\n\n4. **Confidence intervals** provide a range of plausible values\n - Formula: estimate $\\pm$ critical value $\\times$ standard error\n - 95% CI: $\\bar{x} \\pm t_{n-1, 0.025} \\times \\text{se}(\\bar{x}) \\approx \\bar{x} \\pm 2 \\times \\text{se}(\\bar{x})$\n - Interpretation: \"We are 95% confident $\\mu$ lies in this interval\"\n\n5. **Hypothesis tests** evaluate specific claims about parameters\n - Set up $H_0$ (null) and $H_a$ (alternative)\n - Calculate $t\\text{-statistic} = \\frac{\\text{estimate} - \\text{hypothesized value}}{\\text{standard error}}$\n - Make decision using p-value or critical value approach\n\n6. **Two-sided tests** ($H_0: \\mu = \\mu^*$ vs $H_a: \\mu \\neq \\mu^*$)\n - Rejection region in both tails\n - $\\text{p-value} = 2 \\times \\Pr[T \\geq |t|]$\n\n7. **One-sided tests** ($H_0: \\mu \\leq \\mu^*$ vs $H_a: \\mu > \\mu^*$, or vice versa)\n - Rejection region in one tail only\n - Use when testing a directional claim\n\n8. **p-value interpretation**\n - Probability of observing data at least as extreme as ours, assuming $H_0$ is true\n - Small p-value ($< \\alpha$) → reject $H_0$\n - Common significance level: $\\alpha = 0.05$\n\n9. **Methods generalize** to other parameters (regression coefficients, differences in means, etc.) and proportions data\n\n### What You Learned\n\n**Statistical Concepts Covered:**\n\n- Standard error and sampling distribution\n- t-distribution vs normal distribution\n- Confidence intervals (90%, 95%, 99%)\n- Hypothesis testing (two-sided and one-sided)\n- p-values and critical values\n- Type I error and significance level\n- Inference for proportions\n\n**Python Tools Used:**\n\n- `scipy.stats.t`: t-distribution (pdf, cdf, ppf)\n- `scipy.stats.norm`: Normal distribution (for proportions)\n- `pandas`: Data manipulation\n- `matplotlib`: Visualization of hypothesis tests\n\n### Next Steps\n\n- **Chapter 5:** Bivariate data summary (relationships between two variables)\n- **Chapter 6:** Least squares estimator (regression foundation)\n- **Chapter 7:** Inference for regression coefficients\n\n\n### Congratulations! \n\nYou now understand the foundations of statistical inference:\n\n- How to quantify uncertainty using confidence intervals\n- How to test claims about population parameters\n- The difference between statistical and practical significance\n- When to use one-sided vs two-sided tests\n\nThese tools are fundamental to all empirical research in economics and beyond!\n\n> **Common Mistakes to Avoid**\n>\n> - **Misinterpreting p-values**: A p-value is NOT the probability that H₀ is true\n> - **Confusing statistical significance with practical importance**: A tiny effect can be \"significant\" with a large sample\n> - **Using a one-sided test when a two-sided test is appropriate**: One-sided tests require strong prior justification\n\n## Practice Exercises\n\nTest your understanding of statistical inference:\n\n### Exercise 1: Confidence Interval Interpretation\n\nA 95% CI for mean household income is [$48,000, $56,000]\n\n(a) What is the point estimate (sample mean)?\n\n(b) What is the margin of error?\n\n(c) TRUE or FALSE: \"There is a 95% probability that the true mean is in this interval\"\n\n(d) TRUE or FALSE: \"If we repeated sampling, 95% of CIs would contain the true mean\"\n\n### Exercise 2: Standard Error Calculation\n\nSample of $n=64$ observations with mean $\\$45,000$ and standard deviation $s=\\$16,000$\n\n(a) Calculate the standard error\n\n(b) What sample size would halve the standard error?\n\n(c) Construct an approximate 95% CI using the \"mean $\\pm$ 2SE\" rule\n\n### Exercise 3: t vs z Distribution\n\n(a) Why do we use the t-distribution instead of the normal distribution?\n\n(b) For $n=10$, find the critical value for a 95% CI\n\n(c) For $n=100$, find the critical value for a 95% CI\n\n(d) Compare these to $z=1.96$. What do you notice?\n\n### Exercise 4: Hypothesis Test Mechanics\n\nTest $H_0: \\mu = 100$ vs $H_a: \\mu \\neq 100$ with sample mean $= 105$, SE $= 3$, $n = 49$\n\n(a) Calculate the t-statistic\n\n(b) Find the p-value (use t-table or Python)\n\n(c) Make a decision at $\\alpha=0.05$\n\n(d) Would your decision change if $\\alpha=0.01$?\n\n### Exercise 5: One-Sided vs Two-Sided Tests\n\nSample: $n=36$, mean $=72$, $s=18$\n\n(a) Test $H_0: \\mu = 75$ vs $H_a: \\mu \\neq 75$ (two-sided, $\\alpha=0.05$)\n\n(b) Test $H_0: \\mu \\geq 75$ vs $H_a: \\mu < 75$ (one-sided, $\\alpha=0.05$)\n\n(c) Compare the p-values. What is the relationship?\n\n(d) In which case is the evidence against $H_0$ stronger?\n\n### Exercise 6: Type I and Type II Errors\n\n(a) Define Type I error and give an example in the earnings context\n\n(b) Define Type II error and give an example\n\n(c) If we decrease $\\alpha$ from 0.05 to 0.01, what happens to the probability of Type II error?\n\n(d) How can we reduce both types of error simultaneously?\n\n### Exercise 7: Proportions Inference\n\nSurvey of 500 people: 275 support a policy\n\n(a) Calculate the sample proportion and standard error\n\n(b) Construct a 95% CI for the population proportion\n\n(c) Test $H_0: p = 0.50$ vs $H_a: p \\neq 0.50$\n\n(d) Is the result statistically significant?\n\n### Exercise 8: Python Practice\n\nGenerate a random sample of 100 observations from $N(50, 100)$\n\n(a) Calculate the 95% CI for the mean\n\n(b) Does the CI contain the true mean (50)?\n\n(c) Repeat 1000 times. What fraction of CIs contain 50?\n\n(d) Test $H_0: \\mu = 55$. What proportion of tests reject (should be $\\approx 0.05$)?\n\n---\n\n## Case Studies\n\n### Case Study 1: Statistical Inference for Labor Productivity\n\n**Research Question:** \"Has global labor productivity changed significantly over time, and do productivity levels differ significantly across regions?\"\n\nThis case study applies all the statistical inference methods from Chapter 4 to analyze real economic data on labor productivity across 108 countries over 25 years (1990-2014). You'll practice:\n\n- Constructing and interpreting **confidence intervals** for population means\n- Conducting **two-sided hypothesis tests** to compare time periods\n- Performing **one-sided directional tests** for benchmark comparisons\n- Applying **proportions inference** to binary economic outcomes\n- Comparing productivity levels across **regional subgroups**\n- Interpreting results in economic context (development economics, convergence theory)\n\nThe Mendez convergence clubs dataset provides panel data on labor productivity, GDP, capital, human capital, and total factor productivity for 108 countries from 1990 to 2014.\n\n#### Economic Context: Testing Convergence Hypotheses\n\nIn development economics, the **convergence hypothesis** suggests that poorer countries should grow faster than richer ones, leading to a narrowing of productivity gaps over time. Statistical inference allows us to test whether observed changes in productivity are:\n\n- **Statistically significant** (unlikely due to random sampling variation)\n- **Economically meaningful** (large enough to matter for policy)\n\nBy applying Chapter 4's methods to this dataset, you'll answer questions like:\n\n1. Has mean global productivity increased significantly from 1990 to 2014?\n2. Are regional productivity gaps (e.g., Africa vs. Europe) statistically significant?\n3. What proportion of countries experienced positive productivity growth?\n4. Can we reject specific hypotheses about productivity benchmarks?\n\nThese are real questions that economists and policymakers care about when designing development strategies.\n\n> **Key Concept 4.10: Why Statistical Inference Matters in Economics**\n>\n> When analyzing economic data, we rarely observe entire populations. Instead, we work with **samples** (like 108 countries from all countries in the world, or 25 years from a longer historical period). Statistical inference lets us:\n>\n> 1. **Quantify uncertainty** - Confidence intervals tell us the range of plausible values for population parameters\n> 2. **Test theories** - Hypothesis tests evaluate whether data support or contradict economic theories\n> 3. **Compare groups** - We can determine if differences between regions/periods are real or just noise\n> 4. **Inform policy** - Statistical significance helps separate meaningful patterns from random fluctuations\n>\n> Without inference methods, we couldn't distinguish between:\n> - A real productivity increase vs. random year-to-year variation\n> - Genuine regional gaps vs. sampling artifacts\n> - Policy-relevant changes vs. statistical noise\n\n::: {#dd0aea52 .cell execution_count=14}\n``` {.python .cell-code}\n# Load convergence clubs dataset\nurl = \"https://raw.githubusercontent.com/quarcs-lab/mendez2020-convergence-clubs-code-data/master/assets/dat.csv\"\ndf = pd.read_csv(url)\n\n# Set multi-index (country, year)\ndf = df.set_index(['country', 'year'])\n\n# Display dataset information\nprint(\"Dataset Overview:\")\nprint(f\"Total observations: {len(df):,}\")\nprint(f\"Countries: {df.index.get_level_values('country').nunique()}\")\nprint(f\"Years: {df.index.get_level_values('year').min()}-{df.index.get_level_values('year').max()}\")\nprint(f\"\\nVariables: {list(df.columns)}\")\n\n# Extract labor productivity for key years\nlp_1990 = df.loc[df.index.get_level_values('year') == 1990, 'lp']\nlp_2014 = df.loc[df.index.get_level_values('year') == 2014, 'lp']\n\nprint(f\"\\nLabor productivity samples:\")\nprint(f\"1990: n={len(lp_1990)}, mean=${lp_1990.mean()/1000:.1f}k, std=${lp_1990.std()/1000:.1f}k\")\nprint(f\"2014: n={len(lp_2014)}, mean=${lp_2014.mean()/1000:.1f}k, std=${lp_2014.std()/1000:.1f}k\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDataset Overview:\nTotal observations: 2,700\nCountries: 108\nYears: 1990-2014\n\nVariables: ['id', 'Y', 'K', 'pop', 'L', 's', 'alpha_it', 'GDPpc', 'lp', 'h', 'kl', 'kp', 'ky', 'TFP', 'log_GDPpc_raw', 'log_lp_raw', 'log_ky_raw', 'log_h_raw', 'log_tfp_raw', 'log_GDPpc', 'log_lp', 'log_ky', 'log_h', 'log_tfp', 'isocode', 'hi1990', 'region']\n\nLabor productivity samples:\n1990: n=108, mean=$23.2k, std=$20.1k\n2014: n=108, mean=$41.0k, std=$33.9k\n```\n:::\n:::\n\n\n#### How to Use These Tasks\n\n**Task structure:** The 6 tasks below progress from **guided** (fill-in-the-blank code) to **independent** (design your own analysis).\n\n**Working approach:**\n\n1. **Read the task description** - Understand the economic question and learning goal\n2. **Study the code template** - Early tasks provide partial code with blanks (`_____`)\n3. **Insert a new code cell** below each task\n4. **Complete the code** - Fill in blanks or write from scratch (depending on task level)\n5. **Run and interpret** - Execute your code and interpret results economically\n6. **Check your understanding** - Does your answer make economic sense?\n\n**Tips:**\n\n- Reference Section 4.1-4.7 for formulas and methods\n- Use `scipy.stats` functions: `t.ppf()`, `ttest_ind()`, `ttest_1samp()`\n- Always interpret p-values: \"We reject/fail to reject H₀ at α=0.05 because...\"\n- Connect statistical results to economic meaning: \"This suggests that...\"\n\n**Progressive difficulty:**\n\n- **Tasks 1-2:** Guided (fill 4-8 blanks in provided code)\n- **Tasks 3-4:** Semi-guided (complete partial structure)\n- **Tasks 5-6:** Independent (design full implementation)\n\n#### Task 1: Confidence Intervals for Mean Productivity (Guided)\n\n**Learning Goal:** Apply Section 4.3 methods to calculate and interpret confidence intervals\n\n**Economic Question:** \"Can we be 95% confident about the range of global mean labor productivity in 2014?\"\n\n**Your task:**\n\n1. Calculate a 95% confidence interval for mean productivity in 2014\n2. Calculate a 99% confidence interval for comparison\n3. Interpret the difference in interval widths\n4. Compare with a 95% CI for 1990 data\n\n**Code template (fill in the 6 blanks):**\n\n```python\nfrom scipy import stats\n\n# 2014 data: Calculate 95% CI\nn_2014 = len(lp_2014)\nmean_2014 = _____  # Calculate sample mean\nstd_2014 = _____   # Calculate sample standard deviation\nse_2014 = std_2014 / np.sqrt(n_2014)\n\n# Get t-critical value for 95% CI (two-tailed, df = n-1)\nalpha_95 = 0.05\nt_crit_95 = stats.t.ppf(1 - alpha_95/2, df=_____)\n\n# Calculate margin of error and CI bounds\nme_95 = t_crit_95 * se_2014\nci_95_lower = _____\nci_95_upper = _____\n\nprint(f\"2014 Labor Productivity:\")\nprint(f\"Sample mean: ${mean_2014:,.0f}\")\nprint(f\"95% CI: [${ci_95_lower:,.0f}, ${ci_95_upper:,.0f}]\")\nprint(f\"Margin of error: ${me_95:,.0f}\")\n\n# Calculate 99% CI for comparison\nalpha_99 = 0.01\nt_crit_99 = stats.t.ppf(1 - alpha_99/2, df=n_2014-1)\nme_99 = t_crit_99 * se_2014\nci_99_lower = mean_2014 - me_99\nci_99_upper = mean_2014 + me_99\n\nprint(f\"\\n99% CI: [${ci_99_lower:,.0f}, ${ci_99_upper:,.0f}]\")\nprint(f\"Margin of error: ${me_99:,.0f}\")\nprint(f\"\\nInterpretation: The 99% CI is _____ than the 95% CI\")  # Fill in: \"wider\" or \"narrower\"\nprint(f\"because we need more certainty, which requires a larger interval.\")\n\n# Compare with 1990\nmean_1990 = lp_1990.mean()\nstd_1990 = lp_1990.std()\nse_1990 = std_1990 / np.sqrt(len(lp_1990))\nme_1990 = stats.t.ppf(0.975, df=len(lp_1990)-1) * se_1990\n\nprint(f\"\\n1990 mean: ${mean_1990:,.0f}, 95% CI width: ${2*me_1990:,.0f}\")\nprint(f\"2014 mean: ${mean_2014:,.0f}, 95% CI width: ${2*me_95:,.0f}\")\n```\n\n**Questions to consider:**\n\n- Why is the 99% CI wider than the 95% CI?\n- Did the mean productivity increase from 1990 to 2014?\n- Which year has more variability in productivity across countries?\n\n#### Task 2: Testing Productivity Change Over Time (Semi-guided)\n\n**Learning Goal:** Apply Section 4.4 (two-sided tests) to compare time periods\n\n**Economic Question:** \"Has global mean labor productivity changed significantly from 1990 to 2014?\"\n\n**Your task:**\n\n1. State null and alternative hypotheses\n2. Conduct a two-sample t-test (independent samples)\n3. Calculate the test statistic manually\n4. Compare with `scipy.stats.ttest_ind()` result\n5. Interpret the p-value at α = 0.05\n\n**Code template (fill in the 8 blanks):**\n\n```python\n# State hypotheses\nprint(\"H₀: μ₁₉₉₀ = μ₂₀₁₄  (no change in mean productivity)\")\nprint(\"Hₐ: μ₁₉₉₀ ≠ μ₂₀₁₄  (mean productivity changed)\")\nprint(f\"Significance level: α = 0.05\\n\")\n\n# Manual calculation\nmean_1990 = lp_1990.mean()\nmean_2014 = lp_2014.mean()\nse_1990 = lp_1990.std() / np.sqrt(len(lp_1990))\nse_2014 = lp_2014.std() / np.sqrt(len(lp_2014))\n\n# Calculate pooled standard error for difference in means\nse_diff = np.sqrt(_____**2 + _____**2)  # Fill in: se_1990 and se_2014\n\n# Calculate t-statistic\nt_stat = (_____ - _____) / se_diff  # Fill in: mean_2014 and mean_1990\n\n# Degrees of freedom (Welch approximation)\nn1, n2 = len(lp_1990), len(lp_2014)\ns1, s2 = lp_1990.std(), lp_2014.std()\ndf = ((s1**2/n1 + s2**2/n2)**2) / ((s1**2/n1)**2/(n1-1) + (s2**2/n2)**2/(n2-1))\n\n# Calculate two-sided p-value\np_value_manual = 2 * (1 - stats.t.cdf(abs(t_stat), df=df))\n\nprint(f\"Manual calculation:\")\nprint(f\"Difference in means: ${mean_2014 - mean_1990:,.0f}\")\nprint(f\"SE of difference: ${se_diff:,.0f}\")\nprint(f\"t-statistic: {t_stat:.3f}\")\nprint(f\"Degrees of freedom: {df:.1f}\")\nprint(f\"p-value (two-sided): {p_value_manual:.4f}\\n\")\n\n# Verify with scipy\nt_stat_scipy, p_value_scipy = stats.ttest_ind(_____, _____, equal_var=False)  # Fill in: lp_2014, lp_1990\nprint(f\"scipy.stats.ttest_ind() result:\")\nprint(f\"t-statistic: {t_stat_scipy:.3f}\")\nprint(f\"p-value: {p_value_scipy:.4f}\\n\")\n\n# Decision\nif p_value_scipy < 0.05:\n    print(f\"Decision: _____ H₀ at α=0.05\")  # Fill in: \"Reject\" or \"Fail to reject\"\n    print(f\"Interpretation: Mean productivity _____ significantly from 1990 to 2014.\")  # Fill in: \"changed\" or \"did not change\"\nelse:\n    print(f\"Decision: Fail to reject H₀ at α=0.05\")\n    print(f\"Interpretation: Insufficient evidence that mean productivity changed.\")\n```\n\n**Questions to consider:**\n\n- What does the p-value tell you about the likelihood of observing this difference by chance?\n- Is the change economically meaningful (not just statistically significant)?\n- What assumptions does the two-sample t-test make?\n\n#### Task 3: Comparing Regional Productivity Levels (Semi-guided)\n\n**Learning Goal:** Apply hypothesis testing to compare subgroups\n\n**Economic Question:** \"Do African countries have significantly lower productivity than European countries (2014 data)?\"\n\n**Your task:**\n\n1. Filter 2014 data by region (use `region` column in dataset)\n2. Test H₀: μ_Africa = μ_Europe vs Hₐ: μ_Africa ≠ μ_Europe\n3. Calculate 95% CI for the difference in means\n4. Visualize distributions with side-by-side box plots\n\n**Code structure (complete the analysis):**\n\n```python\n# Filter 2014 data by region\ndf_2014 = df.loc[df.index.get_level_values('year') == 2014]\n\n# Extract productivity for Africa and Europe\nlp_africa = df_2014.loc[df_2014['region'] == 'Africa', 'lp']\nlp_europe = df_2014.loc[df_2014['region'] == 'Europe', 'lp']\n\nprint(f\"Sample sizes: Africa n={len(lp_africa)}, Europe n={len(lp_europe)}\")\nprint(f\"Africa mean: ${lp_africa.mean():,.0f}\")\nprint(f\"Europe mean: ${lp_europe.mean():,.0f}\\n\")\n\n# Conduct two-sample t-test\n# YOUR CODE HERE: Use stats.ttest_ind() to test if means differ\n# Calculate and print: t-statistic, p-value, decision at α=0.05\n\n# Calculate 95% CI for difference in means\n# YOUR CODE HERE: \n# 1. Calculate difference in means\n# 2. Calculate SE of difference\n# 3. Get t-critical value\n# 4. Construct CI: (difference - ME, difference + ME)\n\n# Visualize distributions\nfig, ax = plt.subplots(1, 1, figsize=(8, 5))\nax.boxplot([lp_africa, lp_europe], labels=['Africa', 'Europe'])\nax.set_ylabel('Labor Productivity ($)')\nax.set_title('Labor Productivity Distribution by Region (2014)')\nax.grid(axis='y', alpha=0.3)\nplt.tight_layout()\nplt.show()\n```\n\n**Questions to consider:**\n\n- Is the difference statistically significant?\n- How large is the productivity gap in dollar terms?\n- What does the box plot reveal about within-region variation?\n- Does the CI for the difference include zero? What does that mean?\n\n> **Key Concept 4.11: Economic vs Statistical Significance**\n>\n> A result can be **statistically significant** (p < 0.05) but **economically trivial**, or vice versa:\n>\n> **Statistical significance** answers: \"Is this difference unlikely to be due to chance?\"\n> - Depends on sample size: larger samples detect smaller differences\n> - Measured by p-value: probability of observing this result if H₀ is true\n> - Standard: p < 0.05 means <5% chance of Type I error\n>\n> **Economic significance** answers: \"Is this difference large enough to matter?\"\n> - Depends on context: a \\$1,000 productivity gap might be huge for low-income countries but trivial for high-income countries\n> - Measured by effect size: actual magnitude of the difference\n> - Judgment call: requires domain expertise\n>\n> **Example:**\n> - With n=10,000 countries, a \\$100 productivity difference might be statistically significant (p<0.001) but economically meaningless\n> - With n=10 countries, a \\$10,000 difference might not be statistically significant (p=0.08) but could be economically important\n>\n> **Best practice:** Always report BOTH:\n> 1. Statistical result: \"We reject H₀ at α=0.05 (p=0.003)\"\n> 2. Economic interpretation: \"The \\$15,000 productivity gap represents a 35% difference, which is economically substantial for development policy\"\n\n#### Task 4: One-Sided Test for Growth (More Independent)\n\n**Learning Goal:** Apply Section 4.6 (one-sided tests) to directional hypotheses\n\n**Economic Question:** \"Can we conclude that mean global productivity in 2014 exceeds \\$50,000 (a policy benchmark)?\"\n\n**Your task:**\n\n1. Test H₀: μ ≤ 50,000 vs Hₐ: μ > 50,000\n2. Use `scipy.stats.ttest_1samp()` with `alternative='greater'`\n3. Compare one-sided vs two-sided p-values\n4. Discuss Type I error: what does α=0.05 mean in this context?\n\n**Outline (write your own code):**\n\n```python\n# Step 1: State hypotheses clearly\n# H₀: μ ≤ 50,000 (productivity does not exceed benchmark)\n# Hₐ: μ > 50,000 (productivity exceeds benchmark)\n\n# Step 2: Conduct one-sided t-test\n# Use: stats.ttest_1samp(lp_2014, popmean=50000, alternative='greater')\n\n# Step 3: Calculate two-sided p-value for comparison\n# Use: stats.ttest_1samp(lp_2014, popmean=50000, alternative='two-sided')\n\n# Step 4: Report results\n# - Sample mean\n# - t-statistic\n# - One-sided p-value\n# - Two-sided p-value\n# - Decision at α=0.05\n\n# Step 5: Interpret Type I error\n# If we reject H₀, what is the probability we made a mistake?\n```\n\n**Hint:** Remember that for one-sided tests:\n\n- If Hₐ: μ > μ₀, use `alternative='greater'`\n- The one-sided p-value is half the two-sided p-value (when t-stat has correct sign)\n- Type I error = rejecting H₀ when it's actually true\n\n**Questions to consider:**\n\n- Why is the one-sided p-value smaller than the two-sided p-value?\n- When is a one-sided test appropriate vs a two-sided test?\n- What are the policy implications if we reject H₀?\n\n#### Task 5: Proportions Analysis - Growth Winners (Independent)\n\n**Learning Goal:** Apply Section 4.7 (proportions) to binary outcomes\n\n**Economic Question:** \"What proportion of countries experienced productivity growth from 1990 to 2014, and can we conclude that more than half experienced growth?\"\n\n**Your task:**\n\n1. Create country-level dataset with productivity in both 1990 and 2014\n2. Create binary variable: `growth = 1` if productivity increased, `0` otherwise\n3. Calculate sample proportion of \"growth winners\"\n4. Construct 95% CI for population proportion using normal approximation\n5. Test H₀: p = 0.50 vs Hₐ: p ≠ 0.50 (are half growth winners?)\n\n**Hints:**\n\n```python\n# Hint 1: Reshape data to country-level\n# df_1990 = df.loc[df.index.get_level_values('year') == 1990, ['lp']]\n# df_2014 = df.loc[df.index.get_level_values('year') == 2014, ['lp']]\n# Merge on country index\n\n# Hint 2: Create binary growth indicator\n# growth = (lp_2014 > lp_1990).astype(int)\n\n# Hint 3: Proportions formulas from Section 4.7\n# p_hat = np.mean(growth)\n# se_p = np.sqrt(p_hat * (1 - p_hat) / n)\n# CI: p_hat ± z_crit * se_p\n# For 95% CI: z_crit = 1.96\n\n# Hint 4: Test statistic for proportions\n# z = (p_hat - p0) / np.sqrt(p0 * (1 - p0) / n)\n# where p0 = 0.50 under H₀\n```\n\n**Questions to consider:**\n\n- What proportion of countries experienced growth?\n- Does the 95% CI include 0.50? What does that mean?\n- Is there evidence that the proportion differs from 50%?\n- Which countries did NOT experience growth? (Bonus: investigate why)\n\n#### Task 6: Multi-Regional Hypothesis Testing (Independent)\n\n**Learning Goal:** Integrate multiple inference methods in comprehensive analysis\n\n**Economic Question:** \"Which regional pairs show statistically significant productivity gaps in 2014?\"\n\n**Your task:**\n\n1. Identify all regions in the dataset (use `df_2014['region'].unique()`)\n2. Calculate 95% CIs for mean productivity in each region\n3. Conduct pairwise t-tests (Africa vs Europe, Africa vs Asia, Africa vs Americas, etc.)\n4. Create a visualization showing CIs for all regions (error bar plot)\n5. Discuss the **multiple testing problem**: when conducting many tests, what happens to Type I error?\n\n**Challenge goals (minimal guidance):**\n\n- Design your own analysis structure\n- Use loops to avoid repetitive code\n- Create professional visualizations\n- Write clear economic interpretations\n\n**Suggested approach:**\n\n```python\n# Step 1: Get all regions and calculate summary stats\n# For each region: mean, std, se, 95% CI\n# Store in a DataFrame or dictionary\n\n# Step 2: Conduct all pairwise tests\n# Use itertools.combinations() to generate pairs\n# For each pair: run ttest_ind(), store t-stat and p-value\n\n# Step 3: Visualize CIs\n# Create error bar plot: plt.errorbar()\n# Or bar plot with CI whiskers\n\n# Step 4: Report significant differences\n# Which pairs have p < 0.05?\n# What is the magnitude of differences?\n\n# Step 5: Discuss multiple testing\n# If you run 10 tests at α=0.05, what's the probability of at least one false positive?\n# Consider Bonferroni correction: α_adjusted = 0.05 / number_of_tests\n```\n\n**Questions to consider:**\n\n- Which region has the highest mean productivity? Lowest?\n- Are all pairwise differences statistically significant?\n- How does the multiple testing problem affect your conclusions?\n- What economic factors might explain regional productivity gaps?\n\n#### What You've Learned\n\nBy completing this case study, you've practiced **all the major skills from Chapter 4**:\n\n**Statistical Methods:**\n\n- Constructed confidence intervals (90%, 95%, 99%) for population means\n- Conducted two-sided hypothesis tests to compare groups and time periods\n- Performed one-sided directional tests for benchmark comparisons\n- Applied proportions inference to binary economic outcomes\n- Calculated and interpreted t-statistics, p-values, and margins of error\n- Used both manual calculations and `scipy.stats` functions\n\n**Economic Applications:**\n\n- Tested convergence hypotheses (did productivity gaps narrow over time?)\n- Compared regional development levels (Africa, Europe, Asia, Americas)\n- Evaluated policy benchmarks (does productivity exceed thresholds?)\n- Identified \"growth winners\" and \"growth losers\" among countries\n- Distinguished between statistical and economic significance\n\n**Programming Skills:**\n\n- Filtered and reshaped panel data (multi-index DataFrames)\n- Implemented statistical tests with `scipy.stats`\n- Created informative visualizations (box plots, error bars)\n- Wrote clear, reproducible analysis code\n\n**Critical Thinking:**\n\n- Formulated null and alternative hypotheses from economic questions\n- Interpreted p-values in context (not just \"significant\" vs \"not significant\")\n- Connected statistical results to economic meaning and policy implications\n- Recognized limitations (Type I/II errors, multiple testing problem)\n\n---\n\n**Next steps:**\n\nThese skills form the foundation for more advanced methods in later chapters:\n\n- **Chapter 5:** Regression analysis (relationship between two variables)\n- **Chapter 6:** Multiple regression (controlling for confounders)\n- **Chapter 7:** Hypothesis tests in regression models\n\nStatistical inference is everywhere in empirical economics. You've now mastered the core toolkit for:\n\n- Quantifying uncertainty\n- Testing economic theories\n- Making data-driven decisions\n- Communicating results with precision\n\n**Well done!**\n\n### Case Study 2: Is Bolivia's Development Equal? Testing Differences Across Departments\n\n**Research Question**: Are there statistically significant differences in development levels across Bolivia's nine departments?\n\nIn Chapter 1, we introduced the DS4Bolivia project and explored satellite-development relationships across Bolivia's 339 municipalities. In this case study, we apply Chapter 4's statistical inference tools—confidence intervals and hypothesis tests—to test whether development levels differ significantly across Bolivia's departments.\n\n**The Data**: Cross-sectional dataset covering 339 Bolivian municipalities from the [DS4Bolivia Project](https://github.com/quarcs-lab/ds4bolivia), including:\n\n- **Development outcomes**: Municipal Sustainable Development Index (IMDS, 0-100 composite)\n- **Satellite data**: Log nighttime lights per capita (2017)\n- **Demographics**: Population (2017), municipality and department names\n\n**Your Task**: Use confidence intervals, one-sample tests, two-sample tests, and one-sided tests to evaluate whether Bolivia's departments differ significantly in development—and whether those differences are large enough to matter for policy.\n\n#### Load the DS4Bolivia Data\n\nLet's load the DS4Bolivia dataset and prepare the key variables for statistical inference.\n\n::: {#d0624020 .cell execution_count=15}\n``` {.python .cell-code}\n# Load the DS4Bolivia dataset\nurl_bol = \"https://raw.githubusercontent.com/quarcs-lab/ds4bolivia/master/ds4bolivia_v20250523.csv\"\nbol = pd.read_csv(url_bol)\n\n# Select key variables for this case study\nkey_vars = ['mun', 'dep', 'imds', 'ln_NTLpc2017', 'pop2017']\nbol_key = bol[key_vars].dropna().copy()\n\n# DS4Bolivia dataset -- statistical inference case study\nprint(f\"Municipalities: {len(bol_key)}\")\nprint(f\"Departments:    {bol_key['dep'].nunique()}\")\nprint(f\"\\nIMDS summary:\")\nprint(bol_key['imds'].describe().round(2))\nprint(f\"\\nMunicipalities per department:\")\nprint(bol_key['dep'].value_counts().sort_index())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMunicipalities: 333\nDepartments:    9\n\nIMDS summary:\ncount    333.00\nmean      51.16\nstd        6.76\nmin       35.70\n25%       47.10\n50%       50.80\n75%       55.00\nmax       80.20\nName: imds, dtype: float64\n\nMunicipalities per department:\ndep\nBeni          18\nChuquisaca    29\nCochabamba    47\nLa Paz        87\nOruro         35\nPando         13\nPotosí        38\nSanta Cruz    55\nTarija        11\nName: count, dtype: int64\n```\n:::\n:::\n\n\n#### Task 1: Confidence Interval for Mean IMDS (Guided)\n\n**Learning Goal**: Apply Section 4.3 methods to calculate and interpret a confidence interval for a population mean.\n\n**Economic Question**: \"What is the true average development level across all Bolivian municipalities?\"\n\n**Instructions**:\n\n1. Calculate the sample mean and standard error of `imds`\n2. Construct a 95% confidence interval using `scipy.stats.t.interval()`\n3. Print the sample mean, standard error, and CI bounds\n4. Interpret the result: \"We are 95% confident that the true mean municipal development index lies between X and Y.\"\n\n**Apply what you learned in Section 4.3**: The formula is $\\bar{x} \\pm t_{\\alpha/2} \\times SE$, where $SE = s/\\sqrt{n}$.\n\n::: {#21f5376f .cell execution_count=16}\n``` {.python .cell-code}\n# Your code here: 95% Confidence Interval for national mean IMDS\nfrom scipy import stats\n\n# Calculate sample statistics\nn = len(bol_key['imds'])\nx_bar = bol_key['imds'].mean()\nse = bol_key['imds'].std() / np.sqrt(n)\n\n# 95% confidence interval using t-distribution\nci_low, ci_high = stats.t.interval(0.95, df=n-1, loc=x_bar, scale=se)\n\n# 95% confidence interval for mean IMDS\nprint(f\"Sample size (n):       {n}\")\nprint(f\"Sample mean:           {x_bar:.4f}\")\nprint(f\"Standard error:        {se:.4f}\")\nprint(f\"95% CI:                [{ci_low:.4f}, {ci_high:.4f}]\")\nprint(f\"\\nInterpretation: We are 95% confident that the true mean\")\nprint(f\"municipal development index lies between {ci_low:.2f} and {ci_high:.2f}.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSample size (n):       333\nSample mean:           51.1580\nStandard error:        0.3704\n95% CI:                [50.4292, 51.8867]\n\nInterpretation: We are 95% confident that the true mean\nmunicipal development index lies between 50.43 and 51.89.\n```\n:::\n:::\n\n\n#### Task 2: Hypothesis Test — National Development Target (Guided)\n\n**Learning Goal**: Apply Section 4.4 (two-sided test) to test a hypothesis about a population mean.\n\n**Economic Question**: \"Is the average municipality at the midpoint of the development scale?\"\n\nA natural benchmark for the IMDS (which ranges from 0 to 100) is the midpoint of 50. If Bolivia's municipalities were, on average, at this midpoint, we would expect $\\mu_{IMDS} = 50$.\n\n**Instructions**:\n\n1. State the hypotheses: $H_0: \\mu = 50$ vs $H_1: \\mu \\neq 50$\n2. Use `scipy.stats.ttest_1samp()` to conduct the test\n3. Report the t-statistic and p-value\n4. State your conclusion at $\\alpha = 0.05$\n5. Discuss: Is the average municipality at the midpoint of the development scale?\n\n::: {#ad2072a1 .cell execution_count=17}\n``` {.python .cell-code}\n# Your code here: One-sample t-test — is mean IMDS = 50?\n\n# Hypothesis test: H0: mu = 50 vs H1: mu != 50\nt_stat, p_value = stats.ttest_1samp(bol_key['imds'], popmean=50)\n\n# Hypothesis test: is mean IMDS = 50?\nprint(f\"H₀: μ = 50  vs  H₁: μ ≠ 50\")\nprint(f\"\\nSample mean:   {bol_key['imds'].mean():.4f}\")\nprint(f\"t-statistic:   {t_stat:.4f}\")\nprint(f\"p-value:       {p_value:.6f}\")\nprint(f\"\\nConclusion at α = 0.05:\")\nif p_value < 0.05:\n    print(f\"  Reject H₀ (p = {p_value:.6f} < 0.05)\")\n    print(f\"  The average IMDS is significantly different from 50.\")\nelse:\n    print(f\"  Fail to reject H₀ (p = {p_value:.6f} ≥ 0.05)\")\n    print(f\"  No significant evidence that mean IMDS differs from 50.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nH₀: μ = 50  vs  H₁: μ ≠ 50\n\nSample mean:   51.1580\nt-statistic:   3.1258\np-value:       0.001929\n\nConclusion at α = 0.05:\n  Reject H₀ (p = 0.001929 < 0.05)\n  The average IMDS is significantly different from 50.\n```\n:::\n:::\n\n\n> **Key Concept 4.12: Statistical Significance in Development**\n>\n> A statistically significant difference between departments does not automatically imply a **policy-relevant** gap. With 339 municipalities providing large sample sizes, even small differences can achieve statistical significance. Policy makers must evaluate the **magnitude** of differences alongside p-values. A 2-point difference in IMDS may be statistically significant but practically negligible for resource allocation decisions.\n\n#### Task 3: Department-Level Inference (Semi-guided)\n\n**Learning Goal**: Apply confidence intervals to compare subgroups.\n\n**Economic Question**: \"Which departments have significantly different development levels from one another?\"\n\n**Instructions**:\n\n1. Calculate the 95% confidence interval for mean `imds` in each of Bolivia's 9 departments\n2. Create a **forest plot** (horizontal error bars) showing the CI for each department\n3. Identify which departments' CIs overlap (suggesting no significant difference) and which don't\n4. Discuss what the pattern reveals about regional inequality\n\n**Hint**: Use `groupby('dep')` to calculate department-level statistics, then `plt.errorbar()` or `plt.barh()` with error bars for the forest plot.\n\n::: {#ba1713fc .cell execution_count=18}\n``` {.python .cell-code}\n# Your code here: Department-level 95% CIs and forest plot\n\n# Calculate department-level statistics\ndept_stats = bol_key.groupby('dep')['imds'].agg(['mean', 'std', 'count']).sort_values('mean')\ndept_stats['se'] = dept_stats['std'] / np.sqrt(dept_stats['count'])\ndept_stats['ci_low'] = dept_stats['mean'] - 1.96 * dept_stats['se']    # z-critical for 95% CI\ndept_stats['ci_high'] = dept_stats['mean'] + 1.96 * dept_stats['se']\n\n# 95% confidence intervals for mean IMDS by department\ndept_stats[['mean', 'se', 'ci_low', 'ci_high', 'count']].round(2)\n\n# Forest plot\nfig, ax = plt.subplots(figsize=(10, 6))\ndepartments = dept_stats.index\ny_pos = range(len(departments))\nax.errorbar(dept_stats['mean'], y_pos,\n            xerr=1.96 * dept_stats['se'],\n            fmt='o', color='#22d3ee', capsize=5, capthick=1.5, markersize=6)\nax.set_yticks(y_pos)\nax.set_yticklabels(departments)\nax.set_xlabel('Mean IMDS (with 95% CI)')\nax.set_title('Forest Plot: Municipal Development by Department')\nax.axvline(x=bol_key['imds'].mean(), color='red', linestyle='--', alpha=0.5, label='National mean')\nax.legend()\nax.grid(axis='x', alpha=0.3)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch04_Statistical_Inference_for_the_Mean_files/figure-html/cell-19-output-1.png){width=950 height=565}\n:::\n:::\n\n\n#### Task 4: One-Sided Test — Is the Capital Department More Developed? (Semi-guided)\n\n**Learning Goal**: Apply Section 4.6 (one-sided tests) to a directional hypothesis.\n\n**Economic Question**: \"Is La Paz department's mean IMDS significantly greater than the national mean?\"\n\n**Instructions**:\n\n1. Extract IMDS values for La Paz department\n2. Test $H_0: \\mu_{LP} \\leq \\mu_{national}$ vs $H_1: \\mu_{LP} > \\mu_{national}$ using a one-sided t-test\n3. Calculate the one-sided p-value (divide the two-sided p-value by 2, checking direction)\n4. Report and interpret the result at $\\alpha = 0.05$\n5. Discuss: Is the capital department significantly more developed?\n\n**Hint**: Use `scipy.stats.ttest_1samp()` with the national mean as the test value, then adjust for a one-sided test.\n\n::: {#ebb9b167 .cell execution_count=19}\n``` {.python .cell-code}\n# Your code here: One-sided t-test for La Paz department\n\n# Extract La Paz IMDS values\nla_paz = bol_key[bol_key['dep'] == 'La Paz']['imds']\nnational_mean = bol_key['imds'].mean()\n\n# Two-sided test first\nt_stat_lp, p_two = stats.ttest_1samp(la_paz, popmean=national_mean)\n\n# One-sided p-value: H1: mu_LP > national_mean\n# If t > 0, one-sided p = p_two / 2; if t < 0, one-sided p = 1 - p_two / 2\np_one = p_two / 2 if t_stat_lp > 0 else 1 - p_two / 2\n\n# One-sided test: La Paz > national mean?\nprint(f\"H₀: μ_LaPaz ≤ {national_mean:.2f}  vs  H₁: μ_LaPaz > {national_mean:.2f}\")\nprint(f\"\\nLa Paz municipalities:  {len(la_paz)}\")\nprint(f\"La Paz mean IMDS:       {la_paz.mean():.4f}\")\nprint(f\"National mean IMDS:     {national_mean:.4f}\")\nprint(f\"t-statistic:            {t_stat_lp:.4f}\")\nprint(f\"One-sided p-value:      {p_one:.6f}\")\nprint(f\"\\nConclusion at α = 0.05:\")\nif p_one < 0.05:\n    print(f\"  Reject H₀ (p = {p_one:.6f} < 0.05)\")\n    print(f\"  La Paz's mean IMDS is significantly greater than the national mean.\")\nelse:\n    print(f\"  Fail to reject H₀ (p = {p_one:.6f} ≥ 0.05)\")\n    print(f\"  No significant evidence that La Paz exceeds the national mean.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nH₀: μ_LaPaz ≤ 51.16  vs  H₁: μ_LaPaz > 51.16\n\nLa Paz municipalities:  87\nLa Paz mean IMDS:       50.9782\nNational mean IMDS:     51.1580\nt-statistic:            -0.3120\nOne-sided p-value:      0.622110\n\nConclusion at α = 0.05:\n  Fail to reject H₀ (p = 0.622110 ≥ 0.05)\n  No significant evidence that La Paz exceeds the national mean.\n```\n:::\n:::\n\n\n> **Key Concept 4.13: Subnational Inference Challenges**\n>\n> When testing hypotheses about departmental means, each department contains a different number of municipalities (ranging from ~10 to ~50+). Departments with fewer municipalities have **wider confidence intervals** and less statistical power. This means we may fail to detect real differences for smaller departments—not because the differences don't exist, but because we lack sufficient data to establish them conclusively.\n\n#### Task 5: Comparing Two Departments (Independent)\n\n**Learning Goal**: Apply two-sample t-tests to compare group means.\n\n**Economic Question**: \"Is the development gap between the most and least developed departments statistically significant?\"\n\n**Instructions**:\n\n1. Identify the departments with the highest and lowest mean IMDS (from Task 3 results)\n2. Use `scipy.stats.ttest_ind()` to perform a two-sample t-test comparing these departments\n3. Report the t-statistic and p-value\n4. Discuss both **statistical significance** (p-value) and **practical significance** (magnitude of the gap)\n5. What does this tell us about regional inequality in Bolivia?\n\n::: {#155ebbc4 .cell execution_count=20}\n``` {.python .cell-code}\n# Your code here: Two-sample t-test — highest vs lowest IMDS department\n\n# Identify highest and lowest departments\ndept_means = bol_key.groupby('dep')['imds'].mean()\ntop_dept = dept_means.idxmax()\nbot_dept = dept_means.idxmin()\n\n# Extract IMDS values for each\ntop_values = bol_key[bol_key['dep'] == top_dept]['imds']\nbot_values = bol_key[bol_key['dep'] == bot_dept]['imds']\n\n# Two-sample t-test\nt_stat_2s, p_value_2s = stats.ttest_ind(top_values, bot_values)\n\n# Two-sample t-test\nprint(f\"Highest IMDS department: {top_dept}\")\nprint(f\"  Mean IMDS:   {top_values.mean():.4f}\")\nprint(f\"  N:           {len(top_values)}\")\nprint(f\"\\nLowest IMDS department:  {bot_dept}\")\nprint(f\"  Mean IMDS:   {bot_values.mean():.4f}\")\nprint(f\"  N:           {len(bot_values)}\")\nprint(f\"\\nDifference in means:    {top_values.mean() - bot_values.mean():.4f}\")\nprint(f\"t-statistic:            {t_stat_2s:.4f}\")\nprint(f\"p-value:                {p_value_2s:.6f}\")\nprint(f\"\\nConclusion at α = 0.05:\")\nif p_value_2s < 0.05:\n    print(f\"  Reject H₀ (p = {p_value_2s:.6f} < 0.05)\")\n    print(f\"  The development gap of {top_values.mean() - bot_values.mean():.2f} points is statistically significant.\")\nelse:\n    print(f\"  Fail to reject H₀ (p = {p_value_2s:.6f} ≥ 0.05)\")\n    print(f\"  No significant evidence of a development gap.\")\nprint(f\"\\nPractical significance: A gap of {top_values.mean() - bot_values.mean():.2f} points on a 0-100 scale\")\nprint(f\"represents a {'substantial' if abs(top_values.mean() - bot_values.mean()) > 10 else 'modest'} difference in development outcomes.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nHighest IMDS department: Tarija\n  Mean IMDS:   60.6000\n  N:           11\n\nLowest IMDS department:  Pando\n  Mean IMDS:   45.9231\n  N:           13\n\nDifference in means:    14.6769\nt-statistic:            6.2916\np-value:                0.000002\n\nConclusion at α = 0.05:\n  Reject H₀ (p = 0.000002 < 0.05)\n  The development gap of 14.68 points is statistically significant.\n\nPractical significance: A gap of 14.68 points on a 0-100 scale\nrepresents a substantial difference in development outcomes.\n```\n:::\n:::\n\n\n#### Task 6: Policy Brief on Regional Inequality (Independent)\n\n**Objective**: Write a 200-300 word policy brief summarizing your statistical findings.\n\n**Your brief should address**:\n\n1. **Are departmental differences statistically significant?** Summarize results from Tasks 3-5.\n2. **Which departments need the most attention?** Use the forest plot and CI analysis to identify lagging regions.\n3. **How confident are we in these conclusions?** Discuss the confidence levels and what the CIs tell us.\n4. **What are the limitations of these tests?** Consider sample sizes, assumptions, and what the tests cannot tell us.\n\n**Format**: Write your brief in the markdown cell below. Support your arguments with specific numbers from your analysis (means, CIs, p-values).\n\n**Tip**: Remember Key Concepts 4.12 and 4.13—distinguish between statistical significance and policy relevance, and consider how unequal sample sizes affect your conclusions.\n\n::: {#51f28b9e .cell execution_count=21}\n``` {.python .cell-code}\n# Your code here: Additional analysis to support your policy brief\n#\n# Suggestions:\n# 1. Create a summary table of all department CIs and test results\n# 2. Calculate effect sizes (Cohen's d) for the two-sample comparison\n# 3. Visualize the national IMDS distribution with department means marked\n\n# Example: Summary statistics for the policy brief\n# Summary table for policy brief\ndept_summary = bol_key.groupby('dep')['imds'].agg(['mean', 'std', 'count']).sort_values('mean', ascending=False)\ndept_summary['se'] = dept_summary['std'] / np.sqrt(dept_summary['count'])\ndept_summary['ci_95'] = dept_summary.apply(\n    lambda r: f\"[{r['mean'] - 1.96*r['se']:.1f}, {r['mean'] + 1.96*r['se']:.1f}]\", axis=1)\ndept_summary[['mean', 'std', 'count', 'ci_95']].round(2)\n```\n\n::: {.cell-output .cell-output-display execution_count=21}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>mean</th>\n      <th>std</th>\n      <th>count</th>\n      <th>ci_95</th>\n    </tr>\n    <tr>\n      <th>dep</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Tarija</th>\n      <td>60.60</td>\n      <td>5.50</td>\n      <td>11</td>\n      <td>[57.3, 63.9]</td>\n    </tr>\n    <tr>\n      <th>Santa Cruz</th>\n      <td>54.31</td>\n      <td>4.84</td>\n      <td>55</td>\n      <td>[53.0, 55.6]</td>\n    </tr>\n    <tr>\n      <th>Cochabamba</th>\n      <td>52.50</td>\n      <td>8.50</td>\n      <td>47</td>\n      <td>[50.1, 54.9]</td>\n    </tr>\n    <tr>\n      <th>La Paz</th>\n      <td>50.98</td>\n      <td>5.37</td>\n      <td>87</td>\n      <td>[49.8, 52.1]</td>\n    </tr>\n    <tr>\n      <th>Beni</th>\n      <td>50.79</td>\n      <td>4.41</td>\n      <td>18</td>\n      <td>[48.7, 52.8]</td>\n    </tr>\n    <tr>\n      <th>Oruro</th>\n      <td>50.68</td>\n      <td>5.03</td>\n      <td>35</td>\n      <td>[49.0, 52.3]</td>\n    </tr>\n    <tr>\n      <th>Chuquisaca</th>\n      <td>47.80</td>\n      <td>6.60</td>\n      <td>29</td>\n      <td>[45.4, 50.2]</td>\n    </tr>\n    <tr>\n      <th>Potosí</th>\n      <td>47.57</td>\n      <td>7.67</td>\n      <td>38</td>\n      <td>[45.1, 50.0]</td>\n    </tr>\n    <tr>\n      <th>Pando</th>\n      <td>45.92</td>\n      <td>5.85</td>\n      <td>13</td>\n      <td>[42.7, 49.1]</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n#### What You've Learned from This Case Study\n\nThrough this analysis of subnational development in Bolivia, you've applied the full Chapter 4 statistical inference toolkit:\n\n- **Confidence intervals** for mean development levels\n- **One-sample and two-sample hypothesis tests** to evaluate development benchmarks and compare groups\n- **One-sided tests** for directional hypotheses about specific departments\n- **Forest plots** for comparing group CIs visually\n- **Statistical vs practical significance** in a policy context\n- **Critical thinking** about sample size, statistical power, and inference limitations\n\n**Connection to research**: The DS4Bolivia project uses these same statistical tools to evaluate whether satellite-predicted development indicators are significantly different from survey-based measures, providing evidence for the reliability of remote sensing approaches to SDG monitoring.\n\n**Looking ahead**: In Chapter 5, we'll move beyond testing means to exploring *bivariate relationships*—how nighttime lights relate to specific development outcomes across Bolivia's municipalities.\n\n---\n\n**Well done!** You've now tested development hypotheses for both cross-country convergence and Bolivian regional inequality using the tools of statistical inference.\n\n",
    "supporting": [
      "ch04_Statistical_Inference_for_the_Mean_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}