{
  "hash": "6c3655e12a2651eabcd75ed9573c6835",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 12. Further Topics in Multiple Regression\nexecute:\n  enabled: true\n  warning: false\n---\n\n\n**metricsAI: An Introduction to Econometrics with Python and AI in the Cloud**\n\n*[Carlos Mendez](https://carlos-mendez.org)*\n\n<img src=\"https://raw.githubusercontent.com/quarcs-lab/metricsai/main/images/ch12_visual_summary.jpg\" alt=\"Chapter 12 Visual Summary\" width=\"100%\">\n\nThis notebook provides an interactive introduction to advanced topics in regression inference and prediction. All code runs directly in Google Colab without any local setup.\n\n[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/quarcs-lab/metricsai/blob/main/notebooks_colab/ch12_Further_Topics_in_Multiple_Regression.ipynb)\n<div class=\"chapter-resources\">\n<a href=\"https://www.youtube.com/watch?v=0rM5db2lTPo\" target=\"_blank\" class=\"resource-btn\">🎬 AI Video</a>\n<a href=\"https://carlos-mendez.my.canva.site/s12-further-topics-in-multiple-regression-pdf\" target=\"_blank\" class=\"resource-btn\">✨ AI Slides</a>\n<a href=\"https://cameron.econ.ucdavis.edu/aed/traedv1_12\" target=\"_blank\" class=\"resource-btn\">📊 Cameron Slides</a>\n<a href=\"https://app.edcafe.ai/quizzes/6978693a2f5d08069e04bed3\" target=\"_blank\" class=\"resource-btn\">✏️ Quiz</a>\n<a href=\"https://app.edcafe.ai/chatbots/6978a1a32f5d08069e0719da\" target=\"_blank\" class=\"resource-btn\">🤖 AI Tutor</a>\n</div>\n\n\n## Chapter Overview\n\nThis chapter covers advanced topics that extend the multiple regression framework: robust standard errors for different data structures, prediction of outcomes, and deeper understanding of estimation and testing optimality.\n\n**Learning Objectives:**\n\nBy the end of this chapter, you will be able to:\n\n1. Understand when to use heteroskedastic-robust, cluster-robust, and HAC-robust standard errors\n2. Distinguish between prediction of average outcomes and individual outcomes\n3. Compute prediction intervals for conditional means and forecasts\n4. Understand the impact of nonrepresentative samples on regression estimates\n5. Recognize the difference between unbiased and best (most efficient) estimators\n6. Understand Type I and Type II errors in hypothesis testing\n7. Appreciate the role of bootstrap methods as an alternative to classical inference\n8. Know when OLS with robust SEs is preferred over more efficient estimators like FGLS\n\n**Datasets used:**\n\n- **AED_HOUSE.DTA**: 29 houses sold in Davis, California (1999) — for robust SEs and prediction\n- **AED_REALGDPPC.DTA**: Real GDP per capita growth (241 observations) — for HAC standard errors\n\n**Key economic questions:**\n\n- Do conclusions about house prices change with robust standard errors?\n- How precisely can we predict an individual house's price vs. the average price?\n- What happens to inference when our sample is not representative?\n\n**Chapter outline:**\n\n- 12.1 Example - House Price Prediction\n- 12.2 Inference with Robust Standard Errors\n- 12.3 Prediction\n- 12.4 Nonrepresentative Samples\n- 12.5 Best Estimation Methods\n- 12.6 Best Confidence Intervals\n- 12.7 Best Tests\n- Key Takeaways\n- Practice Exercises\n- Case Studies\n\n**Estimated time:** 60-75 minutes\n\n## Setup\n\nFirst, we import the necessary Python packages and configure the environment for reproducibility. All data will stream directly from GitHub.\n\n::: {#9f140665 .cell execution_count=1}\n``` {.python .cell-code}\n# Import required packages\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nimport statsmodels.api as sm\nfrom statsmodels.formula.api import ols\nfrom statsmodels.regression.linear_model import OLS\nfrom scipy import stats\nfrom statsmodels.graphics.tsaplots import plot_acf\nfrom statsmodels.tsa.stattools import acf\nimport random\nimport os\n\n# Set random seeds for reproducibility\nRANDOM_SEED = 42\nrandom.seed(RANDOM_SEED)\nnp.random.seed(RANDOM_SEED)\nos.environ['PYTHONHASHSEED'] = str(RANDOM_SEED)\n\n# GitHub data URL\nGITHUB_DATA_URL = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/\"\n\n# Set plotting style (dark theme matching book design)\nplt.style.use('dark_background')\nsns.set_style(\"darkgrid\")\nplt.rcParams.update({\n    'axes.facecolor': '#1a2235',\n    'figure.facecolor': '#12162c',\n    'grid.color': '#3a4a6b',\n    'figure.figsize': (10, 6),\n    'text.color': 'white',\n    'axes.labelcolor': 'white',\n    'xtick.color': 'white',\n    'ytick.color': 'white',\n    'axes.edgecolor': '#1a2235',\n})\n\nprint(\"Setup complete! Ready to explore further topics in multiple regression.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSetup complete! Ready to explore further topics in multiple regression.\n```\n:::\n:::\n\n\n## 12.1: Example - House Price Prediction\n\nWe'll work with two datasets:\n\n1. **House price data** for cross-sectional robust inference\n2. **GDP growth data** for time series HAC inference\n\n::: {#fe8507fc .cell execution_count=2}\n``` {.python .cell-code}\n# Read house data\ndata_house = pd.read_stata(GITHUB_DATA_URL + 'AED_HOUSE.DTA')\n\nprint(\"House Data Summary:\")\ndata_house.describe()\n\nprint(\"\\nFirst few observations:\")\ndata_house[['price', 'size', 'bedrooms', 'bathrooms', 'lotsize', 'age', 'monthsold']].head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nHouse Data Summary:\n\nFirst few observations:\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>price</th>\n      <th>size</th>\n      <th>bedrooms</th>\n      <th>bathrooms</th>\n      <th>lotsize</th>\n      <th>age</th>\n      <th>monthsold</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>204000</td>\n      <td>1400</td>\n      <td>3</td>\n      <td>2.0</td>\n      <td>1</td>\n      <td>31.0</td>\n      <td>7</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>212000</td>\n      <td>1600</td>\n      <td>3</td>\n      <td>3.0</td>\n      <td>2</td>\n      <td>33.0</td>\n      <td>5</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>213000</td>\n      <td>1800</td>\n      <td>3</td>\n      <td>2.0</td>\n      <td>2</td>\n      <td>51.0</td>\n      <td>4</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>220000</td>\n      <td>1600</td>\n      <td>3</td>\n      <td>2.0</td>\n      <td>1</td>\n      <td>49.0</td>\n      <td>4</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>224500</td>\n      <td>2100</td>\n      <td>4</td>\n      <td>2.5</td>\n      <td>2</td>\n      <td>47.0</td>\n      <td>6</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## 12.2: Inference with Robust Standard Errors\n\nIn practice, the classical assumptions often fail. The most common violations are:\n\n**1. Heteroskedasticity**: Error variance varies across observations\n\n- Common in cross-sectional data\n- Makes default standard errors incorrect\n- Solution: Use **heteroskedasticity-robust standard errors** (HC1, White's correction)\n\n**2. Clustered errors**: Errors correlated within groups\n\n- Common in panel data, hierarchical data\n- Makes default and het-robust SEs too small\n- Solution: Use **cluster-robust standard errors**\n\n**3. Autocorrelation**: Errors correlated over time\n\n- Common in time series\n- Makes default SEs incorrect\n- Solution: Use **HAC (Newey-West) standard errors**\n\n**Key insight**: OLS coefficients remain unbiased under these violations, but standard errors need adjustment.\n\n**Heteroskedastic-robust standard error formula**:\n\n$$se_{het}(\\hat{\\beta}_j) = \\sqrt{\\frac{\\sum_{i=1}^n \\tilde{x}_{ji}^2 \\hat{u}_i^2}{(\\sum_{i=1}^n \\tilde{x}_{ji}^2)^2}}$$\n\nwhere $\\tilde{x}_{ji}$ are residuals from regressing $x_j$ on other regressors, and $\\hat{u}_i$ are OLS residuals.\n\n::: {#b7fc1c7d .cell execution_count=3}\n``` {.python .cell-code}\n# 12.2 INFERENCE WITH ROBUST STANDARD ERRORS\n\n# Estimate with default standard errors\nmodel_default = ols('price ~ size + bedrooms + bathrooms + lotsize + age + monthsold',\n                    data=data_house).fit()\n\nprint(\"\\nRegression with Default Standard Errors:\")\nmodel_default.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nRegression with Default Standard Errors:\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<table class=\"simpletable\">\n<caption>OLS Regression Results</caption>\n<tr>\n  <th>Dep. Variable:</th>          <td>price</td>      <th>  R-squared:         </th> <td>   0.651</td>\n</tr>\n<tr>\n  <th>Model:</th>                   <td>OLS</td>       <th>  Adj. R-squared:    </th> <td>   0.555</td>\n</tr>\n<tr>\n  <th>Method:</th>             <td>Least Squares</td>  <th>  F-statistic:       </th> <td>   6.826</td>\n</tr>\n<tr>\n  <th>Date:</th>             <td>Mon, 06 Apr 2026</td> <th>  Prob (F-statistic):</th> <td>0.000342</td>\n</tr>\n<tr>\n  <th>Time:</th>                 <td>12:11:19</td>     <th>  Log-Likelihood:    </th> <td> -330.74</td>\n</tr>\n<tr>\n  <th>No. Observations:</th>      <td>    29</td>      <th>  AIC:               </th> <td>   675.5</td>\n</tr>\n<tr>\n  <th>Df Residuals:</th>          <td>    22</td>      <th>  BIC:               </th> <td>   685.1</td>\n</tr>\n<tr>\n  <th>Df Model:</th>              <td>     6</td>      <th>                     </th>     <td> </td>   \n</tr>\n<tr>\n  <th>Covariance Type:</th>      <td>nonrobust</td>    <th>                     </th>     <td> </td>   \n</tr>\n</table>\n<table class=\"simpletable\">\n<tr>\n      <td></td>         <th>coef</th>     <th>std err</th>      <th>t</th>      <th>P>|t|</th>  <th>[0.025</th>    <th>0.975]</th>  \n</tr>\n<tr>\n  <th>Intercept</th> <td> 1.378e+05</td> <td> 6.15e+04</td> <td>    2.242</td> <td> 0.035</td> <td> 1.03e+04</td> <td> 2.65e+05</td>\n</tr>\n<tr>\n  <th>size</th>      <td>   68.3694</td> <td>   15.389</td> <td>    4.443</td> <td> 0.000</td> <td>   36.454</td> <td>  100.285</td>\n</tr>\n<tr>\n  <th>bedrooms</th>  <td> 2685.3151</td> <td> 9192.526</td> <td>    0.292</td> <td> 0.773</td> <td>-1.64e+04</td> <td> 2.17e+04</td>\n</tr>\n<tr>\n  <th>bathrooms</th> <td> 6832.8800</td> <td> 1.57e+04</td> <td>    0.435</td> <td> 0.668</td> <td>-2.58e+04</td> <td> 3.94e+04</td>\n</tr>\n<tr>\n  <th>lotsize</th>   <td> 2303.2214</td> <td> 7226.535</td> <td>    0.319</td> <td> 0.753</td> <td>-1.27e+04</td> <td> 1.73e+04</td>\n</tr>\n<tr>\n  <th>age</th>       <td> -833.0386</td> <td>  719.335</td> <td>   -1.158</td> <td> 0.259</td> <td>-2324.847</td> <td>  658.770</td>\n</tr>\n<tr>\n  <th>monthsold</th> <td>-2088.5036</td> <td> 3520.898</td> <td>   -0.593</td> <td> 0.559</td> <td>-9390.399</td> <td> 5213.392</td>\n</tr>\n</table>\n<table class=\"simpletable\">\n<tr>\n  <th>Omnibus:</th>       <td> 1.317</td> <th>  Durbin-Watson:     </th> <td>   1.259</td>\n</tr>\n<tr>\n  <th>Prob(Omnibus):</th> <td> 0.518</td> <th>  Jarque-Bera (JB):  </th> <td>   0.980</td>\n</tr>\n<tr>\n  <th>Skew:</th>          <td> 0.151</td> <th>  Prob(JB):          </th> <td>   0.612</td>\n</tr>\n<tr>\n  <th>Kurtosis:</th>      <td> 2.152</td> <th>  Cond. No.          </th> <td>2.59e+04</td>\n</tr>\n</table><br/><br/>Notes:<br/>[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.<br/>[2] The condition number is large, 2.59e+04. This might indicate that there are<br/>strong multicollinearity or other numerical problems.\n```\n:::\n:::\n\n\n::: {#30e88e13 .cell execution_count=4}\n``` {.python .cell-code}\n# Estimate with heteroskedastic-robust standard errors (HC1)\nmodel_robust = ols('price ~ size + bedrooms + bathrooms + lotsize + age + monthsold',\n                   data=data_house).fit(cov_type='HC1')\n\nprint(\"\\nRegression with Heteroskedastic-Robust Standard Errors (HC1):\")\nmodel_robust.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nRegression with Heteroskedastic-Robust Standard Errors (HC1):\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<table class=\"simpletable\">\n<caption>OLS Regression Results</caption>\n<tr>\n  <th>Dep. Variable:</th>          <td>price</td>      <th>  R-squared:         </th> <td>   0.651</td>\n</tr>\n<tr>\n  <th>Model:</th>                   <td>OLS</td>       <th>  Adj. R-squared:    </th> <td>   0.555</td>\n</tr>\n<tr>\n  <th>Method:</th>             <td>Least Squares</td>  <th>  F-statistic:       </th> <td>   6.410</td>\n</tr>\n<tr>\n  <th>Date:</th>             <td>Mon, 06 Apr 2026</td> <th>  Prob (F-statistic):</th> <td>0.000514</td>\n</tr>\n<tr>\n  <th>Time:</th>                 <td>12:11:19</td>     <th>  Log-Likelihood:    </th> <td> -330.74</td>\n</tr>\n<tr>\n  <th>No. Observations:</th>      <td>    29</td>      <th>  AIC:               </th> <td>   675.5</td>\n</tr>\n<tr>\n  <th>Df Residuals:</th>          <td>    22</td>      <th>  BIC:               </th> <td>   685.1</td>\n</tr>\n<tr>\n  <th>Df Model:</th>              <td>     6</td>      <th>                     </th>     <td> </td>   \n</tr>\n<tr>\n  <th>Covariance Type:</th>         <td>HC1</td>       <th>                     </th>     <td> </td>   \n</tr>\n</table>\n<table class=\"simpletable\">\n<tr>\n      <td></td>         <th>coef</th>     <th>std err</th>      <th>z</th>      <th>P>|z|</th>  <th>[0.025</th>    <th>0.975]</th>  \n</tr>\n<tr>\n  <th>Intercept</th> <td> 1.378e+05</td> <td> 6.55e+04</td> <td>    2.102</td> <td> 0.036</td> <td> 9324.785</td> <td> 2.66e+05</td>\n</tr>\n<tr>\n  <th>size</th>      <td>   68.3694</td> <td>   15.359</td> <td>    4.451</td> <td> 0.000</td> <td>   38.266</td> <td>   98.473</td>\n</tr>\n<tr>\n  <th>bedrooms</th>  <td> 2685.3151</td> <td> 8285.528</td> <td>    0.324</td> <td> 0.746</td> <td>-1.36e+04</td> <td> 1.89e+04</td>\n</tr>\n<tr>\n  <th>bathrooms</th> <td> 6832.8800</td> <td> 1.93e+04</td> <td>    0.354</td> <td> 0.723</td> <td> -3.1e+04</td> <td> 4.46e+04</td>\n</tr>\n<tr>\n  <th>lotsize</th>   <td> 2303.2214</td> <td> 5328.860</td> <td>    0.432</td> <td> 0.666</td> <td>-8141.152</td> <td> 1.27e+04</td>\n</tr>\n<tr>\n  <th>age</th>       <td> -833.0386</td> <td>  762.930</td> <td>   -1.092</td> <td> 0.275</td> <td>-2328.353</td> <td>  662.276</td>\n</tr>\n<tr>\n  <th>monthsold</th> <td>-2088.5036</td> <td> 3738.270</td> <td>   -0.559</td> <td> 0.576</td> <td>-9415.379</td> <td> 5238.372</td>\n</tr>\n</table>\n<table class=\"simpletable\">\n<tr>\n  <th>Omnibus:</th>       <td> 1.317</td> <th>  Durbin-Watson:     </th> <td>   1.259</td>\n</tr>\n<tr>\n  <th>Prob(Omnibus):</th> <td> 0.518</td> <th>  Jarque-Bera (JB):  </th> <td>   0.980</td>\n</tr>\n<tr>\n  <th>Skew:</th>          <td> 0.151</td> <th>  Prob(JB):          </th> <td>   0.612</td>\n</tr>\n<tr>\n  <th>Kurtosis:</th>      <td> 2.152</td> <th>  Cond. No.          </th> <td>2.59e+04</td>\n</tr>\n</table><br/><br/>Notes:<br/>[1] Standard Errors are heteroscedasticity robust (HC1)<br/>[2] The condition number is large, 2.59e+04. This might indicate that there are<br/>strong multicollinearity or other numerical problems.\n```\n:::\n:::\n\n\n> **Key Concept 12.1: Heteroskedastic-Robust Standard Errors**\n>\n> When error variance is not constant across observations, default OLS standard errors are invalid. Heteroskedastic-robust (HC1) SEs correct this problem without changing the coefficient estimates themselves. Only the standard errors, $t$-statistics, and confidence intervals change. For cross-sectional data, reporting HC1 robust SEs is considered best practice.\n\n### Comparison: Default vs. Robust Standard Errors\n\nLet's systematically compare the standard errors and see how inference changes.\n\n### Interpreting the Comparison: What Changed?\n\n**Understanding the Results:**\n\nLooking at the SE Ratio column, we can see how robust standard errors differ from default ones:\n\n**When SE Ratio > 1.0**: Robust SE is larger than default SE\n\n- Suggests heteroskedasticity is present\n- Default SEs were **understating** uncertainty\n- t-statistics decrease, p-values increase\n- We were **too confident** in rejecting null hypotheses\n\n**When SE Ratio ≈ 1.0**: Robust SE similar to default SE\n\n- Little evidence of heteroskedasticity for this variable\n- Both methods give similar inference\n\n**When SE Ratio < 1.0**: Robust SE smaller than default SE\n\n- Unusual but possible\n- Could indicate negative correlation between x² and residuals\n\n**Practical Implications:**\n\n1. **Coefficient estimates unchanged**: OLS point estimates are the same regardless of SE type\n2. **Inference changes**: Variables significant with default SEs might become insignificant with robust SEs\n3. **Publication standard**: Most journals now require robust SEs for cross-sectional data\n4. **Conservative approach**: When in doubt, report robust SEs (they're generally more credible)\n\n**Rule of thumb**: If robust SEs differ substantially (>30% change), heteroskedasticity is likely present and you should use robust inference.\n\n### HAC Standard Errors for Time Series\n\nTime series data often exhibit **autocorrelation**: current errors correlated with past errors.\n\n**Example**: GDP growth tends to persist\n\n- Positive shock today → likely positive next period\n- Creates correlation structure $Corr(u_t, u_{t-s}) \\neq 0$\n\n**HAC (Newey-West) standard errors**:\n\n- Account for both heteroskedasticity AND autocorrelation\n- Require specifying maximum lag length $m$\n- Rule of thumb: $m = 0.75 \\times T^{1/3}$\n\n**Autocorrelation function**:\n\n$$\\rho_s = \\frac{Cov(y_t, y_{t-s})}{\\sqrt{Var(y_t) Var(y_{t-s})}}$$\n\nWe can visualize this with a **correlogram**.\n\n::: {#da0d89cb .cell execution_count=5}\n``` {.python .cell-code}\n# Load GDP growth data\ndata_gdp = pd.read_stata(GITHUB_DATA_URL + 'AED_REALGDPPC.DTA')\n\n# HAC Standard Errors for Time Series Data\n\nprint(\"\\nGDP Growth Data Summary:\")\ndata_gdp['growth'].describe()\n\n# Mean of growth\nmean_growth = data_gdp['growth'].mean()\nprint(f\"\\nMean growth rate: {mean_growth:.6f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nGDP Growth Data Summary:\n\nMean growth rate: 1.990456\n```\n:::\n:::\n\n\n::: {#f09ddb78 .cell execution_count=6}\n``` {.python .cell-code}\n# Autocorrelation analysis\nprint(\"\\nAutocorrelations at multiple lags:\")\nacf_values = acf(data_gdp['growth'], nlags=5, fft=False)\nfor i in range(6):\n    print(f\"  Lag {i}: {acf_values[i]:.6f}\")\n\n# Positive lag 1 correlation suggests persistence\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nAutocorrelations at multiple lags:\n  Lag 0: nan\n  Lag 1: nan\n  Lag 2: nan\n  Lag 3: nan\n  Lag 4: nan\n  Lag 5: nan\n```\n:::\n:::\n\n\n::: {#05f8c9cc .cell execution_count=7}\n``` {.python .cell-code}\n# Correlogram\nfig, ax = plt.subplots(figsize=(10, 6))\nplot_acf(data_gdp['growth'], lags=10, ax=ax, alpha=0.05)\nax.set_xlabel('Lag', fontsize=12)\nax.set_ylabel('Autocorrelation', fontsize=12)\nax.set_title('Figure 12.1: Correlogram of GDP Growth', fontsize=14, fontweight='bold')\nplt.tight_layout()\nplt.show()\n\nprint(\"The correlogram shows autocorrelation at various lags.\")\nprint(\"Blue shaded area = 95% confidence bands under null of no autocorrelation.\")\n```\n\n::: {.cell-output .cell-output-display}\n![](ch12_Further_Topics_in_Multiple_Regression_files/figure-html/cell-8-output-1.png){width=950 height=565}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nThe correlogram shows autocorrelation at various lags.\nBlue shaded area = 95% confidence bands under null of no autocorrelation.\n```\n:::\n:::\n\n\n> **Key Concept 12.2: HAC Standard Errors for Time Series**\n>\n> In time series data, errors are often autocorrelated — today's shock persists into tomorrow. HAC (heteroskedasticity and autocorrelation consistent) standard errors, also called Newey-West SEs, account for both heteroskedasticity and autocorrelation. The lag length $m$ must be specified; a common rule of thumb is $m = 0.75 \\times T^{1/3}$.\n\n### Interpreting HAC Standard Errors\n\n**What the Results Tell Us:**\n\nComparing the three standard error estimates for the mean growth rate:\n\n1. **Default SE** (assumes no autocorrelation):\n - Smallest standard error\n - Assumes errors are independent over time\n - **Underestimates** uncertainty when autocorrelation exists\n\n2. **HAC with lag 0** (het-robust only):\n - Accounts for heteroskedasticity but not autocorrelation\n - Often similar to default in time series\n - Still underestimates uncertainty if autocorrelation present\n\n3. **HAC with lag 5** (Newey-West):\n - Accounts for both heteroskedasticity AND autocorrelation\n - **Larger SE** reflects true uncertainty\n - More conservative but valid inference\n\n**Why is HAC SE larger?**\n\nAutocorrelation creates **information overlap** between observations:\n\n- If growth today predicts growth tomorrow, consecutive observations aren't fully independent\n- We have **less effective information** than the sample size suggests\n- Standard errors must increase to reflect this\n\n**Practical guidance:**\n\n- For time series data, **always use HAC SEs**\n- Lag length choice: Rule of thumb = 0.75 × T^(1/3)\n - For T=100: m ≈ 3-4 lags\n - For T=200: m ≈ 4-5 lags\n- Err on the side of more lags (inference remains valid)\n- Check sensitivity to lag length\n\n**The cost of ignoring autocorrelation:**\n\n- Overconfident inference (SEs too small)\n- Spurious significance (false discoveries)\n- Invalid hypothesis tests\n\nHaving established how to conduct valid inference with robust standard errors, we now turn to prediction — estimating outcomes for specific values.\n\n## 12.3: Prediction\n\nPrediction is a core application of regression, but there's a crucial distinction:\n\n**1. Predicting the conditional mean** $E[y | x^*]$\n\n- Average outcome for given $x^*$\n- More precise (smaller standard error)\n- Used for policy analysis, average effects\n\n**2. Predicting an actual value** $y | x^*$\n\n- Individual outcome including random error\n- Less precise (larger standard error)\n- Used for forecasting individual cases\n\n**Key formulas**:\n\nConditional mean:\n$$E[y | x^*] = \\beta_1 + \\beta_2 x_2^* + \\cdots + \\beta_k x_k^*$$\n\nActual value:\n$$y | x^* = \\beta_1 + \\beta_2 x_2^* + \\cdots + \\beta_k x_k^* + u^*$$\n\n**Standard errors**:\n\nFor conditional mean (bivariate case):\n$$se(\\hat{y}_{cm}) = s_e \\sqrt{\\frac{1}{n} + \\frac{(x^* - \\bar{x})^2}{\\sum(x_i - \\bar{x})^2}}$$\n\nFor actual value (bivariate case):\n$$se(\\hat{y}_f) = s_e \\sqrt{1 + \\frac{1}{n} + \\frac{(x^* - \\bar{x})^2}{\\sum(x_i - \\bar{x})^2}}$$\n\nNote the \"1 +\" term for actual values - this reflects the irreducible uncertainty from $u^*$.\n\n::: {#8d868498 .cell execution_count=8}\n``` {.python .cell-code}\n# 12.3 PREDICTION\n\n# Simple regression: price on size\nmodel_simple = ols('price ~ size', data=data_house).fit()\n\nprint(\"\\nSimple regression: price = β₀ + β₁·size + u\")\nprint(f\"  β₀ (Intercept): ${model_simple.params['Intercept']:.2f}\")\nprint(f\"  β₁ (Size): ${model_simple.params['size']:.4f}\")\nprint(f\"  R²: {model_simple.rsquared:.4f}\")\nprint(f\"  Root MSE (σ̂): ${np.sqrt(model_simple.mse_resid):.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nSimple regression: price = β₀ + β₁·size + u\n  β₀ (Intercept): $115017.28\n  β₁ (Size): $73.7710\n  R²: 0.6175\n  Root MSE (σ̂): $23550.66\n```\n:::\n:::\n\n\n> **Key Concept 12.3: Predicting Conditional Means vs. Individual Outcomes**\n>\n> Predicting the average outcome $E[y|x^*]$ is more precise than predicting an individual $y|x^*$. The forecast variance equals the conditional mean variance plus $\\text{Var}(u^*)$: $\\text{Var}(\\hat{y}_f) = \\text{Var}(\\hat{y}_{cm}) + \\sigma^2$. As $n \\to \\infty$, the conditional mean SE shrinks to zero, but the forecast SE remains at least $s_e$ — a fundamental limit on individual predictions.\n\n### Why Are Prediction Intervals So Much Wider?\n\n**The Fundamental Difference:**\n\nLooking at the two panels, you'll notice the **prediction interval (blue) is dramatically wider** than the confidence interval (red). This isn't a mistake—it reflects a fundamental distinction in what we're predicting.\n\n**Confidence Interval for E[Y|X] (Red):**\n\n- Predicts the **average** price for all 2000 sq ft houses\n- Uncertainty comes only from **estimation error** in β̂\n- As sample size increases (n → ∞), this interval **shrinks to zero**\n- Formula includes: 1/n term (goes to 0 as n grows)\n\n**Prediction Interval for Y (Blue):**\n\n- Predicts an **individual** house price\n- Uncertainty comes from:\n 1. **Estimation error** in β̂ (same as CI)\n 2. **Irreducible randomness** in the individual outcome (u*)\n- Even with perfect knowledge of β, individual predictions remain uncertain\n- Formula includes: **\"1 +\"** term (never goes away)\n\n**Intuitive Example:**\n\nImagine predicting height from age:\n\n- **Conditional mean**: Average height of all 10-year-olds = 140 cm\n - We can estimate this average very precisely\n - CI might be [139, 141] cm\n- **Actual value**: A specific 10-year-old's height\n - Could be anywhere from 120 to 160 cm\n - PI might be [125, 155] cm\n - Even knowing the average perfectly doesn't eliminate individual variation\n\n**Mathematical Insight:**\n\n$$se(\\hat{y}_f) = \\sqrt{s_e^2 + se(\\hat{y}_{cm})^2}$$\n\n- First term (s_e²): Irreducible error variance—dominates the formula\n- Second term: Estimation uncertainty—becomes negligible with large samples\n- Result: PI width ≈ 2 × 1.96 × s_e ≈ 4 × RMSE\n\n**Practical Implications:**\n\n1. **Don't confuse the two**: Predicting averages is much more precise than predicting individuals\n2. **Policy vs. forecasting**: \n - Policy analysis (average effects) → Use confidence intervals\n - Individual forecasting (who will default?) → Use prediction intervals\n3. **Communicating uncertainty**: Always show prediction intervals for individual forecasts\n4. **Limits of prediction**: No amount of data eliminates individual-level uncertainty\n\n### Visualization: Confidence vs. Prediction Intervals\n\nThis figure illustrates the fundamental difference between:\n\n- **Confidence interval for conditional mean** (narrower, red)\n- **Prediction interval for actual value** (wider, blue)\n\n### Understanding the Numbers: A Concrete Example\n\n**Interpreting the Results for a 2000 sq ft House:**\n\nLooking at our predictions, several patterns emerge:\n\n**1. Point Prediction:**\n\n- Predicted price ≈ \\$280,000 (approximately)\n- This is our best single guess\n- Same for both conditional mean and actual value\n\n**2. Confidence Interval for E[Y|X=2000]:**\n\n- Relatively narrow (e.g., \\$250k - \\$310k)\n- Tells us: \"We're 95% confident the **average price** of all 2000 sq ft houses is in this range\"\n- Precise because we're estimating a population average\n- Useful for: Understanding market valuations, setting pricing policies\n\n**3. Prediction Interval for Y:**\n\n- Much wider (e.g., \\$180k - \\$380k)\n- Tells us: \"We're 95% confident **this specific house** will sell in this range\"\n- Wide because individual houses vary considerably\n- Useful for: Setting listing ranges, individual appraisals\n\n**The Ratio is Revealing:**\n\nNotice that the PI is approximately **3-4 times wider** than the CI. This ratio tells us:\n\n- Most variation is **between houses** (individual heterogeneity)\n- Relatively little variation is **estimation uncertainty**\n- Adding more data would shrink the CI but barely affect the PI\n\n**Statistical vs. Economic Significance:**\n\n- **CI width** = Statistical precision (how well we know β)\n- **PI width** = Economic uncertainty (inherent market volatility)\n- In this example: Good statistical precision, but still substantial economic uncertainty\n\n**Practical Takeaway:**\n\nIf you're a real estate agent:\n\n- Don't promise a precise price (\\$280k)\n- Do provide a realistic range (\\$180k - \\$380k)\n- Explain that individual houses vary, even controlling for size\n- Use the confidence interval to discuss average market values\n\n### Deconstructing the Standard Error Formulas\n\n**Understanding Where the \"1 +\" Comes From:**\n\nThe manual calculations reveal the mathematical structure of prediction uncertainty:\n\n**For Conditional Mean:**\n$$se(\\hat{y}_{cm}) = \\hat{\\sigma} \\sqrt{\\frac{1}{n} + \\frac{(x^* - \\bar{x})^2}{\\sum(x_i - \\bar{x})^2}}$$\n\n- **First term (1/n)**: Decreases with sample size—more data reduces uncertainty\n- **Second term**: Distance from mean matters—extrapolation is risky\n - Prediction at $x^* = \\bar{x}$ (sample mean) is most precise\n - Prediction far from $\\bar{x}$ is less precise\n- Both terms → 0 as n → ∞ (perfect knowledge of E[Y|X])\n\n**For Actual Value:**\n$$se(\\hat{y}_f) = \\hat{\\sigma} \\sqrt{1 + \\frac{1}{n} + \\frac{(x^* - \\bar{x})^2}{\\sum(x_i - \\bar{x})^2}}$$\n\n- **The critical \"1 +\"**: Represents $Var[u^*]$, the future error term\n- This term **never disappears**, even with infinite data\n- Dominates the formula in moderate to large samples\n\n**Numerical Insight:**\n\nIn our example:\n\n- $\\hat{\\sigma}$ (RMSE) ≈ \\$90k (this is the irreducible uncertainty)\n- $(1/n)$ term ≈ 0.034 (small with n=29)\n- Distance term varies with prediction point\n\nFor predictions near the mean:\n\n- $se(\\hat{y}_{cm})$ ≈ \\$90k × √0.034 ≈ \\$17k (mainly from 1/n)\n- $se(\\hat{y}_f)$ ≈ \\$90k × √1.034 ≈ \\$92k (mainly from the \"1\")\n\n**The \"1 +\" term is why:**\n\n- Prediction intervals don't shrink much with more data\n- Individual predictions remain uncertain even with perfect models\n- $se(\\hat{y}_f) \\approx \\hat{\\sigma}$ in large samples\n\n**Geometric Interpretation:**\n\nThe funnel shape in prediction plots comes from the distance term:\n\n- Narrow near $\\bar{x}$ (center of data)\n- Wider at extremes (extrapolation region)\n- But even at the center, PI is wide due to the \"1\" term\n\n**Practical Lesson:**\n\nWhen presenting predictions:\n\n1. Always acknowledge the \"1 +\" uncertainty\n2. Be most confident about predictions near the data center\n3. Be especially cautious about extrapolation (predictions outside the data range)\n4. Understand that better models reduce estimation error but not irreducible randomness\n\n### Prediction at Specific Values\n\nLet's predict house price for a 2000 square foot house.\n\n### Manual Calculation of Standard Errors\n\nLet's manually calculate the standard errors to understand the formulas.\n\n### Prediction with Multiple Regression\n\nNow let's predict using the full multiple regression model.\n\n::: {#e12566f7 .cell execution_count=9}\n``` {.python .cell-code}\n# Prediction for Multiple Regression\n\nmodel_multi = ols('price ~ size + bedrooms + bathrooms + lotsize + age + monthsold',\n                  data=data_house).fit()\n\n# Predict for specific values\nnew_house = pd.DataFrame({\n    'size': [2000],\n    'bedrooms': [4],\n    'bathrooms': [2],\n    'lotsize': [2],\n    'age': [40],\n    'monthsold': [6]\n})\n\npred_multi = model_multi.get_prediction(sm.add_constant(new_house))\n\nprint(\"\\nPrediction for:\")\nprint(\"  size=2000, bedrooms=4, bathrooms=2, lotsize=2, age=40, monthsold=6\")\nprint(f\"\\nPredicted price: ${pred_multi.predicted_mean[0]:.2f}\")\n\n# Confidence interval for conditional mean\nci_mean_multi = pred_multi.conf_int(alpha=0.05)\nprint(f\"\\n95% CI for E[Y|X]:\")\nprint(f\"  [${ci_mean_multi[0, 0]:.2f}, ${ci_mean_multi[0, 1]:.2f}]\")\nprint(f\"  SE: ${pred_multi.se_mean[0]:.2f}\")\n\n# Prediction interval for actual value\ns_e_multi = np.sqrt(model_multi.mse_resid)\ns_y_cm_multi = pred_multi.se_mean[0]\ns_y_f_multi = np.sqrt(s_e_multi**2 + s_y_cm_multi**2)\n\nn_multi = len(data_house)\nk_multi = len(model_multi.params)\ntcrit_multi = stats.t.ppf(0.975, n_multi - k_multi)\n\npi_lower = pred_multi.predicted_mean[0] - tcrit_multi * s_y_f_multi\npi_upper = pred_multi.predicted_mean[0] + tcrit_multi * s_y_f_multi\n\nprint(f\"\\n95% PI for Y:\")\nprint(f\"  [${pi_lower:.2f}, ${pi_upper:.2f}]\")\nprint(f\"  SE: ${s_y_f_multi:.2f}\")\n\nprint(\"\\nMultiple regression provides more precise conditional mean predictions.\")\nprint(\"But individual predictions still have large uncertainty.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nPrediction for:\n  size=2000, bedrooms=4, bathrooms=2, lotsize=2, age=40, monthsold=6\n\nPredicted price: $257690.80\n\n95% CI for E[Y|X]:\n  [$244234.97, $271146.63]\n  SE: $6488.26\n\n95% PI for Y:\n  [$204255.32, $311126.28]\n  SE: $25766.03\n\nMultiple regression provides more precise conditional mean predictions.\nBut individual predictions still have large uncertainty.\n```\n:::\n:::\n\n\n### Prediction with Robust Standard Errors\n\nWhen heteroskedasticity is present, we should use robust standard errors for prediction intervals too.\n\n::: {#5bb17874 .cell execution_count=10}\n``` {.python .cell-code}\n# Prediction with Heteroskedastic-Robust SEs\n\nmodel_multi_robust = ols('price ~ size + bedrooms + bathrooms + lotsize + age + monthsold',\n                         data=data_house).fit(cov_type='HC1')\n\npred_multi_robust = model_multi_robust.get_prediction(sm.add_constant(new_house))\n\nprint(f\"\\nPredicted price: ${pred_multi_robust.predicted_mean[0]:.2f}\")\n\n# Robust confidence interval for conditional mean\nci_mean_robust = pred_multi_robust.conf_int(alpha=0.05)\nprint(f\"\\nRobust 95% CI for E[Y|X]:\")\nprint(f\"  [${ci_mean_robust[0, 0]:.2f}, ${ci_mean_robust[0, 1]:.2f}]\")\nprint(f\"  Robust SE: ${pred_multi_robust.se_mean[0]:.2f}\")\n\n# Robust prediction interval\ns_y_cm_robust = pred_multi_robust.se_mean[0]\ns_y_f_robust = np.sqrt(s_e_multi**2 + s_y_cm_robust**2)\n\nprint(f\"\\nRobust 95% PI for Y:\")\nprint(f\"  Robust SE for actual value: ${s_y_f_robust:.2f}\")\n\nprint(\"\\nComparison of standard vs. robust:\")\nprint(f\"  SE (standard): ${s_y_cm_multi:.2f}\")\nprint(f\"  SE (robust): ${s_y_cm_robust:.2f}\")\nprint(f\"  Ratio: {s_y_cm_robust / s_y_cm_multi:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nPredicted price: $257690.80\n\nRobust 95% CI for E[Y|X]:\n  [$244694.26, $270687.34]\n  Robust SE: $6631.01\n\nRobust 95% PI for Y:\n  Robust SE for actual value: $25802.35\n\nComparison of standard vs. robust:\n  SE (standard): $6488.26\n  SE (robust): $6631.01\n  Ratio: 1.022\n```\n:::\n:::\n\n\n> **Key Concept 12.4: Why Individual Forecasts Are Imprecise**\n>\n> Even with precisely estimated coefficients, predicting an individual outcome is imprecise because the forecast must account for the unobservable error $u^*$. The forecast standard error satisfies $se(\\hat{y}_f) \\geq s_e$ — it is at least as large as the regression's standard error. This means 95% prediction intervals are at least $\\pm 1.96 \\times s_e$ wide, regardless of how much data we have.\n\n## 12.4: Nonrepresentative Samples\n\n**Sample selection** can bias OLS estimates:\n\n**Case 1: Selection on regressors** (X)\n\n- Example: Oversample high-income households\n- OLS remains unbiased if we include income as a control\n- Solution: Include selection variables as controls\n\n**Case 2: Selection on outcome** (Y)\n\n- Example: Survey excludes very high earners\n- OLS estimates are biased for population parameters\n- Solution: Sample weights, Heckman correction, or other selection models\n\n**Survey weights**:\n\n- Many surveys provide weights to adjust for nonrepresentativeness\n- Use **weighted least squares (WLS)** instead of OLS\n- Weight formula: $w_i = 1 / P(\\text{selected})$\n\n**Key insight**: Always check whether your sample is representative of your target population!\n\n### Bootstrap Confidence Intervals: An Alternative Approach\n\n**What is Bootstrap?**\n\nThe bootstrap is a computational method that:\n\n1. **Resamples** your data many times (e.g., 1000 replications)\n2. **Re-estimates** the model for each resample\n3. Uses the **distribution of estimates** to build confidence intervals\n\n**How it works:**\n\nFor each bootstrap replication b = 1, ..., B:\n\n1. Draw n observations **with replacement** from original data\n2. Estimate regression: $\\hat{\\beta}_j^{(b)}$\n3. Store the coefficient estimate\n\nAfter B replications:\n\n- You have B estimates: $\\{\\hat{\\beta}_j^{(1)}, \\hat{\\beta}_j^{(2)}, ..., \\hat{\\beta}_j^{(B)}\\}$\n- These form an empirical distribution\n\n**Percentile Method CI:**\n\n- 95% CI = [2.5th percentile, 97.5th percentile] of bootstrap distribution\n- Example: If you have 1000 estimates, use the 25th and 975th largest values\n\n**Advantages of Bootstrap:**\n\n1. **No distributional assumptions**: Don't need to assume normality\n2. **Works for complex statistics**: Medians, ratios, quantiles, etc.\n3. **Better small-sample coverage**: Often more accurate than asymptotic formulas\n4. **Flexibility**: Can bootstrap residuals, observations, or both\n5. **Visual understanding**: See the actual sampling distribution\n\n**When to use Bootstrap:**\n\n- Small samples (n < 30-50)\n- Non-standard statistics (beyond means and coefficients)\n- Skewed or heavy-tailed distributions\n- Checking robustness of standard inference\n- When asymptotic formulas are complex or unavailable\n\n**Limitations:**\n\n- Computationally intensive (need B = 1000+ replications)\n- Requires careful implementation (stratification, cluster bootstrap)\n- May fail with very small samples (n < 10)\n- Assumes sample is representative of population\n\n**Bootstrap vs. Robust SEs:**\n\nBoth address uncertainty, but differently:\n\n- **Robust SEs**: Analytical correction for heteroskedasticity/autocorrelation\n- **Bootstrap**: Computational approach using resampling\n\nOften used together: Bootstrap with robust methods!\n\n**Practical Implementation Tips:**\n\n1. Use B ≥ 1000 for confidence intervals\n2. Set random seed for reproducibility\n3. For time series: Use block bootstrap (resample blocks, not individuals)\n4. For panel data: Use cluster bootstrap (resample clusters)\n5. Check convergence: Results shouldn't change much with different seeds\n\n::: {#748c2361 .cell execution_count=11}\n``` {.python .cell-code}\n# 12.4 NONREPRESENTATIVE SAMPLES\n\n# Key: sample selection can bias estimates; always verify representativeness\n```\n:::\n\n\n> **Key Concept 12.5: Sample Selection Bias**\n>\n> If the sample is not representative of the population, OLS estimates may be biased. Selection on the dependent variable $Y$ (e.g., studying only high earners) is particularly problematic. Selection on the regressors $X$ (e.g., studying only college graduates) is less harmful because it reduces precision but doesn't necessarily bias coefficient estimates.\n\n### The Type I vs. Type II Error Tradeoff\n\n**Understanding the Table:**\n\nThe 2×2 decision table reveals a fundamental tradeoff in hypothesis testing:\n\n| Decision | H₀ True | H₀ False |\n|----------|---------|----------|\n| Reject H₀ | **Type I error (α)** | **Correct (Power)** |\n| Don't reject | Correct (1-α) | **Type II error (β)** |\n\n**Type I Error (False Positive):**\n\n- Reject a true null hypothesis\n- Probability = significance level α (we control this)\n- Example: Conclude a drug works when it doesn't\n- **\"Seeing patterns in noise\"**\n\n**Type II Error (False Negative):**\n\n- Fail to reject a false null hypothesis \n- Probability = β (harder to control)\n- Example: Miss a real drug effect\n- **\"Missing real signals\"**\n\n**The Fundamental Tradeoff:**\n\nIf we make the test **stricter** (lower α):\n\n- Fewer false positives (Type I errors)\n- More false negatives (Type II errors)\n- Lower power (harder to detect real effects)\n\nIf we make the test **looser** (higher α):\n\n- Higher power (easier to detect real effects)\n- More false positives (Type I errors)\n\n**Statistical Power = 1 - β:**\n\n- Probability of correctly rejecting false H₀\n- \"Sensitivity\" of the test\n- Want power ≥ 0.80 (80% chance of detecting real effect)\n\n**What Affects Power?**\n\n1. **Sample size (n)**: Larger n → Higher power\n2. **Effect size (β)**: Larger true effect → Higher power\n3. **Significance level (α)**: Higher α → Higher power (but more Type I errors)\n4. **Noise level (σ)**: Lower σ → Higher power\n\n**The Power Function:**\n\nPower depends on the **true parameter value**:\n\n- At β = 0 (H₀ true): Power = α (just Type I error rate)\n- As |β| increases: Power increases\n- For very large |β|: Power → 1 (almost certain detection)\n\n**Multiple Testing Problem:**\n\nTesting k hypotheses at α = 0.05:\n\n- Expected false positives = 0.05 × k\n- Test 20 hypotheses → expect 1 false positive even if all H₀ are true!\n\n**Solutions:**\n\n1. **Bonferroni correction**: Use α/k for each test (conservative)\n2. **False Discovery Rate (FDR)**: Control proportion of false positives\n3. **Pre-registration**: Specify primary hypotheses before seeing data\n4. **Replication**: Confirm findings in independent samples\n\nNow that we understand how sample selection affects estimates, let's consider what happens when we seek the most efficient estimator.\n\n## 12.5: Best Estimation Methods\n\n**When are OLS estimators \"best\"?**\n\nUnder classical assumptions 1-4, OLS is **BLUE** (Best Linear Unbiased Estimator) by the Gauss-Markov Theorem.\n\n**When assumptions fail:**\n\n**1. Heteroskedasticity**: $Var[u_i | X] = \\sigma_i^2$ (varies)\n\n- OLS remains unbiased but inefficient\n- **Feasible GLS (FGLS)** or **Weighted Least Squares (WLS)** more efficient\n- Weight observations inversely to error variance: $w_i = 1/\\sigma_i$\n\n**2. Autocorrelation**: $Cov[u_t, u_{t-s}] \\neq 0$\n\n- OLS remains unbiased but inefficient\n- **FGLS with AR errors** more efficient\n- Model error structure: $u_t = \\rho u_{t-1} + \\epsilon_t$\n\n**Practical advice**:\n\n- Most applied work uses OLS with robust SEs\n- Efficiency gains from GLS/FGLS often modest\n- Misspecifying error structure can make things worse\n- Exception: Panel data methods explicitly model error components\n\n### Reading the Power Curve: What It Tells Us\n\n**Interpreting Figure 12.3:**\n\nThe power function shows how test power varies with the true coefficient value. Here's what each feature means:\n\n**Key Features of the Curve:**\n\n1. **At β = 0 (vertical gray line)**:\n - Power = α = 0.05\n - This is the Type I error rate\n - When H₀ is true, we reject 5% of the time (false positives)\n\n2. **As |β| increases (moving away from 0)**:\n - Power increases rapidly\n - Larger effects are easier to detect\n - Curve approaches 1.0 (certain detection)\n\n3. **Symmetry around zero**:\n - Power is same for β = 30 and β = -30\n - Two-sided test treats positive and negative effects equally\n - One-sided tests would have asymmetric power\n\n4. **The 0.80 threshold (green dashed line)**:\n - Standard target: 80% power\n - Means 20% chance of Type II error (β = 0.20)\n - In this example: Need |β| ≈ 30 to achieve 80% power\n\n**What This Means for Study Design:**\n\nGiven the parameters (n=30, SE=15, α=0.05):\n\n- **Small effects** (|β| < 15):\n - Power < 50%\n - More likely to **miss** the effect than detect it\n - Study is underpowered\n\n- **Medium effects** (|β| ≈ 30):\n - Power ≈ 80%\n - Good chance of detection\n - Standard benchmark for adequate power\n\n- **Large effects** (|β| > 45):\n - Power > 95%\n - Almost certain detection\n - Study is well-powered\n\n**Sample Size Implications:**\n\nTo detect smaller effects, you need larger samples:\n\n- **Double the sample** (n=60) → Can detect smaller effects with same power\n- Power roughly proportional to √n\n- To halve minimum detectable effect, need **4× the sample size**\n\n**The Power-Sample Size Relationship:**\n\nFor a given effect size β:\n\n- Power increases with √n\n- To go from 50% to 80% power: Need ≈ 2× the sample\n- To go from 80% to 95% power: Need ≈ 2× the sample again\n\n**Practical Applications:**\n\n1. **Pre-study planning**:\n - Specify minimum effect of interest\n - Calculate required sample size for 80% power\n - Avoid underpowered studies\n\n2. **Post-study interpretation**:\n - Non-significant result with low power: Inconclusive (not evidence of no effect)\n - Non-significant result with high power: Evidence against large effects\n - Significant result: Good, but consider magnitude and practical significance\n\n3. **Publication decisions**:\n - Underpowered studies contribute to publication bias\n - Meta-analyses should weight by precision and power\n - Replication studies should be well-powered\n\n**Common Mistakes to Avoid:**\n\n1. Treating non-significant results as \"proof of no effect\"\n - Non-significance in underpowered study is uninformative\n \n2. Conducting multiple underpowered studies instead of one well-powered study\n - Wastes resources and leads to false negatives\n\n3. Post-hoc power analysis\n - Don't calculate power after seeing results (circular reasoning)\n - Do it before data collection\n\n**The Bottom Line:**\n\nThis power curve illustrates a fundamental truth:\n\n- **Smaller effects require larger samples to detect**\n- With n=30 and SE=15, we can reliably detect effects of |β| ≥ 30\n- For smaller effects, we'd need more data or reduced noise (lower σ)\n\n::: {#a8b7fbfc .cell execution_count=12}\n``` {.python .cell-code}\n# 12.5 BEST ESTIMATION METHODS\n\nprint(\"\\nKey concepts:\")\nprint(\"\\n1. Gauss-Markov Theorem:\")\n# Under assumptions 1-4, OLS is BLUE\n# BLUE = Best Linear Unbiased Estimator\n# 'Best' = minimum variance among linear unbiased estimators\n\nprint(\"\\n2. When assumptions fail:\")\n# Heteroskedasticity → Weighted Least Squares (WLS)\n# Autocorrelation → GLS with AR errors\n# Both → Feasible GLS (FGLS)\n\nprint(\"\\n3. Practical considerations:\")\n# Efficiency gains often modest in practice\n# Misspecification of error structure can worsen estimates\n# Most studies use OLS + robust SEs (simpler, more robust)\n# Exception: Panel data methods model error components explicitly\n\nprint(\"\\n4. Maximum Likelihood:\")\n# If error distribution fully specified (e.g., normal)\n# MLE can be more efficient than OLS\n# Under normality, MLE = OLS for linear regression\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nKey concepts:\n\n1. Gauss-Markov Theorem:\n\n2. When assumptions fail:\n\n3. Practical considerations:\n\n4. Maximum Likelihood:\n```\n:::\n:::\n\n\n> **Key Concept 12.6: Feasible Generalized Least Squares**\n>\n> When error variance is not constant (heteroskedasticity) or errors are correlated (autocorrelation), OLS remains unbiased but is no longer the most efficient estimator. Feasible GLS (FGLS) models the error structure and can achieve lower variance. However, FGLS requires correctly specifying the error structure — in practice, OLS with robust SEs is preferred for its simplicity and robustness to misspecification.\n\n## 12.6: Best Confidence Intervals\n\n**What makes a confidence interval \"best\"?**\n\nA 95% CI is \"best\" if it:\n\n1. Has correct coverage: Contains true parameter 95% of the time\n2. Has minimum width among all CIs with correct coverage\n\n**Standard approach**: $\\hat{\\beta}_j \\pm t_{n-k, \\alpha/2} \\times se(\\hat{\\beta}_j)$\n\n- Width determined by $se(\\hat{\\beta}_j)$\n- Shortest CI comes from most efficient estimator\n\n**Alternative approaches**:\n\n**1. Bootstrap confidence intervals**\n\n- Resample data many times (e.g., 1000 replications)\n- Re-estimate model for each resample\n- Use distribution of bootstrap estimates\n- Percentile method: 2.5th and 97.5th percentiles\n- Advantages: No distributional assumptions, works for complex statistics\n\n**2. Bayesian credible intervals**\n\n- Based on posterior distribution\n- Direct probability interpretation\n- Incorporates prior information\n\n**When assumptions fail**:\n\n- Use robust SEs → wider but valid intervals\n- Bootstrap → more accurate coverage in small samples\n- Asymptotic approximations may be poor in small samples\n\n> **Key Concept 12.7: Bootstrap Confidence Intervals**\n>\n> The bootstrap resamples the original data (with replacement) many times to estimate the sampling distribution of a statistic. Bootstrap CIs don't rely on normality or large-sample approximations, making them especially useful with small samples, skewed distributions, or non-standard estimators where analytical formulas aren't available.\n\nHaving discussed the best confidence intervals, we now examine what makes a hypothesis test optimal — balancing Type I and Type II errors.\n\n## 12.7: Best Tests\n\n**Type I and Type II errors**:\n\n| Decision | $H_0$ True | $H_0$ False |\n|----------|------------|-------------|\n| Reject $H_0$ | Type I error (α) | Correct |\n| Don't reject | Correct | Type II error (β) |\n\n**Type I error** (false positive):\n\n- Reject $H_0$ when it's true\n- Probability = significance level α (e.g., 0.05)\n- We control this directly\n\n**Type II error** (false negative):\n\n- Fail to reject $H_0$ when it's false\n- Probability = β\n- Harder to control\n\n**Test power** = 1 - β\n\n- Probability of correctly rejecting false $H_0$\n- Higher power is better\n\n**Trade-off**:\n\n- Decreasing α (stricter test) → increases β (lower power)\n- Solution: Fix α, maximize power\n\n**Most powerful test**:\n\n- Among all tests with size α, has highest power\n- For linear regression: Use most efficient estimator\n\n**The Trinity of Tests** (asymptotically equivalent):\n\n1. **Wald test**: Based on unrestricted estimates\n2. **Likelihood Ratio (LR) test**: Compares likelihoods\n3. **Lagrange Multiplier (LM) test**: Based on restricted estimates\n\n**Multiple testing**:\n\n- Testing many hypotheses inflates Type I error\n- Solutions: Bonferroni correction, FDR control\n\n### Illustration: Power of a Test\n\nLet's visualize how test power depends on the true effect size.\n\n> **Key Concept 12.8: Type I and Type II Errors**\n>\n> Type I error (false positive) means rejecting a true $H_0$; its probability equals the significance level $\\alpha$. Type II error (false negative) means failing to reject a false $H_0$. Power = $1 - P(\\text{Type II})$ measures the ability to detect true effects. The most powerful test for a given size uses the most precise estimator — another reason efficient estimation matters beyond point estimates.\n\n## Key Takeaways\n\n**Robust Standard Errors:**\n\n- When error variance is non-constant, default SEs are invalid — use heteroskedastic-robust (HC1) SEs for cross-sectional data\n- With grouped observations, use cluster-robust SEs with $G-1$ degrees of freedom (not $N-k$)\n- For time series with autocorrelated errors, use HAC (Newey-West) SEs with lag length $m \\approx 0.75 \\times T^{1/3}$\n- Coefficient estimates are unchanged; only SEs, $t$-statistics, and CIs change\n\n**Prediction:**\n\n- Predicting the conditional mean $E[y|x^*]$ is more precise than predicting an individual outcome $y|x^*$\n- Forecast variance = conditional mean variance + $\\text{Var}(u^*)$, so prediction intervals are always wider\n- Even with precise coefficients, individual forecasts are imprecise because we cannot predict $u^*$\n- Policy decisions should be based on average outcomes (precise) rather than individual predictions (imprecise)\n\n**Nonrepresentative Samples:**\n\n- Sample selection on $Y$ can bias OLS estimates; selection on $X$ is less harmful\n- Survey weights can adjust for known selection, but unknown selection remains problematic\n\n**Best Estimation:**\n\n- Under correct assumptions, OLS is BLUE (Gauss-Markov); when assumptions fail, FGLS is more efficient\n- In practice, most studies use OLS with robust SEs — accepting a small efficiency loss for simplicity\n\n**Best Confidence Intervals:**\n\n- Bootstrap methods resample the data to estimate the sampling distribution without relying on normality\n- Particularly useful with small samples or non-normal errors\n\n**Best Tests:**\n\n- Type I error = false positive (rejecting true $H_0$); Type II error = false negative\n- Power = $1 - P(\\text{Type II})$; the most powerful test uses the most precise estimator\n- Higher power comes from larger samples, more variation in regressors, and lower noise\n\n**Python tools used:** `statsmodels` (OLS, HC1, `get_prediction()`), `scipy.stats` (distributions), `matplotlib`/`seaborn` (correlograms, prediction plots)\n\n**Next steps:** Chapter 13 introduces **dummy variables** and **indicator variables** — extending regression to handle qualitative explanatory variables.\n\nCongratulations on completing Chapter 12! You now understand advanced inference methods for handling real-world data challenges.\n\n## Practice Exercises\n\nTest your understanding of advanced inference topics.\n\n---\n\n**Exercise 1: Choosing Standard Errors**\n\nFor each scenario, identify the appropriate type of standard errors:\n\na) Cross-sectional survey of 500 households with varying income levels.\n\nb) Panel data on 50 schools over 10 years, where student outcomes within a school are correlated.\n\nc) Monthly GDP growth data for 20 years, where this quarter's shock affects next quarter.\n\nd) A randomized experiment with 200 independent observations and constant error variance.\n\n---\n\n**Exercise 2: Point Prediction**\n\nA fitted regression model gives $\\widehat{y} = 10 + 2x_2 + 3x_3$ with $n = 200$ and $s_e = 2.0$.\n\na) Predict $y$ when $x_2 = 5$ and $x_3 = 3$.\n\nb) Is this a prediction of the conditional mean or an individual outcome?\n\n---\n\n**Exercise 3: Conditional Mean CI**\n\nUsing the model from Exercise 2, suppose $se(\\widehat{y}_{cm}) = 0.8$ at $x_2 = 5, x_3 = 3$.\n\na) Construct an approximate 95% confidence interval for $E[y|x_2=5, x_3=3]$.\n\nb) How would this interval change if the sample size doubled (assume SE shrinks by $\\sqrt{2}$)?\n\n---\n\n**Exercise 4: Individual Forecast CI**\n\nContinuing from Exercise 3, construct a 95% prediction interval for an individual $y$ at $x_2 = 5, x_3 = 3$.\n\na) Compute $se(\\widehat{y}_f) = \\sqrt{se(\\widehat{y}_{cm})^2 + s_e^2}$.\n\nb) Construct the prediction interval.\n\nc) Why is this interval so much wider than the confidence interval for the conditional mean?\n\n---\n\n**Exercise 5: Robust vs. Default Inference**\n\nA regression yields the following results:\n\n| Variable | Coefficient | Default SE | Robust SE |\n|----------|------------|-----------|----------|\n| $x_2$ | 5.0 | 2.0 | 3.5 |\n| $x_3$ | 7.0 | 2.0 | 1.8 |\n\na) Compute the $t$-statistic for each variable using default and robust SEs.\n\nb) At $\\alpha = 0.05$, which variables are significant under each type of SE?\n\nc) What does the change in SEs suggest about heteroskedasticity?\n\n---\n\n**Exercise 6: Type I/II Error Tradeoff**\n\nA researcher tests $H_0: \\beta = 0$ at three significance levels: $\\alpha = 0.01, 0.05, 0.10$.\n\na) As $\\alpha$ decreases, what happens to the probability of Type I error?\n\nb) As $\\alpha$ decreases, what happens to the probability of Type II error?\n\nc) If it's very costly to miss a true effect (high cost of Type II error), should you use a smaller or larger $\\alpha$? Explain.\n\n## Case Studies\n\n### Case Study 1: Robust Inference for Cross-Country Productivity\n\nIn this case study, you will apply robust inference methods to cross-country productivity data. You'll compare default and robust standard errors, make predictions for specific countries, and assess how methodological choices affect conclusions about productivity determinants.\n\n**Dataset:** Mendez Convergence Clubs Data\n\n- **Source:** Mendez (2020), 108 countries, 1990-2014\n- **Key variables:**\n  - `lp` — Labor productivity (GDP per worker)\n  - `rk` — Physical capital per worker\n  - `hc` — Human capital index\n  - `region` — Geographic region (for clustering)\n\n**Research question:** Do conclusions about productivity determinants change when using robust standard errors? How precisely can we predict productivity for a specific country?\n\n```python\n# Load the Mendez convergence clubs dataset\nurl = \"https://raw.githubusercontent.com/quarcs-lab/mendez2020-convergence-clubs-code-data/master/assets/dat.csv\"\ndat = pd.read_csv(url)\ndat_2014 = dat[dat['year'] == 2014].dropna(subset=['lp', 'rk', 'hc']).copy()\ndat_2014['ln_lp'] = np.log(dat_2014['lp'])\ndat_2014['ln_rk'] = np.log(dat_2014['rk'])\nprint(f\"Cross-section sample: {len(dat_2014)} countries (year 2014)\")\n```\n\n#### Task 1: Default vs. Robust Standard Errors (Guided)\n\nCompare default and heteroskedastic-robust standard errors.\n\n```python\n# Estimate model with default SEs\nmodel = ols('ln_lp ~ ln_rk + hc', data=dat_2014).fit()\nprint(\"Default SEs:\")\nmodel.summary()\n\n# Estimate with HC1 robust SEs\nmodel_robust = model.get_robustcov_results(cov_type='HC1')\nprint(\"\\nRobust SEs:\")\nmodel_robust.summary()\n```\n\n**Questions:**\n\n- How do the standard errors change? Which variables are affected most?\n- Do any significance conclusions change between default and robust SEs?\n\n#### Task 2: Cluster-Robust SEs by Region (Guided)\n\nEstimate with cluster-robust standard errors grouped by geographic region.\n\n```python\n# Cluster-robust SEs by region\nmodel_cluster = model.get_robustcov_results(cov_type='cluster', groups=dat_2014['region'])\nprint(\"Cluster-Robust SEs (by region):\")\nmodel_cluster.summary()\n\n# Compare all three SE types\nprint(\"\\nSE Comparison:\")\nfor var in ['Intercept', 'ln_rk', 'hc']:\n    print(f\"  {var}: Default={model.bse[var]:.4f}, HC1={model_robust.bse[var]:.4f}, Cluster={model_cluster.bse[var]:.4f}\")\n```\n\n**Questions:**\n\n- Are cluster-robust SEs larger or smaller than HC1 SEs? Why?\n- How many clusters (regions) are there? Is this enough for reliable cluster-robust inference?\n\n> **Key Concept 12.9: Choosing the Right Standard Errors**\n>\n> The choice of standard errors depends on the data structure: HC1 for cross-sectional data with potential heteroskedasticity, cluster-robust when observations are grouped (e.g., countries within regions), and HAC for time series. With cross-country data, cluster-robust SEs by region account for the possibility that countries in the same region share unobserved shocks.\n\n#### Task 3: Predict Conditional Mean (Semi-guided)\n\nPredict average productivity for a country with median capital and human capital values.\n\n```python\n# Get median values\nmedian_ln_rk = dat_2014['ln_rk'].median()\nmedian_hc = dat_2014['hc'].median()\nprint(f\"Median ln(rk) = {median_ln_rk:.3f}, Median hc = {median_hc:.3f}\")\n\n# Predict conditional mean with CI\npred_data = pd.DataFrame({'ln_rk': [median_ln_rk], 'hc': [median_hc]})\npred = model.get_prediction(pred_data)\nprint(pred.summary_frame(alpha=0.05))\n```\n\n**Questions:**\n\n- What is the predicted $\\ln(\\text{lp})$ for a median country? Convert back to levels.\n- How narrow is the 95% CI for the conditional mean?\n\n#### Task 4: Forecast Individual Country (Semi-guided)\n\nConstruct a prediction interval for an individual country's productivity.\n\n```python\n# Get prediction with observation-level interval\npred_frame = pred.summary_frame(alpha=0.05)\nprint(\"Conditional mean CI vs. Prediction interval:\")\nprint(f\"  Mean CI:       [{pred_frame['mean_ci_lower'].values[0]:.3f}, {pred_frame['mean_ci_upper'].values[0]:.3f}]\")\nprint(f\"  Prediction PI: [{pred_frame['obs_ci_lower'].values[0]:.3f}, {pred_frame['obs_ci_upper'].values[0]:.3f}]\")\n```\n\n**Questions:**\n\n- How much wider is the prediction interval compared to the confidence interval?\n- Why can't we predict an individual country's productivity precisely even with good data?\n\n#### Task 5: Model Comparison with Robust Inference (Independent)\n\nCompare nested models using robust inference.\n\n**Your tasks:**\n\n1. Estimate three models: (a) $\\ln(\\text{lp}) \\sim \\ln(\\text{rk})$ only, (b) $\\ln(\\text{lp}) \\sim \\text{hc}$ only, (c) both regressors\n2. For each model, report both default and HC1 robust standard errors\n3. Do the significance conclusions change between default and robust SEs for any model?\n4. Compare prediction interval widths across models — does adding variables improve individual predictions?\n\n*Hint: Use `model.get_robustcov_results(cov_type='HC1')` for robust SEs and `model.get_prediction()` for predictions.*\n\n#### Task 6: Policy Brief on Inference Robustness (Independent)\n\nWrite a 200-300 word policy brief summarizing your findings.\n\n**Your brief should address:**\n\n1. How do conclusions about productivity determinants change with robust standard errors?\n2. What is the practical difference between cluster-robust and HC1 SEs in this context?\n3. How precisely can we predict productivity for a specific country vs. a group of countries?\n4. What recommendations would you make about standard error choices for cross-country studies?\n5. What are the limitations of these inference methods (what don't they fix)?\n\n> **Key Concept 12.10: Robust Methods Don't Fix Everything**\n>\n> Robust standard errors correct for heteroskedasticity and clustering, but they don't address omitted variable bias, reverse causality, or measurement error. A coefficient estimate with a perfectly robust SE is still biased if the model is misspecified. Robust inference ensures valid $p$-values and CIs *conditional on the model being correct* — it's a necessary but not sufficient condition for credible empirical work.\n\n### What You've Learned\n\nIn this case study, you applied advanced inference methods to cross-country productivity data:\n\n- Compared default, heteroskedastic-robust, and cluster-robust standard errors\n- Observed how SE choices affect significance conclusions\n- Predicted conditional means with narrow CIs and individual outcomes with wide PIs\n- Connected robust inference methods to practical policy questions\n\nThese tools ensure your empirical conclusions are reliable under realistic data conditions.\n\n### Case Study 2: Robust Prediction of Municipal Development\n\nIn Chapters 10-11, we estimated multiple regression models predicting municipal development from nighttime lights and satellite embeddings, and tested the statistical significance of these predictors. Now we apply Chapter 12's tools for **robust inference** and **prediction**---crucial for translating satellite models into practical SDG monitoring tools.\n\n**The Data**: The [DS4Bolivia project](https://github.com/quarcs-lab/ds4bolivia) provides a comprehensive dataset covering 339 Bolivian municipalities with over 350 variables, including the Municipal Sustainable Development Index (IMDS), nighttime lights per capita, and 64 satellite embedding dimensions. Here we focus on robust standard errors and prediction intervals for the satellite-development model.\n\n#### Load the DS4Bolivia Data\n\nLet's load the DS4Bolivia dataset and select the key variables for robust inference and prediction analysis.\n\n::: {#51797951 .cell execution_count=13}\n``` {.python .cell-code}\n# Load the DS4Bolivia dataset\nurl_bol = \"https://raw.githubusercontent.com/quarcs-lab/ds4bolivia/master/ds4bolivia_v20250523.csv\"\nbol = pd.read_csv(url_bol)\n\n# Display basic information\n# DS4BOLIVIA DATASET\nprint(f\"Dataset shape: {bol.shape[0]} municipalities, {bol.shape[1]} variables\")\nprint(f\"\\nDepartments: {bol['dep'].nunique()} unique departments\")\nprint(f\"Department names: {sorted(bol['dep'].unique())}\")\n\n# Select key variables for this case study\nkey_vars = ['mun', 'dep', 'imds', 'ln_NTLpc2017',\n            'A00', 'A10', 'A20', 'A30', 'A40']\nbol_key = bol[key_vars].copy()\n\nprint(f\"\\nKey variables selected: {len(key_vars)}\")\n# FIRST 10 MUNICIPALITIES\nbol_key.head(10).to_string()\n\n# Variable descriptions\n# KEY VARIABLE DESCRIPTIONS\ndescriptions = {\n    'mun': 'Municipality name',\n    'dep': 'Department (administrative region, 9 total)',\n    'imds': 'Municipal Sustainable Development Index (0-100, composite of all SDGs)',\n    'ln_NTLpc2017': 'Log of nighttime lights per capita (2017, satellite-based)',\n    'A00-A40': 'Satellite image embedding dimensions (5 of 64 principal features)',\n}\nfor var, desc in descriptions.items():\n    print(f\"  {var:20s} --- {desc}\")\n```\n:::\n\n\n#### Task 1: Default vs Robust Standard Errors (Guided)\n\n**Objective**: Estimate the satellite-development model with both default and HC1 robust standard errors and compare the results.\n\n**Instructions**:\n\n1. Estimate `imds ~ ln_NTLpc2017 + A00 + A10 + A20 + A30 + A40` with default standard errors\n2. Re-estimate with HC1 robust standard errors (`cov_type='HC1'`)\n3. Compare standard errors side-by-side for each coefficient\n4. Identify which coefficients have substantially different SEs under the two methods\n\n**Apply what you learned in section 12.2**: Use `ols().fit()` for default SEs and `ols().fit(cov_type='HC1')` for robust SEs.\n\n::: {#16e65f10 .cell execution_count=14}\n``` {.python .cell-code}\n# Task 1: Default vs Robust Standard Errors\n# ----------------------------------------------------------\n\n# Prepare regression data (drop missing values)\nreg_vars = ['imds', 'ln_NTLpc2017', 'A00', 'A10', 'A20', 'A30', 'A40']\nreg_data = bol_key[reg_vars + ['dep']].dropna()\nprint(f\"Regression sample: {len(reg_data)} municipalities (after dropping missing values)\")\n\n# Estimate with default standard errors\nmodel_default = ols('imds ~ ln_NTLpc2017 + A00 + A10 + A20 + A30 + A40',\n                    data=reg_data).fit()\n\n# Estimate with HC1 robust standard errors\nmodel_hc1 = ols('imds ~ ln_NTLpc2017 + A00 + A10 + A20 + A30 + A40',\n                data=reg_data).fit(cov_type='HC1')\n\n# COMPARISON: DEFAULT vs HC1 ROBUST STANDARD ERRORS\nprint(f\"{'Variable':<18} {'Coef':>10} {'Default SE':>12} {'HC1 SE':>12} {'Ratio':>8}\")\nfor var in model_default.params.index:\n    coef = model_default.params[var]\n    se_def = model_default.bse[var]\n    se_hc1 = model_hc1.bse[var]\n    ratio = se_hc1 / se_def\n    print(f\"{var:<18} {coef:>10.4f} {se_def:>12.4f} {se_hc1:>12.4f} {ratio:>8.3f}\")\n\nprint(f\"\\nR-squared: {model_default.rsquared:.4f}\")\nprint(f\"Adj. R-squared: {model_default.rsquared_adj:.4f}\")\nprint(f\"\\nNote: Coefficients are identical --- only SEs change.\")\nprint(\"Ratios > 1 suggest heteroskedasticity inflates default SEs' precision.\")\n```\n:::\n\n\n#### Task 2: Cluster-Robust Standard Errors by Department (Guided)\n\n**Objective**: Re-estimate the model with cluster-robust standard errors grouped by department.\n\n**Instructions**:\n\n1. Re-estimate using `cov_type='cluster'` with `cov_kwds={'groups': reg_data['dep']}`\n2. Compare cluster-robust SEs with default and HC1 SEs\n3. Discuss: Why might municipalities within a department share unobserved characteristics?\n\n**Apply what you learned in section 12.2**: Cluster-robust SEs account for within-group correlation of errors.\n\n::: {#9904be5c .cell execution_count=15}\n``` {.python .cell-code}\n# Task 2: Cluster-Robust Standard Errors by Department\n# ----------------------------------------------------------\n\n# Estimate with cluster-robust SEs by department\nmodel_cluster = ols('imds ~ ln_NTLpc2017 + A00 + A10 + A20 + A30 + A40',\n                    data=reg_data).fit(cov_type='cluster',\n                                      cov_kwds={'groups': reg_data['dep']})\n\n# COMPARISON: DEFAULT vs HC1 vs CLUSTER-ROBUST STANDARD ERRORS\nprint(f\"{'Variable':<18} {'Coef':>10} {'Default SE':>12} {'HC1 SE':>12} {'Cluster SE':>12}\")\nfor var in model_default.params.index:\n    coef = model_default.params[var]\n    se_def = model_default.bse[var]\n    se_hc1 = model_hc1.bse[var]\n    se_clust = model_cluster.bse[var]\n    print(f\"{var:<18} {coef:>10.4f} {se_def:>12.4f} {se_hc1:>12.4f} {se_clust:>12.4f}\")\n\nn_clusters = reg_data['dep'].nunique()\nprint(f\"\\nNumber of clusters (departments): {n_clusters}\")\nprint(f\"Municipalities per department (avg): {len(reg_data) / n_clusters:.0f}\")\n```\n:::\n\n\n> **Key Concept 12.11: Clustered Observations in Spatial Data**\n>\n> Municipalities within the same department share geographic, institutional, and cultural characteristics that create **within-cluster correlation**. Standard OLS assumes independent errors, but when municipalities in La Paz share unobserved factors that affect development, their errors are correlated. Cluster-robust standard errors account for this correlation, typically producing *larger* SEs than default or HC1, reflecting the reduced effective sample size.\n\n#### Task 3: Predict Conditional Mean (Semi-guided)\n\n**Objective**: Use `model.get_prediction()` to predict average IMDS for a municipality with median values of all predictors.\n\n**Instructions**:\n\n1. Calculate the median value of each predictor variable\n2. Use `model_default.get_prediction()` to predict IMDS at the median predictor values\n3. Report the predicted value and its 95% confidence interval\n4. Interpret: \"For a typical municipality, we predict IMDS between X and Y\"\n\n**Apply what you learned in section 12.3**: The confidence interval for the conditional mean reflects estimation uncertainty only.\n\n::: {#8aa0ac69 .cell execution_count=16}\n``` {.python .cell-code}\n# Task 3: Predict Conditional Mean\n# ----------------------------------------------------------\n\n# Your code here: Predict IMDS for a municipality with median predictor values\n#\n# Steps:\n# 1. Calculate median values for each predictor\n# 2. Create a DataFrame with those values\n# 3. Use model_default.get_prediction() to get prediction and CI\n# 4. Report and interpret\n\n# Example structure:\n# pred_vars = ['ln_NTLpc2017', 'A00', 'A10', 'A20', 'A30', 'A40']\n# median_vals = reg_data[pred_vars].median()\n# pred_data = pd.DataFrame([median_vals])\n#\n# pred = model_default.get_prediction(pred_data)\n# pred_frame = pred.summary_frame(alpha=0.05)\n# print(pred_frame)\n#\n# print(f\"\\nPredicted IMDS: {pred_frame['mean'].values[0]:.2f}\")\n# print(f\"95% CI for E[IMDS|X]: [{pred_frame['mean_ci_lower'].values[0]:.2f}, \"\n#       f\"{pred_frame['mean_ci_upper'].values[0]:.2f}]\")\n# print(f\"\\nInterpretation: For a typical municipality with median predictor\")\n# print(f\"values, we predict average IMDS between \"\n#       f\"{pred_frame['mean_ci_lower'].values[0]:.1f} and \"\n#       f\"{pred_frame['mean_ci_upper'].values[0]:.1f}.\")\n```\n:::\n\n\n#### Task 4: Prediction Interval for an Individual Municipality (Semi-guided)\n\n**Objective**: Compute the 95% prediction interval for an *individual* municipality (not just the mean) and compare it with the confidence interval.\n\n**Instructions**:\n\n1. Use `model_default.get_prediction(...).summary_frame(alpha=0.05)` at the same median predictor values\n2. Report the prediction interval using `obs_ci_lower` and `obs_ci_upper`\n3. Compare the width of the prediction interval with the confidence interval from Task 3\n4. Explain why the prediction interval is wider\n\n**Apply what you learned in section 12.3**: Individual predictions must account for the irreducible error $u^*$, making them fundamentally less precise than conditional mean predictions.\n\n::: {#77f05044 .cell execution_count=17}\n``` {.python .cell-code}\n# Task 4: Prediction Interval for an Individual Municipality\n# ----------------------------------------------------------\n\n# Your code here: Compute prediction interval and compare with CI\n#\n# Steps:\n# 1. Use the same prediction from Task 3\n# 2. Extract obs_ci_lower and obs_ci_upper for the prediction interval\n# 3. Compare widths\n# 4. Discuss why PI is wider\n\n# Example structure:\n# pred_vars = ['ln_NTLpc2017', 'A00', 'A10', 'A20', 'A30', 'A40']\n# median_vals = reg_data[pred_vars].median()\n# pred_data = pd.DataFrame([median_vals])\n#\n# pred = model_default.get_prediction(pred_data)\n# pred_frame = pred.summary_frame(alpha=0.05)\n#\n# ci_width = pred_frame['mean_ci_upper'].values[0] - pred_frame['mean_ci_lower'].values[0]\n# pi_width = pred_frame['obs_ci_upper'].values[0] - pred_frame['obs_ci_lower'].values[0]\n#\n#\n# print(\"CONFIDENCE INTERVAL vs PREDICTION INTERVAL\")\n#\n# print(f\"Predicted IMDS: {pred_frame['mean'].values[0]:.2f}\")\n# print(f\"\\n95% CI (conditional mean):  [{pred_frame['mean_ci_lower'].values[0]:.2f}, \"\n#       f\"{pred_frame['mean_ci_upper'].values[0]:.2f}]  width = {ci_width:.2f}\")\n# print(f\"95% PI (individual):        [{pred_frame['obs_ci_lower'].values[0]:.2f}, \"\n#       f\"{pred_frame['obs_ci_upper'].values[0]:.2f}]  width = {pi_width:.2f}\")\n# print(f\"\\nPI/CI width ratio: {pi_width / ci_width:.1f}x wider\")\n# print(f\"\\nThe prediction interval is wider because it includes the\")\n# print(f\"irreducible uncertainty from the individual error term u*.\")\n```\n:::\n\n\n> **Key Concept 12.12: Prediction Uncertainty for SDG Monitoring**\n>\n> Satellite-based prediction models can estimate *average* development patterns with reasonable precision (narrow confidence intervals for the conditional mean). However, predicting development for a *specific municipality* involves much greater uncertainty (wide prediction intervals) because individual municipalities deviate from the average relationship. For SDG monitoring, this means satellite predictions are more reliable for identifying broad patterns than for pinpointing the exact development level of any single municipality.\n\n#### Task 5: Model Robustness Comparison (Independent)\n\n**Objective**: Create a comprehensive comparison table showing coefficient estimates and standard errors under three specifications: default, HC1, and cluster-robust.\n\n**Instructions**:\n\n1. Create a formatted comparison table with coefficients, SEs, and significance stars under all three SE specifications\n2. Identify whether any coefficients change sign or statistical significance across specifications\n3. Discuss what the comparison reveals about model reliability\n4. What does stability (or instability) across SE methods tell us about the trustworthiness of our satellite-development model?\n\n**This extends Chapter 12 concepts**: You're systematically assessing how robust your conclusions are to different assumptions about the error structure.\n\n::: {#23291bf6 .cell execution_count=18}\n``` {.python .cell-code}\n# Task 5: Model Robustness Comparison\n# ----------------------------------------------------------\n\n# Your code here: Create comprehensive comparison table\n#\n# Steps:\n# 1. Extract coefficients and SEs from all three models\n# 2. Compute t-statistics and significance levels for each\n# 3. Create a formatted comparison table\n# 4. Identify any changes in sign or significance\n\n# Example structure:\n# def sig_stars(pval):\n#     if pval < 0.01: return '***'\n#     elif pval < 0.05: return '**'\n#     elif pval < 0.10: return '*'\n#     else: return ''\n#\n#\n# print(\"MODEL ROBUSTNESS: COEFFICIENT ESTIMATES AND STANDARD ERRORS\")\n#\n# print(f\"{'Variable':<16} {'Coef':>8} {'SE(Def)':>10} {'SE(HC1)':>10} {'SE(Clust)':>10} \"\n#       f\"{'Sig(D)':>7} {'Sig(H)':>7} {'Sig(C)':>7}\")\n#\n# for var in model_default.params.index:\n#     coef = model_default.params[var]\n#     se_d = model_default.bse[var]\n#     se_h = model_hc1.bse[var]\n#     se_c = model_cluster.bse[var]\n#     sig_d = sig_stars(model_default.pvalues[var])\n#     sig_h = sig_stars(model_hc1.pvalues[var])\n#     sig_c = sig_stars(model_cluster.pvalues[var])\n#     print(f\"{var:<16} {coef:>8.4f} {se_d:>10.4f} {se_h:>10.4f} {se_c:>10.4f} \"\n#           f\"{sig_d:>7} {sig_h:>7} {sig_c:>7}\")\n#\n# print(\"Significance: *** p<0.01, ** p<0.05, * p<0.10\")\n#\n# print(\"\\nDo any coefficients change sign or significance?\")\n# print(\"What does this tell us about model reliability?\")\n```\n:::\n\n\n#### Task 6: Prediction Brief (Independent)\n\n**Objective**: Write a 200-300 word assessment of prediction uncertainty in satellite-based development models.\n\n**Your brief should address:**\n\n1. How much uncertainty exists in satellite-based development predictions?\n2. Are prediction intervals narrow enough to be useful for policy targeting?\n3. How does the confidence interval for the conditional mean compare with the prediction interval for individual municipalities?\n4. What additional data or methods might reduce prediction uncertainty?\n5. Should policymakers rely on satellite predictions for allocating development resources to specific municipalities?\n\n**Connection to Research**: The DS4Bolivia project shows that satellite-based models achieve meaningful but imperfect predictive accuracy. Your analysis quantifies *how much uncertainty* remains and whether it is small enough for practical SDG monitoring applications.\n\n::: {#7002cba8 .cell execution_count=19}\n``` {.python .cell-code}\n# Your code here: Additional analysis for the prediction brief\n#\n# You might want to:\n# 1. Compare prediction intervals at different predictor values\n#    (e.g., low-NTL vs high-NTL municipalities)\n# 2. Calculate how many municipalities fall outside prediction intervals\n# 3. Visualize actual vs predicted IMDS with confidence bands\n#\n# Example structure:\n# # Actual vs predicted comparison\n# reg_data['predicted'] = model_default.predict(reg_data)\n# reg_data['residual'] = reg_data['imds'] - reg_data['predicted']\n#\n#\n# print(\"PREDICTION ACCURACY SUMMARY\")\n#\n# print(f\"RMSE: {np.sqrt(model_default.mse_resid):.2f}\")\n# print(f\"Mean IMDS: {reg_data['imds'].mean():.2f}\")\n# print(f\"RMSE as % of mean: {100 * np.sqrt(model_default.mse_resid) / reg_data['imds'].mean():.1f}%\")\n# print(f\"\\nLargest over-prediction: {reg_data['residual'].min():.2f}\")\n# print(f\"Largest under-prediction: {reg_data['residual'].max():.2f}\")\n```\n:::\n\n\n#### What You've Learned from This Case Study\n\nThrough this analysis of robust inference and prediction for Bolivia's satellite-development model, you've practiced:\n\n- **Robust SE comparison**: Compared default, HC1, and cluster-robust standard errors for the same model\n- **Cluster-robust inference**: Accounted for within-department correlation among municipalities\n- **Conditional mean prediction**: Predicted average IMDS with a narrow 95% confidence interval\n- **Prediction intervals**: Quantified the much larger uncertainty in predicting individual municipalities\n- **Model robustness assessment**: Evaluated whether conclusions change across different SE specifications\n\nThese tools are essential for translating satellite-based models into credible SDG monitoring instruments. Robust inference ensures your significance conclusions hold under realistic data conditions, while prediction intervals honestly communicate the limits of individual-level forecasting.\n\n**Connection to future chapters**: In Chapter 14, we add *indicator variables* for departments to explicitly model regional differences in the satellite-development relationship.\n\n---\n\n**Well done!** You've now applied Chapter 12's advanced inference and prediction tools to the satellite-development model, quantifying both the reliability of your estimates and the precision of your predictions.\n\n",
    "supporting": [
      "ch12_Further_Topics_in_Multiple_Regression_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}