{
  "hash": "2af5dccb4302675d0cd630e0ca9d2272",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 7. Statistical Inference for Bivariate Regression\nexecute:\n  enabled: true\n  warning: false\n---\n\n\n**metricsAI: An Introduction to Econometrics with Python and AI in the Cloud**\n\n*[Carlos Mendez](https://carlos-mendez.org)*\n\n<img src=\"https://raw.githubusercontent.com/quarcs-lab/metricsai/main/images/ch07_visual_summary.jpg\" alt=\"Chapter 07 Visual Summary\" width=\"100%\">\n\nThis notebook provides an interactive introduction to statistical inference for bivariate regression models. All code runs directly in Google Colab without any local setup.\n\n[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/quarcs-lab/metricsai/blob/main/notebooks_colab/ch07_Statistical_Inference_for_Bivariate_Regression.ipynb)\n<div class=\"chapter-resources\">\n<a href=\"https://www.youtube.com/watch?v=iMi1Fa-PYLs\" target=\"_blank\" class=\"resource-btn\">🎬 AI Video</a>\n<a href=\"https://carlos-mendez.my.canva.site/s07-statistical-inference-for-bivariate-regression-pdf\" target=\"_blank\" class=\"resource-btn\">✨ AI Slides</a>\n<a href=\"https://cameron.econ.ucdavis.edu/aed/traedv1_07\" target=\"_blank\" class=\"resource-btn\">📊 Cameron Slides</a>\n<a href=\"https://app.edcafe.ai/quizzes/697866e42f5d08069e04934f\" target=\"_blank\" class=\"resource-btn\">✏️ Quiz</a>\n<a href=\"https://app.edcafe.ai/chatbots/69789f042f5d08069e070885\" target=\"_blank\" class=\"resource-btn\">🤖 AI Tutor</a>\n</div>\n\n\n## Chapter Overview\n\nThis chapter extends statistical inference from univariate to bivariate regression. You'll gain both theoretical understanding and practical skills through hands-on Python examples, learning how to test hypotheses about regression coefficients and construct confidence intervals.\n\n**What you'll learn:**\n\n- The t-statistic for testing hypotheses about regression coefficients\n- Constructing and interpreting confidence intervals for slope parameters\n- Tests of statistical significance (whether a regressor matters)\n- Two-sided hypothesis tests for specific parameter values\n- One-sided directional hypothesis tests\n- Heteroskedasticity-robust standard errors and their importance\n- Economic vs. statistical significance\n\n**Datasets used:**\n\n- **AED_HOUSE.DTA**: House prices and characteristics for 29 houses sold in Central Davis, California in 1999 (price, size, bedrooms, bathrooms, lot size, age)\n\n**Chapter outline:**\n\n- 7.1 Example: House Price and Size\n- 7.2 The t Statistic\n- 7.3 Confidence Intervals\n- 7.4 Tests of Statistical Significance\n- 7.5 Two-Sided Hypothesis Tests\n- 7.6 One-Sided Directional Hypothesis Tests\n- 7.7 Robust Standard Errors\n- 7.8 Case Studies\n- Key Takeaways\n- Practice Exercises\n\n## Setup\n\nFirst, we import the necessary Python packages and configure the environment for reproducibility. All data will stream directly from GitHub.\n\n::: {#d9d2d6d2 .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Setup: Import libraries and configure environment\"}\n# --- Libraries ---\nimport numpy as np                                       # numerical operations\nimport pandas as pd                                      # data manipulation\nimport matplotlib.pyplot as plt                          # plotting\nimport seaborn as sns                                    # statistical visualizations\nimport statsmodels.api as sm                             # statistical models\nfrom statsmodels.formula.api import ols                  # OLS with formula syntax\nfrom scipy import stats                                  # statistical distributions\nfrom statsmodels.stats.sandwich_covariance import cov_hc1  # robust standard errors\nimport random\nimport os\n\n# --- Reproducibility ---\nRANDOM_SEED = 42\nrandom.seed(RANDOM_SEED)\nnp.random.seed(RANDOM_SEED)\nos.environ['PYTHONHASHSEED'] = str(RANDOM_SEED)\n\n# --- Data source ---\nGITHUB_DATA_URL = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/\"\n\n# --- Plotting style (dark theme matching book design) ---\nplt.style.use('dark_background')\nsns.set_style(\"darkgrid\")\nplt.rcParams.update({\n    'axes.facecolor': '#1a2235',\n    'figure.facecolor': '#12162c',\n    'grid.color': '#3a4a6b',\n    'figure.figsize': (10, 6),\n    'text.color': 'white',\n    'axes.labelcolor': 'white',\n    'xtick.color': 'white',\n    'ytick.color': 'white',\n    'axes.edgecolor': '#1a2235',\n})\n\nprint(\"Setup complete! Ready to explore statistical inference for bivariate regression.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSetup complete! Ready to explore statistical inference for bivariate regression.\n```\n:::\n:::\n\n\n## 7.1 Example: House Price and Size\n\nWe begin with a motivating example: the relationship between house price and house size.\n\n**The regression model:**\n\n$$\\text{price} = \\beta_1 + \\beta_2 \\times \\text{size} + u$$\n\nwhere:\n\n- $\\text{price}$ is the house sale price (in thousands of dollars)\n- $\\text{size}$ is the house size (in square feet)\n- $\\beta_2$ is the population slope (price increase per square foot)\n- $b_2$ is the sample estimate of $\\beta_2$\n\n**Key regression output:**\n\n| Variable | Coefficient | Standard Error | t-statistic | p-value | 95% CI |\n|----------|-------------|----------------|-------------|---------|--------|\n| Size | 73.77 | 11.17 | 6.60 | 0.000 | [50.84, 96.70] |\n| Intercept | 115,017.30 | 21,489.36 | 5.35 | 0.000 | [70,924.76, 159,109.8] |\n\n**Interpretation:**\n\n- Each additional square foot increases house price by approximately \\$73.77\n- The standard error (11.17) measures uncertainty in this estimate\n- The t-statistic (6.60) tests whether the effect is statistically significant\n- The 95% confidence interval is [50.84, 96.70]\n\n::: {#d817fff7 .cell execution_count=2}\n``` {.python .cell-code}\n# 7.1 Example: House price and size\ndata_house = pd.read_stata(GITHUB_DATA_URL + 'AED_HOUSE.DTA')\n\n# Data summary\ndata_house.describe()\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>price</th>\n      <th>size</th>\n      <th>bedrooms</th>\n      <th>bathrooms</th>\n      <th>lotsize</th>\n      <th>age</th>\n      <th>monthsold</th>\n      <th>list</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>29.000000</td>\n      <td>29.000000</td>\n      <td>29.000000</td>\n      <td>29.000000</td>\n      <td>29.000000</td>\n      <td>29.000000</td>\n      <td>29.000000</td>\n      <td>29.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>253910.344828</td>\n      <td>1882.758621</td>\n      <td>3.793103</td>\n      <td>2.206897</td>\n      <td>2.137931</td>\n      <td>36.413792</td>\n      <td>5.965517</td>\n      <td>257824.137931</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>37390.710695</td>\n      <td>398.272130</td>\n      <td>0.675030</td>\n      <td>0.341144</td>\n      <td>0.693034</td>\n      <td>7.118975</td>\n      <td>1.679344</td>\n      <td>40860.264099</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>204000.000000</td>\n      <td>1400.000000</td>\n      <td>3.000000</td>\n      <td>2.000000</td>\n      <td>1.000000</td>\n      <td>23.000000</td>\n      <td>3.000000</td>\n      <td>199900.000000</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>233000.000000</td>\n      <td>1600.000000</td>\n      <td>3.000000</td>\n      <td>2.000000</td>\n      <td>2.000000</td>\n      <td>31.000000</td>\n      <td>5.000000</td>\n      <td>239000.000000</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>244000.000000</td>\n      <td>1800.000000</td>\n      <td>4.000000</td>\n      <td>2.000000</td>\n      <td>2.000000</td>\n      <td>35.000000</td>\n      <td>6.000000</td>\n      <td>245000.000000</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>270000.000000</td>\n      <td>2000.000000</td>\n      <td>4.000000</td>\n      <td>2.500000</td>\n      <td>3.000000</td>\n      <td>39.000000</td>\n      <td>7.000000</td>\n      <td>269000.000000</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>375000.000000</td>\n      <td>3300.000000</td>\n      <td>6.000000</td>\n      <td>3.000000</td>\n      <td>3.000000</td>\n      <td>51.000000</td>\n      <td>8.000000</td>\n      <td>386000.000000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Basic Regression: Price on Size\n\nWe estimate the bivariate regression model using ordinary least squares (OLS).\n\n::: {#82643a70 .cell execution_count=3}\n``` {.python .cell-code}\n# Table 7.1 - Basic regression\nmodel_basic = ols('price ~ size', data=data_house).fit()\n\n# Key results\nintercept = model_basic.params['Intercept']\nslope     = model_basic.params['size']\nr_squared = model_basic.rsquared\n\nprint(f\"Estimated equation: price = {intercept:,.2f} + {slope:.2f} x size\")\nprint(f\"Slope: each additional sq ft is associated with ${slope:,.2f} higher price\")\nprint(f\"R-squared: {r_squared:.4f} ({r_squared*100:.1f}% of variation explained)\\n\")\n\n# Full regression output\nmodel_basic.summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEstimated equation: price = 115,017.28 + 73.77 x size\nSlope: each additional sq ft is associated with $73.77 higher price\nR-squared: 0.6175 (61.7% of variation explained)\n\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<table class=\"simpletable\">\n<caption>OLS Regression Results</caption>\n<tr>\n  <th>Dep. Variable:</th>          <td>price</td>      <th>  R-squared:         </th> <td>   0.617</td>\n</tr>\n<tr>\n  <th>Model:</th>                   <td>OLS</td>       <th>  Adj. R-squared:    </th> <td>   0.603</td>\n</tr>\n<tr>\n  <th>Method:</th>             <td>Least Squares</td>  <th>  F-statistic:       </th> <td>   43.58</td>\n</tr>\n<tr>\n  <th>Date:</th>             <td>Sat, 18 Apr 2026</td> <th>  Prob (F-statistic):</th> <td>4.41e-07</td>\n</tr>\n<tr>\n  <th>Time:</th>                 <td>18:41:59</td>     <th>  Log-Likelihood:    </th> <td> -332.05</td>\n</tr>\n<tr>\n  <th>No. Observations:</th>      <td>    29</td>      <th>  AIC:               </th> <td>   668.1</td>\n</tr>\n<tr>\n  <th>Df Residuals:</th>          <td>    27</td>      <th>  BIC:               </th> <td>   670.8</td>\n</tr>\n<tr>\n  <th>Df Model:</th>              <td>     1</td>      <th>                     </th>     <td> </td>   \n</tr>\n<tr>\n  <th>Covariance Type:</th>      <td>nonrobust</td>    <th>                     </th>     <td> </td>   \n</tr>\n</table>\n<table class=\"simpletable\">\n<tr>\n      <td></td>         <th>coef</th>     <th>std err</th>      <th>t</th>      <th>P>|t|</th>  <th>[0.025</th>    <th>0.975]</th>  \n</tr>\n<tr>\n  <th>Intercept</th> <td>  1.15e+05</td> <td> 2.15e+04</td> <td>    5.352</td> <td> 0.000</td> <td> 7.09e+04</td> <td> 1.59e+05</td>\n</tr>\n<tr>\n  <th>size</th>      <td>   73.7710</td> <td>   11.175</td> <td>    6.601</td> <td> 0.000</td> <td>   50.842</td> <td>   96.700</td>\n</tr>\n</table>\n<table class=\"simpletable\">\n<tr>\n  <th>Omnibus:</th>       <td> 0.576</td> <th>  Durbin-Watson:     </th> <td>   1.219</td>\n</tr>\n<tr>\n  <th>Prob(Omnibus):</th> <td> 0.750</td> <th>  Jarque-Bera (JB):  </th> <td>   0.638</td>\n</tr>\n<tr>\n  <th>Skew:</th>          <td>-0.078</td> <th>  Prob(JB):          </th> <td>   0.727</td>\n</tr>\n<tr>\n  <th>Kurtosis:</th>      <td> 2.290</td> <th>  Cond. No.          </th> <td>9.45e+03</td>\n</tr>\n</table><br/><br/>Notes:<br/>[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.<br/>[2] The condition number is large, 9.45e+03. This might indicate that there are<br/>strong multicollinearity or other numerical problems.\n```\n:::\n:::\n\n\n### Coefficient Table\n\nLet's create a clean table showing the key statistics for statistical inference.\n\n::: {#77ce0984 .cell execution_count=4}\n``` {.python .cell-code}\n# Save coefficients in a clean table\ncoef_table = pd.DataFrame({\n    'Coefficient': model_basic.params,\n    'Std. Error': model_basic.bse,\n    't-statistic': model_basic.tvalues,\n    'p-value': model_basic.pvalues\n})\n\n# Coefficient table\ncoef_table\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Coefficient</th>\n      <th>Std. Error</th>\n      <th>t-statistic</th>\n      <th>p-value</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Intercept</th>\n      <td>115017.282609</td>\n      <td>21489.359861</td>\n      <td>5.352290</td>\n      <td>1.183545e-05</td>\n    </tr>\n    <tr>\n      <th>size</th>\n      <td>73.771040</td>\n      <td>11.174911</td>\n      <td>6.601488</td>\n      <td>4.408752e-07</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## 7.2 The t Statistic\n\nThe t-statistic is fundamental to statistical inference in regression.\n\n**Statistical inference problem:**\n\n- **Sample**: $\\hat{y} = b_1 + b_2 x$ where $b_1$ and $b_2$ are least squares estimates\n- **Population**: $E[y|x] = \\beta_1 + \\beta_2 x$ and $y = \\beta_1 + \\beta_2 x + u$\n- **Goal**: Make inferences about the slope parameter $\\beta_2$\n\n**The t-statistic:**\n\n$$T = \\frac{\\text{estimate} - \\text{parameter}}{\\text{standard error}} = \\frac{b_2 - \\beta_2}{se(b_2)} \\sim T(n-2)$$\n\n**Why use the T(n-2) distribution?**\n\nUnder assumptions 1-4:\n\n- $Var[b_2] = \\sigma_u^2 / \\sum_{i=1}^n (x_i - \\bar{x})^2$\n- We don't know $\\sigma_u^2$, so we replace it with $s_e^2 = \\frac{1}{n-2} \\sum_{i=1}^n (y_i - \\hat{y}_i)^2$\n- This introduces additional uncertainty, so we use $T(n-2)$ instead of $N(0,1)$\n\n**Model Assumptions (1-4):**\n\n1. The population model is $y = \\beta_1 + \\beta_2 x + u$\n2. The error has mean zero conditional on x: $E[u_i | x_i] = 0$\n3. The error has constant variance: $Var[u_i | x_i] = \\sigma_u^2$\n4. The errors are statistically independent: $u_i$ independent of $u_j$\n\n### Understanding Standard Errors: The Foundation of Inference\n\n**What is a standard error?**\n\nThe standard error measures the uncertainty in our estimate. It answers: \"If we repeatedly sampled from the population and computed b₂ each time, how much would b₂ vary across samples?\"\n\n**Key distinction:**\n\n- **Standard deviation**: Variability of individual observations (data spread)\n- **Standard error**: Variability of the estimate across samples (estimation uncertainty)\n\n**Formula for SE of the slope:**\n\n$$se(b_2) = \\frac{\\sigma_u}{\\sqrt{\\sum_{i=1}^n (x_i - \\bar{x})^2}} = \\frac{\\sigma_u}{\\sqrt{n} \\cdot \\sigma_x}$$\n\nwhere:\n\n- σ_u = standard deviation of the error term\n- σ_x = standard deviation of x\n- n = sample size\n\n**What affects the standard error?**\n\n**1. Error variance (σ²_u): Larger σ_u → Larger SE**\n\n- More unexplained variation in y\n- Data points farther from regression line\n- Less precise estimates\n\n**2. Sample size (n): Larger n → Smaller SE**\n\n- More data reduces uncertainty\n- SE decreases at rate 1/√n\n- Quadruple n to halve SE\n\n**3. Variation in x (σ_x): Larger σ_x → Smaller SE**\n\n- More spread in x provides more information\n- Extreme x values help identify the slope\n- Concentrated x values give less precision\n\n**Intuition:**\n\nThink of the regression line as a seesaw balanced at (x̄, ȳ):\n\n- With wide spread in x: Small changes in slope make big differences at the extremes (easy to detect slope)\n- With narrow spread in x: Hard to distinguish different slopes (difficult to detect slope)\n\n**Example calculation for our house price data:**\n\nGiven:\n\n- Sample size: n = 29\n- Standard error of regression: σ_u ≈ 37,000\n- Standard deviation of size: σ_x ≈ 360\n- Estimated SE(b₂) = 37,000 / (√29 × 360) ≈ 19.1\n\n(Actual SE is 11.17, smaller because the relationship is quite strong)\n\n**Why standard errors matter:**\n\n1. **Confidence intervals**: CI = b₂ ± t × SE(b₂)\n2. **Hypothesis tests**: t = (b₂ - β₂⁰) / SE(b₂)\n3. **Practical significance**: Small SE → precise estimate → more reliable\n4. **Study design**: Calculate required n for desired SE\n\n**Relationship to R²:**\n\nHigher R² (better fit) → Smaller σ_u → Smaller SE → More precise estimates\n\nFor our house price example:\n\n- R² = 0.62 (size explains 62% of price variation)\n- This gives relatively small SE\n- If R² were 0.10, SE would be about 2.5 times larger\n\n::: {#a640f53b .cell execution_count=5}\n``` {.python .cell-code}\n# 7.2 The t statistic\nmodel_basic.summary2().tables[1]\n\n# Extract key statistics\ncoef_size = model_basic.params['size']\nse_size = model_basic.bse['size']\nt_stat_size = model_basic.tvalues['size']\np_value_size = model_basic.pvalues['size']\n\n# Detailed statistics for 'size' coefficient\nprint(f\"Coefficient: ${coef_size:.4f}\")\nprint(f\"Standard Error: ${se_size:.4f}\")\nprint(f\"t-statistic: {t_stat_size:.4f}\")\nprint(f\"p-value: {p_value_size:.6f}\")\nprint(f\"t = b₂ / se(b₂) = {coef_size:.4f} / {se_size:.4f} = {t_stat_size:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCoefficient: $73.7710\nStandard Error: $11.1749\nt-statistic: 6.6015\np-value: 0.000000\nt = b₂ / se(b₂) = 73.7710 / 11.1749 = 6.6015\n```\n:::\n:::\n\n\n> **Key Concept 7.1: The t-Distribution and Degrees of Freedom**\n>\n> The **t-distribution** is used for statistical inference when the population variance is unknown (which is always the case in practice). Unlike the standard normal distribution, the t-distribution accounts for the additional uncertainty from estimating the variance.\n>\n> **Key properties:**\n> - Bell-shaped and symmetric (like the normal distribution)\n> - Heavier tails than the normal distribution (more probability in extremes)\n> - Converges to the normal distribution as sample size increases\n> - Characterized by degrees of freedom (df)\n>\n> **Degrees of freedom = n - 2** for bivariate regression:\n> - Start with n observations\n> - Estimate β₁ (intercept): -1 df\n> - Estimate β₂ (slope): -1 df  \n> - Remaining df for estimating variance: n - 2\n>\n> **Practical implication:** For small samples (n < 30), the t-distribution's heavier tails lead to wider confidence intervals and more conservative hypothesis tests compared to the normal distribution. For large samples (n > 100), the difference becomes negligible.\n\n## 7.3 Confidence Intervals\n\nA confidence interval provides a range of plausible values for the population parameter.\n\n**Formula for a \\$100(1-\\alpha)\\%$ confidence interval:**\n\n$$b_2 \\pm t_{n-2, \\alpha/2} \\times se(b_2)$$\n\nwhere:\n\n- $b_2$ is the slope estimate\n- $se(b_2)$ is the standard error of $b_2$\n- $t_{n-2, \\alpha/2}$ is the critical value from Student's t-distribution with $n-2$ degrees of freedom\n\n**95% confidence interval (approximate):**\n\n$$b_2 \\pm 2 \\times se(b_2)$$\n\n**Interpretation:**\n\n- If we repeatedly sampled from the population and constructed 95% CIs, approximately 95% of these intervals would contain the true parameter value $\\beta_2$\n- The calculated 95% CI will correctly include $\\beta_2$ 95% of the time\n\n**Example calculation for house price:**\n\n$$\\begin{aligned}\nb_2 \\pm t_{27, 0.025} \\times se(b_2) &= 73.77 \\pm 2.052 \\times 11.17 \\\\\n&= 73.77 \\pm 22.93 \\\\\n&= [50.84, 96.70]\n\\end{aligned}$$\n\n> **Key Concept 7.2: Interpreting Confidence Intervals**\n>\n> A **confidence interval** provides a range of plausible values for the population parameter. For regression slopes, the 95% CI is:\n>\n> $$b_2 \\pm t_{n-2, 0.025} \\times se(b_2)$$\n>\n> **Common misconceptions:**\n> - WRONG: \"There's a 95% probability that β₂ is in this interval\"\n> - CORRECT: \"If we repeated the sampling process many times, 95% of the constructed intervals would contain β₂\"\n>\n> **Practical interpretation:**\n> - The interval represents our uncertainty about the true parameter value\n> - Wider intervals indicate more uncertainty (large SE, small n, or high variability)\n> - Narrower intervals indicate more precision (small SE, large n, or low variability)\n> - Values inside the interval are \"plausible\" at the chosen confidence level\n> - Values outside the interval would be rejected in a hypothesis test\n>\n> **Relationship to hypothesis testing:** If a null value β₂* falls inside the 95% CI, we fail to reject H₀: β₂ = β₂* at the 5% significance level. This makes CIs more informative than hypothesis tests alone.\n\n### Understanding Confidence Intervals: A Deep Dive\n\n**What is a confidence interval?**\n\nA confidence interval (CI) is NOT a probability statement about the parameter. Instead, it's a statement about the procedure used to construct the interval.\n\n**Common misconceptions:**\n\n **WRONG**: \"There is a 95% probability that β₂ is between 50.84 and 96.70\"\n\n- The parameter β₂ is fixed (not random)\n- The interval either contains β₂ or it doesn't\n\n **CORRECT**: \"If we repeatedly sampled and constructed 95% CIs, approximately 95% of these intervals would contain the true β₂\"\n\n- The randomness is in the sampling process\n- Our particular interval is one realization from this process\n\n**Intuitive explanation:**\n\nImagine conducting 100 different studies using different random samples from the same population:\n\n- Each study estimates β₂ and constructs a 95% CI\n- About 95 of the 100 intervals will contain the true β₂\n- About 5 of the 100 intervals will miss β₂ (just by chance)\n\n**Width of confidence intervals:**\n\nThe CI width depends on three factors:\n\n$$\\text{Width} = 2 \\times t_{n-2, \\alpha/2} \\times se(b_2)$$\n\n1. **Confidence level (1-α)**: Higher confidence → wider interval\n - 90% CI: Narrower (less confident)\n - 95% CI: Standard choice (balance)\n - 99% CI: Wider (more confident)\n\n2. **Sample size (n)**: Larger sample → narrower interval\n - More data reduces uncertainty\n - Critical value t_{n-2, α/2} decreases as n increases\n\n3. **Variability in data**: More scatter → wider interval\n - se(b₂) increases with unexplained variation\n - Tighter relationship → more precise estimates\n\n**Practical use:**\n\nConfidence intervals are more informative than hypothesis tests because they show:\n\n- The point estimate (center of interval)\n- The precision of the estimate (width of interval)\n- All null values that would not be rejected (values inside interval)\n\n::: {#3b746ac5 .cell execution_count=6}\n``` {.python .cell-code}\n# 7.3 Confidence intervals\nconf_int = model_basic.conf_int(alpha=0.05)\n\n# 95% confidence intervals\nconf_int\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>0</th>\n      <th>1</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Intercept</th>\n      <td>70924.758265</td>\n      <td>159109.806952</td>\n    </tr>\n    <tr>\n      <th>size</th>\n      <td>50.842017</td>\n      <td>96.700064</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### The t-Distribution vs Normal Distribution: Why It Matters\n\n**Why not use the normal distribution?**\n\nIn theory, when we know the population variance σ²_u, the test statistic follows a standard normal distribution:\n\n$$Z = \\frac{b_2 - \\beta_2}{\\sigma / \\sqrt{\\sum(x_i - \\bar{x})^2}} \\sim N(0,1)$$\n\n**The problem:** We never know σ_u in practice!\n\n**The solution:** Replace σ_u with its estimate s_e (residual standard error):\n\n$$T = \\frac{b_2 - \\beta_2}{s_e / \\sqrt{\\sum(x_i - \\bar{x})^2}} \\sim T(n-2)$$\n\nThis substitution introduces additional uncertainty, so we use the t-distribution instead of normal.\n\n**Properties of the t-distribution:**\n\n1. **Shape**: Bell-shaped and symmetric (like normal)\n2. **Mean**: 0 (like normal)\n3. **Variance**: df/(df-2) > 1 (heavier tails than normal)\n4. **Degrees of freedom**: n - 2 for bivariate regression\n   - n observations\n   - Minus 2 parameters estimated (β₁ and β₂)\n\n**Key differences from normal:**\n\n| Sample Size | t Critical Value (α=0.05) | z Critical Value | Difference |\n|-------------|---------------------------|------------------|------------|\n| n = 5 (df=3) | 3.182 | 1.96 | +62% |\n| n = 10 (df=8) | 2.306 | 1.96 | +18% |\n| n = 30 (df=28) | 2.048 | 1.96 | +4% |\n| n = 100 (df=98) | 1.984 | 1.96 | +1% |\n| n → ∞ | 1.96 | 1.96 | 0% |\n\n**What this means:**\n\n- **Small samples**: t critical values much larger → wider CIs, harder to reject H₀\n- **Large samples**: t ≈ normal → approximately same inference\n- **Our house data**: n=29, df=27, t(0.025) = 2.052 vs z = 1.96\n\n**Why degrees of freedom = n - 2?**\n\n- Start with n observations\n- Estimate β₁ (intercept): loses 1 df\n- Estimate β₂ (slope): loses 1 df\n- Remaining df for estimating variance: n - 2\n\n**Practical implications:**\n\n**For n = 29 (our house price data):**\n\n- Using normal: 95% CI margin = 1.96 × 11.17 = 21.89\n- Using t(27): 95% CI margin = 2.052 × 11.17 = 22.92\n- Difference: 5% wider with t-distribution (more conservative)\n\n**For n = 10 (small sample):**\n\n- Using normal: 95% CI margin = 1.96 × SE\n- Using t(8): 95% CI margin = 2.306 × SE\n- Difference: 18% wider with t-distribution (much more conservative!)\n\n**Rule of thumb:**\n\n- n < 30: Must use t-distribution\n- 30 ≤ n < 100: Use t-distribution (small difference)\n- n ≥ 100: Normal approximation usually fine, but still use t\n\n**Modern practice:** Statistical software always uses t-distribution (why not? It's correct for any n)\n\n**Visual intuition:**\n\nThe t-distribution has heavier tails:\n\n- More probability in the extremes\n- Less probability near the center\n- This accounts for the uncertainty in estimating σ_u\n- As n increases, estimation uncertainty decreases, and t → normal\n\n### Manual Calculation of Confidence Interval\n\nLet's manually calculate the confidence interval for the size coefficient to understand the mechanics.\n\n::: {#b58a265c .cell execution_count=7}\n``` {.python .cell-code}\n# Manual calculation of confidence interval for size\nn = len(data_house)\ndf = n - 2\n# 0.975 = upper tail for 95% two-sided CI (2.5% in each tail)\nt_crit = stats.t.ppf(0.975, df)\n\nci_lower = coef_size - t_crit * se_size\nci_upper = coef_size + t_crit * se_size\n\n# Manual calculation for 'size' coefficient\nprint(f\"Sample size: {n}\")\nprint(f\"Degrees of freedom: {df}\")\nprint(f\"Critical t-value (α=0.05): {t_crit:.4f}\")\nprint(f\"Margin of error: {t_crit * se_size:.4f}\")\nprint(f\"95% CI: [${ci_lower:.4f}, ${ci_upper:.4f}]\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSample size: 29\nDegrees of freedom: 27\nCritical t-value (α=0.05): 2.0518\nMargin of error: 22.9290\n95% CI: [$50.8420, $96.7001]\n```\n:::\n:::\n\n\n### Example with Artificial Data\n\nTo illustrate the concepts more clearly, let's work with a simple artificial dataset.\n\n## 7.4 Tests of Statistical Significance\n\nA regressor $x$ has no relationship with $y$ if $\\beta_2 = 0$.\n\n**Test of statistical significance** (two-sided test):\n\n$$H_0: \\beta_2 = 0 \\quad \\text{vs.} \\quad H_a: \\beta_2 \\neq 0$$\n\n**Test statistic:**\n\n$$t = \\frac{b_2}{se(b_2)} \\sim T(n-2)$$\n\n**Decision rules:**\n\n1. **p-value approach**: Reject $H_0$ at level $\\alpha$ if $p = Pr[|T_{n-2}| > |t|] < \\alpha$\n\n2. **Critical value approach**: Reject $H_0$ at level $\\alpha$ if $|t| > c = t_{n-2, \\alpha/2}$\n\n**For the house price example:**\n\n- $t = 73.77 / 11.17 = 6.60$\n- $p = Pr[|T_{27}| > 6.60] \\approx 0.000$\n- Critical value: $c = t_{27, 0.025} = 2.052$\n- Since $|t| = 6.60 > 2.052$, reject $H_0$\n- **Conclusion**: House size is statistically significant at the 5% level\n\n> **Key Concept 7.3: The Hypothesis Testing Framework**\n>\n> **Hypothesis testing** is a formal procedure for making decisions about population parameters. The key steps are:\n>\n> **1. State the hypotheses:**\n> - **Null hypothesis (H₀)**: The claim we're testing (usually \"no effect\")\n> - **Alternative hypothesis (Hₐ)**: What we conclude if we reject H₀\n>\n> **2. Choose significance level (α):**\n> - Common choices: 0.10, 0.05, 0.01\n> - α = probability of Type I error (rejecting H₀ when it's true)\n>\n> **3. Calculate test statistic:**\n> - Standardizes the difference: t = (estimate - null value) / SE\n>\n> **4. Determine p-value:**\n> - Probability of observing our result (or more extreme) if H₀ is true\n> - Smaller p-value = stronger evidence against H₀\n>\n> **5. Make decision:**\n> - Reject H₀ if p-value < α\n> - Fail to reject H₀ if p-value ≥ α (never \"accept\" H₀)\n>\n> **Understanding p-values:** If p = 0.001, this means \"if H₀ were true, we'd observe a result this extreme only 0.1% of the time.\" This is strong evidence against H₀.\n\n> **Key Concept 7.4: Statistical vs. Economic Significance**\n>\n> **Statistical significance** and **economic significance** are distinct concepts that answer different questions:\n>\n> **Statistical Significance:**\n> - **Question:** Is the effect different from zero?\n> - **Determined by:** t-statistic = b₂ / se(b₂), which depends on sample size, variability, and effect size\n> - **Interpretation:** We can confidently say the effect exists (not due to chance)\n>\n> **Economic Significance:**\n> - **Question:** Is the effect large enough to matter in practice?\n> - **Determined by:** The magnitude of b₂ and the context\n> - **Interpretation:** The effect has real-world importance\n>\n> **Why they can diverge:**\n> 1. **Large n:** Even tiny effects become statistically significant\n>    - Example: β₂ = \\$0.01 with n = 10,000 might have p < 0.001 but be economically trivial\n> 2. **Small n:** Large effects may not reach statistical significance  \n>    - Example: β₂ = \\$100 with n = 10 might have p = 0.12 but be economically important\n>\n> **Best practice:** Always report both the coefficient estimate (economic magnitude) and the standard error/confidence interval (statistical precision). Focus on confidence intervals, which show both dimensions simultaneously.\n\n> **Key Concept 7.5: One-Sided vs. Two-Sided Tests**\n>\n> The choice between one-sided and two-sided tests depends on your research question:\n>\n> **Two-Sided Test (Most Common):**\n> - H₀: β₂ = β₂* vs. Hₐ: β₂ ≠ β₂*\n> - Detects deviations in either direction\n> - Standard practice in academic research\n> - Rejection region: Both tails of t-distribution\n>\n> **One-Sided Test (Directional):**\n> - Upper: H₀: β₂ ≤ β₂* vs. Hₐ: β₂ > β₂*\n> - Lower: H₀: β₂ ≥ β₂* vs. Hₐ: β₂ < β₂*  \n> - Detects deviations in one specific direction\n> - Rejection region: One tail only\n>\n> **Key relationship:** For the same test statistic, one-sided p-value = (two-sided p-value) / 2 (if sign is correct)\n>\n> **When to use one-sided tests:**\n> - Strong theoretical prediction of direction (before seeing data)\n> - Only care about deviations in one direction\n> - Be cautious: Journals typically require two-sided tests\n>\n> **Important:** If your data contradicts the predicted direction, you cannot reject H₀ with a one-sided test (p-value > 0.5).\n\n::: {#e69507e3 .cell execution_count=8}\n``` {.python .cell-code}\n# Example with artificial data\nx = np.array([1, 2, 3, 4, 5])\ny = np.array([1, 2, 2, 2, 3])\ndf_artificial = pd.DataFrame({'x': x, 'y': y})\n\nmodel_artificial = ols('y ~ x', data=df_artificial).fit()\nmodel_artificial.summary()\n\ncoef_x = model_artificial.params['x']\nse_x = model_artificial.bse['x']\nn_art = len(x)\ndf_art = n_art - 2\nt_crit_art = stats.t.ppf(0.975, df_art)  # 0.975 = upper tail for 95% two-sided CI\n\nci_lower_art = coef_x - t_crit_art * se_x\nci_upper_art = coef_x + t_crit_art * se_x\n\n# Manual CI for artificial data\nprint(f\"Coefficient: {coef_x:.4f}\")\nprint(f\"Standard Error: {se_x:.4f}\")\nprint(f\"95% CI: [{ci_lower_art:.4f}, {ci_upper_art:.4f}]\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCoefficient: 0.4000\nStandard Error: 0.1155\n95% CI: [0.0325, 0.7675]\n```\n:::\n:::\n\n\n### Understanding Hypothesis Testing: The Complete Workflow\n\n**The hypothesis testing framework:**\n\nHypothesis testing is a formal procedure for making decisions about population parameters using sample data.\n\n**Step-by-step workflow:**\n\n**1. State the hypotheses**\n\n   - **Null hypothesis (H₀)**: The claim we're testing (usually \"no effect\")\n   - **Alternative hypothesis (Hₐ)**: What we conclude if we reject H₀\n   - Example: H₀: β₂ = 0 vs Hₐ: β₂ ≠ 0\n\n**2. Choose the significance level (α)**\n\n   - Common choices: 0.10, 0.05, 0.01\n   - α = probability of rejecting H₀ when it's actually true (Type I error)\n   - Convention: α = 0.05 (5% significance level)\n\n**3. Calculate the test statistic**\n\n   - Formula: t = (b₂ - β₂⁰) / se(b₂)\n   - This standardizes the difference between estimate and null value\n   - Under H₀, t follows a t-distribution with n-2 degrees of freedom\n\n**4. Determine the p-value**\n\n   - p-value = probability of observing a test statistic as extreme as ours if H₀ is true\n   - Smaller p-value = stronger evidence against H₀\n   - p-value < α → reject H₀\n\n**5. Make a decision**\n\n   - **Reject H₀**: Strong evidence against the null hypothesis\n   - **Fail to reject H₀**: Insufficient evidence to reject the null\n   - Note: We never \"accept\" H₀, we only fail to reject it\n\n**6. State the conclusion**\n\n   - Translate the statistical decision into plain language\n   - Example: \"House size has a statistically significant effect on price at the 5% level\"\n\n**Understanding p-values:**\n\nThe p-value answers this question: \"If the null hypothesis were true, what is the probability of getting a result at least as extreme as what we observed?\"\n\n**Example interpretation:**\n\n- p = 0.000: If β₂ were truly zero, the probability of getting t ≥ 6.60 is less than 0.1%\n- This is very unlikely, so we have strong evidence against H₀\n\n**Two approaches to hypothesis testing:**\n\n1. **p-value approach**: Reject H₀ if p-value < α\n2. **Critical value approach**: Reject H₀ if |t| > critical value\n\nBoth approaches always give the same conclusion!\n\n**Common significance levels and interpretations:**\n\n| p-value | Interpretation | Strength of Evidence |\n|---------|----------------|---------------------|\n| p > 0.10 | Not significant | Weak/no evidence |\n| 0.05 < p ≤ 0.10 | Marginally significant | Moderate evidence |\n| 0.01 < p ≤ 0.05 | Significant | Strong evidence |\n| p ≤ 0.01 | Highly significant | Very strong evidence |\n\n### Statistical Significance vs Economic Significance\n\nA crucial distinction that is often confused:\n\n**Statistical Significance**\n\n- Answers: \"Is the effect different from zero?\"\n- Depends on: Sample size, variability, effect size\n- Formula: t = b₂ / se(b₂)\n- Interpretation: We can confidently say the effect exists\n\n**Economic Significance**\n\n- Answers: \"Is the effect large enough to matter?\"\n- Depends on: The magnitude of b₂ and context\n- Requires: Domain knowledge and practical judgment\n- Interpretation: The effect has real-world importance\n\n**Key insights:**\n\n**1. Statistical significance ≠ Economic significance**\n\nYou can have:\n\n- Statistically significant but economically trivial effects\n  - Example: With n=10,000, β₂ = 0.001 might be statistically significant but meaningless\n- Economically important but statistically insignificant effects\n  - Example: With n=10, β₂ = 100 might not be statistically significant but potentially important\n\n**2. Sample size matters for statistical significance**\n\n$$t = \\frac{b_2}{se(b_2)} = \\frac{b_2}{\\sigma_u / \\sqrt{\\sum(x_i - \\bar{x})^2}}$$\n\nAs sample size increases:\n\n- The denominator (standard error) decreases\n- The t-statistic increases\n- Small effects become statistically significant\n\n**3. Economic significance requires context**\n\nFor the house price example:\n\n- Statistical result: β₂ = 73.77, highly significant (p < 0.001)\n- Economic interpretation: Each sq ft adds \\$73.77 to price\n- Context matters:\n  - For a 100 sq ft difference: \\$7,377 difference (substantial!)\n  - For a 10 sq ft difference: \\$737.70 difference (moderate)\n  - This is economically meaningful in the housing market\n\n**Practical guidance:**\n\n1. **Always report both**:\n   - The coefficient estimate (economic magnitude)\n   - The p-value or confidence interval (statistical precision)\n\n2. **Focus on confidence intervals**:\n   - Shows both statistical and economic significance\n   - Example: 95% CI = [50.84, 96.70]\n   - Interpretation: Effect is between \\$50.84 and \\$96.70 per sq ft\n   - Even the lower bound is economically meaningful\n\n3. **Consider practical importance**:\n   - Would anyone change their behavior based on this result?\n   - Is the effect large enough to justify policy interventions?\n   - Does the effect matter in real-world terms?\n\n**Example of the distinction:**\n\nSuppose we study the effect of an expensive job training program on wages:\n\n- Statistical result: Training increases wages by \\$0.50/hour (p = 0.001)\n- Statistical significance: YES (highly significant)\n- Economic significance: Questionable\n  - Annual benefit: \\$0.50 × 2000 hours = \\$1,000\n  - If program costs \\$10,000, not worth it\n  - If program costs \\$500, might be worth it\n\n**Bottom line:** Statistical significance tells you the effect exists. Economic significance tells you whether you should care.\n\n### Understanding Two-Sided vs One-Sided Tests\n\n**When to use which test?**\n\nThe choice between two-sided and one-sided tests depends on your research question and what you want to conclude.\n\n**Two-Sided Test (Most Common)**\n\n**Setup:**\n\n- H₀: β₂ = β₂* \n- Hₐ: β₂ ≠ β₂*\n\n**Use when:**\n\n- You want to detect any difference from the null value\n- You don't have a strong prior about the direction\n- You want to be conservative (standard practice in research)\n\n**Rejection region:** Both tails of the distribution\n\n**Example:** Does house size affect price?\n\n- H₀: β₂ = 0 (no effect)\n- Hₐ: β₂ ≠ 0 (some effect, positive or negative)\n- We reject if the effect is either very positive or very negative\n\n**One-Sided Test (Directional)**\n\n**Setup (upper tail):**\n\n- H₀: β₂ ≤ β₂* \n- Hₐ: β₂ > β₂*\n\n**Setup (lower tail):**\n\n- H₀: β₂ ≥ β₂* \n- Hₐ: β₂ < β₂*\n\n**Use when:**\n\n- You have a specific directional hypothesis\n- Economic theory predicts a specific direction\n- You only care about deviations in one direction\n\n**Rejection region:** One tail of the distribution\n\n**Example:** Does house size increase price by less than \\$90/sq ft?\n\n- Claim: β₂ < 90\n- H₀: β₂ ≥ 90 (null is opposite of claim)\n- Hₐ: β₂ < 90 (this is what we want to prove)\n- We only reject if the effect is significantly below 90\n\n**Mathematical relationship:**\n\nFor the same test statistic t:\n\n- Two-sided p-value = 2 × Pr[T > |t|]\n- One-sided p-value = Pr[T > t] (upper tail) or Pr[T < t] (lower tail)\n- One-sided p-value = (Two-sided p-value) / 2 (if sign is correct)\n\n**Important considerations:**\n\n**1. Direction matters for one-sided tests**\n\n- If testing Hₐ: β₂ > β₂* but get b₂ < β₂*, you CANNOT reject H₀\n- The data contradicts your hypothesis, so rejection is impossible\n- In this case, one-sided p-value > 0.5\n\n**2. Two-sided tests are safer**\n\n- Academic journals typically require two-sided tests\n- Avoids \"fishing\" for significant results\n- More conservative approach\n\n**3. One-sided tests have more power**\n\n- For the same significance level α, easier to reject in the predicted direction\n- Critical value is smaller: t(n-2, α) vs t(n-2, α/2)\n- Example: For α = 0.05 and df = 27\n  - Two-sided: t(27, 0.025) = 2.052\n  - One-sided: t(27, 0.05) = 1.703\n\n**Practical example from our house price data:**\n\n**Question 1: Does size affect price? (Two-sided)**\n\n- H₀: β₂ = 0 vs Hₐ: β₂ ≠ 0\n- t = 6.60, p-value = 0.000 (two-sided)\n- Conclusion: Reject H₀, size affects price\n\n**Question 2: Does size increase price? (One-sided)**\n\n- H₀: β₂ ≤ 0 vs Hₐ: β₂ > 0\n- t = 6.60, p-value = 0.000 / 2 = 0.000 (one-sided)\n- Conclusion: Reject H₀, size increases price\n\n**Question 3: Does size increase price by less than \\$90/sq ft? (One-sided)**\n\n- H₀: β₂ ≥ 90 vs Hₐ: β₂ < 90\n- t = (73.77 - 90) / 11.17 = -1.452\n- p-value = 0.079 (one-sided, lower tail)\n- Conclusion: Fail to reject H₀ at α = 0.05 (but would reject at α = 0.10)\n\n**Decision rule:**\n\nUse two-sided tests unless:\n\n1. You have strong theoretical reasons for a directional hypothesis\n2. You specified the direction before seeing the data\n3. You only care about deviations in one direction (rare in economics)\n\n::: {#7f64232d .cell execution_count=9}\n``` {.python .cell-code}\n# 7.4 Tests of statistical significance\n# Null hypothesis: β₂ = 0 (size has no effect on price)\nprint(f\"t-statistic: {t_stat_size:.4f}\")\nprint(f\"p-value: {p_value_size:.6f}\")\nprint(f\"Critical value (α=0.05): ±{t_crit:.4f}\")\n\nif p_value_size < 0.05:\n    print(f\"\\nResult: Reject H₀ at 5% significance level\")\nelse:\n    print(f\"\\nResult: Fail to reject H₀ at 5% significance level\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nt-statistic: 6.6015\np-value: 0.000000\nCritical value (α=0.05): ±2.0518\n\nResult: Reject H₀ at 5% significance level\n```\n:::\n:::\n\n\n> **Key Concept 7.6: Heteroskedasticity and Robust Standard Errors**\n>\n> **Heteroskedasticity** occurs when the error variance is not constant across observations: Var[u_i | x_i] = σ²_i (varies with i).\n>\n> **Homoskedasticity assumption** (Assumption 3): Var[u_i | x_i] = σ²_u (constant)\n>\n> **Why heteroskedasticity matters:**\n> - Coefficient estimates (b₂): Still unbiased \n> - Standard errors: WRONG (biased) \n> - t-statistics, p-values, CIs: All invalid \n>\n> **Solution: Heteroskedasticity-robust standard errors**\n> - Valid whether or not heteroskedasticity exists\n> - No need to test for heteroskedasticity first\n> - Modern best practice for cross-sectional data\n>\n> **Practical impact:**\n> - Robust SEs usually larger → more conservative inference\n> - Protects against false positives (Type I errors)\n> - Sometimes smaller → gain power\n>\n> **Types of robust SEs:**\n> - **HC (Heteroskedasticity-Consistent):** Cross-sectional data\n> - **HAC (Heteroskedasticity and Autocorrelation Consistent):** Time series\n> - **Cluster-robust:** Grouped/clustered data\n>\n> **Bottom line:** Always report heteroskedasticity-robust standard errors for cross-sectional data. They're free insurance against model misspecification.\n\n## 7.5 Two-Sided Hypothesis Tests\n\nSometimes we want to test whether the slope equals a specific non-zero value.\n\n**General two-sided test:**\n\n$$H_0: \\beta_2 = \\beta_2^* \\quad \\text{vs.} \\quad H_a: \\beta_2 \\neq \\beta_2^*$$\n\n**Test statistic:**\n\n$$t = \\frac{b_2 - \\beta_2^*}{se(b_2)} \\sim T(n-2)$$\n\n**Decision rules:**\n\n- **p-value approach**: Reject if $p = Pr[|T_{n-2}| > |t|] < \\alpha$\n- **Critical value approach**: Reject if $|t| > t_{n-2, \\alpha/2}$\n\n**Example**: Test whether house price increases by \\$90 per square foot.\n\n$$t = \\frac{73.77 - 90}{11.17} = -1.452$$\n\n- $p = Pr[|T_{27}| > 1.452] = 0.158$\n- Since $p = 0.158 > 0.05$, do not reject $H_0$\n- **Conclusion**: The data are consistent with $\\beta_2 = 90$\n\n**Relationship to confidence intervals:**\n\n- If $\\beta_2^*$ falls inside the 95% CI, do not reject $H_0$ at 5% level\n- Since 90 is inside [50.84, 96.70], we do not reject\n\n::: {#20559948 .cell execution_count=10}\n``` {.python .cell-code}\n# 7.5 Two-sided hypothesis tests\n# Test H₀: β₂ = 90 vs H₁: β₂ ≠ 90\nnull_value = 90\nt_stat_90 = (coef_size - null_value) / se_size\np_value_90 = 2 * (1 - stats.t.cdf(abs(t_stat_90), df))\nt_crit_90 = stats.t.ppf(0.975, df)  # 0.975 = upper tail for 95% two-sided CI\n\nprint(f\"\\nTest: H₀: β₂ = {null_value} vs H₁: β₂ ≠ {null_value}\")\nprint(f\"  t-statistic: {t_stat_90:.4f}\")\nprint(f\"  p-value: {p_value_90:.6f}\")\nprint(f\"  Critical value (α=0.05): ±{t_crit_90:.4f}\")\n\nif abs(t_stat_90) > t_crit_90:\n    print(f\"\\nResult: Reject H₀ (|t| = {abs(t_stat_90):.4f} > {t_crit_90:.4f})\")\nelse:\n    print(f\"\\nResult: Fail to reject H₀ (|t| = {abs(t_stat_90):.4f} < {t_crit_90:.4f})\")\n    print(f\"Conclusion: The data are consistent with β₂ = {null_value}\")\n\nprint(f\"\\n95% CI for β₂: [{ci_lower:.2f}, {ci_upper:.2f}]\")\nprint(f\"Since {null_value} is inside the CI, we do not reject H₀.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nTest: H₀: β₂ = 90 vs H₁: β₂ ≠ 90\n  t-statistic: -1.4523\n  p-value: 0.157950\n  Critical value (α=0.05): ±2.0518\n\nResult: Fail to reject H₀ (|t| = 1.4523 < 2.0518)\nConclusion: The data are consistent with β₂ = 90\n\n95% CI for β₂: [50.84, 96.70]\nSince 90 is inside the CI, we do not reject H₀.\n```\n:::\n:::\n\n\n### Hypothesis Test Using statsmodels\n\nPython's statsmodels package provides convenient methods for hypothesis testing.\n\n### Why Robust Standard Errors Matter\n\n**The problem with default standard errors:**\n\nDefault (classical) standard errors rely on a strong assumption:\n\n**Assumption 3 (Homoskedasticity):** Var[u_i | x_i] = σ²_u (constant variance)\n\nThis means:\n\n- The spread of errors is the same for all values of x\n- Residuals should have constant variance across fitted values\n- In reality, this assumption is often violated\n\n**What is heteroskedasticity?**\n\n**Heteroskedasticity** means the error variance changes with x:\n\n- Var[u_i | x_i] = σ²_i (varies with i)\n- Common in cross-sectional data\n- Examples:\n - Income variation increases with education level\n - Sales variance increases with firm size\n - Medical costs vary more for older patients\n\n**Visual detection:**\n\nCheck the residual plot (residuals vs fitted values):\n\n- **Homoskedasticity**: Random scatter, constant spread\n- **Heteroskedasticity**: Funnel shape, increasing/decreasing spread\n\n**Consequences of heteroskedasticity:**\n\nIf heteroskedasticity is present but you use default SEs:\n\n1. **Coefficient estimates (b₂)**: Still unbiased and consistent \n2. **Standard errors**: WRONG (biased) \n3. **t-statistics**: WRONG (biased) \n4. **p-values**: WRONG (invalid) \n5. **Confidence intervals**: WRONG (invalid coverage) \n\n**Direction of bias:**\n\n- Heteroskedasticity can cause SEs to be too small or too large\n- Cannot predict direction without knowing the form of heteroskedasticity\n- Could lead to false significance or miss true significance\n\n**The solution: Robust standard errors**\n\n**Heteroskedasticity-robust standard errors** (HC, White, Huber-White):\n\n- Valid whether or not heteroskedasticity is present\n- Automatically adjust for non-constant variance\n- No need to test for heteroskedasticity first\n- Modern best practice: Always use for cross-sectional data\n\n**How they work:**\n\nDefault SE formula (assumes homoskedasticity):\n$$se(b_2) = \\frac{\\sigma_u}{\\sqrt{\\sum(x_i - \\bar{x})^2}}$$\n\nRobust SE formula (allows heteroskedasticity):\n$$se_{robust}(b_2) = \\frac{\\sqrt{\\sum e_i^2 (x_i - \\bar{x})^2}}{\\sum(x_i - \\bar{x})^2}$$\n\nKey difference: Uses individual residuals e²_i instead of pooled variance σ²_u\n\n**Practical implications:**\n\n1. **Coefficient estimates unchanged**\n - Only standard errors change\n - Point estimates remain the same\n\n2. **Standard errors typically larger**\n - Robust SEs are usually (but not always) bigger\n - More conservative inference\n - Wider confidence intervals\n\n3. **t-statistics typically smaller**\n - Less likely to find statistical significance\n - Protects against false positives\n\n4. **Results may change qualitative conclusions**\n - Variable significant with default SEs might become insignificant\n - Or the reverse (if robust SEs are smaller)\n\n**Types of robust standard errors:**\n\nDifferent formulas for finite-sample adjustment:\n\n- **HC0**: Basic White formula\n- **HC1**: Degrees of freedom correction (n/(n-k)), most common in Stata\n- **HC2**: Leverage-weighted\n- **HC3**: Even more conservative\n\n**Python default:** HC1 (matches Stata's \"robust\" option)\n\n**For our house price example:**\n\n| Coefficient | Standard SE | Robust SE | % Change |\n|-------------|-------------|-----------|----------|\n| size | 11.17 | 11.33 | +1.4% |\n| Intercept | 21,489 | 21,825 | +1.6% |\n\n- Difference is small (good news!)\n- Suggests heteroskedasticity is not severe\n- But always report robust SEs as standard practice\n\n**Other types of robust SEs:**\n\n1. **HAC (Heteroskedasticity and Autocorrelation Consistent)**\n - For time series data\n - Accounts for both heteroskedasticity and serial correlation\n\n2. **Cluster-robust**\n - For clustered/grouped data\n - Students within schools, patients within hospitals\n - Accounts for within-cluster correlation\n\n**Best practices:**\n\n1. **Cross-sectional data**: Always use heteroskedasticity-robust SEs\n2. **Time series data**: Use HAC robust SEs (Newey-West)\n3. **Panel/clustered data**: Use cluster-robust SEs\n4. **When in doubt**: Use robust SEs (can't hurt, might help)\n\n**Bottom line:** Robust standard errors provide valid inference under weaker assumptions. They're essentially free insurance against heteroskedasticity.\n\n### Comparing Standard vs Robust Standard Errors: A Practical Guide\n\n**How to interpret the comparison:**\n\nWhen you compute both standard and robust SEs, you're essentially running two different analyses:\n\n**Standard SEs (Classical):**\n\n- Assumes: Homoskedasticity (constant variance)\n- Valid only if: Assumption 3 holds\n- Interpretation: \"If errors have constant variance, here's the uncertainty\"\n\n**Robust SEs (Heteroskedasticity-Consistent):**\n\n- Assumes: Heteroskedasticity allowed (no constant variance assumption)\n- Valid: Whether or not heteroskedasticity exists\n- Interpretation: \"Here's the uncertainty, accounting for possible non-constant variance\"\n\n**What do differences tell us?**\n\n**Case 1: Robust SE ≈ Standard SE (difference < 10%)**\n\n- Example: Our house price data (11.33 vs 11.17)\n- Interpretation: Little evidence of heteroskedasticity\n- Implication: Assumption 3 approximately holds\n- Decision: Still report robust SEs (good practice)\n\n**Case 2: Robust SE > Standard SE (difference > 20%)**\n\n- Example: Robust SE = 15.0, Standard SE = 10.0\n- Interpretation: Evidence of heteroskedasticity\n- Implication: Standard SEs underestimate uncertainty\n- Consequence: Default t-stats too large, p-values too small\n- Risk: False positives (finding significance that isn't real)\n- Decision: MUST use robust SEs\n\n**Case 3: Robust SE < Standard SE (less common)**\n\n- Example: Robust SE = 8.0, Standard SE = 10.0\n- Interpretation: Specific pattern of heteroskedasticity\n- Implication: Standard SEs overestimate uncertainty\n- Consequence: Default t-stats too small, p-values too large\n- Risk: False negatives (missing real significance)\n- Decision: Use robust SEs (more powerful)\n\n**Visual comparison for our house price data:**\n\n```\nVariable: size\n Standard SE: 11.17 |████████████████████|\n Robust SE: 11.33 |█████████████████████| (+1.4%)\n \nVariable: Intercept\n Standard SE: 21,489 |████████████████████|\n Robust SE: 21,825 |█████████████████████| (+1.6%)\n```\n\n**Impact on inference:**\n\nLet's see how the choice affects our conclusions:\n\n| Test | Standard SE | Robust SE | Conclusion |\n|------|-------------|-----------|------------|\n| t-statistic | 73.77/11.17 = 6.60 | 73.77/11.33 = 6.51 | Both highly significant |\n| p-value | 0.0000 | 0.0000 | Both p < 0.001 |\n| 95% CI | [50.84, 96.70] | [50.33, 97.21] | Nearly identical |\n| Reject H₀? | YES | YES | Same conclusion |\n\n**When robust SEs matter most:**\n\n1. **Large sample differences**\n - If robust SE = 2 × standard SE\n - Significance can disappear\n - Example: t = 2.5 (p=0.02) → t = 1.25 (p=0.22)\n\n2. **Borderline significance**\n - If p-value near 0.05 with standard SEs\n - Might become non-significant with robust SEs\n - Example: p = 0.04 → p = 0.07\n\n3. **High-stakes decisions**\n - Policy recommendations\n - Medical treatments\n - Financial investments\n - Need valid inference\n\n**Reading regression output in practice:**\n\nMost statistical software now reports both:\n\n```\n Standard Robust\nVariable Coef. SE t SE t\nsize 73.77 11.17 6.60 11.33 6.51\n```\n\n**What to report in your paper:**\n\n**Minimum:** Robust standard errors in main results\n**Better:** Show both, explain differences if substantial\n**Best:** Report robust SEs, note \"Results similar with classical SEs\"\n\n**Example write-up:**\n\n\"We find that each additional square foot increases house price by \\$73.77 (robust SE = 11.33, t = 6.51, p < 0.001). The heteroskedasticity-robust standard error is nearly identical to the classical standard error (11.17), suggesting homoskedasticity is approximately satisfied. The effect is highly statistically significant and economically meaningful, with a 95% confidence interval of [\\$50.33, \\$97.21].\"\n\n**Common mistakes to avoid:**\n\n1. **Using standard SEs for cross-sectional data** \n - Modern practice: Always use robust SEs\n\n2. **Testing for heteroskedasticity first** \n - Just use robust SEs (they're valid either way)\n - Pre-testing affects inference in complex ways\n\n3. **Switching between standard and robust to get significance** \n - This is p-hacking\n - Choose robust SEs before looking at results\n\n4. **Ignoring large differences** \n - If robust SE >> standard SE, investigate\n - Might indicate model misspecification\n - Consider transformations or different functional forms\n\n**The bottom line:**\n\nThink of robust SEs as the \"safe\" choice:\n\n- If no heteroskedasticity: Robust SEs ≈ Standard SEs (no harm done)\n- If heteroskedasticity exists: Robust SEs correct the problem (saved you!)\n\nIt's like wearing a seatbelt: doesn't hurt if you don't crash, saves you if you do.\n\n::: {#5351387d .cell execution_count=11}\n``` {.python .cell-code}\n# Hypothesis test using statsmodels\nhypothesis = f'size = {null_value}'\nt_test_result = model_basic.t_test(hypothesis)\nt_test_result\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```\n<class 'statsmodels.stats.contrast.ContrastResults'>\n                             Test for Constraints                             \n==============================================================================\n                 coef    std err          t      P>|t|      [0.025      0.975]\n------------------------------------------------------------------------------\nc0            73.7710     11.175     -1.452      0.158      50.842      96.700\n==============================================================================\n```\n:::\n:::\n\n\n## 7.6 One-Sided Directional Hypothesis Tests\n\nSometimes we have a directional hypothesis (greater than or less than).\n\n**One-sided tests:**\n\n1. **Upper one-tailed**: $H_0: \\beta_2 \\leq \\beta_2^*$ vs $H_a: \\beta_2 > \\beta_2^*$\n   - Reject in the right tail: $p = Pr[T_{n-2} > t]$\n\n2. **Lower one-tailed**: $H_0: \\beta_2 \\geq \\beta_2^*$ vs $H_a: \\beta_2 < \\beta_2^*$\n   - Reject in the left tail: $p = Pr[T_{n-2} < t]$\n\n**Example**: Test whether house price rises by less than \\$90 per square foot.\n\n- Claim: $\\beta_2 < 90$\n- Test: $H_0: \\beta_2 \\geq 90$ vs $H_a: \\beta_2 < 90$ (lower-tailed)\n- $t = (73.77 - 90) / 11.17 = -1.452$\n- $p = Pr[T_{27} < -1.452] = 0.079$\n- Since $p = 0.079 > 0.05$, do not reject $H_0$ at 5% level\n- **Conclusion**: Not enough evidence to support the claim at 5% level\n\n**Note on computer output:**\n\n- Computer gives p-value for two-sided test of $H_0: \\beta_2 = 0$\n- For one-sided test of significance:\n  - If $b_2$ has expected sign, halve the printed p-value\n  - If $b_2$ has wrong sign, reject is not possible (p > 0.5)\n\n::: {#1563316e .cell execution_count=12}\n``` {.python .cell-code}\n# 7.6 One-sided directional hypothesis tests\n# Upper one-tailed test: H₀: β₂ ≤ 90 vs H₁: β₂ > 90\np_value_upper = 1 - stats.t.cdf(t_stat_90, df)\nt_crit_upper = stats.t.ppf(0.95, df)  # one-sided test\n\nprint(f\"\\nUpper one-tailed test: H₀: β₂ ≤ {null_value} vs H₁: β₂ > {null_value}\")\nprint(f\"  t-statistic: {t_stat_90:.4f}\")\nprint(f\"  p-value (one-tailed): {p_value_upper:.6f}\")\nprint(f\"  Critical value (α=0.05): {t_crit_upper:.4f}\")\n\nif t_stat_90 > t_crit_upper:\n    print(\"  Result: Reject H₀\")\nelse:\n    print(\"  Result: Fail to reject H₀\")\n\n# Lower one-tailed test: H₀: β₂ ≥ 90 vs H₁: β₂ < 90\np_value_lower = stats.t.cdf(t_stat_90, df)\n\nprint(f\"\\nLower one-tailed test: H₀: β₂ ≥ {null_value} vs H₁: β₂ < {null_value}\")\nprint(f\"  t-statistic: {t_stat_90:.4f}\")\nprint(f\"  p-value (one-tailed): {p_value_lower:.6f}\")\nprint(f\"  Critical value (α=0.05): {-t_crit_upper:.4f}\")\n\nif t_stat_90 < -t_crit_upper:\n    print(\"  Result: Reject H₀\")\n    print(\"  Conclusion: There is evidence that β₂ < 90\")\nelse:\n    print(\"  Result: Fail to reject H₀\")\n    print(\"  Conclusion: Not enough evidence to support β₂ < 90 at 5% level\")\n    print(f\"  (Would reject at 10% level since p = {p_value_lower:.3f} < 0.10)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nUpper one-tailed test: H₀: β₂ ≤ 90 vs H₁: β₂ > 90\n  t-statistic: -1.4523\n  p-value (one-tailed): 0.921025\n  Critical value (α=0.05): 1.7033\n  Result: Fail to reject H₀\n\nLower one-tailed test: H₀: β₂ ≥ 90 vs H₁: β₂ < 90\n  t-statistic: -1.4523\n  p-value (one-tailed): 0.078975\n  Critical value (α=0.05): -1.7033\n  Result: Fail to reject H₀\n  Conclusion: Not enough evidence to support β₂ < 90 at 5% level\n  (Would reject at 10% level since p = 0.079 < 0.10)\n```\n:::\n:::\n\n\n## 7.7 Robust Standard Errors\n\nDefault standard errors make assumptions 1-4. Robust standard errors relax some of these assumptions.\n\n**Heteroskedasticity-Robust Standard Errors:**\n\n- **Default assumption** (homoskedasticity): $Var[u_i | x_i] = \\sigma_u^2$ (constant)\n- **Relaxed assumption** (heteroskedasticity): $Var[u_i | x_i] = \\sigma_i^2$ (varies with $i$)\n\n**Why use robust standard errors?**\n\n- Heteroskedasticity is common in cross-sectional data\n- Default SEs are incorrect when heteroskedasticity is present\n- Robust SEs are valid whether or not heteroskedasticity exists\n- **Modern practice**: Always report robust SEs for cross-sectional data\n\n**Heteroskedastic-robust SE formula:**\n\n$$se_{het}(b_2) = \\frac{\\sqrt{\\sum_{i=1}^n e_i^2 (x_i - \\bar{x})^2}}{\\sum_{i=1}^n (x_i - \\bar{x})^2}$$\n\n**Effect on inference:**\n\n- Coefficient estimates unchanged\n- Standard errors typically increase (more conservative)\n- t-statistics typically decrease\n- Confidence intervals typically wider\n\n**Other robust SEs:**\n\n- **HAC robust**: For time series with autocorrelation\n- **Cluster robust**: For clustered data (students in schools, people in villages, etc.)\n\n::: {#b7a8613c .cell execution_count=13}\n``` {.python .cell-code}\n# 7.7 Robust standard errors\nrobust_results = ols('price ~ size', data=data_house).fit(cov_type='HC1')\n\n# Comparison of standard and robust standard errors\ncomparison_df = pd.DataFrame({\n    'Coefficient': model_basic.params,\n    'Std. Error': model_basic.bse,\n    'Robust SE': robust_results.bse,\n    't-stat (standard)': model_basic.tvalues,\n    't-stat (robust)': robust_results.tvalues,\n    'p-value (standard)': model_basic.pvalues,\n    'p-value (robust)': robust_results.pvalues\n})\ncomparison_df\n```\n\n::: {.cell-output .cell-output-display execution_count=13}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Coefficient</th>\n      <th>Std. Error</th>\n      <th>Robust SE</th>\n      <th>t-stat (standard)</th>\n      <th>t-stat (robust)</th>\n      <th>p-value (standard)</th>\n      <th>p-value (robust)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Intercept</th>\n      <td>115017.282609</td>\n      <td>21489.359861</td>\n      <td>20298.704493</td>\n      <td>5.352290</td>\n      <td>5.666238</td>\n      <td>1.183545e-05</td>\n      <td>1.459671e-08</td>\n    </tr>\n    <tr>\n      <th>size</th>\n      <td>73.771040</td>\n      <td>11.174911</td>\n      <td>11.329669</td>\n      <td>6.601488</td>\n      <td>6.511315</td>\n      <td>4.408752e-07</td>\n      <td>7.449591e-11</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Full Regression Output with Robust Standard Errors\n\n::: {#3af848bc .cell execution_count=14}\n``` {.python .cell-code}\n# Regression with robust standard errors\nrobust_results.summary()\n```\n\n::: {.cell-output .cell-output-display execution_count=14}\n```{=html}\n<table class=\"simpletable\">\n<caption>OLS Regression Results</caption>\n<tr>\n  <th>Dep. Variable:</th>          <td>price</td>      <th>  R-squared:         </th> <td>   0.617</td>\n</tr>\n<tr>\n  <th>Model:</th>                   <td>OLS</td>       <th>  Adj. R-squared:    </th> <td>   0.603</td>\n</tr>\n<tr>\n  <th>Method:</th>             <td>Least Squares</td>  <th>  F-statistic:       </th> <td>   42.40</td>\n</tr>\n<tr>\n  <th>Date:</th>             <td>Sat, 18 Apr 2026</td> <th>  Prob (F-statistic):</th> <td>5.56e-07</td>\n</tr>\n<tr>\n  <th>Time:</th>                 <td>18:41:59</td>     <th>  Log-Likelihood:    </th> <td> -332.05</td>\n</tr>\n<tr>\n  <th>No. Observations:</th>      <td>    29</td>      <th>  AIC:               </th> <td>   668.1</td>\n</tr>\n<tr>\n  <th>Df Residuals:</th>          <td>    27</td>      <th>  BIC:               </th> <td>   670.8</td>\n</tr>\n<tr>\n  <th>Df Model:</th>              <td>     1</td>      <th>                     </th>     <td> </td>   \n</tr>\n<tr>\n  <th>Covariance Type:</th>         <td>HC1</td>       <th>                     </th>     <td> </td>   \n</tr>\n</table>\n<table class=\"simpletable\">\n<tr>\n      <td></td>         <th>coef</th>     <th>std err</th>      <th>z</th>      <th>P>|z|</th>  <th>[0.025</th>    <th>0.975]</th>  \n</tr>\n<tr>\n  <th>Intercept</th> <td>  1.15e+05</td> <td> 2.03e+04</td> <td>    5.666</td> <td> 0.000</td> <td> 7.52e+04</td> <td> 1.55e+05</td>\n</tr>\n<tr>\n  <th>size</th>      <td>   73.7710</td> <td>   11.330</td> <td>    6.511</td> <td> 0.000</td> <td>   51.565</td> <td>   95.977</td>\n</tr>\n</table>\n<table class=\"simpletable\">\n<tr>\n  <th>Omnibus:</th>       <td> 0.576</td> <th>  Durbin-Watson:     </th> <td>   1.219</td>\n</tr>\n<tr>\n  <th>Prob(Omnibus):</th> <td> 0.750</td> <th>  Jarque-Bera (JB):  </th> <td>   0.638</td>\n</tr>\n<tr>\n  <th>Skew:</th>          <td>-0.078</td> <th>  Prob(JB):          </th> <td>   0.727</td>\n</tr>\n<tr>\n  <th>Kurtosis:</th>      <td> 2.290</td> <th>  Cond. No.          </th> <td>9.45e+03</td>\n</tr>\n</table><br/><br/>Notes:<br/>[1] Standard Errors are heteroscedasticity robust (HC1)<br/>[2] The condition number is large, 9.45e+03. This might indicate that there are<br/>strong multicollinearity or other numerical problems.\n```\n:::\n:::\n\n\n### Visualization: Scatter Plot with Regression Line\n\nVisual representation of the bivariate regression relationship.\n\n::: {#fb016492 .cell execution_count=15}\n``` {.python .cell-code}\n# Figure 7.1: Scatter plot with regression line\nfig, ax = plt.subplots(figsize=(10, 6))\nax.scatter(data_house['size'], data_house['price'],\n           alpha=0.6, s=50,  # alpha = transparency, s = marker size\n           color='#22d3ee', label='Actual observations')\nax.plot(data_house['size'], model_basic.fittedvalues, color='#c084fc',\n        linewidth=2, label='Fitted regression line')\nax.set_xlabel('Size (square feet)', fontsize=12)\nax.set_ylabel('Price ($1000s)', fontsize=12)\nax.set_title('Figure 7.1: House Price vs Size with Regression Line',\n             fontsize=14, fontweight='bold')\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch07_Statistical_Inference_for_Bivariate_Regression_files/figure-html/cell-16-output-1.png){width=950 height=565}\n:::\n:::\n\n\n**What to look for in this scatter plot:**\n\n- **Direction**: Positive -- larger houses tend to have higher prices\n- **Form**: Roughly linear -- the points follow an upward-sloping pattern consistent with our regression model\n- **Scatter**: Points do not lie exactly on the line -- this variation is the residual \"error\" that the model cannot explain\n- **Regression line**: The fitted line summarizes the average relationship, with the slope reflecting $73.77 per additional square foot\n\n### Visualization: Confidence Intervals\n\nGraphical display of coefficient estimates with confidence intervals.\n\n::: {#952616b1 .cell execution_count=16}\n``` {.python .cell-code}\n# Figure 7.2: Confidence interval visualization\nfig, ax = plt.subplots(figsize=(10, 6))\n\n# Plot point estimate and confidence interval\ncoef_names = ['Intercept', 'Size']\ncoefs = model_basic.params.values\nci_low = conf_int.iloc[:, 0].values\nci_high = conf_int.iloc[:, 1].values\n\ny_pos = np.arange(len(coef_names))\nax.errorbar(coefs, y_pos, xerr=[coefs - ci_low, ci_high - coefs],\n            fmt='o', markersize=8, capsize=5, capthick=2, linewidth=2, color='#22d3ee')\nax.set_yticks(y_pos)\nax.set_yticklabels(coef_names)\nax.axvline(x=0, color='red', linestyle='--', linewidth=1, alpha=0.5,\n           label='H₀: β = 0')\nax.set_xlabel('Coefficient Value', fontsize=12)\nax.set_title('Figure 7.2: Coefficient Estimates with 95% Confidence Intervals',\n             fontsize=14, fontweight='bold')\nax.legend()\nax.grid(True, alpha=0.3, axis='x')\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch07_Statistical_Inference_for_Bivariate_Regression_files/figure-html/cell-17-output-1.png){width=950 height=565}\n:::\n:::\n\n\n**What to look for in this confidence interval plot:**\n\n- **Exclusion of zero**: If the confidence interval does not cross the red dashed line (zero), the coefficient is statistically significant at the 5% level\n- **Width**: Wider intervals indicate less precision in the estimate; narrower intervals indicate more certainty\n- **Both coefficients**: The intercept and size coefficient are both statistically significant since neither CI contains zero\n\n### Visualization: Residual Plot\n\nCheck for patterns in residuals that might violate model assumptions.\n\n::: {#4ba87ee2 .cell execution_count=17}\n``` {.python .cell-code}\n# Figure 7.3: Residual plot\nfig, ax = plt.subplots(figsize=(10, 6))\nax.scatter(model_basic.fittedvalues, model_basic.resid,\n           alpha=0.6, s=50, color='#22d3ee')  # alpha = transparency, s = marker size\nax.axhline(y=0, color='red', linestyle='--', linewidth=2, label='Zero residual line')\nax.set_xlabel('Fitted values', fontsize=12)\nax.set_ylabel('Residuals', fontsize=12)\nax.set_title('Figure 7.3: Residual Plot', fontsize=14, fontweight='bold')\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ch07_Statistical_Inference_for_Bivariate_Regression_files/figure-html/cell-18-output-1.png){width=950 height=565}\n:::\n:::\n\n\n**What to look for in this residual plot:**\n\n- **Random scatter**: Residuals should appear randomly distributed around zero -- no discernible pattern\n- **Constant spread**: The vertical spread of residuals should be roughly the same across all fitted values (homoskedasticity)\n- **Funnel shape**: If the spread widens or narrows, this signals heteroskedasticity -- robust standard errors are needed\n- **Outliers**: Points far from zero may be influential observations worth investigating\n\n## Key Takeaways\n\n**Key Takeaways:**\n\n1. **The t-statistic** is fundamental to statistical inference in regression:\n   - Formula: $t = \\frac{b_2 - \\beta_2}{se(b_2)} \\sim T(n-2)$\n   - Parallels univariate inference: $t = \\frac{\\bar{x} - \\mu}{se(\\bar{x})} \\sim T(n-1)$\n\n2. **Confidence intervals** provide a range of plausible values:\n   - Formula: $b_2 \\pm t_{n-2, \\alpha/2} \\times se(b_2)$\n   - 95% CI (approximate): $b_2 \\pm 2 \\times se(b_2)$\n   - Interpretation: 95% of such intervals will contain the true $\\beta_2$\n\n3. **Tests of statistical significance** assess whether a regressor matters:\n   - $H_0: \\beta_2 = 0$ vs $H_a: \\beta_2 \\neq 0$\n   - Reject if $p$-value $< \\alpha$ or $|t| > t_{n-2, \\alpha/2}$\n   - Statistical significance $\\neq$ economic significance\n\n4. **Two-sided tests** for specific values:\n   - $H_0: \\beta_2 = \\beta_2^*$ vs $H_a: \\beta_2 \\neq \\beta_2^*$\n   - Equivalent to checking if $\\beta_2^*$ is in the confidence interval\n\n5. **One-sided tests** for directional hypotheses:\n   - Upper tail: $H_0: \\beta_2 \\leq \\beta_2^*$ vs $H_a: \\beta_2 > \\beta_2^*$\n   - Lower tail: $H_0: \\beta_2 \\geq \\beta_2^*$ vs $H_a: \\beta_2 < \\beta_2^*$\n   - p-value is half the two-sided p-value (if sign is correct)\n\n6. **Robust standard errors** provide valid inference under weaker assumptions:\n   - Heteroskedasticity-robust (HC1): Relaxes constant variance assumption\n   - Modern practice: Always use for cross-sectional data\n   - Other types: HAC (time series), cluster (grouped data)\n\n**Model Assumptions (1-4):**\n\n1. Linearity: $y = \\beta_1 + \\beta_2 x + u$\n2. Zero conditional mean: $E[u_i | x_i] = 0$\n3. Constant variance: $Var[u_i | x_i] = \\sigma_u^2$ (relaxed with robust SEs)\n4. Independence: $u_i$ independent of $u_j$\n\n**House Price Example Results:**\n\n- Coefficient: Each additional sq ft increases price by \\$73.77\n- 95% CI: [\\$50.84, \\$96.70]\n- Highly statistically significant (t = 6.60, p < 0.001)\n- Economically meaningful effect\n\n**Python Tools Used:**\n\n- `pandas`: Data manipulation and summary statistics\n- `statsmodels`: Econometric estimation and hypothesis testing\n- `scipy.stats`: Statistical distributions and critical values\n- `matplotlib` & `seaborn`: Visualization\n\n**Practical Skills Developed:**\n\n- Conducting t-tests on regression coefficients\n- Constructing and interpreting confidence intervals\n- Testing economic hypotheses (two-sided and one-sided)\n- Using robust standard errors for valid inference\n- Visualizing regression results\n- Distinguishing statistical from economic significance\n\n**Python Libraries and Code:**\n\nThis single code block reproduces the core workflow of Chapter 7. It is self-contained — copy it into an empty notebook and run it to review the complete pipeline from data loading to hypothesis testing, confidence intervals, and robust standard errors.\n\n```python\n# =============================================================================\n# CHAPTER 7 CHEAT SHEET: Statistical Inference for Bivariate Regression\n# =============================================================================\n\n# --- Libraries ---\nimport pandas as pd                       # data loading and manipulation\nimport matplotlib.pyplot as plt           # creating plots and visualizations\nfrom statsmodels.formula.api import ols   # OLS regression with R-style formulas\nfrom scipy import stats                   # t-distribution and critical values\n\n# =============================================================================\n# STEP 1: Load data directly from a URL\n# =============================================================================\n# pd.read_stata() reads Stata .dta files — the house price dataset has 29 houses\nurl = \"https://raw.githubusercontent.com/quarcs-lab/data-open/master/AED/AED_HOUSE.DTA\"\ndata_house = pd.read_stata(url)\n\nprint(f\"Dataset: {data_house.shape[0]} observations, {data_house.shape[1]} variables\")\n\n# =============================================================================\n# STEP 2: Estimate the regression and extract key statistics\n# =============================================================================\n# The t-statistic measures how many standard errors the estimate is from zero\nmodel = ols('price ~ size', data=data_house).fit()\n\nslope     = model.params['size']       # marginal effect: $/sq ft\nintercept = model.params['Intercept']\nse_slope  = model.bse['size']          # standard error of the slope\nt_stat    = model.tvalues['size']      # t = b2 / se(b2)\np_value   = model.pvalues['size']      # two-sided p-value for H0: b2 = 0\n\nprint(f\"Estimated equation: price = {intercept:,.0f} + {slope:.2f} × size\")\nprint(f\"Standard error of slope: {se_slope:.2f}\")\nprint(f\"t-statistic: {t_stat:.4f}\")\nprint(f\"p-value: {p_value:.6f}\")\n\n# Full regression table (coefficients, std errors, t-stats, p-values, R²)\nmodel.summary()\n\n# =============================================================================\n# STEP 3: Confidence interval — a range of plausible values for β₂\n# =============================================================================\n# CI = b2 ± t_crit × se(b2), using T(n-2) distribution\nn  = len(data_house)\ndf = n - 2                                        # degrees of freedom\nt_crit = stats.t.ppf(0.975, df)                   # critical value for 95% CI\n\nci_lower = slope - t_crit * se_slope\nci_upper = slope + t_crit * se_slope\n\nprint(f\"Degrees of freedom: {df}\")\nprint(f\"Critical t-value (α=0.05, two-sided): {t_crit:.4f}\")\nprint(f\"95% CI for slope: [{ci_lower:.2f}, {ci_upper:.2f}]\")\nprint(f\"Interpretation: each sq ft adds between ${ci_lower:.0f} and ${ci_upper:.0f} to price\")\n\n# =============================================================================\n# STEP 4: Hypothesis tests — does size matter? Is the effect $90/sq ft?\n# =============================================================================\n# Test 1: Statistical significance (H0: β₂ = 0)\nprint(f\"Test H₀: β₂ = 0  →  t = {t_stat:.2f}, p = {p_value:.6f}  →  Reject H₀\")\n\n# Test 2: Two-sided test for a specific value (H0: β₂ = 90)\nnull_value = 90\nt_90 = (slope - null_value) / se_slope\np_90 = 2 * (1 - stats.t.cdf(abs(t_90), df))\n\nprint(f\"Test H₀: β₂ = 90  →  t = {t_90:.4f}, p = {p_90:.4f}  →  Fail to reject H₀\")\nprint(f\"  (90 is inside the 95% CI [{ci_lower:.2f}, {ci_upper:.2f}])\")\n\n# =============================================================================\n# STEP 5: One-sided test — does size increase price by less than $90/sq ft?\n# =============================================================================\n# H0: β₂ ≥ 90  vs  Ha: β₂ < 90 (lower-tailed test)\np_lower = stats.t.cdf(t_90, df)                   # one-sided p-value (left tail)\n\nprint(f\"One-sided test H₀: β₂ ≥ 90 vs Hₐ: β₂ < 90\")\nprint(f\"  t = {t_90:.4f}, one-sided p = {p_lower:.4f}\")\nprint(f\"  Fail to reject at 5% (p = {p_lower:.3f} > 0.05)\")\nprint(f\"  Would reject at 10% (p = {p_lower:.3f} < 0.10)\")\n\n# =============================================================================\n# STEP 6: Robust standard errors — valid with or without heteroskedasticity\n# =============================================================================\n# HC1 robust SEs protect against non-constant variance in the errors\nrobust_model = ols('price ~ size', data=data_house).fit(cov_type='HC1')\n\nprint(f\"{'':20s} {'Standard':>12s} {'Robust (HC1)':>12s}\")\nprint(\"-\" * 46)\nprint(f\"{'SE(size)':<20s} {se_slope:>12.2f} {robust_model.bse['size']:>12.2f}\")\nprint(f\"{'t-statistic':<20s} {t_stat:>12.2f} {robust_model.tvalues['size']:>12.2f}\")\nprint(f\"{'p-value':<20s} {p_value:>12.6f} {robust_model.pvalues['size']:>12.6f}\")\n\npct_change = ((robust_model.bse['size'] - se_slope) / se_slope) * 100\nprint(f\"\\nRobust SE is {pct_change:+.1f}% different from standard SE\")\n\n# =============================================================================\n# STEP 7: Scatter plot with regression line and inference summary\n# =============================================================================\nfig, ax = plt.subplots(figsize=(10, 6))\nax.scatter(data_house['size'], data_house['price'], s=50, alpha=0.7, label='Actual prices')\nax.plot(data_house['size'], model.fittedvalues, color='red', linewidth=2, label='Fitted line')\nax.set_xlabel('House Size (square feet)')\nax.set_ylabel('House Sale Price (dollars)')\nax.set_title(f'price = {intercept:,.0f} + {slope:.2f} × size    '\n             f'95% CI for slope: [{ci_lower:.0f}, {ci_upper:.0f}]')\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\n```\n\n**Try it yourself!** Copy this code into an empty Google Colab notebook and run it: [Open Colab](https://colab.research.google.com/notebooks/empty.ipynb)\n\n**Next Steps:**\n\n- Extend to multiple regression (Chapter 11)\n- Learn about model specification and variable selection\n- Study violations of assumptions and diagnostics\n- Practice with different datasets and research questions\n\n---\n\n**Congratulations!** You've completed Chapter 7. You now have both theoretical understanding and practical skills in conducting statistical inference for bivariate regression models!\n\n> **Common Mistakes to Avoid**\n>\n> - **Using standard errors when heteroskedasticity is present**: Always check robust standard errors\n> - **Confusing confidence intervals for prediction intervals**: CIs are for the mean response, not individual observations\n> - **Forgetting to check model assumptions before interpreting p-values**\n\n## Practice Exercises\n\n**Exercise 1: Understanding Standard Errors**\n\nSuppose you estimate a regression of wages on education using data from 100 workers. The estimated slope is b₂ = 5.2 (each additional year of education increases wages by \\$5.20/hour) with standard error se(b₂) = 1.8.\n\na) Calculate the 95% confidence interval for β₂ (use t-critical value ≈ 2.0).  \nb) Interpret the confidence interval in plain language.  \nc) If the sample size were 400 instead of 100, how would the standard error change (approximately)? Explain why.\n\n**Exercise 2: Hypothesis Testing Mechanics**\n\nUsing the wage-education regression from Exercise 1 (b₂ = 5.2, se(b₂) = 1.8):\n\na) Test H₀: β₂ = 0 vs. Hₐ: β₂ ≠ 0 at the 5% level. Calculate the t-statistic and state your conclusion.  \nb) Calculate the approximate p-value for this test.  \nc) Would you reject H₀ at the 1% level? Explain.\n\n**Exercise 3: Two-Sided Tests**\n\nA researcher claims that each year of education increases wages by exactly \\$6.00/hour. Using the regression from Exercise 1:\n\na) State the null and alternative hypotheses to test this claim.  \nb) Calculate the test statistic.  \nc) At the 5% level, do you reject the researcher's claim? Explain your reasoning.  \nd) Is the claim consistent with the 95% confidence interval from Exercise 1?\n\n**Exercise 4: One-Sided Tests**\n\nA policy analyst claims that education increases wages by less than \\$3.00/hour. Using the regression from Exercise 1:\n\na) State the appropriate one-sided hypotheses (Hint: The claim becomes Hₐ).  \nb) Calculate the test statistic.  \nc) Find the one-sided p-value (using t ≈ normal approximation).  \nd) At the 5% level, do you reject H₀? What do you conclude about the analyst's claim?\n\n**Exercise 5: Statistical vs. Economic Significance**\n\nConsider two regressions:\n\n**Regression A:** n = 50, b₂ = 0.05, se(b₂) = 0.10  \n**Regression B:** n = 10,000, b₂ = 0.05, se(b₂) = 0.01\n\na) For each regression, test H₀: β₂ = 0 at the 5% level. What do you conclude?  \nb) Despite having the same coefficient (0.05), why do the conclusions differ?  \nc) In which regression is the effect more economically significant? Explain.\n\n**Exercise 6: Confidence Interval Properties**\n\nTrue or False? Explain your reasoning for each:\n\na) A 95% confidence interval means there's a 95% probability that β₂ is in the interval.  \nb) If we reject H₀: β₂ = β₂* at the 5% level, then β₂* will be outside the 95% CI.  \nc) Wider confidence intervals are always worse than narrow ones.  \nd) With n = 30, a 95% CI uses a t-critical value of approximately 2.0.\n\n**Exercise 7: Robust Standard Errors**\n\nA researcher estimates a house price regression using n = 100 houses:\n\n- Standard SE: 15.0\n- Robust SE: 22.5\n\na) What does the large difference suggest about the data?  \nb) Which standard error should be reported? Why?  \nc) How does the difference affect the t-statistic and hypothesis tests?  \nd) Is heteroskedasticity a problem for the coefficient estimates themselves? Explain.\n\n**Exercise 8: Comprehensive Analysis**\n\nYou're analyzing the effect of advertising spending (x, in thousands of dollars) on sales revenue (y, in millions of dollars) using data from 80 firms. Your regression output shows:\n\n- Intercept: 2.5, SE = 0.8\n- Slope (advertising): 3.2, SE = 0.9  \n- R² = 0.45\n- n = 80\n\na) Construct a 95% confidence interval for the slope coefficient.  \nb) Test whether advertising has a statistically significant effect on sales at the 5% level.  \nc) A colleague claims that \\$1,000 in advertising spending increases sales by more than \\$5 million. Test this claim using a one-sided test at the 5% level.  \nd) Is the effect of advertising economically significant? Consider that the average firm in the sample spends \\$10,000 on advertising and has \\$5 million in sales revenue.\n\n---\n\n**Hint for all exercises:** When degrees of freedom are large (n > 30), you can use t-critical values of approximately 1.645 (10% level), 1.96 (5% level), and 2.576 (1% level).\n\n## Case Studies\n\n### Case Study 1: Testing Convergence Hypotheses\n\nIn this case study, you'll apply statistical inference concepts to test economic hypotheses about productivity convergence across countries. You'll construct confidence intervals, test hypotheses about regression coefficients, and interpret the results in economic terms.\n\n**Research Question:** Does the relationship between labor productivity and capital per worker support convergence theory predictions?\n\n**Background:**  \nEconomic growth theory suggests that countries with lower initial capital should experience faster productivity growth as they \"catch up\" to richer countries. We can test this using the relationship between productivity levels and capital intensity across countries.\n\n**Dataset:**  \nWe'll use the **Convergence Clubs** dataset (Mendez 2020) containing data for 108 countries in 2014:\n\n- **productivity**: Real GDP per capita (thousands of dollars)\n- **capital**: Physical capital per worker (thousands of dollars)\n\n**Econometric Model:**\n\n$$\\text{productivity}_i = \\beta_1 + \\beta_2 \\times \\text{capital}_i + u_i$$\n\n**Key Hypotheses to Test:**\n\n1. Does capital significantly affect productivity? (H₀: β₂ = 0)\n2. Is the effect economically meaningful?\n3. Does the relationship differ across country income groups?\n\n---\n\n**Learning Objectives:**\n\n- Construct and interpret confidence intervals for regression coefficients\n- Conduct two-sided and one-sided hypothesis tests\n- Compare statistical and economic significance\n- Use robust standard errors appropriately\n- Apply hypothesis testing to economic questions\n\n> **Key Concept 7.7: Economic Convergence and Statistical Testing**\n>\n> **Convergence theory** predicts that poorer countries should grow faster than richer countries, leading to a narrowing of income gaps over time. Two main types:\n>\n> **Absolute convergence:**\n> - All countries converge to the same income level\n> - Predicts negative relationship between initial income and growth rate\n> - Test: H₀: β (growth on initial income) ≥ 0 vs. Hₐ: β < 0\n>\n> **Conditional convergence:**  \n> - Countries converge to their own steady states\n> - After controlling for determinants (savings, education, institutions)\n> - More empirically supported than absolute convergence\n>\n> **Testing convergence hypotheses:**\n> - Requires careful hypothesis formulation\n> - One-sided tests appropriate (theory predicts direction)\n> - Economic significance matters (how fast is convergence?)\n> - Must account for heteroskedasticity (countries differ in volatility)\n>\n> **Our approach:** We examine the cross-sectional relationship between productivity and capital intensity to understand the fundamentals underlying convergence patterns.\n\n::: {#5db4e5c4 .cell execution_count=18}\n``` {.python .cell-code}\n# Case study: Testing convergence hypotheses\nurl_cc = \"https://raw.githubusercontent.com/quarcs-lab/mendez2020-convergence-clubs-code-data/master/assets/dat.csv\"\ndata_convergence = pd.read_csv(url_cc)\n\n# Filter to 2014 cross-section\ndata_2014 = data_convergence[data_convergence['year'] == 2014].copy()\n\n# Create productivity and capital variables\ndata_2014['productivity'] = data_2014['lp']   # labor productivity\ndata_2014['capital'] = data_2014['kl']         # capital per worker\n\nprint(f\"Sample: {len(data_2014)} countries in 2014\")\n\n# Variable summary\ndata_2014[['productivity', 'capital']].describe()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSample: 108 countries in 2014\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=18}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>productivity</th>\n      <th>capital</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>108.000000</td>\n      <td>108.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>40976.872873</td>\n      <td>165853.513152</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>33853.205257</td>\n      <td>158299.099750</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>1371.304400</td>\n      <td>2482.352300</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>11806.898750</td>\n      <td>32297.584250</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>32780.588500</td>\n      <td>108045.820000</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>63377.238000</td>\n      <td>276118.617500</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>142219.970000</td>\n      <td>552395.190000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Task 1: Estimate the Productivity-Capital Relationship (Guided)\n\n**Objective:** Estimate the bivariate regression and interpret the results.\n\n**Your task:**  \nRun the code below to estimate the regression and examine the output. Then answer:\n\na) What is the estimated effect of capital on productivity? Interpret the coefficient.  \nb) Construct a 95% confidence interval for β₂. What does this interval tell you?  \nc) Is the effect statistically significant at the 5% level?  \nd) Is the effect economically significant? (Consider that the average country has capital = 50 and productivity = 25)\n\n::: {#2a630b2b .cell execution_count=19}\n``` {.python .cell-code}\n# Task 1: Basic regression\nmodel_convergence = ols('productivity ~ capital', data=data_2014).fit()\n\n# Task 1: Regression of Productivity on Capital\nmodel_convergence.summary()\n\n# Extract key statistics\nbeta2 = model_convergence.params['capital']\nse_beta2 = model_convergence.bse['capital']\nt_stat = model_convergence.tvalues['capital']\np_value = model_convergence.pvalues['capital']\n\n# Key statistics\nprint(f\"Coefficient (β₂): {beta2:.4f}\")\nprint(f\"Standard Error: {se_beta2:.4f}\")\nprint(f\"t-statistic: {t_stat:.2f}\")\nprint(f\"p-value: {p_value:.6f}\")\n\n# 95% Confidence Interval\nci_95 = model_convergence.conf_int(alpha=0.05).loc['capital']\nprint(f\"95% Confidence Interval: [{ci_95.iloc[0]:.4f}, {ci_95.iloc[1]:.4f}]\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCoefficient (β₂): 0.1995\nStandard Error: 0.0075\nt-statistic: 26.63\np-value: 0.000000\n95% Confidence Interval: [0.1846, 0.2143]\n```\n:::\n:::\n\n\n### Task 2: Test Specific Hypotheses (Semi-guided)\n\n**Objective:** Conduct formal hypothesis tests about the productivity-capital relationship.\n\n**Your tasks:**\n\na) **Test for statistical significance:**  \n\n   - H₀: β₂ = 0 (capital has no effect) vs. Hₐ: β₂ ≠ 0  \n   - Use the t-statistic and p-value from Task 1  \n   - State your conclusion at the 5% level\n\nb) **Test economic theory prediction:**  \n\n   - Economic theory suggests that the marginal product of capital in developing countries might be around 0.5 (50 cents of GDP per dollar of capital)  \n   - H₀: β₂ = 0.5 vs. Hₐ: β₂ ≠ 0.5  \n   - Calculate the test statistic: t = (β₂ - 0.5) / se(β₂)  \n   - Find the p-value and state your conclusion\n\nc) **Test pessimistic hypothesis:**  \n\n   - A pessimist claims that capital contributes less than $0.30 to productivity  \n   - Formulate appropriate one-sided hypotheses  \n   - Calculate the test statistic and one-sided p-value  \n   - Do you reject the pessimist's claim at the 5% level?\n\n**Code hints:**\n```python\n# For part (b)\nt_test_05 = (beta2 - 0.5) / se_beta2\np_value_05 = 2 * (1 - stats.t.cdf(abs(t_test_05), df=model_convergence.df_resid))\n\n# For part (c) - one-sided test\nnull_value = 0.30\nt_test_pessimist = (beta2 - null_value) / se_beta2\n# p-value depends on direction: use stats.t.cdf() or (1 - stats.t.cdf())\n```\n\n::: {#e37c4ff9 .cell execution_count=20}\n``` {.python .cell-code}\n# Task 2: Your hypothesis tests here\n\n# Part (a): Statistical significance test\n# Task 2(a): Test H₀: β₂ = 0\nprint(f\"t-statistic: {t_stat:.2f}\")\nprint(f\"p-value: {p_value:.6f}\")\nif p_value < 0.05:\n    print(\"Conclusion: Reject H₀ at 5% level. Capital significantly affects productivity.\")\nelse:\n    print(\"Conclusion: Fail to reject H₀ at 5% level.\")\n\n# Part (b): Test β₂ = 0.5\n# Task 2(b): Test H₀: β₂ = 0.5\nnull_value_b = 0.5\nt_test_05 = (beta2 - null_value_b) / se_beta2\np_value_05 = 2 * (1 - stats.t.cdf(abs(t_test_05), df=model_convergence.df_resid))\nprint(f\"t-statistic: {t_test_05:.2f}\")\nprint(f\"p-value: {p_value_05:.6f}\")\nif p_value_05 < 0.05:\n    print(f\"Conclusion: Reject H₀. The coefficient differs significantly from {null_value_b}.\")\nelse:\n    print(f\"Conclusion: Fail to reject H₀. The data are consistent with β₂ = {null_value_b}.\")\n\n# Part (c): One-sided test (pessimistic claim: β₂ < 0.30)\n# Task 2(c): Test Pessimist's Claim (β₂ < 0.30)\nnull_value_c = 0.30\nprint(\"H₀: β₂ ≥ 0.30 vs. Hₐ: β₂ < 0.30 (pessimist's claim)\")\nt_test_pessimist = (beta2 - null_value_c) / se_beta2\n# For lower-tailed test: if t > 0, we're rejecting in favor of β₂ > 0.30 (opposite direction)\np_value_pessimist_lower = stats.t.cdf(t_test_pessimist, df=model_convergence.df_resid)\nprint(f\"t-statistic: {t_test_pessimist:.2f}\")\nprint(f\"One-sided p-value (lower tail): {p_value_pessimist_lower:.6f}\")\nif t_test_pessimist < 0:\n    print(\"Test statistic is negative - consistent with pessimist's claim\")\n    if p_value_pessimist_lower < 0.05:\n        print(\"Conclusion: Reject H₀. Evidence supports β₂ < 0.30.\")\n    else:\n        print(\"Conclusion: Fail to reject H₀ at 5% level.\")\nelse:\n    print(\"Test statistic is positive - contradicts pessimist's claim\")\n    print(\"Conclusion: Cannot reject H₀ in favor of Hₐ (data contradicts the claim).\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nt-statistic: 26.63\np-value: 0.000000\nConclusion: Reject H₀ at 5% level. Capital significantly affects productivity.\nt-statistic: -40.12\np-value: 0.000000\nConclusion: Reject H₀. The coefficient differs significantly from 0.5.\nH₀: β₂ ≥ 0.30 vs. Hₐ: β₂ < 0.30 (pessimist's claim)\nt-statistic: -13.42\nOne-sided p-value (lower tail): 0.000000\nTest statistic is negative - consistent with pessimist's claim\nConclusion: Reject H₀. Evidence supports β₂ < 0.30.\n```\n:::\n:::\n\n\n> **Key Concept 7.8: p-Values and Statistical Significance in Practice**\n>\n> The **p-value** measures the strength of evidence against the null hypothesis. But interpreting p-values requires care:\n>\n> **What p-values tell you:**\n> - p = 0.001: Very strong evidence against H₀ (occurs 0.1% of the time if H₀ true)\n> - p = 0.04: Evidence against H₀ (occurs 4% of the time if H₀ true)\n> - p = 0.15: Weak/no evidence against H₀\n>\n> **Common p-value thresholds:**\n>\n> - ★★★ **p < 0.01**: Highly significant\n> - ★★ **0.01 ≤ p < 0.05**: Significant\n> - ★ **0.05 ≤ p < 0.10**: Marginally significant\n> - **p ≥ 0.10**: Not significant\n>\n> **Critical insights:**\n> 1. **Arbitrary thresholds:** The 0.05 cutoff is convention, not law\n> 2. **p-values ≠ importance:** p < 0.001 doesn't mean \"more true\" than p = 0.04\n> 3. **Near the threshold:** p = 0.051 and p = 0.049 provide similar evidence\n> 4. **Large samples:** With n = 10,000, even tiny effects become \"significant\"\n> 5. **Publication bias:** Studies with p < 0.05 more likely to be published\n>\n> **Best practice:** Report exact p-values and confidence intervals rather than just \"significant\" or \"not significant.\" Let readers judge the evidence.\n\n### Task 3: Heteroskedasticity-Robust Inference (Semi-guided)\n\n**Objective:** Compare standard and robust standard errors for cross-country data.\n\n**Background:**  \nCross-country data often exhibits heteroskedasticity because larger/richer countries tend to have more variable outcomes. We should use robust standard errors for valid inference.\n\n**Your tasks:**\n\na) Obtain heteroskedasticity-robust standard errors (HC1) using:\n   ```python\n   robust_model = ols('productivity ~ capital', data=data_2014).fit(cov_type='HC1')\n   ```\n\nb) Compare standard vs. robust standard errors:\n\n   - How much do they differ? (Calculate percentage change)\n   - What does this suggest about heteroskedasticity in the data?\n\nc) Re-test H₀: β₂ = 0 using robust standard errors:\n\n   - Calculate the robust t-statistic\n   - Has your conclusion changed?\n\nd) Construct a 95% CI using robust standard errors:\n\n   - Compare to the standard CI from Task 1\n   - Which should you report in a research paper?\n\n::: {#3ff3bb74 .cell execution_count=21}\n``` {.python .cell-code}\n# Task 3: Robust standard errors\nrobust_model = ols('productivity ~ capital', data=data_2014).fit(cov_type='HC1')\n\n# Task 3: Robust Standard Errors Analysis\n\n# Extract robust statistics\nbeta2_robust = robust_model.params['capital']\nse_beta2_robust = robust_model.bse['capital']\nt_stat_robust = robust_model.tvalues['capital']\np_value_robust = robust_model.pvalues['capital']\n\n# Comparison table\n# Comparison of Standard vs. Robust Standard Errors\ncomparison_df = pd.DataFrame({\n    'Statistic': ['Coefficient', 'Standard SE', 'Robust SE', 't-statistic (standard)', \n                  't-statistic (robust)', 'p-value (standard)', 'p-value (robust)'],\n    'Value': [beta2, se_beta2, se_beta2_robust, t_stat, t_stat_robust, p_value, p_value_robust]\n})\ncomparison_df.to_string(index=False)\n\n# Percent change in SE\npct_change = ((se_beta2_robust - se_beta2) / se_beta2) * 100\nprint(f\"Robust SE is {pct_change:+.1f}% different from standard SE\")\n\nif abs(pct_change) > 10:\n    print(\"→ Substantial difference suggests heteroskedasticity is present\")\n    print(\"→ MUST use robust SEs for valid inference\")\nelse:\n    print(\"→ Small difference suggests heteroskedasticity is mild\")\n    print(\"→ Still best practice to use robust SEs\")\n\n# Robust confidence interval\nci_robust = robust_model.conf_int(alpha=0.05)\nci_95_robust = ci_robust.loc['capital'] if 'capital' in ci_robust.index else ci_robust.iloc[1]\nprint(f\"95% Confidence Intervals:\")\nprint(f\"  Standard CI: [{ci_95.iloc[0]:.4f}, {ci_95.iloc[1]:.4f}]\")\nprint(f\"  Robust CI:   [{ci_95_robust.iloc[0]:.4f}, {ci_95_robust.iloc[1]:.4f}]\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRobust SE is +48.4% different from standard SE\n→ Substantial difference suggests heteroskedasticity is present\n→ MUST use robust SEs for valid inference\n95% Confidence Intervals:\n  Standard CI: [0.1846, 0.2143]\n  Robust CI:   [0.1777, 0.2213]\n```\n:::\n:::\n\n\n### Task 4: Heterogeneity Across Income Groups (More Independent)\n\n**Objective:** Investigate whether the productivity-capital relationship differs between high-income and developing countries.\n\n**Your tasks (design your own analysis):**\n\na) **Split the sample:**  \n\n   - Create two subsamples: high-income countries (productivity above the median) and developing countries (below the median)\n   - How many countries in each group?\n\nb) **Estimate separate regressions:**  \n\n   - Run the same regression for each subsample\n   - Use robust standard errors for both\n   - Create a comparison table showing β₂, robust SE, t-statistic, and p-value for each group\n\nc) **Compare the results:**  \n\n   - Is the effect of capital on productivity stronger in one group?\n   - Test H₀: β₂ = 0.5 for each group separately\n   - Are the effects statistically significant in both groups?\n   - What might explain any differences you find?\n\n**Hints:**\n```python\n# Split data at the median\nthreshold = data_2014['productivity'].median()\nhigh_income = data_2014[data_2014['productivity'] > threshold]\ndeveloping = data_2014[data_2014['productivity'] <= threshold]\n\n# Run regressions with robust SEs\nmodel_high = ols('productivity ~ capital', data=high_income).fit(cov_type='HC1')\nmodel_dev = ols('productivity ~ capital', data=developing).fit(cov_type='HC1')\n```\n\n::: {#e788e369 .cell execution_count=22}\n``` {.python .cell-code}\n# Task 4: Your analysis here\n\n# Split the sample at the median\nthreshold = data_2014['productivity'].median()\nhigh_income = data_2014[data_2014['productivity'] > threshold].copy()\ndeveloping = data_2014[data_2014['productivity'] <= threshold].copy()\n\n# Task 4: Income Group Analysis\nprint(f\"High-income countries: {len(high_income)}\")\nprint(f\"Developing countries: {len(developing)}\")\n\n# Estimate separate regressions with robust SEs\nrobust_high = ols('productivity ~ capital', data=high_income).fit(cov_type='HC1')\nrobust_dev = ols('productivity ~ capital', data=developing).fit(cov_type='HC1')\n\n# Create comparison table\ncomparison_groups = pd.DataFrame({\n    'Group': ['High-Income', 'Developing', 'Full Sample'],\n    'n': [len(high_income), len(developing), len(data_2014)],\n    'β₂': [robust_high.params['capital'], robust_dev.params['capital'], beta2_robust],\n    'Robust SE': [robust_high.bse['capital'], robust_dev.bse['capital'], se_beta2_robust],\n    't-stat': [robust_high.tvalues['capital'], robust_dev.tvalues['capital'], t_stat_robust],\n    'p-value': [robust_high.pvalues['capital'], robust_dev.pvalues['capital'], p_value_robust]\n})\n\n# Regression Results by Income Group\ncomparison_groups.to_string(index=False)\n\n# Test β₂ = 0.5 for each group\nfor name, robust_res in [('High-Income', robust_high), ('Developing', robust_dev)]:\n    beta = robust_res.params['capital']\n    se = robust_res.bse['capital']\n    t_05 = (beta - 0.5) / se\n    p_05 = 2 * (1 - stats.t.cdf(abs(t_05), df=robust_res.df_resid))\n    print(f\"\\n{name}:\")\n    print(f\"  t-statistic: {t_05:.2f}\")\n    print(f\"  p-value: {p_05:.4f}\")\n    if p_05 < 0.05:\n        print(f\"  Conclusion: Reject H₀. β₂ differs significantly from 0.5\")\n    else:\n        print(f\"  Conclusion: Fail to reject H₀. Data consistent with β₂ = 0.5\")\n\n# Interpretation\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nHigh-income countries: 54\nDeveloping countries: 54\n\nHigh-Income:\n  t-statistic: -20.13\n  p-value: 0.0000\n  Conclusion: Reject H₀. β₂ differs significantly from 0.5\n\nDeveloping:\n  t-statistic: -14.06\n  p-value: 0.0000\n  Conclusion: Reject H₀. β₂ differs significantly from 0.5\n```\n:::\n:::\n\n\n> **Key Concept 7.9: Economic Interpretation of Hypothesis Test Results**\n>\n> Statistical hypothesis tests answer specific questions, but their economic interpretation requires care and context.\n>\n> **Translating statistical results to economic conclusions:**\n>\n> **1. Rejecting H₀: β₂ = 0 (statistical significance)**\n> - Statistical: \"Capital has a statistically significant effect on productivity\"\n> - Economic: \"Countries with more capital per worker tend to have higher productivity, and this pattern is unlikely due to chance alone\"\n> - Limitations: Says nothing about causation, magnitude, or policy relevance\n>\n> **2. Rejecting H₀: β₂ = 0.5 (testing theory predictions)**  \n> - Statistical: \"The coefficient differs significantly from 0.5\"\n> - Economic: \"The marginal product of capital differs from theory's prediction, suggesting other factors (technology, institutions) matter\"\n> - Implications: May indicate model misspecification or heterogeneity across countries\n>\n> **3. Failing to reject H₀ (no statistical significance)**\n> - Statistical: \"Cannot rule out β₂ = 0 (or other null value)\"\n> - Economic: Multiple interpretations possible:\n>   - Effect truly absent\n>   - Effect present but sample too small to detect it (low power)\n>   - High variability obscures the relationship\n> - **Never conclude:** \"Proved β₂ = 0\" or \"No relationship exists\"\n>\n> **4. Heterogeneity across groups**\n> - If β₂(high-income) > β₂(developing): Capital complementary with other factors more abundant in rich countries (technology, institutions, human capital)\n> - If β₂(developing) > β₂(high-income): Diminishing returns to capital more pronounced in capital-abundant countries\n>\n> **Best practices for economic interpretation:**\n> 1. Report point estimates, not just significance\n> 2. Use confidence intervals to show uncertainty\n> 3. Assess economic magnitude (not just statistical significance)\n> 4. Consider alternative explanations and limitations\n> 5. Link findings to economic theory and policy implications\n\n### Task 5: Visual Analysis (Independent)\n\n**Objective:** Create visualizations to communicate your statistical inference results effectively.\n\n**Your tasks (completely open-ended):**\n\na) Create a scatter plot showing the productivity-capital relationship:\n\n   - Include the regression line\n   - Color-code points by income group (high-income vs. developing)\n   - Add 95% confidence bands around the regression line (advanced)\n\nb) Create a coefficient plot comparing:\n\n   - Full sample estimate\n   - High-income group estimate\n   - Developing group estimate\n   - Show 95% confidence intervals as error bars\n\nc) Create a residual plot:\n\n   - Check for heteroskedasticity visually\n   - Does the spread of residuals increase with fitted values?\n\n**Challenge:** Can you create a single figure that tells the complete story of your analysis?\n\n::: {#da7ce2f3 .cell execution_count=23}\n``` {.python .cell-code}\n# Task 5: Your visualizations here\n\n# Figure 1: Scatter plot with regression lines by group\nfig, axes = plt.subplots(1, 2, figsize=(14, 6))\n\n# Left panel: Full sample\nax1 = axes[0]\nax1.scatter(data_2014['capital'], data_2014['productivity'], \n           alpha=0.5, s=40, color='#22d3ee', label='All countries')\nax1.plot(data_2014['capital'], model_convergence.fittedvalues, \n        color='red', linewidth=2, label='Regression line')\nax1.set_xlabel('Capital per Worker ($1000s)')\nax1.set_ylabel('Labor Productivity ($1000s)')\nax1.set_title('Full Sample Regression')\nax1.legend()\nax1.grid(True, alpha=0.3)\n\n# Right panel: By income group\nax2 = axes[1]\nax2.scatter(high_income['capital'], high_income['productivity'],\n           alpha=0.5, s=40, color='green', label='High-income')\nax2.scatter(developing['capital'], developing['productivity'],\n           alpha=0.5, s=40, color='orange', label='Developing')\n# Add regression lines\nhigh_income_sorted = high_income.sort_values('capital')\ndeveloping_sorted = developing.sort_values('capital')\nax2.plot(high_income_sorted['capital'], robust_high.predict(high_income_sorted),\n        color='#4ade80', linewidth=2, linestyle='--', label='High-income fit')\nax2.plot(developing_sorted['capital'], robust_dev.predict(developing_sorted),\n        color='darkorange', linewidth=2, linestyle='--', label='Developing fit')\nax2.set_xlabel('Capital per Worker ($1000s)')\nax2.set_ylabel('Labor Productivity ($1000s)')\nax2.set_title('By Income Group')\nax2.legend()\nax2.grid(True, alpha=0.3)\n\nplt.tight_layout()\nplt.show()\n\n# Figure 2: Coefficient plot with confidence intervals\nfig, ax = plt.subplots(figsize=(10, 6))\n\ngroups = ['Full Sample', 'High-Income', 'Developing']\nestimates = [beta2_robust, robust_high.params['capital'], robust_dev.params['capital']]\nses = [se_beta2_robust, robust_high.bse['capital'], robust_dev.bse['capital']]\ncis_lower = [e - 1.96*se for e, se in zip(estimates, ses)]\ncis_upper = [e + 1.96*se for e, se in zip(estimates, ses)]\n\ny_pos = range(len(groups))\nax.errorbar(estimates, y_pos, \n           xerr=[[e - l for e, l in zip(estimates, cis_lower)],\n                 [u - e for e, u in zip(estimates, cis_upper)]],\n           fmt='o', markersize=10, capsize=8, capthick=2, linewidth=2, color='#22d3ee')\nax.set_yticks(y_pos)\nax.set_yticklabels(groups)\nax.axvline(x=0, color='red', linestyle='--', linewidth=1, alpha=0.5, label='H₀: β₂ = 0')\nax.axvline(x=0.5, color='green', linestyle=':', linewidth=1, alpha=0.5, label='Theory: β₂ = 0.5')\nax.set_xlabel('Estimated Coefficient (β₂) with 95% CI')\nax.set_title('Capital-Productivity Relationship: Point Estimates and Confidence Intervals')\nax.legend()\nax.grid(True, alpha=0.3, axis='x')\nplt.tight_layout()\nplt.show()\n\n# All three estimates are positive and statistically significant\n```\n\n::: {.cell-output .cell-output-display}\n![](ch07_Statistical_Inference_for_Bivariate_Regression_files/figure-html/cell-24-output-1.png){width=1334 height=565}\n:::\n\n::: {.cell-output .cell-output-display}\n![](ch07_Statistical_Inference_for_Bivariate_Regression_files/figure-html/cell-24-output-2.png){width=950 height=565}\n:::\n:::\n\n\n### Task 6: Write a Research Summary (Independent)\n\n**Objective:** Communicate your statistical findings in a clear, professional manner.\n\n**Your task:**  \nWrite a 200-300 word summary of your analysis as if for an economics journal. Your summary should include:\n\n1. **Research question** - What were you investigating?\n2. **Data and methods** - What data did you use? What regressions did you run?\n3. **Key findings** - What did you discover? Report specific numbers (coefficients, CIs, p-values)\n4. **Statistical inference** - Were effects statistically significant? Did you use robust SEs?\n5. **Economic interpretation** - What do the results mean economically?\n6. **Limitations and extensions** - What are the caveats? What should future research explore?\n\n**Grading criteria:**\n\n- Clear and concise writing\n- Appropriate use of statistical terminology\n- Correct interpretation of results\n- Discussion of both statistical and economic significance\n- Professional tone suitable for academic publication\n\n**Example opening:**  \n\"Using cross-sectional data for 108 countries in 2014, I investigate the relationship between labor productivity (GDP per capita) and physical capital per worker. The estimated coefficient of 0.XX (robust SE = 0.YY, p < 0.001) indicates that...\"\n\n*Write your summary in the markdown cell below.*\n\n### Your Research Summary\n\n*(Write your 200-300 word summary here)*\n\n[Your text goes here]\n\n---\n\n### What You've Learned\n\n**Congratulations!** You've completed a comprehensive statistical inference analysis. You practiced:\n\n**Statistical Skills:**\n\n- Estimating bivariate regression models\n- Constructing and interpreting 95% confidence intervals\n- Conducting two-sided hypothesis tests (H₀: β = β*)\n- Conducting one-sided hypothesis tests (directional claims)\n- Using heteroskedasticity-robust standard errors\n- Comparing results across subsamples (heterogeneity analysis)\n- Creating publication-quality visualizations\n- Writing professional research summaries\n\n**Economic Insights:**\n\n- Understanding the productivity-capital relationship across countries\n- Testing economic theory predictions with data\n- Interpreting coefficients in economic terms (marginal products)\n- Recognizing heterogeneity across country income groups\n- Distinguishing statistical from economic significance\n\n**Practical Skills:**\n\n- Using Python for comprehensive econometric analysis\n- Generating robust standard errors with `statsmodels`\n- Creating compelling visualizations with `matplotlib`\n- Communicating statistical results to non-technical audiences\n\n**Next Steps:**\n\n- Chapter 8 will extend these methods to multiple regression\n- You'll learn how to control for confounding variables\n- And test joint hypotheses about multiple coefficients\n\n---\n\n**Key Takeaway:** Statistical inference transforms sample estimates into insights about populations. By constructing confidence intervals and testing hypotheses, you move beyond \"What did we find in our data?\" to \"What can we confidently say about the world?\" This is the foundation of evidence-based economics.\n\n### Case Study 2: Is the Light-Development Relationship Significant?\n\nIn Chapter 1, we introduced the DS4Bolivia project and estimated a simple regression of municipal development (IMDS) on nighttime lights (NTL). In Chapter 5, we explored bivariate relationships in depth. Now we apply Chapter 7's inference tools to test whether the NTL-development relationship is statistically significant and construct confidence intervals for the effect.\n\n**Research Question:** Is the association between nighttime lights and municipal development statistically significant, and how precisely can we estimate the effect?\n\n**Data:** Cross-sectional dataset covering 339 Bolivian municipalities from the [DS4Bolivia Project](https://github.com/quarcs-lab/ds4bolivia).\n\n**Key Variables:**\n\n- `imds`: Municipal Sustainable Development Index (0-100)\n- `ln_NTLpc2017`: Log nighttime lights per capita (2017)\n- `mun`: Municipality name\n- `dep`: Department (administrative region)\n\n#### Load the DS4Bolivia Data\n\nLoad the DS4Bolivia dataset and prepare the regression sample.\n\n::: {#c7b0a6d5 .cell execution_count=24}\n``` {.python .cell-code}\n# Load the DS4Bolivia dataset\nurl_bol = \"https://raw.githubusercontent.com/quarcs-lab/ds4bolivia/master/ds4bolivia_v20250523.csv\"\nbol = pd.read_csv(url_bol)\n\n# Select key variables and prepare regression data\nkey_vars = ['mun', 'dep', 'imds', 'ln_NTLpc2017']\nbol_key = bol[key_vars].copy()\nreg_data = bol_key[['imds', 'ln_NTLpc2017']].dropna()\n\n# DS4Bolivia dataset — regression sample\nprint(f\"Total municipalities: {len(bol_key)}\")\nprint(f\"Complete cases for regression: {len(reg_data)}\")\n\n# Descriptive statistics\nreg_data.describe().round(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTotal municipalities: 339\nComplete cases for regression: 333\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=24}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>imds</th>\n      <th>ln_NTLpc2017</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>333.000</td>\n      <td>333.000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>51.158</td>\n      <td>13.880</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>6.760</td>\n      <td>1.181</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>35.700</td>\n      <td>9.064</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>47.100</td>\n      <td>13.134</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>50.800</td>\n      <td>13.914</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>55.000</td>\n      <td>14.774</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>80.200</td>\n      <td>17.064</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Task 1: Estimate and Test Slope (Guided)\n\n**Objective:** Estimate the OLS regression of IMDS on log NTL per capita and test whether the slope is statistically significant.\n\n**Instructions:**\n\n1. Estimate the regression `imds ~ ln_NTLpc2017` using OLS\n2. Display the full regression summary\n3. Extract the t-statistic and p-value for the slope coefficient\n4. Test the null hypothesis H₀: β₁ = 0 (no linear relationship)\n5. State your conclusion: Can we reject the null at the 5% significance level?\n\n::: {#83710f61 .cell execution_count=25}\n``` {.python .cell-code}\n# Task 1: Estimate OLS and test the slope\n\n# Estimate the model\nmodel = ols('imds ~ ln_NTLpc2017', data=reg_data).fit()\nmodel.summary()\n\n# Extract t-statistic and p-value for the slope\nt_stat = model.tvalues['ln_NTLpc2017']\np_value = model.pvalues['ln_NTLpc2017']\n\n# Hypothesis test: H₀: β₁ = 0\nprint(f\"Slope coefficient: {model.params['ln_NTLpc2017']:.4f}\")\nprint(f\"Standard error:    {model.bse['ln_NTLpc2017']:.4f}\")\nprint(f\"t-statistic:       {t_stat:.4f}\")\nprint(f\"p-value:           {p_value:.6f}\")\nprint(f\"Conclusion: {'Reject' if p_value < 0.05 else 'Fail to reject'} H₀ at the 5% level.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSlope coefficient: 3.3703\nStandard error:    0.2544\nt-statistic:       13.2493\np-value:           0.000000\nConclusion: Reject H₀ at the 5% level.\n```\n:::\n:::\n\n\n### Task 2: Confidence Interval for Slope (Guided)\n\n**Objective:** Construct and interpret a 95% confidence interval for the NTL coefficient.\n\n**Instructions:**\n\n1. Use `model.conf_int()` to obtain the 95% confidence interval\n2. Extract the lower and upper bounds for the slope\n3. Interpret: \"We are 95% confident that a 1-unit increase in log NTL per capita is associated with between X and Y points of IMDS.\"\n4. Does the confidence interval contain zero? What does that tell us?\n\n::: {#3ef89317 .cell execution_count=26}\n``` {.python .cell-code}\n# Task 2: Confidence interval for the slope\n\nci = model.conf_int(alpha=0.05)\nci_lower = ci.loc['ln_NTLpc2017', 0]\nci_upper = ci.loc['ln_NTLpc2017', 1]\n\n# 95% confidence interval for NTL coefficient\nprint(f\"Point estimate:  {model.params['ln_NTLpc2017']:.4f}\")\nprint(f\"95% CI:          [{ci_lower:.4f}, {ci_upper:.4f}]\")\nprint(f\"Does the CI contain zero? {'Yes' if ci_lower <= 0 <= ci_upper else 'No'}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPoint estimate:  3.3703\n95% CI:          [2.8699, 3.8707]\nDoes the CI contain zero? No\n```\n:::\n:::\n\n\n### Task 3: Robust Standard Errors (Semi-guided)\n\n**Objective:** Compare default (homoskedastic) standard errors with heteroskedasticity-robust (HC1) standard errors.\n\n**Instructions:**\n\n1. Re-estimate the model with HC1 robust standard errors using `cov_type='HC1'`\n2. Compare the standard errors, t-statistics, and p-values between the two models\n3. Discuss: Do the robust SEs differ substantially from the default SEs?\n4. Why might robust standard errors matter for municipality-level spatial data?\n\n**Hint:** Use `model_robust = ols('imds ~ ln_NTLpc2017', data=reg_data).fit(cov_type='HC1')`\n\n::: {#45772740 .cell execution_count=27}\n``` {.python .cell-code}\n# Task 3: Robust standard errors\n\n# Re-estimate with HC1 robust standard errors\nmodel_robust = ols('imds ~ ln_NTLpc2017', data=reg_data).fit(cov_type='HC1')\n\n# Compare default vs robust results\n# Comparison: default vs robust standard errors\nprint(f\"{'':30s} {'Default':>12s} {'Robust (HC1)':>12s}\")\nprint(f\"{'Slope coefficient':30s} {model.params['ln_NTLpc2017']:12.4f} {model_robust.params['ln_NTLpc2017']:12.4f}\")\nprint(f\"{'Standard error':30s} {model.bse['ln_NTLpc2017']:12.4f} {model_robust.bse['ln_NTLpc2017']:12.4f}\")\nprint(f\"{'t-statistic':30s} {model.tvalues['ln_NTLpc2017']:12.4f} {model_robust.tvalues['ln_NTLpc2017']:12.4f}\")\nprint(f\"{'p-value':30s} {model.pvalues['ln_NTLpc2017']:12.6f} {model_robust.pvalues['ln_NTLpc2017']:12.6f}\")\nprint(f\"SE ratio (robust/default): {model_robust.bse['ln_NTLpc2017'] / model.bse['ln_NTLpc2017']:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                    Default Robust (HC1)\nSlope coefficient                    3.3703       3.3703\nStandard error                       0.2544       0.2990\nt-statistic                         13.2493      11.2731\np-value                            0.000000     0.000000\nSE ratio (robust/default): 1.175\n```\n:::\n:::\n\n\n> **Key Concept 7.12: Robust Inference with Spatial Data**\n>\n> Municipality-level data often exhibits **heteroskedasticity**: the variance of development outcomes may differ between urban areas (where IMDS is tightly clustered around high values) and rural areas (where IMDS varies widely). Heteroskedasticity-robust standard errors (HC1) provide valid inference without assuming constant variance. When standard and robust SEs differ substantially, this signals heteroskedasticity in the data.\n\n### Task 4: Two-Sided Hypothesis Test (Semi-guided)\n\n**Objective:** Test whether the NTL coefficient equals a specific hypothesized value.\n\n**Instructions:**\n\n1. Test H₀: β₁ = 5 (a specific hypothesized effect size)\n2. Calculate the t-statistic manually: t = (β̂₁ − 5) / SE(β̂₁)\n3. Compute the two-sided p-value using `scipy.stats.t.sf()`\n4. Can we reject that the true effect equals exactly 5?\n\n**Hint:** Use robust standard errors for this test. The degrees of freedom are `model_robust.df_resid`.\n\n::: {#9708db3a .cell execution_count=28}\n``` {.python .cell-code}\n# Task 4: Two-sided hypothesis test for H0: beta_1 = 5\nfrom scipy import stats\n\n# Hypothesized value\nbeta_0_hyp = 5\n\n# Calculate t-statistic manually\nbeta_hat = model_robust.params['ln_NTLpc2017']\nse_robust = model_robust.bse['ln_NTLpc2017']\ndf = model_robust.df_resid\n\nt_manual = (beta_hat - beta_0_hyp) / se_robust\np_two_sided = 2 * stats.t.sf(abs(t_manual), df=df)\n\n# Hypothesis test: H₀: β₁ = beta_0_hyp\nprint(f\"Estimated slope:   {beta_hat:.4f}\")\nprint(f\"Hypothesized value: {beta_0_hyp}\")\nprint(f\"Robust SE:          {se_robust:.4f}\")\nprint(f\"t-statistic:        {t_manual:.4f}\")\nprint(f\"Degrees of freedom: {df}\")\nprint(f\"Two-sided p-value:  {p_two_sided:.6f}\")\nprint(f\"Conclusion: {'Reject' if p_two_sided < 0.05 else 'Fail to reject'} H₀ at the 5% level.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEstimated slope:   3.3703\nHypothesized value: 5\nRobust SE:          0.2990\nt-statistic:        -5.4509\nDegrees of freedom: 331.0\nTwo-sided p-value:  0.000000\nConclusion: Reject H₀ at the 5% level.\n```\n:::\n:::\n\n\n### Task 5: One-Sided Test (Independent)\n\n**Objective:** Test whether the NTL coefficient is positive (NTL has a positive effect on development).\n\n**Instructions:**\n\n1. State the hypotheses: H₀: β₁ ≤ 0 vs H₁: β₁ > 0\n2. Calculate the one-sided p-value from the t-statistic\n3. Use robust standard errors\n4. Discuss: Is there strong evidence for a positive relationship between nighttime lights and development?\n\n**Hint:** For a right-sided test, the one-sided p-value is `stats.t.sf(t_stat, df=df)`.\n\n::: {#91390747 .cell execution_count=29}\n``` {.python .cell-code}\n# Task 5: One-sided test — H0: beta_1 <= 0 vs H1: beta_1 > 0\n\n# t-statistic for H0: beta_1 = 0 using robust SEs\nt_onesided = model_robust.tvalues['ln_NTLpc2017']\np_onesided = stats.t.sf(t_onesided, df=model_robust.df_resid)\n\n# One-sided test: H₀: β₁ ≤ 0 vs H₁: β₁ > 0\nprint(f\"Estimated slope:     {model_robust.params['ln_NTLpc2017']:.4f}\")\nprint(f\"Robust SE:           {model_robust.bse['ln_NTLpc2017']:.4f}\")\nprint(f\"t-statistic:         {t_onesided:.4f}\")\nprint(f\"One-sided p-value:   {p_onesided:.8f}\")\nprint(f\"\\nConclusion: {'Reject' if p_onesided < 0.05 else 'Fail to reject'} H₀ at the 5% level.\")\nprint(f\"There {'is' if p_onesided < 0.05 else 'is not'} strong evidence for a positive NTL-development relationship.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEstimated slope:     3.3703\nRobust SE:           0.2990\nt-statistic:         11.2731\nOne-sided p-value:   0.00000000\n\nConclusion: Reject H₀ at the 5% level.\nThere is strong evidence for a positive NTL-development relationship.\n```\n:::\n:::\n\n\n> **Key Concept 7.13: Practical Significance in Development**\n>\n> A statistically significant regression coefficient must be evaluated for **practical significance**. In the DS4Bolivia context, the NTL coefficient tells us how much IMDS changes for a 1-unit increase in log NTL per capita. Since IMDS ranges from roughly 20 to 80, an effect of, say, 5 points represents about 8% of the total range—a meaningful but not transformative association. Policy decisions should weigh both statistical confidence and effect magnitude.\n\n### Task 6: Economic vs Statistical Significance (Independent)\n\n**Objective:** Write a 200-300 word discussion evaluating both the statistical and practical significance of the NTL-development relationship.\n\n**Your discussion should address:**\n\n1. **Statistical significance:** Summarize the hypothesis test results. Is the coefficient significant at the 1%, 5%, and 10% levels?\n2. **Effect magnitude:** A 1-unit change in log NTL per capita corresponds to roughly a 172% increase in NTL per capita (since exp(1) ≈ 2.72). What does the estimated coefficient imply for development?\n3. **Scale context:** Compare the effect magnitude with the full range of IMDS across municipalities. Is the effect large or small in practical terms?\n4. **Policy implications:** If a policy could double NTL per capita in a municipality (a 0.69 increase in log NTL), how much IMDS improvement would we predict? Is that meaningful for SDG progress?\n5. **Limitations:** Does statistical significance prove causation? What omitted variables could confound this relationship?\n\n::: {#f9e2cef1 .cell execution_count=30}\n``` {.python .cell-code}\n# Task 6: Supporting analysis for economic vs statistical significance\n\n# Summary statistics for context\nimds_range = reg_data['imds'].max() - reg_data['imds'].min()\nimds_std = reg_data['imds'].std()\nbeta = model_robust.params['ln_NTLpc2017']\n\n# Economic vs statistical significance — key facts\nprint(f\"\\nEstimated slope (robust): {beta:.4f}\")\nprint(f\"Robust p-value:           {model_robust.pvalues['ln_NTLpc2017']:.6f}\")\nprint(f\"\\nIMDS range:     {reg_data['imds'].min():.1f} to {reg_data['imds'].max():.1f} (range = {imds_range:.1f})\")\nprint(f\"IMDS std dev:   {imds_std:.2f}\")\nprint(f\"\\nEffect of 1-unit increase in log NTL:\")\nprint(f\"  IMDS change:           {beta:.2f} points\")\nprint(f\"  As % of IMDS range:    {100 * beta / imds_range:.1f}%\")\nprint(f\"  As % of IMDS std dev:  {100 * beta / imds_std:.1f}%\")\nprint(f\"\\nEffect of doubling NTL per capita (0.693 increase in log NTL):\")\nprint(f\"  Predicted IMDS change: {beta * 0.693:.2f} points\")\nprint(f\"  As % of IMDS range:    {100 * beta * 0.693 / imds_range:.1f}%\")\nprint(f\"\\nR-squared: {model.rsquared:.4f}\")\nprint(f\"NTL explains {model.rsquared * 100:.1f}% of variation in IMDS across municipalities.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nEstimated slope (robust): 3.3703\nRobust p-value:           0.000000\n\nIMDS range:     35.7 to 80.2 (range = 44.5)\nIMDS std dev:   6.76\n\nEffect of 1-unit increase in log NTL:\n  IMDS change:           3.37 points\n  As % of IMDS range:    7.6%\n  As % of IMDS std dev:  49.9%\n\nEffect of doubling NTL per capita (0.693 increase in log NTL):\n  Predicted IMDS change: 2.34 points\n  As % of IMDS range:    5.2%\n\nR-squared: 0.3466\nNTL explains 34.7% of variation in IMDS across municipalities.\n```\n:::\n:::\n\n\n### What You've Learned\n\nThrough this case study on statistical inference for the NTL-development relationship in Bolivia, you practiced:\n\n**Statistical Inference Skills:**\n\n- Estimating OLS regression and extracting test statistics\n- Constructing and interpreting 95% confidence intervals\n- Computing heteroskedasticity-robust standard errors (HC1)\n- Conducting two-sided hypothesis tests for specific values\n- Conducting one-sided hypothesis tests for directional claims\n\n**Economic Reasoning Skills:**\n\n- Distinguishing statistical significance from practical significance\n- Evaluating effect magnitudes in the context of policy-relevant scales\n- Recognizing the role of heteroskedasticity in spatial economic data\n\n**Connection to Future Chapters:**\nIn Chapters 10-12, we extend this analysis to *multiple regression*—adding satellite embeddings alongside NTL to improve predictive power and test which features matter.\n\n---\n\n**Well done!** You've now applied the full toolkit of regression inference—hypothesis tests, confidence intervals, robust standard errors, and significance evaluation—to real-world satellite development data.\n\n",
    "supporting": [
      "ch07_Statistical_Inference_for_Bivariate_Regression_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}